### ISSUE TITLE
Compiling test_tpm2_session.c with scan-build causes the test to fail

### ISSUE THREAD

**Issue by danintel** [tpm2-software/tpm2-tools#1004]
Compiling test_tpm2_session.c with scan-build causes the test to fail.
There are gcc/clang compiler warnings issued, but they are from the compiler, not scan-build.

To reproduce:
```
scan-build ./configure
scan-build --status-bugs make
```
Run test_tpm2_session

References:
scan-build makes Travis CI die #996
restore scan-build #999

**Comment by williamcroberts** [comment]
Seems fixed awhile ago
