### ISSUE TITLE
VMWare Fusion Virtual TPM: Tss2_Sys_GetCapability(0x80011) - sys:Response is malformed

### ISSUE THREAD

**Issue by blaufish** [tpm2-software/tpm2-tools#1021]
Installation appears sound:
* tpm-server + tpm2-abrmd + tpm2_pcrlist test OK, no errors. 
* `./configure --enable-unit --with-simulatorbin=/home/vmware-tpm/ibmtpm974/src/tpm_server` and  `make check make check` test OK, no errors.

Very old versions of TPM tools, those shipped with Ubuntu16, worked with VMWare Fushion virtual TPM. But when building from git heads, tpm2_pcrlist fails with **Tss2_Sys_GetCapability(0x80011) - sys:Response is malformed** . (Unclear if this is a VMWare problem or tpm2-tools / tpm2-tss problem)

tpm2 tools fails against the virtual TPM still, the response failing un-marshalling is:
```
debug:tcti:src/tss2-tcti/tcti-device.c:183:tcti_device_receive() Response Received (size=43): 
	80010000002b0000
	0000000000000500
	000004000403ffff
	ff000b03ffffff00
	0c03ffffff000d03
	ffffff 
```

From:
```
sudo -u tss TSS2_LOG=all+TRACE tpm2_pcrlist -T device
trace:marshal:src/tss2-mu/base-types.c:196:Tss2_MU_TPM2_ST_Marshal() offset non-NULL, initial value: 0 
debug:marshal:src/tss2-mu/base-types.c:196:Tss2_MU_TPM2_ST_Marshal() Marshalling TPM2_ST from 0x7ffd8a621f6c to buffer 0x557f7c628a88 at index 0x0 
debug:marshal:src/tss2-mu/base-types.c:196:Tss2_MU_TPM2_ST_Marshal() offset parameter non-NULL, updated to 2 
trace:marshal:src/tss2-mu/base-types.c:190:Tss2_MU_UINT32_Marshal() offset non-NULL, initial value: 10 
debug:marshal:src/tss2-mu/base-types.c:190:Tss2_MU_UINT32_Marshal() Marshalling UINT32 from 0x7ffd8a621fdc to buffer 0x557f7c628a88 at index 0xa 
debug:marshal:src/tss2-mu/base-types.c:190:Tss2_MU_UINT32_Marshal() offset parameter non-NULL, updated to 14 
trace:marshal:src/tss2-mu/base-types.c:190:Tss2_MU_UINT32_Marshal() offset non-NULL, initial value: 14 
debug:marshal:src/tss2-mu/base-types.c:190:Tss2_MU_UINT32_Marshal() Marshalling UINT32 from 0x7ffd8a621fdc to buffer 0x557f7c628a88 at index 0xe 
debug:marshal:src/tss2-mu/base-types.c:190:Tss2_MU_UINT32_Marshal() offset parameter non-NULL, updated to 18 
trace:marshal:src/tss2-mu/base-types.c:190:Tss2_MU_UINT32_Marshal() offset non-NULL, initial value: 18 
debug:marshal:src/tss2-mu/base-types.c:190:Tss2_MU_UINT32_Marshal() Marshalling UINT32 from 0x7ffd8a621fdc to buffer 0x557f7c628a88 at index 0x12 
debug:marshal:src/tss2-mu/base-types.c:190:Tss2_MU_UINT32_Marshal() offset parameter non-NULL, updated to 22 
debug:tcti:src/tss2-tcti/tcti-device.c:97:tcti_device_transmit() sending 22 byte command buffer: (size=22): 
	8001000000160000
	017a000000050000
	000000000001 
debug:tcti:src/util/io.c:94:write_all() writing 22 bytes starting at 0x557f7c628a88 to fd 3 
debug:tcti:src/util/io.c:99:write_all() wrote 22 bytes to fd 3 
debug:tcti:src/tss2-tcti/tcti-device.c:183:tcti_device_receive() Response Received (size=43): 
	80010000002b0000
	0000000000000500
	000004000403ffff
	ff000b03ffffff00
	0c03ffffff000d03
	ffffff 
trace:tcti:src/tss2-tcti/tcti-common.c:123:header_unmarshal() Parsing header from buffer: 0x557f7c628a88 
trace:marshal:src/tss2-mu/base-types.c:197:Tss2_MU_TPM2_ST_Unmarshal() offset non-NULL, initial value: 0 
debug:marshal:src/tss2-mu/base-types.c:197:Tss2_MU_TPM2_ST_Unmarshal() Unmarshaling TPM2_ST from 0x557f7c628a88 to buffer 0x557f7c61cefc at index 0x0 
debug:marshal:src/tss2-mu/base-types.c:197:Tss2_MU_TPM2_ST_Unmarshal() offset parameter non-NULL, updated to 2 
trace:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() offset non-NULL, initial value: 2 
debug:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() Unmarshaling UINT32 from 0x557f7c628a88 to buffer 0x557f7c61cf00 at index 0x2 
debug:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() offset parameter non-NULL, updated to 6 
trace:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() offset non-NULL, initial value: 6 
debug:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() Unmarshaling UINT32 from 0x557f7c628a88 to buffer 0x557f7c61cf04 at index 0x6 
debug:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() offset parameter non-NULL, updated to 10 
trace:marshal:src/tss2-mu/base-types.c:197:Tss2_MU_TPM2_ST_Unmarshal() offset non-NULL, initial value: 0 
debug:marshal:src/tss2-mu/base-types.c:197:Tss2_MU_TPM2_ST_Unmarshal() Unmarshaling TPM2_ST from 0x557f7c628a88 to buffer 0x557f7c628a54 at index 0x0 
debug:marshal:src/tss2-mu/base-types.c:197:Tss2_MU_TPM2_ST_Unmarshal() offset parameter non-NULL, updated to 2 
trace:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() offset non-NULL, initial value: 2 
debug:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() Unmarshaling UINT32 from 0x557f7c628a88 to buffer 0x557f7c628a56 at index 0x2 
debug:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() offset parameter non-NULL, updated to 6 
trace:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() offset non-NULL, initial value: 6 
debug:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() Unmarshaling UINT32 from 0x557f7c628a88 to buffer 0x557f7c628a5a at index 0x6 
debug:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() offset parameter non-NULL, updated to 10 
trace:marshal:src/tss2-mu/base-types.c:197:Tss2_MU_TPM2_ST_Unmarshal() offset non-NULL, initial value: 0 
debug:marshal:src/tss2-mu/base-types.c:197:Tss2_MU_TPM2_ST_Unmarshal() Unmarshaling TPM2_ST from 0x557f7c628a88 to buffer 0x7ffd8a62203e at index 0x0 
debug:marshal:src/tss2-mu/base-types.c:197:Tss2_MU_TPM2_ST_Unmarshal() offset parameter non-NULL, updated to 2 
trace:marshal:src/tss2-mu/base-types.c:187:Tss2_MU_UINT8_Unmarshal() offset non-NULL, initial value: 10 
debug:marshal:src/tss2-mu/base-types.c:187:Tss2_MU_UINT8_Unmarshal() Unmarshaling UINT8 from 0x557f7c628a88 to buffer 0x7ffd8a6220b7 at index 0xa 
debug:marshal:src/tss2-mu/base-types.c:187:Tss2_MU_UINT8_Unmarshal() offset parameter non-NULL, updated to 11 
debug:marshal:src/tss2-mu/tpms-types.c:1278:Tss2_MU_TPMS_CAPABILITY_DATA_Unmarshal() Unmarshaling TPMS_CAPABILITY_DATA from 0x557f7bbb62f4 to buffer 0x557f7c628a88 at index 0xb 
trace:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() offset non-NULL, initial value: 11 
debug:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() Unmarshaling UINT32 from 0x557f7c628a88 to buffer 0x557f7bbb62f4 at index 0xb 
debug:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() offset parameter non-NULL, updated to 15 
trace:marshal:src/tss2-mu/tpml-types.c:197:Tss2_MU_TPML_PCR_SELECTION_Unmarshal() offset non-NULL, initial value: 15 
debug:marshal:src/tss2-mu/tpml-types.c:197:Tss2_MU_TPML_PCR_SELECTION_Unmarshal() Unmarshaling TPML_PCR_SELECTION from 0x557f7c628a88 to buffer 0x557f7bbb62f8 at index 0xf 
trace:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() offset non-NULL, initial value: 15 
debug:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() Unmarshaling UINT32 from 0x557f7c628a88 to buffer 0x7ffd8a621bfc at index 0xf 
debug:marshal:src/tss2-mu/base-types.c:191:Tss2_MU_UINT32_Unmarshal() offset parameter non-NULL, updated to 19 
WARNING:marshal:src/tss2-mu/tpml-types.c:197:Tss2_MU_TPML_PCR_SELECTION_Unmarshal() count too big 
ERROR: Tss2_Sys_GetCapability(0x80011) - sys:Response is malformed
ERROR: Unable to run tpm2_pcrlist
```

**Comment by williamcroberts** [comment]
The reason it worked on old versions is probably from the lack of running get capability. With that said, the errors listed are on the response from the tpm in libmu which is in the TSS.

**Comment by flihp** [comment]
sorry @williamcroberts, this started over in the tabrmd issue tracker and I bounced @blaufish over to the tools since it wasn't the tabrmd failing. Still you're right, libtss2-mu code is what's choking on that buffer. Debugging will probably require someone unpack the buffer:
```
        80010000002b0000
	0000000000000500
	000004000403ffff
	ff000b03ffffff00
	0c03ffffff000d03
	ffffff
```
manually to see why libtss2-mu is refusing to unmarshal it. This is a pretty simple call to GetCapability since `tpm2_pcrlist` is just trying to get data about the PCRs on the TPM2.

**Comment by upxe** [comment]
VMware Fusion's virtual TPM has four PCR banks (SHA-{1, 256, 384, 512}).
tpm2-tss/include/tss2/tss2_tpm2_types.h has:

```c
#define TPM2_NUM_PCR_BANKS      3
```
This causes the `Tss2_MU_TPML_PCR_SELECTION_Unmarshal() count too big` error when comparing the rx'd value with the size of the output struct member.

Setting that to 16 then recompiling tpm2-tss and tpm2-tools (not currently using tpm2-abrmd) lets me dump the PCRs. I haven't tested anything else yet.

FWIW, my manual parsing of the response, from a position of near-total ignorance of the marshaling format, is:

```
offset
0x00   8001  tag = TPM_NO_SESSIONS
0x02   0000002b  responseSize
0x06   00000000  responseCode = TPM2_RC_SUCCESS
0x0a   00        moreData = TPM2_NO
       TPMS_CAPABILITY_DATA => TPML_PCR_SELECTION as capabilityData
0x0b   00000005  capability TPM_CAP = TPM2_CAP_PCRS; rest is capabilityData:
0x0f   00000004  count (of TPMS_PCR_SELECTION instances)
0x13   0004      hash = TPM2_ALG_SHA
       03        sizeofSelect
       ffffff    bitmap of selected PCR
       000b      hash = TPM2_ALG_SHA256
       03        sizeofSelect
       ffffff
       000c      hash = TPM2_ALG_SHA384
       03        sizeofSelect
       ffffff
       000d      hash = TPM2_ALG_SHA512
       03        sizeofSelect
       ffffff
```

count of TPMS_PCR_SELECTION instances is the field in question.

**Comment by williamcroberts** [comment]
> VMware Fusion's virtual TPM has four PCR banks (SHA-{1, 256, 384, 512}).
> tpm2-tss/include/tss2/tss2_tpm2_types.h has:
> 
> #define TPM2_NUM_PCR_BANKS      3
> 

I can't find that define in the SPEC at all, seems to be out-of-spec.

> This causes the Tss2_MU_TPML_PCR_SELECTION_Unmarshal() count too big
> error when comparing the rx'd value with the size of the output struct member.
> 
> Setting that to 16 then recompiling tpm2-tss and tpm2-tools (not currently using
> tpm2-abrmd) lets me dump the PCRs. I haven't tested anything else yet.

Have you filed a bug with the tpm2-tss project? This might be in their side of the house.

> 
> FWIW, my manual parsing of the response, from a position of near-total
> ignorance of the marshaling format, is:
> 
> offset
> 0x00   8001  tag = TPM_NO_SESSIONS
> 0x02   0000002b  responseSize
> 0x06   00000000  responseCode = TPM2_RC_SUCCESS
> 0x0a   00        moreData = TPM2_NO
>        TPMS_CAPABILITY_DATA => TPML_PCR_SELECTION as capabilityData
> 0x0b   00000005  capability TPM_CAP = TPM2_CAP_PCRS; rest is capabilityData:
> 0x0f   00000004  count (of TPMS_PCR_SELECTION instances)
> 0x13   0004      hash = TPM2_ALG_SHA
>        03        sizeofSelect
>        ffffff    bitmap of selected PCR
>        000b      hash = TPM2_ALG_SHA256
>        03        sizeofSelect
>        ffffff
>        000c      hash = TPM2_ALG_SHA384
>        03        sizeofSelect
>        ffffff
>        000d      hash = TPM2_ALG_SHA512
>        03        sizeofSelect
>        ffffff
> 
> 
> count of TPMS_PCR_SELECTION instances is the field in question.

Yeah @tstruk this is his side of the house, he wrote libmu.

**Comment by danintel** [comment]
See also #1036. It seems like this is a genuine bug when the SHA-512 bank is available.

**Comment by ricardoas** [comment]
Hi, as I said on the [mailing list](https://lists.01.org/pipermail/tpm2/2018-May/000696.html), I saw this error when running with https://github.com/stefanberger/swtpm simulator after SHA-512 has been enabled on https://github.com/stefanberger/libtpms.

I'll try to compile changing `TPM2_NUM_PCR_BANKS` too and see what happens...

**Comment by ricardoas** [comment]
Hi @danintel,
Setting `TPM2_NUM_PCR_BANKS` to 16 as @upxe did above made tpm2_pcrlist work as expected with SHA-1, SHA-256, SHA-384 and SHA-512 PCR banks.

**Comment by tstruk** [comment]
Looks like the TPM2_NUM_PCR_BANKS==3 was chosen based on the number of hashes enabled at the time when SHA512 was actually disabled.
Ideally this should be derived from the number of hashes enabled, but setting it to 4 for now should fix the problem. I'll create an issue for it in TSS.

**Comment by AndreasFuchsSIT** [comment]
Thing is: The TSS (as per specification) only supports TPMs with up to 3 simultaniously enabled PCR banks.
That seemed to be a reasonable upper bound.

IMHO enabling more than 3 hash algorithms does not make too much sense and is a bad choice...

**Comment by flihp** [comment]
We need to have this conversation with those enabling more than 3 PCR banks. Given the conditions at the time, 3 seemed reasonable, or rather enabling more than 3 seemed unreasonable due to the constraints in play (generally space in a discrete TPM2). VMWare and some of the other implementations in software don't seem to be playing by these rules.

**Comment by williamcroberts** [comment]
It looks like this is going to by bumped from 3 to 16 in the TSS. This isn't a bug in the tools, so I am closing it. Feel free to open a feature request against TSS if one doesn't exist.
