### ISSUE TITLE
Move ContextLoad from tpm2_session_save to tpm2_session_restore

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tools#1025]
This came up in debugging: https://github.com/tpm2-software/tpm2-abrmd/issues/317

The logic in `tpm2_session_save` called both `ContextSave` and `ContextLoad` in an attempt to get the session to extend across tool invocation. The tool saving the session context is how the tabrmd knows to not flush the context when the tool terminates its connection but when the tool loads it again the tabrmd takes over managing the context and will flush it. Instead the tool should only save the context. This lets the tabrmd know that it should not flush the context when the tool terminates / disconnects. When the next tool comes along it takes over the session by `ContextLoad`ing it again.

Requiring a tool to save the context, and another tool to load it provides us with a simple access control mechanism: a tool must be in possession of the file containing the context blob in order to take over the session. This keeps us from having to create our own access control mechanism and instead we can use whatever mechanisms the platform has to do access control (standard file permissions, SELinux etc)

**Comment by flihp** [comment]
also related to #887

**Comment by williamcroberts** [comment]
fixed: in aforementioned PRs
