### ISSUE TITLE
audit manpages to tools

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1042]

**Comment by joshuagl** [comment]
- ensure manpage formatting is consistent
  - consistent whitespace use (blank line after option name before description?)
  - use of quotation marks around section names
  - consistent formatting of options i.e. code formatting or bold formatting?

**Comment by joholl** [comment]
From #1557: don't forget to update the wiki pages.

**Comment by williamcroberts** [comment]
General:
 - [ ] remove dates from all man pages

- tpm2_activatecredential:
  - [ ] -E becomes -e
  - [ ] -P becomes -p to match the lowercase object -c option.
  - [ ] - full end to end example

- tpm2_certify:
  - [ ] - -C and -c should be reversed since the signing key has authority over the certifying key.
  - [ ] -P and -p flipped with -C and -c.
  - [ ] -s --sig-file to --signature
  - [ ] --out-attest-file to --attestation
  - [ ] update examples

- tpm2_checkqoute:
  - [ ] is pcrs_from_file() routine a helper, if so use the helper. Perhaps coalesce with other tools that use -F.
  - [ ] stdout outputs don't make sense, remove them.

- tpm2_clear:
  - [ ] - -L becomes an argument
  - [ ] -p becomes -c and uses the load object interface directly with the user value. Keep default the same.

- tpm2_clearcontrol:
  - a becomes -c because thats the object being worked on.

- tpm2_create:
 - [ ] - example incomplete needs a createprimary call.
