### ISSUE TITLE
3.1 release activities

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1047]
- [x] Fix coverity_scan
- [x] Fix coverity_issues
- [x] Set CI version to TSS 2.0
- [x] Verify abrmd version to use in CI
- [x] cut RCs
- [x] Release 3.1
- [x] Update version matrix

**Comment by joshuagl** [comment]
Proposed changes to fix coverity_scan at https://github.com/tpm2-software/tpm2-tools/pull/1054
I've pushed this change (slightly different commit message) to the coverity_scan branch and we happily have 0 new defects since the last scan.

**Comment by joshuagl** [comment]
Coverity issues addressed in #1059

**Comment by joshuagl** [comment]
[3.1.0-rc0](https://github.com/tpm2-software/tpm2-tools/releases/tag/3.1.0-rc0) has been cut.

**Comment by williamcroberts** [comment]
@joshuagl can you update the version matrix, or are we stuck behind abrmd on that one?

**Comment by joshuagl** [comment]
Version matrix updated, closing this issue.
