### ISSUE TITLE
tpm2_create fails with VMWare Workstation 14.2

### ISSUE THREAD

**Issue by cmouse** [tpm2-software/tpm2-tools#1048]
I am using VMWare Workstation 14.2 TPM feature, but cannot use tpm2_create to create object. I have now attempted this about 10 times, each time removing the TPM2 device and then adding it back, then following the steps outlined here.

Steps to reproduce:
```
# tpm2_takeownership -o str:12345678 -l str:12345678 -e str:12345678 -T abrmd
# tpm2_createprimary -P str:12345678 -H o -g sha256 -G ecc -C po.ctx -T abrmd -P str:12345678
ObjectAttribute: 0x00030072

CreatePrimary Succeed! Handle: 0x800000ff

# tpm2_create -P str:12345678 -g sha256 -G ecc -u key.pub -r key.priv -c po.ctx -T abrmd
ERROR:
Create Object Failed ! ErrorCode: 0x98e

# tpm2_rc_decode 0x98e
error layer
  hex: 0x0
  identifier: TSS2_TPM_ERROR_LEVEL
  description: Error produced by the TPM
format 1 error code
  hex: 0x0e
  identifier: TPM_RC_AUTH_FAIL
  description: the authorization HMAC check failed and DA counter incremented
session
  hex: 0x100
  identifier: TPM_RC_1
  description:  (null)
```

tool="tpm2_create" version="3.0.1" tctis="tarmd,socket,device,"
OS: CentOS 7.5
TPM: VMWare Workstation 14.2
Kernel: 3.10.0-862.3.2.el7.x86_64

**Comment by williamcroberts** [comment]
In tpm2_createprimary, you specify the `-P` option twice, which is only setting the password to use for authorization against the parent hierarchy, in this case the owner hierarchy. The command defaults to an empty key. I think your second -P needs to be a `-K`. Also, you don't need the prefix `str:`. That is the default.

Try:
```
tpm2_createprimary -P 12345678 -H o -g sha256 -G ecc -C po.ctx -T abrmd -K 12345678
tpm2_create -P str:12345678 -g sha256 -G ecc -u key.pub -r key.priv -c po.ctx -T abrmd

```

**Comment by williamcroberts** [comment]
FYI this is more of a support question, please use the mailing list referenced in the README.

**Comment by cmouse** [comment]
The manual is rather difficult to follow on this, and I was genuinely under the impression that this was a bug. But thank you for your help.
