### ISSUE TITLE
dlopen()'ing raw .so files considered bad

### ISSUE THREAD

**Issue by twoerner** [tpm2-software/tpm2-tools#1057]
I've built the latest tpm2 software:
- tpm2-tss @ https://github.com/tpm2-software/tpm2-tss/commit/fafc92108e40374457d4de144d2b6a4b7735c6ed
- tpm2-abrmd @ https://github.com/tpm2-software/tpm2-abrmd/commit/7285806ad83a8b5bc0bdd8a3fef1e7cc0882ddf1
- tpm2-tools @ https://github.com/tpm2-software/tpm2-tools/commit/6b257d1e63d4d32999d4af23d3dc4dc5d887fd77

and I'm still seeing:

        root@raspberrypi3:~# tpm2_pcrlist -v
        tool="tpm2_pcrlist" version="3.0.2-535-g6b257d1" tctis="dynamic" tcti-default=tabrmd dlclose=enabled

        root@raspberrypi3:~# tpm2_pcrlist   
        ERROR: Could not dlopen library: "libtss2-tcti-tabrmd.so"
        ERROR: Could not load tcti, got: "tabrmd"

        root@raspberrypi3:~# tpm2_pcrlist -T device:/dev/tpm0
        ERROR: Could not dlopen library: "libtss2-tcti-device.so"
        ERROR: Could not load tcti, got: "device"

From what I can tell, patches were added to tpm2-abrmd and tpm2-tools to support `dlopen()`'ing versioned `*.so` files (i.e. `*.so.0`), maybe something was missed or needs to be added so the entire TPM2 stack supports it?

**Comment by twoerner** [comment]
Please see https://lists.01.org/pipermail/tpm2/2018-May/000700.html for more details.

**Comment by flihp** [comment]
Hi @twoerner. Are you seeing the same issue with tabrmd? The 1 line change there:
https://github.com/tpm2-software/tpm2-abrmd/commit/d2f0b2d1f0f25f1ef466c88484160ed8edc975f6
was identical to the change made in the tools by @williamcroberts here:
https://github.com/tpm2-software/tpm2-tools/commit/e1fc8d4dda9ee6e64884e475bb4f3401d127c91d

According to the hash you've provided for the tools repo you're using e1fc8d4dd should be in your tree so maybe just the error messages haven't been updated?

**Comment by williamcroberts** [comment]
@twoerner I see the problem:
I updated it here:
https://github.com/tpm2-software/tpm2-tools/blob/master/lib/tpm2_tcti_ldr.c#L58

But not here:
https://github.com/tpm2-software/tpm2-tools/blob/master/lib/tpm2_tcti_ldr.c#L85

Looks like I need to do that, and potentially refactor that into a common routine.

**Comment by twoerner** [comment]
I tested all the components' master branches last night

- https://github.com/tpm2-software/tpm2-abrmd/commit/c90cd599bbde05514a6396ad25c47aec74bbd70a
- https://github.com/tpm2-software/tpm2-tss/commit/847234899fa6522bd96376f0e2e7ad906b283ef1
- https://github.com/tpm2-software/tpm2-tools/commit/e25e9ee704d293fd3f1ad58004f3a3a3136cc97a

and everything is working great!! Thanks so much everyone :-)
