### ISSUE TITLE
TPM2_Create: Cannot specify -G and -I together.

### ISSUE THREAD

**Issue by acmer29** [tpm2-software/tpm2-tools#1080]
Hi, I pulled the new master branch and find tpm2_create cannot use and throw out the error "Cannot specify -G and -I together".

The error does not occur in previous version, it is due to some modification under progress?

**Comment by fidget324** [comment]
In the given documentation, it is also unclear how to specify the key handle. And it is unclear how to specify an authorization value for the created object.

**Comment by joshuagl** [comment]
**-G** and **-I** became mutually exclusive a few days ago in [63bf577](https://github.com/tpm2-software/tpm2-tools/commit/63bf577935b3812dbea0c5f0637234d37ebba90e) with the manual page updated to say:

> "When sealing data only the _TPM_ALG_KEYEDHASH_ algorithm with a NULL scheme is allowed. Thus, **-G** cannot be specified."

We're trying to improve the interface for the tools ahead of the next major release, this includes things like: reducing the number of options, using sane defaults for options where appropriate, making short options and the arguments they take more consistent across tools (particularly those of the same "type"). We're aware that we need to work on the documentation. @williamcroberts recently wrote a tutorial [Creating Objects](https://github.com/tpm2-software/tpm2-tools/wiki/Creating-Objects) which covers the basics of `tpm2_create` and co, please let us know if that helps and what other clarifications we could make to the docs in this area.

**Comment by acmer29** [comment]
Thanks for your reply. My understanding is if **-I** is specified, key algorithm will be keyedhash only. Actually we do specified **-G** to be keyedhash, so they should not cause conflict at all... Will key algorithm be set equals to keyedhash by default if I specified **-I** in the future release?

**Comment by joshuagl** [comment]
That's correct, if **-I** is specified only the `TPM_ALG_KEYEDHASH` algorithm is allowed, therefore it seemed sensible to default to the only supported option (rather than having the user explicitly specify the only supported option). Further we made the options conflict in an attempt to prevent users specifying an algorithm which can't be supported. 

Explicitly, if **-I** is specified the key algorithm defaults to keyedhash.

**Comment by williamcroberts** [comment]
Looks like your questions were answered. Hopefully algorithm support is simpler and more robust now. We also started a tutorial section on this, here: https://github.com/tpm2-software/tpm2-tools/wiki/Creating-Objects
