### ISSUE TITLE
tpm2-tools Cross Compilation

### ISSUE THREAD

**Issue by mohamedalgalby** [tpm2-software/tpm2-tools#1086]
Hi,
I'm new to TPM and to Linux too and hope I can get some help here. I'm using TPM2.0 SLB 6970 form Infineon on an embedded gateway board with Zynq-7000 SoC device from Xlinx, so it includes a single-core ARM Cortex™-A9 processor. The board runs a distribution of Linux for embedded systems. Usually, to compile any code for my board, I must source an environement setup script called "**environment-setup-cortexa9hf-neon-oe-linux-gnueabi**" and then I can compile the code file using $CC e.g. $CC -o myfile myfile.c. My quesition is how to compile the **tpm2-tss**, **tpm2-abrmd** and **tpm2-tools** so that I can run TPM 2.0 commands like generating crypto keys and doing simple encryption/decryption stuff on my machine? I tried to source my setup script firstly and then run the following:
./bootstap
./configure --build=i686-pc-linux-gnu --host=arm-oe-linux-gnueabi --target=arm-oe-linux-gnueabi
but I got comiplation error. I guessed it might be an invalid host or target names. 
Another question, if we set host, build and target names correctly, don't we need also to explicitly specify an option for using **$CC** instead of **gcc** for the ./configure command?
Thank you.
Mohamed Al-Galby

**Comment by williamcroberts** [comment]
Please take support questions to the mailing list. Theirs a lot more people there that could help solve your issue.
