### ISSUE TITLE
backport 72a28f36 to 3.1 & bugfix release

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tools#1091]
There's a bug report on the mailing list https://lists.01.org/pipermail/tpm2/2018-July/000757.html about manpages not installing with the latest release. As @mgerstner points out this was fixed in 72a28f36151db9bfa59a460ae0114dcece218862 but it looks like this didn't make it into 3.1. Backporting this commit and doing a 3.1.x is probably the right thing to do.

**Comment by joshuagl** [comment]
3.1.1 has been released with the backported fix: https://github.com/tpm2-software/tpm2-tools/releases/tag/3.1.1
