### ISSUE TITLE
coveralls rename

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tools#1095]
When we migrated from 01org to tpm2-software org coveralls got confused. We can still push coverage statistics (tools is here: https://coveralls.io/github/01org/tpm2-tools) but interacting with the file level info in the coveralls UI results in an error. The coveralls interface assumes the code is @ the old URL.

This can be fixed by activating the coveralls for the tpm2-tools code at the new location / org and switching over the CI to send statistics there. We can then create an issue in the coveralls github tracker and they'll migrate the history for us.

**Comment by flihp** [comment]
the coveralls folks helped me out with the tpm2-tss stuff here: https://github.com/lemurheavy/coveralls-public/issues/1066

**Comment by joshuagl** [comment]
I don't think I have sufficient access to do this, I can't see a repo token on coveralls.io and according to their [troubleshooting](http://docs.coveralls.io/troubleshooting):

> I can’t see the repo’s token.
> You need to have admin permissions on Github for the repo in order to access/regenerate its token on Coveralls. If you do and our data is out of sync, please re-sync your repos here: https://coveralls.io/refresh
>

**Comment by flihp** [comment]
Didn't realize 'admin' perms on the repo were required for this sort of thing. Pretty weird since @williamcroberts set it up initially and he has the same permissions as you. Let's experiment to see if promoting the 'maintainers' group from 'write' to 'admin' permissions. Let me know if this resolves the issue.

**Comment by joshuagl** [comment]
Thanks @flihp -- I'm now able to see the repo token on coveralls.io and I've triggered two builds which have submitted scan results: https://coveralls.io/github/tpm2-software/tpm2-tools
I've submitted a pull request to update the badge in the README: #1096 and requested that the history be merged by coveralls at lemurheavy/coveralls-public#1159

**Comment by flihp** [comment]
LGTM
