### ISSUE TITLE
Can tpm2_createprimary print or output the name of created object?

### ISSUE THREAD

**Issue by acmer29** [tpm2-software/tpm2-tools#1108]
Hi, 

I am implementing TPM2_Load command with HMAC authentication in my software. In this HMAC computation, the name of the object is required. 

I would like to use tpm2-tools to execute tpm2_createprimary and save the name of created object in a configuration file, which will be read and parsed by my software to run TPM2_Load with HMAC computation. However I did not find any parameters in tpm2_createprimary corresponded to print or output the name of created object. Would you plan to add this feature in the future?

**Comment by williamcroberts** [comment]
Current master will print the name of the object to stdout in a YAML format with tpm2_readpublic:

$ tpm2_load -C parent.ctx -u key.pub -r key.priv -o key.ctx
$ tpm2_readpublic -c key.ctx
name: 000b83c51e4f27b84acf63c950e82028276fb28c06eb4054b1c43e3478b0b65bd8ab
qualified name: 000bb3b8c9e264b5e6036cfc83ddd2823fa6f9ca2016c907fcdd238ba60d5546a14d
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|decrypt|sign
  raw: 0x60072
type:
  value: symcipher
  raw: 0x25
algorithm: 
  value: aes
  raw: 0x6
mode:
  value: cfb
  raw: 0x43
keybits: 128
symcipher: 4347c5cfa1ce9c96c1912a4349e33a5daca7ccbbc9597942201add7c6ca8d262


Bill

**Comment by williamcroberts** [comment]
Next time please use the mailing list for support questions.
