### ISSUE TITLE
Getting started wiki omissions

### ISSUE THREAD

**Issue by montvid** [tpm2-software/tpm2-tools#1113]
https://github.com/tpm2-software/tpm2-tools/wiki/Getting-Started
One needs to start the systemd service after installation to be able to execute "Hello world". Maybe someone could update the wiki? Thanks for the software!
Check to see if tpm is loaded "dmesg | grep -i tpm" if not reboot.
sudo systemctl enable tpm2-abrmd.service
sudo systemctl start tpm2-abrmd.service
sudo systemctl status tpm2-abrmd.service
tpm2_pcrlist

**Comment by williamcroberts** [comment]
Your grep command is for a Hardware TPM and the instructions are set up for using a simulator. The systemctl commands won't work, you need to pass the correct TCTI for the simulator.

The goal of that is the simplest way of getting the stack working without dealing with if the user has both the required hardware, as well as access to the hardware (permissions on /dev/tpm0).

**Comment by williamcroberts** [comment]
Not really sure what else we can add to that, without bloating it more then it already is.

**Comment by montvid** [comment]
@williamcroberts thank you for your reply. Every machine that is windows 10 certified has to have a tpm or an intel ptt and that is a lot of machines so there is less need for a simulator. I haven't found a wiki that shows how to setup a real tpm so maybe someone can improve on that? I am still struggling to find real examples on how to integrate tpm2 with LUKS and GNOME keyrings as I am a newbie in these matters. I am planning to storm irc for answers but if there was a wiki page i would be more than happy.

**Comment by williamcroberts** [comment]
@montvid if you want to start putting together stuff, I'd be happy to take into the wiki as a separate page, you can [clone the wiki](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/) and we can take PR's for the wiki (it would require me to set up a separate project, but it's doable, or you can just email the patch you'd like to apply and I can handle it that way.

While hardware TPMs are available, I don't assume that one is available, but I also am not a Windows user.

**Comment by montvid** [comment]
Found other omissions:
one needs this to compile from source in ubuntu 18.04:
sudo apt install libtool-bin libcmocka-dev libgcrypt20-dev libssl-dev

The fedora 28 binaries on intel nuc with intel ptt work fine but on ubuntu I can't compile the tss I will open another issue for that.

**Comment by montvid** [comment]
@williamcroberts thanks for suggestions. For a start I just wanted a "how to" install and run the software but It was not easy available so I made this report for someone to include in the wiki these commands so not to struggle as I was struggling because if you don't run the abrmd systemd service nothing works for me and there were no instructions how to run the service.

I am a newbie and I don't know how to do any other things besides tpm2_pcrlist. But If I learn something useful I might write a wiki article. I was just expecting that people who work on this project actually use the tpm2 and know how to use it so there should be an abundance of up to date information on how to set it up but I struggle to find anything with google.

**Comment by montvid** [comment]
@williamcroberts a firmware tpm2 (intel ptt) also works - a hardware tpm2 is not required.
https://docs.microsoft.com/en-us/windows/security/hardware-protection/tpm/tpm-recommendations
> Since July 28, 2016, all new device models, lines or series (or if you are updating the hardware configuration of a existing model, line or series with a major update, such as CPU, graphic cards) must implement and enable by default TPM 2.0 (details in section 3.7 of the Minimum hardware requirements page). The requirement to enable TPM 2.0 only applies to the manufacturing of new devices. For TPM recommendations for specific Windows features, see TPM and Windows Features.

**Comment by williamcroberts** [comment]
@montvid - taking your issues one by one below:

1. A lack of tpm2-abrmd documentation.
details on tpm2-abrmd outside of the simple hello world example with the simulator should be documented with the tpm2-abrmd project. We don't want to do full write ups on those components: So one should see https://github.com/tpm2-software/tpm2-abrmd and bug them for missing docs on how to use the abrmd manager.

2. Documentation on TPM2.0
The documentation around TPM2.0 is quite lacking, and this is a problem. I am not sure how far TPM2.0 is integrated in those sub projects, folks started looking at it, but alas I don't have time to get into those topics at the moment.

3. Hardware TPMs - Whether discrete hardware or a software implementation, their is life outside of Intel and Microsoft platforms and we need to support the whole ecosystem. For the tools, and the fact that our CI run's against the simulator, we test primarily against that. Others in the community perform testing on hardware, and provide valuable feedback. Usually, it's work-arounds in vendor TPMs.

**Comment by montvid** [comment]
Thanks, yes, I need to address tpm2-abrmd it seems!
