### ISSUE TITLE
CI: Coveralls Stopped Pushing

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1114]
Get coveralls to start pushing again from CI.
https://travis-ci.org/tpm2-software/tpm2-tools

**Comment by joshuagl** [comment]
Hmm, I tried a test build and Travis tells me:

> COVERALLS_REPO_TOKEN *not* set

despite the fact that the variable is defined in the travis settings. I'll try adding to the variable to the .travis.yml

**Comment by joshuagl** [comment]
I ran the docker scripts from my development machine with COVERALLS_REPO_TOKEN set and the coverage info was uploaded: https://coveralls.io/jobs/38687494

**Comment by williamcroberts** [comment]
Yeah this job works too:
[job214.1](https://travis-ci.org/tpm2-software/tpm2-tools/jobs/407763204)

When I filed this bug, I was looking at PR builds which will not have any secure env variables set, like REPO_TOKEN.

**Comment by williamcroberts** [comment]
Yeah, wird that the latest ones are not popping up, the latest I see on coveralls is:
https://coveralls.io/builds/17921585

**Comment by williamcroberts** [comment]
Fixed: #1558
