### ISSUE TITLE
Using EVP_CIPHER_CTX directly breaks compatibility with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-tools#1118]
The recent commit df7495b91b80b78065d3590c28a27955e54f37f0 breaks compatibility with OpenSSL 1.1.0: the `EVP_CIPHER_CTX ctx` in [line 272 of tools/tpm2_import.c](https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_import.c#L272) must be declared as a pointer, see https://github.com/openssl/openssl/issues/962#issuecomment-208792020, or building with OpenSSL 1.1.0 will fail. If I make the changes described in the linked comment and adapt the subsequent references to `ctx`, the tool suite compiles fine again for me.

**Comment by williamcroberts** [comment]
I accidentally closed https://github.com/tpm2-software/tpm2-tools/issues/1079, but this is a known problem recorded in the task list there.
