### ISSUE TITLE
Test more distros in CI

### ISSUE THREAD

**Issue by joshuagl** [tpm2-software/tpm2-tools#1122]
We've seen a number of recent changes (PR #1121 and db4c126 of PR #1120) for issues that are not covered by our Travis CI, therefore we should increase the range of distros we test to cover a good range of compilers, libraries, etc.

My gut (and past experience with CI and build systems) tells me we'll cover a good range of software if we test latest Fedora (to get cutting edge tools & OS plumbing), latest CentOS (to get an enterprise distro with more mature tools and libraries) and latest (or at least latest LTS) Ubuntu (for a very popular configuration and a mixture of ingredient ages).
In general I think latest Ubuntu + latest LTS makes sense, but when they are the same (as now) do we go with latest LTS & most recent LTS? (I suppose we'd be absolved of making this decision if we wait a few weeks for 18.10).

The only documented limit I've been able to find for Travis CI open source projects is that:

> Builds will timeout after 50 minutes https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts

There's also some old information that only 5 concurrent builds can be executed per organisation [1](https://twitter.com/mattrobenolt/status/651831557410410496).

Which would suggest that we can easily add 3 more builds to our matrix, yet I've defined an additional 6/8 builds above, 3/4 distros with clang+gcc on each. I propose we go ahead and add the 6 extra builds to our matrix and if this is causing issues with Travis and its limits we can take some extra steps to reduce the number of concurrent builds (i.e. have a combination of fixed configurations that execute for each build combined with a random selection from the remaining pool of configurations).

__Proposal__
- [ ] Generate container images for additional distros & upload to [docker hub](https://hub.docker.com/u/tpm2software/)
  - [ ] Fedora 28 (gcc + clang)
  - [ ] CentOS 7 (gcc + clang)
  - [ ] Ubuntu 18.04 (gcc + clang)
- [ ] Adapt CI scripts to choose container based on environment variable
- [ ] Set up Travis matrix to test all selected distros
- [ ] Restrict coverity builds to a single distro

**Comment by joshuagl** [comment]
- Do the selected distros make sense? Is 4 distro/version combinations overkill?
- Do we want the container images to be updated to match the latest OS state semi-regularly?
- Does it make sense to automate update & upload of the container images on a periodic basis?

**Comment by joshuagl** [comment]
Turning Esys off is a good idea, as is restricting coveralls to one distro. You raise a good point with PR builds and master builds. How we tackle that depends on goals:
- If we want to be sure master doesn't break on either of the 4 distros, we could try building everything for PRs and have master builds only happen for one distro (LTS Ubuntu, as done now?).
- If we want to be sure we fix any issues in the distros before release we could have PRs build for a random distro and have master builds build everything.

So far as I can find there isn't a documented bandwidth cap for Travis and we're by no means going to be the largest open source build on Travis, even with the proposed distro additions. I'd be tempted to try building everything and only tune down to a randomised selection if we observe issues. Though as it appears our limits are shared by the entire organisation, it may be more prudent to implement a more conservative approach and build a smaller matrix of randomised distros.

**Comment by williamcroberts** [comment]
Done, See commits:
- d08a4b2fd57bb
- 55f9be3a0c45b
- 44ec17ba2c6b6
