### ISSUE TITLE
Verifying signed releases

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-tools#1125]
Releases are currently signed by one of the three following PGP keys as described in [RELEASE.md](https://github.com/tpm2-software/tpm2-tools/blob/master/RELEASE.md#verifying-tags)<sup>1</sup>:

- William Roberts (5B482B8E3E19DA7C978E1D016DE2E9078E1F50C1)
- Javier Martinez Canillas (D75ED7AA24E50CD645C6F457C751E590D63F3D69)
- Joshua Lock (5BEC526CE3A61CAF07E7A7DA49BCAE5443FFFC34)

I noticed that only the second of these keys seems to be available on a public keyserver. Would it be possible to add the other two keys to the [OpenPGP keyserver pool](http://pool.sks-keyservers.net/) as well?

This would make it much easier to verify a release automatically, e.g. in the build process of an [Arch Linux User Repository (AUR) package](https://wiki.archlinux.org/index.php/Makepkg#Signature_checking), as users can import the keys directly using `gpg --receive-keys <fingerprint>` instead of having to clone the Git repository and manually importing them from the tags.
For the sister projects [tpm2-tss](https://github.com/tpm2-software/tpm2-tss) and [tpm2-abrmd](https://github.com/tpm2-software/tpm2-abrmd), this is already the case, as [documented in their RELEASE.md](https://github.com/tpm2-software/tpm2-tss/blob/master/RELEASE.md#signing-keys).

<sup>1</sup> This document is a bit outdated, as it only lists the `william-roberts-pub` tag, but the other two keys in `javier-martinez-pub` and `joshua-lock-pub` can be found easily by looking at the list of all tags.

**Comment by williamcroberts** [comment]
I uploaded my key:
* https://pgp.mit.edu/pks/lookup?op=vindex&search=0x6DE2E9078E1F50C1
* I also archived revocation certificates in case I need to revoke the key from the server.

FYI How to generate "ascii armor version":
```
gpg --armor --export <key id>
```
I just grabbed the key id from my ~/.gitconfig file.

@joshuagl and @martinezjavier can you please do the same. I also recommend securely archiving revocation certs. I have a few generated for different scenarios:
  * lost key/key no longer used
  * compromised key

**Comment by williamcroberts** [comment]
We also should re-write our RELEASE.md to clarify this change. I still want to keep a public key as an object in the git repo.

**Comment by martinezjavier** [comment]
@williamcroberts as @diabonas mentioned, I already uploaded my key to a public keyserver (pgp.mit.edu) a long time ago.

**Comment by williamcroberts** [comment]
@martinezjavier sorry, senior moment.

**Comment by joshuagl** [comment]
I've uploaded my key: https://pgp.mit.edu/pks/lookup?op=vindex&search=0x49BCAE5443FFFC34

**Comment by martinezjavier** [comment]
> @martinezjavier sorry, senior moment.

haha, no worries. I just mentioned to let you know that's already there.

**Comment by diabonas** [comment]
Nice, thank you very much @martinezjavier @williamcroberts @joshuagl! The next version of the [Arch Linux AUR package for tpm2-tools](https://aur.archlinux.org/packages/tpm2-tools/) will have signature verification enabled.
