### ISSUE TITLE
Unable to get authorization to TPM2 after clearing

### ISSUE THREAD

**Issue by AshithPolepalli** [tpm2-software/tpm2-tools#1137]
I'm working on Nuc7i7BNH firmware TPM2.
Getting the following error on running command below, after performing following steps:

1. TPM2 has been cleared by removing jumper and selecting option on boot.(as mentioned in  NUC datasheet)

2. $ tpm2_takeownership -o ownerpass -e endorsepass -l lockpass
ERROR: Could not change hierarchy for Owner. TPM Error:0x9a2

couldn't understand what is the exact issue in setting password after clearing the TPM.

**Comment by williamcroberts** [comment]
Perhaps something is setting the owner password before you're getting to it. What's the full stack that your running (windows, linux, etc)?

@tstruk don't you have a NUC?

**Comment by tstruk** [comment]
@williamcroberts No, I don't have any NUC system. I'm using minnowboard.
@AshithPolepalli From the Error:0x9a2 it looks like that there is still some auth value somewhere.
Could you try to ru tpm2_clear before tpm2_takeownership

**Comment by AshithPolepalli** [comment]
@williamcroberts i am using Linux 4.15.0-29-generic kernel on ubuntu 16.04.

@tstruk 
1) Disabled tpm2-abrmd service.
2) Cleared TPM
3) executed following command soon after clearing and facing following error.
$ tpm2_clear
ERROR: Tss2_Sys_Clear(0x98E) - tpm:session(1):the authorization HMAC check failed and DA counter incremented

**Comment by SilverJan** [comment]
Getting the same error (`ERROR: Tss2_Sys_Clear(0x98E) - tpm:session(1):the authorization HMAC check failed and DA counter incremented`) while executing `tpm2_clear` with the current master-branch builds.

**Comment by AshithPolepalli** [comment]
@williamcroberts @tstruk can you help me out on the issue, it still persists.

**Comment by idesai** [comment]
@AshithPolepalli @SilverJan I had to do this today on a NUC someone showed up with the same issue. 
These steps worked for me:
1. Boot to linux and confirm passwords are in fact set --> tpm2_getcap -c properties-variable
2. Power-Off --> Remove security jumper --> Power-On --> Configuration menu shows option to clear tpm --> Issue clear --> Power-Off --> Power-On
3. Boot to linux and confirm passwords are in fact cleared --> tpm2_getcap -c properties-variable
4. Change the Owner-Hierarchy, Endorsement-Hierarchy and Lockout auths with tpm2_changeauth command

If this has worked for you, please close the issue. Thanks.
