### ISSUE TITLE
tpm2_createprimary shout value is out of range or is not correct for the context

### ISSUE THREAD

**Issue by u7702045** [tpm2-software/tpm2-tools#1142]
tpm2_clean ; tpm2_createprimary -g 'sha1' -G 'ecc' -o context.primary
Tss2_Sys_CreatePrimary(0x2C4) - tpm:parameter(2):value is out of range or is not correct for the context

I found this issue on ARM platform after git update from
491c9975f264a574556a9166e31d42062423caba
 to
63bf577935b3812dbea0c5f0637234d37ebba90e

**Comment by williamcroberts** [comment]
I wonder if your tpm doesn't support the default chosen ECC algorithm of curve size 256. Since it's a restricted (parent) object the scheme should be NULL and an aes256cfb symmetric key associated. Typing "ecc" in your case, is really the same as typing: "ecc256:null:aes256cfb". The scheme (middle part) has to stay null or the tpm will reject it. So this leaves two parts, either:
1. Your tpm doesn't support ecc256, try ecc192 or ecc224.
2. Your tpm doesn't support aes256cfb, perhaps try something else here, like aes128cbc.

You may want to use tpm2_getcap to dump out what your tpm supports.

**Comment by u7702045** [comment]
@williamcroberts , Thank for the reply, can you point me the right direction? Here is the getcap on my machine:
# tpm2_getcap -c 'properties-variable'
TPM2_PT_PERSISTENT:
  ownerAuthSet:              0
  endorsementAuthSet:        0
  lockoutAuthSet:            0
  reserved1:                 0
  disableClear:              0
  inLockout:                 0
  tpmGeneratedEPS:           0
  reserved2:                 0
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  1
  shEnable:                  1
  ehEnable:                  1
  phEnableNV:                1
  reserved1:                 0
  orderly:                   0
TPM2_PT_TPM2_HR_NV_INDEX: 0x0
TPM2_PT_HR_LOADED: 0x0
TPM2_PT_HR_LOADED_AVAIL: 0x3
TPM2_PT_HR_ACTIVE: 0x0
TPM2_PT_HR_ACTIVE_AVAIL: 0x40
TPM2_PT_TPM2_HR_TRANSIENT_AVAIL: 0x3
TPM2_PT_TPM2_HR_PERSISTENT: 0x0
TPM2_PT_TPM2_HR_PERSISTENT_AVAIL: 0x15
TPM2_PT_NV_COUNTERS: 0x0
TPM2_PT_NV_COUNTERS_AVAIL: 0xD
TPM2_PT_ALGORITHM_SET: 0x0
TPM2_PT_LOADED_CURVES: 0x2
TPM2_PT_LOCKOUT_COUNTER: 0x0
TPM2_PT_MAX_AUTH_FAIL: 0x20
TPM2_PT_LOCKOUT_INTERVAL: 0x1C20
TPM2_PT_LOCKOUT_RECOVERY: 0x15180
TPM2_PT_AUDIT_COUNTER_0: 0x0
TPM2_PT_AUDIT_COUNTER_1: 0x0

#tpm2_getcap -c 'algorithms'
rsa:
  value:      0x1
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     1
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
sha1:
  value:      0x4
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
hmac:
  value:      0x5
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     0
aes:                                                                                                                         [122/1855]
  value:      0x6
  asymmetric: 0
  symmetric:  1
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
keyedhash:
  value:      0x8
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     1
  reserved:   0x0
  signing:    1
  encrypting: 1
  method:     0
xor:
  value:      0xA
  asymmetric: 0
  symmetric:  1
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
sha256:                                                                                                                       [92/1855]
  value:      0xB
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
rsassa:
  value:      0x14
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     0
rsaes:
  value:      0x15
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 1
  method:     0
rsapss:                                                                                                                       [62/1855]
  value:      0x16
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     0
oaep:
  value:      0x17
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 1
  method:     0
ecdsa:
  value:      0x18
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     1
ecdh:                                                                                                                         [32/1855]
  value:      0x19
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     1
ecdaa:
  value:      0x1A
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     0
kdf1_sp800_56a:
  value:      0x20
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     1
kdf1_sp800_108:                                                                                                                [2/1855]
  value:      0x22
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     1
ecc:
  value:      0x23
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     1
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
symcipher:
  value:      0x25
  asymmetric: 0
  symmetric:  0
  hash:       0
  object:     1
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
cfb:
  value:      0x43
  asymmetric: 0
  symmetric:  1
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 1
  method:     0
# tpm2_getcap -c 'properties-fixed'
TPM2_PT_FAMILY_INDICATOR:
  raw: 0x08322e3000
  value: "2.0"
TPM2_PT_LEVEL:
  value: 0
TPM2_PT_REVISION:
  value: 1.16
TPM2_PT_DAY_OF_YEAR:
  value: 0xF
TPM2_PT_YEAR:
  value: 0x7E0
TPM2_PT_MANUFACTURER:
 value        0x49465800
TPM2_PT_VENDOR_STRING_1:
  raw: 0x534C4239
  value: "SLB9"
TPM2_PT_VENDOR_STRING_2:
  raw: 0x36373000
  value: "670"
TPM2_PT_VENDOR_STRING_3:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_STRING_4:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_TPM_TYPE:
  value: 0x0
TPM2_PT_FIRMWARE_VERSION_1:
  value: 0x7003E
TPM2_PT_FIRMWARE_VERSION_2:
  value: 0xC3600
TPM2_PT_INPUT_BUFFER:
  value: 0x400
TPM2_PT_TPM2_HR_TRANSIENT_MIN:
  value: 0x3
TPM2_PT_TPM2_HR_PERSISTENT_MIN:
  value: 0x7                                                                                                                  [19/1950]
TPM2_PT_HR_LOADED_MIN:
  value: 0x3
TPM2_PT_ACTIVE_SESSIONS_MAX:
  value: 0x40
TPM2_PT_PCR_COUNT:
  value: 0x18
TPM2_PT_PCR_SELECT_MIN:
  value: 0x3
TPM2_PT_CONTEXT_GAP_MAX:
  value: 0xFFFF
TPM2_PT_NV_COUNTERS_MAX:
  value: 0x8
TPM2_PT_NV_INDEX_MAX:
  value: 0x680
TPM2_PT_MEMORY:
  value: 0x6
TPM2_PT_CLOCK_UPDATE:
  value: 0x80000
TPM2_PT_CONTEXT_HASH:
  value: 0xB
TPM2_PT_CONTEXT_SYM:
  value: 0x6
TPM2_PT_CONTEXT_SYM_SIZE:
  value: 0x80
TPM2_PT_ORDERLY_COUNT:
  value: 0xFF
TPM2_PT_MAX_COMMAND_SIZE:
  value: 0x500
TPM2_PT_MAX_RESPONSE_SIZE:
  value: 0x500
TPM2_PT_MAX_DIGEST:
  value: 0x20
TPM2_PT_MAX_OBJECT_CONTEXT:
  value: 0x3B8
TPM2_PT_MAX_SESSION_CONTEXT:
  value: 0xEB
TPM2_PT_PS_FAMILY_INDICATOR:
  value: 0x1
TPM2_PT_PS_LEVEL:
  value: 0x0
TPM2_PT_PS_REVISION:
  value: 0x100
TPM2_PT_PS_DAY_OF_YEAR:
  value: 0x0
TPM2_PT_PS_YEAR:
  value: 0x0
TPM2_PT_SPLIT_MAX:
  value: 0x80
TPM2_PT_TOTAL_COMMANDS:
  value: 0x5A
TPM2_PT_LIBRARY_COMMANDS:
  value: 0x59
TPM2_PT_VENDOR_COMMANDS:
  value: 0x1
TPM2_PT_NV_BUFFER_MAX:
  value: 0x300

# tpm2_getcap -c 'ecc-curves'
TPM2_ECC_NIST_P256: 0x3
TPM2_ECC_BN_P256: 0x10

**Comment by u7702045** [comment]
@williamcroberts , more information:
rsa:
value: 0x1
asymmetric: 1
symmetric: 0
hash: 0
object: 1
reserved: 0x0
signing: 0
encrypting: 0
method: 0
sha1:
value: 0x4
asymmetric: 0
symmetric: 0
hash: 1
object: 0
reserved: 0x0
signing: 0
encrypting: 0
method: 0

# tpm2_clear ; tools/tpm2_createprimary -g 'sha1' -G 'rsa' -o context.primary
ERROR: Tss2_Sys_CreatePrimary(0x2CA) - tpm:parameter(2):the type of the value is not appropriate for the use

**Comment by williamcroberts** [comment]
Can you try:
```
tpm2_createprimary -g 'sha1' -G 'rsa2048:null:aes128cfb' -o context.primary
```

**Comment by williamcroberts** [comment]
The reason it works, is that when you do 'rsa' or 'ecc' we need to pick other parameters, as assymetric objects have 3 major components:
1. The main algorithm, like RSA and it's key size, like 2048
2. The scheme. This HAS to be null for parent objects (like primary objects). That's the second part of the field.
3. The symmetric key associated with an asymmetric object for encryption schemes like RSAES.

You can specify all or parts of those 3 fields, and we choose, relatively sane defaults for each of them. In the case of aes128cfb, I chose that because I could see in getcap that rsa2048 was supported, however, I am not sure where the AES supported key-size is, but I know that the TPM has to support AES128CFB per the specification.

The default selections could be smartened up by looking at "getcap" and choosing supported algorithms, but perhaps we can dial the default of choosing aes256cfb down to aes128cfb.

I documented this here: https://github.com/tpm2-software/tpm2-tools/blob/master/man/common/alg.md

FYI: Right now master is moving and changing quite a bit as we add support to the tools.
