### ISSUE TITLE
tpm2_import - truncating 256 AES keys

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1146]
https://github.com/tpm2-software/tpm2-tools/blob/master/test/integration/tests/import.sh#L54

The test creates a 32 byte key, but truncates it in the OSSL calls and when setting the public attribute values.

**Comment by williamcroberts** [comment]
ie 32 should be aes256 not aes128

**Comment by joholl** [comment]
I'll look into this if you don't mind

**Comment by williamcroberts** [comment]
@joholl all yours
