### ISSUE TITLE
tpm2_getcap -c properties-fixed

### ISSUE THREAD

**Issue by ismaws** [tpm2-software/tpm2-tools#1150]
I'm able to run tpm2_getcap with other arguments, but "properties-fixed" throws:

tpm2_getcap -c properties-fixed -V
WARN on line: "65" in file: "lib/tpm2_capability.c": More data to be queried: capability: 0x6, property: 0x100

ERROR on line: "166" in file: "tools/tpm2_tool.c": Unable to run ./tpm2_getcap

**Comment by williamcroberts** [comment]
So I don't have a TPM that actually triggers this, but essentially it needs to loop and store based on the MORE_DATA flag IIUC. I can try putting a patch together for it, but at a minimum I would need your help to test it. Even better, you can propose a patch to the project.

**Comment by ismaws** [comment]
Thanks. I can definitely test it. I'll see if I can propose the patch.
