### ISSUE TITLE
Option -a/-A revisit

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1151]
-a is used for the hierarchy and -A is used for object attributes. Likely want to swap those, since capital options indicate parent idioms, like hierarchy.

**Comment by joshuagl** [comment]
I've a patch to make this change, however before I create a PR I need to look at the output of analyze.py and ensure we're doing the right thing.

**Comment by williamcroberts** [comment]
Seems done..and no longer applicable. We need to scan options one more time for 4.0 release.
