### ISSUE TITLE
Loadexternal failing to load rsa public pem file

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tools#1158]
While load external can load public by specifying private pem files, it is failing to load only the public pem without specifying the private file. May be we should add a test that tests loading public pem files only. 
This is causing PR #1143 to fail. The policyauthorize.sh test script runs and fails the following: 
tpm2_loadexternal -G rsa -a n -u $file_public_key -o $file_verifying_key_ctx

**Comment by williamcroberts** [comment]
Weird that worked at some point... ill put a fix in place and test
