### ISSUE TITLE
getmanufec for Intel doesn't work with real hardware?

### ISSUE THREAD

**Issue by cchandler** [tpm2-software/tpm2-tools#1168]
I'm cross posting this issue because I'm having some difficulty tracking down the actual problem.

https://github.com/MinnowBoard-org/bugs-and-help/issues/108#issuecomment-418196750

I've got a minnowboard with an fTPM enabled and working with a few modifications (I need some free time to open some PRs...). Unfortunately, I can't get Intel's ekops service to return anything other than a 404 for an endorsement credential. Has anyone else had luck with getting that service to work with real hardware? The certificate in the test suite works no problem.

**Comment by williamcroberts** [comment]
@idesai might be more knowledgeable on this.

**Comment by idesai** [comment]
@cchandler the fTPM generation on minnow board (Intel (R) Baytrail SOC or Intel Atom® Z3700 Processor Series) is an older generation where EK certificates are not hosted by Intel. You can get this feature on newer generation fTPM on newer SOC Intel Atom® Processor E3900.
