### ISSUE TITLE
tpm2_createek without context handle segfaults

### ISSUE THREAD

**Issue by truschival** [tpm2-software/tpm2-tools#1169]
Leaving out the context command line argument `-c ` to `tpm2_createek` causes the program to segfault on Debian Stretch with tpm_server simulator (ibmtpm1119).

Steps to reproduce:
```
export TPM2TOOLS_TCTI=mssim
tpm2_createek -G rsa  -p /tmp/output.pem -f pem 
[1]    1661 segmentation fault  tpm2_createek -G rsa -p /tmp/output.pem -f pem
```
In a quick investigation I found line 307 of tpm2_createek.c  (in function `tpm2_tool_onrun`) as the cause of the segfault.
```
    if (!strcmp(ctx.context_arg, "-")) {
```

I think if a context is required, it should be a mandatory parameter or if it is not given `-c -` could be assumed.

**Comment by joshuagl** [comment]
Good catch. The --context/-c is optional, so we need to ensure the variable is set before trying to access it. Fix incoming.
