### ISSUE TITLE
tpm2_dump_capability not working on latest Ubuntu

### ISSUE THREAD

**Issue by martingalvan** [tpm2-software/tpm2-tools#1176]
Hi all,

I have an Infineon SLB9665 chip, which supports TPM 2.0. I'm trying to do a capability dump, and am always getting the same error:

```
# tpm2_dump_capability -c "properties-fixed"
Failed to initialize tcti context: 0x1
```

(I guess it would be good to use tpm2_error_str there)

I'm running Ubuntu 18.04. I'm aware that tpm2_dump_capability was renamed to tpm2_getcap in version 3, but the tpm2-tools package that comes with Ubuntu 18.04 seems to be version 2.1.0 according to https://packages.ubuntu.com/bionic/tpm2-tools. Doing tpm2_dump_capability -v doesn't show anything useful:

```
# tpm2_dump_capability -v
tpm2_dump_capability, version
```

I have the tpm2-resourcemgr daemon running, though I had to enable it manually, because when I installed the package I noticed the following:

```
Setting up libsapi-utils (1.0-1) ...
tpm2-resourcemgr.service is a disabled or a static unit, not starting it.
```

Does anyone know why this is happening? Other tools like Infineon's eltt2 seem to work fine.

**Comment by williamcroberts** [comment]
Please report this to tpm2-abrmd project.
