### ISSUE TITLE
tpm2-tools-3.1.2/test/system/test_tpm2_activecredential.sh failed because of print format error

### ISSUE THREAD

**Issue by xyzhao2018** [tpm2-software/tpm2-tools#1178]
In tpm2-tools-3.1.2/test/system/test_tpm2_activecredential.sh
Line 76: print doc['loaded-key']['name']  should be updated into print (doc['loaded-key']['name']). 
Otherwise the following error will pop up: 
-  File "<stdin>", line 4
    print doc['loaded-key']['name']
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(doc['loaded-key']['name'])?
loaded_key_name_yaml=`python << pyscript
import yaml
with open('ak.out', 'r') as f:
    doc = yaml.load(f)
    print doc['loaded-key']['name']
pyscript` on line 64 failed: 1

**Comment by joshuagl** [comment]
Issues that affected Python3 compatibility were resolved in the master branch via #1133 but not backported to 3.X as that has a different test harness.
