### ISSUE TITLE
/fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by YadongQi** [tpm2-software/tpm2-tools#1179]
https://github.com/tpm2-software/tpm2-tools/blob/2dde72c8295b01629036ad7b6f9531b4c4523cb3/test/system/test.sh#L91

Better not use "git ls-files" to check leftover files, because the release package is not a GIT.

**Comment by joshuagl** [comment]
This has been changed in the newer test harness we have in the master branch. It would likely be useful to fix in the 3.X branch for the current stable series.
