### ISSUE TITLE
Tool arguments divergence

### ISSUE THREAD

**Issue by ismaws** [tpm2-software/tpm2-tools#1182]
tpm2-tools versions change the way TPM commands are parsed e.g.:

version="3.0.2-685-g119c29e" vs  version="3.0.1" - ERROR: Unknown Argument: a

this breaks scaling out tools and automation based on these utilities. Is there any convergence expected around argument parsing?

[user@flakes scripts]$ sudo tpm2_createprimary -v
tool="tpm2_createprimary" version="3.0.2-685-g119c29e" tctis="dynamic" tcti-default=tabrmd dlclose=enabled

[user@flakes scripts]$ sudo tpm2_createprimary -a o -g sha256 -G ecc -o ./owner_prim.key
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: ecc
  raw: 0x23
curve-id:
  value: NIST p256
  raw: 0x3
kdfa-alg:
  value: null
  raw: 0x10
kdfa-halg:
  value: (null)
  raw: 0x0
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
x: a835ee8ec700d980b140d94f71d1ce5b79b22e4808c4f868c91ba90dcd5234ec
y: 1fb9b0307e7776bea982b8b03d649ca4716777541ee5bed2525e8603d0648f94
handle: 0x800000FF
_____________________________________________

[user@purley ~]$ sudo tpm2_createprimary -v
tool="tpm2_createprimary" version="3.0.1" tctis="tabrmd,socket,device,"

[user@purley ~]$  sudo tpm2_createprimary -a o -g sha256 -G ecc -o ./owner_prim.key
tpm2_createprimary: invalid option -- 'a'
**ERROR: Unknown Argument: a**

**Comment by ismaws** [comment]
inversely:

[user@purley ~]$ sudo tpm2_createprimary -v
tool="tpm2_createprimary" version="3.0.1" tctis="tabrmd,socket,device,"

[user@purley ~]$tpm2_createprimary -H o -g sha256 -G ecc -C context.out
ObjectAttribute: 0x00030072

CreatePrimary Succeed ! Handle: 0x800000ff

___________________________

[user@flakes ~]$ tpm2_createprimary -v
tool="tpm2_createprimary" version="3.0.2-685-g119c29e" tctis="dynamic" tcti-default=tabrmd dlclose=enabled

[user@flakes ~]$ tpm2_createprimary -H o -g sha256 -G ecc -C context.out
**tpm2_createprimary: invalid option -- 'H'**

**Comment by williamcroberts** [comment]
When I first took over the project, their was no consistency between tool options between tools and options were usually always required. As we moved forward with making the tools more usable we identified two areas to focus on among others:
1. Consistent tool options across tool groups and ideally across tools.
2. Making the tools smart enough to have sane defaults and remove the amount of required options.

On master, you can just run:
```sh
tpm2_createprimary
```
And it will do something. The 4.0 release, the options will be solidified, and moving forward from 4.0 we will attempt to keep options backwards compatible across versions unless we found we made a mistake or it's worth the hassle. With that said, we use semantic versioning which allows us to break api compatibility across major version updates, master is currently headed to 4.0 release despite the
versioning output. git describe has that wrong on master, but you can use git to figure it out based on the output:
```sh
git branch --contains 119c29e
* master
```

Think of this as moving from Python2 to Python3, it'll be worth it in the end.

**Comment by ismaws** [comment]
thanks for clarifying and set expectations!
