### ISSUE TITLE
tpm2_policyauthorize man page  

### ISSUE THREAD

**Issue by Nilesh-Deshmukh** [tpm2-software/tpm2-tools#1184]
Hi,

While testing the tpm2_policyauthorize command as per man page tpm2_policyauthorize.1.md observed few errors.  Need to make the following changes to run the test successfully.
Request you to review the changes.

1.	Need to change the hierarchy from null to owner since tpm2_verifysignature  do not create the verification ticket when hierarchy is null 

requred changes:
openssl genrsa -out signing_key_private.pem 2048
 openssl rsa -in signing_key_private.pem -out signing_key_public.pem -pubout
-tpm2_loadexternal -G rsa -a n -u signing_key_public.pem -o signing_key.ctx  -n signing_key.name
+tpm2_loadexternal -G rsa -a o -u signing_key_public.pem -o signing_key.ctx  -n signing_key.name

2.	Typo error while providing the signing key name in tpm2_policyauthorize
3.	load object is missing before unseal command.

requred changes::
tpm2_startauthsession -a -S session.ctx
 tpm2_policypcr -Q -S session.ctx -L sha256:0 -f pcr.policy
-tpm2_policyauthorize -S session.ctx -o authorized.policy -f pcr.policy -n verifying_public_key.name -t verification.tkt
+tpm2_policyauthorize -S session.ctx -o authorized.policy -f pcr.policy -n signing_key.name -t verification.tkt
+tpm2_load -Q -C prim.ctx -u sealing_pubkey.pub -r sealing_prikey.pub -o load.context
 unsealed=`tpm2_unseal -p"session:session.ctx" -c sealing_key.ctx
 tpm2_flushcontext -S session.ctx

Thanks and Regards,
Nilesh

**Comment by joshuagl** [comment]
Thanks for the report. We'd be happy to take a patch for this if you care to create a pull request, otherwise I can verify and make the requested changes.

Can you confirm which version of tpm2-tools you are using.

**Comment by joshuagl** [comment]
tpm2_policyauthorize doesn't exist on the 3.0.X branch from which a 3.0.2 release would be built. Can you tell us which branch you cloned to build your copy of tpm2-tools?

**Comment by Nilesh-Deshmukh** [comment]
Hi,

I have cloned the master branch for my testing,
:~/TPM/tpm2-tools$ git branch
* master

I can see commit id of tpm2_policyauthorize in git log.

commit 565502437e2ca36ab5ff451dfcff6616d5dd7637
Author: Imran Desai <imran.desai@intel.com>
Date:   Wed Sep 19 13:57:47 2018 -0700

    Update tpm2_policyauthorize.1.md

    Update tpm2_policyauthorize.1.md

commit cbb35827728342ef8ac9175127e9241db3d48814
Author: Imran Desai <imran.desai@intel.com>
Date:   Sat Sep 1 12:27:21 2018 -0700

    tpm2_policyauthorize: add tool

    New tool to enable authorizing policy digests with PolicyAuthorize

Thanks and Regards,
Nilesh

**Comment by idesai** [comment]
@williamcroberts these changes got merged here https://github.com/tpm2-software/tpm2-tools/pull/1198.
