### ISSUE TITLE
tpm2_changeauth should be able to change the auth value for a loaded TPM object

### ISSUE THREAD

**Issue by joshuagl** [tpm2-software/tpm2-tools#1189]
tpm2_changeauth should be able to change the authorisation values for loaded tpm objects.

**Comment by electrickite** [comment]
Similarly, being able to change the authPolicy would be very useful in addition to the authValue. I have found it fairly common to need re-create an object in order to update its PCR policy.

**Comment by williamcroberts** [comment]
Fixed: https://github.com/tpm2-software/tpm2-tools/commit/ed4c389f71cf7f31d35cc9648785f8aea0534641

**Comment by williamcroberts** [comment]
> Similarly, being able to change the authPolicy would be very useful in addition to the authValue. I have found it fairly common to need re-create an object in order to update its PCR policy.

You can't. The policy digest is part of the public portion of an object thus changing it causes you to create a new object.
