### ISSUE TITLE
Initial passwords for tpm2

### ISSUE THREAD

**Issue by AshithPolepalli** [tpm2-software/tpm2-tools#1192]
I have a new NUC8i7HVK, i tried to take ownership for TPM2 and faced with an error,

tpm2_changeauth --owner-passwd=hello123 --endorse-passwd=hello123 --lockout-passwd=hello123
ERROR: Tss2_Sys_HierarchyChangeAuth(0x98E) - tpm:session(1):the authorization HMAC check failed and DA counter incremented
ERROR: Unable to run tpm2_changeauth

What will be the initial passwords? How can i resolve the issue?

**Comment by lukehinds** [comment]
There are no initial passwords. 

It looks like someone has already taking ownership of the TPM. Can you not do a TPM clear in the units bios?
