### ISSUE TITLE
Add exit codes

### ISSUE THREAD

**Issue by electrickite** [tpm2-software/tpm2-tools#1193]
When using tools in scripts or non-interactive scenarios, it would be very helpful to return more detailed exit codes. Currently the majority (all?) tools return 0 on success and 1 on any type of failure. 

In order to implement branching logic or error messages based on the type of failure, as far as I know the only way to determine the specific error is to capture stderr and grep the output for error codes. This works to a point, but requires additional commands, processes, and is quite brittle.

Would it be possible to convert TPM error codes into a numeric exit code and return that number after a failure? Alternately, a mapping table of common error codes to numeric exit codes could be created.

**Comment by joshuagl** [comment]
This sounds like a nice idea. If we're going to make this change we should do it before our 4.x release as it'll effectively be a part of the ABI (and we're trying to stabilise and freeze interfaces ahead of 4.x).

**Comment by electrickite** [comment]
@williamcroberts Yes, a full mapping would likely not be possible.

One example from a recent project: The script attempts to unseal a TPM object (or access an NVRAM area) using a PCR policy. If the unseal fails, the tool responds with an exit code of 1. We might guess the reason was a PCR value change, but it could be any number of things from a TCTI communication error to a malformed PCR bank specification from the user to a missing object context or bad object handle.

stderr will contain the RC code, of course, but now we are parsing command output for known error strings or matching a line text against a regex, both pretty brittle.

Another alternative would be to add an option to provide _only_ the RC code on stderr (or stdout?) with the accompanying text. This would allow for less brittle output parsing.

**Comment by celesteking** [comment]
It would also be wonderful if you could add automatic decoding of returned codes. Currently, I have to use `tpm2_rc_decode` constantly in order to understand what's up. Via a special option or an ENV var, doesn't matter. No output when command succeeds and a decoded output if there's an error.

**Comment by williamcroberts** [comment]
> It would also be wonderful if you could add automatic decoding of returned codes. Currently, I have to use `tpm2_rc_decode` constantly in order to understand what's up. Via a special option or an ENV var, doesn't matter. No output when command succeeds and a decoded output if there's an error.

That's done, all the output code has been converted to PERROR macro:
```C
    TSS2_RC rval = Esys_GetRandom(ectx,
                                  ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE,
                                  ctx.num_of_bytes, &random_bytes);
    if (rval != TPM2_RC_SUCCESS) {
        LOG_PERR(Esys_GetRandom, rval);
        return false;
    }
```

**Comment by williamcroberts** [comment]
Work is on: https://github.com/williamcroberts/tpm2.0-tools/tree/exit-codes

**Comment by williamcroberts** [comment]
Also, after going through all the lib ESYS_ calls remaining, and ensure everything is plumbed with tool_rc's also need to go through the tools themselves.

- [ ] - lib ESYS_ calls plumbed
- [ ] - tool ESYS_ calls plumbed
- [ ] - work on flatten to be better and update manpage

Note that exit() allows for status & 0377 or 1567 unique errors.

I'd like to leave the tpm with the first 256....
Then from there figure out reasonable layer ranges for:
1. RM
2. SAPI
3. ESAPI
4. errno (stretch goal).

**Comment by williamcroberts** [comment]
I don't know offhand if the other error codes are particularly useful. We have the plumbing in place and can map and add as needed on top of the 3 we have.
