### ISSUE TITLE
Interactive password prompt

### ISSUE THREAD

**Issue by electrickite** [tpm2-software/tpm2-tools#1194]
It would be helpful to have the option of entering passwords interactively when needed. This would

  1. Prevent cleartext passwords form being exposed in command line arguments
  2. Ease the use of tpm2-tools in interactive scripts

Perhaps the option to prompt could be built into the minilanguage? Or the tool could detect when a password is required and prompt if one is not supplied?

**Comment by joshuagl** [comment]
Nice idea, I wonder whether we can use pinentry from GNUPG

**Comment by williamcroberts** [comment]
I like the idea of being in the mini-language. Perhaps `prompt:` A bit awkward but it avoids having to deal with a password of `prompt:`. or perhaps `-:` for a password prompt.

If the tool detected it, it would be an RC of TPM2_RC_AUTH_FAIL and then prompt and retry if the TPM2B_AUTH size is 0.

I could go either way and am easily swayed by logical arguments.

**Comment by williamcroberts** [comment]
Fixed: #1589
