### ISSUE TITLE
No package 'sapi" found

### ISSUE THREAD

**Issue by strongerwill** [tpm2-software/tpm2-tools#1195]
I have read the related issue (https://github.com/tpm2-software/tpm2-tools/issues/764) I think I got a new issue for the above error msg.

I compiled tpm2-abrmd
```
$ sudo useradd --system --user-group tss

$ cd tpm2-abrmd 
$ ./bootstrap 
$ ./configure --with-dbuspolicydir=/etc/dbus-1/system.d --with-udevrulesdir=/etc/udev/rules.d --with-systemdsystemunitdir=/usr/lib/systemd/system --libdir=/usr/lib --prefix=/usr 
$ make -j5 
$ sudo make install

$ sudo pkill -HUP dbus-daemon
$ systemctl daemon-reload
$ reboot
$ systemctl enable tpm2-abrmd.service
$ systemctl start tpm2-abrmd.service
```
and tpm2-tss
```
$ cd tpm2-tss 
$ ./bootstrap 
$ ./configure --with-udevrulesdir=/etc/udev/rules.d --prefix=/usr 
$ make -j5 
$ sudo make install
```
And attemp to compile the tpm2-tools with the following commands:

```
$ cd tpm2-tools 
$ ./bootstrap 
$ ./configure --prefix=/usr 
$ make -j5 
$ sudo make install
```
During the step `/configure --prefix=/usr`, I got the following error msg:

```
configure: WARNING: Required executable pandoc not found, man pages will not be built
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SAPI... no
configure: error: Package requirements (sapi >= 1.3.0 sapi < 2.0.0) were not met:

No package 'sapi' found
No package 'sapi' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SAPI_CFLAGS
and SAPI_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

Addition points:
1) The PKG_CONFIG_PATH environment variable is empty in my system.
2) I cannot find any sapi.pc file in my system
3) I can see the following files that may be related to sapi in my system

```
/usr/lib/x86_64-linux-gnu/libgssapi.so.3
/usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2
/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
/usr/lib/x86_64-linux-gnu/samba/libgssapi-samba4.so.2
/usr/lib/x86_64-linux-gnu/samba/libgssapi-samba4.so.2.0.0
/usr/local/include/sapi
/usr/local/lib/libsapi.a
/usr/local/lib/libsapi.la
/usr/local/lib/libsapi.so
/usr/local/lib/libsapi.so.0
/usr/local/lib/libsapi.so.0.0.0
```
Please help me address this issue. Thx.

**Comment by joshuagl** [comment]
Help requests like this are better handled on the mailing list: https://lists.01.org/mailman/listinfo/tpm2

The pc file for the SAPI is _tss2-sys.pc_, which will have been installed as part of the build/install of tpm2-tss. It's likely that your system's default install location isn't included in the default `PKG_CONFIG_PATHS`. You should find where tpm2-tss was installed to (probably /usr/local/lib) and add the pkgconfig subdirectory of that location to `PKG_CONFIG_PATH`, i.e. 
> PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure 

If you have any further trouble please write to the mailing list.
