### ISSUE TITLE
Building against OpenSSL_1_0_2-stable fails with unused-value

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tools#1200]
While fighting travis I stumbled across a `error: value computed is not used [-Werror=unused-value]`
I assume it's an OpenSSL-Macro-Error, so a pragma around it should fix this.

See details at: https://travis-ci.org/AndreasFuchsSIT/tpm2-tss-engine/jobs/442603207

I have not reproduced it outside of this travis environment though...

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT - submitted a patch. I couldn't reproduce it either.
