### ISSUE TITLE
Clang build fails with missing-field-initializer

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tools#1202]
I don't know why this never poped up before, but see:
https://travis-ci.org/AndreasFuchsSIT/tpm2-tss-engine/jobs/442753045

**Comment by williamcroberts** [comment]
That hunk went away in:
cbb3582772834 (Imran Desai 2018-09-01 12:27:21 -0700 276)         .size = (uint16_t)file_size
