### ISSUE TITLE
Compute message hash failed !

### ISSUE THREAD

**Issue by denizea** [tpm2-software/tpm2-tools#1216]
Hi there,
I have started to work with tpm2_sign command. In order to sign I need to hash the file first. I have followed [this web page](https://dguerriblog.wordpress.com/) which was very useful. 
However, I am running following codes 
`rm *.bin *.raw && tpm2_hash -H e -g 0x00B -I message.txt -o hash.bin -t ticket.bin && tpm2_sign -k 0x81010010 -g 0x000B -m message.txt -s sign.bin -t ticket.bin && dd if=sign.bin of=sign.raw bs=1 skip=6 count=256` and sometimes I receive following message 
```
hierarchyValue: 0x4000000b

halg = 0x000b
Accept socket:  0x6
Resource Manager Other CMD Server accepted client
Accept socket:  0x7
Resource Manager TPM CMD Server accepted client

tpm2_hash succ.


hash value(hex type): 03 ba 20 4e 50 d1 26 e4 67 4c 00 5e 04 d8 2e 84 c2 13 66 78 0a f1 f4 3b d5 4a 37 81 6b 6a b3 40 

validation value(hex type): 67 d8 55 b0 64 0f bb 4f b7 d6 7d 63 a1 40 93 08 01 bd 47 c3 e0 3c c8 70 dd 4b 4e f6 66 6c 70 45 
TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0x7.
OtherCmdServer died (Other CMD), socket: 0x6.
halg = 0x000b
Accept socket:  0x8
Resource Manager Other CMD Server accepted client
Accept socket:  0x9
Resource Manager TPM CMD Server accepted client
**Compute message hash failed !**
TpmCmdServer died (TPM CMD), rval: 0x00000000, socket: 0x9.
OtherCmdServer died (Other CMD), socket: 0x8.```

Do you have any idea why I am failing on computing hashes?
Thank you,

**Comment by williamcroberts** [comment]
Im not sure what version of the tools that post was created against and what version you're using. I would recommend not using stuff in package managers as it tends to be super out-dated.

On tpm2-tools 3.X and master you can just sign the message and it will compute the hash for you. Our test cases are under tes/integration are good examples.

I am closing this, as this is a support question and should be taken to the mailing list.
