### ISSUE TITLE
Add integration test for `-T`/`--tcti` option

### ISSUE THREAD

**Issue by joshuagl** [tpm2-software/tpm2-tools#1233]
The fix for #1171 in the 3.X branch broke the `-T` option. We should develop integration tests which check `-T` is working as expected.

**Comment by williamcroberts** [comment]
You'll probably have mock some part of the TCTI ldr interface, I think mocking `dlopen(3)` will cause some serious issues.

**Comment by joshuagl** [comment]
See also #1269 for further breakage which should be covered by the test.
