### ISSUE TITLE
tpm2_getmanufec HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by batyrchary** [tpm2-software/tpm2-tools#1236]
I want to get certificate of EK from my TPM vendor.

To do that I create EK and AIK first.

then execute this command:

tpm2_getmanufec -O ak.pub -g rsa -E c6.cert -U https://ekop.intel.com/ekcertservice/ -V

and output is like this, sorry for long output, I just hope that you will be able to see sth that I missed

WARN: TLS communication with the said TPM manufacturer server setup with SSL_NO_VERIFY!
9E9AA62FE9F252D3EB9D80A37B582F392A520DA10B4BFBA9460D7AF76F776991
INFO on line: "278" in file: "tools/tpm2_getmanufec.c": Calculating the Base64Encode of the hash of the Endorsement Public Key:
INFO on line: "417" in file: "tools/tpm2_getmanufec.c": npqmL-nyUtPrnYCje1gvOSpSDaELS_upRg169293aZE%3D
*   Trying 192.198.164.61...
* Connected to ekop.intel.com (192.198.164.61) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: ekop.intel.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,postalCode=95630,ST=CA,L=Folsom,street=FM1-110,street=1900 Prairie City Rd.,O=Intel Corporation,OU=Hosted by Intel Corporation,OU=Multi-Domain SSL,CN=ekop.intel.com
* 	 start date: Thu, 07 Sep 2017 00:00:00 GMT
* 	 expire date: Sat, 07 Sep 2019 23:59:59 GMT
* 	 issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Organization Validation Secure Server CA
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET /ekcertservice/npqmL-nyUtPrnYCje1gvOSpSDaELS_upRg169293aZE%3D HTTP/1.1
Host: ekop.intel.com
Accept: */*

< HTTP/1.1 404 Not Found
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Length: 21
< Content-Type: text/plain; charset=utf-8
< Expires: -1
< FWS: 4
< Date: Sat, 10 Nov 2018 05:19:08 GMT
< Set-Cookie: TS01da6661=01c5f9c67c0e72cf091401427d90537afd365a678bf571447ab079eb70e371b49b52bd1ecaa2b787c139677c8bd03d615c685577d6; Path=/
< Vary: Accept-Encoding
< 
* Connection #0 to host ekop.intel.com left intact

Here it says  "HTTP/1.1 404 Not Found"
If I understood correctly it should return me the certificate but it is not doing it.

I retrieved certificate from nv_index and checked for my vendor.
And modified command like this:

 tpm2_getmanufec -O ak.pub -g rsa -U http://www.nuvoton.com/ekcertserver/ -V

But still nothing changed.

Please can you show me what I am missing.

**Comment by williamcroberts** [comment]
Imran,
Any idea?

**Comment by idesai** [comment]
May be the weblink when nuvoton certs are hosted is   http://www.nuvoton.com/security/NTC-TPM-EK-Cert/<http://www.nuvoton.com/security/NTC-TPM-EK-Cert/Nuvoton>
