### ISSUE TITLE
tpm2_createprimary: add unique to template

### ISSUE THREAD

**Issue by mrcdb** [tpm2-software/tpm2-tools#1237]
I wonder if the `tpm2_createprimary` tool allows somehow to specify a unique value in the template (as described in the Part 3 - Commands specs, in addition to the object attributes. Is there a way to use this functionality with current version of the tool?

**Comment by idesai** [comment]
This needs to be added. Meantime with existing tools, If you want to create multiple unique primary objects with same attributes, just use unique passphrase for each.

**Comment by mrcdb** [comment]
Thanks for the help. It is a reasonable workaround to do some tests...
