### ISSUE TITLE
Segmentation fault: Invalid opts argument to tpm2_tcti_ldr_load

### ISSUE THREAD

**Issue by safayetahmedatge** [tpm2-software/tpm2-tools#1241]
Invoking `tpm2_pcrlist` results in segmentation fault when there is no abrmd, or `/dev/tpm`, and the `TPM2TOOLS_TCTI` environment variable is not set.

Looking through the stack trace, tracked the problem to the following line:
https://github.com/tpm2-software/tpm2-tools/blob/ed4c389f71cf7f31d35cc9648785f8aea0534641/lib/tpm2_tcti_ldr.c#L131

The error print statement is trying to print `opts` and I don't see any guarantees that `opts` is a valid string pointer. I would have posted a pull request but I'm unsure what is correct behavior in this case.
1) Is `opts=NULL` valid input to `tpm2_tcti_ldr_load`?
2) Is `opts=NULL` valid input to the init function of a TCTI library?

**Comment by williamcroberts** [comment]
IIRC and IIUC: Yes and yes

**Comment by williamcroberts** [comment]
On linux `printf("%s\n", NULL);`  is valid. I see other PR's for QNX, maybe that's different? Or is the pointer just not initialized and pointing off into never-never land?

**Comment by safayetahmedatge** [comment]
Thanks @williamcroberts. Yes, I'm trying to build for QNX. In that case, I can make the changes to check for `opts==NULL` before printing it. I'll include it in the existing PR (https://github.com/tpm2-software/tpm2-tools/pull/1243).

**Comment by williamcroberts** [comment]
@safayetahmedatge that stuff is probably pervasive i'd suggest a safe macro like:

tpm2_utils.h:
```C
#define PSTR(x) x ? x : "(null)"
```
any_code.c:
```C
LOG_ERR("%s", PSTR(mystring));
```
Comment that macro so we know to keep it around and why we added it.

**Comment by safayetahmedatge** [comment]
As a rough estimate, I just ran `grep -R %s $(find . -name \*.c) | wc -l` and got back `322`. Should this be one commit?

**Comment by williamcroberts** [comment]
@safayetahmedatge you can do it as one commit for that. Seems fine.

**Comment by williamcroberts** [comment]
@safayetahmedatge where did you get with this?

**Comment by williamcroberts** [comment]
Actually looking at the other invocations of %s they look fine, but ill still leave this macro in utils for now.
