### ISSUE TITLE
Policy "AND"

### ISSUE THREAD

**Issue by ShanyYang** [tpm2-software/tpm2-tools#1249]
Hi
Do you have any idea about more than 1 policy on one entity?

For instance:
 I want to define a NV(size=8), this Nv space can only be write once and read infinitely with password. So the policy may looks like: `PolicyCommandCode(NV_Write) AND PolicyNvWritten(0)` OR `PolicyCommandCode(NV_Read) AND PolicyPassword`.

Will you write tools about these kind of scenarios? or some basic support function?

**Comment by idesai** [comment]
For OR use tpm2_policyor tool. As for AND you can start the session and use that session as an input for policy tools. NV policies will be supported soon.

**Comment by idesai** [comment]
@williamcroberts @joshuagl this issue can be closed
