### ISSUE TITLE
tpm2_unseal: unrecognized option '--context-object=0x81010001'

### ISSUE THREAD

**Issue by dnoliver** [tpm2-software/tpm2-tools#1260]
I am using latest master versions of tpm2-tools, tpm2-tss, and tpm2-abrmd, with a firmware tpm device. 

`tpm2_unseal` does not recognize the `--context-object` with a handle. 

Workaround: `tpm2_unseal -c 0x81010001` works well, it seems to only be a problem with the long parameter format

**Comment by joshuagl** [comment]
Looks like the tool and the man page don't match, the option in the code is `item-context`. We should change the tool to use the `context-object` argument.
