### ISSUE TITLE
tpm2_nvreadlock: support policy session

### ISSUE THREAD

**Issue by celesteking** [tpm2-software/tpm2-tools#1266]
Please, add policy support to this tool, the same as with nvread/write.

`tool="tpm2_nvreadlock" version="3.1.3"`

**Update**: workaround found
```bash
$ export TPM2TOOLS_DEVICE_FILE=/dev/tpm0
$ tpm2_createpolicy -P -L sha1:20 -a -e
TPM2_SE_POLICY: 0x3F6DC2F5887B87269AE11CDDF342C712B72A616AE576CF8BCB11559345153063
EXTENDED_POLICY_SESSION_HANDLE: 0x03000000
$ tpm2_getcap -c handles-loaded-session
0x03000000
$ tpm2_nvreadlock  -x 0x1500001 -a 0x1500001 -S 0x03000000
$ tpm2_getcap -c handles-loaded-session
$
```

**Comment by williamcroberts** [comment]
We're not enabling this feature on 3.X branch, as progress needs to move forward on 4.0. However, 4.0 will have session support. 3.X will be deprecated at some point, and will only be receiving bug-fixes.

I am going to drop this on 4.0, so we ensure it gets done.
