### ISSUE TITLE
tpm2_createprimary fails for latest stable version

### ISSUE THREAD

**Issue by pramodrj07** [tpm2-software/tpm2-tools#1271]
HI all,

I have complied the latest version of the tools, tss and abrmd as per the below matrix.

https://github.com/tpm2-software/tpm2-tools/wiki/Dependency-Matrix

Components - tpm2-tools version | tpm2-tss version | tpm2-abrmd version
Versions - 3.1.0 | 2.0.0 | 2.0.0

tpm2_createprimary -A e -K xyz123 -g 0x000b -G 0x0001 -C po.ctx -P xyz123
ERROR: Unable to run tpm2_createprimary

Can anyone tell me where can i find the updated command list as well?

**Comment by joshuagl** [comment]
I think you must be looking at a newer example/man page. In 3.1.0 the short form of the _hierarchy_ option is **-H**, i.e. 

> tpm2_createprimary -H e -K xyz123 -g 0x000b -G 0x0001 -C po.ctx -P xyz123

Please note, per the [README.md](https://github.com/tpm2-software/tpm2-tools/blob/master/README.md) we don't handle support requests here on Github. In future please direct queries to the mailing list: https://lists.01.org/mailman/listinfo/
