### ISSUE TITLE
Test Failed: EncryptDecrypt

### ISSUE THREAD

**Issue by GaelGuegan** [tpm2-software/tpm2-tools#1288]
Hello everyone,

I have succeeded to install the tools and use it.
Although I have been able to perform RSA encryption, I still am having some trouble to do AES symmetric encryption.

The test script : "test/integration/encryptdecrypt.sh" failed.
In a first time, it tell me that my TPM **does not have the AES capability** : 
```sh
tpm2_getcap -c commands > commands.cap
grep -q 0x164 commands.cap
if [ $? != 0 ];then
    echo "WARN: Command EncryptDecrypt is not supported by your device, skipping..."
    exit 0
fi
```

And if I comment this portion of code, it fails at the `tpm2_encryptdecrypt` line with the error code : 0x143 (command code not supported).

However my hardware chip should support the AES encryption, it is written in the spec here a screenshot :
![image](https://user-images.githubusercontent.com/32136623/51488980-46700080-1da7-11e9-88f1-c32d31be464c.png)

**Comment by williamcroberts** [comment]
The symmetric encryption interface is not always supported, and thus if you don't see it in your TPMs command interface as reported by getcap, it's not supported. The spec provides for many optional interfaces, and symmetric encryption is one of them.

For questions like these, the mailing list as documented in the README is the correct avenue.
