### ISSUE TITLE
tpm2_changeauth options

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1289]
tpm2_changeauth has some weird options... it allows for the setting of all the hierarchies or an object handle, I would recommend collapsing this interface into something simpler (ie one hiearchy or object at a time).

I'm not 100% on what a sane interface would look like.

Also -a is the parent object when changing an object, which it should probably be -C to be consistent.

**Comment by joshuagl** [comment]
Whilst we're at it we can overhaul the long options and the manual page for the new ESAPI world.
We will need to do a more general explicit long-option and manual page review for the ESAPI changes.

**Comment by williamcroberts** [comment]
Also, #1307 also points out that their is no way to change platform auth value via the tool.

**Comment by williamcroberts** [comment]
This also could be coupled with:
  - https://github.com/tpm2-software/tpm2-tools/issues/1462

As loading the object from a string can be made consistent.

**Comment by idesai** [comment]
> tpm2_changeauth has some weird options... it allows for the setting of all the hierarchies or an object handle, I would recommend collapsing this interface into something simpler (ie one hiearchy or object at a time).
> 
> I'm not 100% on what a sane interface would look like.
> 
> Also -a is the parent object when changing an object, which it should probably be -C to be consistent.

This tool used to be call tpm2_takeownership if am not mistaken and if so, taking ownership involved programming the owner, lockout and endorsement hierarchy passwords/ auth values. May be this information can go in the tpm2_changeauth manual and then user can call tpm2_changeauth thrice - one call each for setting owner, lockout and endorsement auths. That if we decide to collapse the interface to allow one auth change at a time. @williamcroberts your thoughts?
