### ISSUE TITLE
[tpm2-tools] Question about generating EK

### ISSUE THREAD

**Issue by jhand2** [tpm2-software/tpm2-tools#1297]
Why do the two following commands generate different RSA keypairs?

>tpm2_createek -G rsa -c -
>tpm2_createprimary -a e -g sha256 -G rsa

As I understand it, generating a primary key under the endorsement hierarchy using the same algorithm should product the same key. This is because the same seed is used to generate both keys with the same parameters. Am I missing something about how the TPM generates these keys?

**Comment by williamcroberts** [comment]
Every parameter in the public portion has to be the same, likely some delta.

**Comment by williamcroberts** [comment]
Looks like one delta is that default auth policy
set_default_auth_policy

**Comment by jhand2** [comment]
@williamcroberts I guess at the root of the question is why would the auth policy change the public and private key pairs (maybe this is more of a generic tpm question than a tpm2-tools question).

I thought an EK should uniquely identify a TPM. Which would mean there is only one possible EK for a given tpm. I thought RSA key generation should only depend on the RNG seed, keylength, exponent.

**Comment by williamcroberts** [comment]
primary objects are different, given the same public parameters they will produce the same key every time.

Really the EK is like anything else, just an object. The other semantics are surrounding manufacturer level details, ie they provision the EK and then make the public key available (usually as an X509). So if you're creating the EK, your the manufacturer. Somewhere, somehow this should be made available, but I don't know the details.

The tool here predates me, AFAIK, it exists to create an EK that follows some TCG spec that's linked to in the manpage.

**Comment by williamcroberts** [comment]
Also, I tried re-enabling your list membership and sent an email to:
```
sri.kundula (at) ge.com
```
It got sent back to me, is your email correct? Please feel free to contact me at william.c.roberts (at) intel.com.

**Comment by williamcroberts** [comment]
According to the list interface you're subscribed.

**Comment by jhand2** [comment]
Oh I think I know whats wrong. That email or an alias for a longer address. So I can recieve emails from the list but when I send emails it says it comes from the longer address. I'll subscribe the correct email.

Thanks!
