### ISSUE TITLE
Persisted key does not survive reboot

### ISSUE THREAD

**Issue by pandasauce** [tpm2-software/tpm2-tools#1306]
Followed the instructions here https://github.com/irtimmer/tpm2-pk11/wiki/Create-TPM-key to set up OpenSSH auth.

Creating and persisting the key:

```
$ tpm2_takeownership -c
$ tpm2_createprimary -H o -g sha256 -G rsa -C po.ctx
ObjectAttribute: 0x00030072

CreatePrimary Succeed ! Handle: 0x80ffffff
$ tpm2_create -c po.ctx -g sha256 -G rsa -u key.pub -r key.priv -K "mypass"
algorithm:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|decrypt|sign
  raw: 0x60072
type: 
  value: rsa
  raw: 0x1
  rsa: blablabla
$ tpm2_load -c po.ctx -u key.pub -r key.priv -C obj.ctx  

Load succ.
LoadedHandle: 0x80fffffe
$ tpm2_evictcontrol -A o -c obj.ctx -H 0x81010001
persistentHandle: 0x81010001
$ tpm2_sign -c obj.ctx -P "mypass" -g 0x00b -m msg.in -s sig.out
$ echo $?
0
```

This works with `tpm2-pk11` and OpenSSH.

Next, reboot:

```
$ tpm2_sign -c obj.ctx -P "mypass" -g 0x00b -m msg.in -s sig2.out
ERROR: ContextLoad Error. TPM Error:0x1df
ERROR: Unable to run tpm2_sign
```

And it no longer works with OpenSSH either, returning `C_Sign failed: 5`.

Other things I've tried:

1. Use the persistent handle `0x81010001` instead of `obj.ctx`, doesn't work
2. Clear the TPM, persist the primary key at `0x81010000`
3. Create RSA key, load it, persist at `0x81010001`, test it, everything works
4. As above, reboot, it fails with both `-c obj.ctx` and `-k 0x81010001`
5. `tpm2_load` the RSA key, it succeeds with `Load succ. / LoadedHandle: 0x80ffffff`: but signing fails like this for both `-c` and `-k`:

```
ERROR: Sys_Sign failed, error code: 0x84
ERROR: Unable to run tpm2_sign
```

For `-k 0x80ffffff` which in my understanding should refer to the same key at a transient handle:

```
ERROR:tcti:src/util/io.c:102:write_all() failed to write to fd 3: Invalid argument 
ERROR:tcti:src/tss2-tcti/tcti-device.c:86:tcti_device_transmit() wrong number of bytes written. Expected 14, wrote 0. 
ERROR: Sys_ReadPublic failed, error code: 0xa000a
ERROR: Unable to run tpm2_sign
```

User documentation for TPM2 is pretty much nonexistent when it comes to something like this, but my understanding is that once the key is persisted, I should be able to use both `-c obj.ctx` and `-k 0x81010001` as they will both refer to the same key that is persisted at `0x81010001`. This holds true as long as I don't reboot.

Am I missing something here?

**Comment by pandasauce** [comment]
Interestingly, the same instructions (https://github.com/irtimmer/tpm2-pk11/wiki/Create-TPM-key) work on a different laptop with the same TPM. The only differences I managed to find are below.

Laptop where it works:

```
$ tpm2_getcap -c properties-variable
TPM_PT_STARTUP_CLEAR:
  orderly: clear
TPM_PT_LOCKOUT_COUNTER: 0x00000002
```

Where it doesn't:

```
$ tpm2_getcap -c properties-variable
TPM_PT_STARTUP_CLEAR:
  orderly: set
TPM_PT_LOCKOUT_COUNTER: 0x00000000
```

**Comment by pandasauce** [comment]
Confirmed this to be a Dell firmware issue on XPS 15, not caused by tpm2-tools.

**Comment by qq8512852** [comment]
I meet the same problem on my TPM device with Linux IOT hardware.

**Comment by williamcroberts** [comment]
> I meet the same problem on my TPM device with Linux IOT hardware.

Are you on the same or similar hardware as the original poster. They stated that they, "Confirmed this to be a Dell firmware issue on XPS 15".

**Comment by qq8512852** [comment]
> 

no, I'm running the tpm2-tool with real TPM  chip on Linux IOT device.

**Comment by williamcroberts** [comment]
real TPM as in a discrete TPM?

After you "persist" the key try using tpm2_getcap to list the peristent-handles and verify it was persisted.

**Comment by qq8512852** [comment]
> real TPM as in a discrete TPM?
> 
> After you "persist" the key try using tpm2_getcap to list the peristent-handles and verify it was persisted.

yes, a physical TPM chip.
OK, I'll try
