### ISSUE TITLE
Setting of platformauth value via tpm2_changeauth or new command

### ISSUE THREAD

**Issue by RaymWong** [tpm2-software/tpm2-tools#1307]
Hi,
Currently the platformauth value is NULL after reboot. 
This will allow any user to use tpm2_clear -p to clear the TPM easily.
It would be very useful to include the option to change the platformauth value via separate command or add one more option in the tpm2_changeauth command to set the platformauth value. 
User may use this command during the boot cycle in Linux to set the platformauth value to a random value depends on application.

**Comment by williamcroberts** [comment]
tpm2_changeauth supports changing the platform hiearchy option via the -p|-P options.

**Comment by RaymWong** [comment]
According to the examples  in man page, The tpm2_changeauth -p|-P options are used to modify the transient object auth value.  
How could the -p|-P be used to change   platformauth value? Kindly advise. Many Thanks.

**Comment by williamcroberts** [comment]
> According to the examples in man page, The tpm2_changeauth -p|-P options are used to modify the transient object auth value.
> How could the -p|-P be used to change platformauth value? Kindly advise. Many Thanks.

That's because you're right and it cant :+1: Iv'e updated this ticket with that information so we when overhaul the tool we don't forget this: https://github.com/tpm2-software/tpm2-tools/issues/1289

**Comment by idesai** [comment]
@williamcroberts, @RaymWong typically platform hierarchy auth is set by the platform firmware in a real TPM. I guess it may still be useful when working with a simulator...may be.
But the general idea is that platform hierarchy is strictly managed within platform firmware window.

**Comment by williamcroberts** [comment]
> But the general idea is that platform hierarchy is strictly managed within platform firmware window.

Should still be modifiable by the tool, perhaps someone ports these tools to a UEFI or GRUB shell and wants to do things.

**Comment by williamcroberts** [comment]
#1289 actually has suggestions around fixing this terrible interface changeauth has morphed

**Comment by RaymWong** [comment]
> @williamcroberts, @RaymWong typically platform hierarchy auth is set by the platform firmware in a real TPM. I guess it may still be useful when working with a simulator...may be.
> But the general idea is that platform hierarchy is strictly managed within platform firmware window.

Yes it's supposed to be managed in platform firmware during boot. 
It is also useful for systems that do not implement bootloader to show this feature especially in the case of real TPM with system like raspberry pi3 etc. Perhaps set the platform auth value in early start of OS to prevent user from clearing the TPM using tpm2_clear -p command. User only allowed to clear using the lock out value which make more sense. Its definately a desirable feature to add in this.
Currently the default null value which allow user to clear TPM easily which is not desirable. Many thanks.
