### ISSUE TITLE
Unable to create primary key with tpm2_createprimary -- "ERROR: Unable to run tpm2_createprimary."

### ISSUE THREAD

**Issue by gblewis1** [tpm2-software/tpm2-tools#1308]
Tpm2-tools version: 3.1.3
Tpm2-tss version: 2.2.0
TPM: IBM TPM simulator version 974
Operating system: Ubuntu 16.04.5 LTS

Command: tpm2_createprimary --kalg=rsa --hierarchy=o --context=prim.ctx
Output: ERROR: Unable to run tpm2_createprimary

**Comment by gblewis1** [comment]
Tpm2-abrmd version: 2.1.0

**Comment by williamcroberts** [comment]
Can you run it with `-V`?
Is this some intermittent issue?
We do most of our testing on these two distro versions.

**Comment by gblewis1** [comment]
Output with -V is: ERROR on line: "168" in file: "tools/tpm2_tool.c": Unable to run tpm2_createprimary

Context for that line is:

    /*
     * Call the specific tool, all tools implement this function instead of
     * 'main'.
     */
    ret = tpm2_tool_onrun(sapi_context, flags) ? 1 : 0;
    if (ret != 0) {
        LOG_ERR("Unable to run %s", argv[0]);
    }

Our test setup is a little unusual.. before running full integration we do some sanity checks of the tpm2 tool stack in https://hub.docker.com/r/solita/ubuntu-systemd/ which is a full ubuntu+systemd setup running in Docker.  If this turns out to be an invalid scenario I can move those tests into the full integration test.  It worked with prior versions of the tpm2 stack.

In this test, it is not an intermittent error.

**Comment by williamcroberts** [comment]
The fact that it isn't throwing any other errors probably means a silent failure on dealing with options... i'd throw it in a debugger

**Comment by gblewis1** [comment]
Note, same error in full VM (vagrant) test with TPM simulator.

No errors from tpm2-abrmd.  tpm2-abrmd2.service:

```
[Unit]
Description=TPM2 Access Broker and Resource Management Daemon

[Service]
Type=dbus
Restart=always
RestartSec=5
BusName=com.intel.tss2.Tabrmd
StandardOutput=syslog
ExecStart=/usr/sbin/tpm2-abrmd --tcti=libtss2-tcti-mssim.so
User=tss

[Install]
WantedBy=multi-user.target
```

**Comment by gblewis1** [comment]
Adding --halg=sha256 fixed it.  

This check failed in tpm2_createprimary.c failed:

  `if(ctx.flags.A == 1 && ctx.flags.g == 1 && ctx.flags.G == 1)`

This is contrary to the documentation which says a default hash algorithm of sha256 will be used if not specified, and it looks like this tool could use a more descriptive error message.

**Comment by williamcroberts** [comment]
Looks like a bug.

**Comment by joshuagl** [comment]
> This is contrary to the documentation which says a default hash algorithm of sha256 will be used if not specified, and it looks like this tool could use a more descriptive error message.

I think you're reading the documentation for a newer version, that assertion isn't made in the 3.X docs. I agree that this is undesirable behaviour and could use a more descriptive error message  - both of these issues have been resolved on the master branch.
