### ISSUE TITLE
tpm2_getcap -c properties-fixed segfaults

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-tools#1311]
When I run `tpm2_getcap -c properties-variable` everything works, when I run `tpm2_getcap -c properties-variable` fixed the tool dies with a segault.

Running it in gdb points it to:
```
Thread 1 "tpm2_getcap" received signal SIGSEGV, Segmentation fault.
0x004041a4 in tpm2_capability_get (ectx=0x7efff08f, ectx@entry=0x438400, capability=6, property=256, count=2130702480, capability_data=0x7efff0e8, capability_data@entry=0x7efff0e0) at lib/tpm2_capability.c:134
134                     updated->data.algorithms.algProperties[i] =
```
According to strace it seems to be a bit stuck in a loop:
[getcap.strace.txt](https://github.com/tpm2-software/tpm2-tools/files/2852970/getcap.strace.txt)

Tested with a physical tpm

**Comment by williamcroberts** [comment]
Interesting. I'm not sure how I can replicate the issue to fix it, would you like to send a patch up?

**Comment by PeterHuewe** [comment]
Please find the full esapi debug trace attached - maybe you can see it in there?
[tpm2_getcap.txt](https://github.com/tpm2-software/tpm2-tools/files/2853036/tpm2_getcap.txt)

**Comment by PeterHuewe** [comment]
It seems to be stuck at one single property:
```
tpm2_getcap -c properties-fixed -V
INFO on line: "111" in file: "lib/tpm2_capability.c": GetCapability: capability: 0x6, property: 0x100
INFO on line: "111" in file: "lib/tpm2_capability.c": GetCapability: capability: 0x6, property: 0x100
INFO on line: "111" in file: "lib/tpm2_capability.c": GetCapability: capability: 0x6, property: 0x100
INFO on line: "111" in file: "lib/tpm2_capability.c": GetCapability: capability: 0x6, property: 0x100
INFO on line: "111" in file: "lib/tpm2_capability.c": GetCapability: capability: 0x6, property: 0x100
INFO on line: "111" in file: "lib/tpm2_capability.c": GetCapability: capability: 0x6, property: 0x100
....
```

**Comment by PeterHuewe** [comment]
What is interesting is that when entering the function, count is 127
`Thread 1 "tpm2_getcap" hit Breakpoint 1, tpm2_capability_get (ectx=ectx@entry=0x438400, capability=6, property=256, count=127, capability_data=0x7efff0e8, capability_data@entry=0x7efff0e0) at lib/tpm2_capability.c:92`

but after calling Esys_GetCapability count is **2130702480**

```
Run till exit from #0  Esys_GetCapability (esysContext=0x438400, shandle1=<optimized out>, shandle2=<optimized out>, shandle3=<optimized out>, capability=6, property=256, propertyCount=127, moreData=0x7efff08f "", 
    capabilityData=0x7efff090) at src/tss2-esys/api/Esys_GetCapability.c:92
tpm2_capability_get (ectx=0x7efff08f, ectx@entry=0x438400, capability=6, property=256, count=2130702480, capability_data=0x7efff0e8, capability_data@entry=0x7efff0e0) at lib/tpm2_capability.c:111
111             LOG_INFO("GetCapability: capability: 0x%x, property: 0x%x", capability, property);
```

**Comment by PeterHuewe** [comment]
https://github.com/tpm2-software/tpm2-tools/blob/master/lib/tpm2_capability.c#L121 looks interesting.
Why is there only space for 1 element allocated? Shouldn't it be for the 'exisiting' + 'fetched' capabilities?

However even if I change it, my TPM returns endlessly "moredata" = 1

**Comment by webmeister** [comment]
As far as I can tell, more things are broken in tpm2_capability_get than just this issue. @cplappert's patch fixes much of it, but for example it is still wrong to access data.algorithms.algProperties if capability != TPM2_CAP_ALGS.

I've got a patch that fixes all the issues I found. I'll upload it as soon as I manage to run some basic tests with it.

**Comment by cplappert** [comment]
That's true. The original software seemed to assume that all data was same length. We will now also fix this issue.
