### ISSUE TITLE
ls

### ISSUE THREAD

**Issue by leeehui** [tpm2-software/tpm2-tools#1317]
I can't find the definition of 
tpm2-tools/lib/files.h: bool files_load_public(const char *path, TPM2B_PUBLIC *public);
can anyone help? thanks

**Comment by martinezjavier** [comment]
@leeehui is in https://github.com/tpm2-software/tpm2-tools/blob/master/lib/files.c#L713.

Please use the mailing list for these questions instead of filing issues.

**Comment by leeehui** [comment]
got it, thanks.
