### ISSUE TITLE
tpm2_rsaencrypt & rsadecrypt with handle number not working

### ISSUE THREAD

**Issue by RaymWong** [tpm2-software/tpm2-tools#1323]
The **tpm2_rsaencrypt** and **tpm2_rsadecrypt** with handle number input seems not working
1.) Steps to re-produce
a.) Create primary key and user key 
echo "1234567AAAA" > datain.txt
tpm2_clear -p
tpm2_changeauth -o owner123 -e endorsement123 -l lockout123
tpm2_createprimary -a o -P owner123 -p RSAprimary123 -g sha256 -G rsa -o RSAprimary.ctx
tpm2_create -C RSAprimary.ctx -P RSAprimary123 -p RSAleaf123 -g sha256 -G rsa -r RSAPriv.key -u RSAPub.key
tpm2_load -C RSAprimary.ctx -P RSAprimary123 -u RSAPub.key -r RSAPriv.key -n key_name_structure.data -o RSAkeycontext.ctx
tpm2_evictcontrol -a o -c RSAkeycontext.ctx -p 0x81000005 -P owner123

b.) Encrypt and decrypt with handle number Failed
tpm2_rsaencrypt -c 0x81000005 -o data_encrypted.txt datain.txt
tpm2_rsadecrypt -c 0x81000005 -p RSAleaf123  -I data_encrypted.txt -o dataout.txt

Error Message
WARNING:esys:src/tss2-esys/api/Esys_RSA_Encrypt.c:335:Esys_RSA_Encrypt_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_RSA_Encrypt.c:131:Esys_RSA_Encrypt() Esys Finish ErrorCode (0x00000184) 
ERROR: Esys_RSA_Encrypt(0x184) - tpm:handle(1):value is out of range or is not correct for the context
ERROR: Unable to run tpm2_rsaencrypt

**Comment by joshuagl** [comment]
Thanks for the bug report. This was an oversight on my part when porting tpm2_tools to tss2-esys. I've proposed a fix in #1325

**Comment by kuldeepmarker-eaton** [comment]
WARNING:esys:../tpm2-tss-3.2.0/src/tss2-esys/api/Esys_RSA_Decrypt.c:305:Esys_RSA_Decrypt_Finish() Received TPM Error
ERROR:esys:../tpm2-tss-3.2.0/src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x00000184)
Esys_RSA_Decrypt error: 0x184

I am facing this error when I called Esys_RSA_Decrypt API in my application code.
@joshuagl @williamcroberts any idea what I am missing or is it related to this issue.

**Comment by Ravindra1618** [comment]
WARNING:esys:src/tss2-esys/api/Esys_RSA_Encrypt.c:302:Esys_RSA_Encrypt_Finish() Received TPM Error 

ERROR:esys:src/tss2-esys/api/Esys_RSA_Encrypt.c:103:Esys_RSA_Encrypt() Esys Finish ErrorCode (0x0000019c) 

i am facing same issue any idea

**Comment by JuergenReppSIT** [comment]
@Ravindra1618 Could you please attach the inPublic of the RSA key you are using for Esys_RSA_Encrypt.

**Comment by JuergenReppSIT** [comment]
@Ravindra1618 Sorry I thought that it was a tss and not a tool issue. So could you please attach the output of:
`tpm2_readpublic -c your_rsa_key.ctx`
and the plaintext size.

**Comment by Ravindra1618** [comment]
let public = PublicBuilder::new()

    .with_public_algorithm(PublicAlgorithm::KeyedHash)

    .with_name_hashing_algorithm(HashingAlgorithm::Sha256)

    .with_object_attributes(object_attributes)

    .with_keyed_hash_parameters(PublicKeyedHashParameters::new(KeyedHashScheme::HMAC_SHA_256))

    .with_keyed_hash_unique_identifier(Digest::default())

    .build()

    .unwrap();

This public i am using for key handle and mainly i am getting error in keyhandle 
if anyone having  code regarding this key handle function please share here .

**Comment by JuergenReppSIT** [comment]
You can not use a keyedhash for RSA encrypt. You have to create a RSA key. If you map the following esapi inPublic C declaration to the rust wrappers it should work:
```
  TPM2B_PUBLIC inPublic = {
        .size = 0,
        .publicArea = {
            .type = TPM2_ALG_RSA,
            .nameAlg = TPM2_ALG_SHA256,
            .objectAttributes = (TPMA_OBJECT_USERWITHAUTH |
                                 TPMA_OBJECT_DECRYPT |
                                 TPMA_OBJECT_FIXEDTPM |
                                 TPMA_OBJECT_FIXEDPARENT |
                                 TPMA_OBJECT_SENSITIVEDATAORIGIN),
            .authPolicy = {
                 .size = 0,
             },
            .parameters.rsaDetail = {
                 .symmetric = {
                     .algorithm = TPM2_ALG_NULL},
                 .scheme = { .scheme = TPM2_ALG_RSAES },
                 .keyBits = 2048,
                 .exponent = 0,
             },
            .unique.rsa = {
                 .size = 0,
                 .buffer = {},
             },
        },
    };
```

**Comment by Ravindra1618** [comment]
fn main() {

    // Initialize TSS context and connect to TPM

    let device_conf: DeviceConfig = DeviceConfig::default();

    let mut context: Context = Context::new(TctiNameConf::Device(device_conf)).unwrap();

    
    // Create a primary key

  let key_handle = context.create_primary(

        Hierarchy::Owner,

        PublicBuilder::new()

            .with_public_algorithm(PublicAlgorithm::Rsa)

            .with_name_hashing_algorithm(HashingAlgorithm::Sha256)

            .with_object_attributes(

                ObjectAttributesBuilder::new()

                    .with_sign_encrypt(true)

                    .with_sensitive_data_origin(true)

                    .with_user_with_auth(true)

                    .build()

                    .unwrap(),

            )

            

            .build()

            .unwrap(),

        None,

        None,

        None,

        None,

    ).unwrap().key_handle.into();



   // Message to be encrypted

    let message = b"Hello, world!".to_vec();

    let plaintext = PublicKeyRsa::try_from(message).unwrap();



    // Encryption scheme

    let scheme = RsaDecryptionScheme::create(

        RsaDecryptAlgorithm::Oaep,

        Some(HashingAlgorithm::Sha256),

    ).unwrap();



    // Encrypt the message using the key handle and encryption scheme

    let ciphertext = context.rsa_encrypt(key_handle, plaintext, scheme, Data::default()).unwrap();



    println!("{:?}", ciphertext);

}


The error which i am facing here is 

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WrapperError(ParamsMissing)'

any changes in code for that error

**Comment by JuergenReppSIT** [comment]
@Ravindra1618 since this is not a tpm2 tool issue it might be useful to open an issue e.g. on https://github.com/parallaxsecond/rust-tss-esapi
