### ISSUE TITLE
tpm2_policysecret fails when no auth passed

### ISSUE THREAD

**Issue by xyzhao2018** [tpm2-software/tpm2-tools#1326]
The example shown in https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_policysecret.1.md has bug that no owner auth passed in the following command and result in the error.  
$ tpm2_policysecret -S session.ctx -c $TPM_RH_OWNER -o secret.policy --tcti=mssim
WARNING:esys:src/tss2-esys/api/Esys_PolicySecret.c:379:Esys_PolicySecret_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_PolicySecret.c:147:Esys_PolicySecret() Esys Finish ErrorCode (0x00000982)
ERROR: Esys_PolicySecret(0x982) - tpm:session(1):inconsistent attributes
ERROR: Could not build policysecret
ERROR: Unable to run tpm2_policysecret

**Comment by joshuagl** [comment]
I think the bug here is not so much in the manual page, but that the tool expects an auth value (even when it might be true that no auth value is set).

@idesai would you agree?

**Comment by idesai** [comment]
@joshuagl I tried it at my end without the password and it works just fine. Fixed the man page as well. Thanks.

**Comment by idesai** [comment]
One caveat to my above statement, i found it working with and without the password with an earlier version of the tool: tpm2_policysecret version="3.0.2-731-gf2182cf" tctis="dynamic" tcti-default=tabrmd dlclose=enabled
@joshuagl @williamcroberts @AndreasFuchsSIT do you think this bug may have been introduced after esys integration, in that, there may be a difference in how the password/sensitive part of the command buffer may have been populated? There is also another (related bug I think) with unsealing tool.

**Comment by joshuagl** [comment]
This does indeed look like a bug introduced during the ESAPI port. Thanks for investigating @idesai
