### ISSUE TITLE
SAPI support removed?

### ISSUE THREAD

**Issue by tomoveu** [tpm2-software/tpm2-tools#1327]
Hello,

My team and I are working on a R&D project, which started back in 2017 and throughout 2018 we used the _tpm2-tools_ with SAPI for testing. However, the latest commits on master replace SAPI with ESAPI, which breaks our testing. The commit messages contain no reasoning of this change and we are puzzled what is the technical motivation behind it.

Could you please explain why the SAPI support is being removed and if it is coming back?

Best regards,
Dimi

**Comment by joshuagl** [comment]
The technical motivation is that ESAPI makes some of the functionality we wish to implement much simpler, i.e. HMAC sessions (#956). Are there tools which are broken in your testing? Please let us know which tools and workflows are broken and we will work on fixes for them.

If SAPI support is a requirement you should be able to continue to use the 3.X branch and releases.

**Comment by williamcroberts** [comment]
Switching from SAPI to ESAPI shouldn't break anything. I'd like to know what broke, specifically, and how to replicate it in a test. From there we can fix it and ensure that we don't regress in the future. Do you have steps for reproducing?

**Comment by tomoveu** [comment]
Hello William and Josh,

Thank you both for recognizing the importance of this issue!

Replacing SAPI with ESAPI brought changes to the API of most _tpm2-tools_. I would give "tpm2_hierarchy"[1] as one of the impacted tools. We have break of API at tpm2_hierarchy_create_primary(), which now has an extra argument "tpm2_session *sess". 

Such change is forcing everyone who was using SAPI by now to migrate to ESAPI and ESYS context. Could we instead just have both tpm2-tools variants. Like tools/esapi and tools/sapi, and modify the build process?

Our motivation for such thinking is that ESAPI is essentially using SAPI and both APIs naturally co-exist.

[1] https://github.com/tpm2-software/tpm2-tools/commit/872f457fbd677108ec474377c8e80687531a93c5#diff-bf85a1dbd9cb77bec38bd10041a84fe8R136

**Comment by williamcroberts** [comment]
We have been breaking the API of the command line interface for some time and are making no backwards compatible claims until 4.0 release.

Having those APIs co-exist is not feasible, because we would need to implement all of the session logic, hmac'ing and crypto, that is already included in ESAPI. The reason we switched to ESAPI is to avoid this.

If you need a stable API, I would recommend working off of the 3.X releases, but understand that the bulk of the work is on master heading towards the 4.0 release, and having the command line interface frozen at that point. Ie 4.0 is going to be intentionally different than all previous releases. I understand this is challenging at times, but it will allow us to move into the future more quickly, with a better, more easy to use toolset.

**Comment by williamcroberts** [comment]
Is their some workflow for you that becomes unsupported or is just the annoyance of updating your scripts?

**Comment by tomoveu** [comment]
> Is their some workflow for you that becomes unsupported or is just the annoyance of updating your scripts?

I do not understand your question about "scripts", all APIs in discussion are written in C.

**Comment by tomoveu** [comment]
> We have been breaking the API of the command line interface for some time and are making no backwards compatible claims until 4.0 release.
> 
> Having those APIs co-exist is not feasible, because we would need to implement all of the session logic, hmac'ing and crypto, that is already included in ESAPI. The reason we switched to ESAPI is to avoid this.
> 
> If you need a stable API, I would recommend working off of the 3.X releases, but understand that the bulk of the work is on master heading towards the 4.0 release, and having the command line interface frozen at that point. Ie 4.0 is going to be intentionally different than all previous releases. I understand this is challenging at times, but it will allow us to move into the future more quickly, with a better, more easy to use toolset.

Bottom line: The [most significant dependency](https://github.com/tpm2-software/tpm2-tools/blame/d70cb7f10ffa657d368f9c29434889b476a5426c/README.md#L39) of this project is changed. Design choices and API consequences does not matter until "4.0". The target group for tpm2-tools are end-users, not developers.

Thanks for responding and providing this information!

**Comment by martinezjavier** [comment]
> I do not understand your question about "scripts", all APIs in discussion are written in C.

What @williamcroberts meant is that you are probably using the `tpm2-tools` from a shell script, and if that's the case then should take into account the non-backward compatible changes from the `3.0` release.

If you were using C code directly, then makes more sense to use the `API` provided by the `tpm2-tss` libraries (that way you can choose which layer is more appropriate for your use case).

As others explained, targeting the `ESAPI` instead of the `SAPI` has many benefits and since backward compatibility will be break for `4.0` anyways, using `ESAPI` allows to remove a lot of boiler plate code.

**Comment by martinezjavier** [comment]
> Bottom line: The [most significant dependency](https://github.com/tpm2-software/tpm2-tools/blame/d70cb7f10ffa657d368f9c29434889b476a5426c/README.md#L39) of this project is changed.

Yes, but the dependency will be also changed for `4.0`:

https://github.com/tpm2-software/tpm2-tools/commit/53bc4e6a015646a9fdc17ee066a0e23122ad665f

**Comment by tomoveu** [comment]
> > I do not understand your question about "scripts", all APIs in discussion are written in C.
> 
> What @williamcroberts meant is that you are probably using the `tpm2-tools` from a shell script

OK, so this is a wrong assumption and it confirms that tpm2-tools targets end-users, not developers.

We have been working to integrate tpm2-tools in our own (let's call it) test framework for TPM2 application. For the TPM2 application *itself* we are using SAPI directly.

Thanks for your input @martinezjavier !

**Comment by tomoveu** [comment]
> > Bottom line: The [most significant dependency](https://github.com/tpm2-software/tpm2-tools/blame/d70cb7f10ffa657d368f9c29434889b476a5426c/README.md#L39) of this project is changed.
> 
> Yes, but the dependency will be also changed for `4.0`:
> 
> see commit [53bc4e6](https://github.com/tpm2-software/tpm2-tools/commit/53bc4e6a015646a9fdc17ee066a0e23122ad665f) ("docs: update to reference ESAPI, not SAPI").

Personally, I think we need more real application to boost TPM adoption, therefore finding out that tpm2-tools is not meant for that is actually disappointing.

The bottom line for the bigger picture: "tpm2-tools is OSS project not meant to be adopted or integrated, but only to be redistributed as toolset".

Maybe this could be somewhere in the README or Wiki, so other developers would not come asking about broken dependencies and APIs in the future?
