### ISSUE TITLE
Fix option conflicts uncovered by PR #1335

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-tools#1336]
PR #1335 uncovered some previously undetected option conflicts. These need to be addressed by either renaming the option to the correct name or adding it to the ignore list if it is a false positive. The following options are affected:
```
group: session:
	tools: ['tpm2_startauthsession', 'tpm2_policyrestart']
	conflicts: set(['k', 'halg', 'g', 'key'])
group: object:
	tools: ['tpm2_makecredential', 'tpm2_load', 'tpm2_unseal', 'tpm2_readpublic', 'tpm2_changeauth', 'tpm2_activatecredential', 'tpm2_createprimary', 'tpm2_loadexternal', 'tpm2_create']
	conflicts: set(['credentialkey-context', 'credentialkey-auth', 'E', 'certinfo-data', 'credentialedkey-context', 'in-file', 'credentialedkey-auth', 'credential-secret', 'auth-hierarchy', 'key-alg', 'parent-context', 'auth-object', 'object-auth', 'object-context', 'unique-data', 'enckey', 'serialized-handle', 't', 'context', 'e'])
group: duplication:
	tools: ['tpm2_duplicate', 'tpm2_import']
	conflicts: set(['output-key-file', 'seed', 'pubfile', 'duplicate-key-private', 'inner-wrapper-alg', 'sym-alg-file', 'auth-parent', 'policy-file', 'G', 'object-attributes', 'K', 'c', 'L', 'P', 'output-enc-seed-file', 'halg', 'in-file', 'a', 'parent-pubkey', 'algorithm', 'k', 'o', 'u', 'privfile', 'context', 'input-key-file'])
group: asymmetric:
	tools: ['tpm2_rsaencrypt', 'tpm2_rsadecrypt']
	conflicts: set(['i', 'auth-key', 'in-file', 'p'])
group: symmetric:
	tools: ['tpm2_hmac', 'tpm2_encryptdecrypt', 'tpm2_hash']
	conflicts: set(['C', 'e', 'P', 'c', 'p', 'pad', 'in-file'])
group: random:
	tools: ['tpm2_getrandom', 'tpm2_stirrandom']
	conflicts: set(['out-file', 'force', 'o', 'f'])
group: attestation:
	tools: ['tpm2_certify', 'tpm2_quote']
	conflicts: set(['o', 'c', 'auth-ak', 'sel-list', 'signingkey-auth', 'L', 'certifiedkey-auth', 'l', 'q', 'signingkey-context', 'out-attest-file', 'sig-file', 'ak-context', 'certifiedkey-context', 'qualify-data', 'id-list'])
group: signing:
	tools: ['tpm2_verifysignature', 'tpm2_sign']
	conflicts: set(['out-sig', 'auth-key', 'o', 'sig-scheme', 'p'])
group: integrity:
	tools: ['tpm2_pcrreset', 'tpm2_pcrevent', 'tpm2_pcrlist', 'tpm2_pcrextend', 'tpm2_pcrallocate']
	conflicts: set(['x', 'auth-pcr', 'sel-list', 'L', 'o', 'auth-platform', 'pcr-index', 'out-file'])
group: ea:
	tools: ['tpm2_policyor', 'tpm2_createpolicy', 'tpm2_policylocality', 'tpm2_policyduplicationselect', 'tpm2_policycommandcode', 'tpm2_policyauthorize', 'tpm2_policysecret', 'tpm2_policypassword', 'tpm2_policypcr']
	conflicts: set(['in-policy-file', 'g', 'policy-digest-alg', 'object-name', 'qualify-data'])
group: hierarchy:
	tools: ['tpm2_clear', 'tpm2_clearcontrol']
	conflicts: set(['a', 'auth-lockout', 'L', 'auth', 'platform', 'auth-handle'])
group: context:
	tools: ['tpm2_evictcontrol', 'tpm2_flushcontext']
	conflicts: set(['transient-object', 'loaded-session', 'o', 'saved-session', 'P', 's', 't', 'output', 'auth-hierarchy', 'l'])
group: nv:
	tools: ['tpm2_nvlist', 'tpm2_nvreadlock', 'tpm2_nvincrement', 'tpm2_nvwrite', 'tpm2_nvread', 'tpm2_nvdefine', 'tpm2_nvrelease']
	conflicts: set(['C', 'policy-file', 'L', 'o', 'auth-index', 'p', 'out-file'])
group: testing:
	tools: ['tpm2_gettestresult', 'tpm2_selftest', 'tpm2_incrementalselftest']
	conflicts: set(['f', 'fulltest'])
```

**Comment by diabonas** [comment]
Here is a more structured list of the affected options:

**session**
- [x] `-a`/`--auth-policy-session`
- [x] `-g`/`--policy-digest-alg`

**object**
- [x] `--auth-endorse` *(check capitalisation `-e`/`-E`)*
- [x] `--auth-hierarchy`
- [x] `--auth-object` *(check capitalisation `-p`/`-P`)*
- [ ] `--current-endorsement-passwd`
- [ ] `--current-handle-passwd`
- [ ] `--current-lockout-passwd`
- [ ] `-O`/`--current-owner-passwd`
- [ ] `--enc-key`
- [x] `--format`
- [x] `-I` → `--in-file`, addressed by #1334
- [ ] `--item-context`
- [ ] `--key-alg` → **should probably be `--kalg`**
- [ ] `--key-parent-context`
- [ ] `--new-endorsement-passwd`
- [ ] `--new-handle-passwd`
- [ ] `-l`/`--new-lockout-passwd`
- [ ] `--new-owner-passwd`
- [ ] `--out-context-name`
- [x] `-F`/`--pcr-input-file`
- [x] `--set-list`

**asymmetric**
- [x] `-p`/`--auth-key` *(check capitalisation `-p`/`-P`)*
- [x] `-I`/`--in-file`

**symmetric**
- [ ] `-p`/`-P` → `--auth-key`, *check capitalisation*
- [x] `-I`/`--in-file`
- [ ] `-c`/`-C` → `--key-context`, *check capitalisation*

**attestation**
- [ ] `--ak-context`
- [ ] `-a`/`--attest-file`
- [x] `--auth-ak`
- [x] `--auth-key` *(check capitalisation `-p`/`-P`)*
- [x] `--auth-object` *(check capitalisation `-p`/`-P`)*
- [ ] `-l`/`--id-list`
- [ ] `--obj-context`
- [ ] `-q`/`--qualify-data`
- [x] `-L`/`--sel-list`
- [ ] `--sig-file`
- [ ] `-G`/`--sig-hash-algorithm`
- [x] `-c`/`--key-context` *(check capitalisation `-c`/`-C`)*

**signing**
- [x] `-p`/`--auth-key` *(check capitalisation `-p`/`-P`)*

**integrity**
- [ ] `-P`/`--auth-pcr`
- [x] `-o`/`--out-file` → **called `-f` in `tpm2_getmanufec` and `tpm2_nvread`**
- [ ] `-i`/`--pcr-index`
- [x] `-L`/`--sel-list`

**ea**
- [x] `-a`/`--auth-policy-session`
- [ ] `--input-policy-file`
- [x] `-g`/`--policy-digest-alg`
- [ ] `-P`/`--policy-pcr`

**context**
- [x] `-P`/`--auth-hierarchy` 
- [ ] `-l`/`--loaded-session`
- [ ] `-s`/`--saved-session`
- [ ] `-t`/`--transient-object`

**nv**
- [ ] `-p`/`--auth-index`
- [ ] `-f`/`--out-file` → **should probably be `-o`**
- [x] `--policy-file` → **output policy file is sometimes called `-f`, other times it is `-o`**

The options marked with a tick are found in a different group and are thus probably ok, while the others a unique to the whole tool suite. Sometimes short options have different capitalisation depending on whether they refer to the parent or the child object, e.g. `--auth-endorse`/`-p`/`-P`. In these cases, I haven't checked whether the capitalisation is used correctly, but noted the fact next to the corresponding option.

**Comment by diabonas** [comment]
Only tangentially related to this issue, but `--auth-lockout` is `-L` in `tpm2_clear` and `tpm2_clearlock`, but `-p` in `tpm2_dictionarylockout`.

**Comment by williamcroberts** [comment]
We're doing a full audit in #1042 and adjusting the options, we'll revisit this when we close #1042 and I re-enable the option analyser.

**Comment by williamcroberts** [comment]
Now that we're through #1042, I don't see anything that the tool reports that is of interest or makes sense. I think the tool has now outlived its purpose and should be removed.
