### ISSUE TITLE
tpm2-tools commands fail on libtss2-esys.so.0: cannot open shared object file: No such file or directory after install 

### ISSUE THREAD

**Issue by ambtid** [tpm2-software/tpm2-tools#1339]
Hi i try to install tpm2-tools but after the install all command fail on this error
`

```
 error while loading shared libraries: libtss2-esys.so.0: cannot open shared object file: No such file or directory
```
i do this steps in the install 

```
git clone https://github.com/tpm2-software/tpm2-tss.git
cd tpm2-tss
./bootstrap
./configure
make check
sudo make install

git clone https://github.com/tpm2-software/tpm2-abrmd.git
cd tpm2-abrmd
./bootstrap
./configure --enable-unit --with-dbuspolicydir=/etc/dbus-1/system.d
dbus-launch make check
sudo make install

git clone https://github.com/tpm2-software/tpm2-tools.git
cd tpm2-tools
./bootstrap
./configure --enable-unit
make check
sudo make install
```
NOTE: i do the same steps before and success to make tpm2-tools work.

**Comment by lestums** [comment]
Do you have /usr/local/lib (or insert the path where your libraries are installed) declared in any file of /etc/ld.so.conf.d ?

If not, add it and run `ldconfig`

A temporary workaround (that i use when testing outside of my docker image) : `LD_LIBRARY_PATH=/usr/local/lib tpm2_...`

**Comment by williamcroberts** [comment]
This isn't really a tools bug, but did you get it fixed? You likely need to run `ldconfig` as root or the other suggestions @lestums had.

**Comment by williamcroberts** [comment]
Also make sure you didn't disable ESAPI during the build. If you have other questions, the mailing list is the place for help.
