### ISSUE TITLE
tpm2_sign should allow signature algorithm / scheme TPM2_ALG_RSAPSS

### ISSUE THREAD

**Issue by zt-initech** [tpm2-software/tpm2-tools#1340]
https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_sign.c#L86 (`sign_and_save`)

calls

https://github.com/tpm2-software/tpm2-tools/blob/master/lib/tpm2_alg_util.c#L819 (`get_signature_scheme`)

for RSA keys always sets `scheme` to `TPM2_ALG_RSASSA`.

I would like to use `TPM2_ALG_RSAPSS` instead.

tpm2_sign should have a command line argument to enable this.

**Comment by williamcroberts** [comment]
Iv'e been waiting for this issue to crop up, yes it should, you want to propose a patch?

**Comment by zt-initech** [comment]
@williamcroberts I propose the patch above.

**Comment by zt-initech** [comment]
I updated the patch. I added the missing section in the tpm2_sign man page and also renamed the argument from `sigalg` to `signscheme`.

**Comment by williamcroberts** [comment]
Thank you!
@zt-initech I left a bunch of comments on that commit. Please make the changes and submit a PR. Looks pretty good for the most part.
