### ISSUE TITLE
test_tpm2_listpersistent.sh result is fail when used tpm2-tools-3.1.3 under Fedora 29

### ISSUE THREAD

**Issue by JMing77** [tpm2-software/tpm2-tools#1342]
Hello everyone,

I  run script test_tpm2_listpersistent.sh under Fedora 29 and it will fail and show message:
Only 3 of 2 persistent objects were listed

Other items are pass only tpm2_listpersistent is fail.
There are my tpm2 test packages:
tpm2-abrmd-2.0.3
tpm2-tss-2.1.0
tpm2-tools-3.1.3

Does anyone know this issue how to solve?
Thank you.

**Comment by lestums** [comment]
I assume you ran "make check". Thus, can you attach the `test-suite.log` at the `tpm2-tools` root directory please ?

This will give some context on how it has been executed and might give clues on what have failed.

**Comment by martinezjavier** [comment]
> Only 3 of 2 persistent objects were listed

You mean 2 of 3? But if I read the test correctly it only creates 2 persistent objects.

**Comment by JMing77** [comment]
Hi lestums,
I don't have test-suite.log at the tpm2-tools root directory, please refer attached file tpm2-tools-3.1.3.zip, thanks.

Hi martinezjavier,
Message is "Only 3 of 2 persistent objects were listed", you can refer to test_all.log, thank you.

[test_all.log](https://github.com/tpm2-software/tpm2-tools/files/2940842/test_all.log)
[tpm2-tools-3.1.3.zip](https://github.com/tpm2-software/tpm2-tools/files/2940923/tpm2-tools-3.1.3.zip)

**Comment by williamcroberts** [comment]
This also will need to be cherry picked for 3.1.5: https://github.com/tpm2-software/tpm2-tools/milestone/11

**Comment by williamcroberts** [comment]
> This also will need to be cherry picked for 3.1.5: https://github.com/tpm2-software/tpm2-tools/milestone/11

That comment appears to be nonsensical.

**Comment by williamcroberts** [comment]
Is this still an issue?

**Comment by martinezjavier** [comment]
@williamcroberts I was never able to reproduce it.

**Comment by idesai** [comment]
Closing since the issue could not be reproduced.

**Comment by JMing77** [comment]
Thanks for everyone support.
