### ISSUE TITLE
Yocto build of 3.1.4 tools missing ESAPI commands

### ISSUE THREAD

**Issue by TabMong** [tpm2-software/tpm2-tools#1364]
Hello.... trying to integrate the latest tpm2.0 tools into my Yocto build and some of the ESAPI tools are not being bundled into the TGZ package.  I have not done an extensive compare but two of the tools I notice missing are tpm2_policypcr and tpm2_flushcontext.  I don't see and alternate package that has these tools just wondering what I am doing wrong.  Here is a listing of the tgz filtered for these two items.  The man pages seem to be there just not the source.  Thanks.

207001271@mcasvga2:~/Downloads$ tar tzpf tpm2-tools-3.1.4.tar.gz | grep policy
tpm2-tools-3.1.4/lib/tpm2_policy.c
tpm2-tools-3.1.4/lib/tpm2_policy.h
tpm2-tools-3.1.4/tools/tpm2_createpolicy.c
tpm2-tools-3.1.4/man/man1/tpm2_policyor.1
tpm2-tools-3.1.4/man/man1/tpm2_policypassword.1
tpm2-tools-3.1.4/man/man1/tpm2_policysecret.1
tpm2-tools-3.1.4/man/man1/tpm2_policyrestart.1
tpm2-tools-3.1.4/man/man1/tpm2_policyauthorize.1
tpm2-tools-3.1.4/man/man1/tpm2_policycommandcode.1
tpm2-tools-3.1.4/man/man1/tpm2_policypcr.1
tpm2-tools-3.1.4/man/man1/tpm2_createpolicy.1
tpm2-tools-3.1.4/man/tpm2_createpolicy.1.md
tpm2-tools-3.1.4/test/system/test_tpm2_createpolicy.sh
207001271@mcasvga2:~/Downloads$ tar tzpf tpm2-tools-3.1.4.tar.gz | grep flush
tpm2-tools-3.1.4/man/man1/tpm2_flushcontext.1

**Comment by joshuagl** [comment]
Those tools haven't been added in the 3.X branch, they are only available on master and will be included in the next major release.
