### ISSUE TITLE
./configure --enable-unit must be run as root

### ISSUE THREAD

**Issue by dilyanpalauzov** [tpm2-software/tpm2-tools#1365]
tpm2-abrmd is intalled by default under $prefix/sbin/.

“tpm2-tools/configure --enable-unit” calls 
```
AC_CHECK_PROG([tpm2_abrmd], [tpm2-abrmd], yes, no)
AS_IF([test "$tpm2_abrmd" != "yes"], [AC_MSG_ERROR([Required executable tpm2_abrmd not found, try setting PATH])])
```

tpm2_abrmd is searched by AC_CHECK_PROG in $PATH.  When ./configure is not run by root, /sbin is not in $PATH, so “./configure --enable-unit” must be run by root, in order to succeed.

It is very exceptional (I have not seen this anywhere else), that ./configure must be run as root (so that later the test framework can be started).

**Comment by joshuagl** [comment]
> When ./configure is not run by root, /sbin is not in $PATH

That's certainly not a universal truth, on both Fedora 29 and Ubuntu 18.10 I have _/sbin_ and _/usr/sbin_ in my users `PATH` by default. On openSUSE 15.0 neither are in the users default `PATH`.

Regardless, _/sbin_ is the correct location according to the FHS:
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s10.html

You might want to build with an invocation like:

> $ PATH=$PATH:/sbin ./configure --enable-unit

**Comment by dilyanpalauzov** [comment]
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s10.html says for /usr/sbin "This directory contains any non-essential binaries used exclusively by the system administrator".  So if the user is not system administrator, then that user shall not be able to call binaries intended exclusively for the system administrators.

As far as Fedora is concerned, the rationale at https://fedoraproject.org/wiki/Features/SbinSanity is that even when sbin is included in PATH, the sbin/ tools shall still be run by `sudo`.

That said we come again to the subject, that ./configure --enable-unit must either be run as root or as `sudo -u root`.  The difference between `as root` and `with sudo -u root` is here not essential.

**Comment by williamcroberts** [comment]
Then perhaps it's abrmd not in the proper spot? @flihp you have input on this?

**Comment by joshuagl** [comment]
Is this a real problem somewhere or just hypothetical? I've never had to run configure as root or with sudo, despite building the tools many times on several different distros.

**Comment by williamcroberts** [comment]
@joshuagl me either, i wonder if it's some pedantic distro thing. @dilyanpalauzov can you tell us more about your environment?

**Comment by dilyanpalauzov** [comment]
On my Linux From Scratch system, on which I have not installed `sudo`, sbin/ is not in $PATH.

In any case, it has to be clarified first if `tpm2_abrmd` is supposed to be run only by system administrators, like tcpdump, kadmind, fsck; or by all users  Afterwards can be decided on the installation path: bin or sbin.

**Comment by diabonas** [comment]
In my opinion, `sbin` is the correct directory since the user is not supposed to call `tpm2_abrmd` directly, it is started automatically by D-Bus/systemd. As [@joshuagl pointed out](https://github.com/tpm2-software/tpm2-tools/issues/1365#issuecomment-474372982), there doesn't seem to be a standard whether `sbin` should be included in `PATH`. It might be nice though to change the logic in `configure.ac` so that you can do something like
```
./configure --enable-unit tpm2_abrmd=/sbin/tpm2-abrmd
```
This currently does not work because the `tpm2_abrmd` is only set to `yes` or `no`. Instead we could put the absolute path of the binary in this variable and use it where necessary.

**Comment by dilyanpalauzov** [comment]
If tpm2_abrmd is going to be started only over DBus, then tweak ./configure to check, whether tpm2_abrmd can be started over DBus.

**Comment by joshuagl** [comment]
Setting `PATH` at configure invocation time doesn't feel entirely unreasonable to me

**Comment by joshuagl** [comment]
This really is an edge case, though. In standard usage, or even a standard build, the tools don't care about the location of tpm2-abrmd. However if you're trying to build and run the test suite we need to know where it is so that we can start tpm2-abrmd as a non-system user in order to set up an instance to test against that won't interfere with the global system state.

**Comment by dilyanpalauzov** [comment]
If PATH is set within ./configure, then it must be either set to /usr/local/sbin and /usr/sbin, or even better  tpm2-abrmd shoud install a .pc file and from it the $prefix must be extracted, to set PATH.

If the user is not supposed to call tpm2-abrmd, then it shall go under $?prefix)/libexec, https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html.

From my side, you can decide on anything here, including doing nothing.  I provided a hint that the current ./configure does not work as expected under circumstances.

If I want to call the tests, I can tweak my system appropriately, but it is possible, that others face the same problem.

**Comment by williamcroberts** [comment]
@dilyanpalauzov ill take patches for this if it does indeed correct a corner case. Considering the only bug report we have is from an LFS system and not from Debian or Redhat, it seems like a corner case. I'm not sure what magic to put in the configure scripts to make this work.

**Comment by williamcroberts** [comment]
@dilyanpalauzov did we ever come to a resolution in this?

**Comment by dilyanpalauzov** [comment]
I am not aware of any resolutions.  One possible resolution would be to derive the installation path of `tpm2-abrmd` from `tss2-tcti-tabrmd.pc` and during the tests add that path to a local `$PATH`.

**Comment by williamcroberts** [comment]
I'll take patches, but I don't think I'm going to fix this one. I'm not sure I can replicate the environment to make sure I actually close your issue.

**Comment by dilyanpalauzov** [comment]
Reproducing this is a matter of removing the `sbin/` directory, containing `tpm2_abrmd`,  from the PATH environment variable, before calling `./configure`.

I am not going to send patches.

A quick and dirty workaround is to write either in README.md or at https://github.com/tpm2-software/tpm2-tools/wiki that for running the tests, the location of `tpm2_abrmd` must be in the `$PATH` environment variable, both at configure and test time.

**Comment by dilyanpalauzov** [comment]
https://github.com/tpm2-software/tpm2-tools/blob/master/INSTALL.md says it already “Optional Dependencies: For the tests: tpm2-abrmd (must be on $PATH) and tpm_server”

**Comment by williamcroberts** [comment]
There are a lot of things need to be on PATH for just configure to work.... It seems everywhere else the executables are on PATH or for non-standard installs they get added to PATH.
