### ISSUE TITLE
Optional requirement in configure.ac

### ISSUE THREAD

**Issue by dilyanpalauzov** [tpm2-software/tpm2-tools#1368]
Configure.ac contains:
```
AC_MSG_WARN([System tests require the python module $1, some tests will fail!])
…
AC_MSG_WARN([Required executable bash not found, system tests require a bash shell!])
AC_MSG_WARN([Required executable python not found, some system tests will fail!])
AC_MSG_WARN([Required executable xxd not found, some system tests will fail!])
```
A related program is either optional or required.  Since ./configure continues when a desired program is missing, then the program is optional.

Reword the above warnings to “MNO not found, some system tests will fail”

**Comment by williamcroberts** [comment]
This should be fail hard when not found

**Comment by dilyanpalauzov** [comment]
The line in configure.ac: `enable_unit="$enable_unit (tpm2_abrmd: $tpm2_abrmd, tpm_server: $tpm_server, bash: $BASH_SHELL, python: $PYTHON, xxd: $XXD)"` has now no more added value.
