### ISSUE TITLE
No warning/error on default suite being selected if specified suite is ill formated

### ISSUE THREAD

**Issue by lestums** [tpm2-software/tpm2-tools#1371]
If one attempt to specify such algorithm permutation :
`ecc256<insert_something_here>:....` e.g `ecc256funnytexthere:`
the tool will silently convert the suite into :
`ecc256:null:null`

Same behavior can be obtained by using RSA or any algorithm specification that have data between identifier and the colon (or NULL) and where beginning of the spec. is correct (all permutations of ecc/rsa with a valid curve/key size)
On top of that, algorithms defaults changes between restricted and non restricted modes.
`ecc256:null:null` in non restricted
`ecc256:null:aes128cfb` in restricted

Multiple ways to address the issue :
- Modify manpage to specify default set selected if input is invalid (error-prone and quite abrupt from user's point of view)
- Print a warning & modify manpages to state that user will be warned on invalid algorithm suites (user still need to be careful)
- Throw an error (what i prefer)

What do you suggest ?

**Comment by williamcroberts** [comment]
Throw an error
