### ISSUE TITLE
Nonce changes during tpm2_createak causing failures on some TPMs

### ISSUE THREAD

**Issue by joshuagl** [tpm2-software/tpm2-tools#1381]
During `tpm2_createak` the nonce size changes, which causes a failure on certain TPM implementations.

> The spec states, in section Part 1 section 19.6.3.2 first note (looking at rev 1.38 ) that
> "A TPM implementation may allow larger nonce sizes but the caller should not expect a TPM to accept a nonce size larger than the initial nonceCaller size."

Where the TPM enforces that the nonce size doesn't change this results in an error during `tpm2_createak`.

This error was introduced during the ESAPI port

**Comment by joshuagl** [comment]
We can make the simulator enforce that nonce size doesn't change in order to replicate it with a patch like:

https://gist.github.com/joshuagl/b3b5d356a88faa0c46974b79c23b6984

**Comment by daveti** [comment]
root@sgx-59:~/git/tpm2-bm# tpm2_createak -C 0x81010001 -k 0x81010002 -p ak.pub -n ak.name
WARNING:esys:src/tss2-esys/api/Esys_Create.c:414:Esys_Create_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Create.c:156:Esys_Create() Esys Finish ErrorCode (0x0000008f)
ERROR: Esys_Create(0x8F) - tpm:handle(unk):invalid nonce size or nonce value mismatch
ERROR: Unable to run tpm2_createak

**Comment by daveti** [comment]
Could someone take a look at this? I simply would not create AK due to this nonce error. BTW, I'm using a physical TPM2 chip. Let me know if DEBUG/TRACE logging is needed. Thanks in advance!

**Comment by williamcroberts** [comment]
I'm not really sure where the nonce size is changing, it should just be a matter of finding out why its changing and fixing that. Im not sure if we should be setting the nonce parameter in PolicySecret

**Comment by daveti** [comment]
Yeah, I am also confused to see a nonce error during AK creation. Thanks for the quick response~

**Comment by williamcroberts** [comment]
I applied joshes patch and added a printf to see whats going on:

nonceCaller: 32 - nonceTPM: 20

Looks like it's getting changed to a SHA1 size... now need to run down where.

**Comment by williamcroberts** [comment]
So after much digging, nonceCaller and nonceTPM are comming in at size 20, but this code is using the auth hash size to compute the new nonce for nonceCaller. I'm not sure if this is proper behavior, why wouldn't it use the established nonce size?

```C
iesys_gen_caller_nonces(ESYS_CONTEXT * esys_context)
{
    TSS2_RC r;
    size_t authHash_size = 0;

    for (int i = 0; i < 3; i++) {
        RSRC_NODE_T *session = esys_context->session_tab[i];
        if (session == NULL)
            continue;
        r = iesys_crypto_hash_get_digest_size(session->rsrc.misc.rsrc_session.
                                              authHash, &authHash_size);
        return_if_error(r, "Error: initialize auth session.");

        r = iesys_crypto_random2b(&session->rsrc.misc.rsrc_session.nonceCaller,
                                authHash_size);
        return_if_error(r, "Error: computing caller nonce (%x).");
    }
    return TSS2_RC_SUCCESS;
}
```

**Comment by williamcroberts** [comment]
This seems to be working. Let me run the TSS tests and see if anything breaks.
```diff
diff --git a/src/tss2-esys/esys_iutil.c b/src/tss2-esys/esys_iutil.c
index 78842dc2b669..6535d51f27c2 100644
--- a/src/tss2-esys/esys_iutil.c
+++ b/src/tss2-esys/esys_iutil.c
@@ -536,18 +536,18 @@ TSS2_RC
 iesys_gen_caller_nonces(ESYS_CONTEXT * esys_context)
 {
     TSS2_RC r;
-    size_t authHash_size = 0;
+//    size_t authHash_size = 0;
 
     for (int i = 0; i < 3; i++) {
         RSRC_NODE_T *session = esys_context->session_tab[i];
         if (session == NULL)
             continue;
-        r = iesys_crypto_hash_get_digest_size(session->rsrc.misc.rsrc_session.
-                                              authHash, &authHash_size);
-        return_if_error(r, "Error: initialize auth session.");
+//        r = iesys_crypto_hash_get_digest_size(session->rsrc.misc.rsrc_session.
+//                                              authHash, &authHash_size);
+//        return_if_error(r, "Error: initialize auth session.");
 
         r = iesys_crypto_random2b(&session->rsrc.misc.rsrc_session.nonceCaller,
-                                authHash_size);
+                                  session->rsrc.misc.rsrc_session.nonceCaller.size);
         return_if_error(r, "Error: computing caller nonce (%x).");
     }
     return TSS2_RC_SUCCESS;
```

**Comment by AndreasFuchsSIT** [comment]
Upstream fix looks good...

While looking into the tpm2-tss bug, I notices that the tpm2-tools statically choose 20 as callerNonce.size:
https://github.com/tpm2-software/tpm2-tools/blob/4c40cc4467c6505e3b1c3475a45d35ed3fd53934/lib/tpm2_session.c#L74
Instead, you can pass NULL into StartAuthSession and ESAPI will calculate the callerNonce.size from the sessions algorithm automagically here:
https://github.com/tpm2-software/tpm2-tools/blob/4c40cc4467c6505e3b1c3475a45d35ed3fd53934/lib/tpm2_session.c#L128
And you can remove everything related to nonceCaller nonce_caller, etc...

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT the session code in the tools needs a big delete now with ESAPI.
