### ISSUE TITLE
test/integration/tests/activecredential.sh gets stuck

### ISSUE THREAD

**Issue by dilyanpalauzov** [tpm2-software/tpm2-tools#1417]
When I call `make check` on the latest tpm2-tools, at some moment activecredential.sh does not make a progress. I see it has started tmp2_evictcontrol, tpm2-abrmd, and tpm-server 1332.  Here are the backtraces of those processes:

[gdb-evictcontrol.txt](https://github.com/tpm2-software/tpm2-tools/files/3085815/gdb-evictcontrol.txt)
[gdb-tpm_abrmd.txt](https://github.com/tpm2-software/tpm2-tools/files/3085816/gdb-tpm_abrmd.txt)
[gdb-tpm-server.txt](https://github.com/tpm2-software/tpm2-tools/files/3085817/gdb-tpm-server.txt)

What is here suboptimal?

**Comment by williamcroberts** [comment]
AFAICT everything seems to be sitting in poll, not sure why they are not communicating, is this repeatable?

**Comment by dilyanpalauzov** [comment]
Yes, it is 100% repeatable.

**Comment by williamcroberts** [comment]
Whats the git sha for:
* tss
* abrmd
* tools

Our CI is on an older tpm-server:
ibmtpm1119

I use 974 locally.

Try an older version of the simulator perhaps, is it repeatable then?

**Comment by dilyanpalauzov** [comment]
`ss -paei` shows for the three processes:
```
Netid  State      Recv-Q Send-Q   Local Address:Port       Peer Address:Port   
tcp    LISTEN     0      3                    *:8499                  *:*        users:(("tpm_server",pid=2712,fd=4)) uid:1000 ino:166888 sk:00000002 <->
tcp    LISTEN     0      3                    *:8500                  *:*        users:(("tpm_server",pid=2712,fd=5)) uid:1000 ino:167256 sk:00000003 <->
tcp    LISTEN     0      3                   :::8499                 :::*        users:(("tpm_server",pid=2712,fd=6)) uid:1000 ino:166889 sk:0000000d <->
tcp    LISTEN     0      3                   :::8500                 :::*        users:(("tpm_server",pid=2712,fd=7)) uid:1000 ino:167257 sk:0000000e <->
tcp    ESTAB      0      0                  ::1:8500                ::1:33874    users:(("tpm_server",pid=2712,fd=9)) uid:1000 ino:166895 sk:00000010 <->
tcp    ESTAB      0      0                  ::1:8499                ::1:47664    users:(("tpm_server",pid=2712,fd=8)) uid:1000 ino:166894 sk:00000011 <->
u_str  ESTAB      0      0                    * 165582                * 0       users:(("tpm2-abrmd",pid=2715,fd=6))
u_str  ESTAB      0      0                    * 168181                * 0       users:(("tpm2-abrmd",pid=2715,fd=11))
tcp    ESTAB      0      0                  ::1:33874               ::1:8500     users:(("tpm2-abrmd",pid=2715,fd=7)) uid:1000 ino:168173 sk:0000000f <->
tcp    ESTAB      0      0                  ::1:47664               ::1:8499     users:(("tpm2-abrmd",pid=2715,fd=5)) uid:1000 ino:168169 sk:00000012 <->
u_str  ESTAB      0      0                    * 167261                * 0       users:(("tpm2_evictcontr",pid=2733,fd=5))
u_str  ESTAB      0      0                    * 168180                * 0       users:(("tpm2_evictcontr",pid=2733,fd=7))
```
Thus tpm2-abrmd and tpm_server are connected.,but tpm2_evictcontrol is lonely.  Thus I think the version of ibmtpm is not relevant here.

* How is tpm2_evictcontrol supposed to determine where to connect?

I do not know `git sha`.

**Comment by williamcroberts** [comment]
run --version on any tool, that will at least narrow the tools down. We just pulled in a massive re-work of the CI scripts on changes:

https://github.com/tpm2-software/tpm2-tools/commit/f6c548b7cd63967a1ca1c756067d6fe7cd93736f

**Comment by williamcroberts** [comment]
oh it figures out how to connect by the TCTI env variable or command line tcti options

**Comment by dilyanpalauzov** [comment]
`git -C tpm2-tools/ describe` ⇒ 3.0.2-1005-gc782e7cc.

build/test/integration/tests/activecredential.log:
```
--- To recreate this test run the following from: /git/tpm2-software/tpm2-tools/build ---
#!/usr/bin/env bash
export TPM2_ABRMD="tpm2-abrmd" TPM2_SIM="tpm_server" PATH="/git/tpm2-software/tpm2-tools/build/tools:/git/tpm2-software/tpm2-tools/build/tools/misc:/git/tpm2-software/tpm2-tools/build/../test/integration:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/d/Android/Sdk/platform-tools/" TPM2_SIM_NV_CHIP="" TPM2_TOOLS_TEST_FIXTURES="/git/tpm2-software/tpm2-tools/build/../test/integration/fixtures"
../test/integration/tests/activecredential.sh
--- EOF ---

creating simulator working dir: /tmp/tpm2_test_BMQ0q9
/tmp/tpm2_test_BMQ0q9 /git/tpm2-software/tpm2-tools/build
Switched to CWD: /tmp/tpm2_test_BMQ0q9
Starting the simulator
Attempting to start simulator on port: 28763
tpm2_tabrmd_opts: --session --dbus-name=com.intel.tss2.Tabrmd28763 --tcti=mssim:port=28763
tpm2_tcti_opts: abrmd:bus_type=session,bus_name=com.intel.tss2.Tabrmd28763
Started simulator in tmp dir: /tmp/tpm2_test_BMQ0q9
Started the simulator
Starting tpm2-abrmd
tpm2-abrmd command: tpm2-abrmd --session --dbus-name=com.intel.tss2.Tabrmd28763 --tcti=mssim:port=28763
Started tpm2-abrmd
Setting TCTI to use abrmd
export TPM2TOOLS_TCTI="abrmd:bus_type=session,bus_name=com.intel.tss2.Tabrmd28763"
Running tpm2_clear
```
So it is supposed to connect to com.intel.tss2.Tabrmd28763.

`dbus-send --session --dest=org.freedesktop.DBus --type=method_call   --print-repl
y  /org/freedesktop/DBus   org.freedesktop.DBus.ListNames` in another window, does not print intel.  Does this mean, that the DBus bus does not exist?

**Comment by williamcroberts** [comment]
dbus is a nightmare. I look at the ss output, and from what I can tell its not hooked up with tpm2-abrmd, but tpm2-abrmd is hooked up with tpmserver but the tool is not hooked up with abrmd.

So theirs something wrong in the test code or their is something wrong in abrmd. abrmd hasn't moved much recently, so my guess is the tools.

Try setting up something with git bisect and narrow it down by running the actvatecredential.sh test.

**Comment by dilyanpalauzov** [comment]
This has never runned, so I guess doing bisect will not help.

**Comment by dilyanpalauzov** [comment]
Updating tpm2-tss helped.

**Comment by dilyanpalauzov** [comment]
Some integration tests from tpm2-tools gets only stuck on my system after `tpm2-tss/configure --enable-tcti-partial-reads` is utilized.  Without partial reads, all the tpm2-tools tests complete.

**Comment by williamcroberts** [comment]
This issue needs to go to TSS, not tools.

**Comment by dilyanpalauzov** [comment]
The problem could also be in the resource manager `tpm2-abrmd` not being able to deal with tcti-partial-reads.

**Comment by flihp** [comment]
Given the repro and the logs I'm seeing from `tpm2-abrmd` I'm 80% certain this is my bug. I'll update https://github.com/tpm2-software/tpm2-abrmd/issues/622 with more data when I have it.
