### ISSUE TITLE
Enhancements to tpm2_import

### ISSUE THREAD

**Issue by GlovePuppet** [tpm2-software/tpm2-tools#1423]
Now I have a candidate for tpm2_duplicate I would like to expand tpm2_import to work with TPM objects as well as openssl objects.

How do we want to indicate to the tool that we are importing a TPM object? I could imagine adding a parameter (-S?) that is the encrypted seed filename and if it's present then the tool assumes we are importing a TPM object otherwise it assumes openssl and the behavior is the same as before.

Alternately, how about a new tool (tpm2_import_tpm?) ?

OR we could extract the openssl -> tpm conversion code and move it to a standalone utility then tpm2_import can do what God & Nature intended - import TPM objects

**Comment by williamcroberts** [comment]
Looks like this was fixed in f254d5efd40f4, is that correct?

**Comment by GlovePuppet** [comment]
Yep, all done

**Comment by williamcroberts** [comment]
@GlovePuppet Thanks!
