### ISSUE TITLE
Fix the pandoc version for building the documentation

### ISSUE THREAD

**Issue by dilyanpalauzov** [tpm2-software/tpm2-tools#1433]
Below is the manual page for tpm2_re_decode, generated by
`pandoc 1.19.2.4 Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.5` and `pandoc 2.7.2 Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7`.

[tpm2_rc_decode.1_pandoc_1.19.2.4.txt](https://github.com/tpm2-software/tpm2-tools/files/3107253/tpm2_rc_decode.1_pandoc_1.19.2.4.txt)
[tpm2_rc_decode.1_pandoc_2.0.txt](https://github.com/tpm2-software/tpm2-tools/files/3107254/tpm2_rc_decode.1_pandoc_2.0.txt)

A diff between the files contains:
```diff
@@ -24,3 +24,3 @@
 .IP \[bu] 2
-\f[B]\-h\f[], \f[B]\-\-help=[man|no\-man]\f[]: Display the tools
+\f[B]\-h\f[], \f[B]\[en]help=[man|no\-man]\f[]: Display the tools
 manpage.
```

On my system `man tpm2_rc_decode` shows consistently a single dash before all the long-options, when I use pandoc 2.0 to generate the documentation, but not when pandoc 1.19.2.4 is used.

**Comment by dilyanpalauzov** [comment]
The 2 version used for the file above was `pandoc 2.0 Compiled with pandoc-types 1.17.2, texmath 0.9.4.4, skylighting 0.4.2`, as contained in the first line of tpm2_rc_decode.1_pandoc_2.0.txt, it was not 2.7.2

**Comment by williamcroberts** [comment]
I just tried to reproduce:

Pandoc Versions (1.17.0.5 to 2.7.2):
Old:
```
pandoc2 2.7.2
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
Default user data directory: /home/wcrobert/.local/share/pandoc or /home/wcrobert/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

New:
```
pandoc2 2.7.2
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
Default user data directory: /home/wcrobert/.local/share/pandoc or /home/wcrobert/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

I could not reproduce, the files are identical:
2b853179500090b9acb267086295976c  tpm2_rc_decode.1.v1 (old)
2b853179500090b9acb267086295976c  tpm2_rc_decode.1.v2 (new)

**Comment by dilyanpalauzov** [comment]
I do not see a difference between Old and New, both are 2.7.2. The files must at least differ in the first line: `.\" Automatically generated by Pandoc 2.7.2`.

**Comment by williamcroberts** [comment]
> I do not see a difference between Old and New, both are 2.7.2. The files must at least differ in the first line: `.\" Automatically generated by Pandoc 2.7.2`.

Yep my alias from v1 to v2 didn't propagate through, lets try this again

**Comment by williamcroberts** [comment]
Ok have it reproduced

**Comment by williamcroberts** [comment]
I can reproduce it with this file
[test.md.txt](https://github.com/tpm2-software/tpm2-tools/files/3128875/test.md.txt)

```markdown
# This is my test markdown

  * **-h**, **--help=[man|no-man]**:
    Display the tools manpage. By default, it attempts to invoke the manpager for the tool,
    however, on failure will output a short tool summary. This is the same behavior if the
    "man" option argument is specified, however if explicit "man" is requested, the tool will
    provide errors from man on stderr. If the "no-man" option if specified, or the manpager fails,
    the short options will be output to stdout.
```

**Comment by williamcroberts** [comment]
Pandoc seems to treating these as "em dashes" now, looks like their is an option to control these.
https://github.com/jgm/pandoc/issues/3063

**Comment by williamcroberts** [comment]
Looks like the simplest fix is to escape the `--` with `\-\-`

**Comment by dilyanpalauzov** [comment]
In this particular example `**-h**, **--help=[man|no-man]**`, means that --help needs a mandatory paratemer.  Without equal sign it would mean that the parameter is optional.  This is at least how I see the things.
