### ISSUE TITLE
Improve option detection of analyze.py

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-tools#1449]
- The last element of an entry in a long options array [can be an integer](https://www.gnu.org/software/libc/manual/html_node/Getopt-Long-Options.html#index-struct-option), see e.g. [`tpm2_createpolicy`](https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_createpolicy.c#L192). Such long options are currently not parsed because the [regex in `analyze.py`](https://github.com/tpm2-software/tpm2-tools/blob/f254d5efd40f42f06b2c0e9f3947cb4277f71af2/scripts/utils/analyze.py#L272) expects a char quoted with `'`.
- The regex also doesn't recognise `optional_argument` for the second element. Currently there are no such options, but there might be in the future.

**Comment by williamcroberts** [comment]
Tool removed at 4.0 RC0 cut, no longer valid ticket.
