### ISSUE TITLE
Backport tpm2_flushcontext to 3.x.x

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-tools#1452]
The tpm2-tss-engine needs the tpm2_flushcontext tool for their testsuite and thus has to resort to use the latest master of tpm2_tools.
As the current work on the 4.x release of the tpm2-tools is in progress, there might be api breaks, which then cause tpm2-tss-engine to fail.

The best solution would be to backport tpm2_flushcontext to the current 3.x branch and do a quick update release of 3.x.x so tpm2-tss-engine could rely on the stable api.

**Comment by williamcroberts** [comment]
Fixed in https://github.com/tpm2-software/tpm2-tools/commit/8c13b2f10fa92457ee83a2da784f9a3618c4c49f
