### ISSUE TITLE
tpm2_activatecredential activatehandle auth

### ISSUE THREAD

**Issue by dgptha** [tpm2-software/tpm2-tools#1453]
The auth of the activateHandle (following "Part 2" naming) in the current implementation doesn't work.
This is fairly easy to test with `test/integration/tests/activatecredential.sh`: set an auth for the created ak (`-P password` option on the `tpm2_createak` command). With that `tpm2_activatecredential` with and without the `-P password` option doesn't work. `tpm2_activatecredential` systematically shows the following error:
```
WARNING:esys:src/tss2-esys/api/Esys_ActivateCredential.c:344:Esys_ActivateCredential_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_ActivateCredential.c:127:Esys_ActivateCredential() Esys Finish ErrorCode (0x0000098e)
ERROR: Esys_ActivateCredential(0x98E) - tpm:session(1):the authorization HMAC check failed and DA counter incremented
ERROR: Unable to run tpm2_activatecredential                                               
```

From my testing I found that on `tpm2_activatecredential.c` when creating the shandle for the activateHandle the keyHandle was actually being used. Changing the following code:
```
ESYS_TR key_shandle = tpm2_auth_util_get_shandle(ectx,
                        ctx.key_ctx_obj.tr_handle, &ctx.auth,
                        ctx.auth_session);
```
with:
```
ESYS_TR key_shandle = tpm2_auth_util_get_shandle(ectx,
                        ctx.ctx_obj.tr_handle, &ctx.auth,
                        ctx.auth_session);
```
solves the problem. With this change the `tpm2_activatecredential` command with the `-P passwd` option now works.

As a side note some variable renaming in `tpm2_activatecredential.c` code would be helpful to better follow the TCG docs. E.g., the `key_shandle` in the above code could be named `activate_shandle` to better match the TCG docs and don't confuse it with the shandle for the keyHandle.

**Comment by lukehinds** [comment]
@dgptha , do you plan to submit a PR with your suggested fix in `key_shandle`?

**Comment by idesai** [comment]
Fix proposed in https://github.com/tpm2-software/tpm2-tools/pull/1499. Thanks @dgptha.
