### ISSUE TITLE
default output file names

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1457]
In tools, some of them have default output filenames when Josh ported to ESAPI. We need to consider these options in depth and figure out if we want to make the output file always an explicit required option. Find all of them and fix it or leave and ensure manpages are up-to-date.

```C
    if (!ctx.ak.out.ctx_file || ctx.ak.out.ctx_file[0] == '\0') {
        ctx.ak.out.ctx_file = "ak.ctx";
    }
```

**Comment by williamcroberts** [comment]
This is so annoying, remove it and just clobber:
```
tpm2_startauthsession --policy-session -S session.ctx
WARN: Path: session.ctx already exists. Please rename or delete the file!
session-context: session1.ctx
```

**Comment by idesai** [comment]
@williamcroberts, I agree with the simply overwrite model.
Also, I think output file names should be explicitly specified unless piping to stdout when possible. So I'd rather drop default filenames.
