### ISSUE TITLE
fix session tests/find bug

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1463]
A commit I will reference when I upload the PR will require some XFAIL tests corrected and the XFAIL patch reverted.

**Comment by williamcroberts** [comment]
See: https://lists.01.org/pipermail/tpm2/2019-May/001161.html

**Comment by williamcroberts** [comment]
I think the problem is that when a password is coming in, were trying to start an hmac session when ectx is null or something like that.

**Comment by idesai** [comment]
The issue has been addressed in the Esys module esys_iutil.c. Here is the PR https://github.com/tpm2-software/tpm2-tss/pull/1407
Will unblock (remove XFAIL tags) on test policy password and policy secret. If everything checks out, will close this issue.
Thanks

**Comment by idesai** [comment]
Summary:
1. This is certainly not a resource manager issue. 
    I ran the test command stream directly on the tpm and did not find a behavior that is differentfrom "with" the resource manager. Here are my findings

**Comment by idesai** [comment]
Awaiting tss PR merge https://github.com/tpm2-software/tpm2-tss/pull/1407
