### ISSUE TITLE
Tests and bash

### ISSUE THREAD

**Issue by dilyanpalauzov** [tpm2-software/tpm2-tools#1467]
./configure calls `AC_CHECK_PROG([BASH_SHELL],[bash],[yes])` and verifies, that bash is on $PATH.  But the tests/integration/tests/*.sh files all start with `#!/bin/bash`.

If `bash` is in /usr/bin, but not in /bin, ./configure will not warn, that the tests will fail.

**Comment by williamcroberts** [comment]
So we probably want configure to indicate to the test scripts where bash is, we would have to like sed the scripts or something to insert it. Whats the best solution?

**Comment by dilyanpalauzov** [comment]
You can experiment with the fifth parameter of AC_CHECK_PROG, to force ./configure to check for bash only in /bin/bash (but a simple test during ./configure whether this file exists, would have the same effect), or use as shebang "#!path-to-env bash" in all the tests.

If configure tells the tests where bash is, then it gets messy.  You can have for the test x.sh.in files and configure generates from them x.sh files with the correct shebang line.4

Or you could update somehow in Makefile.am the SH_LOG_COMPILER, to handle all passed files as bash scripts.

**Comment by williamcroberts** [comment]
> -----Original Message-----
> From: Дилян Палаузов [mailto:notifications@github.com]
> Sent: Friday, May 10, 2019 2:22 PM
> To: tpm2-software/tpm2-tools <tpm2-tools@noreply.github.com>
> Cc: Roberts, William C <william.c.roberts@intel.com>; Comment
> <comment@noreply.github.com>
> Subject: Re: [tpm2-software/tpm2-tools] Tests and bash (#1467)
> 
> You can experiment with the fifth parameter of AC_CHECK_PROG, to force
> ./configure to check for bash only in /bin/bash (but a simple test during
> ./configure whether this file exists, would have the same effect), or use as
> shebang "#!path-to-env bash" in all the tests.

That's what I had before was /usr/bin/env bash, do you mean the same? Redhat changed
It IIRC.

**Comment by dilyanpalauzov** [comment]
> That's what I had before was /usr/bin/env bash, do you mean the same? Redhat changed It IIRC.

I mean this.  I do not know what Redhat has changed, nor I know where it is ensured, that env is installed.

**Comment by dilyanpalauzov** [comment]
For the record, `git grep /env` shows:
```
.ci/coveralls-upload.sh:#!/usr/bin/env bash
.ci/coverity.run:#!/usr/bin/env bash
.ci/docker-prelude.sh:#!/usr/bin/env bash
.ci/docker.run:#!/usr/bin/env bash
.ci/download-deps.sh:#!/usr/bin/env bash
.ci/travis.run:#!/usr/bin/env bash
scripts/utils/analyze.py:#!/usr/bin/env python
test/integration/helpers.sh:    echo "#!/usr/bin/env bash"
```
So the handling currently is inconsistent: tests run with /bin/bash, but for repeating the tests helpers.sh recommends using `#!/usr/bin/env bash`.

**Comment by dilyanpalauzov** [comment]
I did this change:
```diff
diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -256,7 +256,7 @@ if UNIT_ABRMD
 AM_TESTS_ENVIRONMENT += TPM2_ABRMD=tpm2-abrmd; export TPM2_ABRMD;
 endif
 
-SH_LOG_COMPILER = dbus-run-session
+SH_LOG_COMPILER = dbus-run-session /bin/bash
 AM_SH_LOG_FLAGS = --
 endif
 
diff --git a/test/integration/tests/activecredential.sh b/test/integration/tests/activecredential.sh
old mode 100755
new mode 100644
--- a/test/integration/tests/activecredential.sh
+++ b/test/integration/tests/activecredential.sh
@@ -1,4 +1,3 @@
-#!/bin/bash
 # SPDX-License-Identifier: BSD-3-Clause
 #;**********************************************************************;
 #
@@ -9,6 +8,8 @@
 
 source helpers.sh
 
+echo MMMMMMMMMMMMMM
+
 cleanup() {
     rm -f secret.data ek.pub ak.pub ak.name mkcred.out actcred.out ak.out
 
```

Notice, that the execution bits of test/integration/tests/activecredential.sh are removed.  Then `make check` printed MMMM after executing the test.  So one way to go is put from ./configure the path to bash in `Makefile.in:SH_LOG_COMPILER = dbus-run-session @PATH_TO_BASH` and remove the she-bang lines from the test files.

Pay attention, that helpers.sh puts in the header of each testcase.log file instruction how to repeat the test.  `make check` executes the tests under `dbus-run-session` and the instructions from helpers.sh say nothing about dbus-run-session.

The instructions will also need to be adjusted to include the path to bash, if the tests will not be anymore executables.

**Comment by dilyanpalauzov** [comment]
If I remember correctly, helpers.sh puts in the header of each testcase.log file instruction how to repeat the test. `make check` executes the tests under dbus-run-session and the instructions from helpers.sh say nothing about dbus-run-session.  This is not addressed by the patch.
