### ISSUE TITLE
Testing without abrmd

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tools#1472]
IMHO, the tests should also be runable against a TPM without the need of a resource manager.
The test script also already foresee this option.

At https://github.com/AndreasFuchsSIT/tpm2-tools/tree/notab_testing I started doing so; with only minor changes.
However, a lot of tests fail in these cases for obvious reasons.

My question is: How should I fix this?
a) Make the tools not leave any clutter inside the TPM; with an abrmd the TPM is left empty anyways, so this seems to be the working assumption to begin with
b) Add a bunch of tpm2_flushcontext statements to the tests ?

Downside of a) is of course that you don't have transient object operations anymore and it's a lot more work.

@williamcroberts Please advice ;-)

**Comment by AndreasFuchsSIT** [comment]
Or maybe c) add a general tool option to clean all transient and loaded (not active) sessions on exit ?

**Comment by williamcroberts** [comment]
> IMHO, the tests should also be runable against a TPM without the need of a resource manager.

No I don't see this as a thing. The RM is optional, but likely useful part of the stack. Considering that direct access to a physical tpm is restricted by file permissions, it's also not a likely thing users would be doing. The tests are built for the common denominator of an RM.

**Comment by williamcroberts** [comment]
Also I don't want to implement some half-baked RM logic into the tools, their would be no reason to implement that logic, if you want RM logic, use an RM.
