### ISSUE TITLE
Travis: XFAIL and passing

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tools#1477]
Two quick questions:
- The tests currently have 2 XFAILs on abrmd tests; I don't know what they are ?
- Travis still succeeds, despite these failure ?

see e.g. https://travis-ci.org/tpm2-software/tpm2-tools/jobs/530310974
```
XFAIL: test/integration/tests/tcti/abrmd/policypassword.sh
XFAIL: test/integration/tests/tcti/abrmd/policysecret.sh
```

**Comment by AndreasFuchsSIT** [comment]
Accordings to #1474 this may be a bug with tpm2-tss 2.2.2 fixed master

**Comment by williamcroberts** [comment]
Duplicate #1463

**Comment by williamcroberts** [comment]
> Accordings to #1474 this may be a bug with tpm2-tss 2.2.2 fixed master

#1474 is a compile time error, how is that related?

**Comment by AndreasFuchsSIT** [comment]
Sorry, I meant the comment by diabonas https://github.com/tpm2-software/tpm2-tools/pull/1474#issuecomment-490944165

**Comment by williamcroberts** [comment]
Closing this as it's a dup of #1463. Lets get the fix discussion on that.

**Comment by diabonas** [comment]
So the failure of `test/integration/tests/tcti/abrmd/extended-sessions.sh` that I get with tpm2-tss 2.2.2 seems to have been fixed on master by https://github.com/tpm2-software/tpm2-tss/commit/07eb8a2ea3d19e815c2e402ea2d2f1fcef7cf613. This commit should probably be cherry-picked for tpm2-tss 2.2.x.

**Comment by diabonas** [comment]
I looked a bit further into this: the test fails with
```
ERROR:esys:src/tss2-esys/esys_iutil.c:605:iesys_encrypt_param() Encryption not possible ErrorCode (0x0008000e) 
ERROR:esys:src/tss2-esys/esys_iutil.c:1190:iesys_gen_auths() Error parameter encryption ErrorCode (0x0008000e) 
ERROR:esys:src/tss2-esys/api/Esys_Unseal.c:187:Esys_Unseal_Async() Error in computation of auth values ErrorCode (0x0008000e) 
ERROR:esys:src/tss2-esys/api/Esys_Unseal.c:78:Esys_Unseal() Error in async function ErrorCode (0x0008000e) 
ERROR: Esys_Unseal(0x8000E) - sys:If function called that uses decrypt parameter, but command doesn't support decrypt parameter.
ERROR: Unseal failed!
ERROR: Unable to run tpm2_unseal
unsealed=`tpm2_unseal -p"session:$file_session_file" -c $file_unseal_key_ctx` on line 92 failed: 1
```
This is because since https://github.com/tpm2-software/tpm2-tss/commit/18600770725a892faa8d7044867466337708fffd (and fixed by the aforementioned https://github.com/tpm2-software/tpm2-tss/commit/07eb8a2ea3d19e815c2e402ea2d2f1fcef7cf613), tpm2-tss sets sensible session attributes itself instead of relying on the application to do that and `tpm2_unseal` is depending on the new behaviour.

I guess this makes this less of a tpm2-tss bug and more of an enhancement not suited for a patch release. @AndreasFuchsSIT, what do you think?

**Comment by AndreasFuchsSIT** [comment]
This was an enhancement/feature we introduced for the upcoming 2.3.0-dev.
If the tpm2-tool rely on this feature, they should PKG_CHECK against tpm2-tss >= 2.3.0
I opened #1481 for this.
