### ISSUE TITLE
Switching BSD-2 to BSD-3

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1478]
The Files:
```
test/unit/test_string_bytes.c
test/unit/test_tpm2_policy.c
test/unit/test_tpm2_header.c
test/unit/test_tpm2_attr_util.c
test/unit/test_tpm2_errata.c
test/unit/test_tpm2_alg_util.c
test/unit/test_pcr.c
test/unit/test_tpm2_error.c
test/unit/test_files.c
test/unit/test_tpm2_auth_util.c
test/unit/test_tpm2_hierarchy.c
test/unit/test_tpm2_session.c
lib/tpm2_tcti_ldr.h
lib/tpm2_session.c
lib/tpm2_openssl.c
lib/tpm2_error.h
lib/tpm2_error.c
lib/tpm2_convert.h
lib/tpm2_kdfa.h
lib/tpm2_identity_util.c
lib/tpm2_tcti_ldr.c
lib/tpm2_session.h
lib/tpm2_openssl.h
lib/tpm2_identity_util.h
lib/tpm2_kdfa.c
tools/misc/tpm2_rc_decode.c
```
Are all BSD-2. We would like to get sign off from the following authors to update to BSD-3:
- [x] Alexander Steffen - Alexander.Steffen@infineon.com
- [x] Alon Bar-Lev - alon.barlev@gmail.com
- [x] Andreas Fuchs - andreas.fuchs@sit.fraunhofer.de
- [x] Carlos Santos - casantos@datacom.ind.br
- [ ] gilb3rt - github@gilb3rt.com
- [x] GlovePuppet - touched.by.his.noodley.appendage@gmail.com
- [x] Javier Martinez Canillas - javierm@redhat.com
- [x] jetwhiz - charles.munson@ll.mit.edu
- [x] Jonas Witschel - diabonas@gmx.de
- [x] Peter Huewe - peter.huewe@infineon.com
- [x] Liu Qun (liuqun) - qunliu@zyhx-group.com
- [x] Safayet N Ahmed - Safayet.Ahmed@ge.com
- [x] sebastien le stum - lestums@gmail.com
- [x] Дилян Палаузов - git-dpa@aegee.org

**Comment by williamcroberts** [comment]
The only thing @gilb3rt touched was commit:
https://github.com/tpm2-software/tpm2-tools/pull/1144/commits/d5239bdcf1b781069ed2e93aa799d491ca6f250d

Which only Modified the Makefile.am the other tools we're not modified and just moved. The Makefile.am is BSD-3 and thus nothing needs to be done.

**Comment by gilb3rt** [comment]
I wasn't on the original list email. It looks like it doesn't matter, but I approve of the license change.

**Comment by williamcroberts** [comment]
Archived Outlook .msg format below. All acks received.

[acks.tar.gz](https://github.com/tpm2-software/tpm2-tools/files/3167489/acks.tar.gz)

[acks.tar.gz.sig.txt](https://github.com/tpm2-software/tpm2-tools/files/3167492/acks.tar.gz.sig.txt)

**Comment by williamcroberts** [comment]
Re-Archived emails on outlook .msg format:
[acks.tar.gz](https://github.com/tpm2-software/tpm2-tools/files/3167635/acks.tar.gz)
[acks.tar.gz.sig.txt](https://github.com/tpm2-software/tpm2-tools/files/3167636/acks.tar.gz.sig.txt)
