### ISSUE TITLE
Question about policy

### ISSUE THREAD

**Issue by roberto497** [tpm2-software/tpm2-tools#1480]
How can I create a persistent key with a policy, with PCR values like (Bios, Bootloader, Kernel), and that this key can not be accessed if any change occurs

**Comment by williamcroberts** [comment]
Look at the test:
https://github.com/tpm2-software/tpm2-tools/blob/master/test/integration/tests/unseal.sh#L85

The only thing you would need to add is tpm2_evictcontrol -c key.ctx to make it persistent.

Questions should go to the mailing list.
