### ISSUE TITLE
Requiring tpm2-tss >=2.3.0

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tools#1481]
https://github.com/tpm2-software/tpm2-tools/issues/1477#issuecomment-491050505 suggests, that the tpm2_unseal tool relies on the tpm2-tss to clean non-applicable session attributes for decrypt-/encrypt-sessions.
This was introduced to tpm2-tss as enhancement for the 2.3.0-dev series.
If tpm2-tools relies on this feature, it should PKG_CHECK for tpm2-tss >= 2.3.0

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT when is 2.3 coming, i see 2.2.3_rc0 tagged.
