### ISSUE TITLE
compound tools

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1492]
Look at compound tools and consider replacing with scripts.

**Comment by idesai** [comment]
@williamcroberts, Compound tools like tpm2_getmanufec?

**Comment by williamcroberts** [comment]
- [ ] tpm2_listpersistent
- [ ] tpm2_createek
- [ ] tpm2_createak
- [ ] tpm2_activatecredential
- [ ] tpm2_getmanufec

@idesai any others?
