### ISSUE TITLE
tpm2 wildcard policies guide help

### ISSUE THREAD

**Issue by Kaidou91** [tpm2-software/tpm2-tools#1517]
Hello.

Can anybody explain me how to use wildcard policies to create a NVindex and how to use a wildcard policy to access that NVindex? 
Thanks.

**Comment by idesai** [comment]
@Kaidou91 for how to questions, instead of the issue tracker, please use the mailing list (https://lists.01.org/mailman/listinfo/tpm2). Thanks.
