### ISSUE TITLE
tpm2_import fails to run.

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-tools#1530]
In https://github.com/tpm2-software/tpm2-pkcs11/blob/master/tools/tpm2_pkcs11/tpm2.py#L191 we use tpm2_import, which fails since a few hours.

```
Could not execute tpm2_import: INFO on line: "355" in file: "lib/files.c": Assuming tpm context file
INFO on line: "289" in file: "lib/files.c": load: TPMS_CONTEXT->savedHandle: 0x80000000
ERROR on line: "153" in file: "tools/tpm2_tool.c": Unable to run tpm2_import
```

**Comment by williamcroberts** [comment]
Oh dang, I must have broke import. I can't wait to get the TSS python bindings and break this dependency. Ill look into this today

**Comment by PeterHuewe** [comment]
seems to be fixed
