### ISSUE TITLE
Tests might not fail since traps are not inherited to bash functions

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-tools#1535]
In `helpers.sh`, there is a bash trap that exits if a return code other than 0 appears:

```bash
#
# Set the default on ERR handler to print the line number
# and failed command.
#
onerror() {
    echo "$BASH_COMMAND on line ${BASH_LINENO[0]} failed: $?"
    exit 1
}
trap onerror ERR
```

However, this trap is **not** inherited to bash functions. See the [bash reference](https://tiswww.case.edu/php/chet/bash/bashref.html#Shell-Functions):

> All other aspects of the shell execution environment are identical between a function and its caller with these exceptions: [...] the ERR trap is not inherited unless the -o errtrace shell option has been enabled. See Bourne Shell Builtins, for the description of the trap builtin.

If the option `-o errtrace` (or `-E`) is passed, the trap will be inherited:

>    If set, any trap on ERR is inherited by shell functions, command substitutions,
>     and commands executed in a subshell environment. The ERR trap is normally not
>     inherited in such cases.

Due to this issue, there are quite some errors (bash commands not returning 0) which are currently missed. For instance, the test `import.sh` passed although the function `run_aes_import_test()` was broken. See #1146.

I suggest adding a `set -E` at the beginning of `helpers.sh`. Unfortunately, as a consequence, some tests will fail and require further work.

**Comment by williamcroberts** [comment]
> I suggest adding a set -E at the beginning of helpers.sh. Unfortunately, as a consequence, some tests will fail and require further work.

That seems reasonable, why would some tests start failing though? Are they broken and passing?

**Comment by joholl** [comment]
Yes, there are several tests failing, some of which are really broken. I'll keep you updated.

**Comment by joholl** [comment]
I pushed the changes I made to a [feature branch](https://github.com/joholl/tpm2-tools/tree/fix_trap_inheritage). I'll eventually create a PR but I want to discuss some issues first.

- `loadexternal.sh` was completely broken and had many problems which are **fixed** now.
- `incrementalselftest.sh` fails at the moment due to an algorithm named `unknown3f` (printed by tpm2_incrementalselftest). This is probably fixed by [this TSS PR](https://github.com/tpm2-software/tpm2-tss/pull/1437)
- In `import.sh`, `tpm2_evictcontrol` is failing. I'm not sure why it is needed here. Any idea?
- In the function `start_up` (in `herlper.sh`), `tpm2_clear` fails for quite some tests. I'm not sure why. We might add a `|| true`. Do you know why it is failing?
- `policypassword.sh` fails with the error shown below. Any idea about that?

```
+ tpm2_encryptdecrypt -c key.ctx -i enc.txt -o dec.txt -D -p session:session.ctx+testpswd
WARN: Using a weak IV, try specifying an IV

** (tpm2-abrmd:25822): WARNING **: 14:37:54.163: Client attempting to save unknown session.
WARNING:esys:src/tss2-esys/api/Esys_ContextSave.c:243:Esys_ContextSave_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_ContextSave.c:88:Esys_ContextSave() Esys Finish ErrorCode (0x00000910) 
ERROR: Esys_ContextSave(0x910) - tpm:warn(2.0): the 1st handle in the handle area references a transient object or session that is not loaded
ERROR: Could not write session context
ERROR: Unable to run tpm2_encryptdecrypt
```

**Comment by williamcroberts** [comment]
I wish I had details on why certain things were failing. I am getting ready to travel for work a bit, but @idesai this issue is going to be pivotal for the 4.0 release. Can you help @joholl out?

**Comment by williamcroberts** [comment]
> * `incrementalselftest.sh` fails at the moment due to an algorithm named `unknown3f` (printed by tpm2_incrementalselftest). This is probably fixed by [this TSS PR](https://github.com/tpm2-software/tpm2-tss/pull/1437)

Yeah that algorithm lines up with 3F

**Comment by joholl** [comment]
I see that I used a TSS version which was not up-to-date. With the current TSS master ([c885eff0](https://github.com/tpm2-software/tpm2-tss/commit/c885eff0a18500676ba86eb821d3adc6cc0a9d28)), there are only two issues left. Sorry for the confusion.

Issues:
* `incrementalselftest.sh` fails at the moment due to an algorithm named `unknown3f` (printed by tpm2_incrementalselftest). To fix this issue, two steps have to be taken:

    * Apply [this pending TSS PR](https://github.com/tpm2-software/tpm2-tss/pull/1437)
    * Add cmac to `tpm2_alg.c`. Note that this is not a bug in the tests, but the code itself.

- In `import.sh`, `tpm2_evictcontrol` is failing. If it is remove, the test succeeds. What is its purpose?

For reference: my [feature branch](https://github.com/joholl/tpm2-tools/tree/fix_trap_inheritage) and its  [tavis build](https://travis-ci.org/joholl/tpm2-tools/jobs/542700222)

**Comment by diabonas** [comment]
The tpm2-tools-side support for CMAC necessary for `incrementalselftest.sh` is in already #1533, but the upstream tpm2-tss pull requests needs to be merged first so that it can be applied.

**Comment by diabonas** [comment]
Regarding the failing `tpm2_evictcontrol`, I think this line can be deleted entirely since the the persistent handle it used to clean up [has been removed](https://github.com/tpm2-software/tpm2-tools/commit/582419356da695501bbe6bd071e4e7140d61821a#diff-e3e241d3bce558c10efb23f057ba93c5L55).

**Comment by idesai** [comment]
@joholl thanks for finding this high priority issue and the proposed solution. I tested your branch and added a commit for dropping the spurious evict control from import.sh. Do you plan to create the PR for your branch?

**Comment by joholl** [comment]
I rebased my changes and created a PR. Thank you for your help.

**Comment by idesai** [comment]
Thanks!
