### ISSUE TITLE
tpm2_create: invalid option -- 'A'

### ISSUE THREAD

**Issue by akela92** [tpm2-software/tpm2-tools#1557]
Hello everyone,

I am currently writing my master thesis in secure seed generation for IOTA wallets and for that I am using a Raspberry Pi 3 and a TPM chip from Infineon. I have successfully configured the TPM (both the HW and the simulator) and can run some commands.   
Following the instructions in the [Wiki](https://github.com/tpm2-software/tpm2-tools/wiki/Creating-Objects) on how to create objects I encounter an error when creating a parent key (Step 2). I am relatively new to working with TPMs in a practical way and don't understand why this error could be happening.

`$ tpm2_create -C primary.ctx -Grsa2048:null:aes -u key2.pub -r key2.priv -A "restricted|decrypt|fixedtpm|fixedparent|sensitivedataorigin|userwithauth"`
`tpm2_create: invalid option -- 'A'`

When using tpm2_create I get a similar error:

`$ tpm2_create -c po.ctx -K subobjectpass -g 0x000b -G 0x0001 -o key.pub -O key.priv`
`tpm2_create: invalid option -- 'c'`

This is the version I am using:
`tool="tpm2_create" version="3.0.2-1177-ga3b3cd1c" tctis="dynamic" tcti-default=tabrmd dlclose=enabled`

I've have tried with version `3.1.4` but I get similar errors.

Thanks in advance!

**Comment by joholl** [comment]
Hi akela92,

The wiki is outdated, thank you for this hint. I suggest reading the man pages of the tool you want to use for the correct options. Also have a look into the [system tests](https://github.com/tpm2-software/tpm2-tools/tree/bd4fc0cfc945f7cfd29d508f31352071ee07517e/test/system) of the tool you are interested in. Those are bash scripts that show how to use the tools together.

[The following info is about [version 3.1.4](https://github.com/tpm2-software/tpm2-tools/releases/tag/3.1.4)]

E.g. for information how to use the tool `tpm2_unseal` have a look at the test [test/system/test_tpm2_unseal.sh](https://github.com/tpm2-software/tpm2-tools/blob/bd4fc0cfc945f7cfd29d508f31352071ee07517e/test/system/test_tpm2_unseal.sh#L71):

I simplified some bash code for you:
```
echo "secret data" > data.txt

tpm2_startup -c
tpm2_takeownership -c
tpm2_createprimary -H e -g sha256 -G ecc -C primary.ctx
tpm2_create -g sha256 -G keyedhash -u unseal.pub -r unseal.priv -I data.txt -c primary.ctx
tpm2_load -c primary.ctx  -u unseal.pub  -r unseal.priv -n name -C unseal.ctx
tpm2_unseal -c unseal.ctx -o unsealed.txt
```

**Comment by DomiNic5787** [comment]
The interface (parameters) have been changed a lot for the last months/years and they are still not really stable.
For example, the version you used (a3b3cd1c) requires `-b` instead of `-A`.
To find the right parameters for your version, please have a look at the man pages or code.

**Comment by idesai** [comment]
Will address in #1042

**Comment by akela92** [comment]
Hi,

I've tried with the `-b` option and is not working either:

`$ tpm2_create -C primary.ctx -Grsa2048:null:aes -u key2.pub -r key2.priv -b "restricted|decrypt|fixedtpm|fixedparent|sensitivedataorigin|userwithauth"
`

`WARNING:esys:src/tss2-esys/api/Esys_ContextLoad.c:275:Esys_ContextLoad_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_ContextLoad.c:89:Esys_ContextLoad() Esys Finish ErrorCode (0x000001df) 
ERROR: Esys_ContextLoad(0x1DF) - tpm:parameter(1):integrity check failed
ERROR: Unable to run tpm2_create`

I've also tried the command in the test file, but no luck:

`$ tpm2_create -c context.out -g sha256 -G 0x1 -L policy.bin -u key.pub -r key.priv \
-A 'sign|fixedtpm|fixedparent|sensitivedataorigin' > out.pub`

`tpm2_create: invalid option -- 'c'`

I've also tried I few other commands from the man page, but nothing is working. I always get an error when I tried to use attributes.

Thanks for your help

**Comment by joholl** [comment]
The options are not broken, you just need to read the manual for your particular version. The_ following commands are working fine for versions `3.1.4` and `3.2.0` (which was released just now):

    tpm2_startup -c
    tpm2_createprimary -H o -g sha256 -G rsa -C primary.ctx
    tpm2_create -c primary.ctx -g sha256 -G rsa -u key.pub -r key.priv   -A 'sign|fixedtpm|fixedparent|sensitivedataorigin'

For further questions, please do not use the bugtracker.

**Comment by akela92** [comment]
I've downloaded the new version `3.2.0` and the options for the commands `tpm2_createprimary` and `tpm2_create` you wrote don't work. Looking in the manual I figured out which options I had to change to successfully create a primary key and a child of that one:

`tpm2_createprimary -a o -g sha256 -G rsa -o primary.ctx`
`tpm2_create -C primary.ctx -g sha256 -G rsa -u key.pub -r key.priv   -b 'sign|fixedtpm|fixedparent|sensitivedataorigin'`                                                                                       

Thanks for the help.

PS: I don't understand what you mean by not using the bugtrucker
