### ISSUE TITLE
TPM2_PT_LOCKOUT_COUNTER: is not incrementing.

### ISSUE THREAD

**Issue by srinivasahk** [tpm2-software/tpm2-tools#1571]
Hi, 
I was running code for dictionarylockout with parameters, I could see the error 0x98e(DA counter is increase)  when i pass wrong password but could see the counter getting incremented. Am I missing something here? 

pi@raspberrypi:~/tpm/tpm2_files/tpm2_src_files $ tpm2_rc_decode 0x98e
error layer
  hex: 0x0
  identifier: TSS2_TPM_RC_LAYER
  description: Error produced by the TPM
format 1 error code
  hex: 0x0e
  identifier: TPM2_RC_AUTH_FAIL
  description: the authorization HMAC check failed and DA counter incremented
session
  hex: 0x100
  identifier: TPM2_RC_1
  description:  (null)

pi@raspberrypi:~/tpm/tpm2_files/tpm2_src_files $ tp
TPM_PT_PERSISTENT:
  ownerAuthSet:              set
  endorsementAuthSet:        clear
  lockoutAuthSet:            set
  reserved1:                 clear
  disableClear:              clear
  inLockout:                 clear
  tpmGeneratedEPS:           clear
  reserved2:                 clear
TPM_PT_STARTUP_CLEAR:
  phEnable:                  set
  shEnable:                  set
  ehEnable:                  set
  phEnableNV:                set
  reserved1:                 clear
  orderly:                   clear
TPM_PT_TPM2_HR_NV_INDEX:          0x00000002
TPM_PT_HR_LOADED:            0x00000000
TPM_PT_HR_LOADED_AVAIL:      0x00000003
TPM_PT_HR_ACTIVE:            0x00000000
TPM_PT_HR_ACTIVE_AVAIL:      0x00000040
TPM_PT_TPM2_HR_TRANSIENT_AVAIL:   0x00000003
TPM_PT_TPM2_HR_PERSISTENT:        0x00000002
TPM_PT_TPM2_HR_PERSISTENT_AVAIL:  0x00000010
TPM_PT_NV_COUNTERS:          0x00000000
TPM_PT_NV_COUNTERS_AVAIL:    0x0000000d
TPM_PT_ALGORITHM_SET:        0x00000000
TPM_PT_LOADED_CURVES:        0x00000002
TPM_PT_LOCKOUT_COUNTER:      0x00000000
TPM_PT_MAX_AUTH_FAIL:        0x00000002
TPM_PT_LOCKOUT_INTERVAL:     0x00000064
TPM_PT_LOCKOUT_RECOVERY:     0x00000001
TPM_PT_AUDIT_COUNTER_0:      0x00000000
TPM_PT_AUDIT_COUNTER_1:      0x00000000

**Comment by AndreasFuchsSIT** [comment]
Which TPM are you using for your tests ?

**Comment by srinivasahk** [comment]
I m using infineon tpm & see same behavior with linux hw tpm.
Thanks,Srinivas.

    On Tuesday, 25 June 2019, 17:07:16 GMT+5:30, Andreas Fuchs <notifications@github.com> wrote:  
 
 
Which TPM are you using for your tests ?

**Comment by idesai** [comment]
@srinivasahk is your object defined with noDA set?

**Comment by joholl** [comment]
@srinivasahk Could you please show us which steps you took so we can reproduce the issue? Please share your TPM firmware version as well (`tpm2_getcap -c properties-fixed`).

Note that the DA lockout counter decrements automatically every `TPM_PT_LOCKOUT_INTERVAL` seconds, in your case 100s.

**Comment by srinivasahk** [comment]
Hi,No, noDA is not set. 

Here is the flow: 
              
    Call  dictionary parameter set with admin define value.    Call  hierarchyChangeAuth with auth value for lockout.    Call again hierarchyChangeAuth with wrong auth value.
Thanks,Srinivas.
   
    On Wednesday, 26 June 2019, 02:44:43 GMT+5:30, Imran Desai <notifications@github.com> wrote:  
 
 
@srinivasahk is your object defined with noDA set?

**Comment by srinivasahk** [comment]
Hi,
Here is the flow: 
              
    Call  dictionary parameter set with admin define value.    Call  hierarchyChangeAuth with auth value for lockout.    Call again hierarchyChangeAuth with wrong auth value.
Here I can see the return code TPM is in DA lockmode. 

tpm2_rc_decode 0x921error layer
  hex: 0x0
  identifier: TSS2_TPM_RC_LAYER
  description: Error produced by the TPM
format 0 warning code
  hex: 0x21
  name: TPM2_RC_LOCKOUT
  description: authorizations for objects subject to DA protection are not allowed at this time because the TPM is in DA lockout mode

TPM_PT_PERSISTENT:
  ownerAuthSet:              set
  endorsementAuthSet:        clear
  lockoutAuthSet:            set
  reserved1:                 clear
  disableClear:              clear
  inLockout:                 clear
  tpmGeneratedEPS:           clear
  reserved2:                 clear
TPM_PT_STARTUP_CLEAR:
  phEnable:                  set
  shEnable:                  set
  ehEnable:                  set
  phEnableNV:                set
  reserved1:                 clear
  orderly:                   set
TPM_PT_TPM2_HR_NV_INDEX:          0x00000002
TPM_PT_HR_LOADED:            0x00000000
TPM_PT_HR_LOADED_AVAIL:      0x00000003
TPM_PT_HR_ACTIVE:            0x00000000
TPM_PT_HR_ACTIVE_AVAIL:      0x00000040
TPM_PT_TPM2_HR_TRANSIENT_AVAIL:   0x00000003
TPM_PT_TPM2_HR_PERSISTENT:        0x00000002
TPM_PT_TPM2_HR_PERSISTENT_AVAIL:  0x00000010
TPM_PT_NV_COUNTERS:          0x00000000
TPM_PT_NV_COUNTERS_AVAIL:    0x0000000d
TPM_PT_ALGORITHM_SET:        0x00000000
TPM_PT_LOADED_CURVES:        0x00000002
TPM_PT_LOCKOUT_COUNTER:      0x00000000
TPM_PT_MAX_AUTH_FAIL:        0x00000002
TPM_PT_LOCKOUT_INTERVAL:     0x00000064
TPM_PT_LOCKOUT_RECOVERY:     0x00000004
TPM_PT_AUDIT_COUNTER_0:      0x00000000
TPM_PT_AUDIT_COUNTER_1:      0x00000000


tpm2_getcap -c properties-fixed
WARN: More data to be queried: capability: 0x6, property: 0x100

TPM_PT_FAMILY_INDICATOR:
  as UINT32:                0x08322e3000
  as string:                "2.0"
TPM_PT_LEVEL:               0
TPM_PT_REVISION:            1.16
TPM_PT_DAY_OF_YEAR:         0x0000000f
TPM_PT_YEAR:                0x000007e0
TPM_PT_MANUFACTURER:        0x49465800
TPM_PT_VENDOR_STRING_1:
  as UINT32:                0x534c4239
  as string:                "SLB9"
TPM_PT_VENDOR_STRING_2:
  as UINT32:                0x36373000
  as string:                "670"
TPM_PT_VENDOR_STRING_3:
  as UINT32:                0x00000000
  as string:                ""
TPM_PT_VENDOR_STRING_4:
  as UINT32:                0x00000000
  as string:                ""
TPM_PT_VENDOR_TPM_TYPE:     0x00000000
TPM_PT_FIRMWARE_VERSION_1:  0x0007003d
TPM_PT_FIRMWARE_VERSION_2:  0x000ae100
TPM_PT_INPUT_BUFFER:        0x00000400
TPM_PT_TPM2_HR_TRANSIENT_MIN:    0x00000003
TPM_PT_TPM2_HR_PERSISTENT_MIN:   0x00000007
TPM_PT_HR_LOADED_MIN:       0x00000003
TPM_PT_ACTIVE_SESSIONS_MAX: 0x00000040
TPM_PT_PCR_COUNT:           0x00000018
TPM_PT_PCR_SELECT_MIN:      0x00000003
TPM_PT_CONTEXT_GAP_MAX:     0xffffffff
TPM_PT_NV_COUNTERS_MAX:     0x00000008
TPM_PT_NV_INDEX_MAX:        0x00000680
TPM_PT_MEMORY:              0x00000006
TPM_PT_CLOCK_UPDATE:        0x00080000
TPM_PT_CONTEXT_HASH:        0x0000000b
TPM_PT_CONTEXT_SYM:         0x00000006
TPM_PT_CONTEXT_SYM_SIZE:    0x00000080
TPM_PT_ORDERLY_COUNT:       0x000000ff
TPM_PT_MAX_COMMAND_SIZE:    0x00000500
TPM_PT_MAX_RESPONSE_SIZE:   0x00000500
TPM_PT_MAX_DIGEST:          0x00000020
TPM_PT_MAX_OBJECT_CONTEXT:  0x000003b8
TPM_PT_MAX_SESSION_CONTEXT: 0x000000eb
TPM_PT_PS_FAMILY_INDICATOR: 0x00000001
TPM_PT_PS_LEVEL:            0x00000000
TPM_PT_PS_REVISION:         0x00000100
TPM_PT_PS_DAY_OF_YEAR:      0x00000000
TPM_PT_PS_YEAR:             0x00000000
TPM_PT_SPLIT_MAX:           0x00000080
TPM_PT_TOTAL_COMMANDS:      0x0000005a
TPM_PT_LIBRARY_COMMANDS:    0x00000059
TPM_PT_VENDOR_COMMANDS:     0x00000001
TPM_PT_NV_BUFFER_MAX:       0x00000300



Thanks,Srinivas.
   
    On Wednesday, 26 June 2019, 12:32:21 GMT+5:30, Johannes Holland <notifications@github.com> wrote:  
 
 
@srinivasahk Could you please show us which steps you took so we can reproduce the issue? Please share your TPM firmware version as well (tpm2_getcap -c properties-fixed).

Note that the DA lockout counter decrements automatically every TPM_PT_LOCKOUT_INTERVAL seconds, in your case 100s.

**Comment by joholl** [comment]
@srinivasahk

Please tell us the exact sequence of tpm2-tool commands which lead to the (intended) error `0x98e`. Please also tell us the output of `tpm2_getcap -c properties-fixed`. Otherwise we will not be able to reproduce this issue.

Also, which version of tpm-tools are you using?

**Comment by srinivasahk** [comment]
Hi,
In command Pdf TPM2_DictionaryAttackParameters it says. This command will set the authorization failure count (failedTries) to zero.  Here I m not sure whether the counter is internally maintained & not showing in getcap. 


I m not using TPM-tools but calling direct api: 

I tried in tools below is the result:
tools version : 3.1.4

tpm2_clear -p
pi@raspberrypi:~/tpm/tpm2-tools $ tpm2_dictionarylockout --setup-parameters --lockout-recovery-time=100 --recovery-time=1 --max-tries=3
pi@raspberrypi:~/tpm/tpm2-tools $ tpm2_changeauth --new-lockout-passwd=test
pi@raspberrypi:~/tpm/tpm2-tools $ tpm2_changeauth --current-lockout-passwd=test1  --new-lockout-passwd=test1
WARNING:esys:src/tss2-esys/api/Esys_HierarchyChangeAuth.c:303:Esys_HierarchyChangeAuth_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_HierarchyChangeAuth.c:110:Esys_HierarchyChangeAuth() Esys Finish ErrorCode (0x0000098e) 
ERROR: Esys_HierarchyChangeAuth(0x98E) - tpm:session(1):the authorization HMAC check failed and DA counter incremented


Output of tpm2_getcap -c properties-fixed
WARN: More data to be queried: capability: 0x6, property: 0x100

TPM_PT_FAMILY_INDICATOR:
  as UINT32:                0x08322e3000
  as string:                "2.0"
TPM_PT_LEVEL:               0
TPM_PT_REVISION:            1.16
TPM_PT_DAY_OF_YEAR:         0x0000000f
TPM_PT_YEAR:                0x000007e0
TPM_PT_MANUFACTURER:        0x49465800
TPM_PT_VENDOR_STRING_1:
  as UINT32:                0x534c4239
  as string:                "SLB9"
TPM_PT_VENDOR_STRING_2:
  as UINT32:                0x36373000
  as string:                "670"
TPM_PT_VENDOR_STRING_3:
  as UINT32:                0x00000000
  as string:                ""
TPM_PT_VENDOR_STRING_4:
  as UINT32:                0x00000000
  as string:                ""
TPM_PT_VENDOR_TPM_TYPE:     0x00000000
TPM_PT_FIRMWARE_VERSION_1:  0x0007003d
TPM_PT_FIRMWARE_VERSION_2:  0x000ae100
TPM_PT_INPUT_BUFFER:        0x00000400
TPM_PT_TPM2_HR_TRANSIENT_MIN:    0x00000003
TPM_PT_TPM2_HR_PERSISTENT_MIN:   0x00000007
TPM_PT_HR_LOADED_MIN:       0x00000003
TPM_PT_ACTIVE_SESSIONS_MAX: 0x00000040
TPM_PT_PCR_COUNT:           0x00000018
TPM_PT_PCR_SELECT_MIN:      0x00000003
TPM_PT_CONTEXT_GAP_MAX:     0xffffffff
TPM_PT_NV_COUNTERS_MAX:     0x00000008
TPM_PT_NV_INDEX_MAX:        0x00000680
TPM_PT_MEMORY:              0x00000006
TPM_PT_CLOCK_UPDATE:        0x00080000
TPM_PT_CONTEXT_HASH:        0x0000000b
TPM_PT_CONTEXT_SYM:         0x00000006
TPM_PT_CONTEXT_SYM_SIZE:    0x00000080
TPM_PT_ORDERLY_COUNT:       0x000000ff
TPM_PT_MAX_COMMAND_SIZE:    0x00000500
TPM_PT_MAX_RESPONSE_SIZE:   0x00000500
TPM_PT_MAX_DIGEST:          0x00000020
TPM_PT_MAX_OBJECT_CONTEXT:  0x000003b8
TPM_PT_MAX_SESSION_CONTEXT: 0x000000eb
TPM_PT_PS_FAMILY_INDICATOR: 0x00000001
TPM_PT_PS_LEVEL:            0x00000000
TPM_PT_PS_REVISION:         0x00000100
TPM_PT_PS_DAY_OF_YEAR:      0x00000000
TPM_PT_PS_YEAR:             0x00000000
TPM_PT_SPLIT_MAX:           0x00000080
TPM_PT_TOTAL_COMMANDS:      0x0000005a
TPM_PT_LIBRARY_COMMANDS:    0x00000059
TPM_PT_VENDOR_COMMANDS:     0x00000001
TPM_PT_NV_BUFFER_MAX:       0x00000300






    On Wednesday, 26 June 2019, 13:24:56 GMT+5:30, Johannes Holland <notifications@github.com> wrote:  
 
 
@srinivasahk

Please tell us the exact sequence of tpm2-tool commands which lead to the (intended) error 0x98e. Please also tell us the output of tpm2_getcap -c properties-fixed. Otherwise we will not be able to reproduce this issue.

Also, which version of tpm-tools are you using?

**Comment by joholl** [comment]
Actually, not incrementing *failedTries* is compliant behavior with the [specification](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf). Please see section 19.8.5.

**Comment by srinivasahk** [comment]
Thanks Johannes. 

 

    On Wednesday, 26 June 2019, 15:31:43 GMT+5:30, Johannes Holland <notifications@github.com> wrote:  
 
 
Actually, not incrementing failedTries is compliant behavior with the specification. Please see section 19.8.5.

**Comment by joholl** [comment]
You're welcome. Thank you for your contribution.

@idesai could you please close this issue?

**Comment by srinivasahk** [comment]
Closing the case, It is expected behavior when used dictionaryLockout parameters.
