### ISSUE TITLE
Configure is failing

### ISSUE THREAD

**Issue by remuswu1019** [tpm2-software/tpm2-tools#1577]
Configure throws below error:
```
$./bootstrap
Generating file lists: src_vars.mk
$ ./configure
configure: error: Invalid policy. Valid policies: git-directory, minor-version.
```
For more information:
```
$ uname -a
Linux maserati 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch
```

**Comment by joholl** [comment]
Have a look at [TSS #69](https://github.com/tpm2-software/tpm2-pkcs11/issues/69). What is your `autoconf-archive` version?

**Comment by remuswu1019** [comment]
> Have a look at [TSS #69](https://github.com/tpm2-software/tpm2-pkcs11/issues/69). What is your `autoconf-archive` version?
Before I upgrade my system, autoconf-archive is version 20160916-1.
```
autoconf-archive is already the newest version (20160916-1).
```
After upgrade to version (20180313-1), issue solved. 

Thanks @joholl 👍
