### ISSUE TITLE
test: integration tests should be verbose

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-tools#1592]
In the integration tests, passing `-Q` (quiet) to the called tools is a common practice. There have also been efforts to make the tests less verbose (#1591). However, IMO tests should be as verbose as possible. If a test fails, it is much easier to find the problem (especially with CI like travis).

When a user runs `make check`, the output is redirected into a logfile anyway. The user usually does not see the output. Additionally, tests are generally not parsed.

Hence, we should remove `-Q` and add `-V` for tools calls in the tests whenever possible and refrain from removing verbosity.

@williamcroberts What do you think?

**Comment by idesai** [comment]
@joholl not sure how much slower it would make travis. Have you done test runs to evaluate?
Also travis outputs the failure results in detail towards the tail end. If you collapse the arrow you could see it. The advantage being, it only does the lengthy output for failure reports.
![image](https://user-images.githubusercontent.com/16821900/61175182-e2611480-a55f-11e9-85cf-37469f3671b5.png)

**Comment by joholl** [comment]
Let me just describe my understanding here (please correct me if I'm wrong).

- If you run a test like `integration/tests/toggle_options.sh`, the output of the test script (and the setup script) directly appears on the console.
- `make check` redirects the output of each test to their respective logfile (e.g. `integration/tests/toggle_options.log`) and copies the logs of all failed tests into `test-suite.log`
- `travis` simply calls `cat` on `test-suite.log` to enable the user to inspect it

That means the output of the failed tests is exactly what you see at the end of a travis log. Everything else is output generated by make. In case of a failed test we want this log to be as verbose as possible.

**Comment by williamcroberts** [comment]
-Q only turns off stdout output. Some tools output result information to stdout. Any errors or warnings are still logged.

**Comment by joholl** [comment]
I know right. IMHO when searching for problems in log files, it helps to have *as much information as possible*, that includes verbosity levels I consider info/trace, not only warning/error.
