### ISSUE TITLE
tpm2_import: hmac support

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1597]
Add support for importing HMAC keys

**Comment by osresearch** [comment]
Was this ever implemented? In #1556 it is implied that HMAC keys can be imported, although the man page doesn't mention it and `tpm2 import -G hmac` results in `ERROR: Cannot handle algorithm, got: hmac`

**Comment by salrashid123** [comment]
Just checking if this capability is in the works for an upcoming release?

**Comment by salrashid123** [comment]
thanks.   suggest adding in an examples here for the import too:
*   https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_import.1.md#examples
*   https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_hmac.1.md

```bash
export secret="key"
export plain="The quick brown fox jumps over the lazy dog"

echo -n $secret > hmac.key
hexkey=$(xxd -p -c 256 < hmac.key)
echo $hexkey

echo -n $plain > data.in

openssl dgst -sha256 -mac hmac -macopt hexkey:$hexkey data.in
   HMAC-SHA256(data.in)= f7bc83f430538424b13298e6aa6fb143ef4d59a14946175997479dbc2d1a3cd8
   

tpm2 createprimary -Q -G rsa -g sha256 -C e -c primary.ctx

tpm2 import -C primary.ctx -G hmac -i hmac.key -u hmac.pub -r hmac.priv
tpm2 load -C primary.ctx -u hmac.pub -r hmac.priv -c hmac.ctx

echo -n $plain | tpm2_hmac -g sha256 -c hmac.ctx | xxd -p -c 256
    f7bc83f430538424b13298e6aa6fb143ef4d59a14946175997479dbc2d1a3cd8

```

---

as a side note, importing hmac could be used to generate AWS S4 signed requests and for S3 and Google storage signedurls.
eg, for aws request, i used go-tpm [here](https://github.com/salrashid123/aws_hmac) to create an AWS v4 signer
