### ISSUE TITLE
TPM2 tools export keys in a parsable form

### ISSUE THREAD

**Issue by nmav** [tpm2-software/tpm2-tools#1599]
The TPM2 tools like tpm2_createprimary and tpm2_create output keys in a form that cannot be identified by other applications. There is a defacto standard from the tpm2 openssl engines which is a PEM (base64) encoding with header "BEGIN TSS2 PRIVATE KEY" of the DER encoding of the ASN.1 definition below:

```
 TPMKey ::= SEQUENCE {
    type            OBJECT IDENTIFIER,
    emptyAuth       [0] EXPLICIT BOOLEAN OPTIONAL,
    parent          INTEGER,
    pubkey          OCTET STRING,
    privkey         OCTET STRING
}
```

(see https://github.com/tpm2-software/tpm2-tss-engine/blob/master/src/tpm2-tss-engine-common.c#L44 )

The advantage of this form in comparison with the existing form is that:
     1. a single file is used to store public and private key
     2. the file can be detected from the PEM header

It would be useful for other applications not necessarily depending on openssl engine to be able to use TPM2 keys, and the move by tpm2-tools to outputing format will make this simpler. In particular it will allow opening such keys as part of a generic key opening routine rather than a specialized tpm2 key loading which will require multiple files and options.

That change can be backwards compatible and would improve interaction with tpm2-tools as well, for the same reasons (a single file needed, future revisions can rely on headers to load older formats).

[amended 2019-08-7: I realized that the a similar issue occurs for the public portion of the key; the format exported by `tpm2_create` is unknown (to me) and a standard SubjectPublicKeyInfo would have been much more useful.]

**Comment by dwmw2** [comment]
It would be extremely useful to be able to import/export such keys with the PKCS#11 module too.

**Comment by williamcroberts** [comment]
> It would be extremely useful to be able to import/export such keys with the PKCS#11 module too.

FYI That is a goal.

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT we mentioned a tpm2 util library. The first 2 really useful candidates are:
1. load from disk in multiple forms
2. save to disk in multiple forms

**Comment by AndreasFuchsSIT** [comment]
Well, yes, that format is definately useful. Don't know if it's the perfect match for the tools, since they are oriented on part 3 of tpm-spec. But as **additional** option, this could be useful for people...

**Comment by williamcroberts** [comment]
useful for tools, we do PEM conversions

**Comment by williamcroberts** [comment]
Plus that's also code common to FAPI

**Comment by williamcroberts** [comment]
So their is 2 items in this for the tpm2-tools project:
[ ] - use keys, including private, in pem form.
[ ] - export keys to pem form (addition to tpm2_print would probably be nice) We could add a conversion format specifier to it.

**Comment by osresearch** [comment]
`tpm2_createek` and `tpm2_createak` have `--format` option to export the keys in PEM or DER format. Perhaps `tpm2_create` should have that as well.

**Comment by drandreas** [comment]
I decided to write an `TSS2 PRIVATE KEY` parser for mbedtls. While the code is by no means feature complete. It might be useful to someone who wants a "simple" sample of an non-openssl parser.

[get-pubkey.c.zip](https://github.com/tpm2-software/tpm2-tools/files/5556786/get-pubkey.c.zip)

**Comment by idesai** [comment]
> `tpm2_createek` and `tpm2_createak` have `--format` option to export the keys in PEM or DER format. Perhaps `tpm2_create` should have that as well.

Support added in 5.2

**Comment by ueno** [comment]
> > `tpm2_createek` and `tpm2_createak` have `--format` option to export the keys in PEM or DER format. Perhaps `tpm2_create` should have that as well.
> 
> Support added in 5.2

I've tried 5.2-rc0 and it indeed works, thank you! On the other hand, as it only encodes public key, the original request to output both public and private key blobs still not seems to be covered.

**Comment by osresearch** [comment]
The EK and AK private keys are not exportable, so they should not be available outside the TPM. If you want to use the private key of a TPM resident key, you might be interested in using `tpm2-duplicate` to import an externally generated key. Support for this was added in https://github.com/tpm2-software/tpm2-tools/pull/2386

**Comment by ueno** [comment]
Sorry, my wording was wrong: I meant the private portion of created object (which we could specify with the `-r` option of `tpm2_load`). When using `tpm2_create --format pem -u pub -r priv -o out`, `pub` and `out` are equivalent except the encoding and preceding length bytes.

**Comment by ueno** [comment]
I tried to port `tpm2tss-genkey` from `tpm2-tss-engine` in #2838; that should complement the `tpm2_create --format pem` option to suffice the original requirement. That can be used something like (with `certtool` from GnuTLS [MR](https://gitlab.com/gnutls/gnutls/-/merge_requests/1460)):
```console
$ tpm2_createprimary -C o -g sha256 -G ecc -c primary.ctx -a "userwithauth|restricted|decrypt|fixedtpm|fixedparent|noda|sensitivedataorigin"
$ tpm2_create -C primary.ctx -g sha256 -G ecc -u pub.out -r priv.out -f pem -o pub.pem
$ tpm2_encodeobject -C primary.ctx -u pub.out -r priv.out -o priv.pem
$ certtool --generate-self-signed --load-privkey priv.pem --load-pubkey pub.pem --template=.../gnutls/doc/credentials/ca.tmpl --outfile cert.pem
[...]
Signing certificate...
```
The good thing is that the serialized object (`priv.pem`) can be seen as a regular private key file as in X.509  and thus handled transparently from the application point of view. On the other hand, I'm not so sure if the stored information is sufficient to recover the original object: for example, if the parent object is generated, it may need to be initialized with the same [attributes](https://gitlab.com/gnutls/gnutls/-/issues/594#note_651399228).

**Comment by dwmw2** [comment]
Yes, the parent object definitely has to be initialized with precisely the same attributes. We had to ensure that the two engines, and OpenConnect, all did it precisely the same way. The attributes used to create the parent object are an implicit part of the file format "standard".

**Comment by dwmw2** [comment]
Just checking... after you sign that cert, you should also be able to run `openconnect -c cert.pem -k priv.pem ...` and use it as a client cert?
