### ISSUE TITLE
Rename Options: Pending issues with changeset #1600

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tools#1602]
Pending fixes
- [x] Rename options for tpm2_checkquote.
- [x] Rename options for tpm2_print.
- [x] Change context short option from -o to -c in tpm2_create, tpm2_createprimary, tpm2_load, tpm2_loadexternal.
- [x] qualification-data should become qualification in tpm2_quote, tpm2_checkquote, tpm2_policyauthorize.
- [x] -L becomes -i as in input policy and -o becomes -L the final policy.
- [x] object-attributes becomes attributes in tpm2_create, tpm2_createprimary, tpm2_import, tpm2_loadexternal.

Changeset #1600 objectives:
Progresses #1039 and #1042 
1. Tools requiring hierarchy specified should use option "hierarchy" --> auth-hierarchy goes away
2. Tools requiring single authentication should use option "auth" alone --> auth-hierarchy, hierarchy-auth, object-auth etc. goes away
3. Tools requiring multiple auths should follow "object-auth" to tell apart auths--> auth-hierarchy becomes hierarchy-auth, auth-key becomes key-auth, etc.
4. halg becomes hash-algorithm
kalg,algorithm becomes key-algorithm
sig becomes signature
5. All options drop the term file. Eg. in-file becomes input
6. All tools using hierarchy input should specify it as C
7. Endorsement hierarchy will use known abbreviations and becomes eh
set-list, sel-list becomes pcr-list with short option becoming "l"
8. alg becomes algorithm in general
Tools with single option taking type hierarchy or NV or other tpm handle types should call it "object-context" and use short option "C"
9. qualify-data becomes qualification-data
10. pcr-input short option becomes "f" and long options becomes pcr

**Comment by williamcroberts** [comment]
@idesai when they're fixed, hit the close button too
