### ISSUE TITLE
Switch anything YAML to JSON

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1606]
We should consider switching the output to JSON, which I think we would be compliant since JSON is a subset and I don't think we are using any YAML only stuff.

This serves as a ticket for discussion and inquiry into doing this.

**Comment by AndreasFuchsSIT** [comment]
I don't know whether this might be too disruptive for all the consumers of tpm2-tools.
As much as I favor JSON over YAML, I'm afraid that we will lose quite a lot of users over this...

A slower approach of adding a --json-outputs switch that turns all outputs into JSON and enabling autodetection between JSON and YAML on inputs might be a better approach going forward.

Also this could be done for 4.1 I guess ?

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT a few things:
* I don't think we use any single YAML feature, folks should be able to parse output with YAML or JSON as is
* The 3.X release also had some early YAML stuff in it, but again I don't think it had anything JSON would balk at, but I need to do deeper analysis. 3.X and 4.X are already incredibly different, I don't see us losing any more users over this. 4.X and moving forward will be backwards compitable, so it's important that we get this choice correct. Considering that other places will be doing JSON, it's worth investigating this now.

**Comment by williamcroberts** [comment]
> >per analysis. 3.X and 4.X are already incredibly different, I don't see us losing any more users over 
 this. 4.X and moving forward will be backwards compitable, so it's important that we get this choice correct. Considering that other places will be doing JSON, it's worth investigating this now.

Nope dies on the way the output from create is structured, and I don't want to add the { and the " to the output... YAML lives.
