### ISSUE TITLE
tpm2_makecredentials --openssl-backend option broken

### ISSUE THREAD

**Issue by mtayyab01** [tpm2-software/tpm2-tools#1614]
When tpm2_makecredentials is invoked with option --openssl-backend, it should invoke the function make_external_credential_and_save() but this function is not invoked. Is it a bug or something I have misunderstood?

make_credentials with ECC keys is not support yet. Can you please let me know a time frame when it is planned? Out of curiosity, I want to understand with ECC how seed will be wrapped with ECC based Endorsement Key. If you can point me to the right TCG document, it'll be highly appreciated.

Thanks,
Muhammad

**Comment by williamcroberts** [comment]
Please see commit: 56710b6e1c4d3e02ff77

We removed -X/--openssl-backend, so now if no tpm context is initialized it works with openssl.... So if you don't have TPM it just uses openssl else it uses TPM. Their is no way to force the behavior, do you need a force flag back?

**Comment by williamcroberts** [comment]
Looks like we need to remove them from the tpm2_options.c folder.

**Comment by mtayyab01** [comment]
I tested with the 4.0-rc0 , but it still needs a TPMC instance running. 

Is there any particular flag/config needs to be enabled?

**Comment by williamcroberts** [comment]
> I tested with the 4.0-rc0 , but it still needs a TPMC instance running.
> 
> Is there any particular flag/config needs to be enabled?

The option is gone, it just checks to see If a TPM is present. If a TPM is present
It uses the TPM. If a TPM isn't present, it doesn't.

Do you need a way to not use the TPM is a TPM is present on the system?

**Comment by mtayyab01** [comment]
> I tested with the 4.0-rc0 , but it still needs a TPMC instance running. Is there any particular flag/config needs to be enabled?
> The option is gone, it just checks to see If a TPM is present. If a TPM is present It uses the TPM. If a TPM isn't present, it doesn't. Do you need a way to not use the TPM is a TPM is present on the system?

@williamcroberts I could figure it out. Thanks! No more action item needed. I was not passing tcti=none

**Comment by williamcroberts** [comment]
I forgot about that option! Glad you figured it out.
