### ISSUE TITLE
ErrorCode: 0x1d5 - Current Kernel limits TPM2  @ 128bytes keyfiles

### ISSUE THREAD

**Issue by homepods** [tpm2-software/tpm2-tools#1621]
Hello all!

I am trying to create an object to load it to the module, but I get some errors with codes (i assume memory - maybne, computer code) which I don't have reference too
```

[root] tpm2_create -g sha256 -G keyedhash -u obj.pub -r obj.priv -c primary.context -L policy.digest -A "noda|adminwithpolicy|fixedparent|fixedtpm" -I secret.bin
ERROR: 
Create Object Failed ! ErrorCode: 0x1d5
```
I've created context and policy files. 

Can someone provide more information ?

**Comment by homepods** [comment]
After a bit of research, I found what the issue is and needs to be solved.
With this version of kernel, the TPM2 supports max 128bytes key files which is limited by the kernel itself. This needs to go higher and allow **keyfiles up to 1024bytes** on TPM2 firmware.

 I would re-complie and edit the **b/include/keys/trusted-type.h** to modify as such.

would you agree with me?


`iff --git a/include/keys/trusted-type.h b/include/keys/trusted-type.h
index a6a1008..42cf2d9 100644
--- a/include/keys/trusted-type.h
+++ b/include/keys/trusted-type.h
@@ -18,6 +18,7 @@ 
 **#define MAX_KEY_SIZE			128**
 #define MAX_BLOB_SIZE			512
 #define MAX_PCRINFO_SIZE		64
+#define MAX_DIGEST_SIZE			64`

**Comment by homepods** [comment]
A user provided HMAC key is not allowed to be larger than the smaller of the block size of the hash
algorithm or 128 octets. Limiting the size to 128 octets is for compatibility of structures between TPM.

The HMAC algorithm requires that keys larger than the hash block size be hashed before use. This
may result in fewer bits of entropy in the HMAC key t han expected by the caller. The TPM will not
allow the caller to specify an overly large value for the HMAC key. If the caller desires to use a
larger value, they should perform the digest externally and pass the resulting digest to the TPM for
use as the HMAC key.

**Comment by homepods** [comment]
but this is for TPM not TPM2, so why stick to 128bytes keyfiles???

**Comment by williamcroberts** [comment]
You're quote specifies why:
```
A user provided HMAC key is not allowed to be larger than the smaller of the block size of the hash
algorithm or 128 octets. Limiting the size to 128 octets is for compatibility of structures between TPM.
```
I am not sure exactly what compatibility they are referring to. But it's in https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf 27.7.5.1 of the aforementioned tpm2.0 spec. Thus the TPM has to implement it.

You might be able to get more details if you post a question to:
https://lists.01.org/mailman/listinfo/tpm2
