### ISSUE TITLE
man/tpm2_policyor: example issues

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1628]
Their are some questions that arrose when I looked into the policyor manpage.

 - [x] why do we fake a pcr extension on sha1 but build policy against bank sha256?
 - [x] why don't we show the pcr extension occurring and the other branch succeeding? Can we 
       have this?

Please address these concerns.

**Comment by idesai** [comment]
> Their are some questions that arrose when I looked into the policyor manpage.
> 
> * [ ]  why do we fake a pcr extension on sha1 but build policy against bank sha256?
> * [ ]  why don't we show the pcr extension occurring and the other branch succeeding? Can we
>   have this?
> 
> Please address these concerns.

We don't. The list option in policyor uses the list language to specify a list of policies to compound and the specified digest algorithm is for the policy digest.
