### ISSUE TITLE
refactor tpm2_qoute

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1647]
tpm2_quote is a bit of a maze, refactor.

**Comment by tomoveu** [comment]
Indeed. Unfortunately, with the addition of ESAPI this was not solved, but rather remained buried. Adding more abstraction to the stack does not enable adoption, it only masks complexity such as this "tpm2_quote". I am interested in refactoring tpm2_quote, if we can get some guarantees about API-backward compatibility in the stack and commands. The transition from SAPI to ESAPI was done in a way that broke API without proper notice on the project page. It was done like no one is using the stack. Not a great experience.

**Comment by tomoveu** [comment]
@williamcroberts I see this improvement was dropped from 4.1 milestone. Does this mean it will be part of a later release?

I am more than happy to help, if there is guaranty for API backward comparability.

**Comment by idesai** [comment]
Not clear what changes are required from the issue description. Please reopen the ticket with specific changes or issues.
