### ISSUE TITLE
Possible typo in tpm2_getcap TPM2_PT_FAMILY_INDICATOR

### ISSUE THREAD

**Issue by yhemery** [tpm2-software/tpm2-tools#1655]
Hi,

It looks like the tpm2_getcap tool has a small typo here :

https://github.com/tpm2-software/tpm2-tools/blob/727cbffd96c91403f4e517e7a7f8d12a8d52d846/tools/tpm2_getcap.c#L267

The output is (on version 3.2.0) :

> TPM_PT_FAMILY_INDICATOR:
>   as UINT32:                0x**08**322e3000
>   as string:                "2.0"

The "08" seems to be out of place. I may create a PR if you want, but I would prefer to have a confirmation that this is really a typo first.

Thanks

**Comment by williamcroberts** [comment]
Yeah looks like a typo thanks.

**Comment by yhemery** [comment]
Thanks for the fix
