### ISSUE TITLE
WARNING: lock held when returning to user space!

### ISSUE THREAD

**Issue by dnoliver** [tpm2-software/tpm2-tools#1676]
The following error warning is logged when `tpm2_createprimary` runs.
The command that generate it is `clevis luks unlock -d /dev/mmcblk0p1 -n c1` 

```text
 1656.971592] ================================================
[ 1656.971605] WARNING: lock held when returning to user space!
[ 1656.971619] 5.3.0-0.rc3.git1.1.fc31.x86_64 #1 Tainted: G        W        
[ 1656.971633] ------------------------------------------------
[ 1656.971646] tpm2_createprim/3229 is leaving the kernel with locks still held!
[ 1656.971662] 2 locks held by tpm2_createprim/3229:
[ 1656.971672]  #0: 0000000040f82a51 (&chip->ops_sem){.+.+}, at: tpm_try_get_ops+0x23/0x90
[ 1656.971700]  #1: 000000005e2badf9 (&chip->tpm_mutex){+.+.}, at: tpm_try_get_ops+0x3e/0x90
[ 1666.789624] EXT4-fs (dm-3): mounted filesystem with ordered data mode. Opts: (null)
```

Versions

```text
[root@fedora-iot-2 containers]# rpm -qa tpm2*
tpm2-tss-2.2.3-2.fc31.x86_64
tpm2-tools-3.2.0-3.fc31.x86_64

[root@fedora-iot-2 containers]# rpm -qa clevis*
clevis-luks-11-6.fc31.x86_64
clevis-11-6.fc31.x86_64
clevis-systemd-11-6.fc31.x86_64
clevis-dracut-11-6.fc31.x86_64
```

Is this a `clevis` problem? or a `tpm2_tools` one?

**Comment by tstruk** [comment]
On 8/19/19 3:06 PM, Nicolas Oliver wrote:
> Is this a |clevis| problem? or a |tpm2_tools| one?

It looks like a tpm driver problem.
Can you reproduce it with a stable kernel?
Could you run the same under strace?

Thanks,
-- 
Tadeusz

**Comment by dnoliver** [comment]
@tstruk I have never seen this issue in an stable kernel. I have a Fedora Server 30 with Linux 5.1 where I can test this, is that stable enough?

Also, I am also having this warning with other tools that interact with the TPM on the same host. Maybe the problem is in the kernel/tpm driver itself.

**Comment by tstruk** [comment]
Yes, it looks like it is a 5.3.0-0.rc3 kernel/TPM driver specific. The strace log would help to see what is going on. I would also report it on linux-integrity@vger.kernel.org

**Comment by williamcroberts** [comment]
Yeah this doesn't seem like a tools bug, i'm not actively managing any locks. It's a kernel oops, looks like an issue in the kernel path.

**Comment by dnoliver** [comment]
Thank you @williamcroberts @tstruk, I reported it into the linux-integrity distribution list. Will follow up with them.
