### ISSUE TITLE
ci: travis does not detect warnings/errors in unit tests

### ISSUE THREAD

**Issue by joholl** [tpm2-software/tpm2-tools#1683]
Note: this issue applies to tpm2-software/tpm2-pkcs11 as well as tools. (see tpm2-software/tpm2-pkcs11#281)

As discussed in tpm2-software/tpm2-pkcs11#211, if travis builds the code with `--disable-hardening`, most gcc warnings will be disabled. With tpm2-software/tpm2-pkcs11#279, this issue was fixed for the productive code, but not for the unit tests.

I created a pull request #1682 with a demo: an unused function is introduced and accepted by travis which breaks a standard way of building: `./bootstrap; configure --enable-unit; make check`

**Explanation why the travis misses the error:**

For gcc we execute the following lines:

```bash
    ./configure
    make distcheck
    make distclean
```

As a result, warnings (e.g. `-Werror=unused-function`) in the productive code are detected. The tests however are not built since `--enable-unit` is not passed. This means warnings in the test code remain undetected.

Later, the tests are built with `--disable-hardening`. Hence warnings in the test code still remain undetected:

```bash
../configure --enable-unit --disable-hardening --enable-code-coverage
make -j$(nproc)
make -j check
```

**Comment by joholl** [comment]
@williamcroberts There might be a second issue I stumbled upon:

In tpm2-software/tpm2-pkcs11#279 you changed the compiler check for gcc from
`"$CC" == gcc*` to
`"$CC" != clang*`.
Is this neccessary for tpm2-tools, as well?

**Comment by joholl** [comment]
@williamcroberts Great, #1684 should indeed fix the issue.

Note that pkcs11 is affected too as referenced above.

**Comment by williamcroberts** [comment]
Fixed for tools: https://github.com/tpm2-software/tpm2-tools/pull/1684
