### ISSUE TITLE
A TPM error (256) occurred continue selftest

### ISSUE THREAD

**Issue by GaelGuegan** [tpm2-software/tpm2-tools#1691]
_(I have already send this message in the TPM2 mailing list without answer)_
Hello all, 

I am working with the linux kernel version 4.9 on an embedded target.
And I am having the following error message from the TPM driver at bootup :

> $  dmesg | grep TPM
[    2.946137] tpm_tis_spi spi32766.0: 2.0 TPM (device-id 0x0, rev-id 78)
[    2.975824] tpm tpm0: A TPM error (256) occurred continue selftest

So I have seen that this error 256 correspond to TPM2_RC_INITIALIZE = 0x0100,  and that it is thrown  from this [function](https://github.com/torvalds/linux/blob/v4.9/drivers/char/tpm/tpm-interface.c#L422) (be32_to_cpu() when executing a tpm_transmit_cmd()).

However can someone explain why I am having this error ? Is it possible that it is because I am trying to access to the TPM during its selftest phase (not of what I know)?
**Can I ignore this error without worry ?**

Thank for your help,

Gael GUEGAN

**Comment by williamcroberts** [comment]
Answered on mailing list:
https://lists.01.org/pipermail/tpm2/2019-August/001271.html

**Comment by osresearch** [comment]
Updated link for future searchers trying to figure out why they are getting this error: https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/SEZLLTQ57VE775BJNM4JQIB5EFZ2Z4NU/

**Comment by johnphilby** [comment]
> Answered on mailing list: https://lists.01.org/pipermail/tpm2/2019-August/001271.html
> https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/SEZLLTQ57VE775BJNM4JQIB5EFZ2Z4NU/

Links no longer exists
