### ISSUE TITLE
tpm2_getekcertificate should decode JSON response

### ISSUE THREAD

**Issue by mdempsky** [tpm2-software/tpm2-tools#1695]
tpm2_getekcertificate currently simply writes the HTTP response to disk. This is annoying because (1) the user needs to know the details of the response format (e.g., how to decode JSON and the particular Base 64 encoding variant used -- URL safe alphabet, but "=" is URL encoded as "%3D"), and (2) if the server reports failure (e.g., a "certificate not found error"), then tpm2_getekcertificate still exits with a successful error code.

I think it would be ergonomically better if tpm2_getekcertificate decoded the JSON response, and could write out a DER or PEM encoded certificate; and that it exited with a non-zero status code if the server failed to return a certificate.

**Comment by asac** [comment]
+1 ... I cant even seem to base64 decode the output if i replace %3D with = ... any pointers what format certificate is exactly?

**Comment by mdempsky** [comment]
@asac It's the URL safe variant of Base 64: https://tools.ietf.org/html/rfc4648#section-5

**Comment by highercomve** [comment]
I have a related question here. After I decoded the certificate with the base64 (in URL safe mode), How I can load that certificate to the TPM because my TPM does have any in the typical 0x1c00002 where should be the EK certificate.

And if I try to define that 

```
tpm2_nvdefine -Q 0x1c00002 -C p -a "ownerread|policywrite|ownerwrite|platformcreate|no_da|policyread|authread"
```

I don't have permission to define that. I guess I doing something wrong, but I kinda lost. If somebody can help me with this I will appreciate.

```
WARNING:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:333:Esys_NV_DefineSpace_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:122:Esys_NV_DefineSpace() Esys Finish ErrorCode (0x000009a2) 
ERROR: Failed to define NV area at index 0x1C00002
ERROR: Esys_NV_DefineSpace(0x9A2) - tpm:session(1):authorization failure without DA implications
ERROR: Unable to run tpm2_nvdefine
```

**Comment by mdempsky** [comment]
@highercomve Do you have "platform" authorization for your TPM? Unless you're writing your own BIOS or something, I think you only have "owner" authorization. And if that's the case, you'll have to (1) create it in the owner hierarchy instead of platform hierorachy (i.e., `-C o` instead of `-C p`), and (2) omit the `platformcreate` attribute.

I also think `policywrite` and `policyread` need a policy to be defined (i.e., `-L`), but maybe I'm mistaken.

**Comment by highercomve** [comment]
Yeah, but you can't write in that space using the owner's authorization. I guess i will continue without EK cert hehehe. If you try to write using the `-C o` i get 

```
ERROR: Failed to define NV area at index 0x1C00002
ERROR: Esys_NV_DefineSpace(0x82) - tpm:handle(unk):inconsistent attributes
ERROR: Unable to run tpm2_nvdefine
```

**Comment by highercomve** [comment]
Yeah, but you can't write in that space using the owner's authorization. I guess I will continue without EK cert. If you try to write using the `-C o` i get 

```
ERROR: Failed to define NV area at index 0x1C00002
ERROR: Esys_NV_DefineSpace(0x82) - tpm:handle(unk):inconsistent attributes
ERROR: Unable to run tpm2_nvdefine
```

**Comment by idesai** [comment]
> tpm2_getekcertificate currently simply writes the HTTP response to disk. This is annoying because (1) the user needs to know the details of the response format (e.g., how to decode JSON and the particular Base 64 encoding variant used -- URL safe alphabet, but "=" is URL encoded as "%3D"), and (2) if the server reports failure (e.g., a "certificate not found error"), then tpm2_getekcertificate still exits with a successful error code.
> 
> I think it would be ergonomically better if tpm2_getekcertificate decoded the JSON response, and could write out a DER or PEM encoded certificate; and that it exited with a non-zero status code if the server failed to return a certificate.

There is a [script](https://github.com/tpm2-software/tpm2-tools/blob/master/scripts/utils/icert2pem.sh) included in the tools for this purpose.
