### ISSUE TITLE
Questionable check for TPM_RNG_EPS in tpm2_getekcertificate.c

### ISSUE THREAD

**Issue by mdempsky** [tpm2-software/tpm2-tools#1697]
In tpm2_getekcertificate.c, there's logic to check if an Intel PTT's Endorsement Primary Seed (EPS) was generated by the PTT or by the manufacturer:

https://github.com/tpm2-software/tpm2-tools/blob/5f9c9e9abbb38f3c6f82d091583ec0bb4acb5bd0/tools/tpm2_getekcertificate.c#L350-L366

In particular, it's using an equality comparison for the value of the TPM_PT_PERMANENT property with 0x400. However, TPM_PT_PERMANENT is a bitset property, so I think it should be using a bit-test operation instead (e.g., `xxx.value & TPM_RNG_EPS` or `(xxx.value & TPM_RNG_EPS) != 0`).

For comparison, INTEL-SA-00086-Linux-Recovery-Tools uses a bit-test operation: https://github.com/intel/INTEL-SA-00086-Linux-Recovery-Tools/blob/master/Intel-SA-00086-Recovery-Utility.c#L429

/cc @idesai who added the above code to tpm2_getekcertificate.c in https://github.com/tpm2-software/tpm2-tools/commit/0df61fcb928e6cf762b08e37312d70edd5f539ec

**Comment by idesai** [comment]
oops, thanks @mdempsky, please review https://github.com/tpm2-software/tpm2-tools/pull/1699
