### ISSUE TITLE
Download-deps.sh Update tpm2-abrmd release with fix for issue #652 

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tools#1735]

**Comment by williamcroberts** [comment]
@idesai can you explain this ticket?

**Comment by idesai** [comment]
@williamcroberts, To fix FORTIFY_SOURCE requiring optimization errors. https://github.com/tpm2-software/tpm2-abrmd/pull/653

Have to check if it made to any recent tpm2-abrmd releases.

**Comment by idesai** [comment]
tpm2-abrmd rc with this fix expected next week
