### ISSUE TITLE
4.0: build fails

### ISSUE THREAD

**Issue by kloczek** [tpm2-software/tpm2-tools#1744]
```
[tkloczko@barrel tpm2-tools-4.0]$ make
/bin/sh ./libtool  --tag=CC   --mode=link gcc -I./tools -I./lib -Wall -Wextra -Werror -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -Wstrict-overflow=5 -Wbool-compare -O2 -fPIC -fPIE -D_GNU_SOURCE -Wstringop-overflow=4 -Wstringop-truncation -Wduplicated-branches -Wduplicated-cond -fdata-sections -ffunction-sections       -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -shared -pie -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -flto-partition=none -fuse-linker-plugin -o tools/tpm2_hash tools/tpm2_hash.o tools/tpm2_tool.o lib/libcommon.a -ltss2-esys  -ltss2-mu  -lcrypto  -ltss2-tctildr  -ltss2-rc  
libtool: link: gcc -I./tools -I./lib -Wall -Wextra -Werror -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -Wstrict-overflow=5 -Wbool-compare -O2 -fPIC -fPIE -D_GNU_SOURCE -Wstringop-overflow=4 -Wstringop-truncation -Wduplicated-branches -Wduplicated-cond -fdata-sections -ffunction-sections -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -pie -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,--gc-sections -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -flto-partition=none -fuse-linker-plugin -o tools/tpm2_hash tools/tpm2_hash.o tools/tpm2_tool.o  lib/libcommon.a -ltss2-esys -ltss2-mu -lcrypto -ltss2-tctildr -ltss2-rc
lib/tpm2_hash.c: In function 'tpm2_hash_common.constprop':
lib/tpm2_hash.c:94:18: error: 'left' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   94 |             left -= buffer.size;
      |                  ^
lib/tpm2_hash.c:17:19: note: 'left' was declared here
   17 |     unsigned long left;
      |                   ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error: gcc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
```

**Comment by williamcroberts** [comment]
What compiler and version are you using?

**Comment by williamcroberts** [comment]
Looks like a false positive. It gets initialized in the block below and use is gaurded on the use_left variable. if use_left is true, then left is initialized.
```C
    /*  if we're using infilep, get file size */
    if (!!infilep) {
        /* Suppress error reporting with NULL path */
        use_left = files_get_file_size(infilep, &left, NULL);
    } else {
        /*  if we're using inbuffer, inbuffer_len is valid*/
        left = inbuffer_len;
        use_left = true;
    }
```

**Comment by kloczek** [comment]
Nevertheless compiler reports this as uninitialised `left`.
I think that `left` can be uninitialised if `files_get_file_size(infilep, &left, NULL)` is not putting some value in `left`.
So how to fix this?
Looks like current fedora gcc cannot compile rel 4.0.

**Comment by kloczek** [comment]
What about below patch?
```
--- a/lib/tpm2_hash.c~  2019-09-23 00:35:32.000000000 +0100
+++ b/lib/tpm2_hash.c   2019-09-23 00:37:24.640867806 +0100
@@ -13,8 +13,8 @@
         TPMI_RH_HIERARCHY hierarchy, FILE *infilep, BYTE *inbuffer,
         UINT16 inbuffer_len, TPM2B_DIGEST **result,
         TPMT_TK_HASHCHECK **validation) {
-    bool use_left, done;
-    unsigned long left;
+    bool use_left = true, done;
+    unsigned long left = inbuffer_len;
     size_t bytes_read;
     TPM2B_AUTH null_auth = TPM2B_EMPTY_INIT;
     TPMI_DH_OBJECT sequence_handle;
@@ -24,10 +24,6 @@
     if (!!infilep) {
         /* Suppress error reporting with NULL path */
         use_left = files_get_file_size(infilep, &left, NULL);
-    } else {
-        /*  if we're using inbuffer, inbuffer_len is valid*/
-        left = inbuffer_len;
-        use_left = true;
     }
 
     /* if data length is non-zero (valid) and less than 1024, just do it in one

```

**Comment by williamcroberts** [comment]
> Nevertheless compiler reports this as uninitialised `left`.
> I think that `left` can be uninitialised if `files_get_file_size(infilep, &left, NULL)` is not putting some value in `left`.
> So how to fix this?
> Looks like current fedora gcc cannot compile rel 4.0.

Whats current Fedora? works on fedora-30: https://travis-ci.org/tpm2-software/tpm2-tools/jobs/591717376

**Comment by williamcroberts** [comment]
> files_get_file_size



> Nevertheless compiler reports this as uninitialised `left`.
> I think that `left` can be uninitialised if `files_get_file_size(infilep, &left, NULL)` is not putting some value in `left`.
> So how to fix this?

It would return false causing the function to not use left.

**Comment by kloczek** [comment]
> Whats current Fedora? works on fedora-30: https://travis-ci.org/tpm2-software/tpm2-tools/jobs/591717376

I'm not using Fedora. What I'm using is Fedora rawhide based but with many modifications.
More or less you can assume that this fail happens on rawhide which is way ahead of fc30.

**Comment by williamcroberts** [comment]
Can you submit the patch as a PR?

**Comment by kloczek** [comment]
Will do this in few hours ans I'm a bit busy right now.
Thx.

**Comment by kloczek** [comment]
There are another warnings which it would be good to resolve:
<pre>In function &apos;fread&apos;,
    inlined from &apos;files_load_bytes_from_buffer_or_file_or_stdin&apos; at lib/files.c:617:27,
    inlined from &apos;process_input_name_hash&apos; at tools/tpm2_policynamehash.c:27:19,
    inlined from &apos;on_option&apos; at tools/tpm2_policynamehash.c:49:18:
/usr/include/bits/stdio2.h:295:9: warning: call to &apos;__fread_chk_warn&apos; declared with attribute warning: fread called with bigger size * nmemb than length of destination buffer [-Wattribute-warning]
  295 |  return __fread_chk_warn (__ptr, __bos0 (__ptr), __size, __n, __stream);
      |         ^
In function &apos;fread&apos;,
    inlined from &apos;files_load_bytes_from_buffer_or_file_or_stdin&apos; at lib/files.c:617:27,
    inlined from &apos;process_input_template_hash&apos; at tools/tpm2_policytemplate.c:27:19,
    inlined from &apos;on_option&apos; at tools/tpm2_policytemplate.c:49:18:
/usr/include/bits/stdio2.h:295:9: warning: call to &apos;__fread_chk_warn&apos; declared with attribute warning: fread called with bigger size * nmemb than length of destination buffer [-Wattribute-warning]
  295 |  return __fread_chk_warn (__ptr, __bos0 (__ptr), __size, __n, __stream);
      |         ^
</pre>

**Comment by williamcroberts** [comment]
Fixed in https://github.com/tpm2-software/tpm2-tools/commit/93861ff7f8cf189d15562461628b285d5a64801b
