### ISSUE TITLE
How to generate the statically linked executable

### ISSUE THREAD

**Issue by kaloho** [tpm2-software/tpm2-tools#1755]
# Context
* Hardware:
i686
* Operating system :
Ubuntu 16.04.6 LTS

# Bug Report
* Expected Behavior
Builds the statically linked executables in tpm2-tools/tools

derek@ubuntu:~/workdir/tpm2-tools$ file tools/tpm2_*
tools/tpm2_activatecredential:        ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), **statically linked**, for GNU/Linux 2.6.32, BuildID[sha1]=91a0834f96856f15537fb75b1d6f822e31b07995, not stripped

* Actual Behavior
Can't compile completely

/usr/bin/ld: attempted static link of dynamic object `/usr/lib/i386-linux-gnu/libcurl-gnutls.so'
collect2: error: ld returned 1 exit status
Makefile:2170: recipe for target 'tools/tpm2_getekcertificate' failed
make: *** [tools/tpm2_getekcertificate] Error 1

* Steps to Reproduce
// install tpm2-tss
./configure "CFLAGS=--static" --enable-shared=no
make
sudo make install
// Install tpm2-tools
./configure "CFLAGS=--static" --enable-shared=no --disable-hardening
make

* Possible Solution
./configure --parameter
or
modify Makefile

**Comment by tstruk** [comment]
Not every distribution provides static library for libcurl. Please make sure that you have a libcurl-gnutls.a installed on your system.

**Comment by kaloho** [comment]
Hi @tstruk :
libcurl-gnutls.a already exists

derek@ubuntu:/usr/lib/i386-linux-gnu$ ll libcurl-gnutls.*
-rw-r--r-- 1 root root 828282 Sep 10 21:35 libcurl-gnutls.a
-rw-r--r-- 1 root root   1000 Sep 10 21:35 libcurl-gnutls.la
lrwxrwxrwx 1 root root     23 Sep 10 21:35 libcurl-gnutls.so -> libcurl-gnutls.so.4.4.0
lrwxrwxrwx 1 root root     19 Sep 10 21:35 libcurl-gnutls.so.3 -> libcurl-gnutls.so.4
lrwxrwxrwx 1 root root     23 Sep 10 21:35 libcurl-gnutls.so.4 -> libcurl-gnutls.so.4.4.0
-rw-r--r-- 1 root root 493132 Sep 10 21:35 libcurl-gnutls.so.4.4.0

I noticed that the link file is linked to .so, so i modified it :
derek@ubuntu:/usr/lib/i386-linux-gnu$ sudo ln -s libcurl-gnutls.a libcurl-gnutls.so
derek@ubuntu:/usr/lib/i386-linux-gnu$ ll libcurl-gnutls.*
-rw-r--r-- 1 root root 828282 Sep 10 21:35 libcurl-gnutls.a
-rw-r--r-- 1 root root   1000 Sep 10 21:35 libcurl-gnutls.la
lrwxrwxrwx 1 root root     16 Sep 25 09:41 libcurl-gnutls.so -> libcurl-gnutls.a
lrwxrwxrwx 1 root root     19 Sep 10 21:35 libcurl-gnutls.so.3 -> libcurl-gnutls.so.4
lrwxrwxrwx 1 root root     23 Sep 10 21:35 libcurl-gnutls.so.4 -> libcurl-gnutls.so.4.4.0
-rw-r--r-- 1 root root 493132 Sep 10 21:35 libcurl-gnutls.so.4.4.0

then make, but there are new errors :
derek@ubuntu:~/workdir/tpm2-tools$ make 
  CCLD     tools/tpm2_getekcertificate
/usr/local/lib/libtss2-esys.a(src_tss2_esys_libtss2_esys_la-tctildr-dl.o): In function `handle_from_name':
/home/derek/workdir/tpm2-tss/src/tss2-tcti/tctildr-dl.c:84: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-netrc.o): In function `Curl_parsenetrc':
(.text+0x449): warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-curl_addrinfo.o): In function `Curl_getaddrinfo_ex':
(.text+0x96): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-url.o): In function `Curl_disconnect':
(.text+0x424a): undefined reference to `idn_free'
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-url.o): In function `Curl_disconnect':
(.text+0x426a): undefined reference to `idn_free'
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-url.o): In function `Curl_connect':
(.text+0x729f): undefined reference to `idn_free'
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-url.o): In function `Curl_connect':
(.text+0x73df): undefined reference to `idn_free'

/* The message is very long, so I omitted it */

/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-curl_ntlm_core.o): In function `setup_des_key':
(.text+0xb6): undefined reference to `nettle_des_set_key'
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-curl_ntlm_core.o): In function `Curl_ntlm_core_lm_resp':
(.text+0x12f): undefined reference to `nettle_des_encrypt'
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-curl_ntlm_core.o): In function `Curl_ntlm_core_lm_resp':
(.text+0x14d): undefined reference to `nettle_des_encrypt'
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-curl_ntlm_core.o): In function `Curl_ntlm_core_lm_resp':
(.text+0x168): undefined reference to `nettle_des_encrypt'
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-curl_ntlm_core.o): In function `Curl_ntlm_core_mk_lm_hash':
(.text+0x237): undefined reference to `nettle_des_encrypt'
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-curl_ntlm_core.o): In function `Curl_ntlm_core_mk_lm_hash':
(.text+0x256): undefined reference to `nettle_des_encrypt'
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-curl_ntlm_core.o): In function `Curl_ntlm_core_mk_nt_hash':
(.text+0x395): undefined reference to `nettle_md4_init'
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-curl_ntlm_core.o): In function `Curl_ntlm_core_mk_nt_hash':
(.text+0x3a3): undefined reference to `nettle_md4_update'
/usr/lib/i386-linux-gnu/libcurl-gnutls.so(libcurl_gnutls_la-curl_ntlm_core.o): In function `Curl_ntlm_core_mk_nt_hash':
(.text+0x3af): undefined reference to `nettle_md4_digest'
collect2: error: ld returned 1 exit status
Makefile:2170: recipe for target 'tools/tpm2_getekcertificate' failed
make: *** [tools/tpm2_getekcertificate] Error 1

**Comment by kaloho** [comment]
I have solved this issues, thank you for your reply.


tools/tpm2_activatecredential:        ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=6bbfbccb10004f3f91d872717d4f6efc521c75de, not stripped
tools/tpm2_certify:                   ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=69e01ed3136342198750328ddf32e324d733fa9e, not stripped
tools/tpm2_changeauth:                ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=781e1421448749e7ca05acefe88377d6d364cc0b, not stripped
tools/tpm2_clear:                     ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=283c745980b12b3e3c7b4ccc2405d3998e5099f6, not stripped
tools/tpm2_clearcontrol:              ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=b7b0171d23909a1df8c6348213a4386d5babe299, not stripped
tools/tpm2_create:                    ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=a94ec67c66887b9508aa1773b083165021114eeb, not stripped
tools/tpm2_createak:                  ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=42346ed53a452244f2f69585ced59145a47b0d6e, not stripped
tools/tpm2_createek:                  ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=1d202342f93e817362d040f951db1e0ac97a75da, not stripped
tools/tpm2_createpolicy:              ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=87118da08fd384c03f366f994b0c37633f0af621, not stripped
tools/tpm2_createprimary:             ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=e9e6dd1c3faa2dd149b4646387c5fbef4c021011, not stripped
tools/tpm2_dictionarylockout:         ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=3bcef8aa1fe126e40934674281944d15bf9d0c8a, not stripped
tools/tpm2_duplicate:                 ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=8123ae65493d013f5b7d4a891b281a2b9df0b4de, not stripped
tools/tpm2_encryptdecrypt:            ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=9e921dd19a4f22bf76287b134ce70947d15e9b9a, not stripped
tools/tpm2_evictcontrol:              ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=6aee2a968807b78ced8ce5e91a08ec6a6dfc0308, not stripped
tools/tpm2_flushcontext:              ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=3df19571940e4b5760f8362a33258017d290dcbb, not stripped
tools/tpm2_getcap:                    ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=0d65743942604dc86a0385b740535620c37f28b7, not stripped
tools/tpm2_getekcertificate:          ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=deb8e3202dd766630261938391bba12d6b9cca48, not stripped
tools/tpm2_getrandom:                 ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=eb3fbe440eb33a584748540a00c5e2c86a9173e2, not stripped
tools/tpm2_gettestresult:             ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=fa2b1cf2cdaa8132a9611878cb3dfcf3b076de25, not stripped
tools/tpm2_hash:                      ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=eccc4bb88bcd559029587401db9493c94849e4f2, not stripped
tools/tpm2_hierarchycontrol:          ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=1e4d2e8cad60107c6cd74c77b7dfb148c37f1389, not stripped
tools/tpm2_hmac:                      ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=e793041b7c3cd7e3abd263c660edfae60294743e, not stripped
tools/tpm2_import:                    ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=5d8283fa08ac7a5a5e64598d24d80f1edc1d9d2d, not stripped
tools/tpm2_incrementalselftest:       ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=37be289726ca2fe1dc8caa926337963282597399, not stripped
tools/tpm2_load:                      ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=596425f88111aa780affc09d3864b5cd2e69fe86, not stripped
tools/tpm2_loadexternal:              ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=42505199929da8acd9a1466c41263b63d88879e9, not stripped
tools/tpm2_makecredential:            ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=48c9de727be2b7a94baea8fe87349b6de7636220, not stripped
tools/tpm2_nvdefine:                  ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=15e4e5270dfc3f0ab32d7d738505f7396e3b31b8, not stripped
tools/tpm2_nvincrement:               ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=67c90c13f1901265c8f54e6fba679f31bb8d97f4, not stripped
tools/tpm2_nvread:                    ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=dae36e7fea3ea45a2374adeead8d9afeaf3dd17a, not stripped
tools/tpm2_nvreadlock:                ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=2d32cf38ed3c56304665436919c85bbeaf5e0b7d, not stripped
tools/tpm2_nvreadpublic:              ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=a264a91fd99cda839c7ef01a0187638e793b824c, not stripped
tools/tpm2_nvundefine:                ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=5f0d6f1809e8e18b03a6ea07647a61adf410eafc, not stripped
tools/tpm2_nvwrite:                   ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=617c3773549e3c5eda3cbf1a93e186c86d3b652e, not stripped
tools/tpm2_pcrallocate:               ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=5fa6cf83ded8ee5ab2a3c5ce290ba92f4c629c9c, not stripped
tools/tpm2_pcrevent:                  ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=7676cf4ebef38cae8c43138c9ce3451cbe712b78, not stripped
tools/tpm2_pcrextend:                 ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=86327e9cc468f75cc7bc695d29fe068b8b3fbc96, not stripped
tools/tpm2_pcrread:                   ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=9e731af29af61bd878ddebabd8deb30d9a3e3cd6, not stripped
tools/tpm2_pcrreset:                  ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=808a6f2143b73bcdf63a26133c86aa5449a74679, not stripped
tools/tpm2_policyauthorize:           ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=8d2fe297f7138cd1de8fa546576abd43f47e028c, not stripped
tools/tpm2_policyauthorizenv:         ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=67e67b85ce8523b9b375dd84f0c0fb772abbca49, not stripped
tools/tpm2_policycommandcode:         ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=8f7dac8a666b26a04092cbf59216e293b3021b60, not stripped
tools/tpm2_policyduplicationselect:   ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=8ad3b71e28ac896372b147cbb37d5155c08d9ce2, not stripped
tools/tpm2_policylocality:            ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=b665d62293cdb1c11e0c4a65a6d662e15264500e, not stripped
tools/tpm2_policyor:                  ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=d18f2373f5be89e96b91f0cb7fc7e7ca0630c5fc, not stripped
tools/tpm2_policypassword:            ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=1025d129fa01679f465ae5ed4c3a6881f2e63203, not stripped
tools/tpm2_policypcr:                 ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=37d0ae568a52223b0c283d0dd84848d7a5fdd1be, not stripped
tools/tpm2_policyrestart:             ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=c27f7913c70ee4d16596d2ffeecb81c362f082ad, not stripped
tools/tpm2_policysecret:              ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=ebd026445f4f407d8174be413428db0b84e0150f, not stripped
tools/tpm2_quote:                     ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=8dad239c50a612c904cdea1bec756ca950f2318a, not stripped
tools/tpm2_readclock:                 ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=a215e9ab5d0302c7c2f6776e887bcc016fadbd28, not stripped
tools/tpm2_readpublic:                ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=55ba0d0066686761155cf3fa1ab9a2d845109839, not stripped
tools/tpm2_rsadecrypt:                ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=aac44a087f12d83f1506ae8fa6ea7d8642248f18, not stripped
tools/tpm2_rsaencrypt:                ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=a218a6e5137670b74ea66b1ac545828a5715bc82, not stripped
tools/tpm2_selftest:                  ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=67c694da85fb9dcf55c01a3d2185c1a454574085, not stripped
tools/tpm2_send:                      ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=48340713dde3fd9afdc6306ce20dc9271f79d1f8, not stripped
tools/tpm2_shutdown:                  ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=542fd2167671bfa314a952733333205fc7de1118, not stripped
tools/tpm2_sign:                      ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=6190c83fa88a5d8bbdd5162a45456b30b440cf55, not stripped
tools/tpm2_startauthsession:          ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=5ca13e88b0543c79a51fc82c601cc9831a1efb6d, not stripped
tools/tpm2_startup:                   ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=0bf25fd52add65b29414ff25b10dd4931f556dfb, not stripped
tools/tpm2_stirrandom:                ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=43eb248a9e4fcb7d03a7ec7e529bf37547ee9022, not stripped
tools/tpm2_testparms:                 ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=c1a616dea8057d0fc76064bf479e5ea0ee4c6b7c, not stripped
tools/tpm2_unseal:                    ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=aba9052d6bfdd7d3822b2136d00f22ac00464c55, not stripped
tools/tpm2_verifysignature:           ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=47ce07888877af7bfc72bfb5e6c12642569abf1f, not stripped
