### ISSUE TITLE
RC cleanup

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tools#1756]
I was just scrolling through the releases page for the tools and ended up having to do a lot of scrolling. The release notes for 4.0 were pretty long, and having a few release candidates left around meant scrolling past the same long release notes 3 times. Any chance I can get you to remove the stale RCs to shrink down the releases page a bit?

**Comment by idesai** [comment]
@flihp The idea was to keep them around as an archive of every release. We can certainly look at trimming down the release notes by referring to the CHANGELOG for a detailed list of changes. I will take this up with @williamcroberts. Thanks.

**Comment by williamcroberts** [comment]
Yeah I noticed that right now. We can just snip the notes and make it a link to the changelog.

**Comment by williamcroberts** [comment]
Done
