### ISSUE TITLE
3.2.1 release status

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tools#1758]
@williamcroberts did an RC for 3.2.1 back in august: https://github.com/tpm2-software/tpm2-tools/releases/tag/3.2.1-rc0 but it doesn't look like 3.2.1 was ever released. Did this get lost in the 4.0 work?

**Comment by idesai** [comment]
@flihp I believe this got overlooked during the 4.0 release. Also, this looks like a bug fix release. Please let me know if this is blocking. If not I will cut a release next week. Thanks for pointing it out.

**Comment by williamcroberts** [comment]
rc1 done.. will roll release next week.

**Comment by williamcroberts** [comment]
Released: https://github.com/tpm2-software/tpm2-tools/releases/tag/3.2.1
