### ISSUE TITLE
Major delay in initramfs with luksOpen after upgrading to TPM 2 Tools 4.0

### ISSUE THREAD

**Issue by glassman81** [tpm2-software/tpm2-tools#1760]
Hello there. Currently, I have my root ext4 partition encrypted. I load a key directly into the TPM's nv storage and then unseal it at boot to automatically unlock my encrypted root ext4 partition. I do this with a `keyscript` option I have defined inside `crypttab`.  This was working fine with TPM Tools 2 v3.2.1, but after upgrading to v4.0, there is a major delay at boot with the same script file when attempting to unlock the drive. The below mentions how this is currently working.

As noted above, the root is already encrypted as a luks2 volume using a passphrase. Since I want to unlock this volume automatically at boot with my TPM, I made another key using `dd if=/dev/random of=secret.bin bs=1 count=32` and then bound that to the luks volume using `cryptsetup luksAddKey /dev/mmcblk0p2 secret.bin`.

I then took that key and put it into the TPM with a few commands. With TPM Tools 2 v3.2.1, the syntax obviously looks different, but with TPM Tools 2 v4.0 and TSS 2 version v2.4, this is what I used:

`tpm2_pcrread sha256:0,2,3,7 -o pcrs.bin`
`tpm2_createpolicy --policy-pcr -l sha256:0,2,3,7 -f pcrs.bin -L policy.digest`
`tpm2_createprimary -C e -g sha256 -G rsa -c primary.context`
`tpm2_create -g sha256 -u obj.pub -r obj.priv -C primary.context -L policy.digest -a "noda|adminwithpolicy|fixedparent|fixedtpm" -i secret.bin`
`tpm2_load -C primary.context -u obj.pub -r obj.priv -c load.context`
`tpm2_evictcontrol -C o -c load.context 0x81010002`

I next edited the crypttab file, appending the keyscript and initramfs options at the end:

`sdcard UUID=443d9351-4e0d-4fc8-b743-b9215b379939 none luks,keyscript=/usr/bin/passphrase-from-tpm,initramfs`

The keyscript referenced from crypttab file above contains the following information:

`#!/bin/sh`
`set -e`
`echo "Unlocking via TPM" >&2`
`export TPM2TOOLS_TCTI="device:/dev/tpm0"`
`/usr/bin/tpm2_unseal -c 0x81010002 -p pcr:sha256:0,2,3,7 && exit`
`/usr/lib/cryptsetup/askpass "TPM unlock failed. Enter passphrase for $CRYPTTAB_SOURCE ($CRYPTTAB_NAME): "`

Next, I created the hook script inside the `/etc/initramfs-tools/hooks` directory. That file contains the following data:

`#!/bin/sh`
`case $1 in`
`prereqs) exit 0;;`
`esac`
`. /usr/share/initramfs-tools/hook-functions`
`copy_exec /usr/bin/tpm2_unseal`
`copy_exec /usr/lib/arm-linux-gnueabihf/libtss2-tcti-device.so`
`copy_exec /usr/lib/arm-linux-gnueabihf/libatspi.so.0`
`copy_file script /usr/bin/passphrase-from-tpm`
`copy_modules_dir kernel/drivers/char/tpm`
`copy_modules_dir kernel/drivers/spi`

Finally, I regenerated the initramfs by running sudo mkinitramfs -o /boot/initramfs.gz. After a reboot, this still works, but it takes a lot longer now. Using TPM tools 2 v3.2.1 it was almost instantaneous. Now, with TPM Tools 2 v4 I'm waiting a few minutes while staring at the `Unlocking via TPM` message before anything happens, and I'm not sure why.

**Comment by diabonas** [comment]
tpm2-tools 4 uses the Enhanced System API (ESAPI) to communicate with the TPM, which needs some entropy to secure the communication channel. Entropy can be scarce during early boot, so it can take some time until enough randomness is collected. On x86 platforms the CPU often includes hardware instructions to generate random numbers (RDRAND), so adding [`random.trust_cpu=on`](https://wiki.debian.org/BoottimeEntropyStarvation) usually helps. I don't think these instructions are available on a Raspberry Pi, but the Raspi seems to feature a builtin hardware RNG device, so using something like [`rng_core.default_quality=700`](https://lkml.org/lkml/2018/11/2/193) might work.

**Comment by glassman81** [comment]
@diabonas You're a beautiful man. That worked!

Seriously though, you're helping a lot of people like me in the future that don't know exactly where to look to find answers to these problems.

**Comment by idesai** [comment]
@glassman81 I agree. Thanks, @diabonas.

**Comment by diabonas** [comment]
No worries, always happy to help :smiley: I had to deal with most of that stuff for [tpm2-totp](https://github.com/tpm2-software/tpm2-totp) anyway ;)
