### ISSUE TITLE
Try Decrypt using EK and AIK

### ISSUE THREAD

**Issue by roberto497** [tpm2-software/tpm2-tools#1765]
I'm trying to encrypt a file using **openssl** and decrypt using AIK and EK keys, but it's not working:

**Create EK**
tpm2_createek -Q -c 0x81010009 -G rsa -u ek_pub.pem -f pem
tpm2_readpublic -Q -c 0x81010009 -o ek.pub

**Create AK**
tpm2_createak -Q -C 0x81010009 -c ak.ctx -G rsa -g sha256 -s rsassa -u ak_pub.pem -f pem -n ak_pub.name
tpm2_readpublic -Q -c ak.ctx -o ak.pub

**Trying using EK**
echo 12345678 > test.txt
openssl rsautl -in test.txt -out dados.enc -pubin -inkey ek_pub.pem -encrypt

tpm2_rsadecrypt -c 0x81010009  -o decrypt.txt dados.enc
**WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:301:Esys_RSA_Decrypt_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x0000012f)
ERROR: Esys_RSA_Decrypt(0x12F) - tpm:error(2.0): authValue or authPolicy is not available for selected entity
ERROR: Unable to run tpm2_rsadecrypt**

**If I try using AK:**
openssl rsautl -in test.txt -out testeak.enc -pubin -inkey ak_pub.pem -encrypt

tpm2_rsadecrypt -c ak.ctx  -o decrypt.txt testeak.enc
**WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:301:Esys_RSA_Decrypt_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x00000182)
ERROR: Esys_RSA_Decrypt(0x182) - tpm:handle(1):inconsistent attributes
ERROR: Unable to run tpm2_rsadecrypt**

**Is it possible to decrypt using these keys?**

**Comment by williamcroberts** [comment]
> I'm trying to encrypt a file using **openssl** and decrypt using AIK and EK keys, but it's not working:
> 
> **Create EK**
> tpm2_createek -Q -c 0x81010009 -G rsa -u ek_pub.pem -f pem
> tpm2_readpublic -Q -c 0x81010009 -o ek.pub
> 
> **Create AK**
> tpm2_createak -Q -C 0x81010009 -c ak.ctx -G rsa -g sha256 -s rsassa -u ak_pub.pem -f pem -n ak_pub.name
> tpm2_readpublic -Q -c ak.ctx -o ak.pub
> 
> **Trying using EK**
> echo 12345678 > test.txt
> openssl rsautl -in test.txt -out dados.enc -pubin -inkey ek_pub.pem -encrypt
> 
> tpm2_rsadecrypt -c 0x81010009 -o decrypt.txt dados.enc
> **WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:301:Esys_RSA_Decrypt_Finish() Received TPM Error ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x0000012f) ERROR: Esys_RSA_Decrypt(0x12F) - tpm:error(2.0): authValue or authPolicy is not available for selected entity ERROR: Unable to run tpm2_rsadecrypt**

Weird, that error code doesn't allign with what I think it would be. I would expects inconsistent attributes or something.

> 
> **If I try using AK:**
> openssl rsautl -in test.txt -out testeak.enc -pubin -inkey ak_pub.pem -encrypt
> 
> tpm2_rsadecrypt -c ak.ctx -o decrypt.txt testeak.enc
> **WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:301:Esys_RSA_Decrypt_Finish() Received TPM Error ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x00000182) ERROR: Esys_RSA_Decrypt(0x182) - tpm:handle(1):inconsistent attributes ERROR: Unable to run tpm2_rsadecrypt**
> 
> **Is it possible to decrypt using these keys?**

Try tpm2_rsaencrypt. In true crypto speak, RSA encryption is the "math" with the private key and tpm2_rsadecrypt is the "math" with the public key.

Their is also the possibility that the attributes don't support decrypt. Check what is set on readpublic

**Comment by williamcroberts** [comment]
Also ask on the mailing list as documented in the README. The bug tracker is for bugs, not questions.

**Comment by brpatel12** [comment]
@roberto497 did you resolve this issue?

**Comment by idesai** [comment]
Take a look at the faq and the way an aik is created in the tutorial https://tpm2-software.github.io/2020/06/12/Remote-Attestation-With-tpm2-tools.html#FAQ

**Comment by dylangerdaly** [comment]
I've been trying to do the same because people can verify my EK is a real TPM2 Key, I'd like the ability to provide my EK Cert to someone, they encrypt an [age](https://github.com/FiloSottile/age) symmetric key with the EK, send me the encrypted age key along with the age encrypted data.

This allows the person encrypting to confirm I can only view the age key on my specific laptop (EK), however I'm getting the exact same error @roberto497 is getting, there appears to be no one else attempting to do this.

It's possible to trick makecredential commands into encrypting and decrypting files with the EK

**Comment by tomoveu** [comment]
Hi @dylangerdaly @roberto497,

The EK can not be used for decryption.

The TCG guidelines for AK is to not have the TPMA_OBJECT_decrypt flag set that is required for TPM2_RsaDecrypt. I assume the tpm2-tools generate AK without that flag set. Thus, the error "inconsistent attributes" for AK. However, AK could be a combined key, for both decryption and signing.

Today we have a [TPM.dev weekly call](https://developers.tpm.dev/events/tpmdev-online-call) and we could discuss further.

**Comment by iolivergithub** [comment]
Quick example with v4.0-116 of the tools, running on RPi with the Infineon evaluation board

First crete the EK and AK and store in handles 0x81010010 and 11 respectively

$ tpm2_createek -c 0x81010010 -G rsa -u ek.pub
$ tpm2_createak -C 0x81010010 -c ak.ctx -G rsa -g sha256 -s rsassa -u ak.pub -f pem -n ak.name
loaded-key:
  name: 000bfff57a3d3af3ec87c72ee7f95ec8a19a0c35b9884e6f5ad267c8d2932731ec42

The properties of these keys are as follows (output snipped)

$ tpm2_readpublic -c 0x81010010
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|adminwithpolicy|restricted|decrypt
  raw: 0x300b2
$ tpm2_readpublic -c 0x81010011
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|sign
  raw: 0x50072

So, the EK has decrypt capabilities and the AK signing capabilities

However...

$ echo "myBigSecret" > secretdata
$ cat secretdata
myBigSecret
$ tpm2_rsaencrypt -c 0x81010010 -o secretdata.enc secretdata
$ ls -l secretdata*
-rw-r--r-- 1 pi pi  12 Nov 25 10:34 secretdata
-rw-r--r-- 1 pi pi 256 Nov 25 10:34 secretdata.enc
$ tpm2_rsaencrypt -c 0x81010011 -o secretdata_ak.enc secretdata
WARNING:esys:src/tss2-esys/api/Esys_RSA_Encrypt.c:302:Esys_RSA_Encrypt_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_RSA_Encrypt.c:103:Esys_RSA_Encrypt() Esys Finish ErrorCode (0x00000182) 
ERROR: Esys_RSA_Encrypt(0x182) - tpm:handle(1):inconsistent attributes
ERROR: Unable to run tpm2_rsaencrypt
$ tpm2_rsadecrypt -c 0x81010010 -o secretdata_unencrypted secretdata.enc
WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:301:Esys_RSA_Decrypt_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x0000012f) 
ERROR: Esys_RSA_Decrypt(0x12F) - tpm:error(2.0): authValue or authPolicy is not available for selected entity
ERROR: Unable to run tpm2_rsadecrypt

So, we can encrypt with the EK (in handle 0x81010010),  we can't encrypt with the AK (in handle 0x81010011) - this is expected.  Decryption with the EK fails (the last statement) which confirms the above observations.

**Comment by tomoveu** [comment]
@iolivergithub what about this gist we discussed few weeks back on tpmdev?

https://gist.github.com/iolivergithub/035810deeadb4fcf42b4cddeefb2a59f

**Comment by osresearch** [comment]
I've been trying to do a similar operation to remotely seal data based on the EK and ran into all of the same errors, even when using a policy session with the correct `policysecret` value listed in the EK to match the authorization policy:
```
$ tpm2 createek -c ek.ctx -G rsa -f pem -u ek.pem
$ tpm2 readpublic -c ek.ctx
name: 000b39c5b73a70372029061367991fb17e3b92da5056a36b32195be534727bfbaa8f
qualified name: 000b6fa6dc5ef3251cf71194072154f1d9db790339ef599f8097558daffb74f96b08
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|adminwithpolicy|restricted|decrypt
  raw: 0x300b2
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: df83aac1000136...
authorization policy: 837197674484b3f81a90cc8d46a5d724fd52d76e06520b64f2a1da1b331469aa
$ tpm2 startauthsession --session session.ctx --policy-session
$ tpm2 policysecret --session session.ctx --object-context e
837197674484b3f81a90cc8d46a5d724fd52d76e06520b64f2a1da1b331469aa
$ 
$ echo hello | openssl rsautl -inkey ek.pem -pubin -encrypt > hello.bin
$ tpm2 rsadecrypt -c ek.ctx -p session:session.ctx  hello.bin 
WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:305:Esys_RSA_Decrypt_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x00000182) 
ERROR: Esys_RSA_Decrypt(0x182) - tpm:handle(1):inconsistent attributes
ERROR: Unable to run rsadecrypt
```

Daniel P Smith pointed me to [Section 25.1.4 of the TCG TPM2 spec](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part1_Architecture_pub.pdf) that defines the additional HMAC integrity checks that are required for TPM objects with the `restricted` attribute set:

> A key that has both decrypt and restricted attributes SET only accepts data that has a specific structure. The encrypted data block must have as its first element an integrity value for the remainder of the structure. This integrity value is an HMAC of the encrypted data. This format allows the TPM to prevent misuse of the restricted decryption keys that are the basis of the protected storage hierarchy.
> If the sensitive data is part of a child object, the symmetric and HMAC keys are derived from the symmetric seed value (seedValue) in the sensitive area of the Storage Parent. If the sensitive data is a duplication or certification blob, the symmetric and HMAC keys are derived from a single use seed. That seed is then protected using the asymmetric public key of the intended recipient of the protected blob.

So a possible work-around would be to create a TPM duplicate object of a sealed data on the remote machine, which would have the HMAC integrity wrapper, and then import it on the local machine, and then unseal it to get the data.  I don't think the tools have a way to do this, so it might be necessary to add patches like #2386 to create the proper datastructures.

**Comment by tomoveu** [comment]
@osresearch Have you tried debugging on @kgold2 TPM simulator?

- Because this way you could see exactly where the error comes from.
- i.e exactly which TPM command field gets a mismatch and generates the error. 

If you think you have identified the issue and would give wolfTPM a try, I think we could add this extra HMAC integrity check (cc @dgarske). 

Out of curiosity, what is the use case or payload that is going to be decrypted?

By the way, today at 7pm CEST / 10am Pacific Time we have our [TPM.dev weekly call](https://developers.tpm.dev/events/tpmdev-online-call), and we could bring up the issue to get more opinions.

**Comment by williamcroberts** [comment]
You can't RSA Decrypt with a restricted key. See section 25 of https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf.

The private key operations on a restricted key are limited to sign of only TPM computed digests.

**Comment by tomoveu** [comment]
@williamcroberts is there a matrix of key-type vs key properties (allowed operations)?

Because this detail changes things and I wish there was a summary table of what a developer could do with the different types of TPM keys. Based on what attributes they have, etc.

@nicowilliams I think we should add this information to the TPM intro tutorial

**Comment by williamcroberts** [comment]
> @williamcroberts is there a matrix of key-type vs key properties (allowed operations)?
> 
> Because this detail changes things and I wish there was a summary table of what a developer could do with the different types of TPM keys. Based on what attributes they have, etc.

If you scroll down in that link I shared to the Architecture spec, Table 24 has that matrix.

**Comment by nicowilliams** [comment]
@tomoveu I cover this in my tutorial, except I don't state that the EK is restricted (hmm, should fix that).

**Comment by williamcroberts** [comment]
@osresearch i'll usually add break points and fire the simulator up in gdb. But adding some informational trace would be nice. I wonder if/how we could get patches upstream. That simulator is just a copy paste from the MS Simulator  + edits for Linux and a few other things that Ken. I wonder if the StefanBerger one would be easier to get these changes in. I have the same issue, lots of sifting through code to find out exactly why its failing.

**Comment by williamcroberts** [comment]
> Ping @kgold2. Any chance you might move your IBM SourceForge codebases to GitHub?

It's here, but its some sort of quasi mirror state/use:
  - https://github.com/kgoldman/ibmswtpm2

**Comment by nicowilliams** [comment]
Maybe that's good enough for submitting PRs though?

**Comment by tomoveu** [comment]
@kgold2 is very welcoming of contributions

TCG documentation or code improvements, I have seen an open communication and positive reaction.

@nicowilliams +1 , IMO whoever has something ready shoudl just send PR to Ken's GitHub repo of ibmswtpm2

**Comment by williamcroberts** [comment]
> Maybe that's good enough for submitting PRs though?

Yeah he pulls from there. I wish their was one repository over the SourceForge and GitHub. But that's because I am not a huge fan of SourceForge.

**Comment by kgold2** [comment]
On 5/20/2021 11:25 AM, Trammell Hudson wrote:
> I've been using the IBM swtpm for debugging and been frustrated by its lack of informational debugging. When I was adding code to build duplicate structures I ended up adding lots of |printfs| into the swtpm code to track where it was deciding that my HMAC's were bad.

I'm the maintainer.

I hesitated to add debug statement since the code was based on the spec code, and
I didn't want to fork.  Now that the spec is quite stable, I'm starting to add tracing.
Let me know what you need.

However, unless you're writing a TSS, you should not have to debug into the HMAC.
The TSS should do all that you you.
