### ISSUE TITLE
tpm2 tools command responses No standard TCTI could be loaded

### ISSUE THREAD

**Issue by kaloho** [tpm2-software/tpm2-tools#1770]
Hi all :

After statically compile tpm2 tools, then run the command on machine,
Why are all command responses as follows?

**ERROR:tcti:src/tss2-tcti/tctildr-dl.c:248:tctildr_get_default() No standard TCTI could be loaded
ERROR:tcti:src/tss2-tcti/tctildr.c:419:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI
ERROR: Could not load tcti, got: "(null)"**

I have tried copy the tpm2 tss lib to the machine, but the error is the same.
ONIE:/ # ls tss_install/lib/
libtss2-esys.a          libtss2-sys.a           libtss2-tctildr.a
libtss2-esys.la         libtss2-sys.la          libtss2-tctildr.la
libtss2-mu.a            libtss2-tcti-device.a   pkgconfig
libtss2-mu.la           libtss2-tcti-device.la  udev
libtss2-rc.a            libtss2-tcti-mssim.a
libtss2-rc.la           libtss2-tcti-mssim.la
ONIE:/ # echo $PATH
/sbin:/usr/sbin:/bin:/usr/bin:/tss_install/lib

Thanks for you reply.
regards

**Comment by idesai** [comment]
@kaloho please see [here](https://github.com/tpm2-software/tpm2-tools/blob/master/INSTALL.md) for detailed instructions.
Please use the [mailing-list](https://lists.01.org/mailman/listinfo/tpm2) questions for general questions. Thanks

**Comment by williamcroberts** [comment]
you can't dynamically load a static library. The tools and everything uses dlopen to load them. So dlopen() isn't finding anything. We would have to add support to actually statically link the TCTI's to and support this.

**Comment by kaloho** [comment]
@idesai I have referenced [INSTALL.md](https://github.com/tpm2-software/tpm2-tools/blob/master/INSTALL.md) and [Getting-Started](https://github.com/tpm2-software/tpm2-tools/wiki/Getting-Started), but I can't successfully execute the tpm2-tool like this issues.

@williamcroberts  I can't get your mean about "add support to actually statically link the TCTI's to and support this", how can I implement it ?

Thanks for your reply,

**Comment by williamcroberts** [comment]
> @idesai I have referenced [INSTALL.md](https://github.com/tpm2-software/tpm2-tools/blob/master/INSTALL.md) and [Getting-Started](https://github.com/tpm2-software/tpm2-tools/wiki/Getting-Started), but I can't successfully execute the tpm2-tool like this issues.
> 
> @williamcroberts I can't get your mean about "add support to actually statically link the TCTI's to and support this", how can I implement it ?
> 
> Thanks for your reply,

You would have to make a config option that removes the dlopen() logic and then calls the tcti symbols directly.

**Comment by alexsmartens** [comment]
@kaloho, I'm having a similar issue. Did you finally make it work?

**Comment by markarnott** [comment]
I found this issue while troubleshooting an error message.  
I was setting up tpm tools on ubuntu 20.04 with tpm2-abrmd connecting to the ibmswtpm2 simulator.

My fix was to run ldconfig.  
Here is what the error looked like:

```
ma@ubuntu2004:~$ export TPM2TOOLS_TCTI="tabrmd:bus_name=com.intel.tss2.Tabrmd"
ma@ubuntu2004:~$ tpm2_pcrread
ERROR:tcti:src/tss2-tcti/tctildr.c:418:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
ERROR: Could not load tcti, got: "tabrmd:bus_name=com.intel.tss2.Tabrmd"

ma@ubuntu2004:~$ sudo ldconfig
ma@ubuntu2004:~$ tpm2_pcrread
sha1:
  0 : 0x0000000000000000000000000000000000000000
  1 : 0x0000000000000000000000000000000000000000

```

don't forget to ldconfig.
