### ISSUE TITLE
Document procedure to transfer imported RSA key

### ISSUE THREAD

**Issue by salrashid123** [tpm2-software/tpm2-tools#1773]
This is more of a question/how-to a the [mailing list](https://lists.01.org/mailman/listinfo/tpm2) for this group 404s.

I'm trying to find a way to securely transfer an RSA key from one TPM to another but unsure of the specific procedure.

I did see [tpm2_duplicate](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_duplicate.1.md) and [tpm2_import](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_import.1.md) but havn't figured out the specific procedure to document.

Basically I have two two TPMs  A, B:

On A:
I'd like to import an externally generated RSA keypair  (eg using `openssl` directly not using `engine`).

I'd then like to securely transfer this RSA key over to B.

On B:
I'd import the RSA key such that i an only use it for `tpm2_sign` or `tpm2_rsadecrypt`

---

I *think* i need do something like this:

- On B
create a parent that A will later use to wrap key:
```
tpm2_createprimary -C o -g sha256 -G rsa -c primary.ctx
tpm2_create -G rsa -u new_parent.pub -r new_parent.priv -C primary.ctx 
```

- On A
generate keypair
```
openssl genrsa -out private.pem 2048
openssl rsa -in private.pem -outform PEM -pubout -out public.pem
```

Create primary object and import keypair

```
tpm2_createprimary -C o -g sha256 -G rsa -c primary.ctx

 tpm2_import -C primary.ctx -G rsa -i private.pem -u key.pub -r key.priv  
 tpm2_load -C primary.ctx -u key.pub -r key.priv -c key.ctx 
```

Now load the B's `new_parent.pub`:

```
tpm2_loadexternal -C o -u new_parent.pub -c new_parent.ctx
```

Try to duplicate

```
tpm2_duplicate -C new_parent.ctx -c key.ctx -G null -r duprv.bin -s seed.dat
```

At this point, i see various erros about `the type of the value is not appropriate for the use`
or if i use
```
tpm2_startauthsession \--policy-session -S session.dat
tpm2_policycommandcode -S session.dat -L policy.dat TPM2_CC_Duplicate
```
i'd see  `tpm:session(1):a policy check failed`

if it did work, i suppose on B i'd [Import a duplicated key](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_import.1.md#import-a-duplicated-key)

```
tpm2_import -C primary.ctx -i duprv.bin -u key.pub -r key.priv  -L policy.dat
```
(i'm not sure what policy to specify there though)

---

Anyway, if anyone has this procedure documented or could give pointers, i'll gladly update the wiki w/ a PR.

**Comment by idesai** [comment]
@salrashid123 thanks for reporting the mailing list error. As for your questions have you looked at the [integration-test](https://github.com/tpm2-software/tpm2-tools/blob/master/test/integration/tests/import_tpm.sh) for duplicate/import?

**Comment by salrashid123** [comment]
@idesai Thanks!..that worked great.  I was able to use a key on TPM as well as one that was generated  via ordinary openssl.

The writeup is here..LMK if you see stuff thats incorrect (or if you want, i can add in as a wiki somehwere)
- https://gist.github.com/salrashid123/6df1e40b58e9068533eb9462f1dd4408

note, i used a pinned `tpm2_tools`  (`git checkout 4.0-rc2`) though.

**Comment by idesai** [comment]
@salrashid123, thanks for the writeup. Can you create a PR for the wiki tutorial section at https://github.com/tpm2-software/tpm2-tools.wiki.git?

**Comment by salrashid123** [comment]
I dont' thnk i can add anything to a wiki (AFAIK, its [restricted to collaborators](https://help.github.com/en/articles/changing-access-permissions-for-wikis), etc)..tuns out that i can't fork it as a normal PR either. 
i don't mind if you directly add the snippet [here](https://gist.github.com/salrashid123/6df1e40b58e9068533eb9462f1dd4408) (i reformatted it)

**Comment by idesai** [comment]
Interesting. For now, I have uploaded your writeup to the [wiki](https://github.com/tpm2-software/tpm2-tools/wiki/Duplicating-Objects) location. I will explore if there is a way to add to the wiki in a review-merge style.

I will let you close the issue :). As for the mailing list, I found another link https://lists.01.org/postorius/lists/tpm2.lists.01.org/. I am not sure if the original link being offline is a temporary issue.

**Comment by salrashid123** [comment]
thanks!

**Comment by salrashid123** [comment]
@idesai 

i documented the various scenarios used so far using both `tpm2_tools` and `go-tpm`.  If you see aything else here you can use, pls feel free to lift (LMK and i'll point back to the canonical wiki for `tpm2_toosl`.

https://github.com/salrashid123/tpm2

finally, its not `tpm2_tools` but for opensslEVP sample i put together for google authentication and general sign, encrypt:  https://github.com/salrashid123/tpm2_evp_sign_decrypt

**Comment by salrashid123** [comment]
@idesai 
do you happen to have a copy of the wiki for this article around still
  https://github.com/tpm2-software/tpm2-tools/wiki/Duplicating-Objects

i don't have the gist around anymore and i can't see the wiki page either in the git history (i don't think wiki's work like that)

if you still can access it, could you post it to a gitst so i can copy it down?
