### ISSUE TITLE
tpm2_createprimary command

### ISSUE THREAD

**Issue by Simon47h** [tpm2-software/tpm2-tools#1781]
Hey evryone;

i am using tpm2-tools for testing my tpm.

Before starting the tests i am doing :   tpm2_createprimary -H o **-g sha256** -G ecc 

why we need a hash to create a primary key ?

thanks in advance

**Comment by idesai** [comment]
@Simon47h Please use the [mailing-list](https://lists.01.org/postorius/lists/tpm2.lists.01.org) for general TPM questions. We'd appreciate any feedback on errors/bugs/new features on the issue tracker. Thanks.
