### ISSUE TITLE
Checkquote no longer outputs proper YAML

### ISSUE THREAD

**Issue by jetwhiz** [tpm2-software/tpm2-tools#1782]
Note that the commit here breaks YAML output (particularly when outputting PCR data): https://github.com/tpm2-software/tpm2-tools/commit/350fae1f410e95b5f9a21059e7c6d1e279857801#diff-6e12f2d1da3a30287442b0cbb76b67eaL87

Now the signature buffer is dumped out to STDOUT without the necessary YAML key field (removed in the commit above).  

https://github.com/tpm2-software/tpm2-tools/blob/ef3bd3aa2c190a8d2d4b38ea4f1442dcc994cc69/tools/misc/tpm2_checkquote.c#L80

**Comment by williamcroberts** [comment]
whoop sorry a little overzealous with that cleanup

**Comment by williamcroberts** [comment]
Fixed in #1784 and I am working on a 4.0.1 release candidate with this fix.

**Comment by jetwhiz** [comment]
Thanks, @williamcroberts !
