### ISSUE TITLE
Evictcontrol fails when trying to evict using platform hierarchy

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tools#1793]
tpm2_createprimary -C o -c primary.ctx

tpm2_evictcontrol -C p -c primary.ctx 0x81010001
WARNING:esys:src/tss2-esys/api/Esys_EvictControl.c:326:Esys_EvictControl_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EvictControl.c:114:Esys_EvictControl() Esys Finish ErrorCode (0x00000285) 
ERROR: Esys_EvictControl(0x285) - tpm:handle(2):hierarchy is not enabled or is not correct for the use
ERROR:esys:src/tss2-esys/esys_tr.c:357:Esys_TR_Close() Error: Esys handle does not exist (70018). 
ERROR: Esys_TR_Close(0x70018) - esapi:0x18
ERROR: Unable to run tpm2_evictcontrol

**Comment by idesai** [comment]
@tstruk @williamcroberts  I think I am passing the hierarchy handle alright. Seems like this may be an issue in ESAPI.

**Comment by williamcroberts** [comment]
Looks like an ESAPI bug, the handle being sent is owner: 0x81000000, but the handle passed to Esys_Evictcontrol is platform.

**Comment by williamcroberts** [comment]
What's interesting is that it hits Tss2_Sys_EvictControl_Prepare() correctly...

**Comment by williamcroberts** [comment]
Oh looks like when we pick a handle to persiste at, that the too starts our persistent first on a handle not suitable for platform
