### ISSUE TITLE
nv tools dont ensure index is passed

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1802]
nv tools all have the same on_arg handler (for the most part) and dont check that the nv index was specified and just call to the TPM with index as 0 causing an error.

**Comment by idesai** [comment]
I think there is a check in the function macro for it
https://github.com/tpm2-software/tpm2-tools/blob/b1f443dc9a2efb65453876730c285a61956c2ab6/lib/tpm2_nv_util.h#L241
