### ISSUE TITLE
nv tools could use common on_arg handler

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1803]
move the nv tool on_arg handler to the library, its duplicated across tools

**Comment by idesai** [comment]
It is in the header currently - https://github.com/tpm2-software/tpm2-tools/blob/b1f443dc9a2efb65453876730c285a61956c2ab6/lib/tpm2_nv_util.h#L228

@williamcroberts do you mean some nv tools do not use this function macro?

**Comment by idesai** [comment]
There are 21 tools mention nv  and they are accounted for using the on_arg_nv_index.

:~/workspace/tpm2-tools/tools$ find -name \*\.c | grep nv | xargs grep -lv on_arg_nv_index | wc -l
21
:~/workspace/tpm2-tools/tools$ find -name \*\.c | grep nv | wc -l
21
