### ISSUE TITLE
What is the equivalent command for "tpm2_takeownership --clear" in tpm2-tools version 4.0

### ISSUE THREAD

**Issue by vamshim567** [tpm2-software/tpm2-tools#1808]
Hi,

In the previous version of tpm2-tools we have used the option tpm2_takeownership --clear in our test script. However, now we want to use version 4.0 and we do not know the exact equivalent command for it.

Could you please help.

**Comment by williamcroberts** [comment]
That portion of the command was just calling TPM2_Clear command, so it's replaced in the tools as tpm2_clear, no options, no arguments. That command requires lockout authorization. So before if you running tpm2_takeownership --clear with no options, then the lockout hierarchy has an empty password for the auth value.
