### ISSUE TITLE
policysigned and policyticket time formats

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1809]
We need a consistent, clean and scalable way to deal with time formats between the tools. I noticed this in PR #1799  for policycounter and it looks like the same issues in policysigned and policyticket.

**Comment by idesai** [comment]
tpm2_policycountertimer --> time/ clock specified in milliseconds
tpm2_policysigned and tpm2_policysecret--> expiration specified in (+/-) seconds
tpm2_policyticket --> simply consumes the timeout structure output by policysecret/policysigned.
- [ ] Add a library routine to convert input string to signed INT32
- [ ] Process the expiration input for tpm2_policysigned as signed INT32
- [ ] Process the expiration input for tpm2_policysecret as signed INT32
