### ISSUE TITLE
Fails to build on 32-bit arch

### ISSUE THREAD

**Issue by arsing** [tpm2-software/tpm2-tools#1835]
https://github.com/tpm2-software/tpm2-tools/pull/1829/files#diff-735b9b0b3bafb20ec3b9294457d73f65R168

```
lib/tpm2_util.c: In function ‘tpm2_util_string_to_int32’:
lib/tpm2_util.c:168:22: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     if (errno || tmp > UINT32_MAX) {
                      ^
```

This is with `gcc (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516` on a Raspberry Pi running Debian 9 armhf.

`signed long int tmp` is 32 bits long and can't exceed a `UINT32_MAX`. So there isn't a logic error in the comparison, but the warning plus the `-Werror` config do make the build fail.

Affects master and 4.1-rc0.

**Comment by DaVolfman** [comment]
Possibly more importantly there is a different function for 32-bit unsigned, so this should probably have been INT32_MAX.  That's the patch I used to get this to compile.  It's worth noting that longs are often 64 bits wide on 64-bit platforms so it's worth leaving the check code in there, just fixing it.
