### ISSUE TITLE
tpm2_policynv crashes tpm

### ISSUE THREAD

**Issue by DaVolfman** [tpm2-software/tpm2-tools#1837]
My attempts to use tpm2_policynv to create policy based on an NV counter crash the tpm requiring a reset of the PC to restore access.  On tpm2_tools 4.1.0rc0 lib32
Steps taken:

- Define an NV counter area of 8 octets and blank owner r/w authorization at handle 0x1800101
- Increment it
- Start a trial authorization session
- echo 0x2 and pipe it to tpm2_policynv with operation of 0x1800101 eq against stdin

Log of test:
[tpm2-tools-4.1rc-log.txt](https://github.com/tpm2-software/tpm2-tools/files/3826373/tpm2-tools-4.1rc-log.txt)
TPM firmware is a little stale since the platform is customized (supplier not offering standalone update) and I'm using an old prototype unit right now. TPM info from getcap:
[tpmversion.txt](https://github.com/tpm2-software/tpm2-tools/files/3826458/tpmversion.txt)
But the commands are implemented:
[commandlist.txt](https://github.com/tpm2-software/tpm2-tools/files/3826460/commandlist.txt)

**Comment by idesai** [comment]
@DaVolfman there are a couple of issues with your commands.
1. The authorization chosen when defining the NV index is not the authorization you use when generating the policyNV.
2. The data that you are piping to compare is not a problem but be aware that the value you have in the NV index is hex 2 and what you are ultimately piping is ascii representation of hex 2.

So try this sequence for generating the policy instead.
tpm2_startauthsession -S session.ctx
echo 0x2| xxd -r -p | tpm2_policynv -S session.ctx -L policy.digest -i- 0x1800101 eq -C o
tpm2_flushcontext session.ctx

**Comment by DaVolfman** [comment]
I think you mean echo 02 | xxd -r -p or printf '\x02;.  I tried it.  I also tried a printf '\2\n' in case the input system needed a newline.  Combined with adding the authorization to policynv none of these made a difference.  I'm hesitant to try x64, since that would run on my primary dev box and I've already had breakage from incomplete forced RPM installs, but I acknowledge it should be done.

**Comment by DaVolfman** [comment]
I installed our development build onto the test unit and installed my 64-bit packages for tpm2_tools.  I'm still getting the same result.  If I can requisition a newer unit again I'll let you know how it turns out there.  In the mean time the priority of this working on my end is reduced: after reading the spec it turns out counters are an exceptionally poor choice for what I wanted them for due to the interdependence and complete lack of restart.

**Comment by idesai** [comment]
Does this work at your end?
```
tpm2_nvdefine -C o -s 8 -a 'ownerread|ownerwrite|nt=1' 0x1800101
tpm2_nvincrement -C o 0x1800101
tpm2_nvincrement -C o 0x1800101

tpm2_startauthsession -S session.ctx --policy-session
echo "02" | xxd -r -p | tpm2_policynv -S session.ctx -L policy.digest -i- 0x1800101 eq -C o --offset 7
tpm2_flushcontext session.ctx
```

**Comment by DaVolfman** [comment]
Nope, same error 101.  Success or failure on the policy shouldn't be a factor on this.  A failure to satisfy policy gives a 1C4 or similar "tpm:parameter(*):value is out of range or is not correct for the context" which is a well behaved recoverable error.

**Comment by idesai** [comment]
@DaVolfman, unfortunately, I do not have the infineon TPM, especially with that old a firmware. Are you able to reproduce the issue with a simulator?

**Comment by DaVolfman** [comment]
I don't have a simulator package and I'm not running a distro on this so there's no repos to pull from.  I don't have a recipe to build the ms/ibm sim, it looks like it would be pretty simple (no autotools to fight), but other things have come up so I'm going to have to wait for some free time as this is off the critical path now.

**Comment by DaVolfman** [comment]
I've installed rc1 on a coworker's unit.  It didn't crash in testing.  So apparently there were some previous versions of the SLB9665 firmware that were broken in this command.
