### ISSUE TITLE
unseal.sh integration test extends sha1 PCR bank without checking to see if sha1 bank is enabled

### ISSUE THREAD

**Issue by bnevis-i** [tpm2-software/tpm2-tools#1838]
The `unseal.sh` integration test at https://github.com/tpm2-software/tpm2-tools/blob/master/test/integration/tests/unseal.sh#L104 reads:

```sh
tpm2_pcrextend 0:sha1=6c10289a8da7f774cf67bd2fc8502cd4b585346a
```

MSFT HLK requirements, the TCG PC client TPM profile 1.03 and the TCG Automotive TPM profile 1.01 require that sha256 be the default allocated PCR bank: the sha1 bank is not required to be enabled.

This test case should be changed to extend the sha256 bank instead, or at a minimum, check whether or not the sha1 bank is enabled before attempting the above operation.

**Comment by idesai** [comment]
The simulator is the intended test platform for the tests and sha1 is enabled on it by default.
