### ISSUE TITLE
tpm2_startauthsession nonce support?

### ISSUE THREAD

**Issue by remuswu1019** [tpm2-software/tpm2-tools#1840]
I am trying to make data persisted with `tpm2_evictcontrol` and I think there is something wrong.
If without HMAC session, nonce is not used, right?

If so, `tpm2_startauthsession` looks like the solution to creation session context, but it's not supported current.

Following is my instruction, 
```
tpm2_getrandom --output=SECRET 32
tpm2_startauthsession -S session.ctx
tpm2_policysecret -c p -S session.ctx -L secret.policy
tpm2_flushcontext session.ctx

tpm2_createprimary -C p -g sha256 -G rsa2048:null:aes128cfb -l sha256:0,2,3,7 -L secret.policy -c primary.ctx
tpm2_create -C primary.ctx -g sha256 -u seal.pub -r seal.priv -l sha256:0,2,3,7 -L secret.policy -i SECRET
tpm2_load -C primary.ctx -u seal.pub -r seal.priv -c seal.ctx --name=seal.name
tpm2_evictcontrol -C p -c seal.ctx 0x81800000

tpm2_startauthsession -S session.ctx
tpm2_policysecret -S session.ctx -c o -L secret.policy
tpm2_unseal -c 0x81800000 -o SECRET.unseal -p "session:session.ctx"
```
and I got error messages as below,
```
ERROR: A trial session cannot be used to authenticate, Please use an hmac or policy session
ERROR: Invalid item handle authorization
ERROR: Unable to run tpm2_unseal
```

How to specific HMAC session with this command?

**Comment by idesai** [comment]
when you try to unseal make sure you start a policy session by specifying:
tpm2_startauthsession -S session.ctx --policy-session

**Comment by remuswu1019** [comment]
Policy session is same as HMAC session?

**Comment by idesai** [comment]
Yes, nonceTPM is factored in the authorization. So when you run tpm2_policysecret add the command line parameter --nonce-tpm to restrict authorization to single use in session.

**Comment by idesai** [comment]
@remuswu1019 please reopen if you find issues with --nonce-tpm option. Thanks.
