### ISSUE TITLE
tpm2_startauthsession hangs in early boot.

### ISSUE THREAD

**Issue by DaVolfman** [tpm2-software/tpm2-tools#1844]
Somewhere in the call stack tpm2_startauthsession is consuming the getrandom() syscall, even when a session key is not provided.  In kernel version >= 4.16 this is a blocking syscall until the rng is fully seeded.  The result is a complete hang if policy authorization is attempted to be used for boot services in a system without a moving mouse or other source of easy entropy.  This is especially the case for use within any initramfs where there aren't many, or even any, background tasks.

**Comment by idesai** [comment]
Try a solution proposed for [BoottimeEntropyStarvation](https://wiki.debian.org/BoottimeEntropyStarvation). ESAPI consumes system entropy for session protections.

**Comment by DaVolfman** [comment]
The rng_core.default_quality option seems to work.  I'll have to sell it to my management though.  It seems to me that trusting the communication over the bus to get random numbers from the tpm to seed the RNG you use to get random numbers for a key/salt so that you can communicate with the tpm without trusting the bus isn't much more secure than just trusting the bus for communication with the tpm.

**Comment by DaVolfman** [comment]
I got buy in on trusting HWRNGs for the entropy count so that's the accepted solution on my end.  I still think it would be nice to have an option to construct a startauthsession so that it didn't grab random numbers but that's a nice-to-have unpaid feature request, not an issue.
