### ISSUE TITLE
They are Bash scripts, not "sh" scripts

### ISSUE THREAD

**Issue by jhealyt** [tpm2-software/tpm2-tools#1855]
The test scripts in the "**_test/integration_**" directory should all have the extension ".bash" and begin with "#!/bin/bash".

This is more important for people working on embedded Linux.

**Comment by williamcroberts** [comment]
> The test scripts in the "**_test/integration_**" directory should all have the extension ".bash" and begin with "#!/bin/bash".

While their are general followings, file extensions in linux don't really do anything, so I am confused what the exact issue is here. Can you elaborate?

> 
> This is more important for people working on embedded Linux.

Why is it important?

**Comment by idesai** [comment]
@jhealyt please reopen if there are additional findings or if this is causing failures at your end.
