### ISSUE TITLE
Expand -L description

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1858]
The manpage -L description isn't very helpful. Expand this so folks know where to go poke around to generate a policy file.

Maybe for things that take -L make sure an example exists.

**Comment by SebaMederos** [comment]
> The manpage -L description isn't very helpful. Expand this so folks know where to go poke around to generate a policy file.
> 
> Maybe for things that take -L make sure an example exists.

I am interested in collaborating with the documentation of the project, and I have found that this issue has been successfully completed, that is, what is required by you is already implemented! I've found it in the man pages generated with pandoc.
