### ISSUE TITLE
tpm2_verifysignature always fails when you use --digest

### ISSUE THREAD

**Issue by jhealyt** [tpm2-software/tpm2-tools#1867]
Previously I had been using "tpm2_verifysignature" with small files (less than a kB), and it worked fine with the options "-m -g".

Now I need to work with files sized about 300 - 500 MB, and so I have to calculate the hashsum manually using "sha256sum", and then I feed the hashsum into verifysignature with the option "-d". This fails every time with the error: 

ERROR: Esys_VerifySignature(0x2D2) - tpm:parameter(2):unsupported
or incompatible scheme

I have checked that the format of my hashsum file is the same as what's produced by "tpm2_hash".

I asked about this on the mailing list, and I was told to file a bug report.

**Comment by idesai** [comment]
@jhealyt, Please look at the [test](https://github.com/tpm2-software/tpm2-tools/blob/5332603986d66a661d3231d7ce0e87bc1453f655/test/integration/tests/verifysignature.sh#L62) that does exactly this. You are missing the ticket input.

**Comment by idesai** [comment]
@jhealyt please reopen the ticket if you are still seeing issues. For now this actually works.

tpm2_createprimary -C e -c primary.ctx -Q
tpm2_create -G rsa -u rsa.pub -r rsa.priv -C primary.ctx -c rsa.ctx -Q
echo "my message" > message.dat
sha256sum message.dat | cut -c -64 | xxd -r -p >  message.hash
tpm2_sign -c rsa.ctx -g sha256 message.dat -o sig.rssa
tpm2_verifysignature -c rsa.ctx -d message.hash -s sig.rssa
