### ISSUE TITLE
tpm2_nvdefine won't accept "--auth"

### ISSUE THREAD

**Issue by jhealyt** [tpm2-software/tpm2-tools#1868]
The manual says you can use "-P" or "--auth" interchangeably, however it only accepts "-P".

**Comment by williamcroberts** [comment]
Where in the manual does it say this? I can find references for `--hierarchy-auth`
  - https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_nvdefine.c#L130
  - https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_nvdefine.1.md

**Comment by idesai** [comment]
@jhealyt the option is --hierarchy-auth for 4.X and current master. Thanks.
