### ISSUE TITLE
missing utils from ubuntu/debian tpm2-tools  package

### ISSUE THREAD

**Issue by dangilson** [tpm2-software/tpm2-tools#1878]
The following seems to be missing:
tpm2_nvrelease
tpm2_akparse
tpm2_nvlist
tpm2_getmanufec
tpm2_takeownership
tpm2_getpubek
tpm2_getpubak
tpm2_listpcrs

But they are included with the tpm2-tools .deb package for ubuntu/debian.  

Is there a technical reason for this or does someone actually just have to do? 
I ask because depending on our customer's acceptance tests,  I may need to make this happen.  Any background would be greatly appreciated.

**Comment by diabonas** [comment]
These tools were renamed in tpm2-tools 4, see the [changelog](https://github.com/tpm2-software/tpm2-tools/blob/master/CHANGELOG.md#40---2019-09-09). I would recommend not using the old tools any more and migrating to version 4 if possible.

**Comment by dangilson** [comment]
Looks like all are there and have been renamed except tpm2_akparse.
Thanks
...Dan
    On Wednesday, December 25, 2019, 02:39:34 AM PST, Jonas Witschel <notifications@github.com> wrote:  
 
 
These tools were renamed in tpm2-tools 4, see the changelog. I would recommend not using the old tools any more and migrating to version 4 if possible.

**Comment by williamcroberts** [comment]
> The link to the change log is 404 now. Can anyone provide a list of the name changes?

Still in the git history:
  - https://github.com/tpm2-software/tpm2-tools/blob/4.0/CHANGELOG.md

**Comment by mathieuDombrockTAF** [comment]
@williamcroberts 
Awesome! I appreciate you pointing me in the right direction there!
