### ISSUE TITLE
tpm2_getekcertificate: needs to support non URL based EK Certs

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1885]
The provisioning guidelines:
  - https://trustedcomputinggroup.org/wp-content/uploads/TCG_IWG_Credential_Profile_EK_V2.1_R13.pdf

Indicate that manufacturers can store certificates in certain NV indices, so we should also check those for certs rather than requiring a URL.

**Comment by idesai** [comment]
@williamcroberts wouldn't that be tpm2_nvread?

**Comment by williamcroberts** [comment]
Yes, that would be one way, but if you call tpm2_getekcertificate, you should get an EK certificate, no matter where it exists.
