### ISSUE TITLE
tpm_nvdefine v.4.1+: Restrict search for free index to the hiearchy specified

### ISSUE THREAD

**Issue by ghfields** [tpm2-software/tpm2-tools#1891]
As of 4.1:
tpm2_nvdefine:  Support searching for free index if an index isn't specified.

The first time `tpm2_nvdefine -Co` is run, it offers `nv-index: 0x1000000`, but this is inappropriate for an Owner hierarchy object.  [According to this document](https://trustedcomputinggroup.org/wp-content/uploads/RegistryOfReservedTPM2HandlesAndLocalities_v1p1_pub.pdf) (Table 2), 0x1800000 - 0x1BFFFFF is the correct range.  Could the tpm2_nvdefine search intelligently for an index based on a specified hierarchy?

**Comment by idesai** [comment]
@ghfields @williamcroberts, according to the same document the TPM does not enforce the conventional usage (i.e., bits 23-00) for NV Indices defined in this section. Would it then be a good idea to enforce it in the tools?

As an example - index 1000000 is reserved for the TPM manufacturer. There are two problems if we restrict this creation:
1. There is no hierarchy called TPM-manufacturer. 
2. There is no reason or restriction for an end-user to not be able to define an NV index in that range except for the recommendation from TCG. Note - it is a recommendation, not a mandate.

**Comment by ghfields** [comment]
@idesai, The request is not to restrict/enforce the assignment to only the specified hierarchy.

In the event that tpm2_nvdefine is asked to search and self-select an index (ie. the behavior in v4.1+ when an index is not specified), it should return an index that conforms to the recommended range of the hierarchy that is also provided.  If one wishes, index 0x1000000 could still be used in any matter, as long as it is explicitly stated as an argument, it just wouldn't be offered as a default.

**Comment by idesai** [comment]
> @idesai, The request is not to restrict/enforce the assignment to only the specified hierarchy.
> 
> In the event that tpm2_nvdefine is asked to search and self-select an index (ie. the behavior in v4.1+ when an index is not specified), it should return an index that conforms to the recommended range of the hierarchy that is also provided. If one wishes, index 0x1000000 could still be used in any matter, as long as it is explicitly stated as an argument, it just wouldn't be offered as a default.

@ghfields, thanks. I see your point.
@williamcroberts should I stage this for 4.2?

**Comment by idesai** [comment]
@ghfields, concluded that the tool should support the mechanism and not enforce a policy as specified in the document.
