### ISSUE TITLE
tpm2_policyor: example resets PCR state

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#1895]
The example resets PCR state which is likely not desired...

**Comment by idesai** [comment]
> The example resets PCR state which is likely not desired...

@williamcroberts, the man page example attempts to illustrate that two separate valid PCR states evaluate through PolicyOR. The reason to use a resettable PCR is to generate and iterate through the two PCR states to demonstrate PolicyOR functionality.
