### ISSUE TITLE
global data in tpm2_tool code module interferes with unit tests

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tools#1897]
In working on #1882 it's become apparent that the `tpm2_tool_output` function / macro is not usable from code under unit test. The issue boils down to the global data used in this function being defined in the `tpm2_tool` code module where the `main` function for the tools is defined. This causes duplicate symbols in the unit test which has a `main` function of it's own. The most logical solution is to move this data and the `tpm2_tool_output` macro to a new module.

https://github.com/tpm2-software/tpm2-tools/pull/1882#issuecomment-575786379

**Comment by idesai** [comment]
Closed via #1898
