### ISSUE TITLE
add new dependency to CI workers

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-tools#1912]
I'm working on a patch to get the `tpm2_eventlog` tool for parsing some event data. As is the case with everything in UEFI, it requires parsing UUIDs (Microsoft and therefore UEFI call these GUIDs). Linking with libuuid seems better than writing a parser from scratch. Integrating a check for libuuid in the build is easy enough, but getting it installed on the CI workers seems to be more complicated now that they're docker images (libuuid-dev isn't installed in the images used by the tools CI AFAIK). Any idea how to best accomplish this?

**Comment by flihp** [comment]
failing CI run is here: https://travis-ci.org/flihp/tpm2-tools/builds/641562602

**Comment by idesai** [comment]
@flihp should this be filed against tpm2-software-container? Need to update the package in every Dockerfile.

**Comment by flihp** [comment]
doesn't really matter to me, just trying to unblock #1925

**Comment by idesai** [comment]
@flihp @williamcroberts [added](https://github.com/tpm2-software/tpm2-software-container/pull/29) uuid package to our docker builds.
