### ISSUE TITLE
tpm2_pcrlist: command not found

### ISSUE THREAD

**Issue by jfrantz1-r7** [tpm2-software/tpm2-tools#1913]
Other TPM2 commands work fine, but this one does not. I have tpm2-tools installed on Ubuntu 18.04 on a lenovo x390

**Comment by idesai** [comment]
@jfrantz1-r7 what version of the tools are you using? Also what error are you seeing?

**Comment by jfrantz1-r7** [comment]
The latest version, let me collect more information and get back to you in a few minutes (sorry about the brevity in the initial post)

**Comment by bnevis-i** [comment]
In the 4.x version of the tools it has been renamed to tpm2_pcrread.
