### ISSUE TITLE
Unable to load AK key

### ISSUE THREAD

**Issue by chenxizf** [tpm2-software/tpm2-tools#1920]
I am trying to create a non-persistent AK, save private and public keys in disk (or DB), and load the key on demand when I use it.
 
I installed the latest releases:
Tpm2_tools 4.1.1
Tpm2-abrmd-2.3.1    
tpm2-tss-2.3.2

I am able to create an AK key successfully with the command below:
$tpm2_createak -C 0x81010001 -c ak.ctx -u ak.pub -r ak.priv -n ak.name -P dummypaswd -p dummypaswd.

I got an error when I try to load the key. 
$tpm2_load -C 0x81010001 -u ak.pub -r ak.priv -n ak.name -c ak.ctx -P dummypaswd

WARNING:esys:src/tss2-esys/api/Esys_Load.c:320:Esys_Load_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x0000012f)
ERROR: Eys_Load(0x12F) - tpm:error(2.0): authValue or authPolicy is not available for selected entity
ERROR: Unable to run tpm2_load

I tried to decode the error code below, but still couldn't understand the reason.
$tpm2_rc_decode 0x0000012f
tpm:error(2.0): authValue or authPolicy is not available for selected entity

Could anyone help take a look why it is failing? Thanks~

**Comment by idesai** [comment]
@chenxizf, the ak.ctx file generated when running tpm2_createak is already the context of the loaded key. You do not have to load the key again.

**Comment by idesai** [comment]
If you have flushed the key handle, to reload you will need to satisfy the auth policy first
tpm2_startauthsession --policy-session -S session.ctx
tpm2_policysecret -S session.ctx -c 0x4000000B dummypassword
tpm2_load -C 0x81010001 -u ak.pub -r ak.priv -n ak.name -c ak.ctx -P session:session.ctx
tpm2_flushcontext session.ctx

**Comment by chenxizf** [comment]
@idesai  Thank you for the answer. It is very helpful.
Another question: is there a way to know if a non-persistent AK has been loaded?  And if it has been loaded, how can I retrieve the key context.

One use case is below:
AK has been created (or reloaded) and then TPM is rebooted for some reason. The caller is still holding old AK context, and no way to know if the key context is still valid and if the AK key is needed to be reloaded.

**Comment by idesai** [comment]
@chenxizf once there is a TPM restart all transient handles will be flushed. You will have to repeat the load steps above by holding on to the .priv and .pub files and ensure the parent continues to be persistent at 0x81010001. In any case if you must see the transient handles and it's properties you can use a couple of tools.
tpm2_getcap handles-transient
tpm2_readpublic -c <handles reported by tpm2_getcap>
The only way to deduce that an ak is loaded is by examining the output of tpm2_readpublic and comparing the name and or the key attributes.

**Comment by idesai** [comment]
@chenxizf since there isn't a particular issue with any specific tool being discussed here, I'd appreciate it if you can please continue the discussion in the mailing list and close this topic in the issue tracker.

**Comment by chenxizf** [comment]
Thanks @idesai.  
Close this ticket as it is resolved.

BTW the "**mailing list**" link at https://github.com/tpm2-software/tpm2-tools/wiki, is not work. what is the mailing list email address?

**Comment by idesai** [comment]
@chenxizf thanks for the information. Please can you try this [link](https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/)?

**Comment by chenxizf** [comment]
it works. Thanks
