### ISSUE TITLE
Question: when we use TPM2tools for RSA signing, do we also use TPM for hashing?

### ISSUE THREAD

**Issue by danielwangksu** [tpm2-software/tpm2-tools#1921]
I know we can use TPM2tools command line to sign file:
```
tpm2_sign -c obj.ctx -g 0x000b -m msg.in -s sig.out
```
We can also use openssl engine `tpm2tss` for file signing.

For either of this case do we use TPM the hardware to hashing or software implementation? The reason I'm trying to figure out is the potential performance toll.

**Comment by steschuser** [comment]
Hello,

by using tpm2tss engine, the chip is only involved in decoding the
private key, everting else is handled by openssl.

if you use tpm2_sign, the signing operation is done with the chip.

thats my afaik anyway.
I might be very wrong indeed :)


performance wise, it should be faster to use openssl engine, at least
for rsa keys.
difference for ec keys is smaller.

regards,
Steffen Schwebel

**Comment by danielwangksu** [comment]
@steschuser Thank you for your insight! For  tpm2_sign "the signing operation is done with the chip" means both hashing and signing operation is done in the chip right?

**Comment by idesai** [comment]
* **-d**, **\--digest**:

    Indicate that _FILE_ is a file containing the digest of the message.
    When this option and **-t** is specified, a warning is
    generated and the **validation ticket (-t) is ignored**.
    You cannot use this option to sign a digest against a restricted
    signing key.

**Comment by idesai** [comment]
@danielwangksu, please reopen the ticket if you find an issue with the tool. If there are more questions on its usage please use the mailing [list](https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/).
