### ISSUE TITLE
Question about tpm2_ownership

### ISSUE THREAD

**Issue by TheHyren** [tpm2-software/tpm2-tools#1924]
In the readme I am told to use tpm2_takeownership to set password access to the chip. This function is no longer in the current version I downloaded with git. What are the comparable functions now?

**Comment by idesai** [comment]
@TheHyren tpm2_takeownership was purported to 
1. Setup the auths for owner, lockout, endorsement hierarchy --> This is now tpm2_changeauth
2. Clear the authorizations --> This is now tpm2_clear

**Comment by TheHyren** [comment]
Thank you!
For clarification:
tpm2_takeownership -c is now tpm2_clear
tpm2_takeownership -L $pass is now tpm2_changeauth -l $pass

Do I have this correct?

**Comment by idesai** [comment]
Yes. Also refer the [man](https://github.com/tpm2-software/tpm2-tools/blob/4.0.X/man/tpm2_changeauth.1.md) page for specific examples.

**Comment by TheHyren** [comment]
Awesome.
Hoping you can help me with 1 last question. I am setting up a luks volume for drive encryption. I am not sure which account should be the owner of the tpm chip. Should the owner be root, tss, or the luks account (secure)

**Comment by idesai** [comment]
> Awesome.
> Hoping you can help me with 1 last question. I am setting up a luks volume for drive encryption. I am not sure which account should be the owner of the tpm chip. Should the owner be root, tss, or the luks account (secure)

Please direct the question to the [mailing-list](https://lists.01.org/postorius/lists/tpm2.lists.01.org/).
