### ISSUE TITLE
Creating TPM2 primary key failed

### ISSUE THREAD

**Issue by bedawi** [tpm2-software/tpm2-tools#1932]
I get the following error message:
```
$ sudo clevis luks bind -d /dev/sda3 tpm2 '{"pcr_ids":"7"}'

WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:389:Esys_CreatePrimary_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x000002ca) 
ERROR: Esys_CreatePrimary(0x2CA) - tpm:parameter(2):the type of the value is not appropriate for the use
ERROR: Unable to run tpm2_createprimary
Creating TPM2 primary key failed!
```

I use version 4.0.1 on Fedora 31.
The device is a Dell Venue Pro 11 7031.
To be sure that the TPM is not locked I installed Windows 10 and used the tpm.msc tool to clear the TPM - no success. Bios has been updated to newest version (December 2019)

Many greetings
Ben

**Comment by idesai** [comment]
@martinezjavier, any thoughts?
@bedawi can you show the output for "tpm2_getcap properties-variable" ?

**Comment by bedawi** [comment]
Here we go:

```
$tpm2_getcap properties-variable
TPM2_PT_PERSISTENT:
  ownerAuthSet:              0
  endorsementAuthSet:        0
  lockoutAuthSet:            1
  reserved1:                 0
  disableClear:              0
  inLockout:                 0
  tpmGeneratedEPS:           1
  reserved2:                 0
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  1
  shEnable:                  1
  ehEnable:                  1
  phEnableNV:                0
  reserved1:                 0
  orderly:                   1
TPM2_PT_HR_NV_INDEX: 0x3
TPM2_PT_HR_LOADED: 0x0
TPM2_PT_HR_LOADED_AVAIL: 0x3
TPM2_PT_HR_ACTIVE: 0x0
TPM2_PT_HR_ACTIVE_AVAIL: 0x40
TPM2_PT_HR_TRANSIENT_AVAIL: 0x3
TPM2_PT_HR_PERSISTENT: 0x3
TPM2_PT_HR_PERSISTENT_AVAIL: 0x16
TPM2_PT_NV_COUNTERS: 0x2
TPM2_PT_NV_COUNTERS_AVAIL: 0xE
TPM2_PT_ALGORITHM_SET: 0x0
TPM2_PT_LOADED_CURVES: 0x0
TPM2_PT_LOCKOUT_COUNTER: 0x0
TPM2_PT_MAX_AUTH_FAIL: 0x20
TPM2_PT_LOCKOUT_INTERVAL: 0x1C20
TPM2_PT_LOCKOUT_RECOVERY: 0x15180
TPM2_PT_AUDIT_COUNTER_0: 0x0
TPM2_PT_AUDIT_COUNTER_1: 0x0
```

**Comment by idesai** [comment]
@bedawi have you tried creating the primary key with tools? Your dump shows owner auth isn't set so the following command should work.
tpm2_createprimary -C o -c prim.ctx

**Comment by bedawi** [comment]
@idesai Thanks a lot. The command you mentioned worked and gave me this output:

```
$tpm2_createprimary -C o -c prim.ctx
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: rsa
  raw: 0x1
exponent: 0x0
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: <omitted>
```
So I have a primary key in a file now. What can I do with it and how does it help me with my problem?

**Comment by idesai** [comment]
@bedawi, with that I just intended to make sure there were no issues with TSS/ tools and clearly there isn't a problem there. As for your specific issue then, it might be useful to create a ticket with [clevis](https://github.com/latchset/clevis/issues/106). Perhaps you might have the command wrong...like missing information on pcr bank algorithm, etc.

**Comment by bedawi** [comment]
@idesai , thanks. I opened an [issue](https://github.com/latchset/clevis/issues/165) with clevis.

**Comment by bedawi** [comment]
Coming back here with a solution: The problem is that clevis is using ```ecc``` as the default algorithm which, as I understood the problem, is not supported by my TPM. So this is not a bug of the TPM2-Software. Check out the [issue with clevis](https://github.com/latchset/clevis/issues/165) to learn more.

Other, who run into the problem can easily solve it by providing a the algorithm like this:

```
$ sudo clevis luks bind -d /dev/sda3 tpm2 '{"key": "rsa", "pcr_ids":"7"}'
```

Thanks for your help @idesai

**Comment by martinezjavier** [comment]
> @martinezjavier, any thoughts?

Sorry for the delay, I see that Sergio already answered in the clevis issue.
