### ISSUE TITLE
CreatePrimary Failed ! ErrorCode: 0x9a2

### ISSUE THREAD

**Issue by zk55555** [tpm2-software/tpm2-tools#1933]
hey guys
I don't know how to fix the following mistakes
Waiting for help
______________________________________________________________________________
input：
tpm2_createprimary -H o -g sha256 -G ecc -C context.out
output:
ObjectAttribute: 0x00030072
ERROR: 
CreatePrimary Failed ! ErrorCode: 0x9a2

ERROR: Unable to run tpm2_createprimary
__________________________________________________________________________________
I look forward to your reply,thx 😊

**Comment by zk55555** [comment]
Maybe it's a lack of parameters            
Tpm2_createprimary - h e - K 11 - G 0x000b - G 0x0001 - C po.ctx - p 1 can be executed

**Comment by idesai** [comment]
@zk55555 can you specify what version of the tools are you using?

**Comment by zk55555** [comment]
@idesai sure

**Comment by idesai** [comment]
> Maybe it's a lack of parameters
> Tpm2_createprimary - h e - K 11 - G 0x000b - G 0x0001 - C po.ctx - p 1 can be executed

Yes. It looks to be. Although the options you specified seem a little in that you may have mixed up the lower and upper cases. However, may I suggest you use 4.X versions instead. The man pages, as well as the code, went through a lot of clean up in 4.0.

**Comment by zk55555** [comment]
hey bro.
I upgraded tools to 4.1.1, and the man pages did improve. 
Thanks for your reply😀

> Maybe it's a lack of parameters
> Tpm2_createprimary - h e - K 11 - G 0x000b - G 0x0001 - C po.ctx - p 1 can be executed
> 
> Yes. It looks to be. Although the options you specified seem a little off, in that you may have mixed up the lower and upper cases. However, may I suggest you use 4.X versions instead. The man pages, as well as the code, went through a lot of clean up in 4.0.
