### ISSUE TITLE
AES IV Length restrictions

### ISSUE THREAD

**Issue by Koneeee1** [tpm2-software/tpm2-tools#1937]
Hi,

I was looking for the reasoning behind the length restriction, but I couldn't find any. Is it safe to remove the length check to support 96 bit IV sizes?

https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_encryptdecrypt.c
        if (file_size != iv->size) {
            LOG_ERR("Iv should be 16 bytes, got %lu", file_size);
            return tool_rc_general_error;
        }

**Comment by idesai** [comment]
@Koneeee1 the IV is of type [TPM2B_IV](https://github.com/tpm2-software/tpm2-tss/blob/6da95b04b4f22284d5b40cc03fa19e6dc514339f/include/tss2/tss2_tpm2_types.h#L930) of size UINT16 which is like 128 bits.

**Comment by Koneeee1** [comment]
I see how this would restrict the maximum size to 128 bits, but does this need to apply for lower sizes as well?
Trying to skip the check lead me to the error  "Tss2_Sys_EncryptDecrypt2(0x4D5) - tpm:parameter(4):structure is the wrong size".

**Comment by idesai** [comment]
Is the AES mode CBC? if so, then key-length should [match](https://security.stackexchange.com/questions/90848/encrypting-using-aes-256-can-i-use-256-bits-iv) iv-length, no?

**Comment by Koneeee1** [comment]
What I was trying to do is implement CTR with 96 Bit IV so I could latter use a GCM hardware accelerator to reverse the operation. As you have rightfully pointed out, the counter block for some modes like CTR actually has to be full 16 Bytes.
For research purposes I will set the last 4 Bytes of the CTR IV to [0x00, 0x00, 0x00, 0x02] to get a running system. 
Thanks you very much
