### ISSUE TITLE
tpm2_policycountertimer is unusable with real policy sessions.

### ISSUE THREAD

**Issue by rowanmoul** [tpm2-software/tpm2-tools#1947]
As per the discussion on the [mailing list](https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/G4TP4JSRIDDQCDMTMWB2WQ3ZVS5ZYZGG/), there is a bug in tpm2_policycountertimer where the operandB byte array is reversed. This is preventing its use with a real policy session. It works with a trial session (although presumably it does not produce the correct output).

I would be happy to fix it myself but I'm not sure where the issue lies. I've looked at the code but my lack of experience with C is getting the better of me.

**Comment by idesai** [comment]
@rowanmoul thanks for finding the issue. Please feel to reopen the ticket if the [PR](https://github.com/tpm2-software/tpm2-tools/pull/1946) doesn't work for you.
