### ISSUE TITLE
tpm2_rsadecrypt error.

### ISSUE THREAD

**Issue by oscargomezf** [tpm2-software/tpm2-tools#1955]
I trying to tet a TPM, more precisely a TPM by ST Microelectronics. The chip ST33HTPH2X32AHC4. It is an SPI module and before compiling the kernel I have loaded all the modules necessary.

I am able to execute some functions without errors, like for example:

```
# tpm2_getrandom 32 | hexdump
0000000 6c8d 6656 520a 87f3 53c0 f272 4cc8 006a
0000010 5bd0 cc84 004e 0af2 52a1 1561 ea09 300f
```

But I am trying to use the example for encrypt/decrypt a file from https://www.mankier.com/1/tpm2_rsadecrypt#Examples

And all the commands work properly without errors, but the last one. This is the  error I've got:

```
# tpm2_rsadecrypt -c key.ctx -o msg.ptext msg.enc
WARNING:esys:src/tss2-esys/api/Esys_ContextLoad.c:279:Esys_ContextLoad_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_ContextLoad.c:93:Esys_ContextLoad() Esys Finish ErrorCode (0x00000902) 
ERROR: Esys_ContextLoad(0x902) - tpm:warn(2.0): out of memory for object contexts
ERROR: Unable to run tpm2_rsadecrypt
```

Does anyone any suggestion? By the way, the version of the TPM2_TOOLS I am using is 4.1.1.

Best regards.

**Comment by idesai** [comment]
Are you using a resource manager like tpm2-abrmd or the in kernel resource manager like /dev/tpmrm0?

**Comment by idesai** [comment]
@oscargomezf please re-open the issue if you are unable to flush contexts using tpm2_flushcontext or the resource manager should do this for you.

**Comment by oscargomezf** [comment]
I am sorry @idesai but I had to put apart this project, but right now I have enough time to work on it again.

I am using the version 4.1.1 of the tpm2_tools:

> # tpm2_getrandom -v
> tool="tpm2_getrandom" version="4.1.1" tctis="libtss2-tctildr" tcti-default=tcti-device

I can see the driver in the dev folder: 

> # ls -la /dev/tpm*
> crw-rw----    1 root     root       10, 224 Jan  1  1970 /dev/tpm0
> crw-rw----    1 root     root      253, 65536 Jan  1  1970 /dev/tpmrm0

I have executed the following commands:

> # tpm2_flushcontext -t
> # tpm2_flushcontext -l
> # tpm2_flushcontext -s

But after executing the example on the page: https://www.mankier.com/1/tpm2_rsadecrypt#Examples I've got the same error.

Do you have any suggestion?

**Comment by idesai** [comment]
@oscargomezf you should ideally use a resource manager.
Anyway, I am not seeing errors with the following sequence without resource manager.
```
tpm2_createprimary -c primary.ctx
tpm2_create -C primary.ctx -Grsa2048 -u key.pub -r key.priv
tpm2_flushcontext -t
tpm2_load -C primary.ctx -u key.pub -r key.priv -c key.ctx
echo "my message" > msg.dat
tpm2_rsaencrypt -c key.ctx -o msg.enc msg.dat
tpm2_flushcontext -t
tpm2_rsadecrypt -c key.ctx -o msg.ptext msg.enc
cat msg.ptext
```

**Comment by oscargomezf** [comment]
HI idesai,

Adding the two commands:

tpm2_flushcontext -t

You told me in that exact place, it works perfectly.

Thank you very much for your help.
