### ISSUE TITLE
Reset TPM2 Windows-Style?

### ISSUE THREAD

**Issue by bedawi** [tpm2-software/tpm2-tools#1956]
Hello there,

I need to reset my tablet's TPM because it is in something called "DA lockout mode".

I tried this:
```
$ tpm2_dictionarylockout --setup-parameters --max-tries=4294967295 --clear-lockout 
WARNING:esys:src/tss2-esys/api/Esys_DictionaryAttackLockReset.c:284:Esys_DictionaryAttackLockReset_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_DictionaryAttackLockReset.c:98:Esys_DictionaryAttackLockReset() Esys Finish ErrorCode (0x00000921) 
ERROR: Esys_DictionaryAttackLockReset(0x921) - tpm:warn(2.0): authorizations for objects subject to DA protection are not allowed at this time because the TPM is in DA lockout mode
ERROR: Unable to run tpm2_dictionarylockout
```

On Windows I'd use the tpm.msc tool. There can a TPM reset be initiated. The device then reboots and requests confirmation. 

Is this function already implemented in the tpm2-tools? If yes, I am sorry that I could not find it myself :-) - can someone please enlighten me? Maybe this would be a great topic for https://github.com/macpijan/tpm2-tools-wiki 

Thanks
Benjamin

**Comment by AndreasFuchsSIT** [comment]
`--clear-lockout` is the right way. However `Only one lockoutAuthauthorization failure is allowed for this command during a lockoutRecoveryinterval (set using TPM2_DictionaryAttackParameters()` (from TPM Spec). So you probably triggered this lockoutprotection while resetting lockout.
My recommendation; leave the machine running (so the countdown works) and think closely about what your authvalue was and then set it using `-p`

**Comment by AndreasFuchsSIT** [comment]
In order to trigger a clear apparently this is the way:
```
echo 5 > /sys/class/tpm/tpm0/ppi/request
```
But I have never used it and it comes at your own risk...

**Comment by bedawi** [comment]
@AndreasFuchsSIT: Many thanks - this worked perfectly.

To sum it up: `echo 5 > /sys/class/tpm/tpm0/ppi/request` has to be executed as root user followed by a `reboot`. The BIOS/UEFI then asks for confirmation to reset the TPM. 

I tested this on my Dell Venue 11 Pro Tablet.
