### ISSUE TITLE
NV Read/Write operations mishandle TPM2 with rev prior than 0.99

### ISSUE THREAD

**Issue by dcpi8990** [tpm2-software/tpm2-tools#1958]
tpm2_nvread and tpm2_nvwrite tools both rely on lib/tpm2_nv_util to determine the adequate transmission size for a buffer (`TPM2_PT_NV_BUFFER_MAX`). 

The function used,  `tpm2_util_nv_max_buffer_size()`, will silently fail on modules conforming to the _TPM2 Library Specification rev0.98_ and older. Indeed, `TPM2_PT_NV_BUFFER_MAX` has been around since revision 0.99 [1], and function `TPM2_GetCapability` is not specified to fail if the requested property does not exist, but to return the next higher property in the category (if it exists) [2].

In case of a module conforming to a revision prior to 0.99, the next property in this category happens to be `TPM_PT_PERMANENT`, which is the TPMA_PERMANENT bit-field describing whether the hierarchy authorizations are set, lockout mode is activated etc... Depending on the current state of the device, it may evaluate to an arbitrary low amount (0 to 7) if `inLockout`, `disableClear` and `tpmgeneratedEPS` are not set.

Currently, the only sanity check done is to verify that `tpm2_util_nv_max_buffer_size()` does not provide a value that is null or greater than `NV_DEFAULT_BUFFER_SIZE` (in the calling function).

Handling rev0.98 and earlier modules simply requires checking that the expected property is returned by the TPM2 : 
in lib/tpm2_nv_util, 
```
static inline tool_rc tpm2_util_nv_max_buffer_size(ESYS_CONTEXT *ectx,
        UINT32 *size) {

    /* Get the maximum read block size */
    TPMS_CAPABILITY_DATA *cap_data;
    TPMI_YES_NO more_data;
    tool_rc rc = tpm2_getcap(ectx, TPM2_CAP_TPM_PROPERTIES,
            TPM2_PT_NV_BUFFER_MAX, 1, &more_data, &cap_data);
    if (rc != tool_rc_success) {
        return rc;
    }

+   if ( cap_data->data.tpmProperties.tpmProperty[0].property == TPM2_PT_NV_BUFFER_MAX ) {
        *size = cap_data->data.tpmProperties.tpmProperty[0].value;
+   } else {
+       /* TPM2_PT_NV_BUFFER_MAX is not part of the module spec */
+       *size = NV_DEFAULT_BUFFER_SIZE;
+   }

    free(cap_data);

    return rc;
}
```

[1] _Trusted Platform Module Library Specification, Family “2.0”, Level 00, Revision 01.38 – September 2016, Part 1 Archictecture_, Change History, Page iii
> Revision 99
> [...]
> Added TPM_PT_NV_BUFFER_MAX, the maximum data size in an NV write

[2]  _Trusted Platform Module Library Specification, Family “2.0”, Level 00, Revision 01.38 – September 2016, Part 3 Commands_, 30.2 TPM2_GetCapability, Page 340
> The capabilityparameter  determines  the  category  of  data  returned.  The propertyparameter  selects  the first value of the selected category to be returned. If there is no property that corresponds to the value of property, the next higher value is returned, if it exists.

**Comment by idesai** [comment]
@dcpi8990 thanks! There is a [PR](https://github.com/tpm2-software/tpm2-tools/pull/1970) for this.
