### ISSUE TITLE
Obtain supported RSA sizes from TPM

### ISSUE THREAD

**Issue by dmgstz** [tpm2-software/tpm2-tools#1961]
I would like to obtain the RSA bitsizes (1024, 2048, 3072...) that a TPM supports from the chip itself and I was wondering if a TPM contains this information somewhere, perhaps in some capability. I am able to obtain the ECC curves supported by the TPM chip (reading the capabilities) but no luck yet with the key sizes for RSA.

From the TCG specs (quoted below), the TPM should support at least 2048 bits RSA, but it also mentions that the reference implementation also supports 3072 bits, so the question really is whether the TPM has a capability or a similar setting that can be read via SPI to obtain the supported RSA bit sizes.

```
A TPM that supports RSA should support a public modulus size of at least 2,048 bits. Support for other key
sizes is permitted.

NOTE 1 The reference implementation supports key sizes of 1024, 2048, and 3072.
```

**Comment by idesai** [comment]
@dmgstz there is a tool for that. You can do ["tpm2_testparms rsa2048"](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_testparms.1.md)
