### ISSUE TITLE
No package 'tss2-esys' found

### ISSUE THREAD

**Issue by shape2100** [tpm2-software/tpm2-tools#1964]
tpm2-tss2 had been built.
When I build tpm2-tools with the command: ./configure
Error:
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for TSS2_FAPI... no
checking for TSS2_ESYS_3_0... no
checking for TSS2_ESYS_2_3... no
configure: error: Package requirements (tss2-esys >= 2.3.0) were not met:

No package 'tss2-esys' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

What happied? Yes, you lost tss2-esys.pc file in OS. So,the command can solve the problem:
cp lib/tss2-*.pc /usr/share/pkgconfig/

And run ./configure again. Lucky.

**Comment by idesai** [comment]
Please pass the intended installation path to configure using prefix.
