### ISSUE TITLE
How can I use TPM with firmware revision 1.16 and 1.38?

### ISSUE THREAD

**Issue by shape2100** [tpm2-software/tpm2-tools#1965]
I have 2 TPMs. It's firmware revision is 1.16. Another is 1.38.
How can I use them with a software now?
OS: centos 7.5
 Thanks your help.

**Comment by idesai** [comment]
In general, the tpm2-software is intended for TPM2 devices of all specifications. They are tested against a simulator at spec v 1.38. If you have questions about the TPM2 from a specific manufacturer, please use the [mailing-list](https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/) for additional help.
