### ISSUE TITLE
How to use tpm2_getrandom() as API and create a C library

### ISSUE THREAD

**Issue by Muthukumar-S1979** [tpm2-software/tpm2-tools#1971]
Hi ,
I have sample to use '[tpm2tss_genkey](https://github.com/tpm2-software/tpm2-tss-engine/blob/master/src/tpm2tss-genkey.c)' command line executable as 'tpm2tss_rsa_genkey' as API and created a C library and get the 'priveteKey' as return value inside my application .

Similarly, is there any way to use "tpm2_getrandom' executable as API and create a C library for my application to get the 'random number' from TPM. 

Tried using below code snippet from [tpm2_tools/tpm2_getrandom.c](https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_getrandom.c) to achieve my above requirement:

static tpm_random_ctx ctx;
static tool_rc get_random_and_save(ESYS_CONTEXT *ectx) {

TPM2B_DIGEST *random_bytes;
tool_rc rc = tpm2_getrandom(ectx, ctx.num_of_bytes, &random_bytes);
if (rc != tool_rc_success) {
        return rc;
}
...
}
But am getting below "undefined reference" error
**undefined reference to `tpm2_getrandom'**

I believe this function 'tpm2_getrandom' API was not defined in any of the library , Let me know what am i doing wrong here.

REF : Below is my 'ldd tpm2_getrandom'
root@muthu-VB:~/work/tpm_dkr_install/tpm/tpm2-tools# ldd tools/tpm2_getrandom
	linux-vdso.so.1 (0x00007ffdd857f000)
	libtss2-esys.so.0 => /usr/local/lib/libtss2-esys.so.0 (0x00007fb2eb821000)
	libtss2-mu.so.0 => /usr/local/lib/libtss2-mu.so.0 (0x00007fb2eb5dd000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fb2eb112000)
	libtss2-tctildr.so.0 => /usr/local/lib/libtss2-tctildr.so.0 (0x00007fb2eaf0a000)
	libtss2-rc.so.0 => /usr/local/lib/libtss2-rc.so.0 (0x00007fb2ead02000)
	libtss2-sys.so.0 => /usr/local/lib/libtss2-sys.so.0 (0x00007fb2eaad5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb2ea6e4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb2ea4e0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb2ea2c1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb2ebce3000)

NOTE : I have included all above libraries (except pthread and vdso) in my makefile.

OBJDUMB : objdump -d /home/muthu/work/tpm_dkr_install/tpm/tpm2-tools/lib/libcommon.a > obj_dmp_libcommon
Seems i could find the 'disassemble' of libcommon.a , where i could see the tpm2_getrandom as reference.
I tried to dig in to tpm2_tools/Makefile and found that "libcommon.a" was included in every tool execution compilation . Do i need to include this "libcommon.a" in to my Makefile ?

Looking forward to your reply.
BR,
Muthukumar

**Comment by williamcroberts** [comment]
`tpm2_getrandom` is a function internal to tpm2_tools project as well as the name of a tool generated by the tpm2-tools project. Their is a static library, that defines that functions, but you shouldn't be using that. Its not considered public API.

If you want to call tpm2_getrandom as an executable, you can use the popen family of routines. This lets you call executables.

You could, ideal, just call one of the tpm2-tss library functions and link with the proper library:
- [(good) Tss2_Sys_GetRandom](https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_sys.h#L682)
- [(better) Esys_GetRandom](https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_esys.h#L1015)
- [(best) Fapi_GetRandom](https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_fapi.h#L105)

These questions are best answered on the mailing list:
https://lists.01.org/postorius/lists/tpm2.lists.01.org/

**Comment by williamcroberts** [comment]
Closing, these issues are better asked on the mailing list.

**Comment by Muthukumar-S1979** [comment]
> `tpm2_getrandom` is a function internal to tpm2_tools project as well as the name of a tool generated by the tpm2-tools project. Their is a static library, that defines that functions, but you shouldn't be using that. Its not considered public API.
> 
> If you want to call tpm2_getrandom as an executable, you can use the popen family of routines. This lets you call executable. See http://man7.org/linux/man-pages/man3/popen.3.html
> 
> ```c
> #include <stdio.h>
> 
> int main(int argc, char *argv[]) {
>     FILE *fp = popen("tpm2_getrandom --hex 4", "r");
> 
>     char buf[1024] = { 0 };
>     char *rand_hex = fgets(buf, sizeof(buf), fp);
> 
>     printf("%s\n", rand_hex);
> 
>     return 0;
> }
> ```
> 
> ```shell
> gcc -o go a.c
> ./go
> f7c64033
> ```
> 
> You could, ideal, just call one of the tpm2-tss library functions and link with the proper library:
> 
> * [(good) Tss2_Sys_GetRandom](https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_sys.h#L682)
> * [(better) Esys_GetRandom](https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_esys.h#L1015)
> * [(best) Fapi_GetRandom](https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_fapi.h#L105)
> 
> These questions are best answered on the mailing list:
> https://lists.01.org/postorius/lists/tpm2.lists.01.org/

Thanks a lot @williamcroberts  for your quick response.  Regarding your sample code , i cant able to use linux 'system' call or popen call to trigger the executable. Basically its an limitation for me to use these two methds.

Coming to the below 3 methods , i was quite interesting and i have tried last two (Esys_GenRandom and Fapi_GetRandom() i could able to link it to my app with respective library and my application is compiled properly . But when i try to run it , am getting 'context' set will NULL (refer below error log for more info) . Can you please guide me how and what to fill in the 'context' argument .

ERROR:fapi:src/tss2-fapi/api/Fapi_GetRandom.c:66:Fapi_GetRandom() context is NULL: BAD_REFERENCE 
Get Random Number got Failed , the reason has been shared below
Failure reason : context or data is NULL

> * [(good) Tss2_Sys_GetRandom](https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_sys.h#L682)
> * [(better) Esys_GetRandom](https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_esys.h#L1015)
> * [(best) Fapi_GetRandom](https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_fapi.h#L105)

**Comment by williamcroberts** [comment]
Here is a full program with FAPI and ESAPI implementations.

```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <tss2/tss2_esys.h>
#include <tss2/tss2_fapi.h>
#include <tss2/tss2_rc.h>

void random_fapi(void) {

	FAPI_CONTEXT  *context = NULL;
	TSS2_RC rc = Fapi_Initialize(
	    &context,
	    NULL);
	if (rc != TSS2_RC_SUCCESS) {
		fprintf(stderr, "Fapi_Initialize: %s\n", Tss2_RC_Decode(rc));
		exit(1);
	}

	/*
	 * This is typically done once via the tpm2-tools tool: tss2_provision
	 *
	 * So this may fail, because it's already been provisioned. SO just log a warning
	 * and plod ahead....
	 */
	rc = Fapi_Provision(context, NULL, NULL, NULL);
	if (rc != TSS2_RC_SUCCESS) {
		fprintf(stderr, "WARN: Fapi_Provision: %s\n", Tss2_RC_Decode(rc));
	}

	uint8_t *bytes = NULL;
	rc = Fapi_GetRandom(context, 8, &bytes);
	if (rc != TSS2_RC_SUCCESS) {
		fprintf(stderr, "Fapi_GetRandom: %s\n", Tss2_RC_Decode(rc));
		exit(1);
	}

    size_t i;
    for (i = 0; i < sizeof(bytes); i++) {
        printf("%02x", bytes[i]);
    }
    printf("\n");

    Fapi_Free(bytes);

	Fapi_Finalize(&context);
}

void random_esys(void) {

	ESYS_CONTEXT *context = NULL;
	TSS2_RC rc = Esys_Initialize(&context, NULL, NULL);
	if (rc != TSS2_RC_SUCCESS) {
		fprintf(stderr, "Esys_Initialize: %s\n", Tss2_RC_Decode(rc));
		exit(1);
	}

	TPM2B_DIGEST *bytes = NULL;
	rc = Esys_GetRandom(context,
			ESYS_TR_NONE, ESYS_TR_NONE, ESYS_TR_NONE,
			8, &bytes);
	if (rc != TSS2_RC_SUCCESS) {
		fprintf(stderr, "Esys_GetRandom: %s\n", Tss2_RC_Decode(rc));
		exit(1);
	}

    size_t i;
    for (i = 0; i < bytes->size; i++) {
        printf("%02x", bytes->buffer[i]);
    }
    printf("\n");

    Esys_Free(bytes);

	Esys_Finalize(&context);
}

int main(int argc, char *argv[]) {

	if (argc == 1 || strcmp(argv[1], "esapi")) {
		random_esys();
	}

	if (argc == 1 || strcmp(argv[1], "fapi")) {
		random_fapi();
	}

	return 0;
}
```

To build it:
```bash
gcc -o go main.c -ltss2-esys -ltss2-fapi -ltss2-rc
```

**Comment by Muthukumar-S1979** [comment]
Thanks a lot @williamcroberts you are the best.
I could able to implement both fapi and esys. esys is working as expected but am getting below error in fapi code . Not sure why the below error has been thrown . 
My env is running all my test in simulator and the s/w that are running at background are shared below 
1) ./tpm2_server (at back ground)
2) running dbus at background using command - "dbus-daemon --system --nofork --nopidfile&"
3) running abrmd at backroung using command -  "tpm2-abrmd --tcti="mssim:host=localhost,port=2321" --allow-root"

Inside gen_RandomKey_fapi() Api
ERROR:fapi:src/tss2-fapi/ifapi_io.c:419:ifapi_io_dirfiles() ErrorCode (0x0006000a) Could not open directory: /usr/etc/tpm2-tss/fapi-profiles/ 
ERROR:fapi:src/tss2-fapi/ifapi_profiles.c:75:ifapi_profiles_initialize_async() Reading profiles from profiles dir ErrorCode (0x0006000a) 
ERROR:fapi:src/tss2-fapi/api/Fapi_Initialize.c:272:Fapi_Initialize_Finish() Read profile ErrorCode (0x0006000a) 
Fapi_Initialize: fapi:IO failure

Am i missing some thing for 'fapi' to be running ?
Looking forward to your valuable reply.

BR,
Muthukumar

**Comment by williamcroberts** [comment]
No idea, maybe @AndreasFuchsSIT will know.

**Comment by kuldeepmarker-eaton** [comment]
@williamcroberts I tried the example code to test ftpm but I am getting bitbake build error. I have integrated TCG-TSS stack with ST OpenSTLinux and I am able to validate the stack using tpm2-tools. So could you share a yocto recipe which can be used to build the code you have provided.

**Comment by williamcroberts** [comment]
Unfortunately no because I don't use yocto or know anything about it's build system.

**Comment by kuldeepmarker-eaton** [comment]
@AndreasFuchsTPM I have gone through some PPT provided by you where you have highlighted use of FAPI and Esys API. I am also trying to use similar API. In my case I am using yocto recipe to build the source code where I am facing problem to build it. Could you share an example recipe which can suggest necessary dependency needed to build it.
