### ISSUE TITLE
ci: coverity scan not working

### ISSUE THREAD

**Issue by pdxjohnny** [tpm2-software/tpm2-tools#1976]
Looking at [the last build submitted on the coverity scan branch on travis](https://travis-ci.org/github/tpm2-software/tpm2-tools/builds/669879418)

The logs show that the following if statement is always evaluating to `true`.

https://github.com/tpm2-software/tpm2-tools/blob/3bd466cae04eef2087c0ae8eb706c7d9bf3f1052/.ci/travis.run#L28-L33

The first thing I'd recommend is doing `set -x` at the top of `.ci/travis.run`, so that you can see which part of that statement is the issue.

My guess is `COVERITY_RUN` is never being set to `true`.

Probaly need something at the top of `.ci/travis.run` to the similar to

```bash

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "x${CURRENT_BRANCH}" == "xcoverity_scan" ]; then
  COVERITY_RUN="true"
fi
```

Ping @idesai @williamcroberts

**Comment by williamcroberts** [comment]
@idesai I thought we discussed this approach, did you to try this? Did you get anywhere with it? I just looked at travis settings to see if COVERITY_RUN was enabled on the coverity scan branch it wasn't set.So I just set in Travis and then set it to filter out DOCKER_TAG so it only runs on ubuntu-18.04.

Ill report back with my results.

**Comment by williamcroberts** [comment]
So it seems to have gotten from travis to coverity OK. And the only build was submitted from ubuntu-18.04.

See build: https://travis-ci.org/github/tpm2-software/tpm2-tools/jobs/673463500

```
Emitted 154 C/C++ compilation units (100%) successfully
154 C/C++ compilation units (100%) are ready for analysis
The cov-build utility completed successfully.
Collecting Coverity data for submission
Submitting data to Coverity
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4141k  100    30  100 4141k     21  2933k  0:00:01  0:00:01 --:--:-- 2933k
Build successfully submitted.
The command "./.ci/travis.run" exited with 0.
Done. Your build exited with 0.
```

**Comment by williamcroberts** [comment]
And I got a confirmation email from coverity that its uploaded, and results are available. Ill set up a PR with my patch on master.
