### ISSUE TITLE
creating "AES" key using TPM API

### ISSUE THREAD

**Issue by Muthukumar-S1979** [tpm2-software/tpm2-tools#1978]
Hi @williamcroberts ,

I just want to create a "AES key" using TPM , i could find the below sample of RSA key generation using [tpm2tss_rsa_genkey](https://github.com/tpm2-software/tpm2-tss-engine/blob/master/src/tpm2tss-genkey.c)() API . Could you help me on sharing the API or sample code block that helps me to generate "AES based key" using TPM ?   

rsa = RSA_new();
    if (!rsa) {
        ERR("out of memory\n");
        BN_free(e);
        return NULL;
    }
    if (!tpm2tss_rsa_genkey(rsa, opt.keysize, e, opt.password, opt.parent)) {
        BN_free(e);
        RSA_free(rsa);
        ERR("Error: Generating key failed\n");
        return NULL;
    }

**Comment by williamcroberts** [comment]
Again, coding help go to the mailing list (it's in the README.md file). The routine tpm2tss_rsa_genkey() is in the tpm2-tss-engine and is not public API. What you want is `Esys_Create`, with the public template filled in for an AES key.

Or you can use tpm2-tools `tpm2_create`. See the manpages for details. If you get stuck, go to the mailing list.
