### ISSUE TITLE
Tool : tpm2_nvwrite () & tpm2_nvread() API(s)  usage as library

### ISSUE THREAD

**Issue by Muthukumar-S1979** [tpm2-software/tpm2-tools#1979]
Hi @williamcroberts ,

I tried using tpm2_nvwrite() API as part of my application , referred the [sample code](https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_nvwrite.c) shared below  . Since tpm2_nvwrite() is an utility function , i couldn't able to use it as API inside my application. Its throwing me error like 'tpm2_nvwrite() undefined.."
Could you help how to achieve "tpm2_nvwrite()" functionality via application , is there any other TPM, TSS_ESYS API ,etc... does this for me. 

static tool_rc nv_write(ESYS_CONTEXT *ectx) {

    TPM2B_MAX_NV_BUFFER nv_write_data;
    UINT16 data_offset = 0;

if (ctx.cp_hash_path) {
        nv_write_data.size = ctx.data_size;
        memcpy(nv_write_data.buffer, &ctx.nv_buffer, ctx.data_size);
        LOG_WARN("Calculating cpHash. Exiting without performing write.");
        TPM2B_DIGEST cp_hash = { .size = 0 };
        tool_rc rc = tpm2_nvwrite(ectx, &ctx.auth_hierarchy.object, ctx.nv_index,
                &nv_write_data, ctx.offset, &cp_hash);
        if (rc != tool_rc_success) {
            LOG_ERR("CpHash calculation failed!");
            return rc;
        }

...
...
...
}

**Comment by williamcroberts** [comment]
Please stop opening tickets for coding help, please go to the mailing list.

You can't use the tpm2-tools projects code. Only the executable tools are considered usable for end use. You need to use the tpm2-tss project, you can use the tools as samples to figure out the tpm2-tss API.
