### ISSUE TITLE
sudo make check fails unit cases

### ISSUE THREAD

**Issue by ambicapramod** [tpm2-software/tpm2-tools#1983]
I followed the instruction in the doc as follows 

git clone https://github.com/tpm2-software/tpm2-tools.git
cd tpm2-tools
./bootstrap
./configure --enable-unit
make check

I see almost all unit cases failed. I'm having fTPM (intel's ptt) What could go wrong here?
log:

[test-suite.log](https://github.com/tpm2-software/tpm2-tools/files/4491748/test-suite.log)

**Comment by AndreasFuchsSIT** [comment]
Same as here https://github.com/tpm2-software/tpm2-abrmd/issues/715

```
./test/unit/test_string_bytes: error while loading shared libraries: libtss2-esys.so.1: cannot open shared object file: No such file or directory
FAIL test/unit/test_string_bytes (exit status: 127)
```
You somehow removed libtss2-esys.so.1 from the library search path...

```
/home/intel/tpm2-tools/test/integration/helpers.sh: line 286: tpm_server: command not found
```
You are lacking tpm_server that is needed as mentioned here:
https://github.com/tpm2-software/tpm2-tools/blob/master/doc/INSTALL.md#optional-dependencies

Please have a look at the complete documentation and also at the test-suit.log before posting, because sometimes it's obviously some error on the local setup.

**Comment by ambicapramod** [comment]
I have fTPM , why would I run TPM simulator for tpm_server?

**Comment by AndreasFuchsSIT** [comment]
The test suit is designed to run against a simulator.

Of course you can run the installed programs themselves against the fTPM.

**Comment by williamcroberts** [comment]
> I have fTPM , why would I run TPM simulator for tpm_server?

as @AndreasFuchsSIT, theyre built to run against the simulator.

The problem with wild TPMs is that we don't know how they are configured, what the users level of access is to them (many regular users do not have the owner hierarchy password for example), what algorithms it supports, so the unit tests are for making sure our code works, not your TPM. In fact running the test code on the TPM could damage NV memory by excessive writes, it could lockout your TPM, etc.

Also, running the make file and test code as root, could hose your system. Perhaps a wild rm -rf command as root for example.

You need to run against the simulator with tpm2-abrmd installed and talking to the simulator for the make check to work.
