### ISSUE TITLE
./tpm2_pcrread giving error

### ISSUE THREAD

**Issue by ambicapramod** [tpm2-software/tpm2-tools#1984]
when I run ./tpm2_pcrread, it is showing all sha256 PCR banks, but also giving the error message before

```
* (process:22818): CRITICAL **: 22:34:47.905: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'com.intel.tss2.Tabrmd': timed out (service_start_timeout=25000ms)
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7f47beeb04f0 failed with a0008
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-abrmd
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0

```
How to resolve this??

**Comment by williamcroberts** [comment]
It must be failing to start up tpm2-abrmd, do you have that installed? Then it's probably defaulting to another tcti, like the device tcti. Do you have a physical tpm on your device? Do you have the path /dev/tpmrm0?

**Comment by idesai** [comment]
While in general using a resource manager, either /dev/tpmrm0 or the tpm2-abrmd is a good idea, You can also run the tpm command bypassing tpm2-abrmd with ` tpm2_pcrread -T device:/dev/tpmrm0`

**Comment by idesai** [comment]
Please re-open if the above solutions and suggestions do not resolve the issue.
