### ISSUE TITLE
tpm2_takeownership alternative

### ISSUE THREAD

**Issue by rolandupm** [tpm2-software/tpm2-tools#1987]
I was reading the wiki : `https://github.com/tpm2-software/tpm2-tools/wiki/How-to-use-tpm2-tools` and saw the tpm2_takeownership command.
In the latest version of tmp2-tools it`s missing. What is the alternative? And hot to use it?

**Comment by idesai** [comment]
[tpm2_changeauth](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_changeauth.1.md)
