### ISSUE TITLE
condition detect error

### ISSUE THREAD

**Issue by xyzhao2018** [tpm2-software/tpm2-tools#1989]
In the following condition in tools/tpm2_loadexternal.c, if both policy and auth are empty, then it will also set TPMA_OBJECT_USERWITHAUTH. 
Seems it is not correct. 

        pub.publicArea.objectAttributes = BASE_DEFAULT_ATTRS;
        if (!(ctx.policy && !ctx.auth)) {
            pub.publicArea.objectAttributes |= TPMA_OBJECT_USERWITHAUTH;
        }

**Comment by idesai** [comment]
> In the following condition in tools/tpm2_loadexternal.c, if both policy and auth are empty, then it will also set TPMA_OBJECT_USERWITHAUTH.
> Seems it is not correct.
> 
> ```
>     pub.publicArea.objectAttributes = BASE_DEFAULT_ATTRS;
>     if (!(ctx.policy && !ctx.auth)) {
>         pub.publicArea.objectAttributes |= TPMA_OBJECT_USERWITHAUTH;
>     }
> ```

What is the "condition detect error"?

**Comment by xyzhao2018** [comment]
I got more information from Roberts, William,  the scenario of both policy and auth are empty is covered by auth with empty password. So no condition detect error.
