### ISSUE TITLE
tss2_template argument of invalid pointer type

### ISSUE THREAD

**Issue by SECimon** [tpm2-software/tpm2-tools#1998]
I followed the Getting Started guide on https://github.com/tpm2-software/tpm2-tools/wiki/Getting-Started
I installed all packages. including the optional ones. TSS and abrmd went fine, all tests passed.
Installing the tools fails:

# ./configure --enable-unit
    - tpm2-tools: 4.2-24-ge2d41569
    - Man pages: yes
    - Unit tests: yes
    - tpm2_abrmd: yes
    - tpm_server: no
    - bash: yes
    - python: yes
    - xxd: yes
    - ss: yes
    - shasum: yes
    - mktemp: yes
    - expect: no

# make check
  CC       tools/fapi/tss2_decrypt-tss2_template.o
tools/fapi/tss2_template.c: In function ‘main’:
tools/fapi/tss2_template.c:316:39: error: passing argument 2 of ‘Fapi_SetAuthCB’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     TSS2_RC r = Fapi_SetAuthCB (fctx, auth_callback, NULL);
                                       ^~~~~~~~~~~~~
In file included from ./tools/fapi/tss2_template.h:6,
                 from tools/fapi/tss2_template.c:19:
/usr/local/include/tss2/tss2_fapi.h:663:21: note: expected ‘Fapi_CB_Auth’ {aka ‘unsigned int (*)(struct FAPI_CONTEXT *, const char *, char **, void *)’} but argument is of type ‘TSS2_RC (*)(const char *, const char *, const char **, void *)’ {aka ‘unsigned int (*)(const char *, const char *, const char **, void *)’}
     Fapi_CB_Auth    callback,
     ~~~~~~~~~~~~~~~~^~~~~~~~
tools/fapi/tss2_template.c:322:33: error: passing argument 2 of ‘Fapi_SetBranchCB’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     r = Fapi_SetBranchCB (fctx, branch_callback, NULL);
                                 ^~~~~~~~~~~~~~~
In file included from ./tools/fapi/tss2_template.h:6,
                 from tools/fapi/tss2_template.c:19:
/usr/local/include/tss2/tss2_fapi.h:676:21: note: expected ‘Fapi_CB_Branch’ {aka ‘unsigned int (*)(struct FAPI_CONTEXT *, const char *, const char **, unsigned int,  unsigned int *, void *)’} but argument is of type ‘TSS2_RC (*)(const char *, const char *, const char **, size_t,  size_t *, void *)’ {aka ‘unsigned int (*)(const char *, const char *, const char **, unsigned int,  unsigned int *, void *)’}
     Fapi_CB_Branch  callback,
     ~~~~~~~~~~~~~~~~^~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:5575: tools/fapi/tss2_decrypt-tss2_template.o] Error 1

**Comment by AndreasFuchsSIT** [comment]
Yes. That's a temporal incompatibility between tpm2-tss/master and tpm2-tools/master until https://github.com/tpm2-software/tpm2-tss/pull/1719 is merged.
Going to happen today or tomorrow, I assume.

**Comment by AndreasFuchsSIT** [comment]
https://github.com/tpm2-software/tpm2-tss/pull/1719 was merged, so it would work again now.
