### ISSUE TITLE
make check fails because of missing TPM server

### ISSUE THREAD

**Issue by SECimon** [tpm2-software/tpm2-tools#2000]
I followed the Getting Started guide on https://github.com/tpm2-software/tpm2-tools/wiki/Getting-Started
I installed all packages. including the optional ones. TSS and abrmd went fine, all tests passed.

The make check fails. In summary, 18 tests pass, 105 fail starting with test/integration/tests/abrmd_extended-sessions.sh.

How do I get the TPM server? 
Log:

tpm2-tools 4.2-24-ge2d41569: ./test-suite.log

TOTAL: 123
PASS:  18
SKIP:  0
XFAIL: 0
FAIL:  105
XPASS: 0
ERROR: 0

.. contents:: :depth: 2

FAIL: test/integration/tests/abrmd_extended-sessions

creating simulator working dir: /tmp/tpm2_test_9yhiVF
/tmp/tpm2_test_9yhiVF ~/Downloads/tpm2-tools
Switched to CWD: /tmp/tpm2_test_9yhiVF
Starting the simulator
Attempting to start simulator on port: 39562
/home/pi/Downloads/tpm2-tools/test/integration/helpers.sh: line 286: tpm_server: command not found
Could not start simulator at port: 39562
/home/pi/Downloads/tpm2-tools/test/integration/helpers.sh: line 304: kill: (1432) - No such process
Tries left: 9

**Comment by idesai** [comment]
https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm1332.tar.gz

**Comment by SECimon** [comment]
Thanks, but I already tried it. I started the server with ./tpm_server &
Still, configure says no tpm server.
And btw. if tpm server is necessary, with is in the text below and not before installing the tools?
I also have a real tpm. It seems to work as I can create for example random numbers.

**Comment by AndreasFuchsSIT** [comment]
Is the tpm_server in your PATH ? in /usr/local/bin or similar ?
You can check that by `$ which tpm_server`

**Comment by SECimon** [comment]
No it wasn't..
The errors (29) reduced:
FAIL: test/integration/tests/abrmd_policycphash.sh
FAIL: test/integration/tests/activecredential.sh
FAIL: test/integration/tests/hierarchycontrol.sh
FAIL: test/integration/tests/hmac.sh
FAIL: test/integration/tests/makecredential.sh
FAIL: test/integration/fapi/fapi-authorize-policy.sh
FAIL: test/integration/fapi/fapi-branch-select.sh
FAIL: test/integration/fapi/fapi-encrypt-decrypt.sh
FAIL: test/integration/fapi/fapi-export-key.sh
FAIL: test/integration/fapi/fapi-export-policy.sh
FAIL: test/integration/fapi/fapi-get-info.sh
FAIL: test/integration/fapi/fapi-get-platform-certificates.sh
FAIL: test/integration/fapi/fapi-get-random.sh
FAIL: test/integration/fapi/fapi-get-tpm-blobs.sh
FAIL: test/integration/fapi/fapi-key-change-auth.sh
FAIL: test/integration/fapi/fapi-nv-extend.sh
FAIL: test/integration/fapi/fapi-nv-increment.sh
FAIL: test/integration/fapi/fapi-nv-set-bits.sh
FAIL: test/integration/fapi/fapi-nv-write-authorize.sh
FAIL: test/integration/fapi/fapi-nv-write-read.sh
FAIL: test/integration/fapi/fapi-pcr-extend-read.sh
FAIL: test/integration/fapi/fapi-provision.sh
FAIL: test/integration/fapi/fapi-quote-verify.sh
FAIL: test/integration/fapi/fapi-seal-unseal.sh
FAIL: test/integration/fapi/fapi-set-get-app-data.sh
FAIL: test/integration/fapi/fapi-set-get-certificate.sh
FAIL: test/integration/fapi/fapi-set-get-description.sh
FAIL: test/integration/fapi/fapi-sign-verify.sh
FAIL: test/integration/fapi/fapi-testing-template.sh

**Comment by williamcroberts** [comment]
@SECimon what are the logs for the current test? Notably one from the:
- pick a  fapi test
- test/integration/tests/abrmd_policycphash.sh
- test/integration/tests/activecredential.sh
- test/integration/tests/hierarchycontrol.sh

I wonder if it's ESYS3_0 handle issue

**Comment by AndreasFuchsSIT** [comment]
Yep, looks like a ESYS_3_0 FAPI_3_0 version mismatch error.

Could you provide the test-suit.log file and also the commit ids of tpm2-tss and tpm2-tools that you use ?

**Comment by SECimon** [comment]
tpm2-tools commit ID: e2d415692c2190a51d9948478c673d3983576fcf
tpm2-tss commit ID: [e0636dd6fbec4f286cc908117ecef4d820a50f79](https://github.com/tpm2-software/tpm2-tss/commit/e0636dd6fbec4f286cc908117ecef4d820a50f79)

[test-suite.log](https://github.com/tpm2-software/tpm2-tools/files/4608004/test-suite.log)

**Comment by fearTheUnknown** [comment]
@SECimon, in you "test-suite.log" i see the following error line:
./test/integration/fapi/fapi-testing-template.sh: line 25: expect: command not found

Could you help to install the "expect" command in your distribution?

- in Debian and Ubuntu: 

`sudo apt install expect`

- in RHEL/CentOS: 

`yum install expect`

By the way, you did check for the "tpm_server" using `which tpm_server` command and it is not available right?
Then i would recommend that you copy the "tpm_server" to a folder in $PATH environment variable. In my case, it is "/usr/local/bin", please use the following command:

`sudo cp tpm_server /usr/local/bin/`

Now, please check if the "tpm_server" can be seen in the $PATH using the `which tpm_server` command again.
After this step, please help to re-run the test again to see if all test cases passed. Please type the folllowing commands in the "tpm2-tools" directory to start the test again:

`make check -j$(nproc)`

Hope this can somehow help you.
