### ISSUE TITLE
4.2.1 - release activities

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#2007]
Backport anything you want to this release, update the changelog and roll RC0

**Comment by AndreasFuchsSIT** [comment]
Maybe we should backport https://github.com/tpm2-software/tpm2-tools/pull/1995 as well.
Otherwise 4.2.x will not run against tpm2-tss 3.0

**Comment by williamcroberts** [comment]
> Maybe we should backport #1995 as well.
> Otherwise 4.2.x will not run against tpm2-tss 3.0
> 
> P.S. 4.1.x is not affected, since it does not contain fapi-CLIs.

On https://github.com/tpm2-software/tpm2-tools/pull/2006

**Comment by williamcroberts** [comment]
Also need PR #2014

**Comment by williamcroberts** [comment]
I forgot the "Fix error: ‘for’ loop initial declarations are only allowed in C99 mode" in the CHANGELOG.md, so when the RC1 or the actual release occurs, update it then.

**Comment by williamcroberts** [comment]
> I forgot the "Fix error: ‘for’ loop initial declarations are only allowed in C99 mode" in the CHANGELOG.md, so when the RC1 or the actual release occurs, update it then.

Done in: f90c05a69b
