### ISSUE TITLE
4.2 fail to build because of 'for' loop initial declarations which is only allowed in C99

### ISSUE THREAD

**Issue by danielcongxu** [tpm2-software/tpm2-tools#2011]
Recently I decide to upgrade my tpm2_tools from 4.1.1 to 4.2, and I found it failed to build per the instructions in INSTALL.md. I ran with the following commands:

./bootstrap && ./configure --disable-hardening && make

And it reported the following errors:
****************************************************
CC       lib/lib_libcommon_a-tpm2_eventlog.o
lib/tpm2_eventlog.c: In function ‘foreach_digest2’:
lib/tpm2_eventlog.c:40:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < count; ++i) {
     ^
lib/tpm2_eventlog.c:40:5: note: use option -std=c99 or -std=gnu99 to compile your code
lib/tpm2_eventlog.c: In function ‘specid_event’:
lib/tpm2_eventlog.c:243:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < sizeof(event->digest); ++i) {
     ^
make: *** [lib/lib_libcommon_a-tpm2_eventlog.o] Error 1
*******************************************************

I know it could be resolved by appending -std=c99 in CFLAGS. But I just felt weired seeing this. Will it be fixed, or I made anything wrong with the build command?

**Comment by williamcroberts** [comment]
I have PR #2014 staged on 4.2.X for a minor bugfix release of 4.2.1
