### ISSUE TITLE
4.2.x: Bump to tpm2-tss >= 2.4.0

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tools#2022]
Because of Esys_GetSysContext()

https://github.com/tpm2-software/tpm2-tools/blob/4d528738144524d713a28816d6738202950bbe24/configure.ac#L53

**Comment by williamcroberts** [comment]
4.2.1-RC1

**Comment by williamcroberts** [comment]
Done in: 98ecfa14eb3c416c

**Comment by osresearch** [comment]
When does the branch get merged to master? `configure` is still checking for tss2-esys 2.3.0, so building a fresh checkout is broken on ubuntu 20.04 with the default 2.3.2 system package.

**Comment by williamcroberts** [comment]
Merged: db83aee55b0e

Normally we just cherry-pick what we want, but now that the branches have less divergent, I just went ahead and merged it.
