### ISSUE TITLE
./tools/tpm2_getrandom 4 is generating garbage value in Ubuntu 20.04

### ISSUE THREAD

**Issue by Muralik2233** [tpm2-software/tpm2-tools#2023]
Followed https://github.com/tpm2-software/tpm2-tools/blob/master/doc/INSTALL.md steps
Not seen in Ubuntu 18.04

**Comment by AndreasFuchsSIT** [comment]
Would you mind sharing some more detail in which way you're seeing garbage ?
Also, which version of the tools are you using ?

Because as you can see here, it works fine against Ubuntu-20.04 in travis-ci:
https://github.com/tpm2-software/tpm2-tools/blob/4d528738144524d713a28816d6738202950bbe24/.travis.yml#L12
https://travis-ci.org/github/tpm2-software/tpm2-tools/builds/686358749

**Comment by Muralik2233** [comment]
![tools_getrand - Copy](https://user-images.githubusercontent.com/65332897/81908180-81262980-95e6-11ea-955b-418078334235.JPG)

Please find the attached image.Used master branch version of Tpm2-tools

**Comment by AndreasFuchsSIT** [comment]
Looks like random bytes in the correct amount.
Maybe try `tpm2_getrandom --hex 4` for hex output or `tpm2_getrandom | hexdump`.
Or did I miss something here ?

**Comment by williamcroberts** [comment]
Yeah tpm2_getrandom, is like `openssl rand 4` and dumps binary as the manpage states,
```
Output  defaults to stdout and binary format unless otherwise specified
with -o and --hex options respectively.
```

This was a behavioral change from 3.X to 4.X. Note that major version bumps will have some incompatibility as documented in https://github.com/tpm2-software/tpm2-tools/blob/master/doc/RELEASE.md as we follow semver.org guidelines to align with common tools, like openssl. This behavior will remain consistent with binary to stdout as the default moving forward, we have no plans on changing anything else in a non-backwards compat way moving forward. I consider 4.0 the first real release of tpm2-tools.

Also when upgrading versions, reference the Changelog for a highlevel synopsis of what changed:
  - https://github.com/tpm2-software/tpm2-tools/blob/master/doc/CHANGELOG.md#40---2019-09-09
