### ISSUE TITLE
tpm2_nvlist is not available

### ISSUE THREAD

**Issue by ambicapramod** [tpm2-software/tpm2-tools#2027]
I have installed tpm2-tools from in ubuntu 20.0 though apt install

also I have built it from source of master. still, I'm not able to see tpm2_nvlist command and also when I give command
sudo tpm2_nvdefine -x 0x1500016 -a 0x40000001 -s 64 -t 0x2000A -T device

it shows :
invalid option --x

**Comment by idesai** [comment]
To list NV indices, use [tpm2_getcap](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_getcap.1.md) instead.

Refer [tpm2_nvdefine](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_nvdefine.1.md) man page for the right options.

**Comment by williamcroberts** [comment]
@ambicapramod that should be version 4.1.1 which doesn't support -x. What was -x is now the argument... so:
tpm2_nvdefine -C o -s 64 -a "ownerread|ownerwrite"

The original attributes are:
- TPMA_NV_OWNERREAD
- TPMA_NV_OWNERWRITE
- TPMA_NV_POLICYWRITE

But you're not specifying a policy... so drop it



Which means

**Comment by ambicapramod** [comment]
@idesai but with tpm2_nvcap I won't get the details of that index, like size and algo as it lists in nvlist. Is there any other that might help?

**Comment by idesai** [comment]
> @idesai but with tpm2_nvcap I won't get the details of that index, like size and algo as it lists in nvlist. Is there any other that might help?

[tpm2_nvreadpublic](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_nvreadpublic.1.md)

**Comment by ambicapramod** [comment]
Thank you! :)
