### ISSUE TITLE
tpm2_nvwrite does not have index to write from

### ISSUE THREAD

**Issue by ambicapramod** [tpm2-software/tpm2-tools#2029]
Hi,

I'm trying to write key to index 1500016, with 4.1 tpm2_tools. 
sudo tpm2_nvwrite -x 0x1500016 -a 0x40000001 -f root.key -T device.

-x argument is not valid now. What to use I could not find proper one.

Thanks in advance

**Comment by idesai** [comment]
It is simply specified as an argument. I added some text to emphasize it in the man page in this [PR](https://github.com/tpm2-software/tpm2-tools/pull/2030).
