### ISSUE TITLE
tpm2_createak: what can be done with the private output?

### ISSUE THREAD

**Issue by osresearch** [tpm2-software/tpm2-tools#2046]
The man page for `tpm2_createak --private` or `tpm2_createak -r` says:
> The output file which contains the sensitive portion of the object, optional.

There is no documentation what this private key can be used for, nor how sensitive it is. Is it encrypted in some way? Can it be used to fake attestation signatures outside of the TPM?

**Comment by SebaMederos** [comment]
I am currently researching on this.

**Comment by williamcroberts** [comment]
> The man page for `tpm2_createak --private` or `tpm2_createak -r` says:
> 
> > The output file which contains the sensitive portion of the object, optional.
> 
> There is no documentation what this private key can be used for, nor how sensitive it is. Is it encrypted in some way? Can it be used to fake attestation signatures outside of the TPM?

Its protected by the TPM. Its encrypted and integrity checked. The algorithm is a HMAC. See 
Sections 23.2 and 11.4.3 of:
  - https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf

So its only usable by the TPM that created it, and when the primary seed for the hierarchy is rolled, lost forever. Unless you can break the cipher.

**Comment by williamcroberts** [comment]
I think I explained this, and I opened a defined bug to update the manpages better:
  - https://github.com/tpm2-software/tpm2-tools/issues/2056

Im gonna close this one.
