### ISSUE TITLE
tpm2_makecredential and ek.crt

### ISSUE THREAD

**Issue by osresearch** [tpm2-software/tpm2-tools#2047]
Does the x509 EK certificate have all of the information needed for running `tpm2_makecredential`? If so it would reduce the number of files that have to be exchanged during an attestation as well as eliminate the potential risk of an attestation with a valid `ek.crt` but with a different `ek.pub`.

**Comment by osresearch** [comment]
How do you tell if the x509 certificate matches the `TPM2B_PUBLIC` structure? As a hack my attestation script [validates the EK using openssl to read the modulus from the cert](https://github.com/osresearch/safeboot/blob/tpm2-attest/sbin/tpm2-attest#L180) and comparing it to the last 256 bytes of the `ek.pub` file, which seems fragile:

```
        mod1="$(bin2hex "$TMP/ek.pub" | tail -c 512)"
        mod2="$(openssl x509 \
                -in "$TMP/ek.crt" \
                -inform DER \
                -noout \
                -modulus \
                | cut -d= -f2 \
                | tr '[A-Z]' '[a-z]')"

        if [ "$mod1" != "$mod2" ]; then
                warn "ek.pub: $mod1"
                warn "ek.crt: $mod2"
                die "ek.crt and ek.pub have different moduli"
        fi

        warn "ek.pub: matches ek.crt!"
```

**Comment by williamcroberts** [comment]
You could get the public modulus from the PEM file and compare. You can get a pem file by tpm2_readpublic using the output and format options. It seems like a tpm2_print command option for this would be nice.

**Comment by williamcroberts** [comment]
FYI tpm2_print can now dump a TPMT_PUBLIC or a TPM2B_PUBLIC in the below PR:
  - https://github.com/tpm2-software/tpm2-tools/pull/2052

From there, you can do something like this to get a public key in a pem format:
- https://calvin.my/posts/reconstruct-rsa-public-key-from-exponent-and-modulus

However, you're original question, I don't think so. They are defined by this standard AFAIK:
  - https://trustedcomputinggroup.org/wp-content/uploads/Credential_Profile_EK_V2.0_R14_published.pdf

**Comment by idesai** [comment]
> Does the x509 EK certificate have all of the information needed for running `tpm2_makecredential`? If so it would reduce the number of files that have to be exchanged during an attestation as well as eliminate the potential risk of an attestation with a valid `ek.crt` but with a different `ek.pub`.

No, you cannot. Because the EK certificate will not have the AIK public/ name.

> How _do_ you tell if the x509 certificate matches the `TPM2B_PUBLIC` structure? As a hack my attestation script [validates the EK using openssl to read the modulus from the cert](https://github.com/osresearch/safeboot/blob/tpm2-attest/sbin/tpm2-attest#L180) and compares it to the last 256 bytes of the `ek.pub` file, which seems fragile:
> 
> ```
>         mod1="$(bin2hex "$TMP/ek.pub" | tail -c 512)"
>         mod2="$(openssl x509 \
>                 -in "$TMP/ek.crt" \
>                 -inform DER \
>                 -noout \
>                 -modulus \
>                 | cut -d= -f2 \
>                 | tr '[A-Z]' '[a-z]')"
> 
>         if [ "$mod1" != "$mod2" ]; then
>                 warn "ek.pub: $mod1"
>                 warn "ek.crt: $mod2"
>                 die "ek.crt and ek.pub have different moduli"
>         fi
> 
>         warn "ek.pub: matches ek.crt!"
> ```

You could also dump the EK public from certificate using OpenSSL and then use tpm2_readpublic to dump the EK in PEM and then compare the PEM files.
