### ISSUE TITLE
tpm2_makecredential man page improvements

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#2051]
The man page sucks, it needs better textual description of how it gets used in the big picture, and make an example of a simple attestation.

**Comment by osresearch** [comment]
Glad it's not just me that found it hard to make sense of this tool...

My [`tpm2-attest`](https://safeboot.dev/attestation/) script can now handle the TPM2 key generation, quote signing, quote validation, EK validation, sealing and unsealing as part of the [safeboot project](https://safeboot.dev/). The lack of examples in the manpages meant that I had to spend some quality time with hex dumps, the various source tree, and gdb to figure out what some of the tools wanted.

**Comment by williamcroberts** [comment]
> Glad it's not just me that found it hard to make sense of this tool...
> 
> My [`tpm2-attest`](https://safeboot.dev/attestation/) script can now handle the TPM2 key generation, quote signing, quote validation, EK validation, sealing and unsealing as part of the [safeboot project](https://safeboot.dev/). The lack of examples in the manpages meant that I had to spend some quality time with hex dumps, the various source tree, and gdb to figure out what some of the tools wanted.

That's how I spend my day
