### ISSUE TITLE
tpm2_checkqoute: support EC

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#2053]
tpm2_checkqoute is currently hardcoded to RSA, support EC.

Also while there fix the options:
tpm2_checkqoute should take as inputs either:
  - public key as a pem + scheme
  - the public output from things like tpm2_create aka a marshalled TPM2B_PUBLIC
   - Optional -G because shceme might be NULL on the key.

We need to keep backwards compat, so mark -g as deprecated, and remove it from the manpage, but keep it (and well comment it), that -g means RSASSA + halg. We should use -G with the algorithm parsing.

**Comment by williamcroberts** [comment]
halg is needed for plain signatures, so don't remove -g. -g only becomes superfluous when you're using a tpmt signature scheme that has all the metadata. So users can not specify it for tpmt signatures, but if they do, we will check it and warn if they pick wrong and use the one we know works, because tpmt told us it did.

**Comment by williamcroberts** [comment]
No need for -G, we can figure out the signature algorithm via the EVP things. They only thing they care about is digest and signature.

**Comment by williamcroberts** [comment]
@osresearch this should get you further along with using EC AK for quote/checkquote.

**Comment by osresearch** [comment]
This works for me!  Thanks for adding the flexible file formats in verifying the quotes - it removes the need to send the `ak.pem` file at all.
