### ISSUE TITLE
tpm2_makecredential: add better name support.

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#2054]
tpm2_makecredential needs either:
  - template file (nothing more)
  - pem + name + symmetric details (scheme)

Right now it always required name, which we have the template file, we can generate name. Make -n optional.

**Comment by idesai** [comment]
What this ideally should look like is **tpm2_loadexternal** followed by **tpm2_makecredential** using the key context generated by **tpm2_loadexternal**.  So adding a **-c** option to load key context is another option.
PS: the **-e** should actually be **-u** since it is a public key, so adding that as an additional short option may also be a good idea.

**Comment by idesai** [comment]
Calculating the name is only going to be possible with template.
Loading the PEM with name and symmetric-details is an interesting one. It actually also needs the rest of key attributes to arrive at the same name — IOW we need the template, unless we can make assumptions using the TCG EK template in which case you don't need the name.

**Comment by idesai** [comment]
- [ ] Make name optional if public key for encryption is provided in tss format
- [ ] Add **-u**, **--public** as an alternative to **-e**, **--encryption-key** for specifying the public key
- [ ] Add **-c**, **--context** option to use key handles loaded by loadexternal
- [ ] Add PEM loading support and assume TCG EK template and further use the template to calculate name. Add **-G** option to know the key type: RSA/ ECC.

**Comment by idesai** [comment]
> * [ ]  Make name optional if public key for encryption is provided in tss format
> * [ ]  Add **-u**, **--public** as an alternative to **-e**, **--encryption-key** for specifying the public key
> * [ ]  Add **-c**, **--context** option to use key handles loaded by loadexternal
> * [ ]  Add PEM loading support and assume TCG EK template and further use the template to calculate name. Add **-G** option to know the key type: RSA/ ECC.

@osresearch @williamcroberts does that look reasonable?

**Comment by idesai** [comment]
> tpm2_makecredential needs either:
> 
> * template file (nothing more)
> * pem + name + symmetric details (scheme)
> 
> Right now it always required name, which we have the template file, we can generate name. Make -n optional.

In this comment, If by template it is implied the input public key, then the name calculation with this public is not useful or relevant. What we need in makecredential is the primary—EKpublic and the child—AIKname.
