### ISSUE TITLE
Tools should have a lookup table for well known constants

### ISSUE THREAD

**Issue by osresearch** [tpm2-software/tpm2-tools#2058]
Instead of having to put random constants into shell scripts, the various `tpm2_*` tools should have their own lookup table of the well known values. These examples might as well be programming in assembly:

```
tpm2_createek -c 0x81010009
tpm2_nvundefine 0x1500018 -C 0x40000001
tpm2_nvread 0x01c00002
tpm2_policysecret --object-context "0x4000000b"
tpm2_evictcontrol --object-context "0x8000001" 
```

**Comment by williamcroberts** [comment]
They do, with the exception of persistent handles.

`tpm2_createek -c 0x81010009`
0x81010009 is a persistent handle. The spec seems to say you should keep these transient, but you can persist them. See https://trustedcomputinggroup.org/wp-content/uploads/RegistryOfReservedTPM2HandlesAndLocalities_v1p1_pub.pdf see 2.3.2
So if you want to persist it, you need to pick the location.

```bash
# defaults to owner hierarchy, but you could use `-C o` instead of -C 0x40..01
# This will define nv index slot 0, and remove it.
tpm2_nvdefine 0
tpm2_nvundefine 0
```
But you don't even need the argument to define, it will just find the first empty slot and use it:
```bash
tpm2_nvdefine
nv-index: 0x1000000
tpm2_nvundefine 0
```
Same goes for read, you can just use slot number, which is the offset from the first index, no need for the whole address.

This:
```bash
tpm2_policysecret --object-context "0x4000000b"
```
can be replaced by this:
```bash
tpm2_policysecret --object-context e
```
Note that its a prefix match, so it could have been endorsement or just e, or anything inbetween.

I did open #2065, we can get rid of hard coded 0x40 values and replace them with nice strings.

This is a permanent handle, you need to specify it. In this case, you want to make
the persistent object at handle 0x8000001 and evict it. If you pass it a context file
for a transient object, you can have it persisted and the tool will pick the persistent handle for you.
```bash
tpm2_evictcontrol --object-context "0x8000001" 
```

The NV manpages make it clear, that its either:
```
The index is specified
as an argument and can be a raw handle or an offset value to the nv handle range
"TPM2_HR_NV_INDEX".
```
But if we missed an nv manpage, please point it out.
