### ISSUE TITLE
tpm2_createak option for ephermal attestation keys

### ISSUE THREAD

**Issue by osresearch** [tpm2-software/tpm2-tools#2059]
The attestation keys generated by `tpm2_createak` do not set the `stclear` attribute, so they can be persistent into the TPM or reloaded.  This potentially allows an attacker to use the AK to sign a quote, then reboot into an untrusted state, and use the persistent key to unseal the response from the attestation server.

If there were an option to `tpm2_createak` to set the attributes, then ephemeral attestation keys could be created with one command rather than requiring the much more verbose:

```
        tpm2_flushcontext --loaded-session

        tpm2_startauthsession >&2 \
                --session "$TMP/session.ctx" \
                --policy-session  \
        || die "tpm2_startauthsession: unable to start authenticated session"

        tpm2_policysecret >&2 \
                --session "$TMP/session.ctx" \
                --object-context "0x4000000b" \
        || die "tpm2_policysecret: unable to set context TPM_RH_ENDORSEMENT"

        warn "tpm2: creating ephemeral attestation key"
        tpm2_create >&2 \
                --parent-context "$TMP/ek.ctx" \
                --parent-auth "session:$TMP/session.ctx" \
                --key-algorithm "rsa:rsassa:null" \
                --attributes "fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|sign|stclear" \
                --public "$TMP/ak-pub.key" \
                --private "$TMP/ak-priv.key" \
        || die "tpm2_create: unable to create an attestation key"

        # have to start a new secret session to load the attestation key
        tpm2_startauthsession >&2 \
                --session "$TMP/session.ctx" \
                --policy-session  \
        || die "tpm2_startauthsession: unable to start authenticated session"

        tpm2_policysecret >&2 \
                --session "$TMP/session.ctx" \
                --object-context "0x4000000b" \
        || die "tpm2_policysecret: unable to set context TPM_RH_ENDORSEMENT"

        tpm2_load >&2 \
                --parent-context "$TMP/ek.ctx" \
                --auth "session:$TMP/session.ctx" \
                --key-context "ak.ctx" \
                --public "$TMP/ak-pub.key" \
                --private "$TMP/ak-priv.key" \
        || die "tpm2_load: unable to load attestation key"

        # output public structure so that the attestation server can compute the name of this key
        # and verify that the stclear attribute is set
        tpm2_readpublic >&2 \
                --object-context "ak.ctx" \
                --output "$TMP/ak.pub" \
                --format "tpmt" \
        || die "tpm2_readpublic: unable to display info"
```

**Comment by williamcroberts** [comment]
> The attestation keys generated by tpm2_createak do not set the stclear attribute, so they can be persistent into the TPM or reloaded. This potentially allows an attacker to use the AK to sign a quote, then reboot into an untrusted state, and use the persistent key to unseal the response from the attestation server.

Not if you set an authorization file and lock it to the PCR state:
https://github.com/tpm2-software/tpm2-tools/blob/master/man/common/authorizations.md#pcr-authorizations

However, I see a couple of issues here:
1. Why are we not setting stclear?
2. Why don't we allow a policy hash for authorization like tpm2_create(1)?
3. Why don't we support setting attributes?

The template was inherited code, I am not sure how they arrived at the template. I cant find anything on how the attestation key template should be generated.
@idesai do you know if their is a spec on that?

**Comment by idesai** [comment]
AFAIK, There is a spec for EK but not AK.
1. tpm2_createak tool is really an extension of tpm2_create for creating generic attestation identity keys. I don't see a harm in adding that attribute as an option. Although, this brings back the ever-interesting question, do we really need tpm2_createak and tpm2_createek to be separate tools or should we update the man page and tests for tpm2_createprimary and tpm2_create tool to demonstrate how endorsement keys and attestation identity keys can be created. 
2. The policy is hard-coded to satisfy/ refer the authorization of endorsement hierarchy with [Esys_PolicySecret](https://github.com/tpm2-software/tpm2-tools/blob/878625f721a63a4f7b8cca3f9bb70ac6e781886e/tools/tpm2_createak.c#L229).  Again, a hardcoding that can be questioned in the context of this ticket but is largely an option in the tpm2_create tool by default.
3. In summary, all the hardcodings with respect to policy and attributes are chosen for tpm2_createak and tpm2_createek tools to cover the most commonly applied parameters. In reality, though these are extensions of  tpm2_create and tpm2_createprimary respectively.

**Comment by osresearch** [comment]
If `tpm2_createek` / `tpm2_createak` go away and are replaced by arguments to `tpm2_create`, perhaps there can be a short-cut for the common configurations.  Having to jump through hoops for setting up sessions, etc makes the tools very challenging to use correctly.

Is the PCR policy in the authorization file set by the client or the server? It looks like `tpm2_makecredential` doesn't have a way to specify a PCR file, so I think the security depends on the client correctly setting it in `tpm2_create --policy`. Can the server verify in some way that the policy was configured?

If it is set by the client, the policy is also persistent, right? If so, can it be modified after a firmware update to record the new PCRs, or would a new persistent attestation key have to be generated as part of the firmware update?

If I'm reading the man page wrong and the authorization can be set by the server, then this would potentially allow a persistent attestation key to be used. There is still a race in that the adversary could reset the client, but they would still only gain access to the secret with `tpm2_activatecredential` if the PCRs came back in the same state. Maybe that is a problem; I have a hazy idea of some use cases where it might be undesirable to have that happen, but nothing concrete.

**Comment by idesai** [comment]
Agreed. The tpm2_createek and tpm2_createak will continue to be around to address common key configurations required for attestation. If more control on the endorsement key and attestation identity key attributes and authorization is required then one should use the tpm2_createprimary and tpm2_create tools for now until we redirect calls to tpm2_createak/tpm2_createek to tpm2_create/tpm2_createprimary.

PCR policies can be decided by the server, set by the client, and verified by the server. Verification of how the policy was set up on the client credential key is achieved by reading the public information on the credential key. This information verification step can be done at the time of makecredential.

Flexible PCR policies are possible. Look at [tpm2_policyauthorize](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_policyauthorize.1.md) or [tpm2_policyauthorizenv](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_policyauthorizenv.1.md).

Not really understanding how the attack could be successful. Only a platform with an ak whose public was chosen during makecredential can actually do the credential activation. After this handshake only the ak signed quotes are trusted by the server. And this quote would have the current PCR values.

**Comment by williamcroberts** [comment]
So whats the final synopsis to close this?

The attestor ultimately should only trust verified keys and quote state (PCR hashes checkout). So in this case, as imran points out, the quote result would fail in the second half. Do we want to add stclear to the attributes anyways? It won't hurt anything AFAICT.

**Comment by osresearch** [comment]
My preference would be to add an argument to `tpm2_createak` to add `--stclear` or `--ephemeral` to the attributes for creating ephemeral attestation keys since that is the only additional attribute that my use case requires.

Taking in a full `--attributes` string like `tpm2_create` is also possible, although perhaps more fraught with potential mistakes.

**Comment by williamcroberts** [comment]
> My preference would be to add an argument to `tpm2_createak` to add `--stclear` or `--ephemeral` to the attributes for creating ephemeral attestation keys since that is the only additional attribute that my use case requires.
> 
> Taking in a full `--attributes` string like `tpm2_create` is also possible, although perhaps more fraught with potential mistakes.

We can just add stclear to the set of attributes. But, consistency is king. I have no problem exposing the "I want these attributes". Where possible and reasonable, I want tools to be consistent in options and behavior with other tools.
