### ISSUE TITLE
tpm2-tools should have a way to decode serialized handles in a human readable format

### ISSUE THREAD

**Issue by rowanmoul** [tpm2-software/tpm2-tools#2060]
When an object is persisted with `tpm2_evictcontrol` there is an option (`-o`) to output a serialized handle file in addition to the handle being printed to stdout. This is great for future use with other `tpm2-tools`, however this handle file is binary and there doesn't seem to be a way to deserialize it and print out the handle value it contains.  
The best I can find is to list all persistent handles with `tpm_getcap` and "guess and check" with `tpm2_readpublic`.
Or perhaps the much more hacky: if you pass he handle file to `tpm2_print -t TPMS_CONTEXT` the error message just happens to contain the handle value.

**Comment by williamcroberts** [comment]
The `-o` handles are meant to be opaque pointers to the object. They are serialized ESYS_TR's, so the mapping is internal to the ESYS library. The tool outputs the raw handle as the YAML dictionary key "persistent-handle". So you just use them, and don't worry about it. As long as you use the same file every-time, you get the same object in the TPM, with name checking to make sure it wasn't swapped out. Use that with a encrypted sessions for additional validity that it is indeed the genuine object.
