### ISSUE TITLE
"make check" reports fails related integrated fapi tests

### ISSUE THREAD

**Issue by Muralik2233** [tpm2-software/tpm2-tools#2061]
![fapi_fails](https://user-images.githubusercontent.com/65332897/82903232-4aed9000-9f7e-11ea-9320-83592bc0b92f.JPG)
followed https://github.com/tpm2-software/tpm2-tools/wiki/Getting-Started
and install.md from tpm2-tools git link.in both cases observing fails in make check
OS : Ubutnu 20.04

**Comment by williamcroberts** [comment]
you should have a `test-suite.log` file, what are the contents of that? Whats the error?

**Comment by Muralik2233** [comment]
I found below information in test-suite.log
--- EOF ---

run_startup: false
./test/integration/fapi/fapi-authorize-policy.sh: line 49: expect: command not found
expect <<EOF
# Try with missing policyPath
spawn tss2_authorizepolicy --keyPath $POLICY_SIGN_KEY_PATH     --policyRef $POLICY_REF
set ret [wait]
if {[lindex \$ret 2] || [lindex \$ret 3] != 1} {
    Command has not failed as expected\n"
    exit 1
}
EOF
 on line 49 failed: 127
Shutting down
~/Music/tpm2-tools
Removing sim dir: /tmp/tpm2_test_92TARX
/home/user/Music/tpm2-tools/test/integration/helpers.sh: line 423: 39113 Killed                  $TPM2_SIM -port $tpm2_sim_port  (wd: /tmp/tpm2_test_92TARX)
/home/user/Music/tpm2-tools/test/integration/helpers.sh: line 423: 39830 Killed                  $TPM2_ABRMD $tpm2_tabrmd_opts $TPM2ABRMD_TCTI  (wd: /tmp/tpm2_test_92TARX)
FAIL test/integration/fapi/fapi-authorize-policy.sh (exit status: 1)

**Comment by williamcroberts** [comment]
looks like you need the expect command. Which is checked for at configure time. What options did you pass to configure? Im noticing an error where make check will try and run scripts even with this option disabled.

**Comment by williamcroberts** [comment]
Can you share your config.log file?

**Comment by williamcroberts** [comment]
Since this isn't a bug report, if you need support use the mailing list mentioned in the README file. Closing. If we determine it's a bug, ill re-open or file another ticket.
