### ISSUE TITLE
tpm2_pcrread is not compatible with tpm2_checkquote

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#2072]
tpm2_checkquote and tpm2_quote have a different metadata format than tpm2_pcrread. tpm2_quote includes the pcr selection information, tpm2_pcrread does not, just the hashes in order.

We should:
make tpm2_pcrread to be able to output either binary format. We will call them plain, which is the current format, or metadata, which is the quote format. We probably want to version the metadata format.

tpm2_checkquote to be able to read any format, and know what format it is by a PCR selection string. If it's pcr selection string, then the plain tpm2_pcrread is being used. If no pcr slection string then the metadata format is being used.

**Comment by williamcroberts** [comment]
@idesai you asked, "Current output from tpm2_pcrread is used between the tools so that will continue to be the default (plain) output. What should the new option be called to output PCR-selection information?"

Perhaps:

  * -f plain (current and default, just hashes)
  * -f meta (selection specifier and hashes)

I don't like the "meta" option, im open to suggestions and improvements on that.

Then in consuming tools if they:

1. Specify a PCR file without the PCR selection string, its meta.
2. Specify a PCR file with the PCR selection string, its plain.

**Comment by idesai** [comment]
2 fixes need to go in
- [ ] Enable tpm2_checkquote to read in PCR-digest data without TPML_PCR_SELECTION header and add PCR-Selection input option.
- [ ] Enable tpm2_pcrread to output TPML_PCR_SELECTION by adding an option to make this non-default choice.

**Comment by idesai** [comment]
> 2 fixes need to go in
> 
> * [x]  Enable tpm2_checkquote to read in PCR-digest data without TPML_PCR_SELECTION header and add PCR-Selection input option.
> * [ ]  Enable tpm2_pcrread to output TPML_PCR_SELECTION by adding an option to make this non-default choice.

Fix-1 through #2114

**Comment by idesai** [comment]
> > 2 fixes need to go in
> > 
> > * [x]   Enable tpm2_checkquote to read in PCR-digest data without TPML_PCR_SELECTION header and add PCR-Selection input option.
> > * [ ]   Enable tpm2_pcrread to output TPML_PCR_SELECTION by adding an option to make this non-default choice.
> 
> Fix-1 through #2114

We agreed that it is sufficient to add support for PCR data without TPML_PCR_SELECTION in the tpm2_checkquote tool, so Fix-1 should suffice to close this issue.
