### ISSUE TITLE
question: is there a way to test if a key handle (generated by tpm2tss-genkey) belongs to this TPM?

### ISSUE THREAD

**Issue by danielwangksu** [tpm2-software/tpm2-tools#2080]
I created a key handle using `tpm2tss-genkey`,  is there a way (e.g. a command) to test if a key handle (generated by tpm2tss-genkey) belongs to a certain TPM? Thanks!

**Comment by williamcroberts** [comment]
I would suggest just trying tpm2_load and see if it loads, but the issue would be that the key format is in the tss2 engine PEM format, and the tpm2-tools don't support that (yet, see https://github.com/tpm2-software/tpm2-tools/pull/1992).

I see you filled a bug on tss2-engine project, they might have a better idea, but I can't think of any. I would try our mailing list, you'll get more people looking at your question.
