### ISSUE TITLE
tpm2_create throws error with files > 128B

### ISSUE THREAD

**Issue by nellorocca** [tpm2-software/tpm2-tools#2083]
Hi,
I'm trying to seal a .pem file created with openssl but it seems that tpm2_create is not happy with files that have size > 128 bytes. In the manual I read "A sealing object allows to seal user data to the TPM, with a maximum size of 256 bytes." so that's why I'm asking you guys for help.

The step to reproduce are:
```
tpm2_createprimary -c primary.ctx
tpm2_create -C primary.ctx -u k.pub -r k.priv -i file.pem
```

The error I get is:

> WARNING:esys:../tpm2-tss-2.3.2/src/tss2-esys/api/Esys_Create.c:370:Esys_Create_Finish() Received TPM Error
> ERROR:esys:../tpm2-tss-2.3.2/src/tss2-esys/api/Esys_Create.c:120:Esys_Create() Esys Finish ErrorCode (0x000001d5)
> ERROR: Esys_Create(0x1D5) - tpm:parameter(1):structure is the wrong size
> ERROR: Unable to run tpm2_create

The pem file is 227B but I can reproduce the error for any files with size > 128B.
Any help? Thanks

**Comment by williamcroberts** [comment]
I thought it was coupled to that is set for the TPM2_PT_CONTEXT_SYM_SIZE, but that doesn't seem to be the case. Looking at the simulator code and walking through an example, `MAX_SYM_DATA` is set to 128. And it seems to be this way for both the ibmtpm1119 and ibmtpm1563 simulators.

I can't find in the spec where it actually defines this. Let me ask around. @idesai do you know?

**Comment by idesai** [comment]
The only reference in the [command-specifications-section-12-7](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part3_Commands_pub.pdf) confirms that the data cannot be more than 128 bytes.

What you can instead do is create an encryption key (optionally make it persistent), encrypt the pem data (optionally save the encrypted pem data on an NV index).

If you must use policyPCR for authentication then reference the auth policy in either tpm2_create or tpm2_nvdefine( to restrict reads) or both.

**Comment by williamcroberts** [comment]
I just updated the man page and submitted PR #2084
