### ISSUE TITLE
tpm2_startauthsession error after a few session started

### ISSUE THREAD

**Issue by p-gentili** [tpm2-software/tpm2-tools#2085]
Hi everyone,
I'm having an issue with tpm2_startauthsession with the -c parameter.

Basically I need to start a session and unseal some data using a policy. The problem is that after some succesful iteration of "(1) startauthsession (2) tpm2_policysecret (3) unseal" I get this error:

> ERROR: Esys_StartAuthSession(0x284) - tpm:handle(2):value is out of range or is not correct for the context

Since I'm using tpm2-abrmd I'm pretty sure it's not a resource problem but I'm not an expert so I'm asking you guys.

After a reboot everything is working fine for a few session and then the error comes back. What should I do in these situations? I tried to recreate the primary key or flushing the context but it's not helping.

Thanks
Paolo

**Comment by tstruk** [comment]
Might be related to this: https://github.com/tpm2-software/tpm2-abrmd/issues/719

**Comment by nellorocca** [comment]
Do you have any suggestion as workaround in the meantime? Like moving to the kernel Resource Manager could fix the problem?

**Comment by tstruk** [comment]
I'm not sure if moving to the kernel Resource Manager would solve it, because it has very limited functionality, but you can always try. You may also try the fixes that are posted:
https://github.com/tpm2-software/tpm2-abrmd/pull/721
and see if that helps.

**Comment by williamcroberts** [comment]
If you move to the in-kernel RM, you're sessions will be flushed as soon as the tpm2_startauthsession command finishes. You could just use /dev/tpm0 directly with the device tcti, and manually flush your sessions and other things as you go using tpm2_flushcontext

**Comment by p-gentili** [comment]
Related to #2381
