### ISSUE TITLE
Inconsistent encryption after reboot with tpm2_rsaencrypt

### ISSUE THREAD

**Issue by alexsmartens** [tpm2-software/tpm2-tools#2088]
Hi there, 

I'm trying to encrypt my key and everything seem to work until fine I reboot. I looked at all the available sources including your wiki and issues (including somewhat similar ones #1955 and #2024) but nothing helped. I feel like I might be missing out some piece of information

### System 
Ubuntu 20.04
tpm2-tools 4.1.1-1

### Steps to replicate 
My sequence of operations:
```
tpm2_changeauth -c owner ***MY_PASSPHRASE***
tpm2_changeauth -c endorsement ***MY_PASSPHRASE***
tpm2_changeauth -c lockout ***MY_PASSPHRASE***
```

```
tpm2_createprimary  -C o -c primary.ctx -P ***MY_PASSPHRASE**
tpm2_create -C primary.ctx -u key.pub -r key.priv
tpm2_load  -C primary.ctx -u key.pub -r key.priv -c key.ctx -n key.name
tpm2_rsaencrypt -c key.ctx -o rpool.enc rpool.pass
tpm2_rsadecrypt -c key.ctx rpool.enc
```

At this point `tpm2_rsadecrypt` works fine, but when I reboot I am seeing the error below

### Problem

```
# tpm2_rsadecrypt -c key.ctx rpool.enc
WARNING:esys:src/tss2-esys/api/Esys_ContextLoad.c:279:Esys_ContextLoad_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_ContextLoad.c:93:Esys_ContextLoad() Esys Finish ErrorCode (0x000001df) 
ERROR: Esys_ContextLoad(0x1DF) - tpm:parameter(1):integrity check failed
ERROR: Unable to run tpm2_rsadecrypt
```

I also tried to use `tpm2_flushcontext -t` as suggested in one of the issues but it did not help to.

What do you think?

**Comment by alexsmartens** [comment]
I quit using `tpm2_rsadecrypt` in favour of `tpm2_unseal`. I followed [Tpm2-Software Community Disk Encryption Manual](https://tpm2-software.github.io/2020/04/13/Disk-Encryption.html) and it worked out great. 
The solution to this issue would probably be to make the transient object persistent with `tpm2_evictcontrol`.
I'm closing the issues because I'm not using  `tpm2_rsadecrypt` anymore

**Comment by monperrus** [comment]
I cannot decrypt after reboot.
@alexsmartens are you able to fix this issue with `tpm2_evictcontrol`? if yes, what's the command exactly?
Thanks!

**Comment by SergiiDmytruk** [comment]
@monperrus, `tpm2_evictcontrol` can be used to move the object into TPM and I think you have to do this with the primary key if you want to use it after a reboot (you can't read primary key from TPM memory):
```
tpm2_evictcontrol -C o -P **OWNER-PASSWORD** -c primary.ctx 0x81000001
```

To use the key after a reboot you need to use `tpm2_load` on it first and get a new context because the old one is invalidated by a reboot (contexts describe things loaded into TPM and non-persistent (transient) objects do not survive a poweroff).  The `tpm2_evictcontrol` example above assigns `0x81000001` handle to primary key, so use that instead of its context file: `tpm2_load -C 0x81000001 ...`.

**Comment by monperrus** [comment]
thanks a lot @SergiiDmytruk for the hints.

after more trials, I have a working solution.
 
after reboot, the solution is to recreate the primary key and to load the rsa key using tpm2_load

```
tpm2_createprimary -c primary.ctx
tpm2_load  -C primary.ctx -u rsakey.pub -r rsakey.priv -c rsakey.ctx 
```

then I can decrypt with `tpm2_rsaencrypt`

**Comment by taumeister** [comment]
Oh jesus, wonderful.
Thanks for this info monperrus.
