### ISSUE TITLE
tpm2_startauthsession initramfs: ERROR: Could not load tcti, got: "device:/dev/tpm0" 

### ISSUE THREAD

**Issue by alexsmartens** [tpm2-software/tpm2-tools#2089]
I'm encrypting my drive by following the [Tpm2-Software Community Disk Encryption Manual](https://tpm2-software.github.io/2020/04/13/Disk-Encryption.html). Here is the error which I'm seeing in `initramfs`:
```
ERROR:tcti:src/tss2-tcti/tctildr.c:418:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
ERROR: Could not load tcti, got: "device:/dev/tpm0"
```

### System 
Ubuntu 20.04
tpm2-tools 4.1.1-1

### Steps to reproduce

Content of `/etc/initramfs-tools/hooks/decryptkey`:
```
#!/bin/sh
PREREQ=""
prereqs()
 {
     echo "$PREREQ"
 }
case $1 in
 prereqs)
     prereqs
     exit 0
     ;;
esac
. /usr/share/initramfs-tools/hook-functions
copy_exec /usr/bin/tpm2_startauthsession
copy_exec /usr/bin/tpm2_policypcr
copy_exec /usr/bin/tpm2_policyauthorize
copy_exec /usr/bin/tpm2_unseal
copy_exec /usr/bin/tpm2_flushcontext
exit 0
```
Initialization code:
```
tpm2_startauthsession --policy-session -S session.ctx -T device:/dev/tpm0
tpm2_policypcr -l sha256:0 -S session.ctx
tpm2_policyauthorize -S session.ctx -i set2.pcr.policy -n signing_key.name -t verification.tkt
tpm2_unseal -p session:session.ctx -c 0x81010001 | $ZFS load-key rpool
tpm2_flushcontext session.ctx
```
Exporting `export TPM2TOOLS_TCTI="device:/dev/tpm0"` leads to the same results.

Also, the same set of commands works perfectly fine on the booted system. 

Any ideas?

**Comment by osresearch** [comment]
safeboot's [initramfs/hooks/tpm-unseal](https://github.com/osresearch/safeboot/blob/master/initramfs/hooks/tpm-unseal) explicitly adds the library for the `device` TCTI. This is necessary since the tools load it with `dlopen()`, so `ldd` is unable to automatically determine that it is a dependency that needs to be included in the initrd.

```
copy_exec /lib/x86_64-linux-gnu/libtss2-tcti-device.so.0
```

**Comment by alexsmartens** [comment]
Adding `libtss2-tcti-device.so.0` solved the problem.
Thanks @osresearch!
