### ISSUE TITLE
tss2_* tools callback dialogs for 5.0

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tools#2101]
For 5.0, I'd like to bump the version of tpm2-tss to >= 3.0 (next release there) and use the better callback dialogs for authorization and branch selection here:

https://github.com/tpm2-software/tpm2-tools/blob/c93feb8db45b3dec1e0de87fde68c0b55d238805/tools/fapi/tss2_template.c#L233-L234

https://github.com/tpm2-software/tpm2-tools/blob/c93feb8db45b3dec1e0de87fde68c0b55d238805/tools/fapi/tss2_template.c#L279-L280

Also we'd get rid of the `#ifdef FAPI_3_0` in that file.

@idesai @williamcroberts Agreed ?

**Comment by williamcroberts** [comment]
I'm OK with that and I haven't seen anyone balk on the mailing list, but if someone does, ill defer to keeping the IFDEF's.
