### ISSUE TITLE
make install symlinks not right

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#2102]
Per this [thread](https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/XNJQUPKIO7X4U4QZ5SPIDRKQHBVXV3JP/), the following issue:

"I got it building today.  I don't know if it's an artifact of my build system but the symlinks are all absolute paths and incorporate a build-time path (possibly the sysroot?) so they won't function on the target machine."

Maybe it's not respecting prefix?

**Comment by diabonas** [comment]
This should be fixed by #2100.
