### ISSUE TITLE
Outdated Wiki tutorial

### ISSUE THREAD

**Issue by lenardteri** [tpm2-software/tpm2-tools#2104]
Greetings,

I have observed that the example commands listed in the Wiki use maybe outdated arguments.

For example, "tpm2_createprimary" in the wiki uses "-o" to save the primary object instead of "-c", as specified in the man page. The same issue is for the later example mentioned regarding "tpm2_load".

Thank you, 
Have a nice day!
Teri.

**Comment by williamcroberts** [comment]
@idesai haven't our discussions been around removing our wiki? Is that in your plans?

**Comment by idesai** [comment]
@williamcroberts yes that is correct. We still need to place the dependency matrix in the tpm2-software.github.io. Can you please merge this [PR](https://github.com/tpm2-software/tpm2-software.github.io/pull/38)?
