### ISSUE TITLE
VTPM tss2 

### ISSUE THREAD

**Issue by HBLocker** [tpm2-software/tpm2-tools#2108]
Tss2 VTPM

When compiled from source, I get this issue:

/tss/utils/./tssgetrandom -by 10

TPM_RC_SIZE - structure is the wrong size Handle number unspecified

But when calling tssgetrandom -by 10 -v  then there is no issue.

The issue is only in a VTPM, the command works in SWTPM

Any idea what this issue might be related to?
`TSS_Command_PreProcessor: Input parameters
bytesRequested 10
TSS_Execute20: Command 0000017b marshal
TSS_Execute_valist: Step 1: initialization
TSS_Execute_valist: Step 5: command encrypt
TSS_Sessions_GetDecryptSession: Found 0 decrypt sessions at 0
TSS_Execute_valist: Step 6 calculate HMACs
TSS_Execute_valist: Step 7 set command authorizations
TSS_Execute_valist: Step 8: process the command
TSS_AuthExecute: Executing TPM2_GetRandom
TSS_Socket_Open: Opening localhost:2321-raw
TSS_Socket_SendCommand: TPM2_GetRandom
TSS_Socket_SendCommand length 12
80 01 00 00 00 0c 00 00 01 7b 00 0a
TSS_Socket_ReceiveCommand length 22
80 01 00 00 00 16 00 00 00 00 00 0a 8e cc 1c ab
20 26 68 57 75 38
TSS_Execute_valist: Step 9 get response authorizations
TSS_Execute_valist: Step 13: response decryption
TSS_Sessions_GetEncryptSession: Found 0 encrypt sessions at 0
TSS_Execute20: Command 0000017b unmarshal
TSS_Socket_Close: Closing localhost-raw
getrandom: failed, rc 00000095
TPM_RC_SIZE - structure is the wrong size Handle number unspecified`

**Comment by idesai** [comment]
@JuergenReppSIT ?

**Comment by HBLocker** [comment]
@idesai This can be closed now. The project was creating a QR v-TPM with NIST round 3 :)
