### ISSUE TITLE
Help/Manpages for commandlet style

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-tools#2111]
Some things @PeterHuewe and I just noticed on the commandlet version of help:

- No bash-completion for `tpm2`

- `man tpm2` does not exist

- `tpm2 create --help=man` provides no-man help

- `tpm2_create --help=no-man` provides man help

- This should be `Usage: tpm2 create`:
```
$ tpm2 create --help=no-man
Usage: create [<options>]
```

- `tpm2` does not have a help option:
```
$ tpm2 --help
ERROR: --help: unknown tool. Available tpm2 commands:
checkquote
eventlog
print
[snip]
```

**Comment by idesai** [comment]
- [ ] Fix an issue where man pages were not displayed when specifying tpm2--space--toolname.
- [ ] Fix an issue where --help man and --help yielded the same unexpected result of providing no-man help.
- [ ] Fix an issue where --help=no-man and --help no-man provided the same unexpected result of providing man help.
- [ ] Fix an issue where tpm2 did not have a bash completion
- [ ] Add tpm2 man page
