### ISSUE TITLE
Add option to tpm2_policypcr to input a pre-calculated pcrDigest

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tools#2113]
In addition to options that specify raw PCR values coming from either from a file or directly reading off the PCR registers and then calculating the pcrDigest, we need to add an option to simply input a pre-calculated pcrDigest. This is useful when creating policies when raw PCR values aren't published.

**Comment by beansrus** [comment]
Hello,  I've been trying to find a way to seal data in nv memory against a digest that has been pre-calculated for a future expected value of PCR4, but whose contents are not that digest yet.  All examples and usage I've found always seem to indicate the PCRs need to be at the expected digest.  Is this bug meant to address that?  Do you know if there is any other way to do this with existing tools?

Thanks!

**Comment by m-fonseca** [comment]
Hello.  I've been looking for a way to seal data/keys against pre-computed PCR digests.  This issue obviously seems to be here to address that, but do you know if there any way to do so with the existing tools (even if its not obvious/straight forward?)

**Comment by williamcroberts** [comment]
> Hello. I've been looking for a way to seal data/keys against pre-computed PCR digests. This issue obviously seems to be here to address that, but do you know if there any way to do so with the existing tools (even if its not obvious/straight forward?)

@idesai I have no idea why the below isn't working and why we don't have a complete example in tpm2_unseal manpage. We just have snippets there that are not complete.

```bash
tpm2_createprimary -c primary.ctx
# -i can be either a - for stdin or a path to a file with the data to seal
echo 'secret' | tpm2_create -C primary.ctx -l sha256:0,1,2,3 -i- -u seal.pub -r seal.priv
tpm2_load -C primary.ctx -u seal.pub -r seal.priv -c seal.ctx
tpm2 unseal -c seal.ctx -p pcr:sha256:0,1,2,3
WARNING:esys:src/tss2-esys/api/Esys_Unseal.c:295:Esys_Unseal_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_Unseal.c:98:Esys_Unseal() Esys Finish ErrorCode (0x0000099d) 
ERROR: Esys_Unseal(0x99D) - tpm:session(1):a policy check failed
ERROR: Unable to run unseal
```

**Comment by idesai** [comment]
> Hello. I've been looking for a way to seal data/keys against pre-computed PCR digests. This issue obviously seems to be here to address that, but do you know if there any way to do so with the existing tools (even if its not obvious/straight forward?)

@williamcroberts, you are missing the step to create the policy and also the step to assign it for authorization to the sealing object.

@m-fonseca, here is a quick example with existing tools.

 ```bash
 tpm2_createprimary -c primary.ctx -Q
 tpm2_pcrread -Q -o pcr.bin sha256:0,1,2,3
 tpm2_createpolicy -Q --policy-pcr -l sha256:0,1,2,3 -f pcr.bin -L pcr.policy
 echo 'secret' | tpm2_create -C primary.ctx -L pcr.policy -i- -u seal.pub -r seal.priv -c seal.ctx -Q
 tpm2_unseal -c seal.ctx -p pcr:sha256:0,1,2,3
 ```

**Comment by idesai** [comment]
@williamcroberts, I updated the example section in the unseal man page.

**Comment by williamcroberts** [comment]
> @williamcroberts, you are missing the step to create the policy and also the step to assign it for authorization to the sealing object.

facepalm, duh. This is what happens when you do things before coffee.

**Comment by idesai** [comment]
@williamcroberts, as for this issue #2113, what can be the best way to specify the pcrdigest instead of raw pcr values? I was thinking as an argument — tpm2_policypcr <halg>:<digest>, your thoughts?

**Comment by m-fonseca** [comment]
> 
> @m-fonseca, here is a quick example with existing tools.
> 
> ```shell
> tpm2_createprimary -c primary.ctx -Q
> tpm2_pcrread -Q -o pcr.bin sha256:0,1,2,3
> tpm2_createpolicy -Q --policy-pcr -l sha256:0,1,2,3 -f pcr.bin -L pcr.policy
> echo 'secret' | tpm2_create -C primary.ctx -L pcr.policy -i- -u seal.pub -r seal.priv -c seal.ctx -Q
> tpm2_unseal -c seal.ctx -p pcr:sha256:0,1,2,3
> ```

Thanks a lot for this, it was a tremendous help!  

I did have problems with the tpm2_create and the `-c seal.ctx`  , but was able to use `tpm2_load -C primary.ctx -u seal.pub -r seal.priv -c seal.ctx` to get around it.

**Comment by williamcroberts** [comment]
> @williamcroberts, as for this issue #2113, what can be the best way to specify the pcrdigest instead of raw pcr values? I was thinking as an argument — tpm2_policypcr halg:digest, your thoughts?

offhand I don't object to that. Write the test first and see if it feels natural, if it does, go with it.
