### ISSUE TITLE
Fix FAPI auto detect

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tools#2120]
Verify with a release tpm2-tss version https://github.com/tpm2-software/tpm2-tools/blob/b0fb44319c78cc49eb1e74360bbb90c833d4ed30/configure.ac#L35

**Comment by AndreasFuchsSIT** [comment]
@idesai What the issue here ?

**Comment by idesai** [comment]
@AndreasFuchsSIT fapi tools are built when tpm2-tss is configured to build with fapi disabled.

**Comment by AndreasFuchsSIT** [comment]
But the default is "check" and if PKG_CHECK_MODULE fails enable_fapi is set to "no".
So the tools should not build in this case ?
https://github.com/tpm2-software/tpm2-tools/blob/2bfddf823a03ee39c46c2b3c526882b51b8c9004/configure.ac#L35-L42
Am I missing something ?

**Comment by idesai** [comment]
nm, I had some remnants from the tpm2-tss builds. Looks good. Would look better if the configure output could show that fapi utilities will not be built.

```
    tpm2-tss 3.1.0-dev
    esys:               yes
    fapi:               no
    tctidefaultmodule:  libtss2-tcti-default.so
    tctidefaultconfig:
    unit:               no
    integration:        no
    testing backend:
    fuzzing:            none
    debug:              info
    maxloglevel:        trace
    doxygen:            1
    crypto backend:     ossl
    sysconfdir:         ${prefix}/etc
    localstatedir:      ${prefix}/var
    runstatedir:        ${localstatedir}/run
    sysusersdir:        ${prefix}/etc/sysusers.d
    tmpfilesdir:        ${prefix}/etc/tmpfiles.d
    userstatedir:       $HOME/.local/share
```

```
    - tpm2-tools: 4.3.0-266-g2bfddf82-dirty
    - Man pages: yes
    - Unit tests: yes
    - tpm2_abrmd: yes
    - tpm_server: yes
    - bash: yes
    - python: yes
    - xxd: yes
    - ss: yes
    - shasum: yes
    - mktemp: yes
    - expect: yes
    - openssl: yes
```
