### ISSUE TITLE
Is RSA-PSS signature verification enabled ?

### ISSUE THREAD

**Issue by adelapie** [tpm2-software/tpm2-tools#2121]
Hello, 

I'm trying to verify RSA-PSS signatures using a TPM but I'm not sure if this feature is implemented. This is my code:

```
#!/bin/sh

# generate rsa key pair
openssl genrsa -out private.rsa.pem 2048 
openssl rsa -in private.rsa.pem -out public.rsa.pem -pubout

# generate msg to sign and digest

echo -n "abc" > data.in.raw
shasum -a 256 data.in.raw | awk '{ print "000000 " $1 }' | xxd -r -c 32 > data.in.digest

# TPM sign

tpm2 loadexternal -Q -G rsa -r private.rsa.pem -c key.ctx
tpm2 sign -Q -c key.ctx -s rsapss -g sha256 -d -f plain -o data.out.signed data.in.digest 

# OpenSSL verify

openssl pkeyutl -verify \
-in data.in.digest -sigfile data.out.signed \
-pkeyopt rsa_padding_mode:pss \
-pubin -inkey public.rsa.pem \
-pkeyopt rsa_pss_saltlen:-1 \
-pkeyopt digest:sha256

# TPM verify

tpm2 loadexternal -Q -G rsa -u public.rsa.pem -c key.ctx
tpm2 verifysignature -Q -c key.ctx -g sha256 -m data.in.raw -f rsapss -s data.out.signed

```

I can verify the RSA-PSS signature that the tpm has generated with openssl. However, tpm2 verifysignature fails with "ERROR: Unsupported signature input format.
ERROR: Unable to run verifysignature"

**Comment by idesai** [comment]
@adelapie, added a fix for the issue. Alternatively, you could also do the following if the verification only needs to happen in the TPM:

tpm2 sign -Q -c key.ctx -s rsapss -g sha256 -d -o data.out.signed data.in.digest
tpm2 verifysignature -Q -c key.ctx -g sha256 -m data.in.raw -s data.out.signed

**Comment by adelapie** [comment]
It works for me, thanks!
