### ISSUE TITLE
Object Load using "tpm2 load" issue : Question

### ISSUE THREAD

**Issue by eceadit** [tpm2-software/tpm2-tools#2125]
Hello,

Background: I worked on tpm 1.2, and went through the basics of tpm2.0, followed the test book reference in this site as well.

**System Setup:** Ubuntu 18.04 Guest HyperV, on Host Windows 10 laptop.
enabled vTPM: tpm2 tools random, NV, PCR, etc... run fine.

./configure --version output for Tools : 4.2-161-gc93feb8d
./configure --version output for TSS : 3.0.0-dev

Running everything as 'root'
I created a demo app in the following method:
1. used on_opts, on_arg functions and built individual tool context structure
2. defined my own wrapper and called tool_on run for each tool i needed to debug and understand the flow
**3. This method worked for for nv,pcr and createprimary, create, load, seal/unseal, sing.verify etc.** 

When combined with multiple steps, for example seal/unseal and sign/verify the following is observed 

ISSUE: observed with load via demo app mentioned above:
Running my demo app for example SEAL/UNSEAL:
1. Create primary  - successful
2. Create seal object - successful
3. Load object - error, in below comparisons image
4. Unseal  - did not reach here

However, when I run steps 1, 2 (i.e createprimary + create seal object )in one go and exit application 
And run only step 3 (load seal object) and exit app
And run only unseal. This works fine, but when combined with Load all 4 steps won't run together.

Running tpm2 tools for example SEAL/UNSEAL: works fine
1. Create primary  - successful
2. Create seal object - successful
3. Load object - successful
4. Unseal  - successful

Issue is in "write_all" function and I also captured the total bytes sent for comparing my app vs running tpm2 tools directly 
The stats are below: The 'current size' is captured in : 
'**function** tcti_device_transmit'  in  **file** tcti-device.c, **location**  size = write_all (tcti_dev->fd,
                                                                                                                                            command_buffer,
                                                                                                                                            command_size);
To compare the bytes sent for each step for various operations with my app and the tools.

**Comparision:** LEFT side tools stats , RIGHT side my app stats
![image](https://user-images.githubusercontent.com/66800129/86040031-f51a7500-ba60-11ea-9547-341bd6347205.png)

Query: 
what triggered this issue, and is there any way to increase memory for internal structs /  is there any config option missed ?
Is there any way forward ?,

Please throw some light this.

**Comment by idesai** [comment]
@eceadit can you show the command sequence that failed?

**Comment by eceadit** [comment]
Hello @idesai ,

output: ls -l /dev/tpm*
crw------- 1 root root  10,   224 Jun 29 12:14 /dev/tpm0
crw------- 1 root root 253, 65536 Jun 29 12:14 /dev/tpmrm0 

Using tpm2 tools directly: 
following python script - **Successful** : I used a simple py script: 
import os
from subprocess import call

#call(['/home/Desktop/tpm2-tools/tools/tpm2', 'getcap', '-l'])

print('\n--- CREATE PRIMARY ---')
call(['/home/Desktop/tpm2-tools/tools/tpm2', 'createprimary', '-c/home/Desktop/tpm2-tools/tools/test/sealprim.ctx'])


print('\n--- CREATE SEAL ---')
call(['/home/Desktop/tpm2-tools/tools/tpm2', 'create', '-C/home/Desktop/tpm2-tools/tools/test/sealprim.ctx', '-i/home/Desktop/tpm2-tools/tools/test/seal.dat', '-u/home/Desktop/tpm2-tools/tools/test/sealobj.pub', '-r/home/Desktop/tpm2-tools/tools/test/sealobj.priv'])

print('\n--- LOAD ---')
call(['/home/Desktop/tpm2-tools/tools/tpm2', 'load', '-C/home/Desktop/tpm2-tools/tools/test/sealprim.ctx', '-c/home/Desktop/tpm2-tools/tools/test/sealobj.ctx', '-u/home/Desktop/tpm2-tools/tools/test/sealobj.pub', '-r/home/Desktop/tpm2-tools/tools/test/sealobj.priv'])

print('\n--- UNSEAL ---')
call(['/home/Desktop/tpm2-tools/tools/tpm2', 'unseal', '-c/home/Desktop/tpm2-tools/tools/test/sealobj.ctx', '-o/home/Desktop/tpm2-tools/tools/test/unseal.dat'])

MY Sample App: few wrappers of code to over tpm2 tool files: 
Steps followed,
**Step 1:**
  TSS2_TCTI_CONTEXT *tcti = NULL;
    TSS2_RC rc_tcti = Tss2_TctiLdr_Initialize(NULL, &tcti);
    ESYS_CONTEXT *ectx = NULL;
    if (tcti) {
        ectx = ctx_init(tcti);
        if (!ectx) {
            return ;
        }
    }
/* no error so far */
**Step 2:** Create a ctx structure for various tpm2 function
example create primary shown here: referred on_opt, on_arg so that i dont miss any step
in my warapper defined for function in each each tool file
		ctx.context_file = malloc (strlen("/home/Demo/primseal.ctx") + 1);
		memset(ctx.context_file, '\0', strlen("/home/Demo/primseal.ctx") + 1);
		strcpy(ctx.context_file, "/home/Demo/primseal.ctx");

**Step 3:**
call the tool run with this created static context for each tool:

tpm2_tool_onrun(ectx, flags) ;

-----------------------------------

I followed similar method and was able to successfully use NV, PCR functionality.
So I called similarly for 'create' , 'load', and 'unseal' -built the ctx object and called tool run directly.

Error comes when all 4 functions as called in sequence: for MY demo app only, 
(tools direct usage is fine with py script.)
1. create primary
2. create 
3. load - error

when i run
1. create primary call
2. create call

only and the use the generated pub,priv, ctx files in load separately , it works fine
1. comment crate primary call - prim ctx file already crated in earlier run
2. comment crate  call - pub, sub files already crated in earlier run
3. load call - successful, exit app

Now 
1. comment crate primary call - prim ctx file already crated in earlier run
2. comment crate  call - pub, sub files already crated in earlier run
3. comment load call - already successful
4. call unseal - work perfect.

I created a thin layer above tools with traces etc, I may not be able to share the complete code base.
This method worked for : 
All 4 steps worked nice : NV def, write, read , undefine 
All 3 steps worked nice : pcr read, extend pcr read

For seal /unseal : only create primary and create works, then i get memory error in io.c, write_all
If i also run the 'load' call, this sequence has the issue. I called repective tool clean / stop functions as well, 

I created a thin layer above tools with traces etc, I may not be able to share the complete code base.
But i provided the my idea that i used to create my demo app.

thanks,
eceadit

**Comment by idesai** [comment]
@eceadit, I am guessing you are running out of TPM resident memory, are you using a resource manager at all? If not, can you try using the tpm2_flushcontext -t, tpm2_flushcontext -l, tpm2_flushcontext -s before the failing step?

**Comment by eceadit** [comment]
@idesai, it makes sense. I'll verify and update.  Also I am trying to check this on a physical device as well, instead of VMs and hyper V. I'll share my results.

Thanks a ton for the quick help.
