### ISSUE TITLE
Is current version supported on CentOS 8?

### ISSUE THREAD

**Issue by jxu103** [tpm2-software/tpm2-tools#2141]
Hello All,

I am currently new to TPM2-tools, and I am on CentOS 7 due to some requirements. I ran into an issue trying to get the newest version of tpm2-tools installed on CentOS 7, and on CentOS packages, it seems like the newest version is only supported on CentOS 8. Is this correct? or is there a way to install it on CentOS 7?

Thank you,
Jim

**Comment by williamcroberts** [comment]
Since it follows RHEL, from my understanding, RHEL 7 is bugfix only on 3.X series. So its pretty much froze. For RHEL 8 my understanding is that it will get updated to the 4.1.1 release of tpm2-tools for the 8.3.0 release of RHEL.

You can always download the source and build it.

**Comment by jxu103** [comment]
> Since it follows RHEL, from my understanding, RHEL 7 is bugfix only on 3.X series. So its pretty much froze. For RHEL 8 my understanding is that it will get updated to the 4.1.1 release of tpm2-tools for the 8.3.0 release of RHEL.
> 
> You can always download the source and build it.

Thank you for the reply, will try building it from source instead. Another quick off topic question, when will tpm2-tools support TPM Library 1.59 commands?

**Comment by idesai** [comment]
@jxu103 after the relevant additions are made to tpm2-tss. It is in the works.
