### ISSUE TITLE
NUC5i5RYH fTPM BIOS bug

### ISSUE THREAD

**Issue by n0p90** [tpm2-software/tpm2-tools#2148]
**Workaround [available here](https://github.com/tpm2-software/tpm2-tools/issues/2148#issuecomment-664049319)**

Dear Intel developers,

I know this is not the best place to report this, but I cannot access your [forums](https://community.intel.com/) because of broken SAML since you switched from https://forums.intel.com to https://community.intel.com (accessing any forum page while logged in redirects me to the registration page) and I never received any response from your ticket support.

The fTPM (PTT) on our NUC5i5RYH machines does not work on Linux. It seems to be a known BIOS bug which was never fixed: see [this issue](https://community.intel.com/t5/Intel-NUCs/NUC-6i7KYB-TPM/td-p/375598) and more specifically [this post](https://community.intel.com/t5/Intel-NUCs/NUC-6i7KYB-TPM/td-p/375598/page/2#lineardisplaymessageviewwrapper_5).

I've tested with 5 randomly selected NUC5i5RYH, several different Linux distributions and kernel versions,
and several different BIOS versions, including the latest one (RY0385).

Here are the related logs:

dmesg:
```
[    0.000000] efi:  ACPI=0xa2347000  ACPI 2.0=0xa2347000  ESRT=0xa2edeb18  SMBIOS=0xa2edec98  TPMEventLog=0x9d42b018
[    0.000000] ACPI: TPM2 0x00000000A2364E08 000034 (v03 INTEL  NUC5i5RY 00000181 AMI  00000000)
[    0.934444] tpm_crb MSFT0101:00: can't request region for resource [mem 0xa2fff000-0xa2fff02f]
[    0.934505] tpm_crb: probe of MSFT0101:00 failed with error -16
[    1.044339] ima: No TPM chip found, activating TPM-bypass!
```

dmidecode:
```
Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
        Vendor: Intel Corporation
        Version: RYBDWi35.86A.0385.2020.0519.1558
        Release Date: 05/19/2020
        Address: 0xF0000
        Runtime Size: 64 kB
        ROM Size: 6528 kB
        Characteristics:
                PCI is supported
                BIOS is upgradeable
                BIOS shadowing is allowed
                Boot from CD is supported
                Selectable boot is supported
                BIOS ROM is socketed
                EDD is supported
                5.25"/1.2 MB floppy services are supported (int 13h)
                3.5"/720 kB floppy services are supported (int 13h)
                3.5"/2.88 MB floppy services are supported (int 13h)
                Print screen service is supported (int 5h)
                Serial services are supported (int 14h)
                Printer services are supported (int 17h)
                ACPI is supported
                USB legacy is supported
                BIOS boot specification is supported
                Targeted content distribution is supported
                UEFI is supported
        BIOS Revision: 5.6

...

On Board Device 7 Information
        Type: Other
        Status: Enabled
        Description: TPM Device

...

Handle 0x001F, DMI type 41, 11 bytes
Onboard Device
        Reference Designation:  TPM Device
        Type: <OUT OF SPEC>
        Status: Enabled
        Type Instance: 1
        Bus Address: 0000:3f:01.0
```

iomem:
```
...
a2fff000-a37fffff : RAM buffer
...
```

As you can see, the same memory region is defined as "RAM buffer" and trying to be used for the fTPM by `tpm_crb`.

If this bug report has not its place here, I would be very grateful if you could forward this information to your colleagues developing the NUC BIOS.

Don't hesitate to tell me if you need more info in order to fix this bug.

Thanks and best regards!

**Comment by williamcroberts** [comment]
> Dear Intel developers,
> 
> I know this is not the best place to report this, but I cannot access your [forums](https://community.intel.com/) because of broken SAML since you switched from https://forums.intel.com to https://community.intel.com (accessing any forum page while logged in redirects me to the registration page) and I never received any response from your ticket support.

I didn't even know that existed... but generally we just use github and mailing list for most support and help. However, for specific things that can't go public, private email works as well.

> 
> The fTPM (PTT) on our NUC5i5RYH machines does not work on Linux. It seems to be a known BIOS bug which was never fixed: see [this issue](https://community.intel.com/t5/Intel-NUCs/NUC-6i7KYB-TPM/td-p/375598) and more specifically [this post](https://community.intel.com/t5/Intel-NUCs/NUC-6i7KYB-TPM/td-p/375598/page/2#lineardisplaymessageviewwrapper_5).
> 
> I've tested with 5 randomly selected NUC5i5RYH, several different Linux distributions and kernel versions,
> and several different BIOS versions, including the latest one (RY0385).
> 
> Here are the related logs:
> 
> dmesg:
> 
> ```
> [    0.000000] efi:  ACPI=0xa2347000  ACPI 2.0=0xa2347000  ESRT=0xa2edeb18  SMBIOS=0xa2edec98  TPMEventLog=0x9d42b018
> [    0.000000] ACPI: TPM2 0x00000000A2364E08 000034 (v03 INTEL  NUC5i5RY 00000181 AMI  00000000)
> [    0.934444] tpm_crb MSFT0101:00: can't request region for resource [mem 0xa2fff000-0xa2fff02f]
> [    0.934505] tpm_crb: probe of MSFT0101:00 failed with error -16
> [    1.044339] ima: No TPM chip found, activating TPM-bypass!
> ```
> 
> dmidecode:
> 
> ```
> Handle 0x0000, DMI type 0, 24 bytes
> BIOS Information
>         Vendor: Intel Corporation
>         Version: RYBDWi35.86A.0385.2020.0519.1558
>         Release Date: 05/19/2020
>         Address: 0xF0000
>         Runtime Size: 64 kB
>         ROM Size: 6528 kB
>         Characteristics:
>                 PCI is supported
>                 BIOS is upgradeable
>                 BIOS shadowing is allowed
>                 Boot from CD is supported
>                 Selectable boot is supported
>                 BIOS ROM is socketed
>                 EDD is supported
>                 5.25"/1.2 MB floppy services are supported (int 13h)
>                 3.5"/720 kB floppy services are supported (int 13h)
>                 3.5"/2.88 MB floppy services are supported (int 13h)
>                 Print screen service is supported (int 5h)
>                 Serial services are supported (int 14h)
>                 Printer services are supported (int 17h)
>                 ACPI is supported
>                 USB legacy is supported
>                 BIOS boot specification is supported
>                 Targeted content distribution is supported
>                 UEFI is supported
>         BIOS Revision: 5.6
> 
> ...
> 
> On Board Device 7 Information
>         Type: Other
>         Status: Enabled
>         Description: TPM Device
> 
> ...
> 
> Handle 0x001F, DMI type 41, 11 bytes
> Onboard Device
>         Reference Designation:  TPM Device
>         Type: <OUT OF SPEC>
>         Status: Enabled
>         Type Instance: 1
>         Bus Address: 0000:3f:01.0
> ```
> 
> iomem:
> 
> ```
> ...
> a2fff000-a37fffff : RAM buffer
> ...
> ```
> 
> As you can see, the same memory region is defined as "RAM buffer" and trying to be used for the fTPM by `tpm_crb`.
> 
> If this bug report has not its place here, I would be very grateful if you could forward this information to your colleagues developing the NUC BIOS.
> 
> Don't hesitate to tell me if you need more info in order to fix this bug.
> 
> Thanks and best regards!

@idesai I have no idea, any ideas? Is their someone else we could sync them up with?

**Comment by idesai** [comment]
Not sure.
@n0p90 have you tried the live chat support? https://www.intel.com/content/www/us/en/support/contact-support.html?productId=98414#@8

Also per the forum comments some really old ubuntu version (12.x something) worked and later releases it stopped working. It seems like for newer distribution there is a kernel [patch](https://patchwork.kernel.org/patch/9585671/) that is a workaround for the issue. Is that something you can use?

**Comment by n0p90** [comment]
Thanks a lot for your responses!

> @n0p90 have you tried the live chat support? https://www.intel.com/content/www/us/en/support/contact-support.html?productId=98414#@8

Yes, the diplomatic way to put it is that the person I spoke to was more interested in closing the ticket (which I don't know if it was ever created as I never received a confirmation e-mail) than transmitting it further.

> Also per the forum comments some really old ubuntu version (12.x something) worked and later releases it stopped working. It seems like for newer distribution there is a kernel [patch](https://patchwork.kernel.org/patch/9585671/) that is a workaround for the issue. Is that something you can use?

Unfortunately [this post](https://community.intel.com/t5/Intel-NUCs/NUC-6i7KYB-TPM/td-p/375598/page/2#lineardisplaymessageviewwrapper_5) indicates that the patch does not resolve the problem with the *RAM buffer* region which was not reserved by the BIOS.

I will try to patch [e820__reserve_resources_late](https://elixir.bootlin.com/linux/v5.7.8/source/arch/x86/kernel/e820.c#L1189) to act as if the region `0xa2fff000-0xa2fff02f` was correctly marked as reserved and see if this changes something. I'll report back if this workaround works or not.

Thanks a lot for your help and your work to make TPM useful on Linux!

**Comment by n0p90** [comment]
@idesai 
I can now confirm that the problem is the NUC BIOS does not reserve the region at `0xa2fff000` that it uses for the fTPM control area.

If I manually reserve this region in the [`e820__memory_setup_default`](https://elixir.bootlin.com/linux/v5.7.8/source/arch/x86/kernel/e820.c#L1227) function, the TPM works.

```diff
diff -ru a/arch/x86/kernel/e820.c b/arch/x86/kernel/e820.c
--- a/arch/x86/kernel/e820.c	2020-07-16 08:13:36.000000000 +0200
+++ b/arch/x86/kernel/e820.c	2020-07-24 18:35:17.677332959 +0200
@@ -1251,6 +1251,9 @@
 		e820__range_add(HIGH_MEMORY, mem_size << 10, E820_TYPE_RAM);
 	}
 
+	// NUC5 BIOS fTPM bug workaround: reserve the TPM control area region
+	e820__range_add(0xa2fff000, 0x1000, E820_TYPE_RESERVED);
+
 	/* We just appended a lot of ranges, sanitize the table: */
 	e820__update_table(e820_table);
 
```

Of course this workaround is just for confirming the origin of the bug. I don't think there is a clean and generic way to implement that in the kernel. This really needs to be fixed in the BIOS.

If you could transmit this information to your colleagues working on the NUC BIOS, I'm sure this bug would be quickly fixed.

Thanks a lot for your help!

**Comment by n0p90** [comment]
I just found out that there is a kernel parameter which does exactly the same as the above patch. I'll leave it here as a workaround for people with the same issue until next BIOS release.

Add the following [kernel parameter](https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt) to your boot loader:
```
memmap=0x1000%0xa2fff000+2
```
