### ISSUE TITLE
cirrus CI failing

### ISSUE THREAD

**Issue by tstruk** [tpm2-software/tpm2-tools#2157]
Since the mssim async change (https://github.com/tpm2-software/tpm2-tss/pull/1793) has been merged into TSS 3.1.0-dev (master) the tools cirrus CI build is failing with strange comms errors between abrmd and TSS: https://cirrus-ci.com/task/5940479990693888?command=main#L583
The Travis builds are running fine against master and 2.4.x: https://travis-ci.org/github/tpm2-software/tpm2-tools/jobs/715590835
And the abrmd integ tests are also fine: https://cirrus-ci.com/task/5178774654287872

**Comment by tstruk** [comment]
Running everything locally on FreeBSD 12.1 against tpm2-tss-master, tpm2-abrmd-master and tpm2-tools-master all tests are passing fine.

**Comment by williamcroberts** [comment]
@tstruk weird. Still seeing this fail on cirrus ci with:
```
** (process:74670): CRITICAL **: 08:41:24.370: failed to allocate dbus proxy object: Timeout was reached
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x8012fbe80 failed with a0008 
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-abrmd 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: tabrmd 
ERROR:tcti:src/tss2-tcti/tctildr.c:416:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
ERROR:fapi:src/tss2-fapi/api/Fapi_Initialize.c:227:Fapi_Initialize_Finish() Initializing TCTI. ErrorCode (0x000a0008) 
Fapi_Initialize(0xA0008) - tcti:Fails to connect to next lower layer
tss2 provision on line 22 failed: 1
ERROR:fapi:src/tss2-fapi/api/Fapi_Delete.c:398:Fapi_Delete_Async() ErrorCode (0x00060034) FAPI not provisioned. 
ERROR:fapi:src/tss2-fapi/api/Fapi_Delete.c:313:Fapi_Delete() ErrorCode (0x00060034) Entity_Delete 
Fapi_Delete(0x60034) - fapi:Provisioning was not executed.
FAIL test/integration/fapi/fapi-nv-increment.sh (exit status: 1)
```

Is it perhaps some configuration bug? I also wonder if its just the tss2 tools or if it's also the tpm2_ toolsets having this issue.

**Comment by tstruk** [comment]
> ** (process:74670): CRITICAL **: 08:41:24.370: failed to allocate dbus proxy object: Timeout was reached

This time is was a timeout. Cirrus is running very slow today. Let's rerun in a bit.

**Comment by tstruk** [comment]
Everything keeps timing out. https://cirrus-ci.com/task/5393944777326592?command=main#L493
The install step takes quite long. There is a time limit of 1h. I would disable some of the integ tests.
Do you know which ones run longest?

**Comment by tstruk** [comment]
With this https://github.com/tpm2-software/tpm2-tools/pull/2186 it is working now

**Comment by williamcroberts** [comment]
> With this #2186 it is working now

Darn timeouts...
