### ISSUE TITLE
tpm2_createprimary: Cannot generate primary context/key using RSA encryption algorithm

### ISSUE THREAD

**Issue by fearTheUnknown** [tpm2-software/tpm2-tools#2163]
Hi all,
I am a beginner in TPM. Currently i am having an issue with the command "tpm2_createprimary" as describe below:

### Description:
"tpm2_createprimary" command cannot generate the primary context/key using "RSA" encryption algorithm.
However, "tpm2_createprimary" is able to generate the primary context/key using "ECC" encryption algorithm.

### Device under test:
Infineon "SLB 9670VQ2.0" TPM module.

### OS under test:
CentOS 8 for aarch64

### Log:

[root@localhost tpm2_test]# t**pm2_createprimary -C e -g sha256 -G rsa -c primary_ctx -P "1234"**

** (process:2798): WARNING **: 11:50:59.029: Failed to create connection with service: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'com.intel.tss2.TctiTabrmd' on object at path /com/intel/tss2/Tabrmd/Tcti
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0xffff8de77c5c failed with a0008
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-abrmd
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0
**ERROR:esys:src/tss2-esys/esys_iutil.c:1390:iesys_check_response() Error: GetRspAuths ErrorCode (0x00080007)
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:408:Esys_CreatePrimary_Finish() Error: check response ErrorCode (0x00080007)
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x00080007)
ERROR: Esys_CreatePrimary(0x80007) - sys:Function called in the wrong order
ERROR:esys:src/tss2-esys/esys_iutil.c:1149:iesys_check_sequence_async() Esys called in bad sequence.
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:66:Esys_FlushContext() Error in async function ErrorCode (0x00070007)
ERROR: Esys_FlushContext(0x70007) - esapi:Function called in the wrong order
ERROR: Unable to run tpm2_createprimary**
[root@localhost tpm2_test]# ls -l
total 0
[root@localhost tpm2_test]# **tpm2_createprimary -C e -g sha256 -G ecc -c primary_ctx -P "1234"**

** (process:2802): WARNING **: 11:51:44.319: Failed to create connection with service: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'com.intel.tss2.TctiTabrmd' on object at path /com/intel/tss2/Tabrmd/Tcti
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0xffff88c77c5c failed with a0008
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-abrmd
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0
**name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: ecc
  raw: 0x23
curve-id:
  value: NIST p256
  raw: 0x3
kdfa-alg:
  value: null
  raw: 0x10
kdfa-halg:
  value: (null)
  raw: 0x0
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
x: ae3af7426f4c91ce91da1d6edc44e29db4fe67eb2b63bcf30a111b40c8deba1c
y: 776908f46306f5e1f73c49e009e5d5157c5313b2619f0144757e50d8cff898f7**
[root@localhost tpm2_test]# ls -l
total 4
**-rw-r--r--. 1 root root 844 Aug 11 11:51 primary_ctx**
[root@localhost tpm2_test]# ls -l /dev/tpm*
**crw-------. 1 root root  10,   224 Jun 22  2018 /dev/tpm0
crw-------. 1 root root 253, 65536 Jun 22  2018 /dev/tpmrm0**
[root@localhost tpm2_test]# ps -aux | grep tpm
root         581  0.0  0.0      0     0 ?        I<   11:32   0:00 [tpm_dev_wq]
root        2748  0.0  0.0 536192 10048 pts/0    Sl   11:48   0:00 tpm2-abrmd --tcti=:/dev/tpm0 --allow-root
root        2825  0.0  0.0   6976  1536 pts/0    S+   11:52   0:00 grep --color=auto tpm
[root@localhost tpm2_test]#

### Attempted Action:
- Performed integration test for "tpm2_createprimary" on the IBM simulator (tpm_server) -> Issue does not occur

Hoping that i executed the command properly. Please do not hesitate to correct if i have done something wrong.
Thank you for your help in advance

**Comment by williamcroberts** [comment]
i'm assuming you have a tpm at /dev/tpmrm0, is that right? if so try adding -t 'device:/dev/tpmrm0' to your command, do the errors go away?

**Comment by fearTheUnknown** [comment]
Hi @williamcroberts,

I have a TPM device at /dev/tpm0.

I have tried adding -t 'device:/dev/tpmrm0' to the "tpm2-abrmd" command as well as the "tpm2_createprimary" command.
Unfortunately, the issue still remains.

Please help to check the log below:

### Added -t 'device:/dev/tpmrm0' to "tpm2-abrmd" command only:

[root@localhost tpm2_test]# **tpm2-abrmd -t "device:/dev/tpmrm0" --allow-root&**
[1] 2800
[root@localhost tpm2_test]#
** (process:2800): WARNING **: 00:18:06.401: tcti_conf before: "device:/dev/tpm0"

** (tpm2-abrmd:2800): WARNING **: 00:18:06.401: tcti_conf after: "device:/dev/tpmrm0"

[root@localhost tpm2_test]#
[root@localhost tpm2_test]#
[root@localhost tpm2_test]#
[root@localhost tpm2_test]#
[root@localhost tpm2_test]# **tpm2_createprimary -C e -g sha256 -G rsa -c primary_ctx -P "1234"**

** (process:2808): WARNING **: 00:18:26.134: Failed to create connection with service: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0xffffa5977c5c failed with a0008
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-abrmd
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0
**ERROR:esys:src/tss2-esys/esys_iutil.c:1390:iesys_check_response() Error: GetRspAuths ErrorCode (0x00080007)
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:408:Esys_CreatePrimary_Finish() Error: check response ErrorCode (0x00080007)
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x00080007)
ERROR: Esys_CreatePrimary(0x80007) - sys:Function called in the wrong order
ERROR:esys:src/tss2-esys/esys_iutil.c:1149:iesys_check_sequence_async() Esys called in bad sequence.
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:66:Esys_FlushContext() Error in async function ErrorCode (0x00070007)
ERROR: Esys_FlushContext(0x70007) - esapi:Function called in the wrong order
ERROR: Unable to run tpm2_createprimary**
[1]+  Exit 74                 tpm2-abrmd -t "device:/dev/tpmrm0" --allow-root


### Added -t 'device:/dev/tpmrm0' to "tpm2_createprimary" command only:
[root@localhost tpm2_test]# **tpm2-abrmd -t "device:/dev/tpm0" --allow-root&**
[1] 2883
[root@localhost tpm2_test]#
** (process:2883): WARNING **: 00:28:12.621: tcti_conf before: "device:/dev/tpm0"

** (tpm2-abrmd:2883): WARNING **: 00:28:12.621: tcti_conf after: "device:/dev/tpm0"

[root@localhost tpm2_test]# **tpm2_createprimary -C e -g sha256 -G rsa -c primary_ctx -P "1234" -t 'device:/dev/tpmrm0'**

** (process:2891): WARNING **: 00:28:29.116: Failed to create connection with service: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0xffffba387c5c failed with a0008
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-abrmd
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0
**ERROR:esys:src/tss2-esys/esys_iutil.c:1390:iesys_check_response() Error: GetRspAuths ErrorCode (0x00080007)
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:408:Esys_CreatePrimary_Finish() Error: check response ErrorCode (0x00080007)
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x00080007)
ERROR: Esys_CreatePrimary(0x80007) - sys:Function called in the wrong order
ERROR:esys:src/tss2-esys/esys_iutil.c:1149:iesys_check_sequence_async() Esys called in bad sequence.
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:66:Esys_FlushContext() Error in async function ErrorCode (0x00070007)
ERROR: Esys_FlushContext(0x70007) - esapi:Function called in the wrong order
ERROR: Unable to run tpm2_createprimary**
[1]+  Exit 74                 tpm2-abrmd -t "device:/dev/tpm0" --allow-root



### Added -t 'device:/dev/tpmrm0' to "tpm2-abrmd" and "tpm2_createprimary" commands:

[root@localhost tpm2_test]# **tpm2-abrmd -t "device:/dev/tpmrm0" --allow-root&**
[1] 2833
[root@localhost tpm2_test]#
** (process:2833): WARNING **: 00:20:22.894: tcti_conf before: "device:/dev/tpm0"

** (tpm2-abrmd:2833): WARNING **: 00:20:22.894: tcti_conf after: "device:/dev/tpmrm0"

[root@localhost tpm2_test]# **tpm2_createprimary -C e -g sha256 -G rsa -c primary_ctx -P "1234" -t 'device:/dev/tpmrm0'**

** (process:2841): WARNING **: 00:20:27.372: Failed to create connection with service: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0xffffa9507c5c failed with a0008
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-abrmd
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0
**ERROR:esys:src/tss2-esys/esys_iutil.c:1390:iesys_check_response() Error: GetRspAuths ErrorCode (0x00080007)
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:408:Esys_CreatePrimary_Finish() Error: check response ErrorCode (0x00080007)
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x00080007)
ERROR: Esys_CreatePrimary(0x80007) - sys:Function called in the wrong order
ERROR:esys:src/tss2-esys/esys_iutil.c:1149:iesys_check_sequence_async() Esys called in bad sequence.
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:66:Esys_FlushContext() Error in async function ErrorCode (0x00070007)
ERROR: Esys_FlushContext(0x70007) - esapi:Function called in the wrong order
ERROR: Unable to run tpm2_createprimary
[1]+  Exit 74                 tpm2-abrmd -t "device:/dev/tpmrm0" --allow-root**

**Comment by williamcroberts** [comment]
So you are you normally running the resource manager tpm2-abrmd? If so, if it's installed it should just work. What versions of everything are you running, specifically: tpm2-tss, tpm2-tools and tpm2-abrmd?

**Comment by fearTheUnknown** [comment]
I'm not **so sure where to find the info about the versions since i clone and build latest update from the master** branch of each component . So i would like to **take the version info from the "CHANGELOG.md" of "tpm2-tss", "tpm2-tools" and "tpm2-abrmd"** along **with the current commit** info for each in my directory:

**tpm2-abrmd: 2.3.2 - 2020-05-18**
commit 78ba8eabe382214b1174f93fbb692115ac03acae (HEAD -> master, origin/master, origin/HEAD)
Author: William Roberts <william.c.roberts@intel.com>
Date:   Fri Jul 17 09:02:23 2020 -0500

    Update CHANGELOG.md

**tpm2-tool: 4.2 2020-04-08**
commit 34f7d1a18af94f47cef728c0630d0cb395c63a49 (HEAD -> master, origin/master, origin/HEAD)
Author: Tadeusz Struk <tadeusz.struk@intel.com>
Date:   Fri Aug 7 08:50:02 2020 -0700

    cirrus: build mssim in a single job

    Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>


**tpm2-tss: 3.0.0**
commit 76be63d641e01e7a3fcdb987fedadf98e970ba8b (HEAD -> master, origin/master, origin/HEAD)
Author: Jonas Witschel <diabonas@gmx.de>
Date:   Wed Aug 5 15:36:16 2020 +0200

    test/esys-certifyX509: use TPMA_OBJECT_X509SIGN depending on integration_tcti

    Currently the esys-certifyX509 integration test enables TPMA_OBJECT_X509SIGN,
    which only works with the mssim TCTI at the moment, depending on the existence
    of the TCTI_MSSIM macro. This macro is defined if the mssim TCTI is enabled,
    i.e. if libtss2-tcti-mssim is built. This excludes that valid use case that the
    user wants to have the mssim TCTI enabled (e.g. for compatibility with other
    tpm2-software test suites), but also has swtpm available for running the
    tpm2-tss integration test suite with libtss2-tcti-swtpm. Introduce a new macro
    INTEGRATION_TCTI_MSSIM that is defined if $integration_tcti is set to mssim in
    configure so that users can run the test suite with swtpm without having to use
    ./configure --disable-tcti-mssim.

    Signed-off-by: Jonas Witschel <diabonas@gmx.de>

**Comment by fearTheUnknown** [comment]
For some more additional info, as i observed **i can still read PCRs of the TPM with or without adding -t 'device:/dev/tpmrm0' to the tpm2-abrmd command**.

Please take a look below:

### Added -t 'device:/dev/tpmrm0' to "tpm2-abrmd":
[root@localhost tpm2_test]# **tpm2-abrmd -t ":/dev/tpmrm0" --allow-root&**
[1] 7016
[root@localhost tpm2_test]#
** (process:7016): WARNING **: 11:01:34.400: tcti_conf before: "device:/dev/tpm0"

** (tpm2-abrmd:7016): WARNING **: 11:01:34.400: tcti_conf after: ":/dev/tpmrm0"

(tpm2-abrmd:7016): GLib-GObject-WARNING **: 11:01:34.404: cannot register existing type 'TctiTabrmd'

(tpm2-abrmd:7016): GLib-GObject-CRITICAL **: 11:01:34.404: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(tpm2-abrmd:7016): GLib-CRITICAL **: 11:01:34.404: g_once_init_leave: assertion 'result != 0' failed

(tpm2-abrmd:7016): GLib-GObject-CRITICAL **: 11:01:34.404: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed

** (tpm2-abrmd:7016): WARNING **: 11:01:34.404: Failed to create connection with service: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'com.intel.tss2.TctiTabrmd' on object at path /com/intel/tss2/Tabrmd/Tcti
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0xffff7d697c5c failed with a0008
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-abrmd
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0

[root@localhost tpm2_test]# **ps -aux | grep abrmd**
root        7016  0.0  0.0 536192 10048 pts/0    Sl   11:01   0:00 tpm2-abrmd -t :/dev/tpmrm0 --allow-root
root        7030  0.0  0.0   6976  1600 pts/0    S+   11:02   0:00 grep --color=auto abrmd
[root@localhost tpm2_test]# **tpm2_pcrread**

** (process:7031): WARNING **: 11:02:16.904: Failed to create connection with service: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'com.intel.tss2.TctiTabrmd' on object at path /com/intel/tss2/Tabrmd/Tcti
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0xffffabb27c5c failed with a0008
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-abrmd
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0
**sha1:
  0 : 0x1E97A0D30A170329D2C9847608B06B20C7CEACC5
  1 : 0xEDC3DCD11BB032C52357942404CE2E4F826040E1
  2 : 0x40D3C81C4761391F64B624901A18C830EA4B8E0B
  3 : 0xB2A83B0EBF2F8374299A5B2BDFC31EA955AD7236
  4 : 0xB7294A471FDB471169E70367DC92482CE4DFEBBD
  5 : 0xAB4BA855C6C4584D0A264C1762355CC623465A70
  6 : 0xB2A83B0EBF2F8374299A5B2BDFC31EA955AD7236
  7 : 0xFA08154AC17AED3AEE241B7D876B8A2F59D95689
  8 : 0xB0DCDB511A85FD16CBF18CE563A24DDCE56239F9
  9 : 0xD4211F57F41A87B8AEBFAFCD947C6378255F368D
  10: 0x0000000000000000000000000000000000000000
  11: 0x0000000000000000000000000000000000000000
  12: 0x0000000000000000000000000000000000000000
  13: 0x0000000000000000000000000000000000000000
  14: 0x0000000000000000000000000000000000000000
  15: 0x0000000000000000000000000000000000000000
  16: 0x0000000000000000000000000000000000000000
  17: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  18: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  19: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  20: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  21: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  22: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  23: 0x0000000000000000000000000000000000000000
sha256:
  0 : 0xEBA1C54342D96F92D5B5894319969F10546B9D76D0D6AD5662AFEAD5F29C9889
  1 : 0x5E6BF252EA0748980EBE75716A76ECBC92B9490A9CFC37C61B0C23FA809571B3
  2 : 0x85E54BCA5B9B5D9FFA486E77B9577CC705A534170B8BE9817B7B69244658B2EC
  3 : 0x3D458CFE55CC03EA1F443F1562BEEC8DF51C75E14A9FCF9A7234A13F198E7969
  4 : 0x10A3F19EBC40488CFEC8DC8743FDD25DADFBC5B70420054926A5B9CB3C221E27
  5 : 0x4F06F5D8F8CF22CBE362CB3A85C64C26A3E88F8C9E0DCEF81ECB77043AD79BD4
  6 : 0x3D458CFE55CC03EA1F443F1562BEEC8DF51C75E14A9FCF9A7234A13F198E7969
  7 : 0xE697A812060B91122205A9E2E251208A230AE5ACE5350D11764211F20B74901A
  8 : 0xF70E94864CD0080B3413234C3FA5915E80E108B057A59E9025D6176D33AABC85
  9 : 0x389CE93DABF210B0F1E97653D4D7E4A7965C06C40220D39B3AB5433BBF5AA063
  10: 0x0000000000000000000000000000000000000000000000000000000000000000
  11: 0x0000000000000000000000000000000000000000000000000000000000000000
  12: 0x0000000000000000000000000000000000000000000000000000000000000000
  13: 0x0000000000000000000000000000000000000000000000000000000000000000
  14: 0x0000000000000000000000000000000000000000000000000000000000000000
  15: 0x0000000000000000000000000000000000000000000000000000000000000000
  16: 0x0000000000000000000000000000000000000000000000000000000000000000
  17: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  18: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  19: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  20: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  21: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  22: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  23: 0x0000000000000000000000000000000000000000000000000000000000000000**
[root@localhost tpm2_test]#


### No "tpm2-abrmd" is used:
[root@localhost tpm2_test]# **ps -aux | grep abrmd**
root        7074  0.0  0.0   6976  1536 pts/0    S+   11:10   0:00 grep --color=auto abrmd
[root@localhost tpm2_test]# **tpm2_pcrread**

** (process:7075): CRITICAL **: 11:10:51.470: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: Timeout was reached
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0xffff841e7c5c failed with a0008
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-abrmd
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0
**sha1:
  0 : 0x1E97A0D30A170329D2C9847608B06B20C7CEACC5
  1 : 0xEDC3DCD11BB032C52357942404CE2E4F826040E1
  2 : 0x40D3C81C4761391F64B624901A18C830EA4B8E0B
  3 : 0xB2A83B0EBF2F8374299A5B2BDFC31EA955AD7236
  4 : 0xB7294A471FDB471169E70367DC92482CE4DFEBBD
  5 : 0xAB4BA855C6C4584D0A264C1762355CC623465A70
  6 : 0xB2A83B0EBF2F8374299A5B2BDFC31EA955AD7236
  7 : 0xFA08154AC17AED3AEE241B7D876B8A2F59D95689
  8 : 0xB0DCDB511A85FD16CBF18CE563A24DDCE56239F9
  9 : 0xD4211F57F41A87B8AEBFAFCD947C6378255F368D
  10: 0x0000000000000000000000000000000000000000
  11: 0x0000000000000000000000000000000000000000
  12: 0x0000000000000000000000000000000000000000
  13: 0x0000000000000000000000000000000000000000
  14: 0x0000000000000000000000000000000000000000
  15: 0x0000000000000000000000000000000000000000
  16: 0x0000000000000000000000000000000000000000
  17: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  18: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  19: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  20: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  21: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  22: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  23: 0x0000000000000000000000000000000000000000
sha256:
  0 : 0xEBA1C54342D96F92D5B5894319969F10546B9D76D0D6AD5662AFEAD5F29C9889
  1 : 0x5E6BF252EA0748980EBE75716A76ECBC92B9490A9CFC37C61B0C23FA809571B3
  2 : 0x85E54BCA5B9B5D9FFA486E77B9577CC705A534170B8BE9817B7B69244658B2EC
  3 : 0x3D458CFE55CC03EA1F443F1562BEEC8DF51C75E14A9FCF9A7234A13F198E7969
  4 : 0x10A3F19EBC40488CFEC8DC8743FDD25DADFBC5B70420054926A5B9CB3C221E27
  5 : 0x4F06F5D8F8CF22CBE362CB3A85C64C26A3E88F8C9E0DCEF81ECB77043AD79BD4
  6 : 0x3D458CFE55CC03EA1F443F1562BEEC8DF51C75E14A9FCF9A7234A13F198E7969
  7 : 0xE697A812060B91122205A9E2E251208A230AE5ACE5350D11764211F20B74901A
  8 : 0xF70E94864CD0080B3413234C3FA5915E80E108B057A59E9025D6176D33AABC85
  9 : 0x389CE93DABF210B0F1E97653D4D7E4A7965C06C40220D39B3AB5433BBF5AA063
  10: 0x0000000000000000000000000000000000000000000000000000000000000000
  11: 0x0000000000000000000000000000000000000000000000000000000000000000
  12: 0x0000000000000000000000000000000000000000000000000000000000000000
  13: 0x0000000000000000000000000000000000000000000000000000000000000000
  14: 0x0000000000000000000000000000000000000000000000000000000000000000
  15: 0x0000000000000000000000000000000000000000000000000000000000000000
  16: 0x0000000000000000000000000000000000000000000000000000000000000000
  17: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  18: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  19: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  20: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  21: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  22: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  23: 0x0000000000000000000000000000000000000000000000000000000000000000**
[root@localhost tpm2_test]#

Hope this can additionally help you in finding the root cause of the issue.

**Comment by fearTheUnknown** [comment]
Hi @williamcroberts,

Might we have any feedback for this issue?

Thank you.

**Comment by fearTheUnknown** [comment]
Just for some more status update,

i have just recently re-installed the whole system with "tpm2-tool" and "tpm2-tss" (without installing "tpm2-abrmd" ) and try to create the RSA context primary key again.

Unfortunately the issue still remains as follow:

```
[root@localhost tpm_test]# tpm2_createprimary -C e -g sha256 -G rsa -c primary_rsa
ERROR:esys:src/tss2-esys/esys_iutil.c:1390:iesys_check_response() Error: GetRspAuths ErrorCode (0x00080007)
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:408:Esys_CreatePrimary_Finish() Error: check response ErrorCode (0x00080007)
ERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x00080007)
ERROR: Esys_CreatePrimary(0x80007) - sys:Function called in the wrong order
ERROR:esys:src/tss2-esys/esys_iutil.c:1149:iesys_check_sequence_async() Esys called in bad sequence.
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:66:Esys_FlushContext() Error in async function ErrorCode (0x00070007)
ERROR: Esys_FlushContext(0x70007) - esapi:Function called in the wrong order
ERROR: Unable to run tpm2_createprimary
```
From this, i believe that the issue is not due to "tpm2-abrmd".

Thank you

**Comment by fearTheUnknown** [comment]
Hi @williamcroberts,

I think the root cause of the issue is found.

The TPM takes more time to generate the RSA primary key context than the ECC primary key context.

The private TPM firmware which we are using times out before the TPM can set the data available bit. This leads to the data corruption during transmission between TPM and the firmware.

To overcome this issue, we have increased the timeout time interval in our firmware.

We would like to include our log showing proper functioning of our TPM in generating RSA primary key with different key size:

```
Executing: tpm2_createprimary -C e -g sha256 -G rsa -c primary_ctx
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: a8ee4851a401d25178261dbe3c2f2e63192129e45370215d5ff270a0294c339ad9c1cdbaefda90c2d91f5ce694d76d17e5149c5812ef74213e25f3d2a25a5ca16b9cfce53d2846700a0b3475e15628df1f422954a572cb97266b3a695e4306c0f778c1984b712e75fb984cf424738ed0fa51f570a4e35220e18630ddaa9b8f24e6ae6f2fc4c54be8a0b9c6db776b831cfbe6f60c3e984497d8a24b9ebf2aaa2a4616fdfbd342e1dc643be8fe667cd0e96220e5d0e381112b08a0f7f38c3e20098649a01a617f01495e1f7d690f7fdca6dbdb123bf54eb86acfc5c5c48d722e95a02341eeaa20bd595f88adccc6133d6f6376769f3f0636e3bf8d5970c98f8bf7
Time eclapsed: 25
Executing: tpm2_createprimary -C e -g sha256 -G rsa1024 -c primary_ctx
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 1024
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: b085bb9a5e1d3689838cc207cf25d368e30aa056dc2969b647c6a5cfb11b8229ffa53071e25547836afa0922d68f05b62d95069f8b72144e09bdc960e3fb2342dc673b7e518509c849d9d60eeb6c191e84ec35ca7f768b922e8ec74919b8c7396134f923efb5eedb88783326ba5096fb3a87ec2d84abfe46bc32d6921c1c50e5
Time eclapsed: 8
Executing: tpm2_createprimary -C e -g sha256 -G rsa2048 -c primary_ctx
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
  raw: 0x30072
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: a8ee4851a401d25178261dbe3c2f2e63192129e45370215d5ff270a0294c339ad9c1cdbaefda90c2d91f5ce694d76d17e5149c5812ef74213e25f3d2a25a5ca16b9cfce53d2846700a0b3475e15628df1f422954a572cb97266b3a695e4306c0f778c1984b712e75fb984cf424738ed0fa51f570a4e35220e18630ddaa9b8f24e6ae6f2fc4c54be8a0b9c6db776b831cfbe6f60c3e984497d8a24b9ebf2aaa2a4616fdfbd342e1dc643be8fe667cd0e96220e5d0e381112b08a0f7f38c3e20098649a01a617f01495e1f7d690f7fdca6dbdb123bf54eb86acfc5c5c48d722e95a02341eeaa20bd595f88adccc6133d6f6376769f3f0636e3bf8d5970c98f8bf7
Time eclapsed: 25
```

Sorry that we could not include the patch which shows changes in our firmware since the firmware itself is a proprietary property of our organization.

Thank you
