### ISSUE TITLE
Fedora:33 Rpm package failed dependency

### ISSUE THREAD

**Issue by hajnalmt** [tpm2-software/tpm2-tools#2164]
There was a tpm2-tss version update (https://pkgs.org/download/tpm2-tss(x86-64)). In fedora:33 only the 3.0.0 version is available now (released a week ago.)

This causes errors on the installation side, because these two libs were updated:

[root@e1001aed7f36 /]# yum install tpm2-tools
Last metadata expiration check: 0:19:55 ago on Tue Aug 11 21:59:41 2020.
Error:
 Problem: conflicting requests
  - nothing provides libtss2-fapi.so.0()(64bit) needed by tpm2-tools-4.2.1-3.fc33.x86_64
  - nothing provides libtss2-sys.so.0()(64bit) needed by tpm2-tools-4.2.1-3.fc33.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

Due to the json-c dependency of the tpm2-tss, I couldn't find any workaround for this now. A new release of the tpm2-tools, with this new tss version could solve the issue.

**Comment by williamcroberts** [comment]
tools 5.0 will be for this: https://github.com/tpm2-software/tpm2-tools/milestone/17

But since their is a lot of work left on the 5.0 milestone, we could do a 4.X release that has the API/ABI updates and then the packagers could pick that up.

**Comment by williamcroberts** [comment]
FYI I am testing 4.2.1-14-g5227e4cc1a3a (the tip of 4.2.X) and normal tpm2_<xxx> tools all seem to work with tpm2-tss 3.0. However, the fapi, tss2_<xxx> tools do not seem to be working.

**Comment by williamcroberts** [comment]
All tools seem to be working, local setup issue. So this is really that the packager hasn't provided binaries for the newer library. Not much I can do to help with that. Contact the package maintainer. However, with that said, I will be releasing a 4.2.2, as we need it: https://github.com/tpm2-software/tpm2-tools/milestone/21

**Comment by hajnalmt** [comment]
Thank you for the update.
I'm hoping they will release with the new package soon.
They have a ticket about it already, and the builds passed today.
https://bugzilla.redhat.com/show_bug.cgi?id=1868852
