### ISSUE TITLE
tpm2_nvincrement: nvdefine example fails with "NV-Index handles are not supported"

### ISSUE THREAD

**Issue by osresearch** [tpm2-software/tpm2-tools#2176]
The documentation for `tpm2_nvincrement` has this example:
```
tpm2_nvdefine -C 0x1500016 -s 8 -a "ownerread|policywrite|ownerwrite|nt=1" \
0x1500016 -p index
```

This fails with:
```
ERROR: NV-Index handles are not supported by this command.
```

Changing the `-C 0x150016` to `-C o` to create it in the owner hierarchy works (as does leaving it blank), although the `nvincrement` fails with this error:

```
# tpm2_nvincrement 0x1500016 -P index
ERROR:esys:src/tss2-esys/api/Esys_NV_Increment.c:109:Esys_NV_Increment() Esys Finish ErrorCode (0x0000012f)
```

**Comment by idesai** [comment]
@osresearch, check out [this](https://github.com/tpm2-software/tpm2-tools/blob/86fe82c6ed82464338549c1c863a38eccf5e3821/test/integration/tests/nvinc.sh#L71). Is this what you were trying?

**Comment by idesai** [comment]
The man page example is broken. Try this instead.
tpm2_nvdefine -C o -s 8 -a "ownerread|authread|authwrite|nt=1" 0x1500016 -p index
tpm2_nvincrement -C 0x1500016  0x1500016 -P "index"

**Comment by osresearch** [comment]
It looks like there are two issues with the example in the docs -- the `nvdefine` should have `-C owner`, as well as the `nvincrement` and `nvread`:

```
# tpm2 nvdefine -C owner -s 8 -a "ownerread|policywrite|ownerwrite|nt=counter" 0x1500016
# tpm2 nvincrement -C owner 0x1500016
# tpm2 nvread -C owner 0x1500016 | xxd -g8
00000000: 000000000010c
```

I'm not certain what the `-p index` argument is supposed to do -- if I add it to the `nvdefine`, it doesn't seem to be required for the increment or read programs.

**Comment by osresearch** [comment]
Oh, I think I see -- if increment or read is called with the context of the nvram object, it requires the password, but since I'm calling it from owner context then no password (or the owner password) would be required.

**Comment by idesai** [comment]
> Oh, I think I see -- if increment or read is called with the context of the nvram object, it requires the password, but since I'm calling it from owner context then no password (or the owner password) would be required.

Right. Also -p index is setting the index specific auth. Did the example I pasted above worked for you?

**Comment by idesai** [comment]
@osresearch  there is a PR to fix the man, please take a look https://github.com/tpm2-software/tpm2-tools/pull/2177

**Comment by osresearch** [comment]
Yes, that does work, and the index auth appears to be default, so the examples could be simplified to:
```
tpm2 nvdefine 0x1500016 -s 8 -a 'ownerread|authread|authwrite|nt=counter' -p 'secretpassword'
tpm2 nvincrement 0x1500016 -P 'secretpassword'
tpm2 nvread 0x1500016 -P 'secretpassword' | xxd -g8
```

I was confused since using "`index`" and "`owner`" as the passwords in the examples isn't clear to a new user where it is a required magic word (such as `-C owner`), versus a user-selectable password. Something like `-p secretpassword` and `-P secretpassword` might make it more understandable.

Using `nt=counter` is also more explicit since I haven't found where the magic values for the nt are defined in [the big spec](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-2-Structures-01.38.pdf)
