### ISSUE TITLE
Issue Debugging the locking mechanism blocking the TPM-Platform Configuration Registers(PCR)

### ISSUE THREAD

**Issue by kaushendra** [tpm2-software/tpm2-tools#2178]
Hi,

I'm Performing TPM2-PCR Commands using TPM2-Tools
I'm using TPM2-TOOLS-version="3.0.2-1179-g3e8847c"

**with the usage of following commands:**
```
tpm2 pcrextend
tpm2 pcr_read
tpm2_pcrreset (only applicale to PCR>16)
```
I looked some TPM Reference Documents mentioning usage of PCR(0-7) for System Measure Storage.But as  if we Provide Power-on-reset to TPM2.0 , PCR value(0-7) gets Resets also.

I need to know any mechanism or Command to lock/Un-lock by authority for PCR(0-7) once we put System Measure into It. 
**Note: Also i need some Solution to bring TPM2.0  to normal state or Clear Once it Gone in  LOCKOUT  State**

Thanks,
kaushendra

**Comment by idesai** [comment]
Look at [tpm2_pcrallocate](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_pcrallocate.1.md) and [tpm2_dictionarylockout](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_dictionarylockout.1.md]
