### ISSUE TITLE
eventlog parse failure on HP firmware

### ISSUE THREAD

**Issue by jbrindle** [tpm2-software/tpm2-tools#2179]
Any idea what is going on here? 

The binary_bios_measurements_parser.py script can parse this but tpm2_eventlog cannot. 

[root@localhost ~]# cat /sys/kernel/security/tpm0/binary_bios_measurements > log.bin
[root@localhost ~]# tpm2_eventlog log.bin
---
ERROR: SpecID eventType must be EV_NO_ACTION
ERROR: failed to parse tpm2 eventlog
ERROR: Unable to run tpm2_eventlog

[root@localhost ~]# fwupdmgr get-devices
HP ProBook 650 G5 System Firmware
  DeviceId:             82c0b707f7573e30fa548ff4ea37b53f4c9b5bf6
  Guid:                 dd29e2bb-b1f4-4c14-9f4d-9848d7fd5e09
  Guid:                 68264ab0-73cb-5572-a217-6ba4482083d2
  Guid:                 230c8b18-8d9b-53ec-838b-6cfc0383493a
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|registered|needs-reboot
  Version:              0.1.769
  VersionLowest:        0.0.1
  Icon:                 computer
  Created:              2020-08-22

**Comment by williamcroberts** [comment]
I'm guessing the parser doesn't handle EV_EFI_ACTION events. So I think we would need to add support. Any chance you can send us a reference log we can test against?

**Comment by jbrindle** [comment]
Sure thing. Attached. 
[bin.log](https://github.com/tpm2-software/tpm2-tools/files/5119537/bin.log)
