### ISSUE TITLE
tpm2_unseal

### ISSUE THREAD

**Issue by brpatel12** [tpm2-software/tpm2-tools#2181]
I'm trying to run the example in: [tpm2_unseal examples](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_unseal.1.md) but am getting the following error on the tpm2_create command.

Eventual goal is to encrypt/decrypt a PEM encoded RSA private key (in the following example an arbitrary file was used).

Here'e exactly what I did:
```
brpatel@laptop:~$ sudo -i
root@laptop:~# tpm2_createprimary -c primary.ctx -Q
root@laptop:~# tpm2_pcrread -Q -o pcr.bin sha256:0,1,2,3
root@laptop:~# tpm2_createpolicy -Q --policy-pcr -l sha256:0,1,2,3 -f pcr.bin -L pcr.policy
root@laptop:~# echo "my sealed data" > seal.dat

root@laptop:~# ls
dead.letter  pcr.bin  pcr.policy  primary.ctx seal.dat

root@laptop:~# tpm2_create -C primary.ctx -L pcr.policy -i seal.dat -u seal.pub -r seal.priv -c seal.ctx -Q
WARNING:esys:src/tss2-esys/api/Esys_CreateLoaded.c:355:Esys_CreateLoaded_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_CreateLoaded.c:129:Esys_CreateLoaded() Esys Finish ErrorCode (0x000b0143) 
ERROR: Esys_CreateLoaded(0xB0143) - rmt:error(2.0): command code not supported
ERROR: Unable to run tpm2_create

**Comment by idesai** [comment]
@brpatel12 it is what the error says the specific command is not supported on your TPM.  To confirm run the following.
```bash
tpm2_getcap commands | grep -i createloaded
```
You will have to perform the create and load operations separately, in that case, using tpm2_create and tpm2_load.

**Comment by williamcroberts** [comment]
> @brpatel12 it is what the error says the specific command is not supported on your TPM. To confirm run the following.
> 
> ```shell
> tpm2_getcap commands | grep -i createloaded
> ```
> 
> You will have to perform the create and load operations separately, in that case, using tpm2_create and tpm2_load.

@idesai, I see a feature here. we detect this condition in the tool (before calling createloaded) and perform the tpm2_create and tpm2_load to emulate the createloaded.

**Comment by idesai** [comment]
@williamcroberts, somehow this fell off our to-do list.  Ideally tpm2_create and tpm2_createloaded should be separate tools — 
Man page description of createloaded is a misnomer because unlike tpm2_create:
1. createloaded can create both primary keys under hierarchy and child keys
2. createloaded cannot take inputs like outsideInfo and creationPCR — sufficient to totally change cpHash data
3. createloaded yields the object name additionally but does not return creationData creationHash and creationTicket — sufficient to totally change rpHash.

While point-2 and point-3 will mess with tools like certifycreation and policycphash
point-1 feature cannot be enabled because the man page would be at odds in its description and inaccurately suggest createloaded is used to create child keys — which it can but totally skips it's ability to also create primary keys, yet its not the same as tpm2_createprimary because of point-2 and point-3 above.

**Comment by williamcroberts** [comment]
> @williamcroberts, somehow this fell off our to-do list. Ideally tpm2_create and tpm2_createloaded should be separate tools —
> Man page description of createloaded is a misnomer because unlike tpm2_create:
> 
> 1. createloaded can create both primary keys under hierarchy and child keys
> 2. createloaded cannot take inputs like outsideInfo and creationPCR — sufficient to totally change cpHash data
> 3. createloaded yields the object name additionally but does not return creationData creationHash and creationTicket — sufficient to totally change rpHash.
> 
> While point-2 and point-3 will mess with tools like certifycreation and policycphash
> point-1 feature cannot be enabled because the man page would be at odds in its description and inaccurately suggest createloaded is used to create child keys — which it can but totally skips it's ability to also create primary keys, yet its not the same as tpm2_createprimary because of point-2 and point-3 above.

Well it's just limited having it built into tpm2_create, but we can at least support the -c option without throwing an error. I think for item 2 in the list, the tool already throws an error if folks try and pass that.
3, same, if folks try to request those options, then the tool can just error. It should already, but maybe some error cases were missed.

We can still create a tpm2_createloaded tool to fully expose all the features if needed.

**Comment by brpatel12** [comment]
Hi, just getting back to this thread. 

I have a private key (which I'll just refer to as "data"0 which I want to encrypt with the TPM, and then store the TPM encrypted data in my local fs).
Then, I'd like some way to call tpm2_unseal (or whatever equivalent) to decrypt the TPM encrypted data (so I'll have the decrypted data in memory). That encrypted data will be stored in the filesystem across reboot, and I'd still need to be able to decrypt the data with the TPM upon reboot. 

The method I was going to follow was the example I provided in the link. Will said mechanism work, or do you have another suggestion? From your comments, it sounds like I'm loading the encrypted data into the TPM, which I do not need to do. The ideal workflow would be creating some asymmetric key pair with the TPM (where I never have access to the private key), and using the returned TPM public key to encrypt my data --> eventually call some tpm function to decrypt it with the private key.

**Comment by aliasdevelopment** [comment]
I have tried ubuntu 20.04 distro package tpm2 v4.1.1 and compiled tpm2 v5.0 using tss2 v3.0.3 which all produce the 

`ERROR: Esys_CreateLoaded(0xB0143) - rmt:error(2.0): command code not supported`

when trying the tpm2 unseal example as described.

The TPM2 device do not support the 'createloaded' command which I have checked by use of

`tpm2_getcap commands | grep -i createloaded`

How is it possible to perform the tpm2 unseal example if the device do no support 'createloaded'

**Comment by AndreasFuchsSIT** [comment]
This means that your TPM does not support the command.
Use can use the seuence of create and load in place of createloaded.

________________________________________
Von: aliasdevelopment ***@***.***>
Gesendet: Dienstag, 4. Mai 2021 12:20
An: tpm2-software/tpm2-tools
Cc: Subscribed
Betreff: Re: [tpm2-software/tpm2-tools] tpm2_unseal (#2181)

I have tried ubuntu 20.04 distro package tpm2 v4.1.1 and compiled tpm2 v5.0 using tss2 v3.0.3 which all produce the

ERROR: Esys_CreateLoaded(0xB0143) - rmt:error(2.0): command code not supported

when trying the tpm2 unseal example as described.

The TPM2 device do not support the 'createloaded' command which I have checked by use of

tpm2_getcap commands | grep -i createloaded

How is it possible to perform the tpm2 unseal example if the device do no support 'createloaded'

**Comment by williamcroberts** [comment]
> I have tried ubuntu 20.04 distro package tpm2 v4.1.1 and compiled tpm2 v5.0 using tss2 v3.0.3 which all produce the
> 
> `ERROR: Esys_CreateLoaded(0xB0143) - rmt:error(2.0): command code not supported`
> 
> when trying the tpm2 unseal example as described.
> 
> The TPM2 device do not support the 'createloaded' command which I have checked by use of
> 
> `tpm2_getcap commands | grep -i createloaded`
> 
> How is it possible to perform the tpm2 unseal example if the device do no support 'createloaded'

Yes do not use the `-c` option on `tpm2_create`. Just take the `-u` and `-r` from `tpm2_create` and pass them to `tpm2_load`. That will always work.

```bash
tpm2_createprimary -c primary.ctx
echo "sealdata" | tpm2_create -C primary.ctx -pmypass -u seal.pub -r seal.priv -i-
tpm2_load -C primary.ctx -u seal.pub -r seal.priv -c seal.ctx
tpm2_unseal -c seal.ctx -p mypass
```

**Comment by aliasdevelopment** [comment]
Thank you for the feedback. Your example worked as expected.

**Comment by williamcroberts** [comment]
> Thank you for the feedback. Your example worked as expected.
> 
> Unsure how often a TPM2 device do not support 'createloaded', but this example would be nice in the man pages.

Quite often. It's been documented in the tpm2_create -c example in the man page since commit 866ab005 which has been on releases 4.0+ here: https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_create.1.md#create-an-ec-key-object-and-load-it-to-the-tpm

Is their something not clear, like perhaps adding to that and saying not all TPM's support create loaded and thus should use tpm2_load?

**Comment by aliasdevelopment** [comment]
Based on my updated understanding the tpm2_create man make sense, but when you are new to tpm it is not obvious that the unseal https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_unseal.1.md example needs special treatment when you are missing TPM capabilities.

A reference from https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_unseal.1.md to https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_create.1.md would be nice statement this must be used instead if createloaded is not available

**Comment by williamcroberts** [comment]
> Based on my updated understanding the tpm2_create man make sense, but when you are new to tpm it is not obvious that the unseal https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_unseal.1.md example needs special treatment when you are missing TPM capabilities.
> 
> A reference from https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_unseal.1.md to https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_create.1.md would be nice statement this must be used instead if createloaded is not available

See https://github.com/tpm2-software/tpm2-tools/pull/2720
