### ISSUE TITLE
tss2 tools shouldn't try to run api initialize routines when options like --help or --version are invoked

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tools#2183]

**Comment by AndreasFuchsSIT** [comment]
@cplappert Could you take care of this please

**Comment by cplappert** [comment]
@AndreasFuchsSIT : We currently use Fapi_GetInfo() to retrieve the api version string when using the --version option. In this case we need the API initialization. Should this be removed?

**Comment by AndreasFuchsSIT** [comment]
I guess since the `tpm2_*` tools do not provide an esys-version, we don't need to provide a fapi-version here.

**Comment by idesai** [comment]
Fixed via #2203
