### ISSUE TITLE
Prebuilt FAPI manpages are missing from 4.3.0 

### ISSUE THREAD

**Issue by salahcoronya** [tpm2-software/tpm2-tools#2189]
I am unable to compile 4.3.0 on my system (Gentoo) because FAPI is enabled, the prebuilt man pages for FAPI not present, and pandoc is not installed on my system.

**Comment by williamcroberts** [comment]
The manpages are distributed prebuilt in the release archive. IIRC Gentoo builds things from source, is that right? So either point that build system to the release archive:
  - https://github.com/tpm2-software/tpm2-tools/releases/download/4.3.0/tpm2-tools-4.3.0.tar.gz

or install pandoc to build the man pages. Would that work?

**Comment by salahcoronya** [comment]
That's the problem, the prebuilt FAPI mapages are missing from that archive. I'm the maintainer of the package in Gentoo and I would I like to avoid having the package require pandoc, because that pulls in Haskell and all of its dependencies. 

See `tar ztvf tpm2-tools-4.3.0.tar.gz  | grep \.1$`. The tss2_ prebuilt manpages are missing.

**Comment by markarnott** [comment]
I am also having problems with release 4.3.0 needing pandoc.

I am building from the release archive tpm2-tools-4.3.0.tar.gz not from a git clone.
I am on ubuntu 20.04.  I do not have pandoc installed.  ( I did not need it with release 4.2.1)

Compilation halts with the following error message:

>   GEN      man/man1/tss2_list.1
> /bin/bash: line 38: pandoc: command not found
> make: *** [Makefile:6999: man/man1/tss2_list.1] Error 127

**Comment by williamcroberts** [comment]
Got it, I will re-upload with the FAPI prebuilts. My release build machine didn't have FAPI installed.

**Comment by williamcroberts** [comment]
I re-uploaded the tarball, my apologies. I am heading away, but @idesai can you verify the new upload fixed their issues and if so close this ticket?

**Comment by markarnott** [comment]
@williamcroberts This fixed the tools build issue, but now when I run some tools I get a symbol lookup error.

>symbol lookup error: tpm2_createprimary: undefined symbol: Esys_GetSysContext

This seems to be a different problem.  I am linking with tpm2-tss version 3.0.0.  I will roll-back my vm and try to use tpm2-tss version 2.4.2

**Comment by williamcroberts** [comment]
@markarnott all the following tags contain the relevant tss commit https://github.com/tpm2-software/tpm2-tss/commit/ece734f40413bf2995ebe9c496cbe169f90d8231

Perhaps old version kicking around, what does ldd show it resolving to? did you run ldconfig?

```bash
git tag --contains ece734f404
- 2.4.0
- 2.4.1
- 2.4.2
- 3.0.0
```

**Comment by markarnott** [comment]
yes I ran ldconfig.

ldd shows the following:

ldd /usr/local/bin/tpm2_createprimary 
	linux-vdso.so.1 (0x00007fff26516000)
	libtss2-esys.so.0 => /lib/x86_64-linux-gnu/libtss2-esys.so.0 (0x00007f5da988a000)
	libtss2-mu.so.0 => /lib/x86_64-linux-gnu/libtss2-mu.so.0 (0x00007f5da9843000)
	libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f5da956d000)
	libtss2-tctildr.so.0 => /lib/x86_64-linux-gnu/libtss2-tctildr.so.0 (0x00007f5da9564000)
	libtss2-rc.so.0 => /lib/x86_64-linux-gnu/libtss2-rc.so.0 (0x00007f5da955a000)
	libtss2-sys.so.1 => /lib/libtss2-sys.so.1 (0x00007f5da952f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5da933b000)
	libtss2-sys.so.0 => /lib/x86_64-linux-gnu/libtss2-sys.so.0 (0x00007f5da9319000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5da9313000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5da92f0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5da9944000)

it is a dev vm.  I thought it was clean, but I will roll-back and make sure it is clean and try again.

Thanks for your help

**Comment by idesai** [comment]
> yes I ran ldconfig.
> 
> ldd shows the following:
> 
> ldd /usr/local/bin/tpm2_createprimary
> linux-vdso.so.1 (0x00007fff26516000)
> libtss2-esys.so.0 => /lib/x86_64-linux-gnu/libtss2-esys.so.0 (0x00007f5da988a000)
> libtss2-mu.so.0 => /lib/x86_64-linux-gnu/libtss2-mu.so.0 (0x00007f5da9843000)
> libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f5da956d000)
> libtss2-tctildr.so.0 => /lib/x86_64-linux-gnu/libtss2-tctildr.so.0 (0x00007f5da9564000)
> libtss2-rc.so.0 => /lib/x86_64-linux-gnu/libtss2-rc.so.0 (0x00007f5da955a000)
> libtss2-sys.so.1 => /lib/libtss2-sys.so.1 (0x00007f5da952f000)
> libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5da933b000)
> libtss2-sys.so.0 => /lib/x86_64-linux-gnu/libtss2-sys.so.0 (0x00007f5da9319000)
> libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5da9313000)
> libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5da92f0000)
> /lib64/ld-linux-x86-64.so.2 (0x00007f5da9944000)
> 
> it is a dev vm. I thought it was clean, but I will roll-back and make sure it is clean and try again.
> 
> Thanks for your help

@markarnott are you still seeing issues. I could not replicate any failure at my end with tss 2.4x

**Comment by williamcroberts** [comment]
I built against 3.0 and it was fine

**Comment by williamcroberts** [comment]
Make sure the esys binary ldd outputs is the one you built. I'll just md5sum them or something to make sure they're identical.

**Comment by markarnott** [comment]
My problem was an old build still hanging around.
Once I cleaned up and rebuilt, everything is working fine now.

Thanks for your help.
