### ISSUE TITLE
tpm2_getrandom length check wrong/inconsistent

### ISSUE THREAD

**Issue by capiman2** [tpm2-software/tpm2-tools#2198]
tpm2_getrandom (at least on my system) can only generate max 32 bytes.
When using

sudo tpm2_getrandom 33 -o random.out

only 32 bytes are written out to the file, no error message occurs.

But when using

sudo tpm2_getrandom 65536 -o random.out

a error message is displayed.

https://github.com/tpm2-software/tpm2-tools/blob/8190262c17d28d82147e7aac81ab2bea4ad1b63b/tools/tpm2_getrandom.c#L178

Convert to uint16 and return an error if nr is >= 65536.

Perhaps add check for number < 32? I think this is correct way, according to spec...
Perhaps add loop to generate up to 65535 bytes as output by calling "generate 32 bytes" multiple times?

**Comment by idesai** [comment]
@capiman2 can you specify the version of the tools you are seeing this with?

Below is the output from my platform with tools off current master
```
 tpm2_getrandom 33  -T device:/dev/tpm0| xxd -p -c 33
ERROR: TPM getrandom is bounded by max hash size, which is: 32
Please lower your request (preferred) and try again or use --force (advanced)
ERROR: Unable to run tpm2_getrandom

tpm2_getrandom 33 -o rand.out  -T device:/dev/tpm0
ERROR: TPM getrandom is bounded by max hash size, which is: 32
Please lower your request (preferred) and try again or use --force (advanced)
ERROR: Unable to run tpm2_getrandom
```

**Comment by capiman2** [comment]
It is on a Raspi CM3+
uname -a
Linux raspberrypi 5.4.51-v7+ #1327 SMP Thu Jul 23 10:58:46 BST 2020 armv7l GNU/Linux

pi@raspberrypi:~/scripts $ sudo tpm2_getrandom --version
tool="tpm2_getrandom" version="3.1.3" tctis="dynamic" tcti-default=device dlclose=enabled
pi@raspberrypi:~/scripts $ sudo apt list tpm2-tools
Listing... Done
tpm2-tools/stable,now 3.1.3-2 armhf [installed]
pi@raspberrypi:~/scripts $

pi@raspberrypi:~/scripts $ sudo tpm2_getrandom 33  -T device:/dev/tpm0| xxd -p -c 33
307844432030784343203078384420307844302030784345203078363520307838
442030783738203078334420307834352030784337203078414220307830362030
784636203078374120307837332030783937203078454320307841322030784437
203078303820307834322030783430203078373920307836322030783045203078
3935203078333820307846432030783134203078433520307834410a
pi@raspberrypi:~/scripts $ sudo tpm2_getrandom 33 -o rand.out  -T device:/dev/tpm0
pi@raspberrypi:~/scripts $ ls -l rand.out
-rw-r--r-- 1 root root 32 Sep 16 08:31 rand.out
pi@raspberrypi:~/scripts $

**Comment by williamcroberts** [comment]
> It is on a Raspi CM3+
> uname -a
> Linux raspberrypi 5.4.51-v7+ #1327 SMP Thu Jul 23 10:58:46 BST 2020 armv7l GNU/Linux
> 
> ```
> pi@raspberrypi:~/scripts $ sudo tpm2_getrandom --version
> tool="tpm2_getrandom" version="3.1.3" tctis="dynamic" tcti-default=device dlclose=enabled
> pi@raspberrypi:~/scripts $ sudo apt list tpm2-tools
> Listing... Done
> tpm2-tools/stable,now 3.1.3-2 armhf [installed]
> pi@raspberrypi:~/scripts $
> 
> pi@raspberrypi:~/scripts $ sudo tpm2_getrandom 33  -T device:/dev/tpm0| xxd -p -c 33
> 307844432030784343203078384420307844302030784345203078363520307838
> 442030783738203078334420307834352030784337203078414220307830362030
> 784636203078374120307837332030783937203078454320307841322030784437
> 203078303820307834322030783430203078373920307836322030783045203078
> 3935203078333820307846432030783134203078433520307834410a
> pi@raspberrypi:~/scripts $ sudo tpm2_getrandom 33 -o rand.out  -T device:/dev/tpm0
> pi@raspberrypi:~/scripts $ ls -l rand.out
> -rw-r--r-- 1 root root 32 Sep 16 08:31 rand.out
> pi@raspberrypi:~/scripts $
> ```
> 
> Perhaps my version is just too old and I must change to a newer version or latest, to have it fixed.
> I will try to compile latest version myself and retest.

The TPM will only return up to max hash len bytes, so if your TPM only supports SHA256, it will truncate them silently to 32 bytes.
Per the [spec](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part3_Commands_pub.pdf):
```
If bytesRequested is more than will fit into a TPM2B_DIGEST on the TPM, no error is returned but the
TPM will only return as much data as will fit into a TPM2B_DIGEST buffer for the TPM.
```

On newer TPM2 tools versions than 4.0 we don't check for this and error, however on newer tools versions 4.0+, (commit 0292a4de5fc) we check that the output size == requested size and error if not equal.
