### ISSUE TITLE
tpm2_hmac example has invalid option for tpm2_createprimary

### ISSUE THREAD

**Issue by osresearch** [tpm2-software/tpm2-tools#2205]
https://github.com/tpm2-software/tpm2-tools/blame/master/man/tpm2_hmac.1.md#L84

```
# create a primary object
tpm2_createprimary -o primary.ctx
```

`tpm2_createprimary` does not have a `-o` option. `-c` is likely what is intended?

**Comment by idesai** [comment]
That is a man page error — https://github.com/tpm2-software/tpm2-tools/blob/2bfddf823a03ee39c46c2b3c526882b51b8c9004/tools/tpm2_createprimary.c#L133

**Comment by osresearch** [comment]
Also the argument to `tpm2_create`:
```
# create an hmac key
tpm2_create -C primary.ctx -Ghmac -o hmac.key
```
