### ISSUE TITLE
tpm2_eventlog tool: missing?

### ISSUE THREAD

**Issue by IAXES** [tpm2-software/tpm2-tools#2239]
I'm looking through the latest binary release (i.e. 4.3.0), and I don't see the `tpm2_eventlog` binary in it (though there are testing scripts that appear to reference it). 

Can I please confirm if the binary should be present?

**Comment by IAXES** [comment]
To add some context, I'm using a QEMU-based VM that connects to a docker container running the TPM2 simulator via a shared Unix domain socket, and am attempting to get at the TPM2 event log so I can parse/analyze it. Even though I'm using a recent build of Linux kernel v5.8 plus SeaBios, I don't appear to see any sysfs entries (e.g. `/sys/kernel/security/tpm0`, or equivalent) that expose the event log. Is there a guide/process/etc. that helps to accomplish this, or is the use of UEFI required? If so, I'll have to re-create my VM (i.e. `debootstrap` + custom kernel).

**Comment by idesai** [comment]
https://github.com/tpm2-software/tpm2-tools/blob/48a48d606f72707306e039d8876a42c8e94ec8b8/Makefile.am#L82

**Comment by IAXES** [comment]
> 
> 
> https://github.com/tpm2-software/tpm2-tools/blob/48a48d606f72707306e039d8876a42c8e94ec8b8/Makefile.am#L82

Hmm, it seems the `tools/misc` binaries aren't shipped as part of the release tarball, i.e.:

```sh
$> find . -iname "*eventlog*"
./lib/tpm2_eventlog.c
./lib/tpm2_eventlog_yaml.c
./lib/tpm2_eventlog_yaml.h
./lib/tpm2_eventlog.h
./man/tpm2_eventlog.1.md
./man/man1/tpm2_eventlog.1
./tools/misc/tpm2_eventlog.c
./test/integration/tests/eventlog.sh
./test/unit/test_tpm2_eventlog.c
./test/unit/test_tpm2_eventlog_yaml.c
```

While on the topic, may I please confirm where the source/file that's fed into this tool should be found? It seems there's no `/sys/kernel/security/tpm0` in my setup (i.e. Ubuntu 20.04 with a custom 5.8.x series kernel and the latest SeaBIOS running in QEMU), so I'm trying to determine if that path **should** exist (i.e. is the system misconfigured), or if the data/input is found somewhere else in `sysfs` or some other location.

Thank you.

**Comment by williamcroberts** [comment]
The tools are now a commandlet tpm2 <command>, so tpm2_eventlog is now tpm2 eventlog. However, when you run make install, we symlink tpm2_eventlog --> tpm2, and then tpm2 is smart enough to parse argv[0] and see that it wants the eventlog commandlet. See PR: https://github.com/tpm2-software/tpm2-tools/pull/2077

In short, you can use the new commandlet style, but all the old commands still exist on install. You can set DESTDIR to install to a custom location, which I usually do at ~/bin, and then I just add PATH to point to where the tools are.. usually usr/local/bin unless you change it during configure with --prefix (IIRC).

So they're not missing... just install.

**Comment by idesai** [comment]
> The tools are now a commandlet tpm2 , so tpm2_eventlog is now tpm2 eventlog. However, when you run make install, we symlink tpm2_eventlog --> tpm2, and then tpm2 is smart enough to parse argv[0] and see that it wants the eventlog commandlet. See PR: #2077
> 
> In short, you can use the new commandlet style, but all the old commands still exist on install. You can set DESTDIR to install to a custom location, which I usually do at ~/bin, and then I just add PATH to point to where the tools are.. usually usr/local/bin unless you change it during configure with --prefix (IIRC).
> 
> So they're not missing... just install.

@williamcroberts I think @IAXES was referring to 4.X which did not have the busybox style implementation, right?

**Comment by IAXES** [comment]
Found the commit of interest: my understanding is that userspace apps can get at the TPM2 event log (somehow) rather than just within bootloader code: 

```
commit 85467f63a05c43364ba0b90d0c05bb89191543fa
Author: Stefan Berger <stefanb@linux.ibm.com>
Date:   Mon Jul 6 19:58:07 2020 -0400    
tpm: Add support for event log pointer found in TPM2 ACPI table    
In case a TPM2 is attached, search for a TPM2 ACPI table when trying    
to get the event log from ACPI. If one is found, use it to get the    
start and length of the log area. This allows non-UEFI systems, such    
as SeaBIOS, to pass an event log when using a TPM2.    
Cc: Peter Huewe <peterhuewe@gmx.de>    
Cc: Jason Gunthorpe <jgg@ziepe.ca>    
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>    
Reviewed-by: Jerry Snitselaar <jsnitsel@redhat.com>    
Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
```

Does the `tpm2` tool automatically find this location in the ACPI table (i.e. if I'm using a current version of SeaBios, up-to-date kernel, etc.), or is this data supposed to be in a sysfs path?

**Comment by williamcroberts** [comment]
@idesai yep, I thought that was on 4.3, but I guess not... thats a slated 5.0 feature.

Well, I just looked at the release tarball and built it, and it's there:
https://github.com/tpm2-software/tpm2-tools/releases/download/4.3.0/tpm2-tools-4.3.0.tar.gz

@IAXES you're getting a release tarball of:
sha256sum ~/Downloads/tpm2-tools-4.3.0.tar.gz 
ae009b3495b44a16faa3d94d41ac9c9d99c71723482efad53c5eea17eeed80fc  /home/wcrobert/Downloads/tpm2-tools-4.3.0.tar.gz

```bash
tar -tvf /home/wcrobert/Downloads/tpm2-tools-4.3.0.tar.gz  | grep eventlog
-rwxr-xr-x 1000/1000       849 2020-09-09 13:33 tpm2-tools-4.3.0/test/integration/tests/eventlog.sh
-rw-r--r-- 1000/1000      5675 2020-06-30 14:16 tpm2-tools-4.3.0/test/unit/test_tpm2_eventlog_yaml.c
-rw-r--r-- 1000/1000     16327 2020-09-09 13:33 tpm2-tools-4.3.0/test/unit/test_tpm2_eventlog.c
-rw-r--r-- 1000/1000     12905 2020-09-09 13:33 tpm2-tools-4.3.0/lib/tpm2_eventlog_yaml.c
-rw-r--r-- 1000/1000       842 2020-06-30 14:16 tpm2-tools-4.3.0/lib/tpm2_eventlog_yaml.h
-rw-r--r-- 1000/1000     10348 2020-09-09 13:33 tpm2-tools-4.3.0/lib/tpm2_eventlog.c
-rw-r--r-- 1000/1000      1677 2020-09-09 13:33 tpm2-tools-4.3.0/lib/tpm2_eventlog.h
-rw-r--r-- 1000/1000      1945 2020-09-09 13:33 tpm2-tools-4.3.0/tools/misc/tpm2_eventlog.c
```
```bash
tar -xavf ~/Downloads/tpm2-tools-4.3.0.tar.gz
cd tpm2-tools-4.3.0
./configure
make -j4
<snip>
  CCLD     tools/misc/tpm2_checkquote
  CCLD     tools/misc/tpm2_eventlog
  CCLD     tools/misc/tpm2_print
  CCLD     tools/misc/tpm2_rc_decode
<snip>
```

Note it's built.... now it should install as well
```bash
mkdir bin
make install DESTDIR=$(realpath bin)
find bin -name tpm2_eventlog
bin/usr/local/bin/tpm2_eventlog
bin/usr/share/bash-completion/completions/tpm2_eventlog
```

Seems there....

**Comment by williamcroberts** [comment]
> Found the commit of interest: my understanding is that userspace apps can get at the TPM2 event log (somehow) rather than just within bootloader code:
> 
> ```
> commit 85467f63a05c43364ba0b90d0c05bb89191543fa
> Author: Stefan Berger <stefanb@linux.ibm.com>
> Date:   Mon Jul 6 19:58:07 2020 -0400    
> tpm: Add support for event log pointer found in TPM2 ACPI table    
> In case a TPM2 is attached, search for a TPM2 ACPI table when trying    
> to get the event log from ACPI. If one is found, use it to get the    
> start and length of the log area. This allows non-UEFI systems, such    
> as SeaBIOS, to pass an event log when using a TPM2.    
> Cc: Peter Huewe <peterhuewe@gmx.de>    
> Cc: Jason Gunthorpe <jgg@ziepe.ca>    
> Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>    
> Reviewed-by: Jerry Snitselaar <jsnitsel@redhat.com>    
> Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
> ```
> 
> Does the `tpm2` tool automatically find this location in the ACPI table (i.e. if I'm using a current version of SeaBios, up-to-date kernel, etc.), or is this data supposed to be in a sysfs path?

sysfs path:
/sys/kernel/security/tpm0/binary_bios_measurements

**Comment by idesai** [comment]
> Found the commit of interest: my understanding is that userspace apps can get at the TPM2 event log (somehow) rather than just within bootloader code:
> 
> ```
> commit 85467f63a05c43364ba0b90d0c05bb89191543fa
> Author: Stefan Berger <stefanb@linux.ibm.com>
> Date:   Mon Jul 6 19:58:07 2020 -0400    
> tpm: Add support for event log pointer found in TPM2 ACPI table    
> In case a TPM2 is attached, search for a TPM2 ACPI table when trying    
> to get the event log from ACPI. If one is found, use it to get the    
> start and length of the log area. This allows non-UEFI systems, such    
> as SeaBIOS, to pass an event log when using a TPM2.    
> Cc: Peter Huewe <peterhuewe@gmx.de>    
> Cc: Jason Gunthorpe <jgg@ziepe.ca>    
> Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>    
> Reviewed-by: Jerry Snitselaar <jsnitsel@redhat.com>    
> Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
> ```
> 
> Does the `tpm2` tool automatically find this location in the ACPI table (i.e. if I'm using a current version of SeaBios, up-to-date kernel, etc.), or is this data supposed to be in a sysfs path?

Its supposed to be in the sysfs path— /sys/kernel/security/tpm0/binary_bios_measurements

**Comment by IAXES** [comment]
Is this the appropriate project to request additional help (i.e. if the sysfs path is missing in my QEMU + TPM2.0 simulator setup)?

**Comment by idesai** [comment]
> Is this the appropriate project to request additional help (i.e. if the sysfs path is missing in my QEMU + TPM2.0 simulator setup)?

No. But you can reach a wider audience in the [mailing-list](/sys/kernel/security/tpm0/binary_bios_measurements) or [gitter](https://gitter.im/tpm2-software/community).

**Comment by IAXES** [comment]
Thank you for your help.

**Comment by IAXES** [comment]
> 
> 
> > Is this the appropriate project to request additional help (i.e. if the sysfs path is missing in my QEMU + TPM2.0 simulator setup)?
> 
> No. But you can reach a wider audience in the [mailing-list](/sys/kernel/security/tpm0/binary_bios_measurements) or [gitter](https://gitter.im/tpm2-software/community).

May I please confirm the mailing list address? The link appears to be malformed.

**Comment by idesai** [comment]
https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/

**Comment by idesai** [comment]
> > > Is this the appropriate project to request additional help (i.e. if the sysfs path is missing in my QEMU + TPM2.0 simulator setup)?
> > 
> > 
> > No. But you can reach a wider audience in the [mailing-list](/sys/kernel/security/tpm0/binary_bios_measurements) or [gitter](https://gitter.im/tpm2-software/community).
> 
> @idesai
> 
> May I please confirm the mailing list address? The link appears to be malformed.

PEBCAK

**Comment by IAXES** [comment]
Thanks again. The discussion I posted is here: https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/FMBZO6V6QO55BER4YGIGUAYFWEB7ATAM/

+CC: @stefanberger May I please confirm the question on the intent of the `85467f63a05c43364ba0b90d0c05bb89191543fa` patch (i.e. does it make the TPM2 event log visible to userspace apps running a SeaBIOS/QEMU VM instance), or is it preferable this is addressed via e-mail or a new thread on the LKML?

**Comment by stefanberger** [comment]
@IAXES 
5.8.15 looks like this here: https://elixir.bootlin.com/linux/v5.8.15/source/drivers/char/tpm/eventlog/acpi.c#L53
5.9 has the modified code: https://elixir.bootlin.com/linux/v5.9/source/drivers/char/tpm/eventlog/acpi.c#L64

I guess the answer is 'you have to be patient a little longer'...

**Comment by IAXES** [comment]
> 
> 
> @IAXES
> 5.8.15 looks like this here: https://elixir.bootlin.com/linux/v5.8.15/source/drivers/char/tpm/eventlog/acpi.c#L53
> 5.9 has the modified code: https://elixir.bootlin.com/linux/v5.9/source/drivers/char/tpm/eventlog/acpi.c#L64
> 
> I guess the answer is 'you have to be patient a little longer'...

@stefanberger  Thank you. Is there a setup that would allow userspace access to TPM2 event logs in the meantime other than SeaBIOS (i.e. if I used an EFI-enabled BIOS with QEMU), or a quick rebuild/hack to GRUB? Or, if I just pulled the latest stable 5.9 kernel, does that auto-magically solve my problems?

Additionally, do you see any value in a Dockerized end-to-end testing/regression tool (described here: https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/LZVEXWOLZJPAZKNIEAV42MSEONIVATWS/)? I figured it'd be helpful as a training/learning tool.

**Comment by stefanberger** [comment]
@IAXES EFI should work even with older kernels, for SeaBIOS it should work with 5.9. Grub changes will not help.

I am running regression tests but I use IBM's TSS2 + test suite for TPM 2 functionality testing: https://github.com/stefanberger/swtpm/blob/master/tests/test_tpm2_ibmtss2

**Comment by IAXES** [comment]
@stefanberger Thanks! Kernel v5.9 did the trick.

https://github.com/tpm2-software/tpm2-tools/issues/2239
