### ISSUE TITLE
tpm2_eventlog fails with event logs larger than 64 KB

### ISSUE THREAD

**Issue by terryplee** [tpm2-software/tpm2-tools#2243]
When processing TCG event logs larger than 64 KB, tpm2_eventlog fails with the following error messages.

ERROR: size insufficient for event data
ERROR: failed to parse tpm2 eventlog
ERROR: Unable to run tpm2_eventlog

**Comment by idesai** [comment]
> When processing TCG event logs larger than 64 KB, tpm2_eventlog fails with the following error messages.
> 
> ERROR: size insufficient for event data
> ERROR: failed to parse tpm2 eventlog
> ERROR: Unable to run tpm2_eventlog

It should warn about truncating the data as in here:
https://github.com/tpm2-software/tpm2-tools/blob/16f7e5cb0eb88942dc2bbfef3daf06641fb6909b/tools/misc/tpm2_eventlog.c#L63-L65

**Comment by terryplee** [comment]
Yes, there is warning about truncation.  However, it would be good for tpm2_eventlog to support event logs larger than 64 KB without truncation.  64 KB is the minimum (not maximum) supported log size required by the TCG PC Client Platform Firmware Profile Specification.

**Comment by terryplee** [comment]
Thanks for looking into this.  Is this still planned for 5.1?
