### ISSUE TITLE
TPM2 Commands do not return when running with the tpm2-abrmd service

### ISSUE THREAD

**Issue by glennb-dev** [tpm2-software/tpm2-tools#2246]
I have been using the TSS2 stack for a couple weeks using only the IBM TPM Server. I was having some issues getting the TPM2 Access Broker/Resource Manager Daemon working, but finally managed to resolve some setup/configuration issues. I have noticed a couple of things however while running the TPM2 tools.

1) Running the tools in a terminal console window while the tpm2-abrmd is running, the commands do not return. I.e., when you execute, e.g. tpm2_startup or tpm2_getrandom 4, they just sit there with no response. If I turn off the tmp2-abrmd, the commands work as expected.

2) The tpm2_createprimary command is always returning with no response and an error code of 1. I have tried several variations from no arguments, to --hierarchy o --context prime.ctx and still, no output (or errors), just error code of 1. Even tried adding the '-V' flag, nothing.

3) I have run all the unit/integration/fapi tests on both the --enable-unit= mssim and abrmd configurations and all the tests have passed. So I am assuming this means they are working. 157 tests run, 156 passed, 1 skipped.

Can you provide me with some answers to these questions? I would like to start to develop a TSS2 solution, but need to understand how these calls all work in order to create my solution correctly.

Environment: Ubuntu 18.04 LTS (Bionic Beaver)
TSS2 Tool Set Version: 4.3.0-296-g96d3b567
TPM2 Abrmd Version: 2.3.3-2-g01a3f62

**Comment by glennb-dev** [comment]
Ok, I am continuing to learn things about this environment. Doing some reverse engineering, I discovered that the TPM2 Tool tests call 'tpm2 createprimary...' and not 'tpm2_createprimary'. Calling it in this manner worked. So is the tpm2 executable is the one you are supposed to use instead of the individual commands?

**Comment by idesai** [comment]
Make sure that run make install and add the installation directory to the PATH.
Quoting from the changelog—
"   - tpm2_tools and tss2_tools are now a busybox style commandlet. Ie tpm2\_getrandom becomes tpm2 getrandom.
     make install will install symlinks to the old tool names and the tpm2 commandlet will
     interogate argv[0] for the command to run. This will provide backwards compatibility
     if they are installed. If you wish to use the old names not installed system wide, set
     DESTDIR during install to a seperate path and set the proper directory on PATH."

**Comment by williamcroberts** [comment]
> Ok, I am continuing to learn things about this environment. Doing some reverse engineering, I discovered that the TPM2 Tool tests call 'tpm2 createprimary...' and not 'tpm2_createprimary'. Calling it in this manner worked. So is the tpm2 executable is the one you are supposed to use instead of the individual commands?

tpm2_createprimary is a symlink tp tpm2, it then introspects argv[0] to see what commandlet you want to invoke. However, tpm2 createprimary and tpm2_createprimary should behave the same. However, make sure you don't have 2 versions accidentally installed, ie $(which tpm2_createprimary) is indeed a symlink file. Else, you'll want to nuke that old install.

The stalling you're seeing is probably something related to TCTIs... what does `tpm2_getrandom --version` return?

**Comment by glennb-dev** [comment]
Thanks for your reply William. If I execute 'tpm2_getrandom --version' it
just returns 'tpm2_getrandom, version', that is all. If I run 'tpm2
getrandom --version', it returns 'tool='getrandom'
version='4.3.0-286-g96d3b567' tctis="libtss2-tctildr'
tcti-default=tcti-abrmd'

I will look to look to see if I have 2 versions accidentally installed. I
have been exploring a lot of different TSS solutions.

- Glenn

**Comment by glennb-dev** [comment]
I did have 2 versions of the tools on my system. I removed the tpm2-tools package and rebuilt the tss-tools project. Now all the commands are working as expected, both TPM2 <command> and the tool links. Closing ticket.
