### ISSUE TITLE
tpm2_eventlog: Validate event type (EV SEPARATOR) matches the information in the log.

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tools#2247]
Possible spoofing goes undetected when parsing the event log.

**Comment by idesai** [comment]
@mjg59 can you please provide some information and context regarding the possible spoofing that can go undetected.

**Comment by mjg59** [comment]
The event type is usually not part of the digest, and so an attacker with access to the event log can change the type while still ensuring that replay is successful. One thing they can do is to replace EV_SEPARATOR events with some other type - a validator that assumes all events before an EV_SEPARATOR are generated by the firmware and are therefore trustworthy may then be fooled by additional events introduced by the attacker. Further details are at https://github.com/google/go-attestation/blob/master/docs/event-log-disclosure.md .

**Comment by idesai** [comment]
Closed via #2264
