### ISSUE TITLE
Is this only suitable for TPM emulators?

### ISSUE THREAD

**Issue by Mykrobin** [tpm2-software/tpm2-tools#2250]
I am new in this field, I found the TPM 2.0 module on my computer, and I want to use it in Ubuntu18, what should I do? I am confused about this. Shall I follow the guidance of this install.md?

**Comment by trinity-1686a** [comment]
This project works with real TPM2.0 modules.
The easiest way to install it is probably through your distribution packet manager. On Ubuntu20.04 I can simply install with `sudo apt install tpm2-tools`, I guess the same package must be available for Ubuntu18.
You should probably clarify what you mean by wanting to use it. Simply installing the tools provided by this project won't make your setup more secure by itself,

**Comment by williamcroberts** [comment]
The tools on Ubuntu-18.04 (Bionic) are super old. I would recommend following the install.md file and install the latest 4.3.0 release from source code. The next question is, what do you want to do with it?

A great starting point is to use the tpm2.0 to generate a random number for you, this lets you make sure everything is working. You can get from an application using TPM2.0, to the TPM chip itself and back.
```bash
tpm2_getrandom --hex 4
d04b8d16
```

From there, you probably want to create keys, etc using commands like `tpm2_create`. One thing to consider is that the TPM2.0 is a physical device and may already be configured, so you need to understand if you can clear it, and if you care. Ie if you're dual booting with Windows and clear your TPM, you might have issues with Windows and Bitlocker.

There are simulators as well, so you may want to use those.

Questions like this are better asked on the mailing list mentioned in the README. You will find a much larger audience of folks willing to help.

**Comment by Mykrobin** [comment]
Thanks so much for all your help, I followed the way you guide, I successfully installed the tpm2-tools, then I get the generated random number, and I wonder if it can conduct the integrity measurement to protect my computer?

**Comment by IAXES** [comment]
@Mykrobin Is it fair to close this issue then?
