### ISSUE TITLE
tpm2_nvread human readable outputs

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#2253]
Add an option for outputting nvread data in hex, --hex

**Comment by idesai** [comment]
tpm2 nvread <> | xxd -p ?

**Comment by whooo** [comment]
It was more about getting a human readable number out of a NV counter/pin instead of doing something like:
kaka=$(tpm2_nvread 0x1000000 | xxd -p | tr "[:lower:]" "[:upper:]") ; echo -e "ibase=16\n$kaka" | bc

**Comment by williamcroberts** [comment]
> It was more about getting a human readable number out of a NV counter/pin instead of doing something like:
> kaka=$(tpm2_nvread 0x1000000 | xxd -p | tr "[:lower:]" "[:upper:]") ; echo -e "ibase=16\n$kaka" | bc

Oh so base10 numbers....

The tool just currently uses nv read to get the data, and doesn't consult the public portion of the object to determine it's type.

However, it does make the call to readpublic to check the size or get the size, so we have the info available, and don't have to make another trip to the TPM:
  - https://github.com/tpm2-software/tpm2-tools/blob/master/lib/tpm2_nv_util.h#L117

So we could modify that interface to pass back the public portion of the object, and see if it's a type where a base10 number makes more sense. But this would break existing scripts....

We would have to plumb this as a new-option, since this behavioral change is likely to cause issues in existing scripts.
I am not sure of the best way to do this, perhaps something like `--format=d` `--format=x`

Then these would be arbitrary by design, and we could use something like OpenSSL to take a hunk of bytes and output them as a number via this psuedo code:
```C
tpm2_nv_read(data, len);

if (format != binary) {
    /* im not sure how you know the endianess... by your sample code it looks to be in native endianess */
    if (HOST_LE) {
        BN_lebin2bn(data, len, bn);
    } else {
        BN_bin2bn(data, len, bn);
    }

    if (format.x) {
        printf(BN_bn2hex(bn);
    } else {
        printf(BN_bn2dec(bn);
    }
} else {
  // output binary
}
```
