### ISSUE TITLE
Cannot reset disableClear with tpm2_clearcontrol

### ISSUE THREAD

**Issue by dnoliver** [tpm2-software/tpm2-tools#2256]
This is reproducible with a vanilla VM on HyperV with Fedora Server 32 using a vTPM.
TPM Software Stack is installed from the rpm repos.
vTPM is in default state.

```shell
[root@test-1 test]# cat /etc/redhat-release
Fedora release 32 (Thirty Two)

[root@test-1 test]# uname -a
Linux test-1.mshome.net 5.6.6-300.fc32.x86_64 #1 SMP Tue Apr 21 13:44:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[root@test-1 test]# rpm -qa tpm2*
tpm2-tss-engine-1.0.1-2.fc32.x86_64
tpm2-tss-2.4.3-1.fc32.x86_64
tpm2-pkcs11-tools-1.3.2-1.fc32.x86_64
tpm2-tools-4.1.3-1.fc32.x86_64
tpm2-pkcs11-1.3.2-1.fc32.x86_64

# Starting State: disableClear is 0
[root@test-1 test]# tpm2_getcap properties-variable
TPM2_PT_PERSISTENT:
  ownerAuthSet:              0
  endorsementAuthSet:        0
  lockoutAuthSet:            0
  reserved1:                 0
  disableClear:              0
  inLockout:                 0
  tpmGeneratedEPS:           1
  reserved2:                 0
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  0
  shEnable:                  1
  ehEnable:                  1
  phEnableNV:                1
  reserved1:                 0
  orderly:                   1
TPM2_PT_HR_NV_INDEX: 0x2
TPM2_PT_HR_LOADED: 0x0
TPM2_PT_HR_LOADED_AVAIL: 0x3
TPM2_PT_HR_ACTIVE: 0x0
TPM2_PT_HR_ACTIVE_AVAIL: 0x40
TPM2_PT_HR_TRANSIENT_AVAIL: 0x3
TPM2_PT_HR_PERSISTENT: 0x0
TPM2_PT_HR_PERSISTENT_AVAIL: 0x6
TPM2_PT_NV_COUNTERS: 0x0
TPM2_PT_NV_COUNTERS_AVAIL: 0x20
TPM2_PT_ALGORITHM_SET: 0x0
TPM2_PT_LOADED_CURVES: 0x3
TPM2_PT_LOCKOUT_COUNTER: 0x2
TPM2_PT_MAX_AUTH_FAIL: 0x3
TPM2_PT_LOCKOUT_INTERVAL: 0x3E8
TPM2_PT_LOCKOUT_RECOVERY: 0x3E8
TPM2_PT_AUDIT_COUNTER_0: 0x0
TPM2_PT_AUDIT_COUNTER_1: 0x0

[root@test-1 test]# tpm2_clearcontrol -C l s

# disableClear is now 1
[root@test-1 test]# tpm2_getcap properties-variable
TPM2_PT_PERSISTENT:
  ownerAuthSet:              0
  endorsementAuthSet:        0
  lockoutAuthSet:            0
  reserved1:                 0
  disableClear:              1
  inLockout:                 0
  tpmGeneratedEPS:           1
  reserved2:                 0
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  0
  shEnable:                  1
  ehEnable:                  1
  phEnableNV:                1
  reserved1:                 0
  orderly:                   1
TPM2_PT_HR_NV_INDEX: 0x2
TPM2_PT_HR_LOADED: 0x0
TPM2_PT_HR_LOADED_AVAIL: 0x3
TPM2_PT_HR_ACTIVE: 0x0
TPM2_PT_HR_ACTIVE_AVAIL: 0x40
TPM2_PT_HR_TRANSIENT_AVAIL: 0x3
TPM2_PT_HR_PERSISTENT: 0x0
TPM2_PT_HR_PERSISTENT_AVAIL: 0x6
TPM2_PT_NV_COUNTERS: 0x0
TPM2_PT_NV_COUNTERS_AVAIL: 0x20
TPM2_PT_ALGORITHM_SET: 0x0
TPM2_PT_LOADED_CURVES: 0x3
TPM2_PT_LOCKOUT_COUNTER: 0x2
TPM2_PT_MAX_AUTH_FAIL: 0x3
TPM2_PT_LOCKOUT_INTERVAL: 0x3E8
TPM2_PT_LOCKOUT_RECOVERY: 0x3E8
TPM2_PT_AUDIT_COUNTER_0: 0x0
TPM2_PT_AUDIT_COUNTER_1: 0x0

# Clear is disabled as expected
[root@test-1 test]# tpm2_clear
WARNING:esys:src/tss2-esys/api/Esys_Clear.c:291:Esys_Clear_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Clear.c:97:Esys_Clear() Esys Finish ErrorCode (0x00000120)
ERROR: Esys_Clear(0x120) - tpm:error(2.0): the command is disabled
ERROR: Unable to run tpm2_clear

# Try to clear the disableBit with Lockout (l) hierarchy results in an error
[root@test-1 test]# tpm2_clearcontrol -C l c
ERROR: Only platform hierarchy handle can be specified for CLEAR operation on disableClear
ERROR: Unable to run tpm2_clearcontrol

# Try to clear the disableBit with Platform (p) hierarchy results in an error
[root@test-1 test]# tpm2_clearcontrol -C p c
WARNING:esys:src/tss2-esys/api/Esys_ClearControl.c:293:Esys_ClearControl_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_ClearControl.c:101:Esys_ClearControl() Esys Finish ErrorCode (0x00000185)
ERROR: Esys_ClearControl(0x185) - tpm:handle(1):hierarchy is not enabled or is not correct for the use
ERROR: Unable to run tpm2_clearcontrol

# checking if tpm2_clear is now available
[root@test-1 test]# tpm2_clear
WARNING:esys:src/tss2-esys/api/Esys_Clear.c:291:Esys_Clear_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Clear.c:97:Esys_Clear() Esys Finish ErrorCode (0x00000120)
ERROR: Esys_Clear(0x120) - tpm:error(2.0): the command is disabled
ERROR: Unable to run tpm2_clear
```

Is this expected behavior?
If so, how do you clear the disableClear bit?
Where is the Platform Authorization handle?

**Comment by idesai** [comment]
@dnoliver your problem is that platform hierarchy is unavailable to you on the TPM you are working with.
```
  phEnable:                  0
```

**Comment by dnoliver** [comment]
Ok, looks like it is expected behavior then.

So, if `phEnable = 0`, setting the `disableClear` bit is permanent?
There is no way to go back, other than resetting the TPM from the BIOS, or deleting/recreating the VM?

**Comment by idesai** [comment]
> Ok, looks like it is expected behavior then.
> 
> So, if `phEnable = 0`, setting the `disableClear` bit is permanent?
> There is no way to go back, other than resetting the TPM from the BIOS, or deleting/recreating the VM?

Yep. This is one of the TPM gotchas, unfortunately.

**Comment by dnoliver** [comment]
I am sure it is described in one of the hundreds TCG documents 👍 

Should `tpm2_clearcontrol` help the user to not run into this error, by checking if `phEnabled = 0` and asking for confirmation before doing a permanent action?

On the other hand, in the NUC where we run into this problem we have `phEnabled = 1` and `phEnableNV = ``:

```shell
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  1
  shEnable:                  1
  ehEnable:                  1
  phEnableNV:                1
  reserved1:                 0
  orderly:                   0
```

How do you use that Platform Authorization to reset the `disableClear` bit in this case?

**Comment by idesai** [comment]
> I am sure it is described in one of the hundreds TCG documents 👍
> 
> Should `tpm2_clearcontrol` help the user to not run into this error, by checking if `phEnabled = 0` and asking for confirmation before doing a permanent action?
> 
> On the other hand, in the NUC where we run into this problem we have `phEnabled = 1` and `phEnableNV = 1`:
> 
> ```shell
> TPM2_PT_STARTUP_CLEAR:
>   phEnable:                  1
>   shEnable:                  1
>   ehEnable:                  1
>   phEnableNV:                1
>   reserved1:                 0
>   orderly:                   0
> ```
> 
> How do you use that Platform Authorization to reset the `disableClear` bit in this case?

I think there should be a blue-wire/ jumper configuration on the main-board which should bring up a slew of TPM options at the startup that execute commands using TPM platform hierarchy auth.

**Comment by idesai** [comment]
> I am sure it is described in one of the hundreds TCG documents 👍
> 
> Should `tpm2_clearcontrol` help the user to not run into this error, by checking if `phEnabled = 0` and asking for confirmation before doing a permanent action?
> 
> On the other hand, in the NUC where we run into this problem we have `phEnabled = 1` and `phEnableNV = 1`:
> 
> ```shell
> TPM2_PT_STARTUP_CLEAR:
>   phEnable:                  1
>   shEnable:                  1
>   ehEnable:                  1
>   phEnableNV:                1
>   reserved1:                 0
>   orderly:                   0
> ```
> 
> How do you use that Platform Authorization to reset the `disableClear` bit in this case?

I like the option of something like using ```--force```, we have to explore how we can do that in a 4.X backward-compatible way. I am worried that if this was used in a script somewhere and if implemented this way, it will break their security model.
