### ISSUE TITLE
Installation of tpm2-tools tss fails 

### ISSUE THREAD

**Issue by vponnuru23** [tpm2-software/tpm2-tools#2259]
Tried installing tpm2-tss by following instructions: https://github.com/tpm2-software/tpm2-tools/blob/master/doc/INSTALL.md 

OS: Ubuntu 20.4

Installation failed: 
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'src/tss2-fapi/libtss2-fapi.la' with the above command before installing it
make[1]: *** [Makefile:9310: install-libLTLIBRARIES] Error 1

**Comment by idesai** [comment]
Addressed in tpm2-tss https://github.com/tpm2-software/tpm2-tss/issues/1890
