### ISSUE TITLE
Persistent objects can't be persistent by using a loaded transient object handle #489

### ISSUE THREAD

**Issue by penpendandan** [tpm2-software/tpm2-tools#2260]
when I run the following command, I get a error: EvictControl Failed, error code: 0xc1000.

tpm2_evictcontrol -A o -H 0x80000000 -S 0x81010004
I have create a primary key by:
tpm2_createprimary -A e -g 0x000B -G 0x0001
the primary key has been created and the handle is 0x80000000.

**Comment by idesai** [comment]
@penpendandan, what is the error, and what version of the tools are you using?
