### ISSUE TITLE
tpm2_getekcertificate returns exit code 0 when certificate was not found

### ISSUE THREAD

**Issue by dnoliver** [tpm2-software/tpm2-tools#2273]
Version of the TPM2 Tools are 4.3 tagged release, compiled from source.

```shell
[test@fedora-server curl]$ tpm2_createek -G rsa -u ek.pub -c key.ctx

[test@fedora-server curl]$ ls
ek.pub  key.ctx

[test@fedora-server curl]$ tpm2_getekcertificate -u ek.pub
Certificate not found

[test@fedora-server curl]$ echo $?
0
```

Expected behavior is to fail with non zero exit code if the certificate was not found.

Hint: Looks like CURL returns CURL_OK despite HTTP 404 errors. It needs a flag like https://curl.se/libcurl/c/CURLOPT_FAILONERROR.html

**Comment by idesai** [comment]
Fixed in #2272 and #2271
