### ISSUE TITLE
Encrypted session not working

### ISSUE THREAD

**Issue by wenxinleong** [tpm2-software/tpm2-tools#2278]
Im trying to get encrypted session to work but without any success. Is encrypted session implemented in tpm2-tools?

tpm2-tss v2.4.0
tpm2-tools v4.2

Here is an example which works well without encrypted session enabled:
```
tpm2_startup -c
tpm2_clear -c p

tpm2_createprimary -p pass1 -c primary.ctx
tpm2_evictcontrol -C o -c primary.ctx 0x81000000
tpm2_flushcontext 0x80000000

tpm2_startauthsession -S session.ctx
tpm2_policypassword -S session.ctx -L policy.dat
tpm2_flushcontext session.ctx

tpm2_create -G rsa -P pass1 -p pass2 -C 0x81000000 -u rsa.pub -r rsa.priv -L policy.dat
tpm2_load -P pass1 -C primary.ctx -u rsa.pub -r rsa.priv -c rsa.ctx
tpm2_evictcontrol -C o -c rsa.ctx 0x81000001

echo "ffffffff" > msg.txt
xxd -r -p msg.txt msg.dat
tpm2_rsaencrypt -c 0x81000001 -o msg.enc msg.dat

tpm2_startauthsession --policy-session -S session.ctx
tpm2_policypassword -S session.ctx
tpm2_rsadecrypt -c 0x81000001 -p session:session.ctx+pass2 -o msg.plain msg.enc
tpm2_flushcontext session.ctx
```

TPM throws error once encrypted session is enabled:
```
tpm2_startup -c
tpm2_clear -c p

tpm2_createprimary -p pass1 -c primary.ctx
tpm2_evictcontrol -C o -c primary.ctx 0x81000000
tpm2_flushcontext 0x80000000

tpm2_startauthsession -S session.ctx
tpm2_policypassword -S session.ctx -L policy.dat
tpm2_flushcontext session.ctx

tpm2_create -G rsa -P pass1 -p pass2 -C 0x81000000 -u rsa.pub -r rsa.priv -L policy.dat
tpm2_load -P pass1 -C primary.ctx -u rsa.pub -r rsa.priv -c rsa.ctx
tpm2_evictcontrol -C o -c rsa.ctx 0x81000001

echo "ffffffff" > msg.txt
xxd -r -p msg.txt msg.dat
tpm2_rsaencrypt -c 0x81000001 -o msg.enc msg.dat

tpm2_startauthsession --policy-session -c 0x81000000 -S session.ctx
tpm2_policypassword -S session.ctx
tpm2_rsadecrypt -c 0x81000001 -p session:session.ctx+pass2 -o msg.plain msg.enc
```
**WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:305:Esys_RSA_Decrypt_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x00000084)
ERROR: Esys_RSA_Decrypt(0x84) - tpm:handle(unk):value is out of range or is not correct for the context
ERROR: Unable to run tpm2_rsadecrypt**
```
tpm2_flushcontext session.ctx
```

**Comment by williamcroberts** [comment]
Not sure why offhand, ill have to dig into it.

**Comment by wenxinleong** [comment]
I notice in general the encrypted session is not operating correctly. I'll list down some observations. 

I have also upgraded the version to the latest release: tpm2-tss v3.0.3, tpm2-tools v5.0

### **``tpm2_hmac``**
Observation made on ``tpm2_hmac``. If encrypted session is not activated during hashing, the hash value is always the same as expected:
```
tpm2_startup -c
tpm2_clear -c p

tpm2_createprimary -p pass1 -c primary.ctx
tpm2_evictcontrol -C o -c primary.ctx 0x81000000
tpm2_flushcontext 0x80000000

tpm2_startauthsession -S session.ctx
tpm2_policypassword -S session.ctx -L policy.dat
tpm2_flushcontext session.ctx

tpm2_create -G hmac -P pass1 -p pass2 -C 0x81000000 -u hmac.pub -r hmac.priv -L policy.dat
tpm2_load -P pass1 -C primary.ctx -u hmac.pub -r hmac.priv -c hmac.ctx
tpm2_flushcontext 0x80000000
tpm2_flushcontext 0x80000001
tpm2_flushcontext 0x80000002
tpm2_evictcontrol -C o -c hmac.ctx 0x81000001

echo "ffffffff" > msg.txt
xxd -r -p msg.txt msg.dat
tpm2_startauthsession --policy-session -S session.ctx
tpm2_policypassword -S session.ctx
tpm2_hmac -c 0x81000001 -p session:session.ctx+pass2 -o sig1.hmac msg.dat
tpm2_policypassword -S session.ctx
tpm2_hmac -c 0x81000001 -p session:session.ctx+pass2 -o sig2.hmac msg.dat
tpm2_flushcontext session.ctx
xxd -ps -c 32 sig1.hmac 
> 3e040710c2004e57bf59b9758451ede42b235811bc2261cc8a1f6ceb912fae77
xxd -ps -c 32 sig2.hmac 
> 3e040710c2004e57bf59b9758451ede42b235811bc2261cc8a1f6ceb912fae77
```

But oddly, if the encrypted session is enabled, hash value is different every time:
```
tpm2_startup -c
tpm2_clear -c p

tpm2_createprimary -p pass1 -c primary.ctx
tpm2_evictcontrol -C o -c primary.ctx 0x81000000
tpm2_flushcontext 0x80000000

tpm2_startauthsession -S session.ctx
tpm2_policypassword -S session.ctx -L policy.dat
tpm2_flushcontext session.ctx

tpm2_create -G hmac -P pass1 -p pass2 -C 0x81000000 -u hmac.pub -r hmac.priv -L policy.dat
tpm2_load -P pass1 -C primary.ctx -u hmac.pub -r hmac.priv -c hmac.ctx
tpm2_flushcontext 0x80000000
tpm2_flushcontext 0x80000001
tpm2_flushcontext 0x80000002
tpm2_evictcontrol -C o -c hmac.ctx 0x81000001

echo "ffffffff" > msg.txt
xxd -r -p msg.txt msg.dat
tpm2_startauthsession --policy-session -c 0x81000000 -S session.ctx
tpm2_policypassword -S session.ctx
tpm2_hmac -c 0x81000001 -p session:session.ctx+pass2 -o sig1.hmac msg.dat
tpm2_policypassword -S session.ctx
tpm2_hmac -c 0x81000001 -p session:session.ctx+pass2 -o sig2.hmac msg.dat
tpm2_flushcontext session.ctx
xxd -ps -c 32 sig1.hmac 
> d30ad707ad44be2acdefa21035fe5c41b6c4112d50477a50574961da6a2561db
xxd -ps -c 32 sig2.hmac 
> 5f6e99ed4bf08162ae2f11e1fb668b1f448efcebe1de8c43b996cf95105cdc89
```


### **``tpm2_sign``**
Observation made on ``tpm2_sign``. If encrypted session is not activated during signing, the subsequence ``tpm2_verifysignature`` works ok:
```
tpm2_startup -c
tpm2_clear -c p

tpm2_createprimary -p pass1 -c primary.ctx
tpm2_evictcontrol -C o -c primary.ctx 0x81000000

tpm2_startauthsession -S session.ctx
tpm2_policypassword -S session.ctx -L policy.dat
tpm2_flushcontext session.ctx

tpm2_create -G rsa -P pass1 -p pass2 -C 0x81000000 -u rsa.pub -r rsa.priv -L policy.dat
tpm2_load -P pass1 -C primary.ctx -u rsa.pub -r rsa.priv -c rsa.ctx
tpm2_evictcontrol -C o -c rsa.ctx 0x81000001

echo "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" > msg.txt
xxd -r -p msg.txt msg.dat
tpm2_startauthsession --policy-session -S session.ctx
tpm2_policypassword -S session.ctx
tpm2_sign -d -g sha256 -c 0x81000001 -p session:session.ctx+pass2 -o sig.rssa msg.dat
tpm2_flushcontext session.ctx
tpm2_verifysignature -d msg.dat -c 0x81000001 -s sig.rssa
```
With encrypted session enabled during signing, the generated signature seems broken.
```
tpm2_startup -c
tpm2_clear -c p

tpm2_createprimary -p pass1 -c primary.ctx
tpm2_evictcontrol -C o -c primary.ctx 0x81000000

tpm2_startauthsession -S session.ctx
tpm2_policypassword -S session.ctx -L policy.dat
tpm2_flushcontext session.ctx

tpm2_create -G rsa -P pass1 -p pass2 -C 0x81000000 -u rsa.pub -r rsa.priv -L policy.dat
tpm2_load -P pass1 -C primary.ctx -u rsa.pub -r rsa.priv -c rsa.ctx
tpm2_evictcontrol -C o -c rsa.ctx 0x81000001

echo "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" > msg.txt
xxd -r -p msg.txt msg.dat
tpm2_startauthsession --policy-session -c 0x81000000 -S session.ctx
tpm2_policypassword -S session.ctx
tpm2_sign -d -g sha256 -c 0x81000001 -p session:session.ctx+pass2 -o sig.rssa msg.dat
tpm2_flushcontext session.ctx
tpm2_verifysignature -d msg.dat -c 0x81000001 -s sig.rssa
```
**WARNING:esys:src/tss2-esys/api/Esys_VerifySignature.c:302:Esys_VerifySignature_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_VerifySignature.c:103:Esys_VerifySignature() Esys Finish ErrorCode (0x000002db)
ERROR: Esys_VerifySignature(0x2DB) - tpm:parameter(2):the signature is not valid
ERROR: Verify signature failed!
ERROR: Unable to run tpm2_verifysignature**

I checked in the tpm2-tss code ``esys_iutil.c``. The ``tpm2_sign`` operation, only the command parameter TPM2B_DIGEST is encrypted, response parameter (signature) is not in encrypted form. Does it means that there is issue in the implementation of parameter encryption, causing the TPM2B_DIGEST corrupted; therefore, generating an invalid signature?

**Comment by wenxinleong** [comment]
Couple of things are at fault here, correct me if im wrong:
- There is no option in `tpm2_startauthsession` to accept the auth value of encryption key handle `0x81000000` and resulted in bad session key derivation at the caller side. 
- In TCG spec Part 1: Architecture, quote "A password authorization may not be used for anything but authorization and the TPM will return an error (TPM_RC_ATTRIBUTES) if encrypt, decrypt, or audit is SET in a password authorization.". Therefore, not to use `tpm2_policypassword`
- TPM not returning error (TPM_RC_ATTRIBUTES) if encrypt, decrypt, or audit is SET in a password authorization. This has been observed using TPM simulator

**Comment by AndreasFuchsSIT** [comment]
Have you tried creating 0x81000000 without a password ?
Does that work ?

**Comment by AndreasFuchsSIT** [comment]
Some comments to clear some things up

>    I checked in the tpm2-tss code esys_iutil.c. The tpm2_sign operation, only the command parameter TPM2B_DIGEST is encrypted, response parameter (signature) is not in encrypted form.

That's correct. The TPM only supports encryption of the first parameter (of a command or response) if that parameter is a TPM2B_. The return parameter of TPM2_Sign is a TPMT_ and thus not encryptable.
 
> In TCG spec Part 1: Architecture, quote A password authorization may not be used for anything but authorization and the TPM will return an error (TPM_RC_ATTRIBUTES) if encrypt, decrypt, or audit is SET in a password authorization. Therefore, not to use `tpm2_policypassword`

The password authorization referred to in the TPM spec is authentication _without_ a session. PolicyPassword is something different than this (session-less) password authorization. (I know, bad choice of wording)

**Comment by wenxinleong** [comment]
> Have you tried creating 0x81000000 without a password ?
Does that work ?

Yes this will work.

> The password authorization referred to in the TPM spec is authentication without a session. PolicyPassword is something different than this (session-less) password authorization. (I know, bad choice of wording)

Do you mean that encrypted session should work on ``tpm2_policypassword``? I investigated the code and found out if ``tpm2_policypassword`` is used the caller nonce is never transmitted to TPM, resulted in different encryption key derived at caller and TPM. If I use ``tpm2_policyauthvalue`` encryption session works ok. If what you are saying is true, means tpm2-tss implementation has issue

**Comment by AndreasFuchsSIT** [comment]
So the first problem seems to be that tpm2_startauthsession is lacking a parameter for the bindkey authvalue and as a result lacks the Esys_TR_SetAuth() C-call on the bindkey object before calling Esys_StartAuthSession.

It's hard to make a statement about tpm2-tss/libesys at this point.

**Comment by idesai** [comment]
> So the first problem seems to be that tpm2_startauthsession is lacking a parameter for the bindkey authvalue and as a result lacks the Esys_TR_SetAuth() C-call on the bindkey object before calling Esys_StartAuthSession.
> 
> It's hard to make a statement about tpm2-tss/libesys at this point.

WIP in PR #2274

**Comment by idesai** [comment]
> > So the first problem seems to be that tpm2_startauthsession is lacking a parameter for the bindkey authvalue and as a result lacks the Esys_TR_SetAuth() C-call on the bindkey object before calling Esys_StartAuthSession.
> > It's hard to make a statement about tpm2-tss/libesys at this point.
> 
> WIP in PR #2274

Now #2293
