### ISSUE TITLE
Create HMAC key reports error 0x143 command code not supported on IFX SLB9665 device

### ISSUE THREAD

**Issue by keke8273** [tpm2-software/tpm2-tools#2281]
Hi, I am working with a IFX SLB9665 device with the following configuration 
```
Manufacturer; IFX              
Vendor string; SLB9665
Firmware version; 5.51.8.12800 
Image tag; v1.0 
tpm2_tools: 4.1.1
```
The device seems to support the `hmac` algorithm since it reports the following when executing `tpm2_getcap`
```
tpm2_getcap algorithms
rsa:
  value:      0x1
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     1
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
sha1:
  value:      0x4
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
hmac:
  value:      0x5
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     0
```
However, when I try to create a hmac key I got error `0x143 command code not supported`
```
sudo tpm2_create -C primary.context -G hmac -c hmac.ctx
WARNING:esys:src/tss2-esys/api/Esys_CreateLoaded.c:359:Esys_CreateLoaded_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_CreateLoaded.c:129:Esys_CreateLoaded() Esys Finish ErrorCode (0x00000143) 
ERROR: Esys_CreateLoaded(0x143) - tpm:error(2.0): command code not supported
ERROR: Unable to run tpm2_create
```

**Comment by williamcroberts** [comment]
You're checking the supported algorithms. I think they have to support HMAC algorithm to support HMAC sessions for password protection and integrity of blobs. However, I don't think they have to support the command. So you want to check "commands" not "algorithms".

```bash
tpm2_getcap commands | grep -i hmac
TPM2_CC_HMAC:
TPM2_CC_HMAC_Start:
```
What's your output?

**Comment by keke8273** [comment]
Hi @williamcroberts, my output is identical to yours
```
sudo tpm2_getcap commands | grep -i hmac
TPM2_CC_HMAC:
TPM2_CC_HMAC_Start:
```

Another data point. I ran a fulltest with [tpm2_algtest](https://github.com/crocs-muni/tpm2-algtest). The test run is able to generate hmac keys and perform hmac operation.
**Key  Generation Test Results:**
```
INFO: Keygen 98: ECC | curve 0010 | duration 0.070933 | rc 02d2
INFO: Keygen 99: ECC | curve 0010 | duration 0.071316 | rc 02d2
INFO: Keygen 0: KEYEDHASH | duration 0.311190 | rc 0000
INFO: Keygen 1: KEYEDHASH | duration 0.311385 | rc 0000
INFO: Keygen 2: KEYEDHASH | duration 0.311062 | rc 0000
INFO: Keygen 3: KEYEDHASH | duration 0.311757 | rc 0000
INFO: Keygen 4: KEYEDHASH | duration 0.311538 | rc 0000
INFO: Keygen 5: KEYEDHASH | duration 0.311678 | rc 0000
INFO: Keygen 6: KEYEDHASH | duration 0.311620 | rc 0000
INFO: Keygen 7: KEYEDHASH | duration 0.311575 | rc 0000
```
HMAC operation results
```
INFO: Perf hmac: Generating HMAC key...
INFO: Perf hmac 0: duration 0.076540 | rc 0000
INFO: Perf hmac 1: duration 0.074450 | rc 0000
INFO: Perf hmac 2: duration 0.073944 | rc 0000
INFO: Perf hmac 3: duration 0.074380 | rc 0000
```

**Comment by keke8273** [comment]
Ok, I think i have found the problem. The complain is against the command `Esys_CreateLoaded`.  It seems the device only supports the following to create commands:
```
sudo tpm2_getcap commands | grep -i create
TPM2_CC_CreatePrimary:
TPM2_CC_Create:
```
creating a hmac key **without** loading it is successful. 
```
sudo tpm2_create -C primary.context -G hmac -u obj.pub -r obj.priv
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|sign
  raw: 0x40072
type:
  value: keyedhash
  raw: 0x8
algorithm: 
  value: hmac
  raw: 0x5
hash-alg:
  value: sha256
  raw: 0xb
keyedhash: 952d70e3e473083638ae7d5f24f2407b3365bf2c04f6f3e2d0d174e77bee360c
```

**Comment by williamcroberts** [comment]
Oh duh, I should have noticed that:
`ERROR: Esys_CreateLoaded(0x143) - tpm:error(2.0): command code not supported`

For some reason I got it in my head that you couldn't perform the HMAC, not create the key. My mistake, but glad you sorted it out.

**Comment by keke8273** [comment]
Thanks for the hint to look at supported commands. That was very helpful.

**Comment by danielwangksu** [comment]
I encountered the same issue on real TPM. Since tpm2_create cannot write to a handler (cannot use -c) how can we further use the create key? Thank you!

**Comment by keke8273** [comment]
i loaded the key via the `tpm2_load` command
```
tpm2_create -C "$owner_primary_handle" -P hex:"$owner_primary_pass" -G hmac -u "$owner_hmac_pub" -r "$owner_hmac_prv"
tpm2_load -C "$owner_primary_handle" -P hex:"$owner_primary_pass" -u "$owner_hmac_pub" -r "$owner_hmac_prv" -c "$owner_hmac_ctx"
```

**Comment by williamcroberts** [comment]
If `-c` doesn't work, just use `-u/-r` and pass them to tpm2_load `-u` and `-r` respectively. The load command can output the context via `-c`.

Really tpm2_create -c should be smart enough to call `tpm2_load` if needed.
