### ISSUE TITLE
TSS2 Tools test causes memory leak in TSS library

### ISSUE THREAD

**Issue by cplappert** [tpm2-software/tpm2-tools#2285]
In #2262 the CI fails in a negative test due to a memory leak in the TSS 3.0.1.
The memory leak is however fixed in version 3.0.2 where the nonce is correctly freed
in the error case:

3.0.2 (leak fixed): https://github.com/tpm2-software/tpm2-tss/blob/3.0.2/src/tss2-fapi/ifapi_policy_execute.c#L527
vs.
3.0.1 (leak present):  https://github.com/tpm2-software/tpm2-tss/blob/3.0.1/src/tss2-fapi/ifapi_policy_execute.c#L527 (no `SAFE_FREE(current_policy->nonceTPM);`)

Can we update the TSS version in the CI to 3.0.2?

**Comment by williamcroberts** [comment]
> In #2262 the CI fails in a negative test due to a memory leak in the TSS 3.0.1.
> The memory leak is however fixed in version 3.0.2 where the nonce is correctly freed
> in the error case:
> 
> 3.0.2 (leak fixed): https://github.com/tpm2-software/tpm2-tss/blob/3.0.2/src/tss2-fapi/ifapi_policy_execute.c#L527
> vs.
> 3.0.1 (leak present): https://github.com/tpm2-software/tpm2-tss/blob/3.0.1/src/tss2-fapi/ifapi_policy_execute.c#L527 (no `SAFE_FREE(current_policy->nonceTPM);`)
> 
> Can we update the TSS version in the CI to 3.0.2?

Sure you can bump that

**Comment by cplappert** [comment]
Ok. I added a respective commit in the PR.
