### ISSUE TITLE
tpm2_nvdefine incorrectly limits nv index size to TPM2_MAX_NV_BUFFER_SIZE in stead of TPM2_PT_NV_INDEX_MAX

### ISSUE THREAD

**Issue by rapmaste** [tpm2-software/tpm2-tools#2288]
The tpm2_nvdefine tool can't define indexes of a size larger than TPM2_MAX_NV_BUFFER_SIZE, which happens to be 768 bytes on for example an Infineon SLB9670 chip. The correct size limit for an nv-index on this particular chip is 1664 bytes from the fixed property TPM2_PT_NV_INDEX_MAX=0x680

This behavior of tpm2_nvdefine  is observed on at least tpm2-tools version 4.1.2 while tpm2_nvdefine limited the nv-index size correctly in the 3.x.x series. tpm2_nvwrite and tpm2_nvread can handle nv-indexes larger than TPM2_MAX_NV_BUFFER_SIZE, it's just impossible to define larger nv-indexes with version 4.1.2

**Comment by idesai** [comment]
@rapmaste I was able to create a bigger NV index. There was a specific fix with [commit](https://github.com/tpm2-software/tpm2-tools/commit/48594efa6f1faca50c73ce0d88f6e99eb0f5005c). I will have to check if the commit made it to 4.1.2 branch.

Are you able to use the newer version of the tools? Below is the output from the latest version of the tools with an even bigger NV size.

tpm2_nvdefine -C o 0x01500016 -s 2048 
nv-index: 0x1500016

 tpm2_nvreadpublic
0x1500016:
  name: 000bb4a306a3b703398d20e2e3db3971f45e09d06c9621c311866f175ee3f88844e4
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ownerwrite|authwrite|ownerread|authread
    value: 0x6000600
  size: 2048

tpm2_nvdefine --version
tool="tpm2_nvdefine" version="5.0-47-g43d91ef8e" tctis="libtss2-tctildr" tcti-default=tcti-abrmd

**Comment by rapmaste** [comment]
There is a (small) gotcha here!

The problem was actually with the "writeall" bit in the NV index attributes. If this bit is set, partial writes to the NV index are not allowed. Thinking about it, of course it makes perfect sense to limit the index size to the buffer size in this case.

Weirdly, I clearly remember that if the "writeall" bit was set, it was possible to define larger nv indexes with the older 3.x.x version. That was, of course not correct so I think we can close this issue now.
