### ISSUE TITLE
Avoid casts when dereferencing session structures in sessionconfig tool

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tools#2299]

**Comment by williamcroberts** [comment]
So it looks like you get all the information from an IESYS_METADATA via populate_iesys_session_info(). What we need to do is find a way to get the information you care about, which you currently dump it all out, in an upstream compatible way. You need to work with Andreas and if we need a new interface, the TCG TSS working group to build this interface. I only see you use the IESYS_METADATA to print the data, can we just remove this functionality and still have a working tool or do you need some of those outputs for something? The simplest way to deal with it, is to avoid it ;-p
