### ISSUE TITLE
tpm2_create error, Create Object Failed ! ErrorCode: 0x2c2

### ISSUE THREAD

**Issue by penpendandan** [tpm2-software/tpm2-tools#2301]
hello
I want to create ek key and ak key by tpm tools, but when I create ak key, I got the following error:
```
Client accepted
Client accepted
ERROR:
Create Object Failed ! ErrorCode: 0x2c2

ERROR: Unable to run tpm2_create
$tpm2_rc_decode 0xc2c
error layer
  hex: 0x0
  identifier: TSS2_TPM_RC_LAYER
  description: Error produced by the TPM
format 1 error code
  hex: 0x02
  identifier: TPM2_RC_ATTRIBUTES
  description: inconsistent attributes
parameter
  hex: 0x200
  identifier:  TPM2_RC_2
  description:  (null)
```

 the command to create ek key is:

` tpm2_createprimary -H e -g sha256 -L ek.policy -G rsa -C ek.ctx -A 'restricted|fixedtpm|fixedparent|sensitivedataorigin|decrypt|adminwithpolicy'
`
 the command to create ak key is:
`tpm2_create -H 0x81010001 -g sha256 -G rsa -u aik.pub -r aik.priv -A 'fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|sign'`
so why do I get the error code, Thanks

**Comment by idesai** [comment]
Did you try to satisfy the policy and specify the auth for the parent ek.ctx during key creation?
