### ISSUE TITLE
Regenerate public portion of a tpm key

### ISSUE THREAD

**Issue by tobuh** [tpm2-software/tpm2-tools#2305]
Let's say I would do something like that:

```
tpm2_createprimary -c primary.ctx
tpm2_create -C primary.ctx -u obj.pub -r obj.priv
rm obj.pub
```

Is it possible to regenerate the public portion, similar to "standard" keys like OpenSSL and Private keys in PEM format?

I tried with tpm2_load and tpm2_loadexternal, to load only private part, but it seems that public part is mandatory?

Kind regards
Tobi

**Comment by idesai** [comment]
[tpm2_readpublic](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_nvreadpublic.1.md)

**Comment by tobuh** [comment]
Thanks for that hint.

Could you please be more precise? I tried that command before. But as far as I understand, I first need a context via tpm2_load. But there "-u" (public object portion) is mandatory.

If things are unclear from my side:
Given example above, I want to regenerate obj.pub. I don't want to have a PEM formatted public key. This was just for analogy.

**Comment by williamcroberts** [comment]
@tobuh use the "-f pem"  option on tpm2_readpublic. It will produce a pem file.

```bash
tpm2_createprimary -c primary.ctx
tpm2_create -C primary.ctx -u key.pub -r key.priv
tpm2_load -C primary.ctx -c key.ctx -u key.pub -r key.priv
tpm2_readpublic -c key.ctx -f pem -o key.pem
cat key.pem
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqxgydXbJkLzVEQNoGzlL
hBzJqCgSwWF/zIlDsqRf7BXvomjnduweysq23mRIWE7L3lKuCPqvsatmD7V432Fp
zOv1WNF2zUhsBia2Kk0fC724tWLhL3PO0/XIBrS367llE3vY+XnDsyTzjwCkSSTP
XqnDZF8jmBgIn3EEXpQgZxWl/8o+NWyRtop9FaLzRSUCwWjZUebynrHELdgKWQoE
REeFQMh0jhiFqa7lMKO4PerrUcmBBwhXgkDTIcEgv90BbNI93+6Hm8ZY++B94AmA
A0SdoUtno5iMqzuQ+Wc4V7gvPwU02QfP0LvNcGZPpa3tYSjfAg/Da+3UEWxgam2G
1wIDAQAB
-----END PUBLIC KEY-----
```

**Comment by tobuh** [comment]
Thanks for that detailed example, but unfortunately, that's not an answer to my question. :-(

It is NOT about PEM Public Keys, sorry that I used this as an example. **It is about about the public portion from tpm2_create. If I delete this, is it somehow possible to regenerate that?**

What I was trying to explain with the PEM analogy: Usually it is possible to regenerate the public pendant of a key, if you only have the private part of the key. Is it also possible with the results from tpm2_create?

**Comment by williamcroberts** [comment]
> Thanks for that detailed example, but unfortunately, that's not an answer to my question. :-(
> 
> It is NOT about PEM Public Keys, sorry that I used this as an example. **It is about about the public portion from tpm2_create. If I delete this, is it somehow possible to regenerate that?**

No because the TPM will not load the private portion of the key without the public portion, and since we cannot peer into the private blob, we cannot re-generate the public key from it..

> 
> What I was trying to explain with the PEM analogy: Usually it is possible to regenerate the public pendant of a key, if you only have the private part of the key. Is it also possible with the results from tpm2_create?

That work's because you have access to the private key material. Since the TPM doesn't provide us a way to do this, deleting the public key deletes the key in essence.

**Comment by tobuh** [comment]
Thanks for the detailed explanation. I really appreciate!
