### ISSUE TITLE
no tpm2-createek here

### ISSUE THREAD

**Issue by sqq0216** [tpm2-software/tpm2-tools#2316]
I using an old version that is 3.X, so no tpm2-createek here, I find it is renamed , before renamed it is called tpm2-getpubek, but I can't find some doc to present how to using the old command-tpm2-getpubek, so I want to know how to implement the next command using tpm2-getpubek
```
tpm2_createek -G rsa -u ek.pub -c ek.ctx
tpm2_createak -C 0x81010001 -c ak.ctx -G rsa -g sha256 -s rsassa -u ak.pub -n ak.name
```
thanks very much!

**Comment by idesai** [comment]
https://github.com/tpm2-software/tpm2-tools/blob/3.X/man/tpm2_getpubek.1.md
https://github.com/tpm2-software/tpm2-tools/blob/3.X/man/tpm2_getpubak.1.md

**Comment by sqq0216** [comment]
I want to use the version 4.X, and the platform information is :
ubuntu16.04
tss2.4.5
abrmd2.0.2
tools3.X
autoconf-archive2019
but there always is an errors when to do ./configure,  that is 
```
configure: error: Invalid policy. Valid policies: git-directory, minor-version.
```
when I use tools3.X it is ok.
what should I do? thanks very much!

**Comment by williamcroberts** [comment]
> I want to use the version 4.X, and the platform information is :
> ubuntu16.04
> tss2.4.5
> abrmd2.0.2
> tools3.X
> autoconf-archive2019
> but there always is an errors when to do ./configure, that is
> 
> ```
> configure: error: Invalid policy. Valid policies: git-directory, minor-version.
> ```
> 
> when I use tools3.X it is ok.
> what should I do? thanks very much!

That error looks like your building out of the "Download Zip" feature of github. You need to use the release tarballs from:
  - https://github.com/tpm2-software/tpm2-tools/releases

Or you can git clone it and git checkout <tag> and build from there.
