### ISSUE TITLE
Mailing list doesn't work

### ISSUE THREAD

**Issue by jc-lab** [tpm2-software/tpm2-tools#2321]
I know it is not suitable for github issues.
But there was no other way.

I signed up a few weeks ago, but "You have a subscription request pending. If you don't hear back soon, please contact the list owners." still.
So, I can't discuss it.
Is there another process for signing up?

**Comment by williamcroberts** [comment]
When you sign up you should recieve a "confirm your email" address. Can you send me an email to william.c.roberts(at)intel.com so I can verify it. I see a few folks in the "pending" queue.

But you should make sure that confirmation email isn't in the spam folder.
