### ISSUE TITLE
tpm2_pcrallocate: unable to select 'none' (to switch banks completely)

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-tools#2344]
If I have a tpm which can only have 1 PCR bank active and I want to switch the allocation e.g. from sha256 to sha1 this is currently not possible, as there is no way to specify "empty/none" allocation for a bank,

`tpm2_pcrallocate "sha1:all+sha256:none"` would be my proposed solution.
If that's okay I can create a patch.

**Comment by williamcroberts** [comment]
Nope, interesting find in functionality limitation. I had to read the spec to figure out how this would even work, I like your proposal.

Ill drop the note from the spec here that clarifies for anyone so interested:
```
If a TPM supports SHA1 and SHA256, then it maintains an allocation for two banks (one of which
could be empty). If pcrAllocation only has a selector for the SHA1 bank, then only the allocation of
the SHA1 bank will be changed and the SHA256 bank will remain unchanged. To change the
allocation of a TPM from 24 SHA1 PCR and no SHA256 PCR to 24 SHA256 PCR and no SHA1 PCR,
the pcrAllocation would have to have two selections: one for the empty SHA1 bank and one for the
SHA256 bank with 24 PCR.
```
