### ISSUE TITLE
Trying unsuccessfully to clear the TPM

### ISSUE THREAD

**Issue by cole-seph-work** [tpm2-software/tpm2-tools#2362]
I'd like to completely reset the TPM back to factory defaults in order to be able to put a new TPM key on there, as the chip is currently holding the max capacity of nv slots / keys.

When I run: 
```tpm2_nvreadpublic```
on an encrypted machine,  I see the different nv slots stored on the TPM. This is expected. 

However, both clearing the TPM in the BIOS/UEFI of the machine _or_ running "tpm2_clear" seem to only lock out the tpm lockout hierarchy (as mentioned in the [man page](https://www.mankier.com/1/tpm2_nvdefine). 

It does not seem to erase these nv slots from memory altogether, as if I run: 
```tpm2_nvreadpublic```
again, after a BIOS clear of the TPM, I still see the exact same nv slots and their values/attributes. 

I have also tried running:
```tpm2_clear -c platform``` to no avail. 
I receive this error: 
```
WARNING:esys:src/tss2-esys/api/Esys_Clear.c:282:Esys_Clear_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Clear.c:97:Esys_Clear() Esys Finish ErrorCode (0x000009a2)
ERROR: Esys_Clear(0x9A2) - tpm:session(1):authorization failure without DA implications
ERROR: Unable to run tpm2_clear
```

Am I wrong in thinking I should see no nv slots occupied after clearing the TPM and running: 
```tpm2_nvreadpublic```
?

**OS: Ubuntu 20.04 LTS**
**Laptop brand: Lenovo**

Also, noting that the tpm nv slots currently in place were created with clevis and it seems they have the attribute: "policydelete", meaning I'm unable to delete them with the command: "[tpm2_nvundefine](https://www.mankier.com/1/tpm2_nvundefine)", as I not longer have whatever authorization string/file was originally used to create them.

**Comment by idesai** [comment]
@cole-seph-work if your BIOS has the option to clear the TPM, it should most likely use the platform hierarchy authorization in platform-early-initialization (PEI) stage to clear the TPM. If that is not working as you indicated, you must contact Lenovo.

There are certain NV indices holding your EK certificate that may not be deleted. What indices are you looking at?

**Comment by cole-seph-work** [comment]
@idesai thank you for your input

Here is a list of indices (obtained from running "tpm2_nvreadpublic") that appear non-deleteable:
(names and policy names have been obfuscated)
```
0x1800001:
  name: obfuscated_name_1
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: authwrite|policydelete|writelocked|writedefine|authread|no_da|written|platformcreate
    value: 0x42C0462
  size: 70
  authorization policy: obfuscated_policy_1
0x1800003:
  name: obfuscated_name_2
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: policywrite|policydelete|write_stclear|authread|no_da|platformcreate
    value: 0x8440442
  size: 104
  authorization policy: obfuscated_policy_2
0x1800004:
  name: obfuscated_name_3
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: authwrite|policydelete|authread|no_da|written|platformcreate
    value: 0x4040462
  size: 8
  authorization policy: obfuscated_policy_3
0x1c00002:
  name: obfuscated_name_4
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|write_stclear|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1600762
  size: 1600
  authorization policy: 0000000000000000000000000000000000000000000000000000000000000000 (unchanged from original)
0x1c0000a:
  name: obfuscated_name_5
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|write_stclear|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1600762
  size: 1600
  authorization policy: 0000000000000000000000000000000000000000000000000000000000000000 (unchanged from original)

```

**Comment by idesai** [comment]
@0x1c00002 and 0x1c0000a you have the TPM EK certificates from the TPM manufacturer that you cannot delete.
@0x1800001 and 0x1800004 you have the policydelete that means with a policy setup such that it cannot be satisfied implies you cannot delete that either.

**Comment by idesai** [comment]
You have consumed about 3382 bytes. Typically there is about 14kb. So you still got some space in there.
As for new keys, unless made persistent to the TPM, they don't actually consume any space. So you could create the keys and then the TPM would wrap/encrypt them for you to be able to disk storage. If you absolutely need the keys to be on the TPM then you can make them persistent using tpm2_evictcontrol.

**Comment by cole-seph-work** [comment]
Super helpful info. Thank you so much. 

Do you happen to know of any docs you could point me to that might explain this line better? 
> As for new keys, unless made persistent to the TPM, they don't actually consume any space.

**Comment by idesai** [comment]
Section [28.2.1](https://www.trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf)
