### ISSUE TITLE
RHEL 7.9 tools do not compile - missing esys

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-tools#2368]
RHEL 7.9, built TSS from source.  Then configure fails with the log below.  There are some hints about env variables, but there are no instructions in the install.md.

hecking for pkg-config... /bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for TSS2_FAPI... no
checking for TSS2_FAPI_3_0... no
checking for TSS2_ESYS_3_0... no
checking for TSS2_ESYS_2_3... no
configure: error: Package requirements (tss2-esys >= 2.4.0) were not met:

No package 'tss2-esys' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables TSS2_ESYS_2_3_CFLAGS
and TSS2_ESYS_2_3_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by williamcroberts** [comment]
When you did a make install of tpm2-tss, where did it install everything?

Generally this happens if you don't use the right set of configure option(s) to match what the distro is expecting.

You can figure out where pkg-config looks by executing:
```bash
pkg-config --variable=pc_path pkg-config
```

If your .pc files are not being installed into one of those paths, you can:

1. `export PKG_CONFIG_PATH` to point to the directory they were installed in
2. Uninstall and correct your install path at configure time, something like this:
    ```bash
       sudo make uninstall
       make distclean
       pkg_conf_path="$(pkg-config --variable pc_path pkg-config | cut -d: -f 1-1)"
      ./configure --with-pkgconfigdir="$pkg_conf_path"
      make -j4
      sudo make install
      ```

**Comment by tstruk** [comment]
Probably related to https://github.com/tpm2-software/tpm2-tss/issues/2025
Fix already on its way.

**Comment by williamcroberts** [comment]
@kgold2 The default location for package config files (.pc) is usually `/usr/local/lib/pkgconfig` which sometimes isn't on distro package config paths. Ubuntu has it set up by default:
```
pkg-config --variable=pc_path pkg-config
/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
```

But RHEL might not, so you probably want to check, and run the configure command I gave you if its not.
