### ISSUE TITLE
Occasional tpm2_quote failures

### ISSUE THREAD

**Issue by stefanberger** [tpm2-software/tpm2-tools#2376]
We are seeing occasional tpm2_quote failures when using tpm2_quote in Keylime: https://github.com/keylime/keylime/issues/585 . It is likely that between the time the PCRs are read and the Quote has been done (or Quote first then PCRs read; order doesn't matter) the value of the PCRs has change if the system is 'somewhat' busy with IMA extending PCR 10 (for example).

I am not sure whether it is actually necessary to compare the read PCRs to the quoted but we just trust the **trusted** platform module (pun intended) to quote the PCRs correctly.

**Comment by idesai** [comment]
@stefanberger thank you for reporting the error. But the comparison happens only if there is a necessity to output the PCR values alongside the quote. So if you don't specify the **--pcr, -o** option, it should only produce a quote. What is the command line option used in keylime for tpm2_quote?

**Comment by stefanberger** [comment]
It's being used with the `--pcr option` to later on run the `tpm2_checkquote`. Closing this issue now since there's a work-around.

**Comment by idesai** [comment]
> It's being used with the `-o` option to later on run the `tpm2_checkquote`. Closing this issue now since there's a work-around.

@stefanberger I am curious what the workaround is and if that could be added to the tpm2-tools.

**Comment by stefanberger** [comment]
The work-arounds are to repeatedly run `tpm2_quote` in case of failure to match the PCRs against the Quote or to not read the PCRs (and then avoiding running tpm2_checkquote).

**Comment by idesai** [comment]
@stefanberger IIUC, is this an accurate representation?
Here (A)(B)(C)(D)(E)(F)(G)(H) are measurements and 1/0 imply specific event.

|Correction | IMA(extend) | Quote(read) | PCR(read) | Mismatch | Missed
|---|---|---|--- |---|---
|0          | 1(A)        | 0           | 0         | NA       | NA
|0          | 0           | 1(A)        | 1(A)      | 0        | 0
|0          | 1(B)        | 0           | 0         | NA       | NA
|0          | 1(C)        | 1(C)        | 1(C)      | 0        | (B)
|0          | 1(D)(E)     | 1(D)        | 1(E)      | 1        | Min. (D)
|1          | 0           | 1(E)        | 1(E)      | 0        | (D)
|0          | 1(F)(G)(H)  | 1(F)        | 1(G)      | 1        | Min. (F)
|1          | 0           | 1(H)        | 1(H)      | 0        | (F)(G)

I am afraid, even solving with this truth table, there are possibilities of
missing measurements as you can see in the missed column. Stating the obvious,
but the only true solution is to somehow lock accesses to the TPM by
synchronizing the IMA and tpm2-tools.
