### ISSUE TITLE
tpm2_getcap handle-transient : does not show transient handle

### ISSUE THREAD

**Issue by boissinp** [tpm2-software/tpm2-tools#2379]
Hello, by using tpm2-tools I don't understand that : 

At any state of this procedure tpm2_getcap handles-transient return nothing while tpm2_getcap handles-persistent seems to make the jobs.

tpm2_createek -c ek.handle -G rsa -u ek.pub
tpm2_getcap handles-transient  -> return nothing

tpm2_createak -C ek.handle -c ak.ctx -u ak.pub -n ak.name
tpm2_getcap handles-transient  -> return nothing

tpm2_evictcontrol -C o -c ak.ctx 0x81010002
tpm2_getcap handles-persistent -> return the handle number 

tpm2_evictcontrol -c 0x81010002
tpm2_getcap handles-transient  -> return nothing

**Comment by williamcroberts** [comment]
> Hello, by using tpm2-tools I don't understand that :
> 
> At any state of this procedure tpm2_getcap handles-transient return nothing while tpm2_getcap handles-persistent seems to make the jobs.

I am assuming you are running with a resource manager aka RM, is that correct? tpm2-abmrmd and /dev/tpmrm0 are examples of an RM.

> 
> tpm2_createek -c ek.handle -G rsa -u ek.pub
> tpm2_getcap handles-transient -> return nothing

When the tool exits, a resource manager will flush all transient objects. But the -c option says, save the context of the EK to this context file, so I can pass it to tools later on. Those tools will load the context, thus making the object transient again, and the cycle repeats itself.

> 
> tpm2_createak -C ek.handle -c ak.ctx -u ak.pub -n ak.name
> tpm2_getcap handles-transient -> return nothing

Same, the ek ak is just a transient object that gets flushed by the RM.

> 
> tpm2_evictcontrol -C o -c ak.ctx 0x81010002
> tpm2_getcap handles-persistent -> return the handle number

You said, take this transient object in this context thats not loaded in the TPM, load it and make it persist at 0x81010002. Its now persistent, and RM won't flush it.

> 
> tpm2_evictcontrol -c 0x81010002
> tpm2_getcap handles-transient -> return nothing

You moved it to a transient object, and the RM flushed it.

**Comment by boissinp** [comment]
No it's a device tpm

**Comment by williamcroberts** [comment]
> No it's a device tpm (st33zp24),
> when i add -v option : " version="4.1.1" tctis="libtss2-tctildr" tcti-default=tcti-device"

The device tcti opens /dev/tpmrm0 first, does that file exist?

**Comment by boissinp** [comment]
yes

**Comment by williamcroberts** [comment]
> yes
Yes, you have an RM between you and your device. 

When I said:
`tpm2-abmrmd and /dev/tpmrm0 are examples of an RM.`

/dev/tpmrm0 uses the in kernel resource manager. So all of your behavior is explained by the presence of an RM flushing transient objects on client exit. So when tpm2_xxx tooling exits, the RM flushes transient objects. The tools use context files (-c option) so you can move from tool to tool seamlessly.

**Comment by boissinp** [comment]
Is there a way to prevent the RM to do that ?
Thank you for your explanations.

**Comment by williamcroberts** [comment]
Don't use an RM, but you'll need to manage the memory yourself. But why would you want to do this? This can be precarious.

You can alter the device TCTI by specifying it via the --tcti option or the env var. You can point the device tcti to use /dev/tpm0, which is the TPM device without the RM.

Examples:
```bash
tpm2_getrandom --tcti="device:/dev/tpm0" --hex 4
```

```bash
export TPM2TOOLS_TCTI="device:/dev/tpm0"
tpm2_getrandom --hex 4
```

**Comment by boissinp** [comment]
Thanks you very much, 

It's just to make it visual in a tutorial
