### ISSUE TITLE
Memory leak issues (?)

### ISSUE THREAD

**Issue by p-gentili** [tpm2-software/tpm2-tools#2381]
I everyone,
I'm having many issues that leads to a poor usage of the memory, probably due to some error on my side.

Linux 5.4.3
tpm2-tools 4.3.0
tpm2-abrmd 2.4.0
tpm2-tss 3.0.3

I have a **initramfs** that performs the following:
```
tpm2_createprimary -Q -c primary.ctx
tpm2_startauthsession -Q --policy-session -S session.ctx -c primary.ctx
tpm2_policysecret -Q -S session.ctx -c o -L secret.policy -x
tpm2_unseal -p "session:session.ctx" -c 0x81010000 -o key.bin
tpm2_flushcontext -s
tpm2_shutdown -c
```

After this I chroot to a new root which is using **systemd**. I have 0 loaded sessions and 0 saved sessions (from tpm2_getcap).
I perform the followings:
```
tpm2_createprimary -Q -c primary.ctx
tpm2_startauthsession -Q --policy-session -S session.ctx -c primary.ctx
tpm2_startauthsession -Q -c primary.ctx -S trial.ctx
tpm2_policysecret -Q -S trial.ctx -c o -L trial_policy.secret
echo "mykey" | tpm2_create -Q -C primary.ctx -u key.pub -r key.priv -i - -L trial_policy.secret
```

The last command throws this error:

> WARNING:esys:../tpm2-tss-3.0.3/src/tss2-esys/api/Esys_Create.c:375:Esys_Create_Finish() Received TPM Error
> ERROR:esys:../tpm2-tss-3.0.3/src/tss2-esys/api/Esys_Create.c:120:Esys_Create() Esys Finish ErrorCode (0x00000902)
> ERROR: Esys_Create(0x902) - tpm:warn(2.0): out of memory for object contexts
> ERROR: Unable to run tpm2_create

Instead, if I don't start the policy session (that I need for unsealing data) I can correctly create any child object.

Lastly, I have a similar problem rebooting the OS: at boot the initramfs is not able to start the session. This is the error:
> WARNING:esys:../tpm2-tss-3.0.3/src/tss2-esys/api/Esys_StartAuthSession.c:390:Esys_StartAuthSession_Finish() Received TPM Error
> ERROR:esys:../tpm2-tss-3.0.3/src/tss2-esys/api/Esys_StartAuthSession.c:136:Esys_StartAuthSession() Esys Finish ErrorCode (0x00000284)
> ERROR: Esys_StartAuthSession(0x284) - tpm:handle(2):value is out of range or is not correct for the context
> ERROR: Unable to run tpm2_startauthsession

Do you know how to improve the situation?
Thanks.

**Comment by idesai** [comment]
@p-gentili you should be using a resource manager or flush unused handles manually using tpm2_flushcontextx

**Comment by p-gentili** [comment]
> 
> 
> @p-gentili you should be using a resource manager or flush unused handles manually using tpm2_flushcontextx

Hi, thanks for your answer.
I'm using tpm2-abrmd, version 2.4.0. I've also performed the [Sanity Tests](https://github.com/tpm2-software/tpm2-abrmd/blob/master/INSTALL.md) and they're fine.

Also,  I'm flushing the saved sessions as I've written in the first post. 

Please consider that after I get the error  "tpm:warn(2.0): out of memory for object contexts" I'm not able to restore a working situation even after calling tpm2_shutdown -c; tpm2_startup -c. The only working solution for now is a hard reboot.

**Comment by idesai** [comment]
how do you start the resource manager?

**Comment by williamcroberts** [comment]
Are you sure you're using tpm2-abrmd? All your commands are sans the --tcti option and you don't mention setting TPM2TOOLS_TCTI. So the code under the hood will be figuring out what TCTI to use and could be defaulting to /dev/tpm0 (but it should use /dev/tpmrm0 AFAIK, since your kernel is since 4.12 ans has the inkernel RM.) If you run a command in the environments with the `--version`, whats that display?

**Comment by p-gentili** [comment]
Hi again,
in the **INITRAMFS** I start the abrmd with the following:
`/usr/sbin/tpm2-abrmd --allow-root &`
For testing the selected tcti:
```
# tpm2_getrandom --version
tool="tpm2_getrandom" version="c2fd641-dirty" tctis="libtss2-tctildr" tcti-default=tcti-abrmd
```

in **USERSPACE** I start the abrmd with **systemd**; this is the service:
```
[Unit]
Description=TPM2 Access Broker and Resource Management Daemon
After=systemd-udev-settle.service
Requires=systemd-udev-settle.service
# This condition is needed when using the device TCTI. If the
# TCP mssim is used then the condition should be commented out.
ConditionPathExistsGlob=/dev/tpm*

[Service]
Type=dbus
BusName=com.intel.tss2.Tabrmd
StandardOutput=syslog
ExecStart=/usr/sbin/tpm2-abrmd
User=tss

[Install]
WantedBy=multi-user.target
```
For testing the selected tcti:
```
# tpm2_getrandom --version
tool="tpm2_getrandom" version="0.1.4-10-g0ae9c36-dirty" tctis="libtss2-tctildr" tcti-default=tcti-abrmd
```

In both cases (initramfs and userspace) I get these two warnings when starting abrmd:

> ** (process:399): WARNING **: 00:00:04.777: tcti_conf before: "device:/dev/tpm0"
> ** (tpm2-abrmd:399): WARNING **: 00:00:04.777: tcti_conf after: "device:/dev/tpm0"

What do you think? Thanks again for your support.

**Comment by williamcroberts** [comment]
> 
> > ** (process:399): WARNING **: 00:00:04.777: tcti_conf before: "device:/dev/tpm0"
> > ** (tpm2-abrmd:399): WARNING **: 00:00:04.777: tcti_conf after: "device:/dev/tpm0"
> 

Fyi these superfluous warnings are fixed:
https://github.com/tpm2-software/tpm2-abrmd/pull/763

Not released yet, only on master.

> What do you think? Thanks again for your support.
> 
> EDIT:
> If I manually kill tpm2-tprmd process any tpm2_* command fails: this should also indicates that I'm using the abrmd, right?

Yep, i'd say so.

> 
> EDIT 2:
> It seems that using the built-in resource manager (settings TPM2TOOLS_TCTI=device:/dev/tpmrm0) I can start multiple sessions without having these memory problems. Probably it is something not correctly configured for the tpm2-abrmd. What could it be?

I'm surprised that works. When a process exits, the in-kernel RM flushes the sessions. So when you pass that to the next tool, the session passed via -S won't be valid. Either they finally added this missing feature in the in-kernel RM, or something weird is going on.

When tpm2-abrmd sees a session get saved via the -S option, it keeps that session alive for following commands. As you can imagine, this creates a memory leak. However, it's the only way to have multi-process chaining of session contexts. This does require you to **always** tpm2_flushcontext -s on exit of your script. You can also do a tpm2_flushcontext -s on startup as well. perhaps when your reboot, your TPM is not being restarted and you still have some transient state or something. I wonder what a `tpm2_getcap handles-saved-session` and a `tpm2_getcap handles-loaded-session` would show before and after these commands.

**Comment by p-gentili** [comment]
Thanks for your support. Switching to in-kernel resource manager solves the issue so it must be something related to my abrmd configuration: not related to tpm2-tools.
