### ISSUE TITLE
TPM2_PERMANENT_FIRST

### ISSUE THREAD

**Issue by SchermannR** [tpm2-software/tpm2-tools#2383]
![issue_permanent_first](https://user-images.githubusercontent.com/16487902/112354224-c1f1d300-8ccc-11eb-9b93-1cfb9679ca6e.png)

Hi, I tried to create a permanent key, but unfortunately this did not work...With TPM2_PERSISTENT_FIRST the code works...
However, the key_handle that I have received starts with 0x40 -> According to TCG this is a Permanent Resource Handle. (Persistent = 0x81)

rc was 0x1c4

Is there an issue in the Esys_EvictControl?

**Comment by JuergenReppSIT** [comment]
You can choose a persistent handle between 0x81000000 and 0x81ffffff. What handle did you use?
Do you mean with "key that you received" the parameter key_handle? That's an esys handle and not a TPM handle.

**Comment by SchermannR** [comment]
Hi, yea you are right...thx!
I used the TPM2_PERMANENT_FIRST      
#define TPM2_PERMANENT_FIRST      ((TPM2_HC) TPM2_RH_FIRST) -> #define TPM2_RH_FIRST       ((TPM2_RH) 0x40000000). Should be also visibly in the picture above. So it seems that the TPM2_PERMANENT_FIRST is not correct, but I need to take a closer look with the debugger.

**Comment by AndreasFuchsSIT** [comment]
Permanent are TPM's own resources as handle range.
What you want is TPM2_PERSISTENT_FIRST.
