### ISSUE TITLE
Receiving tpm2 error "Failed tpm session start auth with params"

### ISSUE THREAD

**Issue by darcyrailip** [tpm2-software/tpm2-tools#2681]
Running into this error trying to bind to `tpm2`:

```
# clevis luks bind -f -k- -d /dev/sde3 tpm2 '{"pcr_ids":"7"}'
ERROR: Failed tpm session start auth with params
ERROR: Error starting the policy session.
```

This worked before. I have been installing this on almost a hundred devices, and now I'm seeing this error on new devices.

This is what occurs in the install script:

```
# Secure Boot Mode:
part /boot/efi --fstype="efi" --size=200 --fsoptions="umask=0077,shortname=winnt"
part /boot     --fstype="xfs" --size=200
part /         --fstype="xfs" --grow --encrypted --passphrase=temppass
```

Later followed by:
```
yum install -y clevis clevis-luks clevis-dracut
# Entries from previous installs can remain and cause problems:
luksmeta nuke -f -d /dev/sde3
# Move decryption to the TPM:
clevis luks bind -f -k- -d /dev/sde3 tpm2 '{"pcr_ids":"7"}' <<< temppass
echo -n temppass | cryptsetup luksRemoveKey /dev/sde3 -
dracut -f
```

Something isn't quite working right anymore, however.

I see this output as well:

```
# luksmeta show -d /dev/sde3
0   active empty
1   active cb6e8904-81ff-40da-a84a-07ab9ab5715e
2 inactive empty
3 inactive empty
4 inactive empty
5 inactive empty
6 inactive empty
7 inactive empty
```

Any ideas on what may be going wrong here? The goal is to decrypt the drive with the tpm2 chip.

**Comment by williamcroberts** [comment]
What version of tpm2-tools?

**Comment by darcyrailip** [comment]
> What version of tpm2-tools?

```
tpm2-abrmd.x86_64    1.1.0-11.el7    @base
tpm2-tools.x86_64    3.0.4-3.el7     @base
tpm2-tss.x86_64      1.4.0-3.el7     @base
```

**Comment by williamcroberts** [comment]
Well package managers are usually behind the latest, especially for older stable releases. I wish I knew what the error was, normally tpm2-tss logs error returns, so I don't see that in your bug tracker which makes me think its not getting that far. Ive never touched clevis, but perhaps @martinezjavier has seen this issue?

**Comment by martinezjavier** [comment]
@darcyrailip can you please file a bug for your OS? As @williamcroberts said this issue is with an older stable release so not really suitable for upstream.
