### ISSUE TITLE
tpm2_rsadecrypt with OAEP padding

### ISSUE THREAD

**Issue by alexp-lyft** [tpm2-software/tpm2-tools#2691]
I'm trying to use tpm2_rsadecrypt with OAEP padding, but it fails with this error:
```
WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:301:Esys_RSA_Decrypt_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x000002c3)
ERROR: Esys_RSA_Decrypt(0x2C3) - tpm:parameter(2):hash algorithm not supported or not appropriate
ERROR: Unable to run tpm2_rsadecrypt
```
I'm able to use default padding (PKCSV1.5):
```
# tpm2_readpublic -c 0x81000005 -o key_pub.pem --f pem --quiet
# openssl rsautl -encrypt -inkey key_pub.pem -pubin -in msg.txt -out msg.enc
# tpm2_rsadecrypt -c 0x81000005 -o msg.out msg.enc
```

but when I try the same with OAEP it fails:
```
# tpm2_readpublic -c 0x81000005 -o key_pub.pem --f pem --quiet
# openssl rsautl -encrypt -oaep -inkey key_pub.pem -pubin -in msg.txt -out msg.enc
# tpm2_rsadecrypt -c 0x81000005 -s oaep -o msg.out msg.enc
WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:301:Esys_RSA_Decrypt_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x000002c3)
ERROR: Esys_RSA_Decrypt(0x2C3) - tpm:parameter(2):hash algorithm not supported or not appropriate
ERROR: Unable to run tpm2_rsadecrypt
```

The key is created and persisted as follows:
```
tpm2_clear
tpm2_createprimary \
	--hash-algorithm=sha256 \
	--key-algorithm=rsa \
	--key-context="primary.ctx" \
	--quiet
tpm2_create \
	--parent-context="primary.ctx" \
	--hash-algorithm=sha256 \
	--key-algorithm=rsa \
	--private="key.priv" \
	--public="key.pub" \
	--quiet
tpm2_load \
	--parent-context="primary.ctx" \
	--public="key.pub" \
	--private="key.priv" \
	--key-context="key.ctx" \
	--quiet
tpm2_evictcontrol 0x81000005 \
	--hierarchy=o \
	--object-context="key.ctx" \
	--quiet
```

also tried to create key with oaep-sha256 scheme, but got this error:
```
# tpm2_create -C primary.ctx -G rsa2048:oaep-sha256 -u key.pub -r key.priv
ERROR: Could not handle algorithm spec: "rsa2048:oaep-sha256"
ERROR: Unable to run tpm2_create
```

 
I'm using version 4.1.1
```
tool="tpm2_rsadecrypt" version="4.1.1" tctis="libtss2-tctildr" tcti-default=tcti-device
```

Am I missing something or my TPM doesn't support oaep?

**Comment by idesai** [comment]
@alexp-lyft this was added in faa79fa7 and fc34b4fd. However, both of them made to 5.0 release. Any reason you must still use 4.1.1?

**Comment by alexp-lyft** [comment]
Thanks @idesai . Sounds like i need to upgrade to v5.x. I'm on Ubuntu Bionic which only has tpm2 tools v3. 
I was able to install 4.1.1 on Boning using debian packages, will try to upgrade to 5.0.

**Comment by alexp-lyft** [comment]
so I've upgraded to 5.0, and it seems to recognize oaep scheme parameter. However now I'm getting a different error and still unable to decode data encoded with OAEP

```
# tpm2_readpublic -c 0x81000005 -o key_pub.pem --f pem --quiet
# openssl rsautl -encrypt -oaep -inkey key_pub.pem -pubin -in msg.txt -out msg.enc
# tpm2_rsadecrypt -c 0x81000005 -s oaep -o msg.out msg.enc
WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:305:Esys_RSA_Decrypt_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x00000084)
ERROR: Esys_RSA_Decrypt(0x84) - tpm:handle(unk):value is out of range or is not correct for the context
ERROR: Unable to run tpm2_rsadecrypt
```

```
# tpm2_rsadecrypt --version
tool="tpm2_rsadecrypt" version="5.0" tctis="libtss2-tctildr" tcti-default=tcti-device
```

**Comment by idesai** [comment]
@alexp-lyft, to make sure, Does this [sequence](https://github.com/tpm2-software/tpm2-tools/blob/master/test/integration/tests/rsadecrypt.sh#L85:#L90) work for you?

**Comment by alexp-lyft** [comment]
@idesai , yes, the tpm2_rsaencrypt / tpm2_rsadecrypt sequence works. It's only when I give it an input encrypted by openssl or golang crypto/rsa lib it fails to decrypt it.  

```
# tpm2_rsaencrypt -c 0x81000005 -s oaep -o msg.enc msg.txt
# tpm2_rsadecrypt -c 0x81000005 -s oaep -o msg.out msg.enc
```

Attributes:
```
# tpm2_readpublic -c 0x81000005 -o /tmp/key.pub
name: 000b7bd2fc31754b105f9cde7fb39c841a4e78f26add0c9fc0d5f77e8c2a9d4cfc2f
qualified name: 000b9a9cdfa2f5c3bc5eb4e431877ae17357809c4168a1df5e807e3ee5bd001cbbdb
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|decrypt|sign
  raw: 0x60072
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: null
  raw: 0x10
sym-mode:
  value: (null)
  raw: 0x0
sym-keybits: 0
rsa: d24ab93b9cbf329fe988981c8d48f695c0bc571fe1f21a178a7ed8ad954faac3078f6df5922bd32d242a19a700db4e201955e76f84484717b6482e8127c88697d0ad01ccbb1870fba8e25a00b4b9cb26e1e47e02e1af354b66bc83545de3ee43e7e974d8c23fd3fe71d883c259efbe7928cdc39148b9024575fd4f932b864622a3b8441b4e4eea784620c2c7daf021b03c24dcbbac72e4cf23ede8d06fec3f9d0c4668804a46c4c9334a2a01cff31427d2583cba79fad4b9bd99a93f6851c05daa396b6b386d7adb8f8aa735bcbd00a37da3ce3f7c75fe7f4155b89303689539ffa2e53b23756ed8f262df8de5d00456960c8b66ff6f531ec51c7a15c3925e3b
```

**Comment by idesai** [comment]
@alexp-lyft, did you try pkeyutl instead?

**Comment by alexp-lyft** [comment]
yes, just tried pkeyutll and it worked, which is  Now need to figure out the difference between the rsautl and pkeyutl commands. I actually encrypt in go binary, so need to repro it in goland as well.

**Comment by idesai** [comment]
> yes, just tried pkeyutll and it worked, which is great news! Now need to figure out the difference between the rsautl and pkeyutl commands. I actually encrypt in go binary, so need to repro it in goland as well.

The difference is the padding mode. rsautl is restricted to sha1 padding mode.

**Comment by alexp-lyft** [comment]
Got it, thanks for the explantation. I got it working with go as well. Thanks very much for help!

Does `tpm2_rsadecrypt` support sha512?

**Comment by idesai** [comment]
> Got it, thanks for the explantation. I got it working with go as well. Thanks very much for help!
> 
> Does `tpm2_rsadecrypt` support sha512?

Awesome. Not yet.

**Comment by alexp-lyft** [comment]
sounds good. Thanks again!

**Comment by williamcroberts** [comment]
> > Got it, thanks for the explantation. I got it working with go as well. Thanks very much for help!
> > Does `tpm2_rsadecrypt` support sha512?
> 
> Awesome. Not yet.

You'd have to find a TPM that support SHA512, the tool itself should have support, no?

**Comment by idesai** [comment]
> > > Got it, thanks for the explantation. I got it working with go as well. Thanks very much for help!
> > > Does `tpm2_rsadecrypt` support sha512?
> > 
> > 
> > Awesome. Not yet.
> 
> You'd have to find a TPM that support SHA512, the tool itself should have support, no?

We still have to add support for other algorithms. Currently, it's [hardcoded](https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_rsadecrypt.c#L96:#L98).

**Comment by williamcroberts** [comment]
> > > > Got it, thanks for the explantation. I got it working with go as well. Thanks very much for help!
> > > > Does `tpm2_rsadecrypt` support sha512?
> > > 
> > > 
> > > Awesome. Not yet.
> > 
> > 
> > You'd have to find a TPM that support SHA512, the tool itself should have support, no?
> 
> You are right. The TPM must have the support, to begin with. As for tools, we still have to add support for other algorithms. Currently, it's [hardcoded](https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_rsadecrypt.c#L96:#L98).

Ahh it needs to support the oaep-<hash> option as specified here by our man page:
  - https://github.com/tpm2-software/tpm2-tools/blob/master/man/common/alg.md#hash-optional-scheme-specifiers

**Comment by idesai** [comment]
The same changes are needed on the tpm2_rsaencrypt tool
