### ISSUE TITLE
configure: error: Invalid policy. Valid policies: git-directory, minor-version.

### ISSUE THREAD

**Issue by kgoldman** [tpm2-software/tpm2-tools#2696]
Ubuntu 16.04 Xenial 5.5.1 kernel 4.15

1. clone master 12 April 2021
2. ./bootstrap
3. ./configure

Yields error in the subject line.

**Comment by idesai** [comment]
@kgoldman possible that the autoconf is too old on your system?

**Comment by williamcroberts** [comment]
It's either one of two things:
1. Autoconf archive is too old
  - See: https://github.com/tpm2-software/tpm2-tools/issues/1972
2. You didn't clone it, you used the download zip feature (either use dedicated release tarballs or git clone)
  - See: https://github.com/tpm2-software/tpm2-tools/issues/2316

**Comment by kgoldman** [comment]
I used git clone git@github.com:tpm2-software/tpm2-tools.git

I don't know if autoconf is too old.  I thought the point of autotools is to handle differences.  I see a discussion in #1972. This pointed to some patches.  Someone suggested a path change. 

 What was the official fix?  Bottom line.

**Comment by williamcroberts** [comment]
> I used git clone [git@github.com](mailto:git@github.com):tpm2-software/tpm2-tools.git
> 
> I don't know if autoconf is too old. I thought the point of autotools is to handle differences. I see a discussion in #1972. This pointed to some patches. Someone suggested a path change.

autoconf is a set of m4 macros that do stuff, they are no different than any other piece of software. So like any software project, different features and bugs are introduced along the way. Debian is notoriously behind in the packaging of things, so using an EOL'd Ubuntu 16.04 will exacerbate things. I'd recommend Ubuntu-18.04 or 20.04 or one of the Fedora flavors. With that said, we still test on Ubuntu 16.04 for some projects.

> 
> What was the official fix? Bottom line.

Install a newer autoconf:

```bash
sudo apt-get purge autoconf-archive
autoconf_archive=autoconf-archive-2018.03.13
wget "http://mirror.kumi.systems/gnu/autoconf-archive/$autoconf_archive.tar.xz"
tar -xf $autoconf_archive.tar.xz
cd $autoconf_archive
./configure --prefix=/usr
make -j $(nproc) && make install
```

Do that, then run a git clean -fdx in the tpm2-tools project and re-run the bootstrap command.

**Comment by williamcroberts** [comment]
@kgoldman FYI, if you're ever wondering how to get it to build on distro X, our docker container images are good references:
  - https://github.com/williamcroberts/tpm2-software-container

They will give you all the commands to run to build a working docker container, which you can just use as the commands to build a working non-docker container as well for distro X. Note: they are processed with m4, but they are easily followed unprocessed. m4 is really only used for include statements.

**Comment by williamcroberts** [comment]
@kgoldman any luck?

**Comment by williamcroberts** [comment]
Stale
