### ISSUE TITLE
tpm2_import seems to ignore -p password

### ISSUE THREAD

**Issue by tedhkim** [tpm2-software/tpm2-tools#2708]
using tpm2-tools 4.3 and tpm2-tss 3.0

tpm2_import seems to ignore attempt to set password on imported object via -p password in command line

subsequent use of imported key with matching -p password fails with auth error, so it actually seems the import didn't setup the password

workaround seems to be to use tpm2_changeauth on private part being imported with -p password

but of course would be better if tpm2_import just worked with -p

**Comment by idesai** [comment]
@tedhkim can you share the exact steps? Are you trying to import a key whose sensitive portion is already encrypted?
