### ISSUE TITLE
 tpm2_createprimary -C primary.ctx (unable to create object after command executed successfully )

### ISSUE THREAD

**Issue by Nikilesh121** [tpm2-software/tpm2-tools#2712]
In same line if i execute the same command it throws me an error 
tpm2_createprimary -c primary.ctx
tpm2_createprimary: invalid option -- 'c'
ERROR: Unknown Argument: c

I am using this TPM tool for my testing process with TPM version  tpm_tis IFX0762:00: 2.0 TPM

**Comment by williamcroberts** [comment]
If I copy and paste your title:
```bash
$ echo 'tpm2_createprimary -C' | xxd
00000000: 7470 6d32 5f63 7265 6174 6570 7269 6d61  tpm2_createprima
00000010: 7279 202d 430a                           ry -C.
```
You're specifying capital C, which is not valid. It needs to be lowercase c.

Is that your problem, uppercase instead of lowercase C?

Lowercase c should be supported, what version of tpm2-tools are you using?
What does this command output?
```bash
tpm2_getrandom --version
````

**Comment by Nikilesh121** [comment]
Initially when i tried with small c i was getting an error given a try with capital C , 

Getting below error after executing it with small c 
#tpm2_createprimary -c primary.ctx
tpm2_createprimary: invalid option -- 'c'
ERROR: Unknown Argument: c


Please find the tpm version below 
 TPM]# tpm2_getrandom --version
tool="tpm2_getrandom" version="3.0.4" tctis="tabrmd,socket,device,"

For any changes and updates for tools or pkgs , please refer me a link or pkg .

**Comment by williamcroberts** [comment]
> Initially when i tried with small c i was getting an error given a try with capital C ,
> 
> Getting below error after executing it with small c
> #tpm2_createprimary -c primary.ctx
> tpm2_createprimary: invalid option -- 'c'
> ERROR: Unknown Argument: c

Yeah you're on very old tools, so it's capital C for 3.0.4. If we go back to my initial response, flip it. Ie use lowercase instead of uppercase. Know that options changed radically from 3.X to 4.X+ version. I would recommend to upgrade, any particular reason you're using 3.0.4?

> 
> Please find the tpm version below
> TPM]# tpm2_getrandom --version
> tool="tpm2_getrandom" version="3.0.4" tctis="tabrmd,socket,device,"
> 
> For any changes and updates for tools or pkgs , please refer me a link or pkg .
> @williamcroberts
> @idesai

Any way you could download the release tarball and build it?
https://github.com/tpm2-software/tpm2-tools/releases/tag/5.0

**Comment by Nikilesh121** [comment]
Hi williamcroberts  , i unable to install or might be configure the tpm2-tools 5.0 , getting an error of dependency pkg , unable to get it anywhere or any link of binary rpm file will be also really appreciated.Thanks in advance .
 

Here is the error which i encountered when i try to configure the latest tpm2-tools.
configure: error: Package requirements (tss2-sys >= 2.4.0) were not met:

No package 'tss2-sys' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables TSS2_SYS_CFLAGS
and TSS2_SYS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by williamcroberts** [comment]
> Hi williamcroberts , i unable to install or might be configure the tpm2-tools 5.0 , getting an error of dependency pkg , unable to get it anywhere or any link of binary rpm file will be also really appreciated.Thanks in advance .
> 
> Here is the error which i encountered when i try to configure the latest tpm2-tools.
> configure: error: Package requirements (tss2-sys >= 2.4.0) were not met:
> 
> No package 'tss2-sys' found
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables TSS2_SYS_CFLAGS
> and TSS2_SYS_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.

What's your OS version details?

**Comment by Nikilesh121** [comment]
OS : - Oracle Linux Server 7.7
KERNEL : 4.14.35-1902.3.2.el7uek.x86_64

**Comment by Nikilesh121** [comment]
Hi williamcroberts waiting for your reply , unable to upgrade tpm2-tss  
OS : OEL 7.7 I'm currently trying to install the latest tpm2-tss, It's installed, but as usual the version is very old (1.4.0-3 compared to 3.0.1) Running ./configure as per the "INSTALL" document, I found some problems below even after installing the json-c pkg .
configure: error: Package requirements (json-c) were not met:
No package 'json-c' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you installed software in a non-standard prefix.
Alternatively, you may set the environment variables JSONC_CFLAGS and JSONC_LIBS to avoid the need to call pkg-config. See the pkg-config man page for more details.
For reference :
#yum install json-c Loaded plugins: ulninfo Package json-c-0.11-4.el7_0.x86_64 already installed and latest version Nothing to do
rpm -qa | grep json-c

json-c-0.11-4.el7_0.i686 json-c-devel-0.11-4.el7_0.i686 json-c-0.11-4.el7_0.x86_64

**Comment by Nikilesh121** [comment]
Hi williamcroberts waiting for your reply , unable to upgrade tpm2-tss  
OS : OEL 7.7 I'm currently trying to install the latest tpm2-tss, It's installed, but as usual the version is very old (1.4.0-3 compared to 3.0.1) Running ./configure as per the "INSTALL" document, I found some problems below even after installing the json-c pkg .
configure: error: Package requirements (json-c) were not met:
No package 'json-c' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you installed software in a non-standard prefix.
Alternatively, you may set the environment variables JSONC_CFLAGS and JSONC_LIBS to avoid the need to call pkg-config. See the pkg-config man page for more details.
For reference :
#yum install json-c Loaded plugins: ulninfo Package json-c-0.11-4.el7_0.x86_64 already installed and latest version Nothing to do
rpm -qa | grep json-c

json-c-0.11-4.el7_0.i686 json-c-devel-0.11-4.el7_0.i686 json-c-0.11-4.el7_0.x86_64

**Comment by williamcroberts** [comment]
> Hi williamcroberts waiting for your reply , unable to upgrade tpm2-tss
> OS : OEL 7.7 I'm currently trying to install the latest tpm2-tss, It's installed, but as usual the version is very old (1.4.0-3 compared to 3.0.1) Running ./configure as per the "INSTALL" document, I found some problems below even after installing the json-c pkg .
> configure: error: Package requirements (json-c) were not met:
> No package 'json-c' found
> Consider adjusting the PKG_CONFIG_PATH environment variable if you installed software in a non-standard prefix.
> Alternatively, you may set the environment variables JSONC_CFLAGS and JSONC_LIBS to avoid the need to call pkg-config. See the pkg-config man page for more details.
> For reference :
> #yum install json-c Loaded plugins: ulninfo Package json-c-0.11-4.el7_0.x86_64 already installed and latest version Nothing to do
> rpm -qa | grep json-c
> 
> json-c-0.11-4.el7_0.i686 json-c-devel-0.11-4.el7_0.i686 json-c-0.11-4.el7_0.x86_64

Is the devel package installed? Above you yum install the normal one. You need the devel package for the package config and header files.

I cant replicate your issue, so I am perplexed. I think it might be a character set issue. I am going to grab a cetos7 docker image and try and replicate today, and at a minimum give you a dockerfile with something working in it to help give you a known good.

**Comment by williamcroberts** [comment]
Oh I think I see it now, i think gcc is right

**Comment by Nikilesh121** [comment]
Here are the packages which i found with OEL 7.7 
# rpm -qa | grep tpm
tpm2-tss-1.4.0-3.el7.x86_64
tpm2-tools-3.0.4-3.el7.x86_64
tpm2-tss-devel-1.4.0-3.el7.x86_64
tpm2-abrmd-1.1.0-11.el7.x86_64

**Comment by Nikilesh121** [comment]
Replicate Procedure , 
Installing the Os OEL 7.7 , Installing the Dependencies and trying to install the any tpm2-tss abbove 2.0 version will counter this issue , 
Below are the pkgs which i installed , let me know anything more i have to do apart from install.d doc . 
# yum install autoconf-archive   libcmocka0   libcmocka-dev   procps   iproute2   build-essential   git   pkg-config   gcc   libtool   automake   libssl-dev   uthash-dev   autoconf   doxygen   libjson-c-dev   libini-config-dev
Loaded plugins: ulninfo
Package autoconf-archive-2017.03.21-1.el7.noarch already installed and latest version
No package libcmocka0 available.
No package libcmocka-dev available.
Package procps-ng-3.3.10-28.el7.x86_64 already installed and latest version
No package iproute2 available.
No package build-essential available.
Package git-1.8.3.1-23.el7_8.x86_64 already installed and latest version
No package pkg-config available.
Package gcc-4.8.5-44.0.3.el7.x86_64 already installed and latest version
Package libtool-2.4.2-22.el7_3.x86_64 already installed and latest version
Package automake-1.13.4-3.el7.noarch already installed and latest version
No package libssl-dev available.
No package uthash-dev available.
Package autoconf-2.69-11.el7.noarch already installed and latest version
Package 1:doxygen-1.8.5-4.el7.x86_64 already installed and latest version
No package libjson-c-dev available.
No package libini-config-dev available.
Package libcmocka-devel-1.1.5-1.el7.x86_64 already installed and latest version
Package libcmocka-1.1.5-1.el7.x86_64 already installed and latest version
Package libcmocka-static-1.1.5-1.el7.x86_64 already installed and latest version
Package iproute-5.4.0-1.0.1.el7.x86_64 already installed and latest version
Package iproute-devel-5.4.0-1.0.1.el7.x86_64 already installed and latest version
Package iproute-doc-5.4.0-1.0.1.el7.x86_64 already installed and latest version
Package iproute-tc-5.4.0-1.0.1.el7.x86_64 already installed and latest version
Package 1:pkgconfig-0.27.1-4.el7.x86_64 already installed and latest version
Package openssl098e-0.9.8e-29.el7_2.3.x86_64 already installed and latest version
Package 1:openssl11-libs-1.1.1g-3.el7.x86_64 already installed and latest version
Package 1:dovecot-2.2.36-8.el7.x86_64 already installed and latest version
Package nss-3.53.1-7.el7_9.x86_64 already installed and latest version
Package 1:openssl-libs-1.0.2k-21.0.1.el7_9.x86_64 already installed and latest version
Package openssl098e-0.9.8e-29.el7_2.3.x86_64 already installed and latest version
Package dcap-tunnel-ssl-2.47.12-4.el7.x86_64 already installed and latest version
Package 1:openssl11-libs-1.1.1g-3.el7.x86_64 already installed and latest version
Package 1:dovecot-2.2.36-8.el7.x86_64 already installed and latest version
Package nss-3.53.1-7.el7_9.x86_64 already installed and latest version
Package 1:openssl-libs-1.0.2k-21.0.1.el7_9.x86_64 already installed and latest version
Package libini_config-1.3.1-32.el7.x86_64 already installed and latest version
Package json-c-0.11-4.el7_0.x86_64 already installed and latest version
Package json-c-0.11-4.el7_0.x86_64 already installed and latest version
Package json-c12-0.12.1-4.el7.x86_64 already installed and latest version

**Comment by williamcroberts** [comment]
If you use the packaged tools:
```bash
tpm2_createprimary -H o -G rsa -C primary.ctx
```
This works for me, Ill upload a docker file for you to build and run with.

If you want to update to newer tools (highly recommended), I can give you a script to install them.

**Comment by Nikilesh121** [comment]
yeah , surely , Thanks alot , let me try the script and update you once you send the script .

**Comment by williamcroberts** [comment]
Dockerfile Example
[demo.tar.bz2.txt](https://github.com/tpm2-software/tpm2-tools/files/6436438/demo.tar.bz2.txt)

Unpacking instructions
```bash
mv demo.tar.bz2.txt demo.tar.bz2
tar -xavf demo.tar.bz2
./build.sh
```

You'll need docker and dependencies.

**Comment by Nikilesh121** [comment]
ohh currently am using a bare metal server . not sure about the docker part , let me try out this anyhow .

**Comment by williamcroberts** [comment]
> ohh currently am using a bare metal server . not sure about the docker part , let me try out this anyhow .

You could probably just run script.sh

**Comment by Nikilesh121** [comment]
Please find the below output after execution .Guide me if i am wrong .Thanks a ton .
# tar -xavf demo.tar.bz2
README.md
build.sh
oraclelinux-7.7.docker
script.sh

# ./script.sh 
+ sleep 1
+ tpm_server
./script.sh: line 6: tpm_server: command not found
+ tpm2_startup --tcti=socket -c
^C

**Comment by williamcroberts** [comment]
Did you install tpm_server? If you look at the dockerfile, that has some dependencies that get installed. You gotta do a little sleuthing and observe, I can't do it all for you.

I got the below script to work on Oracle Linux. But you'll probably need to massage it a bit. But I am probably not going to have much time to guide you past this. Maybe small things.

```bash
#!/usr/bin/env bash
# SPDX: BSD-3-Clause

set -exo pipefail

# From a fresh install of Oracle Linux 7.7 in a Virtual Box VM:
# - Under Software Selection during the install, I Enabled
# - Server with GUI Option
# - Development Tools Option
# - System Administration Option
#
# I then installed the Guest Additions so I could get copy+paste working between my host and guest.
#
# With that said, my default packages could be different then your system. So I took a guess at what you would need.
# Ive done yum update
#

sudo yum groupinstall 'Development Tools' 'System Administration Tools'

# I had to disable quite a few things becuase I couldn't figure out why cmocka isn't in the yum repos as
# listed here:
#   - https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/x86_64/index_src.html
#
# Optional dependencies are:
#  - cmocka
#
sudo yum install -y openssl-devel dbus-glib-devel libcurl-devel libuuid-devel

#
# Only pkg-config --variable=pc_path pkg-config doesn't include /usr/local/lib/pkgconfig on default path, so export it.
# I tried tinkering with various config variables, like libdir, but never got something it liked. So this is easier.
#
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

#
# Set root to a directory we can build in. This can be passed as arg1
#
ROOT="$(realpath "${1:-$HOME}")"
cd "$ROOT"

#
# Install a TPM Simulator. I see that 1661 is available, however I haven't tested against it yet. However, 1637 works,
# but you have to fix up the memory issue as described in this PR:
#  - https://github.com/kgoldman/ibmswtpm2/pull/4
#
# We also need to make it respect CFLAGS, so we insert the CFLAGS variable into the Makefile, so we can pass the fixups.
#
mkdir ibmtpm1637
cd ibmtpm1637
wget https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm1637.tar.gz
sha256sum --check <<< 'dd3a4c3f7724243bc9ebcd5c39bbf87b82c696d1c1241cb8e5883534f6e2e327  ibmtpm1637.tar.gz'
tar -xavf ibmtpm1637.tar.gz
cd src
sed -i 's/-DTPM_NUVOTON/-DTPM_NUVOTON $(CFLAGS)/' makefile
CFLAGS="-DNV_MEMORY_SIZE=32768 -DMIN_EVICT_OBJECTS=7" make -j"$(nproc)"
sudo make install

cd "$ROOT"

#
# Build, test and install tpm2-tss libraries
#
wget https://github.com/tpm2-software/tpm2-tss/releases/download/3.0.3/tpm2-tss-3.0.3.tar.gz
sha256sum --check <<< '78392be7309baf47f51b122f566ac915fd4d1760ea78571cba2e1484f9b5be17  tpm2-tss-3.0.3.tar.gz'

tar -xavf tpm2-tss-3.0.3.tar.gz
cd tpm2-tss-3.0.3
# needs cmocka
#./configure --disable-doxygen-doc --disable-fapi --enable-unit --enable-integration
./configure --disable-doxygen-doc --disable-fapi
make -j"$(nproc)" check
sudo make install

#update the shared libraries for the dynamic linker
sudo ldconfig

cd "$ROOT"

#
# Build test and install tpm2-abrmd
#
wget https://github.com/tpm2-software/tpm2-abrmd/releases/download/2.4.0/tpm2-abrmd-2.4.0.tar.gz
sha256sum --check <<< '044522f1568f3d5334878f0564f808ec9fdd6a4ac5d0f3bd75ae6f2c7551a96c  tpm2-abrmd-2.4.0.tar.gz'
tar -xavf tpm2-abrmd-2.4.0.tar.gz
cd tpm2-abrmd-2.4.0
# patch dbus policy to allow THIS user to access dbus and thus start tpm2-abrmd on the system bus if they would like.
# this is not a production config, but makes casual use and development easy. For users, we could also attach it to
# the session bus. The session bus is restricted to the user and the system bus is global, for more details see:
#  - https://developer.gnome.org/platform-overview/unstable/tech-d-bus.html.en
#
#
# I DIDN't do this here, because you need to reload dbus for this to take affect (something like systemctrl restart dbus)
# which didn't seem to go as planned on oracle linux. Instead ill use the session bus.
#
#patch -p1 << PATCH
#--- tpm2-abrmd-2.4.0/dist/tpm2-abrmd.conf   2017-05-15 19:13:38.000000000 -0500
#+++ tpm2-abrmd-2.4.0/dist/tpm2-abrmd.conf   2021-05-04 13:56:26.478244361 -0500
#@@ -8,6 +8,9 @@
#   <policy user="root">
#     <allow own="com.intel.tss2.Tabrmd"/>
#   </policy>
#+  <policy user="$USER">
#+    <allow own="com.intel.tss2.Tabrmd"/>
#+  </policy>
#   <policy context="default">
#     <allow send_destination="com.intel.tss2.Tabrmd"/>
#     <allow receive_sender="com.intel.tss2.Tabrmd"/>
PATCH
#./configure --enable-unit --enable-integration --with-dbuspolicydir='/etc/dbus-1/system.d/'
./configure --with-dbuspolicydir='/etc/dbus-1/system.d/'
make -j"$(nproc)" check
sudo make install

#update the shared libraries for the dynamic linker
sudo ldconfig

cd "$ROOT"

#
# Build, test and install tpm2-tools tools
#
wget https://github.com/tpm2-software/tpm2-tools/releases/download/4.2/tpm2-tools-4.2.tar.gz
sha256sum --check <<< '1baaccd8bd663e9dd70cf6d8f99f16897ea32b9106860967ebb259d81954f904  tpm2-tools-4.2.tar.gz'
tar -xavf tpm2-tools-4.2.tar.gz
cd tpm2-tools-4.2
# Old compiler, need to disable hardening, 4.8 gcc is super pedantic about c99 mode.
# Need cmocka for --enable-unit
./configure --disable-hardening CFLAGS='-std=gnu99'
make -j"$(nproc)" check
sudo make install

cd "$ROOT"

#
# Run a sample command against the tpm2 simulator
# You need sleeps or something that is smarter and waits on the sockets to become avaialble. Since it will race
# the subsequent command on socket initialization of the first process.
#
dbus-run-session bash << SCRIPT
tpm_server &
sleep 1
tpm2-abrmd --session --tcti=mssim &
sleep 1
tpm2_getrandom --tcti=tabrmd:bus_type=session --hex 4
SCRIPT
```

**Comment by Nikilesh121** [comment]
Really appreciate your valuable time for this issue . Thanks  , Finally its working with the above steps mentioned , 
tpm2_createprimary -c primary.ctx 

name-alg:

  value: sha256

  raw: 0xb

attributes:

  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt

  raw: 0x30072

type:

  value: rsa

  raw: 0x1

exponent: 0x0

bits: 2048

scheme:

  value: null

  raw: 0x10

scheme-halg:

  value: (null)

  raw: 0x0

sym-alg:

  value: aes

  raw: 0x6

sym-mode:

  value: cfb

  raw: 0x43

sym-keybits: 128

rsa: e530b5e4d77210908f5617e4146cb2179724e8abb51166670d3748fe49eb6831b7130512af2a51c7d29594ce71657b089ecdf13e0dae26b1b1876de7d0595fcd604b212b54ec36cd8964611bbc69d663544a24107960ebd1cb6ac63d448e921089cff4c3edcea9566b2361d669993e6679551daed120845927898bb765278016c03eff0494c77e1fc0cef03f8b7cf6e2f0b6192cbaec90d4f5137fd140c72d49dd3a88596c146766c827d22941891a50c8100e7b9985f962a5661be411846379ba0785516aa832276aeb33d52acd4cb28b429e6f6d387f9d437fa8974bdef62f660935cb16d35f0547a8daeb8dc2ce2989942cbe344f36845a11b9bce347a871

**Comment by Akhil564** [comment]
Hi williamcroberts ,  
I am using this TPM tool for my testing process with TPM version tpm_tis IFX0762:00: 2.0 TPM. while working on this am getting following issue. could you please help me out regarding this error. Thanks in advance.
@williamcroberts 

# sudo systemctl start tpm2-abrmd
# sudo systemctl status tpm2-abrmd
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/etc/systemd/system/tpm2-abrmd.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2021-06-04 18:42:46 IST; 8s ago
 Main PID: 13522 (tpm2-abrmd)
    Tasks: 7
   CGroup: /system.slice/tpm2-abrmd.service
           └─13522 /usr/local/sbin/tpm2-abrmd

systemd[1]: Starting TPM2 Access Broker and Resource Management Daemon...
tpm2-abrmd[13522]: tcti_conf before: "(null)"
 tpm2-abrmd[13522]: tcti_conf after: "device:/dev/tpm0"
systemd[1]: Started TPM2 Access Broker and Resource Management Daemon.


# tpm2_getrandom -V 16
INFO on line: "44" in file: "lib/tpm2_capability.c": GetCapability: capability: 0x6, property: 0x100
INFO on line: "44" in file: "lib/tpm2_capability.c": GetCapability: capability: 0x6, property: 0x214


-> while executing tpm2 related commands like tpm2_nvlist  and for all commands getting like an error. could you look that error as below....

# tpm2_nvlist

** (process:25409): ERROR **: 19:10:21.698: CreateConnection expected to return 2 handles, received 1
Trace/breakpoint trap


# sudo -u tss G_MESSAGES_DEBUG=all tpm2-abrmd &
[1] 17832
# [1] 6054** INFO: 18:52:54.406: tabrmd startup
** (process:17834): DEBUG: 18:52:54.407: tcti_options_set_property
** (process:17834): DEBUG: 18:52:54.407:   PROP_TCTI_TYPE
** (process:17834): DEBUG: 18:52:54.407:   value: 0x1
** (process:17834): DEBUG: 18:52:54.407: tcti_options_set_property
** (process:17834): DEBUG: 18:52:54.407: TctiOptions set device_name: /dev/tpm0
** (process:17834): DEBUG: 18:52:54.407: tcti_options_set_property
** (process:17834): DEBUG: 18:52:54.407: TctiOptions set socket_address: 127.0.0.1
** (process:17834): DEBUG: 18:52:54.407: tcti_options_set_property
** (process:17834): DEBUG: 18:52:54.407: TctiOptions set socket_port: 2321
** INFO: 18:52:54.407: logging to stdout
** (tpm2-abrmd:17834): DEBUG: 18:52:54.407: tcti_options_get_tcti
** (tpm2-abrmd:17834): DEBUG: 18:52:54.407: TctiDevice set filename: /dev/tpm0
** INFO: 18:52:54.407: entering g_main_loop
** INFO: 18:52:54.407: init_thread_func start
** (tpm2-abrmd:17834): DEBUG: 18:52:54.408: random_class_init
** (tpm2-abrmd:17834): DEBUG: 18:52:54.408: opening entropy source: /dev/urandom
** (tpm2-abrmd:17834): DEBUG: 18:52:54.408: reading from entropy source: /dev/urandom
** (tpm2-abrmd:17834): DEBUG: 18:52:54.408: seeding rand with 8561363406376705609
** (tpm2-abrmd:17834): DEBUG: 18:52:54.408: connection_manager_set_property: 0x7f0a2c0020c0
** (tpm2-abrmd:17834): DEBUG: 18:52:54.408:   max_connections: 0x1b
** (tpm2-abrmd:17834): DEBUG: 18:52:54.408: ConnectionManager: 0x7f0a2c0020c0
** (tpm2-abrmd:17834): DEBUG: 18:52:54.408: tcti_initialize: 0x123e400

** (tpm2-abrmd:17834): WARNING **: 18:52:54.408: failed to initialize device TCTI context: 0xa000a

** (tpm2-abrmd:17834): CRITICAL **: 18:52:54.408: TCTI initialization failed: 0xa000a

**Comment by williamcroberts** [comment]
For this error:
`** (process:25409): ERROR **: 19:10:21.698: CreateConnection expected to return 2 handles, received 1`

Iv'e only ever seen one report of this, and it was on a WSL system. I have no idea what causes it. 

For this error:
`** (tpm2-abrmd:17834): WARNING **: 18:52:54.408: failed to initialize device TCTI context: 0xa000a`

Whats the permissions on `/dev/tpm0`? Since your starting the process as user tss, user tss needs read/write perms on that file.

**Comment by Akhil564** [comment]
Thanks for your reply williamcroberts,

# cat /etc/udev/rules.d/99-tpm-perm.rules 
# tpm devices can only be accessed by the tss user but the tss
# group members can access tpmrm devices
KERNEL=="tpm0", MODE="0660", OWNER="tss", GROUP="tss"
KERNEL=="tpmrm0", MODE="0660", OWNER="tss", GROUP="tss"

i have configured with the udev rules and the above things i have included.

**Comment by shootingatshadow** [comment]
Please do:
```bash
ls -la /dev/tpm0
```

**Comment by williamcroberts** [comment]
Please do:
```bash
ls -la /dev/tpm0
```

**Comment by Akhil564** [comment]
# ls -la /dev/tpm0
crw-rw---- 1 tss tss 10, 224 Jun  4 18:39 /dev/tpm0
i got this one.

**Comment by williamcroberts** [comment]
I wish I knew, try setting environment vairbale `G_DEBUG=all` when you start up tpm2-abrmd

**Comment by Akhil564** [comment]
yaa i have tried  with setting environment vairbale G_DEBUG=all. still same issue

**Comment by williamcroberts** [comment]
> yaa i have tried with setting environment vairbale G_DEBUG=all. still same issue

Do the logs indicate what's failing? Can we run I through strace to get whats failing?

**Comment by Akhil564** [comment]
------>can you check this logs

 systemd-logind: New session 185 of user root.
 systemd: Started Session 185 of user root.
tpm2-toolbox.tpm-server: error: timeout waiting for snap system profiles to get updated
tpm2-toolbox.tpm2-abrmd: error: timeout waiting for snap system profiles to get updated
systemd: snap.tpm2-toolbox.tpm2-abrmd.service: main process exited, code=exited, status=1/FAILURE
 systemd: Unit snap.tpm2-toolbox.tpm2-abrmd.service entered failed state.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service failed.
systemd: snap.tpm2-toolbox.tpm-server.service: main process exited, code=exited, status=1/FAILURE
 systemd: Unit snap.tpm2-toolbox.tpm-server.service entered failed state.
 systemd: snap.tpm2-toolbox.tpm-server.service failed.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service holdoff time over, scheduling restart.
 systemd: snap.tpm2-toolbox.tpm-server.service holdoff time over, scheduling restart.
 systemd: Stopped Service for snap application tpm2-toolbox.tpm-server.
 systemd: Started Service for snap application tpm2-toolbox.tpm-server.
 systemd: Stopped Service for snap application tpm2-toolbox.tpm2-abrmd.
 systemd: Started Service for snap application tpm2-toolbox.tpm2-abrmd.
 kernel: traps: tpm2_nvlist[27442] trap int3 ip:7fc35661cbe1 sp:7ffdd1d4eb00 error:0 in libglib-2.0.so.0.5600.1[7fc3565cb000+114000]
 systemd: Started Session 186 of user root.
 systemd: Started Session 187 of user root.
tpm2-toolbox.tpm-server: error: timeout waiting for snap system profiles to get updated
 tpm2-toolbox.tpm2-abrmd: error: timeout waiting for snap system profiles to get updated
 systemd: snap.tpm2-toolbox.tpm-server.service: main process exited, code=exited, status=1/FAILURE
 systemd: Unit snap.tpm2-toolbox.tpm-server.service entered failed state.
 systemd: snap.tpm2-toolbox.tpm-server.service failed.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service: main process exited, code=exited, status=1/FAILURE
systemd: Unit snap.tpm2-toolbox.tpm2-abrmd.service entered failed state.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service failed.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service holdoff time over, scheduling restart.
 systemd: snap.tpm2-toolbox.tpm-server.service holdoff time over, scheduling restart.
 systemd: Stopped Service for snap application tpm2-toolbox.tpm-server.
 systemd: Started Service for snap application tpm2-toolbox.tpm-server.
systemd: Stopped Service for snap application tpm2-toolbox.tpm2-abrmd.
 systemd: Started Service for snap application tpm2-toolbox.tpm2-abrmd.
 tpm2-toolbox.tpm-server: error: timeout waiting for snap system profiles to get updated
 tpm2-toolbox.tpm2-abrmd: error: timeout waiting for snap system profiles to get updated
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service: main process exited, code=exited, status=1/FAILURE
 systemd: Unit snap.tpm2-toolbox.tpm2-abrmd.service entered failed state.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service failed.
systemd: snap.tpm2-toolbox.tpm-server.service: main process exited, code=exited, status=1/FAILURE
 systemd: Unit snap.tpm2-toolbox.tpm-server.service entered failed state.
 systemd: snap.tpm2-toolbox.tpm-server.service failed.
 systemd: snap.tpm2-toolbox.tpm-server.service holdoff time over, scheduling restart.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service holdoff time over, scheduling restart.
 systemd: Stopped Service for snap application tpm2-toolbox.tpm2-abrmd.
 systemd: Started Service for snap application tpm2-toolbox.tpm2-abrmd.
 systemd: Stopped Service for snap application tpm2-toolbox.tpm-server.
 systemd: Started Service for snap application tpm2-toolbox.tpm-server.
systemd: Started Session 188 of user root.
 tpm2-toolbox.tpm2-abrmd: error: timeout waiting for snap system profiles to get updated
tpm2-toolbox.tpm-server: error: timeout waiting for snap system profiles to get updated
systemd: snap.tpm2-toolbox.tpm2-abrmd.service: main process exited, code=exited, status=1/FAILURE
 systemd: Unit snap.tpm2-toolbox.tpm2-abrmd.service entered failed state.
systemd: snap.tpm2-toolbox.tpm2-abrmd.service failed.
 systemd: snap.tpm2-toolbox.tpm-server.service: main process exited, code=exited, status=1/FAILURE
systemd: Unit snap.tpm2-toolbox.tpm-server.service entered failed state.
  systemd: snap.tpm2-toolbox.tpm-server.service failed.
 systemd: snap.tpm2-toolbox.tpm-server.service holdoff time over, scheduling restart.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service holdoff time over, scheduling restart.
 systemd: Stopped Service for snap application tpm2-toolbox.tpm2-abrmd.
 systemd: Started Service for snap application tpm2-toolbox.tpm2-abrmd.
 systemd: Stopped Service for snap application tpm2-toolbox.tpm-server.
 systemd: Started Service for snap application tpm2-toolbox.tpm-server.
 tpm2-toolbox.tpm-server: error: timeout waiting for snap system profiles to get updated
tpm2-toolbox.tpm2-abrmd: error: timeout waiting for snap system profiles to get updated
systemd: snap.tpm2-toolbox.tpm-server.service: main process exited, code=exited, status=1/FAILURE
 systemd: Unit snap.tpm2-toolbox.tpm-server.service entered failed state.
 systemd: snap.tpm2-toolbox.tpm-server.service failed.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service: main process exited, code=exited, status=1/FAILURE
 systemd: Unit snap.tpm2-toolbox.tpm2-abrmd.service entered failed state.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service failed.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service holdoff time over, scheduling restart.
 systemd: snap.tpm2-toolbox.tpm-server.service holdoff time over, scheduling restart.
systemd: Stopped Service for snap application tpm2-toolbox.tpm-server.
 systemd: Started Service for snap application tpm2-toolbox.tpm-server.
 systemd: Stopped Service for snap application tpm2-toolbox.tpm2-abrmd.
 systemd: Started Service for snap application tpm2-toolbox.tpm2-abrmd.
 systemd-logind: New session 189 of user root.
systemd: Started Session 189 of user root.
systemd-logind: New session 190 of user root.
 systemd: Started Session 190 of user root.
 systemd: Started Session 191 of user root.
 systemd: Stopping TPM2 Access Broker and Resource Management Daemon...
 systemd: Stopped TPM2 Access Broker and Resource Management Daemon.
 systemd: Starting TPM2 Access Broker and Resource Management Daemon...
journal: tcti_conf before: "(null)"
 journal: tcti_conf after: "device:/dev/tpm0"
systemd: Started TPM2 Access Broker and Resource Management Daemon
 tpm2-toolbox.tpm-server: error: timeout waiting for snap system profiles to get updated
tpm2-toolbox.tpm2-abrmd: error: timeout waiting for snap system profiles to get updated
 systemd: snap.tpm2-toolbox.tpm-server.service: main process exited, code=exited, status=1/FAILURE
 systemd: Unit snap.tpm2-toolbox.tpm-server.service entered failed state.
systemd: snap.tpm2-toolbox.tpm-server.service failed.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service: main process exited, code=exited, status=1/FAILURE
 systemd: Unit snap.tpm2-toolbox.tpm2-abrmd.service entered failed state.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service failed.
 systemd: snap.tpm2-toolbox.tpm2-abrmd.service holdoff time over, scheduling restart.
 systemd: snap.tpm2-toolbox.tpm-server.service holdoff time over, scheduling restart.
 systemd: Stopped Service for snap application tpm2-toolbox.tpm-server.
 systemd: Started Service for snap application tpm2-toolbox.tpm-server.
 systemd: Stopped Service for snap application tpm2-toolbox.tpm2-abrmd.
 systemd: Started Service for snap application tpm2-toolbox.tpm2-abrmd.

**Comment by Akhil564** [comment]
Hi williamcroberts waiting for your reply , unable to sort out the issue.

**Comment by williamcroberts** [comment]
No idea, not really sure and I haven't had time to setup your environment to try and reproduce.We got to get logs as to why tpm2-abrmd is failing to start.

With that said, the tools can use /dev/tpmrm0 or /dev/tpm0 directly with sufficient permissions using the `--tcti` option. `--tcti=device:/dev/tpmrm0` or `--tcti=device:/dev/tpm0`. That could be a workaround for now. You could also try manually starting the tpm2-abrmd daemon on the session bus: `tpm2-abrmd --session --tcti=device:/dev/tpm0` and then starting the tools with option `--tcti:tabrmd:bus_type=session`.
