### ISSUE TITLE
ImportError: No module named yaml

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-tools#2714]
Ubuntu groovy 

When building, I get this:

checking for python... yes
checking for module yaml in python... Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named yaml
not found
configure: WARNING: System tests require pyyaml, some tests will fail!

**Comment by kgold2** [comment]
From a mailing list, the symlink works, but could break other software.  Perhaps there's a better solution than manually changing a system file.

~~~

I think all the python used is python3 compatible, so you could just symlink python to python3. Most distros would use something like update-alternatives so you can control python and python3 independently and have both side by side or not.

In my system, Ubuntu 20.04, python is /usr/bin/python --> /etc/alternatives/python --> /usr/bin/python3 and python3 is /usr/bin/python3 --> /usr/local/bin/python3.8

**Comment by williamcroberts** [comment]
2 things here:
- python command has a sorted history, see https://www.python.org/dev/peps/pep-0394/ for the details. Just read the Recommendation section for the TL;DR.

You don't have to modify the system files. Add to your path and symlink it from there. update-alternatives is generally how folks do it, so thats the way I advised.

This error is that you didn't install pyyaml. You can either use the distro package manager or pip to install it:
pip example, but you need to have pip installed.

For ubuuntu 20.04
```bash
# you can also get pip via https://pip.pypa.io/en/stable/installing/
apt-get install python3-pip
python -m pip install pyyaml
```
OR package manager

```bash
sudo apt-get install python3-yaml
```
