### ISSUE TITLE
fapi config

### ISSUE THREAD

**Issue by cleversonsch** [tpm2-software/tpm2-tools#2724]
Hi,

I am new user of the tpm. I have been using the evaluation board. I think  I am having some trouble to use the FAPI, That is the message I get when I enter tss2_provision in the command line:

ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:521:Fapi_Provision_Finish() ErrorCode (0x0006000b) SRK persistent handle already defined 
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x0006000b) Provision 
Fapi_Provision(0x6000B) - fapi:A parameter has a bad value

And that is for the tss2_list in the command line:
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:521:Fapi_Provision_Finish() ErrorCode (0x0006000b) SRK persistent handle already defined 
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x0006000b) Provision 
Fapi_Provision(0x6000B) - fapi:A parameter has a bad value

That must be something simple, I am sorry for that.

**Comment by williamcroberts** [comment]
Yes it means theirs already a persistent key setup. I'm not sure how you proceed under this condition, @AndreasFuchsSIT or @JuergenReppSIT might know?

**Comment by cleversonsch** [comment]
Sorry, that is for the tss2_list:
WARNING:fapi:src/tss2-fapi/api/Fapi_List.c:216:Fapi_List_Finish() Path not found:  
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:81:Fapi_List() ErrorCode (0x00060034) Entities_List 
Fapi_List(0x60034) - fapi:Provisioning was not executed.

**Comment by cleversonsch** [comment]
I could fix the problem by clearing the NVRAM first and then clearing the FAPI...

**Comment by JuergenReppSIT** [comment]
It's also possible to use another handle for the SRK. It can be adjusted in the FAPI profile:
` "srk_template": "system,restricted,decrypt,0x81000001",`

**Comment by mike2307** [comment]
> I could fix the problem by clearing the NVRAM first and then clearing the FAPI...

@cleversonsch:
Can you please provide instructions on how you did that?
