### ISSUE TITLE
Export a key from TPM to openssl (TPM -> OpenSSL)

### ISSUE THREAD

**Issue by boissinp** [tpm2-software/tpm2-tools#2725]
Hi,
I'm trying to export a key from a TPM to OpenSSL in order to run a decrypt operation with OpenSSL (TPM take too much time to decrypt).

I have not found this feature. With the command tpm2_duplicate, only the opposite operation seems available

Is there a way to do that ?

**Comment by idesai** [comment]
@boissinp, no this is not implemented. Why not also create the key using OpenSSL?

**Comment by williamcroberts** [comment]
@idesai perhaps sealing a key to the TPM? @boissinp I'm assuming since speed is critical, you're looking at a symmetric operation in OpenSSL? Either way, you could use tpm2_create to seal a key to the TPM, perhaps with a policypcr/policysigned so it only unlocks in a particular system state. Then you would use tpm2_unseal and pull the key out to use with openssl.

**Comment by boissinp** [comment]
> Why not also create the key using OpenSSL?

I should have precise : First, I transfer the key from a tpm A to a tpm B using tpm2_duplicate. Once the key is on tpm B I would run the decrypt operation with openSSL (yes, it's a symetric operation with an AES key). 
So unfortunately, in my situation I don't think it's make sens to seal that to the TPM ...

**Comment by boissinp** [comment]
Yes, transfer a key by duplication is working

> tpm2_encryptdecrypt is the interface to symmetric keys, with an RSA assymetric keypair you would use rsadecrypt and rsaencrypt.
Of course. In my scenario, the symmetric key, is crypted by rsa during transfer. So once in the deviceB I use tpm2_rsadecrypt to find back my symmetric key.

In fact, It will be cool to allow the creation of crypted session betweem TPM and other entities such as OpenSSL

**Comment by williamcroberts** [comment]
> Yes, transfer a key by duplication is working
> 
> > tpm2_encryptdecrypt is the interface to symmetric keys, with an RSA assymetric keypair you would use rsadecrypt and rsaencrypt.
> 
> Of course. In my scenario, the symmetric key, is crypted by rsa during transfer. So once in the deviceB I use tpm2_rsadecrypt to find back my symmetric key.

The risk is that at some point the key is in plaintext outside of the TPM.

> 
> In fact, It will be cool to allow the creation of crypted session betweem TPM and other entities such as OpenSSL

When you import, the private portion is protected with the importation parent and optionally another inner AES key.

But again, theirs a point in time the key is open to being in the clear, so it needs to be accounted for in your threat model. Where as a TPM generated key is never open to this attack. Both keys would be subject to threats against the TPM.
