### ISSUE TITLE
There is an error running TPM2_hash.sh. This may be a bug

### ISSUE THREAD

**Issue by hammerzero** [tpm2-software/tpm2-tools#2730]
An error occurred while running the test//integration/tests/tpm2_hash.sh with the following error message:
ERROR:esys:src/tss2-esys/esys_iutil.c:394:iesys_handle_to_tpm_handle() Error: Esys invalid ESAPI handle (40000007). 
WARNING:esys:src/tss2-esys/esys_iutil.c:416:iesys_is_platform_handle() Convert handle from TPM2_RH to ESYS_TR, got: 0x40000007
Test environment:
debian10
tpm2-tools: tpm2-tools-4.0 
tpm2-tss: tpm2simulator-master.zip(download 20210414)
tpm2-simulator: tpm2simulator-master.zip(download 20210414)

Through the analysis of the code, the reasons are as follows:
tpm2_hash.c hierarchy is init：
static tpm_hash_ctx ctx = {
    .hierarchy_value = TPM2_RH_OWNER,
    .halg = TPM2_ALG_SHA1,
};
Hierarchy_value needs to be converted from "Iesys Handle" to "TPM Handle" when the ESYS API is invoked.
eg：TPM2_RH_OWNER to ESYS_TR_RH_OWNER.

Because the function "Esys_Hash_Async ()" in TSS will call the function "iesys_handle_to_tPM_handle ()" for the conversion.
So that could be a problem.

**Comment by williamcroberts** [comment]
> An error occurred while running the test//integration/tests/tpm2_hash.sh with the following error message:
> ERROR:esys:src/tss2-esys/esys_iutil.c:394:iesys_handle_to_tpm_handle() Error: Esys invalid ESAPI handle (40000007).
> WARNING:esys:src/tss2-esys/esys_iutil.c:416:iesys_is_platform_handle() Convert handle from TPM2_RH to ESYS_TR, got: 0x40000007
> Test environment:
> debian10
> tpm2-tools: tpm2-tools-4.0
> tpm2-tss: tpm2simulator-master.zip(download 20210414)
> tpm2-simulator: tpm2simulator-master.zip(download 20210414)
> 
> Through the analysis of the code, the reasons are as follows:
> tpm2_hash.c hierarchy is init：
> static tpm_hash_ctx ctx = {
> .hierarchy_value = TPM2_RH_OWNER,
> .halg = TPM2_ALG_SHA1,
> };
> Hierarchy_value needs to be converted from "Iesys Handle" to "TPM Handle" when the ESYS API is invoked.
> eg：TPM2_RH_OWNER to ESYS_TR_RH_OWNER.
> 
> Because the function "Esys_Hash_Async ()" in TSS will call the function "iesys_handle_to_tPM_handle ()" for the conversion.
> So that could be a problem.

The tools commands themselves should still be completing okay, just noisily. The backwards compat shim (see history), is noisy on purpose. So application developers, like tpm2-tools, will update their handles accordingly. Which tpme-tools did in 

What's your version of tpm2-tss? You show `tpm2-tss: tpm2simulator-master.zip(download 20210414)`, but that doesn't seem right. Ie what does command `pkg-config --modversion tss2-esys` return?

Certain versions of the tools internally should call `fix_esys_hierarchy` in the lib/tpm2.c routines as needed, see commits:
- 2d323cdc0
- e607f78a0
- 715d62bc5

Which is on 4.2.1+. So if your tools version is < 4.2.1, you will have a noisy tools, but they should work.

The history of tpm2-tss:
The ESYS API was changed in commit:
  - https://github.com/tpm2-software/tpm2-tss/commit/9d48cc7922ad8dc3496444b04c94439c5bfbec8e

However, in commit https://github.com/tpm2-software/tpm2-tss/commit/6e508670b3b7d4e49b52ab591fb76db49aaf3135 I changed it to be backwards compat.

**Comment by hammerzero** [comment]
After I upgraded tpm2_tools to version 4.2.x,(pkg-config --modversion tss2-esys == 3.1.0-rc0)
As an ordinary user, I login to the home page of tPM2-software and default prompt is that I download the master version. However, after downloading and deploying the environment, it cannot run normally due to version matching problems. Therefore, I suggest providing a complete download link of the suite (including :TSS SWTPM Tools, abrmd, etc.).

**Comment by williamcroberts** [comment]
Where do we tell you to download master?

**Comment by hammerzero** [comment]
Please be aware of this BUG, which affects usage.
Test version: TPM2-tools-4.2.x
The parameter "c" is not defined in the file "tpm2_flushcontext.c"。see tools/tpm2_flushcontext.c：
static bool on_option(char key, char *value) {
    UNUSED(value);
    if (ctx.encountered_option) {
        LOG_ERR("Options -t, -l and -s are mutually exclusive");
        return false;
    }
    ctx.encountered_option = true;
    switch (key) {
    case 't':
        ctx.property = TPM2_TRANSIENT_FIRST;
        break;
    case 'l':
        ctx.property = TPM2_LOADED_SESSION_FIRST;
        break;
    case 's':
        ctx.property = TPM2_ACTIVE_SESSION_FIRST;
        break;
    }
    return true;
}
However, the "-c" option is used in the "flushContext.sh" script file:
res=`tpm2_getcap handles-transient`
if [ -n "$res" ]; then
    tpm2_flushcontext -Q -c 0x80000000
fi
so,the runtime will report an error:
tpm2_flushcontext: invalid option -- 'c'

**Comment by hammerzero** [comment]
Please be aware of this BUG, which affects usage.
Test version: TPM2-tools-4.2.x
The parameter "c" is not defined in the file "tpm2_flushcontext.c"。see tools/tpm2_flushcontext.c：
static bool on_option(char key, char *value) {
    UNUSED(value);
    if (ctx.encountered_option) {
        LOG_ERR("Options -t, -l and -s are mutually exclusive");
        return false;
    }
    ctx.encountered_option = true;
    switch (key) {
    case 't':
        ctx.property = TPM2_TRANSIENT_FIRST;
        break;
    case 'l':
        ctx.property = TPM2_LOADED_SESSION_FIRST;
        break;
    case 's':
        ctx.property = TPM2_ACTIVE_SESSION_FIRST;
        break;
    }
    return true;
}
However, the "-c" option is used in the "flushContext.sh" script file:
res=`tpm2_getcap handles-transient`
if [ -n "$res" ]; then
    tpm2_flushcontext -Q -c 0x80000000
fi
so,the runtime will report an error:
tpm2_flushcontext: invalid option -- 'c'

**Comment by idesai** [comment]
The change to specify context as cmd line arg was introduced in 4.X and we are backwards compatible with 4.X for all releases since.
