### ISSUE TITLE
How to `TPM2_CreateLoaded()` a key using a fixed template and sensitive area to deterministically create the same key repeatedly on the same TPM?

### ISSUE THREAD

**Issue by nicowilliams** [tpm2-software/tpm2-tools#2752]
How to `TPM2_CreateLoaded()` a key using a fixed template and sensitive area to deterministically create the same key repeatedly on the same TPM?

**Comment by nicowilliams** [comment]
Answer: `tpm2 create --parent-context endorsement -c k.ctx`.

**Comment by ReeceNee** [comment]
A related question, how to create the same key repeatedly on the different TPMs? It means how to give the fixed seed/sensitive data, make sure different TPM can derive the same keys?

**Comment by ReeceNee** [comment]
> A related question, how to create the same key repeatedly on the different TPMs? It means how to give the fixed seed/sensitive data, make sure different TPM can derive the same keys?

@nicowilliams Is there any advice? thanks!

**Comment by williamcroberts** [comment]
> endorsement

I don't think that's possible. Each TPM will have it's own hierarchy seed, so no matter what you'll end up at a different key. For non-primary keys, the're always generated for ECC and RSA. For symmetric and keyedhash, you can set the data field in the TPMS_SENSITIVE_CREATE structure and have sensitiveDataOrigin bit clear in the attributes. Else the keys are generated from the RNG.

If you want TPM's to have a same asymmetric key, you can import the key. If you want them to have the same symmetric or keyedhash, you can set the sensitive data field on creation.

**Comment by ReeceNee** [comment]
> > endorsement
> 
> I don't think that's possible. Each TPM will have it's own hierarchy seed, so no matter what you'll end up at a different key. For non-primary keys, the're always generated for ECC and RSA. For symmetric and keyedhash, you can set the data field in the TPMS_SENSITIVE_CREATE structure and have sensitiveDataOrigin bit clear in the attributes. Else the keys are generated from the RNG.
> 
> If you want TPM's to have a same asymmetric key, you can import the key. If you want them to have the same symmetric or keyedhash, you can set the sensitive data field on creation.

Yes, I'm trying to create(or derivate) the same symmetric key from different TPMs by calling tpm2_crate(). The idea of given specific TPMS_SENSITIVE_CREATE structure is good and I also find it from the TPM Spec docs. However, I could not find any samples for how to set the parameter in tpm2_crate commands( tpm2-tools level).

**Comment by ReeceNee** [comment]
> > endorsement
> 
> I don't think that's possible. Each TPM will have it's own hierarchy seed, so no matter what you'll end up at a different key. For non-primary keys, the're always generated for ECC and RSA. For symmetric and keyedhash, you can set the data field in the TPMS_SENSITIVE_CREATE structure and have sensitiveDataOrigin bit clear in the attributes. Else the keys are generated from the RNG.
> 
> If you want TPM's to have a same asymmetric key, you can import the key. If you want them to have the same symmetric or keyedhash, you can set the sensitive data field on creation.

Actually, the TPMS_SENSITIVE_CREATE structure now can only be set by -i option for the keydhash type, while not for the symmetric key. I found the restrict from the [tpm2-tools/tpm2_create.c](https://github.dev/tpm2-software/tpm2-tools/blob/4e31eaeb45aed04887a0d28202153507da520309/tools/tpm2_create.c#L477) . Is it conflict with the tpm2 spec?
