### ISSUE TITLE
tpm2_checkquote / ERROR: Malformed PCR file, pcr count cannot be greater than 32, got: <BIG NUMBER>

### ISSUE THREAD

**Issue by aplanas** [tpm2-software/tpm2-tools#2767]
I am playing with tpm2-tools in relation with keylime, using vTPM and QEMU. I can see that keylime fails during the quote validation with an error similar to the one in the title, and I am able to reproduce it using the documented example for "tpm2_checkquote":

```bash
# tpm2_clear -v
tool="tpm2_clear" version="5.1" tctis="libtss2-tctildr" tcti-default=tcti-abrmd

# tpm2_clear

# tpm2_createek -c 0x81010001 -G rsa -u ekpub.pem -f pem

# tpm2_createak -C 0x81010001 -c ak.ctx -G rsa -s rsassa -g sha256 -u akpub.pem -f pem -n ak.name
loaded-key:
  name: 000b857dee16b05486730b02a7bb8306305a0ca3ca6f4d83df1afeaaed79ad72d319
  qualified name: 000b3231360fe2abd45d9825cc2ce5df8541ab591b5dc205a2f4affc18b85b4be57a

# tpm2_quote -c ak.ctx -l sha256:15,16,22 -q abc123 -m quote.msg -s quote.sig -o quote.pcrs -g sha256
quoted: ff54434780180022000b3231360fe2abd45d9825cc2ce5df8541ab591b5dc205a2f4affc18b85b4be57a0003abc12300000000000092b7000000000000000001201910230016363600000001000b03008041002051cdfd15463a712da38c49e9390d861030e28cf1f19ebe9f5a8b6901a9df64fc
signature:
  alg: rsassa
  sig: 161d0ebf260b70572e81cdc947a84e1e85272319ebca6bc21d5042d20f2dade40a7019c6308d4621b6c11ac33acf33124f8b75309864bd91740984e429ed3be9fa3b9fc917e7b4e9c9804ab18e3a43ff816bb3d736d105a2cbe026e802cd3f73961ffdea02cf95f279034ca5fe263753a15a1237767722cb26847736417c01f0c8b3e95b128664c38f953c8f598715b5d5b823e8aaa42c7db28f826d917f030d0cb3fe98243c08ef15248c997c3b0408a7ec2eb556c3b7ad36b2bf45f2bef62c1a25a11daef5863fbd6799413febcc4766245943b612a65ad22b0e3540c493a1b3899fac3809ccd948e032099ea02c44561945d9a3e4fa7779764cf0b699b443
pcrs:
  sha256:
    15: 0x0000000000000000000000000000000000000000000000000000000000000000
    16: 0x0000000000000000000000000000000000000000000000000000000000000000
    22: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
calcDigest: 51cdfd15463a712da38c49e9390d861030e28cf1f19ebe9f5a8b6901a9df64fc

# tpm2_checkquote -u akpub.pem -m quote.msg -s quote.sig -f quote.pcrs -g sha256 -q abc123
ERROR: Malformed PCR file, pcr count cannot be greater than 32, got: 2095863776099172353 
ERROR: Unable to run tpm2_checkquote
```

Incidentally, I found a similar comment here: https://github.com/keylime/rust-keylime/issues/194

I played a bit with `export TSS2_LOG=all+DEBUG` and I can see that is using the `tcti-abrmd` service.

**Comment by aplanas** [comment]
Without abrmd I see the same error (`systemctl stop tpm2-abrmd.service`, `export TPM2TOOLS_TCTI="device:/dev/tpm0"`)

**Comment by williamcroberts** [comment]
@idesai ? Endian issue?

**Comment by aplanas** [comment]
After further debugging I cannot reproduce it in the upstream code (tested both in master and 5.1 tag). The bug is present in downstream package (openSUSE). There must be some compilation option or library that is causing the problem. Still no idea.

Closing here, and thanks!

**Comment by williamcroberts** [comment]
> After further debugging I cannot reproduce it in the upstream code (tested both in master and 5.1 tag). The bug is present in downstream package (openSUSE). There must be some compilation option or library that is causing the problem. Still no idea.
> 
> Closing here, and thanks!

If you ever figure it out, please come back and update this for others :-p Godspeed

**Comment by aplanas** [comment]
I found the cause, but I am not sure how this affect this project. We (openSUSE) use a build system named OBS, and we compile it with `-flto=auto`. Seems that this optimization with gcc 11.1.1 cause this problem in the `tpm2 checkquote`. I tested also to generate the quote with the invalid binary, and this can be validated with a valid one.

Do makes sense to reopen the issue here?

**Comment by williamcroberts** [comment]
Yes, we can just reopen this and look into what causes the issue perhaps.

**Comment by aplanas** [comment]
@marxin debugged the issue, and the fix can be found here: https://github.com/tpm2-software/tpm2-tools/pull/2774
