### ISSUE TITLE
tpm2_eventlog: ERROR: Unable to run tpm2_eventlog

### ISSUE THREAD

**Issue by aplanas** [tpm2-software/tpm2-tools#2775]
I am having this error under recent kernels (5.12.9 and 5.12.10) and in different distributions (openSUSE Tumbleweed and Fedora 34 Server). Also I can reproduce it from 5.1 and master:

```
-- openSUSE Tumbleweed
# tpm2_eventlog -v
tool="tpm2_eventlog" version="5.1" tctis="libtss2-tctildr" tcti-default=tcti-abrmd

# uname -a
Linux dhcp189 5.12.9-1-default #1 SMP Thu Jun 3 07:44:58 UTC 2021 (f17eb01) x86_64 x86_64 x86_64 GNU/Linux

-- Fedora 34 (Server Edition)
# tpm2_eventlog -v
tool="tpm2_eventlog" version="5.1" tctis="libtss2-tctildr" tcti-default=tcti-abrmd

# uname -a
Linux fedora 5.12.10-300.fc34.x86_64 #1 SMP Thu Jun 10 14:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Doing strace seems that could be a problem in fseek. According to the bug created for the openSUSE project (https://bugzilla.suse.com/show_bug.cgi?id=1187360#c2) fseek is used to identify the size of the file, and this should not work with securefs.

```
# strace tpm2_eventlog /sys/kernel/security/tpm0/binary_bios_measurements
...
futex(0x7fba8bafbe18, FUTEX_WAKE_PRIVATE, 2147483647) = 0
openat(AT_FDCWD, "/sys/kernel/security/tpm0/binary_bios_measurements", O_RDONLY) = 3
lseek(3, 0, SEEK_CUR)                   = 0
newfstatat(3, "", {st_mode=S_IFREG|0440, st_size=0, ...}, AT_EMPTY_PATH) = 0
newfstatat(3, "", {st_mode=S_IFREG|0440, st_size=0, ...}, AT_EMPTY_PATH) = 0
lseek(3, 0, SEEK_SET)                   = 0
lseek(3, 0, SEEK_SET)                   = 0
close(3)                                = 0
write(2, "ERROR: ", 7ERROR: )                  = 7
write(2, "Unable to run eventlog", 22Unable to run eventlog)  = 22
write(2, "\n", 1
)                       = 1
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by aplanas** [comment]
This upstream change seems to be related with a similar issue (https://github.com/tpm2-software/tpm2-tools/issues/1975):

https://github.com/tpm2-software/tpm2-tools/commit/10b8344d320830af346557bfde9ffb8a918bbbd8#diff-7d4dddff4bada4641635ff8faf4b9e9cce2b949578f748dd8fe3b003a5ce7844

seems to address the issue, and was reverted here:

https://github.com/tpm2-software/tpm2-tools/commit/d043f2f4f09f2e04fe98c2b71139794ab18c125f#diff-7d4dddff4bada4641635ff8faf4b9e9cce2b949578f748dd8fe3b003a5ce7844

**Comment by aplanas** [comment]
What should be the correct approach here? (not a C developer)

- Allocate an initial buffer and read chunks / do realloc() until the EOF
- Assume some big size (1MB) an call a day

**Comment by williamcroberts** [comment]
We did approach 2 before, and it didn't work. So I guess just realloc until EOF.

**Comment by aplanas** [comment]
> We did approach 2 before, and it didn't work. So I guess just realloc until EOF.

Indeed. https://github.com/tpm2-software/tpm2-tools/pull/2776 is using the expected approach then

**Comment by williamcroberts** [comment]
@aplanas for a work around on older tools, can you just cp the file off of securityfs to somewhere else, use it and delete it?
