### ISSUE TITLE
Tool to go from PEM of pulic key to TPM2B_PUBLIC would be nice

### ISSUE THREAD

**Issue by nicowilliams** [tpm2-software/tpm2-tools#2779]
Google's cloud environment provides a REST API that returns the public key of the cloud instance's EK as a PEM blob.  When I try to `tpm2 loadexternal` it to eventually get the EKpub as a `TPM2B_PUBLIC`, it fails every time as long as I have the `restricted` attribute.  I don't understand why that would be:

```
$ tpm2 loadexternal -L nullpolicy -Grsa -a 'fixedtpm|fixedparent|sensitivedataorigin|adminwithpolicy|restricted|decrypt' -C n -u nek.pem -c nek-wrong.ctx
WARNING:esys:src/tss2-esys/api/Esys_LoadExternal.c:314:Esys_LoadExternal_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_LoadExternal.c:108:Esys_LoadExternal() Esys Finish ErrorCode (0x000002d6)
ERROR: Esys_LoadExternal(0x2D6) - tpm:parameter(2):unsupported symmetric algorithm or key size or not appropriate for instance
ERROR: Unable to run loadexternal
$ 
```

```
$ # This works, but the name is wrong because restricted is missing:
$ tpm2 loadexternal -L nullpolicy -Grsa -a 'fixedtpm|fixedparent|sensitivedataorigin|adminwithpolicy|decrypt' -C n -u nek.pem -c nek-wrong.ctx
name: 000bf3b2e878796925c719c050497c8eca618a32e74ba2d287af6af718e72fa24113
```

I've tried using `-G rsa2048:oeap:aes256cfb` to get around `unsupported symmetric algorithm or key size or not appropriate for instance`, but no dice:

```
$ tpm2 loadexternal -L nullpolicy -G rsa2048:oeap:aes256cfb -a 'fixedtpm|fixedparent|sensitivedataorigin|adminwithpolicy|restricted|decrypt' -C n -u nek.pem -c nek-wrong.ctx
ERROR: Unsupported key type, got: "rsa2048:oeap:aes256cfb"
ERROR: Unable to run loadexternal
$ 
```

And no variation of that succeeds.

**Comment by nicowilliams** [comment]
My workaround is to `loadexternal`, then `readpublic` to get the modulus, then convert that to binary and `dd` it over the last 256 bytes of a file that has a proper `TPM2B_PUBLIC` structure for an EKpub.

**Comment by nicowilliams** [comment]
Here's what you get from the [Google Shielded VM API](https://cloud.google.com/security/shielded-cloud/retrieving-endorsement-key):

```
encryptionKey:
  ekPub: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4ucWqhLjIkcEJyqc8KJM
    12345678abcdefghijklmnopqrstuvwxyz12345678abcdefghijklmnopqrstu
    oBSrm0swIu3x4LWR/Ebl5KA0EKe9YFGaS9Pguun1m6X8Ld2zAqmoIwnxDiOqxQEU
    mx2wxkjf0bbjxG5ZI1i3t/c/QzeaE2WWTlKdgnUDyxSloDBq63yywtoIrp1nbDLj
    X8qdBymixu8jXXp1iGwmEUltnEnx779JKTpKgKTEednri+NcfRmXHrnPCxfiPudQ
    4wIDAQAB
    -----END PUBLIC KEY-----
kind: compute#shieldedInstanceIdentity
signingKey:
  ekPub: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzQvcD+2LAnsXAgdsVYAc
    12345678abcdefghijklmnopqrstuvwxyz12345678abcdefghijklmnopqrstu
    V/7WHasUuGlkbqiDOuDWgb15FAn35PU64HGey67McZTUT9EvrkT/ryXi4kZgBtoM
    lQIDAQAB
    -----END PUBLIC KEY-----
```

**Comment by idesai** [comment]
You must import the key if you need restricted attribute set and then read the object's name.

**Comment by nicowilliams** [comment]
Not so.  The restricted attribute is just part of the structure in order to compute the key's cryptographic name.

**Comment by nicowilliams** [comment]
If the TPM is refusing to load it, what I'd say that `tpm2-tools` should have a program to take a public key and the desired attributes (and policy and auth value) and output the `TPM2B_PUBLIC` for it and its cryptographic name.

**Comment by nicowilliams** [comment]
The goal here is to load an EKpub by just its public key and then call `TPM2_MakeCredential()`.

**Comment by idesai** [comment]
I see there is a [provision](https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_makecredential.c#L335:#L346) for that in the makecredential tool.

**Comment by nicowilliams** [comment]
Exactly.  But I need that in `loadexternal` because not only will I call `makecredential`, but also I need the hash of the `TPM2B_PUBLIC` EKpub before I get even remotely close to calling `makecredential`.

To give you context, I'm implementing an off-line enrollment operation for an attestation protocol server.  The enrollment interface takes a device name (hostname here), and an EKpub, either as a `TPM2B_PUBLIC` or as a bare public key (in PEM form), and it creates an entry in a database.  The entry in the database is named after the hash of the EKpub, as it will be looked up by the same during attestation.

This is in [Safeboot.dev PR#125](https://github.com/osresearch/safeboot/pull/125), in [sbin/attest-enroll](https://github.com/nicowilliams/safeboot/blob/pxe-server/sbin/attest-enroll).

**Comment by nicowilliams** [comment]
I can make a PR if you like.

**Comment by williamcroberts** [comment]
Perhaps in tpm2 print, since that's become the non-TPM connected format conversion swiss army knife

**Comment by nicowilliams** [comment]
> Perhaps in tpm2 print

So... we do need pure-software, `none` TPM implementations of this (which then I agree belongs in `print`), and of `TPM2_Duplicate()` (which @osresearch contributed?) and of `TPM2_MakeCredential()` (which already exists.

But we also need real-TPM `TPM2_Duplicate()`, possibly to be called to duplicate to an EK, which the TPM needs to know about, and which therefore must have been loaded via `TPM2_LoadExternal()`.  So I think `loadexternal` needs to support this too.

**Comment by williamcroberts** [comment]
> But we also need real-TPM `TPM2_Duplicate()`, possibly to be called to duplicate to an EK, which the TPM needs to know about, and which therefore must have been loaded via `TPM2_LoadExternal()`. So I think `loadexternal` needs to support this too.

Previously it was mentioned that the:
> The goal here is to load an EKpub by just its public key and then call TPM2_MakeCredential().

IIUC, you can do that now with tpm2_loadexternal as it supports PEM input's, and the ability to set the various public field data that's missing from the PEM, like object attributes and policy.

**Comment by nicowilliams** [comment]
But no, I can't, because if I include the `restricted` attribute then it refuses.  Oh, well, maybe `TPM2_Duplicate()` doesn't mind if the EKpub we're duplicating to isn't restricted?

**Comment by williamcroberts** [comment]
> But no, I can't, because if I include the `restricted` attribute then it refuses.

So then what exactly does load external need to support? I can't change the TPM itself.

> Oh, well, maybe `TPM2_Duplicate()` doesn't mind if the EKpub we're duplicating to isn't restricted?

Parent keys must have the restricted attribute set

**Comment by nicowilliams** [comment]
I'm going to have to spend some time root causing this, then I'll get back to you about `loadexternal`.

**Comment by idesai** [comment]
@nicowilliams let me know if the PR #2780 worked for you.

**Comment by nicowilliams** [comment]
I'll try it soon.  Thanks for the quick fix!

**Comment by tomoveu** [comment]
@nicowilliams why do you need the restricted attribute on the public key?

MakeCredential performs pure cryptographic operations as such the key attributes should not matter.

There is no authorization to MakeCredential and no attributes check AFAIK.

**Comment by williamcroberts** [comment]
Is it name of the parent calculation?

**Comment by nicowilliams** [comment]
Indeed, I do not need it.  I thought I would need it, but I was wrong.
