### ISSUE TITLE
undefined symbol: Esys_TR_GetTpmHandle

### ISSUE THREAD

**Issue by deepakdc01** [tpm2-software/tpm2-tools#2784]
Installed the current version of Tpm2_tss, Tpm2_abrmd and Tpm2_tools per the installation guide on https://tpm2-tools.readthedocs.io/en/latest/INSTALL
After that all tpm2_ commands fail with this undefined symbol.

Environment: Ubuntu 20.04 LTE

**Comment by williamcroberts** [comment]
Are you sure you don't have multiple versions of tpm2-tss installed? Perhaps through the package manager? The function `Esys_TR_GetTpmHandle` was added in 2.4.0+ version of tpm2-tss, but ubuntu 20.04 (Focal) shows it's version https://packages.ubuntu.com/focal/libtss2-esys0. So I think you're hitting some issue there.

**Comment by deepakdc01** [comment]
It looks like I do. 
$ apt-file list libtss2-esys0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-esys.so.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-esys.so.0.0.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-mu.so.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-mu.so.0.0.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-rc.so.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-rc.so.0.0.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-sys.so.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-sys.so.0.0.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-tcti-device.so.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-tcti-device.so.0.0.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-tcti-mssim.so.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-tcti-mssim.so.0.0.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-tctildr.so.0
libtss2-esys0: /usr/lib/x86_64-linux-gnu/libtss2-tctildr.so.0.0.0
libtss2-esys0: /usr/share/doc/libtss2-esys0/changelog.Debian.gz
libtss2-esys0: /usr/share/doc/libtss2-esys0/copyright
libtss2-esys0: /usr/share/lintian/overrides/libtss2-esys0

**Comment by williamcroberts** [comment]
What does something like `tpm2_getrandom --version` report?

**Comment by deepakdc01** [comment]
# tpm2_getrandom --version
tool="tpm2_getrandom" version="5.1.1-54-ge6f50be2" tctis="libtss2-tctildr" tcti-default=tcti-device

**Comment by williamcroberts** [comment]
does something like `tpm2_getrandom --hex 4` output anything? When it exits, whats the error code (returned to the shell via $?).

Here is an example:
```bash
tpm2 getrandom --hex 4
d77885bfwcrobert@beowulf:~/workspace/tpm2-pkcs11$ echo $?
0
```
Note that getrandom doesn't put a newline so my prompt and the hex encoded random show up on the same line.

**Comment by deepakdc01** [comment]
deepakdc# tpm2 getrandom --hex 4
b97b688froot@deepakdc# echo $?
0

**Comment by deepakdc01** [comment]
@williamcroberts, does that mean the tool works well?

**Comment by williamcroberts** [comment]
> Looks like it. I uninstalled the version which came with Focal now but none of the commands report an output. Apologies, I do not have much idea of TPMs but just wanted to setup an environment to consume it like a key store.
> Am I missing something?

So I am responding and helping you trouble shoot that.

> @williamcroberts, does that mean the tool works well?

Yep! We confirmed the tools work. Massive changes to options and outputs were done from the pre-4.0 release and 4.0+ releases. We consider pre 4.0 tooling unstable. Since 4.0 we have kept backwards compat and outputs stable. The 5.0 release wasn't a truly breaking release depending on how the packager packages it[1].

So I think your tools are working, you can create a primary key and child key with the following commmands:
```bash
# Create a primary key
tpm2_createprimary -c primary.ctx

# create a load a child RSA 2048 key with a SHA256 name algorithm (default settings).
tpm2_create -C primary.ctx -u key.pub -r key.priv
tpm2_load -C primary.ctx -u key.pub -r key.priv -c key.ctx

# sign something with it
echo "my message" > message.dat

# this will default to an RSSA signature
tpm2_sign -c rsa.ctx -g sha256 -o sig.rssa message.dat
```

If you look in the manpages for sign you'll see examples for various things. You can get public keys in PEM format for verifying the signature if needed.

[1] the tools were moved to a busy box style commandlet style in 5.0. Thus tpm2_getrandom and tpm2 getrandom are the same things. But you won't get the old name tpm2_getrandom command unless you do a make install or the packager includes the symlinks IIUC.

**Comment by deepakdc01** [comment]
Thanks for the detailed explaination. While I built the 5.x version on my test machine running Ubuntu Focal, the production machines are running CentOS7. They can't change. I tried building the same 5.x source code on them and it failed miserably due to dependencies. Spent nearly nearly a day fixing the dependencies and but still the 'make' fails with tpm2-abrmd.
So I gave it up and yum installed a older version of the same -  3.0.4 version. Like you said, the commands and options are very different between the 5.x and 3.x versions.  This is my new challenge now.

If I get disk encryption keys sealed with TPM2 chip using the 3.x tool, I would consider my job done for the moment. Obviously, there are other posts on the internet but most of the commands they suggest won't work in 3.x. 

Can you tell me how I can seal a disk unlock key securely using 3.x tool? Would be of great help as I'm struggling with this for days now.

**Comment by idesai** [comment]
Please reference 3.X man pages https://github.com/tpm2-software/tpm2-tools/tree/3.X/man
