### ISSUE TITLE
tpm2-send fails with non-TPM error 

### ISSUE THREAD

**Issue by elliotmtx** [tpm2-software/tpm2-tools#2790]
I am using tpm2-cmd option and trying to run something like this "tpm2_getrandom --tcti="cmd:ssh localhost tpm2_send" --hex 32", but I get below error, I do not understand why it is throwing error, tpm2-cmd getting initialized but after that I see this issue 

`$ tpm2_getrandom --tcti="cmd:ssh localhost tpm2_send" --hex 32
sdp@localhost's password:
ERROR:tcti:src/tss2-tcti/tcti-cmd.c:511:tcti_cmd_receive() Read was not size of header, got 0 expected 10
ERROR:esys:src/tss2-esys/api/Esys_GetRandom.c:281:Esys_GetRandom_Finish() Received a non-TPM Error
ERROR:esys:src/tss2-esys/api/Esys_GetRandom.c:95:Esys_GetRandom() Esys Finish ErrorCode (0x000a0011)
ERROR: Esys_GetRandom(0xA0011) - tcti:Response is malformed
ERROR: Unable to run tpm2_getrandom`

**Comment by idesai** [comment]
Do you get the same response if you run the tpm2_getrandom directly with --tcti=dev:/dev/tpm0 or if you are running it with a simulator --tcti=mssim ?
