### ISSUE TITLE
Secure key storage with tpm2.0

### ISSUE THREAD

**Issue by x-logic-iot** [tpm2-software/tpm2-tools#2793]
I can successfully store any key to a tpm non-volatile memory with following commands:

    sudo tpm2_createprimary -Q -C o -c prim.ctx
    dd if=/dev/urandom bs=1 count=32 status=none | sudo tpm2_create -Q -g sha256 -u seal.pub -r seal.priv -i- -C prim.ctx
    sudo tpm2_load -Q -C prim.ctx -u seal.pub -r seal.priv -n seal.name -c seal.ctx
    sudo tpm2_evictcontrol -C o -c seal.ctx 0x81010001

And successfully restore it with:

    sudo tpm2_unseal -Q -c 0x81010001

How can I securely store the key so not everyone could have access to it?

**Comment by williamcroberts** [comment]
The TPM is a global device, so you want to protect your object with a password and/or policy. This way even if someone has access to the object either on disk, or an object resident on the TPM they will not be able to use it.

For on disk storage, simply store it with the file system permissions you want to control access to the private and public blobs that get sent to the TPM in tpm2_load.
