### ISSUE TITLE
loading protected objects to TPM

### ISSUE THREAD

**Issue by herryin** [tpm2-software/tpm2-tools#2794]
Hi everyone,

I'm currently using tpm2-tool 5.1.1 and TSS 3.1.  I've successfully created a primary project named primary.ctx under the
endorsement hierarch with the command:

` sudo tpm2_createprimary -C e -g sha256 -G rsa -c primary.ctx`

and created a rsa key pair with:
`sudo tpm2_create -C e -g sha256 -G rsa -c primary.ctx -u primary.pub -r primary.priv`

I can also load the public part of RSA key into TPM:
` sudo tpm2_loadexternal -C n -u primary.pub -c rasencrypt_key.ctx`

But I got a error message with the command tpm2_load:
`sudo tpm2_load -C primary.ctx -u primary.pub -r primary.priv -n key.name -c rsadecrypt`

`ERROR:esys:src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x000001d5)
ERROR: Eys_Load(0x1D5) - tpm:parameter(1):structure is the wrong size
ERROR: Unable to run tpm2_load`

what does "structure is the wrong size" mean? Could anyone give me an idea to solve this problem? Thanks!

**Comment by idesai** [comment]
@herryin it is a little confusing what you are trying to achieve. Are you wanting to load the primary object or the secondary object?
```bash
tpm2_createprimary -C e -g sha256 -G rsa -c primary.ctx
tpm2_create -C primary.ctx -G rsa -u rsakey.pub -r rsakey.priv -c rsakey.ctx
#if you need to reload the rsakey object after a TPM restart etc.
tpm2_createprimary -C e -g sha256 -G rsa -c primary.ctx
tpm2_load -C primary.ctx -u rsakey.pub -r rsakey.priv -c rsakey.ctx
```
