### ISSUE TITLE
 Latest release is still marked as the old one

### ISSUE THREAD

**Issue by utkarsh2102** [tpm2-software/tpm2-tools#2798]
Hi @williamcroberts,

It looks like the latest release, 5.1.1, is not the official latest release in the releases page but an older one, 4.3.2. This is weird and I am not sure what's up. If you go to https://github.com/tpm2-software/tpm2-tools/releases/latest, you'll see what I am talking about.

Also, this:
![image](https://user-images.githubusercontent.com/31288318/126651199-191c83b4-c3ce-4fd2-bb4a-3061d8647963.png)

I am not sure if this was an overlook or what but this breaks a lot of automated script to find a newer version using the GitHub API. Here's how we use it:

```
$ curl -s https://api.github.com/repos/{$BRANCH}/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'
4.3.2
```

Here, `$BRANCH` is obviously `tpm2-software/tpm2-tools`. Can you take a look and maybe fix this? Thank you!

**Comment by williamcroberts** [comment]
This isn't anything I can fix. Latest doesn't mean highest tag, it means most recently tagged item, see:
  - https://stackoverflow.com/questions/22822586/swap-latest-release-on-github

Something like this will get you more of you want:
```bash
curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/tpm2-software/tpm2-tools/releases 2>/dev/null | grep tag_name | grep -v 'rc[0-9]' | cut -d":" -f2- | sed -E s/'[ ",]'//g | sort | tail -n 1 
```
Also is that URL you use with `${BRANCH}` the right URL, i see it in the docs differently:
  - https://docs.github.com/en/rest/reference/repos#get-the-latest-release
