### ISSUE TITLE
how to clear the authorization in platform hierarchy?

### ISSUE THREAD

**Issue by penpendandan** [tpm2-software/tpm2-tools#2804]
In addition to restarting the tpm device, is there any tpm2-tools command to clear the authorization in platform hierarchy?

**Comment by idesai** [comment]
Typically platform hierarchy authvalue is set to a large random value and policy is set such that it cannot be satisfied. This makes it difficult on a real platform to change the platform-hierarchy auth. In case, you can get access the hierarchy auth or policy, you can use the [tpm2_changeauth](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_changeauth.1.md) tool.
