### ISSUE TITLE
How do I test the TPM2_ECC_Decrypt/TPM2_ECC_Encrypt command

### ISSUE THREAD

**Issue by kktornado** [tpm2-software/tpm2-tools#2805]
I cannot find the test script for ECC encryption and decryption in the test/unit directory. How do I test the TPM2_ECC_Decrypt/TPM2_ECC_Encrypt command?

**Comment by idesai** [comment]
@kktornado did you try [creating](https://github.com/tpm2-software/tpm2-tools/blob/e6bfa8762af081f3c00ce4244c572a182178b211/test/integration/tests/create.sh#L29) a key and using it with [encryptdecrypt](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_encryptdecrypt.1.md) command?

**Comment by kktornado** [comment]
Encryptdecrypt. sh is used to test the symmetric encryption decryption algorithm. TPM2_ECC_Decrypt/TPM2_ECC_Encrypt is an asymmetric encryption decrypt algorithm, but I couldn't find a shell script to test these two commands

**Comment by idesai** [comment]
Ah I see. We are at spec 1.59 which doesn't support these commands. Support for these should come in future.
