### ISSUE TITLE
generate_partial_X509 fails as i2d_X509_bio cannot produce invalid data in OSSL >=3.0

### ISSUE THREAD

**Issue by gotthardp** [tpm2-software/tpm2-tools#2813]
The `tpm2_certifyX509certutil.c`:`generate_partial_X509()` creates a "partial" (in fact, an incomplete) certificate and stores that with `i2d_X509_bio`. The OpenSSL team decided that starting from 3.0 the *i2d should not create invalid encodings*. In other words, the encoding of a partial certificate will fail.
```
00429D20477F0000:error:068000DE:asn1 encoding routines:asn1_template_ex_i2d:illegal zero content::0:
00429D20477F0000:error:068C0100:asn1 encoding routines:ASN1_item_i2d_bio:malloc failure::0:
ERROR: i2d_X509_bio
ERROR: Unable to run certifyX509certutil
```
The change is originally motivated by https://github.com/openssl/openssl/issues/16026, implemented by https://github.com/openssl/openssl/pull/16036 and further discussed in https://github.com/openssl/openssl/issues/16257. The later even includes a suggestion to create a `TPM_PARTIAL_CERT` structure.

Please have a look at the proposal https://github.com/openssl/openssl/issues/16257#issuecomment-895448370. Is that a correct way to proceed?

**Comment by williamcroberts** [comment]
Yeah I have been following the mailing list for openssl more closely because poor Ken has been one of the first testing OSSL 3.0 against common TPM things... so I would imagine whatever Ken gets suggested to do by the community is the right thing to do.
