### ISSUE TITLE
Failed to instantiate TCTI

### ISSUE THREAD

**Issue by alishir** [tpm2-software/tpm2-tools#2834]
Hello everyone,

I compiled tpm2-tools 5.1.1 from source and exported `TPM2TOOLS_TCTI="device:/dev/tpm0"`, but when I execute `tpm2 getrandom 8` I got following error:

```
ERROR:tcti:src/tss2-tcti/tctildr.c:416:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI
ERROR: Could not load tcti, got: "device:/dev/tpm0"
```

The output of `cat /sys/class/tpm/tpm0/tpm_version_major` is `2`, and I'm using kernel 5.12.12.

**Comment by williamcroberts** [comment]
I wonder if it failed because it cannot find the library, does this work and if so whats the output?
```bash
pkg-config --libs tss2-tcti-device 
-L/usr/local/lib -ltss2-tcti-device
```
Did you copy and paste the whole error message? I don't have access to my /dev/tpm0 so it fails but the error message of why is before it:
```bash
export TPM2TOOLS_TCTI="device:/dev/tpm0"
tpm2 getrandom --hex 8
ERROR:tcti:src/tss2-tcti/tcti-device.c:442:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpm0: Permission denied 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: device 
ERROR:tcti:src/tss2-tcti/tctildr.c:428:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
ERROR: Could not load tcti, got: "device:/dev/tpm0"
```

**Comment by alishir** [comment]
Thanks a lot, the problem resolved by copying tss2-tcti-device library to the destination system. I've copied all required shared libraries that listed by `ldd`, but this library does not listed by `ldd`.
