### ISSUE TITLE
tpm2_print: invalid option -- 'f'

### ISSUE THREAD

**Issue by ernesto418** [tpm2-software/tpm2-tools#2840]
When I want to print a public key in PEM format I get 

```
tpm2_print: invalid option -- 'f'
```

To replicate the error:

```
tpm2_createprimary -c primary.ctx

tpm2_create -C primary.ctx -G ecc256 -u obj.pub -r obj.priv

tpm2_print -t TPM2B_PUBLIC -f pem obj.pub

```

Same error when following the guide of [tpm2_print](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_print.1.md).

**Comment by idesai** [comment]
@ernesto418 I saw that it works with version 5.2 and the current master. What version of tools have been installed on your system?

**Comment by ernesto418** [comment]
I was using e6bfa876 , but I recompiled and reinstalled and now is working properly,

I don't know what kind of error could it be.

Thanks for your support @idesai
