### ISSUE TITLE
How to use tss2_exportkey to restore the key?

### ISSUE THREAD

**Issue by lsxkugoug** [tpm2-software/tpm2-tools#2858]
Excuse me, I meet an interesting question for my project.
My professor assumes that the attackers can delete the key of tss. So how to restore it?
If it is in tpm_tool, you can retain the original key ctx. If the attacker delete it, you can reload it by its' parent(for example SRK).

So does tss command can do that?
tss2_exportkey, how can I use it to export the key pair? and how can I reload it by the primary object(for example SRK object)？

**Comment by AlexVIM1** [comment]
The main feature of TPM is an impossibility of exporting or viewing secret keys. Idk, just my guessworks
