### ISSUE TITLE
ERROR: Tss2_Sys_NV_Write(0x99D) - tpm:session(1):a policy check failed

### ISSUE THREAD

**Issue by wfive** [tpm2-software/tpm2-tools#2870]
I created an NV by：
tpm2_startauthsession -S session.ctx
tpm2_policycommandcode -S session.ctx -L policy.dat TPM2_CC_NV_UndefineSpaceSpecial
tpm2_nvdefine 0x01C10103 -a 0x42040408 -L policy.dat

 **attributes:
    friendly: policywrite|policydelete|authread|no_da|platformcreate
    value: 0x8040442**
this NV is set policydelete；

But there was an error when I writing NV by：

root@localhost:~# tpm2_nvwrite 0x01C10103 -i ~/NewPlatform.pol -P session:session.ctx
WARNING:esys:src/tss2-esys/api/Esys_NV_Write.c:310:Esys_NV_Write_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_Write.c:110:Esys_NV_Write() Esys Finish ErrorCode (0x0000099d)
ERROR: Failed to write NV area at index 0x1C10103
ERROR: Tss2_Sys_NV_Write(0x99D) - tpm:session(1):a policy check failed
ERROR: Unable to run tpm2_nvwrite

**Comment by wfive** [comment]
and  run:
tpm2_startauthsession -S session.ctx
tpm2_policycommandcode -S session.ctx -L policy.delete TPM2_CC_NV_UndefineSpaceSpecial
tpm2_policyrestart -S session.ctx 
tpm2_policycommandcode -S session.ctx -L policy.write TPM2_CC_NV_Write
tpm2_policyrestart -S session.ctx 
tpm2_policyor -S session.ctx -L policy.nv sha256:policy.delete,policy.write
**tpm2_nvdefine -C p -s 70 -a 0x42040408 -L policy.nv  0x1500001**
tpm2_flushcontext session.ctx

If so, 0x1500001 will always be restrict  deleted and written?

**Comment by wfive** [comment]
I found out that I made a mistake,
My NV can’t be undefine may be because the policy.dat specified by -L is wrong，I used the last file authorized.policy
Is there a way to undefine this NV...

~# tpm2_startauthsession -S session.ctx -g sha256
~# tpm2_policycommandcode -S session.ctx -L **_policy.dat_** TPM2_CC_NV_UndefineSpaceSpecial
1d2dc485e177ddd0a40a344913ceeb420caa093c42587d2e1b132b157ccb5db0
~# tpm2_nvdefine 0x01C10103 -a 0x42040408 -L **_./authorized.policy_**  -s 70 -P C p
nv-index: 0x1c10103
~# tpm2_flushcontext s.ctxession.ctx

~# tpm2_nvreadpublic 0x1c10103
 0x1c10103:
   name: 000b97910fa6cfe0d5ebe48146987625c1a72d91025b74670f929f293cab37802767
   hash algorithm:
     friendly: sha256
     value: 0xB
   attributes:
     friendly: policywrite|policydelete|authread|no_da|platformcreate
     value: 0x8040442
   size: 70
   authorization policy: **9C743B8EEBED96DE19A2B727E5DCE17B60BFB5FA1CF0A569133A359DE7638951**

~# hexdump -C **authorized.policy**
**00000000  9c 74 3b 8e eb ed 96 de  19 a2 b7 27 e5 dc e1 7b  |.t;........'...{|
00000010  60 bf b5 fa 1c f0 a5 69  13 3a 35 9d e7 63 89 51  |`......i.:5..c.Q|
00000020**

**Comment by idesai** [comment]
@wfive how was the authorization policy: 9C743B8EEBED96DE19A2B727E5DCE17B60BFB5FA1CF0A569133A359DE7638951 calculated?

**Comment by wfive** [comment]
It's calculated this way:
~# openssl genrsa -out signing_key_private.pem 2048
~# openssl rsa -in signing_key_private.pem -out signing_key_public.pem -pubout
~# tpm2_loadexternal -G rsa -C o -u signing_key_public.pem -c signing_key.ctx -n signing_key.name
name: 000b5e8d0c5636b3fafaa96ff7c91bd4e925a8f87bff58c6fe523ae6989d7c7ab8d3
~# tpm2_policyauthorize -S session.ctx -L authorized.policy -n signing_key.name
**9c743b8eebed96de19a2b727e5dce17b60bfb5fa1cf0a569133a359de7638951**

**Comment by wfive** [comment]
I create a policy.nv by this way
`tpm2_startauthsession -S session.ctx
tpm2_policycommandcode -S session.ctx -L policy.delete TPM2_CC_NV_UndefineSpaceSpecial
tpm2_policyrestart -S session.ctx 
tpm2_policycommandcode -S session.ctx -L policy.write TPM2_CC_NV_Write
tpm2_policyrestart -S session.ctx 
tpm2_policyor -S session.ctx -L policy.nv sha256:policy.delete,policy.write
tpm2_flushcontext session.ctx`

and define a nv by this policy.nv
`tpm2_startauthsession -S session.ctx
tpm2_policycommandcode -S session.ctx -L policy.delete TPM2_CC_NV_UndefineSpaceSpecial
tpm2_policyrestart -S session.ctx 
tpm2_policyor -S session.ctx -L policy.nv sha256:policy.delete,policy.write
tpm2_nvdefine -C p -s 70 -a 0x42040408 -L policy.nv 0x1500001
tpm2_flushcontext session.ctx`

final I want to undefine this nv, by
`tpm2_startauthsession -S session.ctx
tpm2_policycommandcode -S session.ctx -L policy.delete TPM2_CC_NV_UndefineSpaceSpecial
tpm2_policyrestart -S session.ctx 
tpm2_policyor -S session.ctx -L policy.nv sha256:policy.delete,policy.write
**tpm2_unnvdefine -S session.ctx 0x1500001**
tpm2_flushcontext session.ctx`

At tpm2_unnvdefine  got a 0x99D err  "a policy check failed".
I have authenticated it with TPM2 Policyor,Why failed again😭😭

**Comment by idesai** [comment]
> I create a policy.nv by this way
> 
> """ _tpm2_startauthsession -S session.ctx tpm2_policycommandcode -S session.ctx -L policy.delete TPM2_CC_NV_UndefineSpaceSpecial tpm2_policyrestart -S session.ctx tpm2_policycommandcode -S session.ctx -L policy.write TPM2_CC_NV_Write tpm2_policyrestart -S session.ctx tpm2_policyor -S session.ctx -L policy.nv sha256:policy.delete,policy.write tpm2_flushcontext session.ctx_ """
> 
> and define a nv by this policy.nv """ _tpm2_startauthsession -S session.ctx tpm2_policycommandcode -S session.ctx -L policy.delete TPM2_CC_NV_UndefineSpaceSpecial tpm2_policyrestart -S session.ctx tpm2_policyor -S session.ctx -L policy.nv sha256:policy.delete,policy.write tpm2_nvdefine -C p -s 70 -a 0x42040408 -L policy.nv 0x1500001 tpm2_flushcontext session.ctx_ """
> 
> final I want to undefine this nv, by """ _tpm2_startauthsession -S session.ctx tpm2_policycommandcode -S session.ctx -L policy.delete TPM2_CC_NV_UndefineSpaceSpecial tpm2_policyrestart -S session.ctx tpm2_policyor -S session.ctx -L policy.nv sha256:policy.delete,policy.write **tpm2_unnvdefine -S session.ctx 0x1500001** tpm2_flushcontext session.ctx_ """
> 
> At tpm2_unnvdefine got a 0x99D err "a policy check failed". I have authenticated it with TPM2 Policyor,Why failed again😭😭

Based on your script above, I made some changes and found it to work.
```bash
# create policy
 tpm2_startauthsession -S session.ctx
 tpm2_policycommandcode -S session.ctx -L policy.delete TPM2_CC_NV_UndefineSpaceSpecial
 tpm2_policyrestart -S session.ctx
 tpm2_policycommandcode -S session.ctx -L policy.write TPM2_CC_NV_Write
 tpm2_policyrestart -S session.ctx
 tpm2_policyor -S session.ctx -L policy.nv sha256:policy.delete,policy.write
 tpm2_flushcontext session.ctx

# create nv index
 tpm2_nvdefine -C p -s 70 -a 0x42040408 -L policy.nv 0x1500001

# delete nvindex
 tpm2_startauthsession -S session.ctx --policy-session
 tpm2_policycommandcode TPM2_CC_NV_UndefineSpaceSpecial -S session.ctx 
 tpm2_policyor -S session.ctx sha256:policy.delete,policy.write
 tpm2_nvundefine 0x1500001 -S session.ctx 
 tpm2_flushcontext session.ctx 
```

**Comment by wfive** [comment]
Can I still undefine that NVRAM Index because of my error?

**Comment by wfive** [comment]
befor I do undefine, I make a tpm2_nvwrite, 
 ./wr-nv.sh 0x1000005 ~/tpm-work/fac-tboot/NewPlatform.pol ./password/zero.policy ./password/gohi.policy
index:0x1000005 size: auth_policy:
+ tpm2_startauthsession -S s.ctx --policy-session
+ tpm2_policycommandcode -S s.ctx -L policy-nv-wr.dat TPM2_CC_NV_Write
1c4f7107dcaf23ce00756448508558683104bd9e203e93749c227b451270438f
+ tpm2_policyrestart -S s.ctx
+ tpm2_policyor -S s.ctx -L policy-wr.nv sha256:./password/zero.policy,./password/gohi.policy
b77c56c9818974f7d62c25891d4cb8b18158b3bd31c1a3a1c8d424ee35f8ce55
+ tpm2_nvwrite 0x1000005 -i /root/tpm-work/fac-tboot/NewPlatform.pol -P session:s.ctx
+ tpm2_flushcontext s.ctx
root@localhost:~/gohi-ag#

after nvwrite ,do undefine got fail, 
root@localhost:~/gohi-ag# ./rm-nv.sh  0x1000005 ./password/zero.policy ./password/gohi.policy
0x1000005 ./password/zero.policy ./password/gohi.policy
+ tpm2_startauthsession -S s.ctx --policy-session
+ tpm2_policycommandcode -S s.ctx -L policy-nv-rm.dat TPM2_CC_NV_UndefineSpaceSpecial
1d2dc485e177ddd0a40a344913ceeb420caa093c42587d2e1b132b157ccb5db0
+ tpm2_policyrestart -S s.ctx
+ tpm2_policyor -S s.ctx sha256:./password/zero.policy,./password/gohi.policy
b77c56c9818974f7d62c25891d4cb8b18158b3bd31c1a3a1c8d424ee35f8ce55
+ tpm2_nvundefine -S s.ctx 0x1000005
WARNING:esys:src/tss2-esys/api/Esys_NV_UndefineSpaceSpecial.c:315:Esys_NV_UndefineSpaceSpecial_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_UndefineSpaceSpecial.c:108:Esys_NV_UndefineSpaceSpecial() Esys Finish ErrorCode (0x0000099d)
ERROR: Failed to release NV area at index 0x1000005
ERROR: Esys_NV_UndefineSpaceSpecial(0x99D) - tpm:session(1):a policy check failed
ERROR: Unable to run tpm2_nvundefine
+ tpm2_flushcontext s.ctx

**Comment by wfive** [comment]
I think I got it,If NV_POLICYDELETE attribute is set and there is no authPolicy, or the authPolicy does not contain a branch that only allows the TPM2_NV_UndefineSpaceSpecial() command, then the index can never be deleted.
