### ISSUE TITLE
tpm2_nvread with PCR authorization fails

### ISSUE THREAD

**Issue by srwalter** [tpm2-software/tpm2-tools#2875]
Using tpm2-tools v5.2:

```
tpm2_createpolicy --policy-pcr -l sha1:0 -L policy.digest
tpm2_nvdefine -L policy.digest -a 'policyread|authwrite' 0x1000000
echo foo > foo
tpm2_nvwrite -i foo 0x1000000
```

The above steps all work as I would expect.  However, I can't turn around and nvread:

```
$ tpm2_nvread -P pcr:sha1:0 0x1000000
WARN: Reading full size of the NV index
WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x0000099d) 
ERROR: Esys_NV_Read(0x99D) - tpm:session(1):a policy check failed
ERROR: Failed to read NVRAM area at index 0x1000000
ERROR: Unable to run tpm2_nvread
```

The value of PCR 0 has not changed throughout the entire operation according to tpm2_pcrread (nor would I expect it to)

**Comment by idesai** [comment]
@srwalter, can you try specifying the size you are trying to read?

**Comment by srwalter** [comment]
Interesting, I'm able to read if I use a sufficiently small size.  I made the test case more specific:

```
tpm2_createpolicy --policy-pcr -l sha1:0 -L policy.digest
tpm2_nvdefine -L policy.digest -a 'policyread|authwrite' 0x1000000 -s 1024
echo foo > foo
tpm2_nvwrite -i foo 0x1000000
```

If I read with -s 768 it succeeds, but any value larger than 768 fails:

```
$ tpm2_nvread -P pcr:sha1:0 0x1000000 -s 769
WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x0000099d) 
ERROR: Esys_NV_Read(0x99D) - tpm:session(1):a policy check failed
ERROR: Failed to read NVRAM area at index 0x1000000
ERROR: Unable to run tpm2_nvread
```

Does that make sense?  That doesn't make sense to me.

**Comment by idesai** [comment]
@srwalter can you share the output for
```bash
 tpm2_getcap properties-fixed | grep -i nv -A 1
```

**Comment by srwalter** [comment]
Okay this makes sense now :smile: 

```
$  tpm2_getcap properties-fixed | grep -i nv -A 1
TPM2_PT_NV_COUNTERS_MAX:
  raw: 0x8
TPM2_PT_NV_INDEX_MAX:
  raw: 0x680
--
TPM2_PT_NV_BUFFER_MAX:
  raw: 0x300

```

Should nvdefine default to using TPM2_PT_NV_BUFFER_MAX as the buffer size?

**Comment by idesai** [comment]
> Okay this makes sense now 😄
> 
> ```
> $  tpm2_getcap properties-fixed | grep -i nv -A 1
> TPM2_PT_NV_COUNTERS_MAX:
>   raw: 0x8
> TPM2_PT_NV_INDEX_MAX:
>   raw: 0x680
> --
> TPM2_PT_NV_BUFFER_MAX:
>   raw: 0x300
> ```
> 
> Should nvdefine default to using TPM2_PT_NV_BUFFER_MAX as the buffer size?

That would limit defining the nvindex size to 768 bytes where as you could very well define it to be 1664 bytes

**Comment by srwalter** [comment]
Understood, thanks for the clarification!

**Comment by idesai** [comment]
> > Okay this makes sense now 😄
> > ```
> > $  tpm2_getcap properties-fixed | grep -i nv -A 1
> > TPM2_PT_NV_COUNTERS_MAX:
> >   raw: 0x8
> > TPM2_PT_NV_INDEX_MAX:
> >   raw: 0x680
> > --
> > TPM2_PT_NV_BUFFER_MAX:
> >   raw: 0x300
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Should nvdefine default to using TPM2_PT_NV_BUFFER_MAX as the buffer size?
> 
> That would limit defining the nvindex size to 768 bytes where as you could very well define it to be 1664 bytes

What is weird to me though is the error message from the TPM. Why a policy-check-fail?

**Comment by srwalter** [comment]
Yes, that also seemed odd to me.  Something like RC_SIZE would seem to make more sense

**Comment by idesai** [comment]
The problem is with the second iteration when the auth comes from a policy session. The policy session will have to be re-instantiated for the second iteration.

**Comment by williamcroberts** [comment]
Interesting, so you need a new session for N > 1 nvreads, because session's can only be used once for auth and then are invalidated?

**Comment by idesai** [comment]
> Interesting, so you need a new session for N > 1 nvreads, because session's can only be used once for auth and then are invalidated?

correct

**Comment by williamcroberts** [comment]
> > Interesting, so you need a new session for N > 1 nvreads, because session's can only be used once for auth and then are invalidated?
> 
> correct

Darn, that makes NV Reads intelligence limited here. Could we detect a policy session is present and then issue an error on the second loop and tell them to/how-to re-run the command with the offset and size?

**Comment by idesai** [comment]
> > > Interesting, so you need a new session for N > 1 nvreads, because session's can only be used once for auth and then are invalidated?
> > 
> > 
> > correct
> 
> Darn, that makes NV Reads intelligence limited here. Could we detect a policy session is present and then issue an error on the second loop and tell them to/how-to re-run the command with the offset and size?

Trying to keep it consistent with nvwrite and not allowing partial read/ writes so the end user is reminded to reconstruct the policy digest identically. This is what I have for the error message:
```C
        LOG_ERR("Cannot continue as the policy auth session must be "
                "reinstantiated for multiple iterations of NV read. "
                "Specify a max read size of TPM2_PT_NV_BUFFER_MAX or specify "
                "an offset and max read size of TPM2_PT_NV_BUFFER_MAX");
```

**Comment by williamcroberts** [comment]
SGTM
