### ISSUE TITLE
the way to prove the data is generated by tpm

### ISSUE THREAD

**Issue by lsxkugoug** [tpm2-software/tpm2-tools#2876]
Helle, every friend!
  I meet a problem. And I need some help orz. Thenk you! I want to get the counter value of tpm and then want to prove the value is generated by the tpm. 

  The model is that, we assume the attacker can use tpm to sign the anything. In this case, the attacker can create a file, for example "000000001" to pretend the counter value, and use tpm sign it. So use tpm2_sign can't implement it.

  Does any way to sign the data in the tpm? I mean, the key only can sign the data which is in the tpm. In this case, we can use the special key's public key to verify the signature and know it exactly generated by tpm.

Expect any response.
Thank you!

**Comment by lsxkugoug** [comment]
From the "A practical guide to TPM2.0", I see "A restricted signing key can only sign a digest produced by the TPM. This is a generalization of the TPM 1.2 Info keys and attestation identity key (AIKs), which could only sign a TPM internally created structure. For internal TPM data, this assurance is easy, because the TPM created the digest from its internal data at signing time."

So can I use AIK to sign the hash of counter value?

**Comment by idesai** [comment]
You can use [TPM2_CC_NV_Certify](https://tpm2-tools.readthedocs.io/en/latest/man/tpm2_nvcertify.1/)
