### ISSUE TITLE
Unable to run tpm2_policyauthorizenv

### ISSUE THREAD

**Issue by mgmillsa** [tpm2-software/tpm2-tools#2877]
I am following the tpm2_policyauthorizenv example at: [tpm2-tools/man/tpm2_policyauthorizenv.1.md](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_policyauthorizenv.1.md), and I get the error below. I have tpm2-tools v4.1.1-1 installed on Ubuntu 20.04. I have run several other examples without issue, but this one fails. I have tried on a couple machines and I get the same error.

```
WARNING:esys:src/tss2-esys/api/Esys_PolicyAuthorizeNV.c:307:Esys_PolicyAuthorizeNV_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_PolicyAuthorizeNV.c:104:Esys_PolicyAuthorizeNV() Esys Finish ErrorCode (0x000b0143)
ERROR: Esys_PolicyAuthorizeNV(0xB0143) - rmt:error(2.0): command code not supported
ERROR: Unable to run tpm2_policyauthorizenv
```

**Comment by idesai** [comment]
@mgmillsa can you check if the command is supported on your TPM?
```bash
tpm2_getcap commands| grep 192
```
Note command code for TPM2_CC_PolicyAuthorizeNV is 0x192

**Comment by idesai** [comment]
@mgmillsa can you check if the command is supported on your TPM?
```bash
tpm2_getcap commands| grep 192
```
Note command code for TPM2_CC_PolicyAuthorizeNV is 0x192

**Comment by mgmillsa** [comment]
@idesai I do not get any output from the above command, and I searched for the text as well.

**Comment by idesai** [comment]
@mgmillsa, as we figured the particular tpm doesn't support the command.
