### ISSUE TITLE
Enable debug not working

### ISSUE THREAD

**Issue by fer9898** [tpm2-software/tpm2-tools#2887]
Hello,

I would like to enable debug in order to display this log trace: https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-esys/api/Esys_StartAuthSession.c#L190

I already had `tpm2-tools` installed, so I recompiled the library and the tools:

`tpm2-tss:`
```
make clean
./bootstrap
./configure --with-maxloglevel=trace --enable-debug=yes
make -j5
sudo make install
```

`tpm2-tools:`
```
make clean
./bootstrap
./configure --enable-debug=yes
make -j5
sudo make install
```

After that, I ran this tpm2-tools command:
```shell
$ tpm2_startauthsession -S session.ctx -V
** Some not important INFO log **
$ tpm2_getrandom 5 -v
tool="tpm2_getrandom" version="5.2-54-ge4f5e2fc" tctis="libtss2-tctildr" tcti-default=tcti-device
```

But it's not working, I got no TRACE log, how can I solve this ?

Greetings.

**Comment by idesai** [comment]
export TSS2_LOG=all+trace

**Comment by fer9898** [comment]
Thank you @idesai, do you know if this is documented somewhere ? Aswell as all other environnement variable like `TPM2TOOLS_TCTI` for example.

**Comment by idesai** [comment]
They are in the man pages. You can also see them [here](https://tpm2-tools.readthedocs.io/en/latest/man/common/tcti/) and [here](https://tpm2-tss.readthedocs.io/en/latest/md_doc_logging.html).

**Comment by qizhangz** [comment]
Hi,

With "export TSS2_LOG=all+trace", I still can't see the strace of tpm2-tss.

Is there any additional set up?

**Comment by williamcroberts** [comment]
> Hi,
> 
> With "export TSS2_LOG=all+trace", I still can't see the strace of tpm2-tss.
> 

this will only output a bunch of logs for the tpm2-tss project libraries (like tss2-esys). It will not cause additional output from the tools code itself. You won't get an strace, you'll get the function traces from explicit logging code in the libraries.

> Is there any additional set up?

Their shouldn't be assuming that the env variable was set in the environment you're running in and was set prior to execution of a tpm2-tool.
