### ISSUE TITLE
How to have different Auth values for reading and writing to NV Index -TPM2-Tools

### ISSUE THREAD

**Issue by stickybits123** [tpm2-software/tpm2-tools#2888]
I am trying to have different authorization values for reading and writing to the TPM 2.0's NV Index. **The Owner password cannot be one of the values.** 

I have tried different attributes, such as the obvious: tpm2_nvdefine 1 -s 32 -a "policyread | authwrite" -p write_passwd -L secret.policy

I've also used sessions in place of policies, but I cannot get it to work. I have been able to successfully have different auth values for reading and writing but the owner password was one of the values. I was able to get it to be write-once with the tpm2_policycommandcode and tpm2_nvwritten, but we need the ability to write to the index more than once, since we will be rolling over the key from time to time. so this will not work either. 

by all accounts, I should be able to configure the NV Index to have different auth values for reading and writing that do not include the owner password. Ch. 14 of "A Practical Guide to TPM 2.0" describes situations where a policy can be used to write to the index, but an index-specific password is used for reading. how is this done specifically with the tpm2_tools? also, part 2 of the TCG TPM table 214 lists the different NV index attributes that the user can set.

I appreciate all the help I can get.

**Comment by idesai** [comment]
Authpolicy = (PolicySecret=AuthObject && PolicyCommandCode=NVwrite) || (PolicyAuthValue && PolicyCommandCode=NVRead)

Here AuthObject is any transient-object whose sole purpose is to provide an authvalue.

**Comment by stickybits123** [comment]
thank you very much. Could you express this in a series of commands? My understanding is not so great as to immediately apply what you've told me. here is what I take from your comment:

I need to use tpm2_policysecret with the name of the NV index, something like 0x1000001. This what I am tying the authorization of the index to the object in the index. is this correct? So, something like:

tpm2_startauthsession -S session.ctx

tpm2_policysecret -c 0x1000001 -S session.ctx -L secretpolicy

but this fails with "handles is not correct for use"

so I try:

tpm2_nvdefine 1 -s 32 -a "authwrite|policyread" -p 123

tpm2_startauthsession --policy-session -S session.dat

tpm2_policycommandcode -S session.dat TPM2_CC_NV_Read

tpm2_policysecret -c 0x1000001 -S session.dat -L secretpolicy

and this also fails. error is: authvalue or authpolicy is not available for selected entity. i really do appreciate your help. will you please show me how this is done with the CLI?

**Comment by stickybits123** [comment]
In order to replace the key inside the TPM NVRAM, we would obviously use the write credential. What I am not sure of is how to change the read credential? if the read credential is compromised, how is the read privileges changed? do we likewise use the write credential to change the read credential? again, i want to keep the TPM Owner Password out of this.

**Comment by idesai** [comment]
```bash
# Create read password
tpm2_nvdefine -s 0 -C o -p nvreadpass 1 -a "authread|authwrite"
tpm2_startauthsession -S session.ctx
tpm2_policysecret -S session.ctx -c 0x1000001 nvreadpass -L read.policy
tpm2_flushcontext session.ctx

# Define NV Index
tpm2_nvdefine -C o -p nvwritepass -a "authwrite|policyread" -L read.policy -s 10

# Write using nvwritepass
echo "test" | tpm2_nvwrite 0 -i- -P nvwritepass

# Read using nvreadpass
tpm2_startauthsession -S session.ctx --policy-session
tpm2_policysecret -S session.ctx -c 0x1000001 nvreadpass
tpm2_nvread 0 -P session:session.ctx
tpm2_flushcontext session.ctx 
```

**Comment by idesai** [comment]
@stickybits123 can we close this?

**Comment by stickybits123** [comment]
please do. Thank you very much. You are very helpful.
