### ISSUE TITLE
tpm2_pcrevent - Improve handling of procfs (0 byte) files

### ISSUE THREAD

**Issue by PhilippHomann** [tpm2-software/tpm2-tools#2895]
Hey there,

I've added a small script to my initramfs to read `/proc/cmdline` and hash it to tpm.
After some playing around I've noticed that `tpm2_pcrevent` is not reading the contents of `/proc/cmdline` if provided as argument (`tpm2_pcrevent /proc/cmdline`).
Looking at the code shows that the file size is determined (which is 0 in case of procfs) and due to that no data is read at all.
To workaround that you have to pipe data proc `/proc/cmdline` to `tpm2_pcrevent` (`cat /proc/cmdline | tpm2_pcrevent`) or read data to a temporary file and let `tpm2_pcrevent` use this file for reading.

I don't think that this is very intuitional as this also produces a hash and not just a bunch of zeros.
So one (like me) wouldn't even recognize that something is not working as expected.

**Comment by williamcroberts** [comment]
I guess we should read to EOF and if size get's too big or size is 0, fail.

**Comment by idesai** [comment]
The maximum event size in octets is 1024. Despite getting a file size of zero, we could attempt to read a chunk of max event size assuming the fs is preventing reporting of file size. Question is do we do this across all tools doing file IO?
PS: Certainly for pcrevent as there is a use case as described in this issue.

**Comment by williamcroberts** [comment]
> The maximum event size in octets is 1024. Despite getting a file size of zero, we could attempt to read a chunk of max event size assuming the fs is preventing reporting of file size. 

We do that for <= 1024, if not we do a hash sequence/update/sequence complete

> Question is do we do this across all tools doing file IO? PS: Certainly for pcrevent as there is a use case as described in this issue.

Their's some wonkyness getting filesize from fseek based on fd type. So we probably want to drop fseek usage for that always just read as much as we can till EOF or buffer full.
