### ISSUE TITLE
PCR Event Log Not Accessible

### ISSUE THREAD

**Issue by stickybits123** [tpm2-software/tpm2-tools#2896]
We've been working with trying to review event logs from the TPM in case of one our systems not booting up. Is there any support from the TSS that will allow us to pull event logs from the TPM, check what PCR values were extended to each register and determine where the failure was? the systems we are interested in are air-gapped, so there is no remote attestation.

can we side-boot a different OS, and pull event logs of some sort?

**Comment by idesai** [comment]
**tpm2_eventlog** should parse the data. The eventlog should be here /sys/kernel/security/tpm0/binary_bios_measurements
