### ISSUE TITLE
Are objects in TPM NVRAM Stored Encrypted?

### ISSUE THREAD

**Issue by stickybits123** [tpm2-software/tpm2-tools#2897]
We are needing to explain to customers that the TPM 2.0 provides secure storage of sensitive items. I have not been able to find a definitive answer as to whether data stored in NVRAM indexes are stored encrypted. I would imagine that they are stored encrypted by the read credential you set when running TPM2_NVdefine. is this true?

**Comment by williamcroberts** [comment]
No data stored in NV index's is not protected with any encryption, at least in the simulator code.

**Comment by idesai** [comment]
That is correct.
If you are using Intel (R) PTT though, persistent TPM data is encrypted and integrity protected prior to offloading to the storage.

**Comment by stickybits123** [comment]
is there a way to encrypt the data that is stored in a NV index? I would have thought that the credential would serve as some sort of decryption key. This NV index needs to be separate from the owner heirarchy

**Comment by williamcroberts** [comment]
> is there a way to encrypt the data that is stored in a NV index?

Encrypt it before you write the data or use a persistent key. In general use of NV/Persistent objects is highly discouraged.

> I would have thought that the credential would serve as some sort of decryption key.

What credential are you referring to?

>This NV index needs to be separate from the owner heirarchy

What hierarchy are you going to select? TPM2_NVDefine requires a hierarchy.
