### ISSUE TITLE
Question: how to find out supported key size for AES CFB parameter encryption

### ISSUE THREAD

**Issue by wmjdgla** [tpm2-software/tpm2-tools#2908]
Encrypt/decrypt sessions allows parameters to be encrypted when in transit between the caller and the TPM. According to the [TCG PC Client Platform TPM Profile Specification for TPM 2.0 - Section 4.2 PC Client Algorithms](https://trustedcomputinggroup.org/wp-content/uploads/PC-Client-Specific-Platform-TPM-Profile-for-TPM-2p0-v1p05p_r14_pub.pdf#page=18), for AES, 128-bit keys are mandated, while 256-bit keys are mandated from version 1.03 of the specification (released in 2017) onwards. This means TPMs out there will have different supported keys sizes. Is there any way to query for this information?

I've tried `TPM2_GetCapability` with `TPM_CAP_ALGS`, but it only returns the supported algorithms without any key size information.
The properties returned by `TPM2_GetCapability` with `TPM_CAP_TPM_PROPERTIES` doesn't seem to have it either. The closest thing is the `TPM_PT_CONTEXT_SYM_SIZE` property which is the size of the key used for encryption of saved contexts.

**Comment by idesai** [comment]
Try [tpm2_testparms](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_testparms.1.md)

**Comment by wmjdgla** [comment]
Sweet, thanks!
