### ISSUE TITLE
tpm2_pcrevent on actual size 0 file

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#2915]
Looking at the code, it appears that an actual size 0 (ie `touch zero.dat`) file will cause tpm2_pcrevent to misbehave, can we test this and correct any issues? Also what happens when an event sequnce is started but not terminated?

**Comment by idesai** [comment]
When pcrevent is run on a zero sized file, internally the tool runs TPM2_HashSequenceStart followed by TPM2_SequenceUpdate and finally TPM2_SequenceComplete. As is expected for a zero sized buffer, no changes are recorded to the final result at hash sequence start and update.

What is interesting and rather inexplicable is that at EventSequenceComplete, a hash of one byte of zero is calculated by the TPM and then the PCR is extended with that hash.

As an example,
```bash
touch test.dat
tpm2_pcrevent 16 test.dat
tpm2_pcrread sha1:16
```
This renders PCR16 value as 0x31A2DC4C22F9C5444A41625D05F95898E055F750.
This value is essentially,
```bash
echo -ne "0" | xxd -r -p | openssl dgst -sha1 -binary 0.hash
echo -ne "0000000000000000000000000000000000000000" | xxd -r -p > current.pcr
cat current.pcr 0.hash | openssl dgst -sha1
(stdin)= 31a2dc4c22f9c5444a41625d05f95898e055f750
```

Is the TPM expected to do this?

**Comment by idesai** [comment]
This is the same behavior as ossl as can be seen [here](https://gist.github.com/idesai/9a18ec8a9fb38dd5c022de86259081b3).

**Comment by williamcroberts** [comment]
> This is the same behavior as ossl as can be seen [here](https://gist.github.com/idesai/9a18ec8a9fb38dd5c022de86259081b3).

Looking at this, it seems to be how the internal function operates:
  - https://qvault.io/cryptography/how-sha-2-works-step-by-step-sha-256/

You always end up with something...
