### ISSUE TITLE
Backwards compatibity issue with tpm2_startauthsession?

### ISSUE THREAD

**Issue by pwicks86** [tpm2-software/tpm2-tools#2925]
I've been following [this](https://www.intel.com/content/www/us/en/developer/articles/code-sample/secret-key-provisioning-in-c-using-ptt.html) intel code sample to setup tpm based encryption and I've run into an incompatibility with newer versions of tpm2-tools. In the code sample, they issue the following commands to start an integrity-protected trial session:

```
tpm2_createprimary --quiet "--key-context=${tmp_primary_ctx}"
tpm2_startauthsession --quiet "--key-context=${tmp_primary_ctx}" "--session=${tmp_session}"
```

This works just fine in 4.1.1, but when I try this in 5.2 I get an error telling me that "Trial sessions cannot be additionally used as encrypt/decrypt session". Is there a way to perform these same operations in 5.2+?

**Comment by williamcroberts** [comment]
I think that's to prevent the foot cannon that is mentioned in the spec, "A trial session cannot use encrypt or decrypt" and "When sessionType is TPM_SE_TRIAL, there is no benefit in using any other version of
TPM2_StartAuthSession() as a trial session is not allowed to be used for authorization. This means
that the sessionKey of the session will never be used so there is no point in having the TPM
generate it."

So while you may think you're getting an encrypted session, you never did. @idesai am I wrong?

**Comment by williamcroberts** [comment]
So for 5.0+ just do:
```bash
tpm2_startauthsession -S s.ctx
```
That will start a trial session. If you want encryption and integrity protection, I think you need to pass a second policy but I am not sure how far @idesai has made it with that support.

**Comment by idesai** [comment]
> I think that's to prevent the foot cannon that is mentioned in the spec, "A trial session cannot use encrypt or decrypt" and "When sessionType is TPM_SE_TRIAL, there is no benefit in using any other version of TPM2_StartAuthSession() as a trial session is not allowed to be used for authorization. This means that the sessionKey of the session will never be used so there is no point in having the TPM generate it."
> 
> So while you may think you're getting an encrypted session, you never did. @idesai am I wrong?

That's right.

**Comment by idesai** [comment]
> So for 5.0+ just do:
> 
> ```shell
> tpm2_startauthsession -S s.ctx
> ```
> 
> That will start a trial session. If you want encryption and integrity protection, I think you need to pass a second policy but I am not sure how far @idesai has made it with that support.

@pwicks86 currently you cannot do that. There is support for only a single session with startauthsession. This feature is being [tracked](https://github.com/tpm2-software/tpm2-tools/issues/2566).

**Comment by pwicks86** [comment]
Hmm, ok, I'm just trying to implement the system described in the code samples provided by Intel. Does this mean that fundamentally what I should be doing in `policy_sign.sh` is just 

```
tpm2_startauthsession --quiet  "--session=${tmp_session}"
```

rather than what I have above? And if I understand correctly, this will provide the same behavior as 4.x since that other parameter was actually unused? I guess the further question is does this change me that the security that I think I am getting from the system is compromised?

**Comment by williamcroberts** [comment]
> Hmm, ok, I'm just trying to implement the system described in the code samples provided by Intel. Does this mean that fundamentally what I should be doing in `policy_sign.sh` is just
> 
> ```
> tpm2_startauthsession --quiet  "--session=${tmp_session}"
> ```
> 
> rather than what I have above? 

Yes.

> And if I understand correctly, this will provide the same behavior as 4.x since that other parameter was actually unused?

Yes, but it's not that it was unused in the tools, it's just that the TPM and subordinate libraries don't generate a session key.

> I guess the further question is does this change me that the security that I think I am getting from the system is compromised?

This only affects trial sessions, which are for policy hash generation. For actual policy sessions, the encrypted session is in 
started. In reality, TPM's don't need a trial session, you can compute the hashes without going to the TPM. We're actually working on support in the tools so we don't have to hit the TPM to generate hashes.
