### ISSUE TITLE
Compile issue without efivar?

### ISSUE THREAD

**Issue by mirschkyn** [tpm2-software/tpm2-tools#2927]
EFIVAR is afaiu optional.
"checking for EFIVAR... no"

Yet without efivar, I get this build error:
lib/libcommon.a(libcommon_a-tpm2_eventlog_yaml.o): in function `yaml_devicepath':
tpm2-tools-5.2/lib/tpm2_eventlog_yaml.c:239: undefined reference to `efidp_format_device_path'

Problem seems to stem that headers are found but not relevant pkgconfig.
If "checking for EFIVAR" = no, shouldn't that stop the declaration of HAVE_EFIVAR_EFIVAR_H to true?

Ie, if any of the efivar tests fail, stop using efivar?

**Comment by idesai** [comment]
Discussed in #2918
