### ISSUE TITLE
How to run tpm2-tools test with physical TPM device rather than Simulator device

### ISSUE THREAD

**Issue by qiaozhanfeng** [tpm2-software/tpm2-tools#2941]
First enable TPM2.0 device in BIOS setup. then boot to os, after completed the configuration of tpm2-tss/tpm2-abrmd/tpm2-tools and fTPM simulator which followed  "https://tpm2-tools.readthedocs.io/en/latest/INSTALL/"，then run"make check" to execute tests in tpm2-tools directory，after finished test，record test result., then reboot to BIOS setup to disabled tpm2.0 device，then boot to OS run "make check" again，record test result，compared with the previous result, found the result is the same, so I guess the default is to use  Simulator device to test, so how can I run testing with physical TPM device? Looking forward to your help

**Comment by idesai** [comment]
@qiaozhanfeng we advise against running the integration tests directly on the TPM because the tests go through a series of programming and clearing hierarchy auths.

As for the second part of your question, if you are using the tools to program the physical TPM, you have to point the tools to the right tcti. If you are using the resource manager like tpm2-abrmd then point the tcti to device. Or if you directly working with the tpm then set an environment variable like this `export TPM2TOOLS_TCTI="device:/dev/tpm0"`

**Comment by qiaozhanfeng** [comment]
@idesai Thank you for your quick reply. I tried to run **export TPM2TOOLS_TCTI="device:/dev/tpm0"** in shell environment, then run **echo $TPM2TOOLS_TCTI** to check the result is successful, and then run make check again, but found the same results as before, then I tried to add **TPM2TOOLS_TEST_TCTI="device:/dev/tpm0"** in helpers.sh before line **"echo "TPM2TOOLS_TEST_TCTI=$TPM2TOOLS_TEST_TCTI""**, then make check again, but found that almost all the tests failed. The log of one of the tests is as follows:
*********************************************************
FAIL: test/integration/tests/abrmd_extended-sessions

creating simulator working dir: /tmp/tpm2_test_xKMrHS
/tmp/tpm2_test_xKMrHS ~/tpm2-tools-5.2
Switched to CWD: /tmp/tpm2_test_xKMrHS
Starting the simulator
Attempting to start simulator on port: 43255
LIBRARY_COMPATIBILITY_CHECK is ON
Manufacturing NV state...
Size of OBJECT = 2600
Size of components in TPMT_SENSITIVE = 1096
    TPMI_ALG_PUBLIC                 2
    TPM2B_AUTH                      66
    TPM2B_DIGEST                    66
    TPMU_SENSITIVE_COMPOSITE        962

Starting ACT thread...
TPM command server listening on port 43255
Platform server listening on port 43256
LISTEN    0         3                  0.0.0.0:43255            0.0.0.0:*        users:(("tpm_server",pid=219882,fd=4))                                         
LISTEN    0         3                  0.0.0.0:43256            0.0.0.0:*        users:(("tpm_server",pid=219882,fd=5))                                         
Started simulator on port 43255 in dir "/tmp/tpm2_test_xKMrHS"
tpm2tools_tcti="mssim:host=localhost,port=43255"
Started the simulator
Starting tpm2-abrmd
TPM2ABRMD_TCTI is empty, configuring
TPM2ABRMD_TCTI="--session --dbus-name=com.intel.tss2.Tabrmd43255 --tcti=mssim:port=43255"
tpm2-abrmd command: tpm2-abrmd --allow-root --session --dbus-name=com.intel.tss2.Tabrmd43255 --tcti=mssim:port=43255 --session --dbus-name=com.intel.tss2.Tabrmd43255 --tcti=mssim:port=43255

** (process:219900): WARNING **: 10:08:59.027: tcti_conf before: "(null)"

** (tpm2-abrmd:219900): WARNING **: 10:08:59.027: tcti_conf after: "mssim:port=43255"
Command IPv4 client accepted
Platform IPv4 client accepted
tpm2tools_tcti="tabrmd:bus_type=session,bus_name=com.intel.tss2.Tabrmd43255"
TPM2TOOLS_TEST_TCTI=device:/dev/tpm0
export TPM2TOOLS_TCTI="device:/dev/tpm0"

--- To recreate this test run the following: ---
#!/usr/bin/env bash
export TPM2_ABRMD="tpm2-abrmd"
export TPM2_SIM="tpm_server"
export TPM2ABRMD_TCTI="--session --dbus-name=com.intel.tss2.Tabrmd43255 --tcti=mssim:port=43255"
export TPM2_SIMPORT="43255"
export TPM2TOOLS_TEST_TCTI="device:/dev/tpm0"
export TPM2TOOLS_TEST_PERSISTENT=""
export PATH="/root/tpm2-tools-5.2/tools:/root/tpm2-tools-5.2/tools/misc:/root/tpm2-tools-5.2/test/integration:/root/tpm2-tools-5.2/tools/fapi:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
export srcdir="."
export abs_srcdir="/root/tpm2-tools-5.2"
export abs_builddir="/root/tpm2-tools-5.2"

/root/tpm2-tools-5.2/test/integration/tests/abrmd_extended-sessions.sh
--- EOF ---
run_startup: false
ERROR:tcti:src/tss2-tcti/tcti-device.c:442:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpm0: Device or resource busy 
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: device 
ERROR:tcti:src/tss2-tcti/tctildr.c:428:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
ERROR: Could not load tcti, got: "device:/dev/tpm0"
Shutting down
~/tpm2-tools-5.2
Removing sim dir: /tmp/tpm2_test_xKMrHS
/root/tpm2-tools-5.2/test/integration/helpers.sh: line 443: 219882 Killed                  "$TPM2_SIM" -port "$tpm2_sim_port"  (wd: /tmp/tpm2_test_xKMrHS)
/root/tpm2-tools-5.2/test/integration/helpers.sh: line 443: 219900 Killed                  $TPM2_ABRMD $tpm2_tabrmd_opts $TPM2ABRMD_TCTI  (wd: /tmp/tpm2_test_xKMrHS)
FAIL test/integration/tests/abrmd_extended-sessions.sh (exit status: 1)
*********************************************************
and the log of the other tests is the same. Is it possible that I did not set the TPM2TOOLS_TCTI environment variable in the right way，attached the full test log
[test-suite.log](https://github.com/tpm2-software/tpm2-tools/files/8076408/test-suite.log)

**Comment by idesai** [comment]
The resource manager is pointed to the sim `--tcti=mssim:port=43255"` and TPM2TOOLS_TEST_TCTI is pointed to /dev/tpm0
