### ISSUE TITLE
aminclude_static.am file missing - despite supposed resolution by issue 1291

### ISSUE THREAD

**Issue by Cyborg1138** [tpm2-software/tpm2-tools#2942]
https://github.com/tpm2-software/tpm2-tools/issues/1291

Using the  .zip or git clone of this repository,  experience the same issue detailed by the link above.

I can see the the changes detailed by the related links in 1291 are indeed what I am building with, yet I still get the error.

I am building on Centos 7.

Any ideas? I am not familiar with automake.

**Comment by williamcroberts** [comment]
You can't use the zip, you have to download a release tarball from the releases page or a git clone. The patch was included in the tools by patch 9901d6e59e. Do you have autoconf archive installed?

**Comment by Cyborg1138** [comment]
Well, I did try the zip and as I said also did a clone. Exactly the same issue with both.

The reason I am trying to build it is the rpm doesn't appear to contain all that we require. For instance, if you check out its contents, it doesn't contain tmp2_createek an other items for which there is source code in the repo. Nor do its contents match up with the documentation on how it should behave. But's that's another problem.

I have by-passed the issue by creating an empty aminclude_static.am, which I believe was the intention of the fix, but I think the issue is still there.

**Comment by Cyborg1138** [comment]
I believe this problem occurred as my m4 directory did not contain the required files.

**Comment by Cyborg1138** [comment]
Hi WIlliam,

Only just seen this, and no, I didn't have the autoconf tarball installed, and it was the reason for the issue, which is why I closed 1291.

Building it from the repo on centos 7 started to become a big task, so I aborted it. The only reason I was doing it was the yum install on centos 7 appears to be well behind the github repo.

For instance, there's no createek, and there appears to be lots of other missing stuff. As in this is all there is:

[cid:713a4f2a-6c16-48d9-b4d6-1060578a40cc]

Is there any plan to update the yum install for centos 7 or is it not maintained anymore?

Thanks.

Justin
________________________________

**Comment by williamcroberts** [comment]
We don't actually maintain the distro packages. What makes it so hard to build, minimum versions of some dependency?
________________________________
