### ISSUE TITLE
FAPI not provisioned?

### ISSUE THREAD

**Issue by rkgfk** [tpm2-software/tpm2-tools#2945]
Hi guys,
we are trying to setup ssh with the use of the TPM2 module under Fedora 35.
But it is not possible to get it to run due to provisioning errors?

That's what we get:
`WARNING:fapi:src/tss2-fapi/api/Fapi_List.c:226:Fapi_List_Finish() Profile of path not provisioned: /HS/SRK 
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:81:Fapi_List() ErrorCode (0x00060034) Entities_List 
WARNING: Listing FAPI token objects failed: "fapi:Provisioning was not executed."`

What am I doing wrong?
`tss2_provision` does not change anything.

**Comment by williamcroberts** [comment]
> Hi guys, we are trying to setup ssh with the use of the TPM2 module under Fedora 35. But it is not possible to get it to run due to provisioning errors?
> 
> That's what we get: `WARNING:fapi:src/tss2-fapi/api/Fapi_List.c:226:Fapi_List_Finish() Profile of path not provisioned: /HS/SRK ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:81:Fapi_List() ErrorCode (0x00060034) Entities_List WARNING: Listing FAPI token objects failed: "fapi:Provisioning was not executed."`
> 
> What am I doing wrong? `tss2_provision` does not change anything.

IIUC It should, if you don't want the FAPI features the easiest way is to just disable fapi: `./configure --without-fapi`

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT any insights here?

**Comment by rkgfk** [comment]
> IIUC It should, if you don't want the FAPI features the easiest way is to just disable fapi: `./configure --without-fapi`
Well, as the installation comes from the Fedora Repository, it's not easily possible to reconfigure it. Of course it could be built from source, but that's not what is supposed to work. It is just frustrating that it does not work as expected even following the instructions to set it up.
So there should be another solution than shutting down FAPI, right?

**Comment by AndreasFuchsSIT** [comment]
Could you show us the output of `tss2_provision` ?

**Comment by rkgfk** [comment]
Sure. The output is:
`[rk@fedora ~]$ tss2_provision 
ERROR:fapi:src/tss2-fapi/ifapi_io.c:50:ifapi_io_read_async() File "/etc/tpm2-tss/fapi-config.json" not found. 
ERROR:fapi:src/tss2-fapi/ifapi_config.c:152:ifapi_config_initialize_async() Could not read config file  ErrorCode (0x0006000a) 
ERROR:fapi:src/tss2-fapi/api/Fapi_Initialize.c:132:Fapi_Initialize_Async() Could not initialize FAPI context ErrorCode (0x0006000a) 
ERROR:fapi:src/tss2-fapi/api/Fapi_Initialize.c:70:Fapi_Initialize() FAPI Async call initialize ErrorCode (0x0006000a) 
Fapi_Initialize(0x6000A) - fapi:IO failure`

**Comment by AndreasFuchsSIT** [comment]
As it says, the file `/etc/tpm2-tss/fapi-config.json` is missing...
How did you install the tss ?

**Comment by rkgfk** [comment]
Oh yes. Sorry. That was the wrong error trace. It was installed via
`dnf install tpm2-tss`
The correct error trace is:
`[rk@fedora ~]$ tpm2_provision
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:520:Fapi_Provision_Finish() ErrorCode (0x0006000b) SRK persistent handle already defined 
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x0006000b) Provision 
Fapi_Provision(0x6000B) - fapi:A parameter has a bad value
`

**Comment by AndreasFuchsSIT** [comment]
Could you also tell me the version ?

So The thing is that there is already a key registered persistently inside the TPM at handle 0x81000001. The fapi config/profile say that fapi shall provision a key at said location.

You have a few options now:
- Remove this key and let fapi create one (might break existing stuff like tpm2-pkcs11)
- Change the config/profile to use a different handle (for the SRK)
- Use tpm2-tss 3.2 and change the config/profile such that the configured key type matches the key already registered, then fapi will just reuse the key.

**Comment by rkgfk** [comment]
Thx. I'll give it a try.

**Comment by frhun** [comment]
@AndreasFuchsTPM Could you please point me (and everyone else that desperately searches for a solution, and finds this) to some further resources that explain what the things you mentioned mean exactly, and how one could go about doing them?

**Comment by JuergenReppSIT** [comment]
> Could you please point me (and everyone else that desperately searches for a solution, and finds this) to some further resources that explain what the things you mentioned mean exactly, and how one could go about doing them?

* you could check the public info of the key stored at 0x81000001with `tpm2_readpublic -c 0x81000001`
* Delete the key with `tpm2_evictcontrol -C o -c 0x81000001` Now fapi provisioning should work also in older versions which do not check whether the existing persistent key is appropriate to the FAPI definition in the profile.
*  Aftwards you could check again the public date of this key. again with `tpm2_readpublic -c 0x81000001`
* If the public data is equal to the first `tpm2_readpublic` everything should be OK.
* If the public data of the key was changed you could delete the key again. Now with `tss2_delete -p /`and reconstruct the key with tpm2_createprimary with the parameters from the first `tpm2_readpublic` and executing `tpm2_evictcontrol` to make the key persistent.
* Now you could define another persistent handle e.g.  0x81000002 for the SRK key and execute the provisioning (For ecc e.g. in /usr/local/etc/tpm2-tss/fapi-profiles/P_ECCP256SHA256.json).
