### ISSUE TITLE
TPM2_createprimary not working with raw number

### ISSUE THREAD

**Issue by stickybits123** [tpm2-software/tpm2-tools#2954]
The man page for tpm2_createprimary states we can use a raw number to establish a primary object. when trying to establish a primary object for a NV index, we get error messages: NV-Index not supported by this command , persistent handles not supported by this command, implicit indexes not supported by this command.

the commands being run are essentially:

tpm2_createprimary -C 0x1000001 -c primary.ctx

we must store values inside nv memory encrypted. so the idea is to have the primary object perform the encryption/decryption whenever we pull the object from the TPM NVRAM index. is there a way to do this? and, what "raw numbers" are supported by this command?

**Comment by williamcroberts** [comment]
`-C` option is for the hierarchy, so you can use the raw numerics for the owner hierarchy `0x40000001`. If you want to persist the object you create it, and then pass the context output from tpm2_createprimry to tpm2_evictcontrol.

```bash
tpm2_createprimary -c primary.ctx
tpm2_evictcontrol -c primary.ctx
persistent-handle: 0x81000000
action: persisted
```
You can specify the address to persist the object at as an argument to tpm2_evictcontrol if you desire or it will look and use the first available slot.

> we must store values inside nv memory encrypted. so the idea is to have the primary object perform the encryption/decryption whenever we pull the object from the TPM NVRAM index. is there a way to do this? and, what "raw numbers" are supported by this command?

Why don't you just establish an encrypted session (prevents snooping)? Why do you have to store it encrypted in NV? If you store it encrypted in NV using a particular key to encrypt it, then you must use that key to decrypt it. An assymetric primary key is likely not the best bet. Which by the way, they are deterministic for a given TPM, so you don't need to persist the primary object, the same arguments to tpm2_createprimary yield the same key every time.
