### ISSUE TITLE
SAPI warning from makecredential 

### ISSUE THREAD

**Issue by osresearch** [tpm2-software/tpm2-tools#2961]
When using `tpm2 makecredential --tcti=none` there is always a warning and it does not appear possible to silence it:
```
WARN: Tool optionally uses SAPI. Continuing with tcti=none
```

Since this operation does not require a TPM, it seems like this warning is extraneous?

Added in https://github.com/tpm2-software/tpm2-tools/commit/f7cbbd0d4d81a771887966ffb59809fccf8ecca0

**Comment by idesai** [comment]
[Parsing](https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_tool.c#L234:#L243) flags.quiet before handling options could possibly resolve it. I will test it out.

**Comment by osresearch** [comment]
`--quiet` doesn't silence it in my build (5.2).  There is another warning for `-G` / `--key-algorithm`:
```
WARN: Tool optionally uses SAPI. Continuing with tcti=none
WARN: Because **-G** is specified, assuming input encryption public key is in PEM format.
```

**Comment by idesai** [comment]
@osresearch, please let me know if #2963 fixes the issue for you.

Thanks!
