### ISSUE TITLE
Installation version incorrect

### ISSUE THREAD

**Issue by kostamoisidis** [tpm2-software/tpm2-tools#2979]
Running `./configure` script of tpm2-tools right after installing tpm2-tss throws following.
```
configure: error: Package requirements (tss2-esys >= 2.4.0) were not met:

Requested 'tss2-esys >= 2.4.0' but version of tss2-esys is b66d7a5
You may find new versions of tss2-esys at https://github.com/tpm2-software/tpm2-tss

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables TSS2_ESYS_2_3_CFLAGS
and TSS2_ESYS_2_3_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
Where `b66d7a5` looks like the last commit [b66d7a5](https://github.com/tpm2-software/tpm2-tss/commit/b66d7a589be6d312b7d7cebf744d97e5ec2c6d8e)

**Comment by williamcroberts** [comment]
> Running `./configure` script of tpm2-tools right after installing tpm2-tss throws following.
> 
> ```
> configure: error: Package requirements (tss2-esys >= 2.4.0) were not met:
> 
> Requested 'tss2-esys >= 2.4.0' but version of tss2-esys is b66d7a5
> You may find new versions of tss2-esys at https://github.com/tpm2-software/tpm2-tss
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables TSS2_ESYS_2_3_CFLAGS
> and TSS2_ESYS_2_3_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.
> ```
> 
> Where `b66d7a5` looks like the last commit [b66d7a5](https://github.com/tpm2-software/tpm2-tss/commit/b66d7a589be6d312b7d7cebf744d97e5ec2c6d8e)

Did you install the tpm2-tss project with make install? What does `pkg-config --debug --modversion tss2-esys` output?

**Comment by kostamoisidis** [comment]
I followed [this](https://github.com/tpm2-software/tpm2-tss-engine/blob/master/INSTALL.md) INSTALL.md and to my surprise I have really frogoten to run the `sudo make install`. I ran the `make -j$(nproc)` twice ...
