### ISSUE TITLE
Update PCR values for PCRs 0-10?

### ISSUE THREAD

**Issue by dadiestfish2077** [tpm2-software/tpm2-tools#2983]
TPM2_pcrrest works for 23 and 16. But if an OS, BIOS, or bootloader update is required, how is it possible to alter the PCR values that are tied to these components? I suspect that a tpm2_wipe would be required, turn off measured boot, and then install the new BIOS or bootloader, and then reconfigure measured boot based on the new PCR values. is there a way to wipe the current state of PCR 8-10, for example, and then extend a new expected hash to the wiped PCRs? the use case is we may need to update the bootloader or BIOS in the future and we would like to know how that effects the measured boot process. in particular, we need to automate the updates to the PCRs that reside between 0-10.

**Comment by idesai** [comment]
23 and 16 are debug PCRs and so are resettable. The others are extended by different segments in the boot software. The TPM is entrusted to hold on to those PCR extensions by definition of its security properties. The only way to have them in a zero state on a real platform and a real TPM is to block out all the PCR extensions or turn off measured boot in boot software.
