### ISSUE TITLE
Best way to have AuthWrite and Anyone Read on NV Index

### ISSUE THREAD

**Issue by workmaryville** [tpm2-software/tpm2-tools#2984]
we are trying to have a public key stored in the TPM that  anyone can read, but only a special password can overwrite. the commands are: 

tpm2_nvdefine -C o -a "authwrite|ownerread" -p 246 -P OwnerPassword.
 &
tpm2_nvdefine 1 -s 32 -a "authwrite" -p 246

the top allows us to write to the TPM given authentication, but fails to read. we've also tried to include simply just "authwrite" but it fails as "inconsistent attributes." we need a password other than the owner password used to overwrite the value. But, we must have a blank password for reading. what is the proper way to do this?

**Comment by idesai** [comment]
"authwrite|policyread" where Policy is PolicyCommandCode = TPM2_CC_NVRead

**Comment by workmaryville** [comment]
@idesai thank you. 

So I am running:

tpm2_nvdefine -C o -a "authwrite|policyread" -p 246 -P ownerpass

tpm2_policycommandcode -L policy.dat TPM2_CC_NVRead

this fails with "could not convert command-code to number"

am i supposed to start an authsession and pass in my session to this command? when i do that it fails as well. 

how am I to pass in that policy to the index so anyone can read?

**Comment by williamcroberts** [comment]
I would flip it to authread and policywrite since read is likely more often than write, so make the hard path the least common and set the policy on some other object, thoughts @idesai ?

**Comment by idesai** [comment]
> I would flip it to authread and policywrite since read is likely more often than write, so make the hard path the least common and set the policy on some other object, thoughts @idesai ?
True. The policy to write then would be something like an PolicyAuthorize or PolicySigned to give the user the ownership of the NV object.

**Comment by idesai** [comment]
> @idesai thank you.
> 
> So I am running:
> 
> tpm2_nvdefine -C o -a "authwrite|policyread" -p 246 -P ownerpass
> 
> tpm2_policycommandcode -L policy.dat TPM2_CC_NVRead
> 
> this fails with "could not convert command-code to number"
> 
> am i supposed to start an authsession and pass in my session to this command? when i do that it fails as well.
> 
> how am I to pass in that policy to the index so anyone can read?

Try defining it this way:
```bash
tpm2_startauthsession -S session.ctx
tpm2_policycommandcode -S session.ctx -L policy.cmdcode TPM2_CC_NV_Read
tpm2_flushcontext session.ctx 

tpm2_nvdefine -C o -a "authwrite|policyread" -p 246 -P ownerpass -L policy.cmdcode
```

**Comment by workmaryville** [comment]
@idesai  thanks again. 

I run the above commands you've provided. then the following:

tpm2_nvwrite 0 -i pub.key -P 246

when i try to read i run:

tpm2_nvread 0 
&
tpm2_nvread 0 -P session:session.ctx

it errors out each time. reading with blank credentials do not work. and I restart the auth session as well and it likewise fails with "invalid handle authorization" and "trial session cannot be used to authenticate."

I also am getting "authValue or authPolicy is not available for selected entity"

is there a way to get around this?

**Comment by williamcroberts** [comment]
```bash
#!/usr/bin/env bash
tpm2_changeauth -co ownerpass
tpm2_startauthsession -S session.ctx
tpm2_policycommandcode -S session.ctx -L policy.cmdcode TPM2_CC_NV_Read
tpm2_flushcontext session.ctx

tpm2_nvdefine -C o -a "authwrite|policyread" -p mypass -P ownerpass -L policy.cmdcode 0

echo "foo" > write.dat
tpm2_nvwrite -P mypass -C0 -i write.dat 0

tpm2_startauthsession --policy-session -S session.ctx
tpm2_policycommandcode -S session.ctx -L policy.cmdcode TPM2_CC_NV_Read
tpm2_nvread -C0 -P"session:session.ctx" -s3 0
tpm2_flushcontext session.ctx
```

**Comment by workmaryville** [comment]
@williamcroberts that works. thank you. 

so just to be clear, the software that we automate to pull this key for signature validation will need to run the start auth session command every time before reading the index?

**Comment by williamcroberts** [comment]
> @williamcroberts that works. thank you.
> 
> so just to be clear, the software that we automate to pull this key for signature validation will need to run the start auth session command every time before reading the index?

Correct, but you could flip this and do it another way so read just works and write is the "harder" path. I can give you an example for that.

> 
> lastly, to rewrite the index, in case of key rollover, we must use the owner password to run tpm2_nvundefine, correct?

Just write the NV Index with the nvindex password of mypass

> 
> if that is the case, then the write password is only good for one time? after that the owner password really owns the index. is this true? it is how it playing out in my simulation.

No, but you have to understand this quirk with NV Indexs, they can be authorized to use with them through 2 passwords based on attributes:
| attribute | action |
| ---------- | --------- |
| ownerread | use owner password to read |
| authread | use index password to read |
Note their are also write versions of these.

So when you specify option `-C` to nvread, you can specify the nvindex, which says, hey I want to read this with the NV Index password (specified in option `-P`), or you can specify the hierarchy like `-C owner` and it says hey I want to read this with the owner password. I think in my example you can drop the `-C` in `tpm2_nvwrite -P mypass -C0 -i write.dat 0` as the tools default to using the index password.

You can drop the attribute ownerread and ownerwrite to prevent the hierarchy from having access IIUC. The default set of attributes for an nv index defined by `tpm2_nvdefine` is `ownerwrite|authwrite|ownerread|authread`.

**Comment by williamcroberts** [comment]
Here is an example of using policysecret for write and having tpm2_nvread just work with no extra steps:

```bash
#!/usr/bin/env bash
tpm2_changeauth -co ownerpass

# define an nv index for the password (note it will warn on size being 0, no worries)
tpm2_nvdefine -C o -a "" -p mypass -P ownerpass -s0 0x1000000

# define an nv index that will use the password of NV Index 0 and an empty password for read.
tpm2_startauthsession -S session.ctx
tpm2_policysecret -S session.ctx -L authsecret.policy -c 0x1000000 "mypass"
tpm2_flushcontext session.ctx 

tpm2_nvdefine -C o -a "policywrite|authread" -P ownerpass -L authsecret.policy 0x1000001

# start the policy for writes
tpm2_startauthsession --policy-session -S session.ctx
tpm2_policysecret -S session.ctx -L authsecret.policy -c 0x1000000 "mypass"
echo "foo" > write.dat
tpm2_nvwrite -P "session:session.ctx" -i write.dat 0x1000001
tpm2_flushcontext session.ctx

# reads are simple
tpm2_nvread -s3 0x1000001
```

**Comment by workmaryville** [comment]
@williamcroberts that works beautifully. nice call on making writing the more difficult path.

**Comment by workmaryville** [comment]
@williamcroberts one quick question. for education, why do the index handles change across the commands? it goes from 0x1000000 to 0x1000001?

**Comment by idesai** [comment]
> @williamcroberts one quick question. for education, why do the index handles change across the commands? it goes from 0x1000000 to 0x1000001?

Because it looks for the next available one in case the one you are attempting to use is already defined like so [here](https://github.com/tpm2-software/tpm2-tools/blob/9814300d2fea0a439bb801cda27bdc45ad930bb9/tools/tpm2_nvdefine.c#L200)
