### ISSUE TITLE
Policy with password

### ISSUE THREAD

**Issue by ntnx-alay** [tpm2-software/tpm2-tools#2989]
I have this sample script that depicts one of the use case.

Need two authorization for decrypt. Own password and satisfy policy secret.

`
OWNER_PSWD="ownerpassword"
KEY_PSWD="keypassword"
mkdir work
pushd work
# Prep policy and keys
tpm2_changeauth -c o ${OWNER_PSWD}
tpm2_createprimary -C o -c prim.ctx -P ${OWNER_PSWD}
tpm2_startauthsession -S session.ctx
tpm2_policysecret -S session.ctx -c o -L secret.policy ${OWNER_PSWD}
tpm2_flushcontext session.ctx
rm session.ctx
# Important! Create key that follows policy and has password. Is this wrong?
tpm2_create -C prim.ctx -r key.priv -u key.pub -L secret.policy -G rsa -g sha256 -p  ${KEY_PSWD}
tpm2_load -C prim.ctx -r key.priv -u key.pub -c key.ctx

echo "secret data" > toencrypt.txt

# Get encrypted data
tpm2_rsaencrypt -c key.ctx -o encrypted.txt toencrypt.txt

# Trial# 1: Prented to satisfy "policy" and password
tpm2_startauthsession -S session.ctx --policy-session
tpm2_policysecret -S session.ctx -c o ${OWNER_PSWD}
tpm2_rsadecrypt -c key.ctx -o decrypted.txt -p ${KEY_PSWD} encrypted.txt
tpm2_flushcontext session.ctx
rm session.ctx

# Trial# 2: Just passdown password!
tpm2_rsadecrypt -c key.ctx -o decrypted.txt -p ${KEY_PSWD} encrypted.txt
popd
`

Question: Both Trial# 1 and Trial# 2 is able to decrypt message. I hoped and believed that Trial# 2 shall fail since policy is not satisfied. Am I missing something?

**Comment by ntnx-alay** [comment]
While creating key with following resolves concern, doubt I have (I think):

`
tpm2_create -C prim.ctx -r key.priv -u key.pub -a "sign|decrypt|fixedtpm|fixedparent|sensitivedataorigin" -L secret.policy -G rsa -g sha256 -p  ${KEY_PSWD}
`

It would be great is expert can confirm my understanding.

Default attribute of tpm2_create is "userWithAuth" and that allowed password authentication when supplied. Policy was really useless. Moment I removed "userWithAuth" - now it forced to have it authenticated with policy.

I updated code to:

`
OWNER_PSWD="ownerpassword"
KEY_PSWD="keypassword"
mkdir -p work
pushd work
# Prep policy and keys
#tpm2_changeauth -c o ${OWNER_PSWD}
#tpm2_createprimary -C o -c prim.ctx -P ${OWNER_PSWD}
tpm2_startauthsession -S session.ctx
tpm2_policyauthvalue -S session.ctx -L secret.policy
tpm2_policysecret -S session.ctx -c o -L secret.policy ${OWNER_PSWD}
tpm2_flushcontext session.ctx
rm session.ctx
tpm2_create -C prim.ctx -r key.priv -u key.pub -a "sign|decrypt|fixedtpm|fixedparent|sensitivedataorigin" -L secret.policy -G rsa -g sha256 -p  ${KEY_PSWD}
tpm2_load -C prim.ctx -r key.priv -u key.pub -c key.ctx

echo "secret data" > toencrypt.txt

# Get encrypted data
tpm2_rsaencrypt -c key.ctx -o encrypted.txt toencrypt.txt

# Trial# 1: Prented to satisfy "policy" and password
echo "Trial# 1 starts"
tpm2_startauthsession -S session.ctx --policy-session
tpm2_policyauthvalue -S session.ctx
tpm2_policysecret -S session.ctx -c o ${OWNER_PSWD}
tpm2_rsadecrypt -c key.ctx -o decrypted_1.txt -p "session:session.ctx+${KEY_PSWD}" encrypted.txt
tpm2_flushcontext session.ctx
rm session.ctx
echo "Trial# 1 ends"


# Trial# 2: Just passdown password!
echo "Trial# 2 starts"
tpm2_rsadecrypt -c key.ctx -o decrypted_2.txt -p ${KEY_PSWD} encrypted.txt
echo "Trial# 2 ends"

popd
`

**Comment by idesai** [comment]
That's correct. At object creation time,
1. if you specify a password then userwithAuth is turned on.
2. If instead you specify a policy then this attribute is turned off.
3. If you specify a policy and a password then the attribute is turned on to ensure any policysecret can reference the object's authvalue.
4. As always, you can enforce the attributes by specifying them.

**Comment by ntnx-alay** [comment]
Nice, thanks a lot @idesai! Especially #3 is very important that I learnt from experiment and your response.
