### ISSUE TITLE
Cannot Flush Context to Handle Transient Resources, or Start Auth Session 

### ISSUE THREAD

**Issue by dadiestfish2077** [tpm2-software/tpm2-tools#2996]
We are using an older version of the tools, and the lack of commands are creating issues for our desired implementation. 

First, when accessing the tpm directly, we consistently run into the following error messages when creating and sealing objects to the TPM PCRs. 

tpm2_pcrlist -L sha256:23 -o pcr.bin
tpm2_createpolicy --policy-pcr -L sha256:23 -f pcr.policy -F pcr.bin
tpm2_createprimary -H o -g 0x0004 -G 0x0001 -C primary.context -P 999
tpm2_create -g 0x000B -G 0x0008 -u obj.pub -r obj.priv -I secret.data -c primary.context -L pcr.policy
tpm2_load -c primary.context -u obj.pub -r obj.priv  -n name.load -C load.ctx

**Load Object Failed ! ErrorCode: 0x902**
tpm2_rc_decode 0x902

hex: 0x0
  identifier: TSS2_TPM_RC_LAYER
  description: Error produced by the TPM
format 0 warning code
  hex: 0x02
  name: TPM2_RC_OBJECT_MEMORY
  description: out of memory for object contexts

this will work only if we use the kernel resource manager. However, in production there are reasons why we cannot do this. so we must access the tpm directly and therefore be in charge of managing the transient objects. when running get_cap -c handles-transient we get:

0x80000000
0x80000001
0x80000002

and this is the max as detailed in the TPM_PT_TPM2_HR_TRANSIENT_MIN:  field. 

the tools we are using does not have flush_context. **is there any other way for us to manage these objects?** 

the commands available seem to be:
tpm2_activatecredential  tpm2_getcap              tpm2_load                tpm2_nvwrite             tpm2_rsaencrypt
tpm2_certify             tpm2_getmanufec          tpm2_loadexternal        tpm2_pcrevent            tpm2_send
tpm2_create              tpm2_getpubak            tpm2_makecredential      tpm2_pcrextend           tpm2_sign
tpm2_createpolicy        tpm2_getpubek            tpm2_nvdefine            tpm2_pcrlist             tpm2_startup
tpm2_createprimary       tpm2_getrandom           tpm2_nvlist              tpm2_quote               tpm2_takeownership
tpm2_dictionarylockout   tpm2_hash                tpm2_nvread              tpm2_rc_decode           tpm2_unseal
tpm2_encryptdecrypt      tpm2_hmac                tpm2_nvreadlock          tpm2_readpublic          tpm2_verifysignature

We also do not have start_authsession. in order to manage the nvindices on the TPM we need to perform startauthsession as well as policysecret. are there functions above that support the same functionality?

**Comment by idesai** [comment]
what version of tools are being used?
