### ISSUE TITLE
Compile TPM2-tools for Windows 10

### ISSUE THREAD

**Issue by danielwangksu** [tpm2-software/tpm2-tools#3001]
Hi there, I found some old thread discussion on porting TPM2-tools to Windows. Is there any progress on that effort? Also does anyone know if there is other tools we can use to provision TPM on Windows at this moment? Thank you for you help!

**Comment by williamcroberts** [comment]
> Thank you! @williamcroberts I guess that's what I have to do. The only thing I found about TPM2 related command line tools are those https://docs.microsoft.com/en-us/powershell/module/trustedplatformmodule/?view=windowsserver2022-ps in case someone is also search

If you just ifdef out the broken parts and submit a patch we could start to roll in experimental windows support and set up appveyor to build.

**Comment by danielwangksu** [comment]
Will do! I will close this thread for now! Thank you again for your help!
