### ISSUE TITLE
Command handling when all sessions are occupied

### ISSUE THREAD

**Issue by robret77** [tpm2-software/tpm2-tools#3020]
On Ubuntu 22.04, currently TPM commands fall into a deep sleep when all sessions are occupied. It can for example be reproduced by repeated sealing a secret to an object with a PCR policy auth session and without flushing the session contexts (one for the trial session, one for the policy session).

This will lead to a denial of service situation, specially if another application is responsible for not flushing the context. After a quite random amount of occupied sessions, the next call to e. g. 'tpm2_startauthsession  --policy-session -S mysession.ctx' will fall into an endless sleep and the following message is printed to dmesg:

```
[15593.832591] tpm tpm0: tpm2_save_context: failed with a TPM error 0x0901
[15593.856637] tpm tpm0: A TPM error (459) occurred flushing context
[15593.856657] tpm tpm0: tpm2_commit_space: error -14
```

Currently one (tested) way around is to add a timeout to every TPM command in a batch, abort the batch in case of a single timeout, then flush all sessions by calling: 'tpm2_flushcontext -s' and start over the full batch one more time. Another solution (untested) could be to create one dedicated session when the system boots, reuse it and in fact never flush it.

Both ways are probably not nice, it would be better if a TPM command would fail with a special error code when all sessions are occupied instead of sleep indefinitely or, even better, have the resource manager swap them in and out like it already does with transient objects.

**Comment by williamcroberts** [comment]
I think this is a kernel bug as the kernel RM should send an error back indicating the save_context failed.

**Comment by robret77** [comment]
The problem persists even after a reboot, when all sessions are consumed and the device is rebooted, then a TPM LUKS integration will stall forever in initrd, and CTRL+C of course does not work. Booting from an USB stick and clearing the sessions will release this lock.

I'll write a kernel bug report.
