### ISSUE TITLE
Consider serializing TPML_PCR_SELECTION according to specification

### ISSUE THREAD

**Issue by ansasaki** [tpm2-software/tpm2-tools#3021]
In `pcr_fwrite_serialized()` function, the `TPML_PCR_SELECTION` structure is serialized using a custom format instead of using the serialization format from the specification (i.e. the same format implemented by `Tss2_MU_TPML_PCR_SELECTION_Marshal()`):

https://github.com/tpm2-software/tpm2-tools/blob/9cf075b8f8563a75b465e06a428c962e6ef83fd1/lib/pcr.c#L240-L256

This forces consumers of this output to implement a custom de-serialization instead of using the `Tss2_MU_TPML_PCR_SELECTION_Unmarshal()` function from the specification.

**Comment by idesai** [comment]
@ansasaki the format can be specified with [this](https://github.com/tpm2-software/tpm2-tools/blob/9cf075b8f8563a75b465e06a428c962e6ef83fd1/lib/pcr.c#L285).
