### ISSUE TITLE
Failed to run tpm2_checkquote for sha1 in new version.

### ISSUE THREAD

**Issue by mengwangict** [tpm2-software/tpm2-tools#3031]
When I run the command of tpm2_checkquote for sha1, it's failed in tpm2-tools-5.2-1.el9.x86_64. But The same commands could be successful in lower version. The following is the commands:
    (1) The failed version------------------------------
[root@centos9-center tmp]# uname -a
Linux centos9-center 5.14.0-105.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun 3 10:10:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@centos9-center tmp]# rpm -qa | grep tpm2-tools
tpm2-tools-5.2-1.el9.x86_64
[root@centos9-center tmp]# tpm2_clear
[root@centos9-center tmp]# tpm2_createek -c 0x81010001 -G rsa -u ekpub.pem -f pem
[root@centos9-center tmp]# tpm2_createak -C 0x81010001 -c ak.ctx -G rsa -s rsassa -g sha1 -u akpub.pem -f pem -n ak.name
loaded-key:
  name: 000b132e10c69a84361a1bb8fbc35da49ce41d1d296bb0c373f22a991d5fb354c4ba
  qualified name: 000b398aee311d7802a46a41f6698700514b2da86ffff0597ec61da10432c8862544
[root@centos9-center tmp]# tpm2_quote -c ak.ctx -l sha1:0,16 -q abc123 -m quote.msg -s quote.sig -o quote.pcrs -g sha1
quoted: ff54434780180022000b398aee311d7802a46a41f6698700514b2da86ffff0597ec61da10432c88625440003abc123000000000000668c0000000000000000012019102300163636000000010004030100010014814ffad5d7753c9ad209de6dbdad29a85594d99e
signature:
  alg: rsassa
  sig: 8550fd66658d00f78a236567614d04192e1e2a77082121ec8cc9586fedbae8c6be38e33415206cfd95aa9191e4b9c395e6bb0ca2c88ee03d55a91a0f9fab24e872acc097f49f6c15264bae9adecc94db1b14abfbfde94828e2e213123ad5aef261ff214347ee5467c2ff9605f441bdb7c3b7ed72b7fb86fd8b0c0f4d08b70267ff271b272b3e72efa11074d35ae9d6996c432b9bed749b9e535786c91d18395afac00819333f7f9dc8b906bf02b1eb6e3a41a70531b94e3ce2f704b0b35159bb4661393ffc94124354f3b5a88f1de17f5f742e6bd6266c2636684e8287dc6de2d367929ece196b748731461086bba8c57e281deed3d4c4d6e5722c344e63a930
pcrs:
  sha1:
    0 : 0x46FE5CF1BC061BB9D2DF1893B4662BFCB10608D0
    16: 0x0000000000000000000000000000000000000000
calcDigest: 814ffad5d7753c9ad209de6dbdad29a85594d99e
[root@centos9-center tmp]# tpm2_checkquote -u akpub.pem -m quote.msg -s quote.sig -f quote.pcrs -g sha1 -q abc123
pcrs:
  sha1:
    0 : 0x46FE5CF1BC061BB9D2DF1893B4662BFCB10608D0
    16: 0x0000000000000000000000000000000000000000
sig: 8550fd66658d00f78a236567614d04192e1e2a77082121ec8cc9586fedbae8c6be38e33415206cfd95aa9191e4b9c395e6bb0ca2c88ee03d55a91a0f9fab24e872acc097f49f6c15264bae9adecc94db1b14abfbfde94828e2e213123ad5aef261ff214347ee5467c2ff9605f441bdb7c3b7ed72b7fb86fd8b0c0f4d08b70267ff271b272b3e72efa11074d35ae9d6996c432b9bed749b9e535786c91d18395afac00819333f7f9dc8b906bf02b1eb6e3a41a70531b94e3ce2f704b0b35159bb4661393ffc94124354f3b5a88f1de17f5f742e6bd6266c2636684e8287dc6de2d367929ece196b748731461086bba8c57e281deed3d4c4d6e5722c344e63a930
ERROR: Error validating signed message with public key provided
ERROR: Verify signature failed!
ERROR: Unable to run tpm2_checkquote
(2) The successed version----------------
[root@measureBoot ~]# uname -a
Linux measureBoot 5.14.0-105.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun 3 10:10:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@measureBoot ~]# tpm2_checkquote -v
tool="tpm2_checkquote" version="5.0" tctis="libtss2-tctildr" tcti-default=tcti-abrmd
[root@measureBoot ~]# rpm -qa |g grep tpm2-tools
bash: g: command not found...
[root@measureBoot ~]# rpm -qa | grep tpm2-tools
tpm2-tools-5.0-3.el9.x86_64
[root@measureBoot ~]# tpm2_clear
[root@measureBoot ~]# cd /tmp/
[root@measureBoot tmp]# tpm2_createek -c 0x81010001 -G rsa -u ekpub.pem -f pem
[root@measureBoot tmp]# tpm2_createak -C 0x81010001 -c ak.ctx -G rsa -s rsassa -g sha1 -u akpub.pem -f pem -n ak.name
loaded-key:
  name: 000b7318b0c72de6dbcee763df8a9d8ec82c398ce73e9c6d73f55e6ea5511d8cf9a9
  qualified name: 000b53bdc7e02f0f6235e70d7a5e5b702b4119df61a32c91100c44ed3b90ba98d0e9
[root@measureBoot tmp]# tpm2_quote -c ak.ctx -l sha1:0,16 -q abc123 -m quote.msg -s quote.sig -o quote.pcrs -g sha1
quoted: ff54434780180022000b53bdc7e02f0f6235e70d7a5e5b702b4119df61a32c91100c44ed3b90ba98d0e90003abc123000000000000ce450000000000000000012019102300163636000000010004030100010014dabd8cecad766b22e4f94156b421e7a79e1fdf77
signature:
  alg: rsassa
  sig: 5e242c5fc519f718403601440f39e6b75076d402e210c03c5afbcb9ee1b97d9c8399617f1b37c92fc95bfc0f3d5f09dfc5dbd7caf2dd9a6a1c048ecb86baec2c7ff651c846fb63ea384d325a30e0ff3b4a3459934b1d6d35c6aef795c6d1fef6d86d137dfcd2c65acf1bda6de5c12b3831e8173d0628eeddfec6c0aed187ad9371ed59a19f70363a27bef7bf14b67892db86c9af40ba0e009d7a8b7455c8d2ece3a0c8d9c8222d253079ccc606f22b54dabf4f9faf03e94f81736ba41b4bd518a5f391d634a88104680d192068ef38cdba4d5f8dafe5f25d6f977ad9808cdee43355b39759a491c6c3fccddcecd825763d3a94007c6a63495f602808dfb570a5
pcrs:
  sha1:
    0 : 0x46FE5CF1BC061BB9D2DF1893B4662BFCB10608D0
    16: 0x36191678BE80100C6A6D670C46B93994789F0B43
calcDigest: dabd8cecad766b22e4f94156b421e7a79e1fdf77
[root@measureBoot tmp]# tpm2_checkquote -u akpub.pem -m quote.msg -s quote.sig -f quote.pcrs -g sha1 -q abc123
pcrs:
  sha1:
    0 : 0x46FE5CF1BC061BB9D2DF1893B4662BFCB10608D0
    16: 0x36191678BE80100C6A6D670C46B93994789F0B43
sig: 5e242c5fc519f718403601440f39e6b75076d402e210c03c5afbcb9ee1b97d9c8399617f1b37c92fc95bfc0f3d5f09dfc5dbd7caf2dd9a6a1c048ecb86baec2c7ff651c846fb63ea384d325a30e0ff3b4a3459934b1d6d35c6aef795c6d1fef6d86d137dfcd2c65acf1bda6de5c12b3831e8173d0628eeddfec6c0aed187ad9371ed59a19f70363a27bef7bf14b67892db86c9af40ba0e009d7a8b7455c8d2ece3a0c8d9c8222d253079ccc606f22b54dabf4f9faf03e94f81736ba41b4bd518a5f391d634a88104680d192068ef38cdba4d5f8dafe5f25d6f977ad9808cdee43355b39759a491c6c3fccddcecd825763d3a94007c6a63495f602808dfb570a5
[root@measureBoot tmp]#
(3)  So, the same commands:
       tpm2_createek -c 0x81010001 -G rsa -u ekpub.pem -f pem
       tpm2_createak -C 0x81010001 -c ak.ctx -G rsa -s rsassa -g sha1 -u akpub.pem -f pem -n ak.name
       tpm2_quote -c ak.ctx -l sha1:0,16 -q abc123 -m quote.msg -s quote.sig -o quote.pcrs -g sha1
       tpm2_checkquote -u akpub.pem -m quote.msg -s quote.sig -f quote.pcrs -g sha1 -q abc123
    The newer version will be failed. I also found that the commands will be successful in centos 8 stream which has tpm2-tools-4.1.1-5.el8.x86_64.
Could anyone tell me, it's a bug or just miss operation for the commands?

**Comment by idesai** [comment]
@mengwangict I am not able to replicate the issue at my end. Your commands look okay.

**Comment by mengwangict** [comment]
It seems that the security policy of centos 9 stream does not support SHA1.  Run the cmd:
update-crypto-policies --set LEGACY ,  then the problem disappeared. So this issume could be closed. Thanks all guys anyway.

**Comment by williamcroberts** [comment]
That's good to know, I had no idea centos was doing that
