### ISSUE TITLE
Test cannot be executed in paralell

### ISSUE THREAD

**Issue by aplanas** [tpm2-software/tpm2-tools#3042]
Seems that executing the tests in parallel (`make -j8 check`, for example) left some `tpm_server` instances running behind, making the tests to never end.

**Comment by idesai** [comment]
Can you tell us more about how we can replicate the issue with some details of your system env? I have seen instances where there are some orphaned tpm_server instances, however, never a scenario where tests do not complete. Is it a specific test that it hangs on every time?

**Comment by aplanas** [comment]
Seems that the tests `gettime.sh`, `readclock.sh` and `symlink.sh` are launching the simulator, but forgot to call the shutdown. I will fix those and see if this is the cause of the make blockage.
