### ISSUE TITLE
Computing NV Index Names

### ISSUE THREAD

**Issue by ptsolakos** [tpm2-software/tpm2-tools#3048]
Hi

I am trying to compute the names for the NV Indices storing Delegation Policies as described in section 7.3.6.5 of specification [TPM 2.0 Keys for Device Identity and Attestation](https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf). For this purpose I am executing the following commands: 

```
tpm2_startauthsession -g sha256 -S session.ctx
tpm2_policysecret -Q -S session.ctx -c e -L secret.policy
tpm2_nvdefine -S session.ctx -s 0x22 -a 0x220F1008 0x01C90010
```

and I am getting the following error:

```
WARNING:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:344:Esys_NV_DefineSpace_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:122:Esys_NV_DefineSpace() Esys Finish ErrorCode (0x00000a82)
ERROR: Failed to define NV area at index 0x1C90010
ERROR: Esys_NV_DefineSpace(0xA82) - tpm:session(2):inconsistent attributes
ERROR: Failed to create NV index 0x1c90010.
ERROR: Unable to run tpm2_nvdefine
```

Can somebody please shed some light why this error happens? What am I doing wrong? How can the below name be computed?

| Policy Index Name  | Value (hex) |
| ------------- | ------------- |
|  DS1 Signing Key Name:<br/>0x000B \|\| H<sub>SHA256</sub>(0x01C90010 \|\|<br/> 0x000B \|\| 0x220F1008 \|\| 0x0020 \|\| PolicyUser<sub>SHA256</sub> \|\| 0x0022) | 000bd910fb32da43317c5e7780c0ef8c4d92d9c13505267ce1fa27acc9f9478ac412  |

(Copied from Table 14 of TPM 2.0 Keys for Device Identity and Attestation specification)

Thank you very much in advance
Panagiotis

**Comment by idesai** [comment]
@ptsolakos change `tpm2_nvdefine -S session.ctx -s 0x22 -a 0x220F1008 0x01C90010` to `tpm2_nvdefine -L secret.policy -s 0x22 -a 0x020F1008 0x01C90010` and then actually write to the NV index by satisfying the auth to realize the correct NV index name.

**Comment by ptsolakos** [comment]
@idesai Thank you very much for your help.

I now understand, that when defining the NV index, I have to provide the raw attribute value with the written bit cleared, and then actually write to the NV index which will eventually set the bit.

**Comment by ptsolakos** [comment]
@idesai I was wandering why the raw value of the attributes in the `tpm2_nvreadpublic` is shown in opposite endianness. Is the ntoh conversion needed [here](https://github.com/tpm2-software/tpm2-tools/blob/42486c83b9af1ba7ddb0a142cbb1cc3e991db786/tools/tpm2_nvreadpublic.c#L122)?

**Comment by williamcroberts** [comment]
> @idesai I was wandering why the raw value of the attributes in the `tpm2_nvreadpublic` is shown in opposite endianness. Is the ntoh conversion needed [here](https://github.com/tpm2-software/tpm2-tools/blob/42486c83b9af1ba7ddb0a142cbb1cc3e991db786/tools/tpm2_nvreadpublic.c#L122)?

Yes that ntoh should go away...
**with NTOH**:
```bash
tpm2 nvdefine
tpm2 nvreadpublic 0
0x1000000:
  name: 000b1195f36a21c8219055ad0803c39e7e81d06cdb2eee2b7cf93dd83e01d4273828
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ownerwrite|authwrite|ownerread|authread
    value: 0x6000600
  size: 2048

tpm2 nvdefine -a 0x6000600
ERROR:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:192:Esys_NV_DefineSpace_Async() Error (async) NV_DefineSpace: 7000b 
ERROR:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:99:Esys_NV_DefineSpace() Error in async function ErrorCode (0x0007000b) 
ERROR: Failed to define NV area at index 0x1000001
ERROR: Esys_NV_DefineSpace(0x7000B) - esapi:A parameter has a bad value
ERROR: Failed to create NV index 0x1000001.
ERROR: Unable to run tpm2_nvdefine
```

**NTOH Removed**
```bash
tpm2 nvreadpublic 0
0x1000000:
  name: 000b1195f36a21c8219055ad0803c39e7e81d06cdb2eee2b7cf93dd83e01d4273828
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ownerwrite|authwrite|ownerread|authread
    value: 0x60006
  size: 2048
./tools/tpm2 nvdefine -a 0x60006 1
nv-index: 0x1000001
```

** Patch incoming **

**Comment by williamcroberts** [comment]
PR: https://github.com/tpm2-software/tpm2-tools/pull/3054
