### ISSUE TITLE
Verify TPM residency of IDevID key in process of credential activation

### ISSUE THREAD

**Issue by UHeinitz** [tpm2-software/tpm2-tools#3070]
Hi, 
I am trying to reconstruct the process of credential activation (OEM Creation of IAK and IDevID in a Single Pass) according section 6.2.2 of specification [TPM 2.0 Keys for Device Identity and Attestation](https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf) and fail on CA to verify the TPM residency of the IDevID key. 

Platform software certifies IDevID key (only certify IDevID relevant commands):
`tpm2_readpublic -Q -c $IAKCTX -f pem -o iak.pem`
`tpm2_certify -Q -c $IDEVIDCTX -C $IAKCTX -g sha256 -o $ATTEST -s $SIG`
the content of $ATTEST and $SIG are put together with others in the CSR.

CA extracts the needed data pieces from the CSR:
- $ATTEST file (contains TPM2B_ATTEST structure)
- $SIG file (contains signature over TPM2B_ATTEST structure)
IAK public key iak.pem is send from platform to CA too.

Now the CA tries to validate the signature of the TPM2B_ATTEST structure:
`openssl dgst -sha256 -verify iak.pem -signature $SIG $ATTEST`
`Verification failure`

Why does the verification fail?

Thank you very much for any hints
Uta

**Comment by UHeinitz** [comment]
Sorry, I forgot some additional info:
The iak.pem is created by platform software via:
`tpm2_readpublic -Q -c $IAKCTX -f pem -o iak.pem`

**Comment by idesai** [comment]
`openssl dgst -verify iak.pem -keyform pem -sha256 -signature $SIG $ATTEST`

**Comment by UHeinitz** [comment]
Thank you for your answer but this doesn't fix the problem. The failure is:
`$ sudo openssl dgst -verify iak.pem -keyform pem -sha256 -signature sig.out attest.out
Verification failure
4067835A097F0000:error:0200008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding:../crypto/rsa/rsa_pk1.c:75:
4067835A097F0000:error:02000072:rsa routines:rsa_ossl_public_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:599:
4067835A097F0000:error:1C880004:Provider routines:rsa_verify:RSA lib:../providers/implementations/signature/rsa_sig.c:774:`

I am using
- swtpm 0.6.3-0ubuntu3 (https://github.com/stefanberger/swtpm)
- tpm2-openssl 1.0.1-1
- tpm2-tools 5.2-1build1

The problem looks similar as described in https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/CJEV4ESV7KXDXHVBCXWWYTXUO7P4I3PC/

**Comment by idesai** [comment]
@UHeinitz, we have an integration test now that tests this scenario. Does your script look different from [this](https://github.com/tpm2-software/tpm2-tools/blob/master/test/integration/tests/certify.sh#L21:#L36)?

**Comment by UHeinitz** [comment]
My script is similar to the referenced. Should the tpm2_load the point of the matter? Would this command be needed for primary keys too? 
I would like to have both IAK and IDevID primary keys as described in [TPM 2.0 Keys for Device Identity and Attestation](https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf). But for tpm2_createprimary command there is no '--private' option.

My script is the following:
<pre>
# create IAK and IDevID and certify IDevID with IAK
$ tpm2_getekcertificate -o ek.crt
sudo tpm2_createprimary -C e -G rsa2048:rsassa-sha256:null -g sha256 -c iak.ctx -a 'fixedtpm|fixedparent|sign|adminwithpolicy|userwithauth|restricted|sensitivedataorigin'
sudo tpm2_readpublic -c iak.ctx -o iak.pub
tpm2_evictcontrol -C o -c iak.ctx 0x81010002
sudo tpm2_readpublic -Q -c iak.ctx -f pem -o iak.pem
sudo tpm2_createprimary -C e -G rsa2048 -g sha256 -c idevid.ctx -a 'fixedtpm|fixedparent|sign|userwithauth|noda|sensitivedataorigin'
sudo tpm2_evictcontrol -C o -c idevid.ctx 0x81010003
sudo tpm2_readpublic -Q -c idevid.ctx -f pem -o idevid.pem
sudo tpm2_certify -Q -c idevid.ctx -C iak.ctx -g sha256 -o attest.out -s sig.out

# verify the signature over attestation structure
sudo openssl dgst -sha256 -verify iak.pem -signature sig.out attest.out
</pre>

The output is:
<pre>
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|adminwithpolicy|restricted|sign
  raw: 0x500f2
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: rsassa
  raw: 0x14
scheme-halg:
  value: sha256
  raw: 0xb
sym-alg:
  value: null
  raw: 0x10
sym-mode:
  value: (null)
  raw: 0x0
sym-keybits: 0
rsa: a6e20724b48c3dcac68cb8af3b18a6629c8f0466573f0de37fc7d0b363a5c2e1b326810ecf82a9f5af93278df3b4ea432bbcfba9e832106b2c34c21dc2e76f76f2235c9c31d0fc9e5853aebfe0e4281ce85919425e3f54a83c7d5d1ed409240f2547feee5dfa95571a1f7c2dee2797c21654c7f64215b95a7af9c76dd04f05f83ab73508624a5d72aa060a9dad6af403b185a8c0f87bdf06143ac5be96513a3ac5c184129c2142ade61fa429f82c22d31d627dd3fa63b0c19b7c23e95b4f9bbf90a483ae8a00544e852d57624f9a4060da43b61fb81a86fd547187bcb8f8eb8ee5795084dd4e4ef79fe9bf2a5da6bc4e12fa69f0151ce4afe7e408cd86aa6f63
name: 000b51d969d9fe41169467d4704a7f696213edaf597f91d9a32b73045fd52271a0df
qualified name: 000bb9776591abd88f72c97eab6c90dfe29106b911737e6985a0b5736b33de69f0c2
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|adminwithpolicy|restricted|sign
  raw: 0x500f2
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: rsassa
  raw: 0x14
scheme-halg:
  value: sha256
  raw: 0xb
sym-alg:
  value: null
  raw: 0x10
sym-mode:
  value: (null)
  raw: 0x0
sym-keybits: 0
rsa: a6e20724b48c3dcac68cb8af3b18a6629c8f0466573f0de37fc7d0b363a5c2e1b326810ecf82a9f5af93278df3b4ea432bbcfba9e832106b2c34c21dc2e76f76f2235c9c31d0fc9e5853aebfe0e4281ce85919425e3f54a83c7d5d1ed409240f2547feee5dfa95571a1f7c2dee2797c21654c7f64215b95a7af9c76dd04f05f83ab73508624a5d72aa060a9dad6af403b185a8c0f87bdf06143ac5be96513a3ac5c184129c2142ade61fa429f82c22d31d627dd3fa63b0c19b7c23e95b4f9bbf90a483ae8a00544e852d57624f9a4060da43b61fb81a86fd547187bcb8f8eb8ee5795084dd4e4ef79fe9bf2a5da6bc4e12fa69f0151ce4afe7e408cd86aa6f63
persistent-handle: 0x81010002
action: persisted
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|noda|sign
  raw: 0x40472
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: null
  raw: 0x10
sym-mode:
  value: (null)
  raw: 0x0
sym-keybits: 0
rsa: c29435ff6bee6a001c5d95c40b0c8563b1bc065bf6fa1775722d7a255de73cbb47f45774add158c431e40d409bd77155e4635ac3b2f69b627af60c7f931ff45e756854a47f1a519c0ae109410554efe34d7ebd1a9d4f0e6efc2545719ea19bce600f41d4c31f2e817b0ca163f1e055c9745ce8fac478bd5a08b314c1bb0d025207703fe5ff092e423bd6bddb48d12333bac2196a91d12d73e05a4313df41dd32088027c59b30187737af68672a7205c40f8a45129b3fa5c7916b51aeafdf7620bdbd79bb4da74cdc25c1fa05ba60e8e3a383ebed208cc6ae670b57cbff2fb9e1cbaff3347ca4f45de1beae9a909bc13ee1a7166963e26fa2457ad8cf11e7fb67
persistent-handle: 0x81010003
action: persisted
Verification failure
40F771EB087F0000:error:0200008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding:../crypto/rsa/rsa_pk1.c:75:
40F771EB087F0000:error:02000072:rsa routines:rsa_ossl_public_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:599:
40F771EB087F0000:error:1C880004:Provider routines:rsa_verify:RSA lib:../providers/implementations/signature/rsa_sig.c:774:
uta@uta-Ubuntu-VM:~/device$ sudo tpm2_getcap handles-persistent
- 0x81010001
- 0x81010002
- 0x81010003
- 0x81010016
</pre>

**Comment by idesai** [comment]
This line needs to be fixed in your script - `sudo tpm2_certify -Q -c idevid.ctx -C iak.ctx -g sha256 -o attest.out -s sig.out -f plain`

**Comment by UHeinitz** [comment]
@idesai Thank you - now it works :) The option '-f plain' was finally the point. I considered your first hint to that detail but I guess it didn't work at that time because I created the keys a different way first.
