### ISSUE TITLE
tpm2_certify: sign key with auth

### ISSUE THREAD

**Issue by ptsolakos** [tpm2-software/tpm2-tools#3082]
Hi,

I am trying to run the tpm2_certify command when the sign key has a non empty auth value. I am using the example script from the documentation of the tpm2_certify with the only addition that the sign key has an auth value as follows:

```
tpm2_createprimary -Q -C e -g sha256 -G rsa -c primary.ctx
tpm2_create -Q -g sha256 -G rsa -u certify.pub -r certify.priv -C primary.ctx -p certifypass
tpm2_load -Q -C primary.ctx -u certify.pub -r certify.priv -n certify.name -c certify.ctx
tpm2_certify -Q -c primary.ctx -C certify.ctx -g sha256 -o attest.out -s sig.out -P certifypass
```
and I receive the error:

`ERROR: Eys_Certify(0x98E) - tpm:session(1):the authorization HMAC check failed and DA counter incremented`

What am I missing here?

**Comment by idesai** [comment]
`tpm2_certify -Q -c primary.ctx -C certify.ctx -g sha256 -o attest.out -s sig.out -p certifypass`

**Comment by ptsolakos** [comment]
@idesai Thank you very much for your help.
Your change solves the issue but it confuses me when I read the documentation of the tpm2_certify command:

- **-c, --certifiedkey-context=** The object to be certified.
-  **-C, --signingkey-context=** The key used to sign the attestation structure.
-  **-p, --certifiedkey-auth=** The authorization value provided for the object specified with -c.
- **-P, --signingkey-auth=** The authorization value for the signing key specified with -C.

In your change, we use **-p** for the authorization value for the signing key specified with **-C**, which is  the opposite of what the documentation specifies.

**Comment by idesai** [comment]
True that. We have a documentation bug that needs fixing.

PS: I concur that the capitalization of the option is not intuitive but we cannot change that typo in code to avoid breaking scripts that may already be using the tool. And so we'll fix the documentation instead.

**Comment by ptsolakos** [comment]
Thank you for letting me know. I understand your concern about breaking existing scripts.

On the same topic, I am experimenting with the case where the object to be certified needs to be authorized with a policy. For this reason I am setting the adminwithpolicy attribute of the object, creating the object with a policy and satisfying the policy when trying to certify it. Please see script below:

```
tpm2_startauthsession -S session.ctx
tpm2_policysecret -S session.ctx -c e -L secret.policy
tpm2_flushcontext session.ctx

tpm2_createprimary -C e -g sha256 -G rsa -c primary.ctx -L secret.policy -a 'fixedtpm|fixedparent|sensitivedataorigin|userwithauth|adminwithpolicy|restricted|decrypt'
tpm2_create -g sha256 -G rsa -u certify.pub -r certify.priv -C primary.ctx
tpm2_load -C primary.ctx -u certify.pub -r certify.priv -n certify.name -c certify.ctx

tpm2_startauthsession -S session.ctx --policy-session
tpm2_policysecret -S session.ctx -c e
tpm2_certify -c primary.ctx -C certify.ctx -g sha256 -o attest.out -s sig.out -P session:session.ctx
tpm2_flushcontext session.ctx
```

This script fails with a policy check failed error, although both the creation and the satisfying policies are the same. Can you please elaborate on that?

```
WARNING:esys:src/tss2-esys/api/Esys_Certify.c:331:Esys_Certify_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Certify.c:107:Esys_Certify() Esys Finish ErrorCode (0x0000099d)
ERROR: Eys_Certify(0x99D) - tpm:session(1):a policy check failed
ERROR: Unable to run tpm2_certify
```

**Comment by idesai** [comment]
It needs the secret.policy be included in tpm2_create with -L and also in tpm2_certify use -p instead.

**Comment by idesai** [comment]
> The policy branch should include the command code for TPM2_CC_Certify
> 
> ```shell
> tpm2_startauthsession -S session.ctx
> tpm2_policycommandcode -S session.ctx TPM2_CC_Certify
> tpm2_policysecret -S session.ctx -c e -L secret.policy
> tpm2_flushcontext session.ctx
> ```

@ptsolakos did this change work for you?

**Comment by ptsolakos** [comment]
> > The policy branch should include the command code for TPM2_CC_Certify
> > ```shell
> > tpm2_startauthsession -S session.ctx
> > tpm2_policycommandcode -S session.ctx TPM2_CC_Certify
> > tpm2_policysecret -S session.ctx -c e -L secret.policy
> > tpm2_flushcontext session.ctx
> > ```
> 
> @ptsolakos did this change work for you?

@idesai Yes, with this addition it worked! Thanks again for your help and sorry for my late response. I am partially unavailable this month.

However, it is not clear to me why I have to explicitly constrain the policy to the certify command. I thought that any policy will work as long as it matches the policy at the time of the object creation.
