### ISSUE TITLE
Owner creation of LAK certificate based on IAK certificate

### ISSUE THREAD

**Issue by UHeinitz** [tpm2-software/tpm2-tools#3095]
Hi,
I am trying to reconstruct the whole process of DevID enrollment according section 5.7 of specification [TPM 2.0 Keys for Device Identity and Attestation](https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf). The credential activation process to create and install IAK and IDevID keys and certificates I could reproduce. Now I'm going to examine the administrator part for LAK and LDevID keys and certificates.

I don't understand how "the LAK can be remotely verified by the owner PKI CA to be in the same TPM as the IAK" (Box 3 comment). 
Can this be done using a standard owner PKI CA?
What does this sentence mean: "This use case uses the OEM CA assertion that the IAK belongs to a specific platform (identified in the IAK Certificate) to prove that the new LAK key is held by the same TPM and thus represents the same platform." (Box 3 comment)?
Section 6.3.2 of [TPM 2.0 Keys for Device Identity and Attestation](https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf) describes that the IAK is used to certify the new LAK as it is used to certify the IDevID. This would mean in my understanding that the owner PKI CA would be no standard CA. In section 6.4.2 (Owner Creation of an LDevID Certificate based on an OEM installed IAK Certificate) the following is demanded: "The OEM needs to provide a software feature for the device administrator or owner to securely create, validate and sign a TCG-CSR-LDEVID ..."

These declarations either assume a very close collaboration of device manufacturer and device owner (by OEM provided software feature) or a very sophisticated handling of supplied devices by the device owner (with a non-standard CA). 
Neither one way nor the other match my idea of an easy to use handling that is suitable for a device owner.

Did I overlook a part in TCG documentation where this proceeding is described?
Is there a 'simple' solution for device owner to create and certificate storage keys under owner hierarchy (LAK and LDevID) by himself?
Would it be a good solution to create and certify LAK and LDevID by device manufacturer?
Or did I misinterpret something completely?

Thank you in advance for your answer.

**Comment by idesai** [comment]
@nedmsmith can you please suggest? - Thanks!

**Comment by nedmsmith** [comment]
In step 2 of the procedure 6.3.2 indicates the new LAK is created and attested using TPM2_Certify where the attestation key is the IAK. The signature means that the TPM verified the LAK existed within the same protected capability (aka TPM) that also protects the IAK. 

The CSR (step 3) should include the payload from step 2 so that the Local CA can verify that the LAK is protected by the same TPM that protects the IAK. The IAK signature over the LAK is used to verify the TPM is authentic wrt its mfg'r. 

The TPM2_Certify should be exposed via TSS to allow application code to specify which key should be used to sign and which key is to be signed. 

A typical CSR usually has extensions / extensibility that allows the TPM2_Certify payload to be included in the CSR (which is then signed by the LAK). Depending on the PKI software used, there may or may not be support for extending the CSR.

**Comment by UHeinitz** [comment]
@nedmsmith Thank you for your answer. Short summary in my words:
The software/ application used by the device owner uses TPM2_Certify to certify the new LAK and puts the resulting structures into the TCG-CSR-LDEVID. The TCG-CSR-LDEVID has to be build according section 13.2. The OEM may support the device owner by providing the needed function call TPM2_Certify in a more simplified API.
A CSR can gather the needed structs (TPM2B_ATTEST, TPMT_SIGNATURE) in extensions and a standard local CA (that supports extensions) should be able to handle them.
Did I understand it correctly?

**Comment by nedmsmith** [comment]
Yes. That sounds right.

**Comment by UHeinitz** [comment]
Thank you again for help.

**Comment by rabipaikaray** [comment]
> Hi, I am trying to reconstruct the whole process of DevID enrollment according section 5.7 of specification [TPM 2.0 Keys for Device Identity and Attestation](https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf). The credential activation process to create and install IAK and IDevID keys and certificates I could reproduce. Now I'm going to examine the administrator part for LAK and LDevID keys and certificates.
> 
> I don't understand how "the LAK can be remotely verified by the owner PKI CA to be in the same TPM as the IAK" (Box 3 comment). Can this be done using a standard owner PKI CA? What does this sentence mean: "This use case uses the OEM CA assertion that the IAK belongs to a specific platform (identified in the IAK Certificate) to prove that the new LAK key is held by the same TPM and thus represents the same platform." (Box 3 comment)? Section 6.3.2 of [TPM 2.0 Keys for Device Identity and Attestation](https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf) describes that the IAK is used to certify the new LAK as it is used to certify the IDevID. This would mean in my understanding that the owner PKI CA would be no standard CA. In section 6.4.2 (Owner Creation of an LDevID Certificate based on an OEM installed IAK Certificate) the following is demanded: "The OEM needs to provide a software feature for the device administrator or owner to securely create, validate and sign a TCG-CSR-LDEVID ..."
> 
> These declarations either assume a very close collaboration of device manufacturer and device owner (by OEM provided software feature) or a very sophisticated handling of supplied devices by the device owner (with a non-standard CA). Neither one way nor the other match my idea of an easy to use handling that is suitable for a device owner.
> 
> Did I overlook a part in TCG documentation where this proceeding is described? Is there a 'simple' solution for device owner to create and certificate storage keys under owner hierarchy (LAK and LDevID) by himself? Would it be a good solution to create and certify LAK and LDevID by device manufacturer? Or did I misinterpret something completely?
> 
> Thank you in advance for your answer.

Hi ,
I am trying to do the similar exercise for section 6.2.2 IDevID and IAK 
Want to know how to achieve the step 4 .
Is there any tool available for the same?
 
Platform software builds the TCG-CSR-IDEVID structure described in section 13.1 including:
a. Platform Identity Information—the non-TPM device information needed to build the 802.1AR
certificate. This includes the device model and serial number.
b. EK Certificate
c. IAK Public Area (TPMT_PUBLIC structure)
d. IDevID key Public Area (TPMT_PUBLIC structure)
e. IDevID key TPMB_Attest structure with signature
// The TCS-CSR-IDEVID uses Big Endian byte ordering. All sizes are in bytes.
typedef struct TCG_CSR_t
{
uint8_t structVer[4]; // Version 1.0 = 0x01000100
uint8_t contents[4]; // Size of csrContents
uint8_t sigSz[4]; // Size, in bytes, of signature
TCG_IDEVID_CONTENT_t csrContents;
uint8_t signature[0]; // DER encoded signature, including algorithm ID
} TCG_CSR_IDEVID;
typedef struct TCG_IDEVID_CONTENT_t
{
uint8_t structVer[4]; // Version 1.0 = 0x00000100
uint8_t hashAlgoId[4]; // TCG algorithm identifier for CSR hash
uint8_t hashSz[4]; // Size, in bytes, of hash used
// Hash of all that follows is placed here
uint8_t prodModelSz[4]; // Size of unterminated product model string
uint8_t prodSerialSz[4];// Size of unterminated product serial number string
uint8_t prodCaDataSz[4];// Size of CA-specific required data structure
uint8_t ekCertSZ[4]; // TPM EK cert size
uint8_t attestPubSZ[4]; // Attestation key public size
uint8_t atCreateTktSZ[4]; // TPM2_CertifyCreation ticket size
uint8_t atCertifyInfoSZ[4]; // TPM2_Certify info size
uint8_t atCertifyInfoSignatureSZ[4]; // TPM2_CertifyInfo Signature size
uint8_t signingPubSZ[4]; // Signing key public size
uint8_t sgnCertifyInfoSZ[4]; // TPM2_Certify info size
uint8_t sgnCertifyInfoSignatureSZ[4];// TPM2_CertifyInfo Signature size
uint8_t padSz[4];
// Payload bytes begin here.
// All payloads are included as byte arrays (no delimiters)
// Payload is followed by padSz bytes of random data here to make
// the structure size a multiple of 16 bytes.
// prodModel[]
// prodSerial[]
// prodCaData[]
// ekCert[]
// attestPub[]
// atCreateTkt[]
// atCertifyInfo[]
// atCertifyInfoSig[]
// signingPub[]
// sgnCertifyInfo[]
// sgnCertifyInfoSig[]
// pad[]
} TCG_CSR_IDEVID_CONTENT;

In step 7
How the verification is done? Are there any command to verify those from this CSR which is generated in step 4?
Does openssl understands this to generate the certificate ?

@UHeinitz  If you have done similar exercises for LDevID could you share me some pointers here?

Thanks in advance
