### ISSUE TITLE
Is it secured on my host device, when the obj.priv created by tpm_load whit "-r"?

### ISSUE THREAD

**Issue by qq8512852** [tpm2-software/tpm2-tools#3104]
tpm2_load -H 0x81010009 -u obj.pub -r obj.priv -C load.context
base on the instruction:
 "-r, --privfile=PRIVATE_OBJECT_DATA_FILE: A file containing the sensitive portion of the object."
So, the obj.priv is  unsecured on my host device, right?

**Comment by williamcroberts** [comment]
obj.priv is secured by the TPM. You can only view that key if you have the key it was wrapped with inside of the TPM.

**Comment by qq8512852** [comment]
> obj.priv is secured by the TPM. You can only view that key if you have the key it was wrapped with inside of the TPM.

Thanks. 
Although the obj.priv is private and exists on my host device. 
Because the wrapped key was in the TPM. So it was saved.
