### ISSUE TITLE
How to Enforce a Certain Way to Store Auth Values?

### ISSUE THREAD

**Issue by stickybits123** [tpm2-software/tpm2-tools#3116]
I cannot locate information in the TCG specs that tells me how exactly passwords in the TPM are stored. How is the TPM Owner Password stored? How is the password for NV RAM Indices stored? 

My assumption is they are stored as hashes. But I do not see any switches for TPM2_changeauth that allows me to dictate what algorithm is used to hash the password. Same for TPM2_nvdefine. Is there a way I can tell the TPM to store passwords in the clear? Or can I dictate SHA1, or SHA256? When I pass an auth credential to the TPM, does it hash my provided password?

**Comment by williamcroberts** [comment]
AuthValue is part of the `TPM2B_SENSITIVE` structure that is passed during a create call. That `TPM2B_SENSITIVE` is wrapped following the procedure described in Object Protections Section 22 of  https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part1_Architecture_pub.pdf. The return of create, the `TPM2B_PRIVATE`, is the wrapped and populated TPM2B_SENSITIVE that was initially sent. I think the easiest way to see this in action is with the Python Wrapper where we implemented wrap which performs the "Object Protections". This is used to wrap the object prior to a call like tpm2_import, see the python code https://github.com/tpm2-software/tpm2-pytss/blob/master/src/tpm2_pytss/utils.py#L74 and uses here: https://github.com/tpm2-software/tpm2-pytss/blob/master/test/test_utils.py#L246

**Comment by stickybits123** [comment]
Thanks, William. This was very helpful. I see that there are methods for wrapping credentials used during create commands, as well as secure methods to distribute TPM credentials such as with the activatecredential and createcredential commands. 

My question relates to commands such as this:
tpm2_nvdefine -x 0x1500015 -a 0x40000001 -s 32 \
  -t "policyread|policywrite|authread|authwrite|ownerwrite|ownerread" \
  -I "index" -P "owner"

in this case, does the TPM perform any hashing on the -I and -P credentials provided? Are these passwords stored as hashes inside the TPM? 

when i run: tpm2_nvread -Q -x 0x1500015 -a 0x1500015 -P "index" does the TPM hash my credential and compare it to a hash stored in the TPM? 

Thank you for your help.

**Comment by williamcroberts** [comment]
AFAICT from reading the code, no, it's just straight constant time comparison.

I did a test to dump the NVChip file from the simulator:
```bash
tpm2 nvdefine -pbill
nv-index: 0x1000000

grep bill NVChip 
Binary file NVChip matches

strings NVChip 
Qi{9
)u\(
rp\|
t^jsq
0.0a
P!,_
o$N!%
DRBG
\EMh
\EMh
bill
```
We can see my password in the NVChip file.

It makes sense, if you can read or access the NV Chip you can read/write whatever you want without needing passwords.

If you want to protect your password in transit from the Application to the TPM you can use encrypted sessions or HMAC sessions.

**Comment by stickybits123** [comment]
That looks convincing. Would you mind telling me how you did that? What simulation are you using? The simulation environment I have access to is VMware workstation. Can i read out the contents like that in the actual hardware? 

For the code, what code are you looking at? Ide like to take a look as well.
