### ISSUE TITLE
IDEVID enrollment according to TCG spec TPM 2.0 Keys for Device Identity and Attestation

### ISSUE THREAD

**Issue by rabipaikaray** [tpm2-software/tpm2-tools#3123]
Hi ,
I was trying to do  exercise for section 6.2.2 IDevID and IAK .
IDevID enrollment and creation of IDevID and IAK certificate in one pass.

I could see a similar discussion in 
https://github.com/tpm2-software/tpm2-tools/issues/3095 

Want to know about step 4  
[TPM 2.0 Keys for Device Identity and Attestation](https://trustedcomputinggroup.org/wp-content/uploads/TPM-2p0-Keys-for-Device-Identity-and-Attestation_v1_r12_pub10082021.pdf). 
Pasted below the extract from the document.
Is there anyone has done any exercise for the same?

4. Platform software builds the TCG-CSR-IDEVID structure described in section 13.1 including:
a. Platform Identity Information—the non-TPM device information needed to build the 802.1AR
certificate. This includes the device model and serial number.
b. EK Certificate
c. IAK Public Area (TPMT_PUBLIC structure)
d. IDevID key Public Area (TPMT_PUBLIC structure)
e. IDevID key TPMB_Attest structure with signature

// The TCS-CSR-IDEVID uses Big Endian byte ordering. All sizes are in bytes.
typedef struct TCG_CSR_t
{
uint8_t structVer[4]; // Version 1.0 = 0x01000100
uint8_t contents[4]; // Size of csrContents
uint8_t sigSz[4]; // Size, in bytes, of signature
TCG_IDEVID_CONTENT_t csrContents;
uint8_t signature[0]; // DER encoded signature, including algorithm ID
} TCG_CSR_IDEVID;
typedef struct TCG_IDEVID_CONTENT_t
{
uint8_t structVer[4]; // Version 1.0 = 0x00000100
uint8_t hashAlgoId[4]; // TCG algorithm identifier for CSR hash
uint8_t hashSz[4]; // Size, in bytes, of hash used
// Hash of all that follows is placed here
uint8_t prodModelSz[4]; // Size of unterminated product model string
uint8_t prodSerialSz[4];// Size of unterminated product serial number string
uint8_t prodCaDataSz[4];// Size of CA-specific required data structure
uint8_t ekCertSZ[4]; // TPM EK cert size
uint8_t attestPubSZ[4]; // Attestation key public size
uint8_t atCreateTktSZ[4]; // TPM2_CertifyCreation ticket size
uint8_t atCertifyInfoSZ[4]; // TPM2_Certify info size
uint8_t atCertifyInfoSignatureSZ[4]; // TPM2_CertifyInfo Signature size
uint8_t signingPubSZ[4]; // Signing key public size
uint8_t sgnCertifyInfoSZ[4]; // TPM2_Certify info size
uint8_t sgnCertifyInfoSignatureSZ[4];// TPM2_CertifyInfo Signature size
uint8_t padSz[4];
// Payload bytes begin here.
// All payloads are included as byte arrays (no delimiters)
// Payload is followed by padSz bytes of random data here to make
// the structure size a multiple of 16 bytes.
// prodModel[]
// prodSerial[]
// prodCaData[]
// ekCert[]
// attestPub[]
// atCreateTkt[]
// atCertifyInfo[]
// atCertifyInfoSig[]
// signingPub[]
// sgnCertifyInfo[]
// sgnCertifyInfoSig[]
// pad[]
} TCG_CSR_IDEVID_CONTENT;

**Comment by gidde8** [comment]
Is this issue resolved ? We have similar requirement.
