### ISSUE TITLE
Create EK from template

### ISSUE THREAD

**Issue by gc-zoetis** [tpm2-software/tpm2-tools#3129]
Hi ,
As per project requirement, i wanted to create EK key with some default template using tpm2_tool command.
But there is no information about how should we pass that argument.
Link given documents broke.

Template want to used mentioned sample code in C
```
static TPM2B_PUBLIC* GetEkTemplate ()
    {
        static TPM2B_PUBLIC EkTemplate = { 0,   // size will be computed during marshaling
        {
            TPM_ALG_RSA,                    // TPMI_ALG_PUBLIC      type
            TPM_ALG_SHA256,                 // TPMI_ALG_HASH        nameAlg
            { 0 },                          // TPMA_OBJECT  objectAttributes (set below)
            {32,
            { 0x83, 0x71, 0x97, 0x67, 0x44, 0x84, 0xb3, 0xf8,
            0x1a, 0x90, 0xcc, 0x8d, 0x46, 0xa5, 0xd7, 0x24,
            0xfd, 0x52, 0xd7, 0x6e, 0x06, 0x52, 0x0b, 0x64,
            0xf2, 0xa1, 0xda, 0x1b, 0x33, 0x14, 0x69, 0xaa }
            },                              // TPM2B_DIGEST         authPolicy
            { 0 },                          // TPMU_PUBLIC_PARMS    parameters (set below)
            { 0 }                           // TPMU_PUBLIC_ID       unique
        } };
        EkTemplate.publicArea.objectAttributes = ToTpmaObject(
            Restricted | Decrypt | FixedTPM | FixedParent | AdminWithPolicy | SensitiveDataOrigin);
        EkTemplate.publicArea.parameters.rsaDetail = RsaStorageParams;
        return &EkTemplate;
    }
```

command that i want to use
```
tpm2_createek -c 0x81010001 -G rsa -u ek.pub -t {template value}
```

Please help out to create the EK from template

**Comment by idesai** [comment]
Use [tpm2_createprimary](https://tpm2-tools.readthedocs.io/en/latest/man/tpm2_createprimary.1/l) instead.

**Comment by hommeabeil** [comment]
Hi I have the same question and I don't understand what `tpm2_createprimary` make this easier ? The struct show above is exactly the same as describe Template L-1: RSA 2048 (Storage) [here](https://trustedcomputinggroup.org/wp-content/uploads/TCG_IWG_Credential_Profile_EK_V2.1_R13.pdf). What does `--template` take as argument ?

**Comment by williamcroberts** [comment]
> Hi I have the same question and I don't understand what `tpm2_createprimary` make this easier ? The struct show above is exactly the same as describe Template L-1: RSA 2048 (Storage) [here](https://trustedcomputinggroup.org/wp-content/uploads/TCG_IWG_Credential_Profile_EK_V2.1_R13.pdf). What does `--template` take as argument ?

Per the man-page, the --template options takes a TPM2B_PUBLIC. This is typically read from an NV Index, but you could generate a TPM2B_PUBLIC and serialize it and use that here as well.

**Comment by hommeabeil** [comment]
Ok, thanks for your answer, I will try it.

**Comment by hommeabeil** [comment]
Finaly got time to work on this. Here how I create what I need. @gc-zoetis  you are probably trying to connect to the Azure DPS, here how you can generate what you need.

```sh
policies="restricted|decrypt|fixedtpm|fixedparent|sensitivedataorigin|adminwithpolicy"

# p.bin contains the following content in binary
# this represent the policy
#
# 0x83, 0x71, 0x97, 0x67, 0x44, 0x84, 0xb3, 0xf8, 0x1a, 0x90, 0xcc, 0x8d, 0x46, 0xa5, 0xd7,
# 0x24, 0xfd, 0x52, 0xd7, 0x6e, 0x06, 0x52, 0x0b, 0x64, 0xf2, 0xa1, 0xda, 0x1b, 0x33, 0x14,
# 0x69, 0xaa

tpm2_createprimary  --hierarchy e -g sha256 -G rsa2048:null:aes128cfb -a "${policies}" -c prim.ctx -L p.bin
tpm2_readpublic -c prim.ctx -o key.pub
base64 -w0 key.pub
```
