### ISSUE TITLE
Whether the encryption and decryption process is in or outside the TPM?

### ISSUE THREAD

**Issue by qq8512852** [tpm2-software/tpm2-tools#3130]
Dear TPM team,
About the example which link is [https://github.com/tpm2-software/tpm2-tools/blob/3.2.2-RC0/test/system/test_tpm2_rsadecrypt.sh] . 
**I have a little comfused that whether the encryption and decryption process are in or outside the TPM?**
For example:
when we input some plaint data as "123456" to TPM , cmd like this : "tpm2_rsaencrypt -Q -c $file_rsaencrypt_key_ctx -o $file_rsa_en_output_data < "123456" ".
**where to implement the plaint data  to excrypted data?**
### I'm not sure that the step like this:
**1. load key from TPM to CPU RAM**
**2. encrypted plaint data wiht key in the CPU RAM**
**3. output the ciphertext**
### or the second kind of process like this :
**1. input plain data to TPM from CPU**
**2. encrypted plaint data in TPM with key which in TPM**
**3. output ciphertext to CPU from TPM**

Could you please kindly help me clarify the question? Thanks.

**Comment by idesai** [comment]
The particular command tpm2_rsadecrypt does the decryption within the TPM. Albeit, this would be slow for two reasons. The key is asymmetric and also TPMs typically do not have a fast crypto engine. If you have large amounts of data to be encrypted/ decrypted, I'd suggest sealing a symmetric key to the TPM using tpm2_create. You can then unseal the key off the TPM using tpm2_unseal and use the key to encrypt/ decrypt using the main cpu core on your system.

**Comment by williamcroberts** [comment]
> > The particular command tpm2_rsadecrypt does the decryption within the TPM. Albeit, this would be slow for two reasons. The key is asymmetric and also TPMs typically do not have a fast crypto engine. If you have large amounts of data to be encrypted/ decrypted, I'd suggest sealing a symmetric key to the TPM using tpm2_create. You can then unseal the key off the TPM using tpm2_unseal and use the key to encrypt/ decrypt using the main cpu core on your system.
> 
> Thank you for your response. Yeah, as you said when I implement secure storage policy, the method be used. First create the AES key , then seal it to the TPM. When encrypting plaint text, call the seal function, and the aes key will be taken from the TPM for encryption. Similarly, when unseal is called, the aes key is taken from the TPM for decryption. 

> Seal stores that key to the TPM, from there to get the key you call unseal. Once you have the key you perform encryption and decryption with the key without involving the TPM further.

> **But I am afraid that is there a potential risk? Is there a possibility that our AES key will be stolen when it is exposed to the TPM（because CPU core get the AES key）. I think if the encryption and decryption process can be completed within TPM, it will be safe.**

Maybe. What's your threat model? If someone gets that key then:
1. They can see the bus
2. They can see your process/kernel memory

In either case they can get the plaintext. And in some instances of 1, and all instances of 2, know how to access that key even if theirs a passphrase on it.

To protect against 1 you can use **verified** encrypted sessions. To protect against attack 2 you could use some type of enclave/tee environment. Coupled with encrypted sessions is a powerful method to protect your assets.

The TPM is not really meant for bulk symmetric encryption. The reason symmetric keys are sealed to the TPM and released to the host is:
1. Not all TPMs support the symmetric encryption interface (most don't)
2. Speed, TPMs are slow
3. Some hard drive controllers take the key directly
4. Without disk storage, ie decryting a hard drive, their needs to be a protected storage place for a disk key.

**Comment by qq8512852** [comment]
> > > The particular command tpm2_rsadecrypt does the decryption within the TPM. Albeit, this would be slow for two reasons. The key is asymmetric and also TPMs typically do not have a fast crypto engine. If you have large amounts of data to be encrypted/ decrypted, I'd suggest sealing a symmetric key to the TPM using tpm2_create. You can then unseal the key off the TPM using tpm2_unseal and use the key to encrypt/ decrypt using the main cpu core on your system.
> > 
> > 
> > Thank you for your response. Yeah, as you said when I implement secure storage policy, the method be used. First create the AES key , then seal it to the TPM. When encrypting plaint text, call the seal function, and the aes key will be taken from the TPM for encryption. Similarly, when unseal is called, the aes key is taken from the TPM for decryption.
> 
> Seal stores that key to the TPM, from there to get the key you call unseal. Once you have the key you perform encryption and decryption with the key without involving the TPM further.
> 
> > **But I am afraid that is there a potential risk? Is there a possibility that our AES key will be stolen when it is exposed to the TPM（because CPU core get the AES key）. I think if the encryption and decryption process can be completed within TPM, it will be safe.**
> 
> Maybe. What's your threat model? If someone gets that key then:
> 
> 1. They can see the bus
> 2. They can see your process/kernel memory
> 
> In either case they can get the plaintext. And in some instances of 1, and all instances of 2, know how to access that key even if theirs a passphrase on it.
> 
> To protect against 1 you can use **verified** encrypted sessions. To protect against attack 2 you could use some type of enclave/tee environment. Coupled with encrypted sessions is a powerful method to protect your assets.
> 
> The TPM is not really meant for bulk symmetric encryption. The reason symmetric keys are sealed to the TPM and released to the host is:
> 
> 1. Not all TPMs support the symmetric encryption interface (most don't)
> 2. Speed, TPMs are slow
> 3. Some hard drive controllers take the key directly
> 4. Without disk storage, ie decryting a hard drive, their needs to be a protected storage place for a disk key.

I can't agree more.
Maybe security is relative, and higher level security will increase the cost, so you only need to make choices according to the scenario.
Much appreciate for your help to resolve my question.
