### ISSUE TITLE
tss2_createnv: authorization failure

### ISSUE THREAD

**Issue by fansari** [tpm2-software/tpm2-tools#3136]
I am testing an example like this:

```
tss2_createnv --path=/nv/Owner/mynvtest --policyPath=/policy/nvtest --size=64 --authValue=''
```

This gives me this output:

```
WARNING:esys:src/tss2-esys/api/Esys_NV_DefineSpace.c:344:Esys_NV_DefineSpace_Finish() Received TPM Error
ERROR:fapi:src/tss2-fapi/api/Fapi_CreateNv.c:435:Fapi_CreateNv_Finish() ErrorCode (0x000009a2) FAPI CreateWithTemplate_Finish
ERROR:fapi:src/tss2-fapi/api/Fapi_CreateNv.c:121:Fapi_CreateNv() ErrorCode (0x000009a2) NV_CreateWithTemplate
Fapi_CreateNv(0x9A2) - tpm:session(1):authorization failure without DA implications
```

I have set passwords for the TPM:

```
TPM2_PT_PERMANENT:
  ownerAuthSet:              1
  endorsementAuthSet:        1
  lockoutAuthSet:            1
  reserved1:                 0
  disableClear:              0
  inLockout:                 0
  tpmGeneratedEPS:           0
  reserved2:                 0
```

I did not find a parameter for tss2_createnv to enter my password.

How can I authorize for tss2_createnv?

**Comment by williamcroberts** [comment]
Option `--authValue`

**Comment by fansari** [comment]
I have cleared the TPM with my BIOS.

This time I did not set the passwords with tsshierarchychangeauth but used the options for tss2_provision instead.

When I now run tss2_createenv I am prompted for the owner password:

```
Authorize HS "Owner Hierarchy":
```

**Comment by williamcroberts** [comment]
Oh yeah `--authValue` is for the nv object. I was looking at the code and it should just prompt, as it's doing now. I wonder why it didn't prompt.
