### ISSUE TITLE
tpm2_ptool init fails after passwords were set

### ISSUE THREAD

**Issue by fansari** [tpm2-software/tpm2-tools#3138]
tpm2_ptool runs tpm2_createprimary. How can I handover my owner password?

Without this the command fails. I did not see any option to give the password to tpm2_ptool. It also does not prompt for it on its own.

```
[fansari@bat keys]$ tpm2_ptool init
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/commandlets_store.py", line 100, in __call__
    pobj_ctx = create_primary(tpm2, hierarchyauth, pobjauth, transient_parent)
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/utils.py", line 430, in create_primary
    return tpm2.createprimary(hierarchyauth, pobjauth, alg=alg, attrs=attrs)
  File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/tpm2.py", line 86, in createprimary
    raise RuntimeError("Could not execute tpm2_createprimary: %s" %
RuntimeError: Could not execute tpm2_createprimary: b'WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:400:Esys_CreatePrimary_Finish() Received TPM Error \nERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x000009a2) \nERROR: Esys_CreatePrimary(0x9A2) - tpm:session(1):authorization failure without DA implications\nERROR: Unable to run tpm2_createprimary\n'
Could not execute tpm2_createprimary: b'WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:400:Esys_CreatePrimary_Finish() Received TPM Error \nERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x000009a2) \nERROR: Esys_CreatePrimary(0x9A2) - tpm:session(1):authorization failure without DA implications\nERROR: Unable to run tpm2_createprimary\n'
```

Is there a generic way to work with passwords? I have read about tpm2_startauthsession but I am unsure whether this is the right way.

**Comment by williamcroberts** [comment]
> tpm2_ptool runs tpm2_createprimary. How can I handover my owner password?
> 
> Without this the command fails. I did not see and option to give the password to tpm2_ptool. It also does not prompt for it on its own.
> 
> ```
> [fansari@bat keys]$ tpm2_ptool init
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/commandlets_store.py", line 100, in __call__
>     pobj_ctx = create_primary(tpm2, hierarchyauth, pobjauth, transient_parent)
>   File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/utils.py", line 430, in create_primary
>     return tpm2.createprimary(hierarchyauth, pobjauth, alg=alg, attrs=attrs)
>   File "/usr/lib/python3.10/site-packages/tpm2_pkcs11/tpm2.py", line 86, in createprimary
>     raise RuntimeError("Could not execute tpm2_createprimary: %s" %
> RuntimeError: Could not execute tpm2_createprimary: b'WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:400:Esys_CreatePrimary_Finish() Received TPM Error \nERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x000009a2) \nERROR: Esys_CreatePrimary(0x9A2) - tpm:session(1):authorization failure without DA implications\nERROR: Unable to run tpm2_createprimary\n'
> Could not execute tpm2_createprimary: b'WARNING:esys:src/tss2-esys/api/Esys_CreatePrimary.c:400:Esys_CreatePrimary_Finish() Received TPM Error \nERROR:esys:src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x000009a2) \nERROR: Esys_CreatePrimary(0x9A2) - tpm:session(1):authorization failure without DA implications\nERROR: Unable to run tpm2_createprimary\n'
> ```
```bash
$ tpm2_ptool init --help
usage: tpm2_ptool.py init [-h] [--hierarchy-auth HIERARCHY_AUTH] [--primary-auth PRIMARY_AUTH] [--primary-handle [PRIMARY_HANDLE] |
                          --transient-parent [{tpm2-tools-default,tpm2-tools-ecc-default,tss2-engine-key}]] [--path PATH]

optional arguments:
  -h, --help            show this help message and exit

init options:
  --hierarchy-auth HIERARCHY_AUTH
                        The authorization password for adding a primary object to the hierarchy.
```

> 
> Is there a generic way to work with passwords? I have read about tpm2_startauthsession but I am unsure whether this is the right way.

That's completely different. That's for doing policy stuff and some other advanced features.

**Comment by fansari** [comment]
working!
