### ISSUE TITLE
Encryption Using tss2_ Tools

### ISSUE THREAD

**Issue by dsburns** [tpm2-software/tpm2-tools#3142]
I want to create a key pair for encrypting secrets on a Linux device.  The idea is to encrypt the secrets using the public key during device provisioning and decrypt using the private key each time the device boots.  Encryption and decryption are performed outside the TPM for performance reasons.  I want to seal the private key to the TPM so it can be stored on disk as an encrypted blob.   See example below and error when attempting to seal the private key.

```
# Create keys to encrypting/decrypting secrets
openssl genrsa -out key.priv 2048

# generate corresponding public key
openssl rsa -in  key.priv -pubout -out key.pub

# Encrypt secrets using public key
openssl rsautl -encrypt -inkey key.pub -pubin -in my_secret.txt -out my_secret.cipher

# Seal the private key with the TPM
tss2_createseal --path=HS/SRK/sealed_key --authValue= --type="noDa" --data="key.priv"
```

The tss2_createseal command issues the following error:
```
ERROR:fapi:src/tss2-fapi/fapi_util.c:3137:ifapi_key_create_prepare_sensitive() Data too big or equal zero. ErrorCode (0x0006000b) 
ERROR:fapi:src/tss2-fapi/api/Fapi_CreateSeal.c:198:Fapi_CreateSeal_Async() Key create. ErrorCode (0x0006000b) 
ERROR:fapi:src/tss2-fapi/api/Fapi_CreateSeal.c:106:Fapi_CreateSeal() ErrorCode (0x0006000b) CreateSeal 
Fapi_CreateSeal(0x6000B) - fapi:A parameter has a bad value
```

## Versions
* OS: Ubuntu 20.04
* tpm2-tools: 5.3-rc1
* tpm2-tss: SHA 4edce679ae508bedb7b88908198d1007a266fef6

**Comment by idesai** [comment]
The size of data sealed is limited to 128 bytes. Can you use a symmetric key instead? The other option is to import the private key into the TPM.
