### ISSUE TITLE
Tpm2_eventlog not initializing PCR[0] correctly

### ISSUE THREAD

**Issue by vrpate2** [tpm2-software/tpm2-tools#3146]
For PCR[0], the default initial condition may be all bits CLEAR, all bits SET, the locality at which TPM2_Startup() was received, or an indicator that the first measurement came from an H-CRTM. Refer to Hardware Core Root of Trust Measurement (H-CRTM) Event Sequence in TPM Library specification part 1.

**Comment by Max-ad-Wu** [comment]
Hi,
I saw it. May I know is it an issue and can it be fixed in this application?
Thanks
