### ISSUE TITLE
tpm2-encodeobject should allow creating password protected tss2 pem files

### ISSUE THREAD

**Issue by webczat** [tpm2-software/tpm2-tools#3152]
In case of the tpm2-openssl provider, i can generate a key in PEM format. if I specify the user auth, trying to use the key will prompt me for password, but I know that is a flag inside of a PEM file itself which triggers that behavior.
tpm2-encodeobject allows me to create keys with settings I cannot set using the openssl providers and then convert the tpm2 private and public key blobs into that PEM format, however it doesn't allow creating a pem file which prompts for passphrase. It would be an useful addition.

**Comment by williamcroberts** [comment]
It appears its a bug. TRhe current authValue boolean flag is triggered off the parent objects password specifived via the `-P` option instead of a flag indicating the child object, ie the key in use, needs a password.

**Comment by webczat** [comment]
oh so it actually is triggered, but badly? that's fair. my primary key is passwordless, and it's done cos I have owner password set and I don't want loading keys to require passwords, say, for disk encryption scenarios or using tpm  for secureboot private keys, which was the usage where I need openssl. not sure what are the cons of not setting auth/policy on primary key, as owner password allows some more administrative commands. However I want actual leaf keys to have some security, in this case passwords.

**Comment by williamcroberts** [comment]
> oh so it actually is triggered, but badly? that's fair. my primary key is passwordless, and it's done cos I have owner password set and I don't want loading keys to require passwords, say, for disk encryption scenarios or using tpm for secureboot private keys, which was the usage where I need openssl. not sure what are the cons of not setting auth/policy on primary key, as owner password allows some more administrative commands. However I want actual leaf keys to have some security, in this case passwords.

Yeah the leaf key definitely should have a password. I have a patch forthcoming very soon. As a workaround for now you could create a primary key that matches the one your using and set a password on it and specify it via `-P` in `tpm2_ecodeobject` OR you could hand modify the PEM file and set that flag manually.

**Comment by webczat** [comment]
i didn't know enough about pem files to hand modify, and didn't know that encodeobject command can set this flag at all. What I did yesterday, that is before reporting this issue, was to use the openssl provider to generate these keys, because it can set this flag, it's just not that configurable, for example i cannot make the key sign only, and additionally I cannot provide the user auth password by any means other than... via command line, not even env var. I am not really security sensitive here as my intention is more to play with tpm/secureboot technologies, but this was still concerning. Ofc that needs to be reported to openssl provider, but if there is a command to encode tpm keys into that format, I figured that might be faster to get in.

**Comment by williamcroberts** [comment]
@webczat the issue with OpenSSL not asking for a password is because the boolean flag was not set properly. With my patch that corrects the flag state and it should prompt. Most commands also allow the specification of a password I think as well, it's usually like `-passin` option. However without the flag set in the PEM file I think it just gets ignored.

**Comment by webczat** [comment]
does that patch make it configurable or now all pem files will prompt when created by encodeobject?

**Comment by webczat** [comment]
fair, thank you :)

**Comment by williamcroberts** [comment]
@webczat if you need to modify an existing PEM file, do:

1. Convert it to DER
`openssl asn1parse -dump -inform PEM -in key.pem -out key.der`

2. Modify byte at offset 0x10, 0x01 for True (it has password), 0x00 for False (no password). I just used ghex but also is a little python script attached. Example usage to set a password on a pem file:
```bash
./changepem.py key.der 1
```

3. Convert it back to PEM
```bash

**Comment by webczat** [comment]
i suspected it's something like this. but as there is a patch already and I have set up keys, although not ideally, via openssl provider, I probably won't need to do this. :) thank you!
