### ISSUE TITLE
HMAC algorithm

### ISSUE THREAD

**Issue by hoinmic** [tpm2-software/tpm2-tools#3159]
Hi

I can't explain the following behavior right now. It seems that the TPM2 supports the HMAC algorithm:
```bash
tpm2_getcap algorithms | grep hmac -A 9
hmac:
  value:      0x5
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     0
```

But when I run create (from [HMAC Example](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_hmac.1.md)) it shows that it does not support this:
```bash
tpm2_create -C primary.ctx -G hmac -c hmac.key
WARNING:esys:../tpm2-tss-3.2.0/src/tss2-esys/api/Esys_CreateLoaded.c:368:Esys_CreateLoaded_Finish() Received TPM Error 
ERROR:esys:../tpm2-tss-3.2.0/src/tss2-esys/api/Esys_CreateLoaded.c:129:Esys_CreateLoaded() Esys Finish ErrorCode (0x00000143) 
ERROR: Esys_CreateLoaded(0x143) - tpm:error(2.0): command code not supported
ERROR: Unable to run tpm2_create
```

Can someone possibly help me?

**Comment by williamcroberts** [comment]
Using `-c` option requires the TPM to support TPM2_CreateLoaded command. If you use the `-u` and `-r` option, the typical TPM2_Create command is invoked. Notice the error is that the Command Code is not supported:
`ERROR: Esys_CreateLoaded(0x143) - tpm:error(2.0): command code not supported`.

Drop `-c` option and use `-u key.pub` -r `key.priv` and then pass those to `tpm2_load command`.
`tpm2_load -C <parent used in tpm2_create> -u key.pub -r key.priv -c hmac.key`

**Comment by hoinmic** [comment]
Thank you very much. I was totally looking in the wrong place.
