### ISSUE TITLE
primary key handle not showing up after creating it 

### ISSUE THREAD

**Issue by l-sousa** [tpm2-software/tpm2-tools#3163]
I'm creating a primary key using:
`tpm2_createprimary -C e -p top -G rsa2048 -c primary.ctx`
No errors on the output, all goes ok.

Then when i run:
`tpm2_getcap handles-permanent`
It doesn't output anything... there should be a handle 0x80000000... 

tpm2_getcap properties-variable:

TPM2_PT_PERSISTENT:
  ownerAuthSet:              0
  endorsementAuthSet:        0
  lockoutAuthSet:            0
  reserved1:                 0
  disableClear:              0
  inLockout:                 0
  tpmGeneratedEPS:           0
  reserved2:                 0
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  1
  shEnable:                  1
  ehEnable:                  1
  phEnableNV:                1
  reserved1:                 0
  orderly:                   1
TPM2_PT_HR_NV_INDEX: 0x2
TPM2_PT_HR_LOADED: 0x0
TPM2_PT_HR_LOADED_AVAIL: 0x3
TPM2_PT_HR_ACTIVE: 0x0
TPM2_PT_HR_ACTIVE_AVAIL: 0x40
TPM2_PT_HR_TRANSIENT_AVAIL: 0x4
TPM2_PT_HR_PERSISTENT: 0x0
TPM2_PT_HR_PERSISTENT_AVAIL: 0xF
TPM2_PT_NV_COUNTERS: 0x0
TPM2_PT_NV_COUNTERS_AVAIL: 0xD
TPM2_PT_ALGORITHM_SET: 0x0
TPM2_PT_LOADED_CURVES: 0x2
TPM2_PT_LOCKOUT_COUNTER: 0x0
TPM2_PT_MAX_AUTH_FAIL: 0x20
TPM2_PT_LOCKOUT_INTERVAL: 0x1C20
TPM2_PT_LOCKOUT_RECOVERY: 0x15180
TPM2_PT_NV_WRITE_RECOVERY: 0x0
TPM2_PT_AUDIT_COUNTER_0: 0x0
TPM2_PT_AUDIT_COUNTER_1: 0x0

Any input on why it's not showing the handle? 

Thanks.

**Comment by williamcroberts** [comment]
> I'm creating a primary key using: `tpm2_createprimary -C e -p top -G rsa2048 -c primary.ctx` No errors on the output, all goes ok.
> 
> Then when i run: `tpm2_getcap handles-permanent` It doesn't output anything... there should be a handle 0x80000000...
> 

That's expected. `tpm2_createprimary` creates a transient primary object, if you want it to be persistent and show up in `tpm2_getcap handles-permanent` you need to use 1tpm2_evictcontrol`, like so:

```bash
tpm2 createprimary -c primary.ctx
tpm2 evictcontrol -c primary.ctx 0x81000000
```
Now when you run getcap, you'll see them:
```bash
tpm2 getcap handles-persistent
- 0x81000000
```

Note that you want to look at handles-persistent to see persistent handles. handles-permanent is for permanent handles like the built in hierarchy handles.

**Comment by l-sousa** [comment]
@williamcroberts it worked. I was following a guide that failed to mention that. Sorry for the noobieness :)

**Comment by williamcroberts** [comment]
> @williamcroberts it worked. I was following a guide that failed to mention that. Sorry for the noobieness :)

No worries, is one of our guides out of date?

**Comment by l-sousa** [comment]
> No worries, is one of our guides out of date?
Not at all. It wasn't yours :)
