### ISSUE TITLE
tpm2_create hmac key fails with SLB9670

### ISSUE THREAD

**Issue by GianlucaB** [tpm2-software/tpm2-tools#3171]
Hello,

While testing hmac operations on  SLB9670 by following the procedure explained here 
https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_hmac.1.md#examples 

We faced the following issue creating an hmac key :

    guest@eMMC:~$ tpm2_createprimary -c primary.ctx
    name-alg:
      value: sha256
      raw: 0xb
    attributes:
      value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
      raw: 0x30072
    type:
      value: rsa
      raw: 0x1
    exponent: 65537
    bits: 2048
    scheme:
      value: null
      raw: 0x10
    scheme-halg:
      value: (null)
      raw: 0x0
    sym-alg:
      value: aes
      raw: 0x6
    sym-mode:
      value: cfb
      raw: 0x43
    sym-keybits: 128
    rsa: e42e9e691124a7eb46276186c66af12089c3d2af7a80b7e190f7f2c86e9560872d4ae0de2d3ffa70e404cf1311310e31
    9514272112416b05d4a6ac71e0f23c4d503b465598e383073f37cfe8b8db5f9d7f2e60762566239b50db8158391440c4b47bf
    9801d54f2744ee58bffbd5402354a290fb324b4b5d06e1f8a78779d950899f0292e959c7b86f144d6248ea6d9cb18370cd29d
    3e2f659d6a6b570530b4b6e5b0f7d94162112d1905484a4c60edc948d33f25e22d9451d96fe350c2bfb2cd24dcfcc4c5b5e65
    768efbdbc980a1a6346a21e1dec5838d9fe4bc25c52aeef9d91b374ed11c38028801892e2851af54b2a6d3d015ad39b5d34b4
    a0d37de8b73b
    guest@reliagate-10-14:eMMC:~$ tpm2_create -C primary.ctx -G hmac -c hmac.key
    WARNING:esys:../tpm2-tss-3.0.3/src/tss2-esys/api/Esys_CreateLoaded.c:355:Esys_CreateLoaded_Finish() R
    eceived TPM Error
    ERROR:esys:../tpm2-tss-3.0.3/src/tss2-esys/api/Esys_CreateLoaded.c:129:Esys_CreateLoaded() Esys Finis
    h ErrorCode (0x00000143)
    ERROR: Esys_CreateLoaded(0x143) - tpm:error(2.0): command code not supported
    ERROR: Unable to run tpm2_create

The adopted version of tpm2-tools is 5.2.0.
Despite the suggested version of tpm2-tss for supporting hmac is at least 3.1.0, and the output above reports tpm2-tss-3.0.3 , the result is the same when tpm2-tss v3.1.0 is used .
Any help is appreciated ,
Thanks

**Comment by williamcroberts** [comment]
> Hello,
> 
> While testing hmac operations on SLB9670 by following the procedure explained here https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_hmac.1.md#examples
> 
> We faced the following issue creating an hmac key :
> 
> ```
> guest@eMMC:~$ tpm2_createprimary -c primary.ctx
> name-alg:
>   value: sha256
>   raw: 0xb
> attributes:
>   value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
>   raw: 0x30072
> type:
>   value: rsa
>   raw: 0x1
> exponent: 65537
> bits: 2048
> scheme:
>   value: null
>   raw: 0x10
> scheme-halg:
>   value: (null)
>   raw: 0x0
> sym-alg:
>   value: aes
>   raw: 0x6
> sym-mode:
>   value: cfb
>   raw: 0x43
> sym-keybits: 128
> rsa: e42e9e691124a7eb46276186c66af12089c3d2af7a80b7e190f7f2c86e9560872d4ae0de2d3ffa70e404cf1311310e31
> 9514272112416b05d4a6ac71e0f23c4d503b465598e383073f37cfe8b8db5f9d7f2e60762566239b50db8158391440c4b47bf
> 9801d54f2744ee58bffbd5402354a290fb324b4b5d06e1f8a78779d950899f0292e959c7b86f144d6248ea6d9cb18370cd29d
> 3e2f659d6a6b570530b4b6e5b0f7d94162112d1905484a4c60edc948d33f25e22d9451d96fe350c2bfb2cd24dcfcc4c5b5e65
> 768efbdbc980a1a6346a21e1dec5838d9fe4bc25c52aeef9d91b374ed11c38028801892e2851af54b2a6d3d015ad39b5d34b4
> a0d37de8b73b
> guest@reliagate-10-14:eMMC:~$ tpm2_create -C primary.ctx -G hmac -c hmac.key
> WARNING:esys:../tpm2-tss-3.0.3/src/tss2-esys/api/Esys_CreateLoaded.c:355:Esys_CreateLoaded_Finish() R
> eceived TPM Error
> ERROR:esys:../tpm2-tss-3.0.3/src/tss2-esys/api/Esys_CreateLoaded.c:129:Esys_CreateLoaded() Esys Finis
> h ErrorCode (0x00000143)
> ERROR: Esys_CreateLoaded(0x143) - tpm:error(2.0): command code not supported
> ERROR: Unable to run tpm2_create
> ```
> 
> The adopted version of tpm2-tools is 5.2.0. Despite the suggested version of tpm2-tss for supporting hmac is at least 3.1.0, and the output above reports tpm2-tss-3.0.3 , the result is the same when tpm2-tss v3.1.0 is used . Any help is appreciated , Thanks

Just change you tpm2_create command to not use createloaded and split it into tpm2_create and tpm2_load calls:
```bash
tpm2_create -C primary.ctx -G hmac -u hmac.pub -r hmac.priv 
tpm2_load -C primary.ctx -u hmac.pub -r hmac.priv -c -c hmac.key
```

**Comment by williamcroberts** [comment]
> If I see this correctly from a quick glance at the code, then tpm2_create currently does not run at all with any TPM following spec 1.16, since they do not support TPM2_CreateLoaded.
> 
> We really need to fix this, since we cannot expect all TPMs to be at least 1.38.
> 
> @williamcroberts @idesai What do you think ?

Nothing really needs to change, they just need to not use `-c` on tpm2_create, I gave them the example of using create and load calls.

It's documented in the manpage (below), but we should probably provide a better error message here.
```
       • -c, --key-context=FILE:

         The output file which contains the key context, optional.  The key context is analogous to the context file produced by tpm2_load(1),
         however is generated via a tpm2_createloaded(1) command.  This option can be used to avoid the normal tpm2_create(1) and tpm2_load(1)
         command sequences and do it all in one command, atomically.
```

**Comment by GianlucaB** [comment]
Hi @williamcroberts ,

the sequence you have suggested   ( despite a quite obvious typo that I've fixed, consisting on double occurence of "-c" parameter)  is working fine with SLB9670.

Here follows the output : 

    root@:eMMC:/home/guest# tpm2_createprimary -c primary.ctx
    name-alg:
      value: sha256
      raw: 0xb
    attributes:
      value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
      raw: 0x30072
    type:
      value: rsa
      raw: 0x1
    exponent: 0x0
    bits: 2048
    scheme:
      value: null
      raw: 0x10
    scheme-halg:
      value: (null)
      raw: 0x0
    sym-alg:
      value: aes
      raw: 0x6
    sym-mode:
      value: cfb
      raw: 0x43
    sym-keybits: 128
    rsa: c151436fea85bd45992eed2e2b86b297248e40ca8804fb76db63491ab7c4d93ad50cb4de408df63ed699dafc052339de863f68beec2bf1474d0fe66d80a92590ed411706cfbeec744bf895af518895a446632cf237e60f24f8daa7fab051bf48b89f45e0b7c391fbfc00fca5ded6eb27eb0894bd568f50cfae537e9b89fd5ae1e9b7f3b08223c5008462045fcada1e4872288f0532697661c7f5c8fa49e114d8c7b7ba5882a3a5df3434bac0065c6c7bec06c9782acab8438db39b326aab1906ff101480f8d10c4772e310c6de1488adca82b902bf9c260827caae2f2546ddcdefcd3df935c98f2368d7b09134b27b881a0bbae969feff2901b8e118d2f53ad7

    root@:eMMC:/home/guest# tpm2_create -C primary.ctx -G hmac -u hmac.pub -r hmac.priv 
    name-alg:
      value: sha256
      raw: 0xb
    attributes:
      value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|sign
      raw: 0x40072
    type:
      value: keyedhash
      raw: 0x8
    algorithm: 
      value: hmac
      raw: 0x5
    hash-alg:
      value: sha256
      raw: 0xb
    keyedhash: 24f5adc4775b551340a7a39f71541d91abe388c5fc1dcad857f969d4de023db7

    root@:eMMC:/home/guest# tpm2_load -C primary.ctx -u hmac.pub -r hmac.priv -c hmac.key
    name: 000bbd35da89c354d39192fce1735c5ffa319e3bf03d0e0eae380f843e5793909cb6

    root@reliagate-10-14:eMMC:/home/guest# echo "MickeyMouse" > data.in

    root@reliagate-10-14:eMMC:/home/guest# tpm2_hmac -c hmac.key --hex data.in
    82ea4d1cc213c96dcf21d9bbdaae0c5354515cee052b57bdfdcf962f0e056676

FYI, 
on Friday 25/11/2022, we got a fw update from Infineon for P/N SLB9670 (from v 7.83.3358.0 to v 7.85.4555.0) ; once updated the tpm device, the original test sequence works fine as well; here is what we get : 

    root@:eMMC:/home/guest# tpm2_createprimary -c primary.ctx
    name-alg:
      value: sha256
      raw: 0xb
    attributes:
      value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|decrypt
      raw: 0x30072
    type:
      value: rsa
      raw: 0x1
    exponent: 65537
    bits: 2048
    scheme:
      value: null
      raw: 0x10
    scheme-halg:
      value: (null)
      raw: 0x0
    sym-alg:
      value: aes
      raw: 0x6
    sym-mode:
      value: cfb
      raw: 0x43
    sym-keybits: 128
    rsa: cb0f7e70e500df0f037c5d0bde074e6c28ea3a39020be46f21862ebeb50e1e2d3d73ad696b065e97186703ca88d249e0efa692594b807d77daa08e5fe045c6f1
    d978486869ee7e757526ba3853df7336290fafb75b7479c659407debc349db695f6a48f4e703118b1f8c7be34b0f4d8ae9670b13618839f2b7ca40ddf8305997c6040
    dc1b26f3c26d3ccd086babc16d9b1085c6106ab5d1d84698101e6fdf383d68fbcd9a27175a97010f092fc27181bfafd87d970ac0e8e641dfb6f1e33d5e36c5ef7f774
    49ed9955d119de59d79792932d069b3242a1722f55e6f6ff47c23ca8abab355e871ebab2c28d328cb0618b47b125daf850948b9af985b77c126ec5
    root@eMMC:/home/guest# tpm2_create -C primary.ctx -G hmac -c hmac.key
    name-alg:
      value: sha256
      raw: 0xb
    attributes:
      value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|sign
      raw: 0x40072
    type:
      value: keyedhash
      raw: 0x8
    algorithm: 
      value: hmac
      raw: 0x5
    hash-alg:
      value: sha256
      raw: 0xb
    keyedhash: e38970655dd85a0b41e1f9cd2bff18a39a8f0039af6e4b9d3cde9b98949fde9d
    root@:eMMC:/home/guest# echo "MickeyMouse" > data.in
    root@:eMMC:/home/guest# tpm2_hmac -c hmac.key --hex data.in                                                           
    44572a0a59e989c89bd6045cfbb95465e45c0470f065288e9b63ab1f298f9c18
