### ISSUE TITLE
TPM2_Encryptdecrypt not supported by my TPM2

### ISSUE THREAD

**Issue by GaspardLauras** [tpm2-software/tpm2-tools#3180]
Hello,
I am currently working with tpm2 to encrypt a file and I can't manage to make the tutorial from the man ```tpm2_encryptdecrytpt``` page. 
More precisely the first part works if I specify aes128ctr in the -G parameter of ```tpm2_create``` 

```sudo tpm2_create -C primary.ctx -Gaes128ctr -u key.pub -r key.priv```

But the second part where we use ```tpm2_encryptdecrypt``` returns the following error message : 

```
sudo tpm2_encryptdecrypt -c key.ctx -o secret.enc secret.dat

WARN: Using a weak IV, try specifying an IV
WARNING:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:322:Esys_EncryptDecrypt2_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EncryptDecrypt2.c:107:Esys_EncryptDecrypt2() Esys Finish ErrorCode (0x000b0143) 
WARNING:esys:src/tss2-esys/api/Esys_EncryptDecrypt.c:328:Esys_EncryptDecrypt_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EncryptDecrypt.c:110:Esys_EncryptDecrypt() Esys Finish ErrorCode (0x000b0143) 
ERROR: Esys_EncryptDecrypt(0xB0143) - rmt:error(2.0): command code not supported
ERROR: Unable to run tpm2_encryptdecrypt

```
I found an issue explaining that it was because my TPM does not support tpm_encryptdecrypt command. [https://github.com/tpm2-software/tpm2-tools/issues/2229](url)
Also using the command ```tpm2_getcap commands```, I wasn't able to find the TPM2_CC_Encryptdecrypt command available. 

```
sudo tpm2_getcap commands | grep -i Encryptdecrypt | wc -l 
0
```
Because of that, I was not able to use the tutorial provided in the issue mentionned. 

Is there another way for me to encrypt and decrypt files with a TPM stored AES key?

**Comment by williamcroberts** [comment]
You're TPM doesn't support EncryptDecrypt, most don't. So you have to seal and unseal the key to and from the TPM and use software encrypt/decrypt.

**Setup**
```bash
tpm2 createprimary -c primary.ctx
dd if=/dev/urandom bs=1 count=32 of=aes256.key
tpm2 create -C primary.ctx -i aes256.key -u key.pub -r key.priv
# Store key.pub and key.priv OR use tpm2 evictcontrol after loading (see below) to persist it.
```
**Use**
```bash
tpm2 load -C primary.ctx -u key.pub -r key.priv -c key.ctx
tpm2 unseal -c key.ctx
tpm2 unseal -c key.ctx > aes256.key2
openssl enc -aes-256-ctr -pbkdf2 -e -p -kfile aes256.key2 -in ~/.bashrc -out file.enc
```

Note: You can set passwords and policies on the key when you call `tpm2_create`.
