### ISSUE TITLE
tpm logs 

### ISSUE THREAD

**Issue by Naranthiran** [tpm2-software/tpm2-tools#3187]
Hi, 

Where can I find the TPM device logs? or do we need to configure the system  log the activities of TPM.

Regards
Naran

**Comment by idesai** [comment]
@Naranthiran, you mean eventlogs of PCR extensions?

**Comment by Naranthiran** [comment]
Yes,I wanted to know the when tpm got into dictionary lockout mode or got reset.

**Comment by idesai** [comment]
The eventlog is here: /sys/kernel/security/tpm0/binary_bios_measurement

**Comment by Naranthiran** [comment]
Hi Idesai,

Thank you for your reply, the file(binary_bios_measurement) content is not proper. I am using vi tool to view the file.

Any reason for that?

Regards
Naran

**Comment by thomasoll** [comment]
@Naranthiran you can cat the log to a file, and then use tpm2_eventlog to read it.
` cat /sys/kernel/security/tpm0/binary_bios_measurements > ./tpm.txt
tpm2_eventlog ./tpm.txt`

**Comment by Naranthiran** [comment]
Hi Idesai,

Thanks for your reply!! 

Regards
Naran
