### ISSUE TITLE
limit tpm2 reads

### ISSUE THREAD

**Issue by oregonpillow** [tpm2-software/tpm2-tools#3190]
Hi,
is there a way to enforce that the tpm can only be read once per boot? If so, what is the name of the command that can do this?

Thanks.

**Comment by williamcroberts** [comment]
> Hi, is there a way to enforce that the tpm can only be read once per boot? If so, what is the name of the command that can do this?
> 
> Thanks.

What specifically do you want to have read once per boot? The tpm provides a lot of things: keys, NV memory, measurements,.etc

**Comment by oregonpillow** [comment]
I would like to read a key from the nv memory so that it only reads once per boot. Currently I'm using tpm2_nvread but this can be executed unlimited number of times.

**Comment by williamcroberts** [comment]
> I would like to read a key from the nv memory so that it only reads once per boot. Currently I'm using tpm2_nvread but this can be executed unlimited number of times.

NV Readlock command

**Comment by oregonpillow** [comment]
Thanks @williamcroberts this is exactly what I've been looking for.

**Comment by nicowilliams** [comment]
Another more general trick is to use a policy that requires PCR \#11 to have a particular value, like the initial value, then after doing whatever you have to on early boot you extend that PCR and now the policy can't be satisfied w/o rebooting.
