### ISSUE TITLE
validate if key is present inside the TPM

### ISSUE THREAD

**Issue by shekharpaty** [tpm2-software/tpm2-tools#3201]
Hello Team,

Please let me know are there any tools where I can validate the key is present in the TPM.

with the means of FAPI (Fapi_CreateKey) API I am getting success return , I can see my key meta data inside /HS/SRK/main_key/object.json.

But are there any tools which query the TPM hardware and tell us the key is present inside TPM hardware. 

I am aware of Fapi_List().

**Comment by JuergenReppSIT** [comment]
With 'tpm2_getcap` you can inspect the object stored in the TPM.
`tpm2_getcap -l` displays all possibilities.

FAPI keys are stored in the TPM if you define a persistent handle for the key.
If you use your key `/SRK/main_key` FAPI will load it into the TPM (if the key is not persistent)  for the current usage e.g. signing.
