### ISSUE TITLE
Generate shared secret using ECDH keys

### ISSUE THREAD

**Issue by syedelec** [tpm2-software/tpm2-tools#3202]
Hello

I want to generate a shared ECHD secret based on 2 ECDH key pair but I am not obtaining the same secret.

Here is an example based on the [man page of tpm2_ecdhzgen](https://tpm2-tools.readthedocs.io/en/latest/man/tpm2_ecdhzgen.1/): 

```
tpm2_createprimary -C o -c prim.ctx -Q

tpm2_create -C prim.ctx -c keyA.ctx -G ecc256:ecdh
tpm2_ecdhkeygen -u ecdhA.pub -o ecdhA.priv -c keyA.ctx

tpm2_create -C prim.ctx -c keyB.ctx -G ecc256:ecdh
tpm2_ecdhkeygen -u ecdhB.pub -o ecdhB.priv -c keyB.ctx

# Generate ECDH secrets
tpm2_ecdhzgen -u ecdhB.pub -o ecdh1.dat -c keyA.ctx
tpm2_ecdhzgen -u ecdhA.pub -o ecdh2.dat -c keyB.ctx
```

The ECDH secret is not the same. Could you point me to the right way of having same ECDH secret generated using 2 ECDH key pair?

Thanks

**Comment by JuergenReppSIT** [comment]
With these commands it should work:
```
tpm2_createprimary -C o -c prim.ctx -Q
tpm2_create -C prim.ctx -c keyA.ctx -G ecc256:ecdh
tpm2_create -C prim.ctx -c keyB.ctx -u ecdhB.pub -G ecc256:ecdh
tpm2_readpublic -c keyB.ctx -o pubkeyB.bin
tpm2_loadexternal -C o -u pubkeyB.bin -c pubkeyB.ctx
tpm2_ecdhkeygen -u ecdhA.pub -o secretA.dat -c pubkeyB.ctx
tpm2_ecdhzgen -u ecdhA.pub -o secretB.dat -c keyB.ctx
diff secretA.dat secretB.dat
```

**Comment by syedelec** [comment]
Thanks! I find the same secret as you mentioned but to be honest I do not understand why.

The principle of ECDH shared secret is the following:

![image](https://user-images.githubusercontent.com/9877335/217079637-0d21b360-356b-4fa3-adf0-87b52230e51b.png)

If we take the same concept with `openssl`, we have the following:

```
# Generate EC key pair A
openssl ecparam -name prime256v1 -genkey -noout -out keyA.pem
openssl ec -in keyA.pem -pubout -out publicA.pem

# Generate EC key pair B
openssl ecparam -name prime256v1 -genkey -noout -out keyB.pem
openssl ec -in keyB.pem -pubout -out publicB.pem

# Derive shared secret
openssl pkeyutl -derive -inkey keyB.pem -peerkey publicA.pem -out secret1.bin
openssl pkeyutl -derive -inkey keyA.pem -peerkey publicB.pem -out secret2.bin

# Same shared secret
diff secret1.bin secret2.bin
```

I cannot understand how to reproduce the same concept using tpm2-tools.

The `tpm2_ecdhzgen` [recovers the shared secret value (Z) from a public point and a specified private key](https://tpm2-tools.readthedocs.io/en/latest/man/tpm2_ecdhzgen.1/)

The `tpm2_ecdhkeygen` [creates an ephemeral key and uses it to generate the shared secret value using the parameters from a ECC public key](https://tpm2-tools.readthedocs.io/en/latest/man/tpm2_ecdhkeygen.1/)

From what I understand, the `tpm2_ecdhkeygen` will always generate/derive a new secret since the private key is generated on the fly (ephemeral key) each run.

And regarding the `tpm2_ecdhzgen`, it describes exactly what I need but I cannot get it working.

Here is an example that should be working:

```
tpm2_createprimary -C o -c prim.ctx -Q

# Create ECDH keypair A
tpm2_create -C prim.ctx -c keyA.ctx -u ecdhA.pub -G ecc256:ecdh

# Create ECDH keypair B
tpm2_create -C prim.ctx -c keyB.ctx -u ecdhB.pub -G ecc256:ecdh

# Derive ECDH secret 1 using private key A and public key B
tpm2_ecdhzgen -c keyA.ctx -u ecdhB.pub -o secret1.dat 

# Derive ECDH secret 2 using private key B and public key A
tpm2_ecdhzgen -c keyB.ctx -u ecdhA.pub -o secret2.dat 
```

But I have an error:

```
root@board:~# tpm2_ecdhzgen -c keyA.ctx -u ecdhB.pub -o secret1.dat  
WARNING:esys:../tpm2-tss-3.2.0/src/tss2-esys/api/Esys_ECDH_ZGen.c:295:Esys_ECDH_ZGen_Finish() Received TPM Error 
ERROR:esys:../tpm2-tss-3.2.0/src/tss2-esys/api/Esys_ECDH_ZGen.c:98:Esys_ECDH_ZGen() Esys Finish ErrorCode (0x000001d5) 
ERROR: Esys_ECDH_ZGen(0x1D5) - tpm:parameter(1):structure is the wrong size
ERROR: Unable to run tpm2_ecdhzgen
```

**Comment by JuergenReppSIT** [comment]
I did assume that you want to use an ephemaral key because you did use
`tpm2_ecdhkeygen` in your first example. The creation of keyA was not needed,
in my example it was just copied from your example.

The problem with your second example is that `tpm2_ecdhzgen` expects the
structure TPM2B_ECC_POINT but `tpm2_create` produces the type TPM2B_PUBLIC
for the public key. `tmp2_ecdhkeygen` produces a TPM2B_ECC_POINTm, therefore
my example did work
@williamcroberts  @idesai  Perhaps I have overlooked the possibility to extract
the public point from an ECC key? If not I think we should add an option to
`tpm2_ecdhzgen` to allow usage of the TPM2B_PUBLIC type of the key?

I have created a small python script (ec_public_to_point.py) to convert
the public ECC key to a point:
```
#!/usr/bin/python3

import sys
from tpm2_pytss import *

with open(sys.argv[1], mode='rb') as file:
    public_bytes = file.read()

public, _ = TPM2B_PUBLIC.unmarshal(public_bytes)
point = TPM2B_ECC_POINT()
point.point = public.publicArea.unique.ecc;

with open(sys.argv[2], mode='wb') as file:
    file.write(TPM2B_ECC_POINT.marshal(point))

```

So the secrects can be computed as you did expect it:
```
tpm2_createprimary -C o -c prim.ctx -Q

# Create ECDH keypair A
tpm2_create -C prim.ctx -c keyA.ctx -u ecdhA.pub -G ecc256:ecdh
ec_public_to_point.py ecdhA.pub pointA.pub
# Create ECDH keypair B
tpm2_create -C prim.ctx -c keyB.ctx -u ecdhB.pub -G ecc256:ecdh
ec_public_to_point.py ecdhB.pub pointB.pub

# Derive ECDH secret 1 using private key A and public key B
tpm2_ecdhzgen -c keyA.ctx -u pointB.pub -o secret1.dat 

# Derive ECDH secret 2 using private key B and public key A
tpm2_ecdhzgen -c keyB.ctx -u pointA.pub -o secret2.dat

diff secret1.dat secret2.dat

```

**Comment by syedelec** [comment]
> I did assume that you want to use an ephemaral key because you did use `tpm2_ecdhkeygen` in your first example. The creation of keyA was not needed, in my example it was just copied from your example.

Right, this is my fault, I though `tpm2_ecdhkeygen` generates an ECDH key pair and exports private and public part from the key context. I did not read the doc correctly.

> The problem with your second example is that `tpm2_ecdhzgen` expects the structure TPM2B_ECC_POINT but `tpm2_create` produces the type TPM2B_PUBLIC for the public key. `tmp2_ecdhkeygen` produces a TPM2B_ECC_POINTm, therefore my example did work @williamcroberts @idesai Perhaps I have overlooked the possibility to extract the public point from an ECC key? If not I think we should add an option to `tpm2_ecdhzgen` to allow usage of the TPM2B_PUBLIC type of the key?

Ok I understand now. Thanks for the explanation :+1: 

> I have created a small python script (ec_public_to_point.py) to convert the public ECC key to a point:
> 
> ```
> #!/usr/bin/python3
> 
> import sys
> from tpm2_pytss import *
> 
> with open(sys.argv[1], mode='rb') as file:
>     public_bytes = file.read()
> 
> public, _ = TPM2B_PUBLIC.unmarshal(public_bytes)
> point = TPM2B_ECC_POINT()
> point.point = public.publicArea.unique.ecc;
> 
> with open(sys.argv[2], mode='wb') as file:
>     file.write(TPM2B_ECC_POINT.marshal(point))
> ```
> 
> So the secrects can be computed as you did expect it:
> 
> ```
> tpm2_createprimary -C o -c prim.ctx -Q
> 
> # Create ECDH keypair A
> tpm2_create -C prim.ctx -c keyA.ctx -u ecdhA.pub -G ecc256:ecdh
> ec_public_to_point.py ecdhA.pub pointA.pub
> # Create ECDH keypair B
> tpm2_create -C prim.ctx -c keyB.ctx -u ecdhB.pub -G ecc256:ecdh
> ec_public_to_point.py ecdhB.pub pointB.pub
> 
> # Derive ECDH secret 1 using private key A and public key B
> tpm2_ecdhzgen -c keyA.ctx -u pointB.pub -o secret1.dat 
> 
> # Derive ECDH secret 2 using private key B and public key A
> tpm2_ecdhzgen -c keyB.ctx -u pointA.pub -o secret2.dat
> 
> diff secret1.dat secret2.dat
> ```

Everything works as expected now! On my side the issue is fixed. Thanks again!

PS: That would be great to have `tpm2_ecdhzgen`  accepting `TPM2B_PUBLIC` as argument.
