### ISSUE TITLE
Restricted, fixedTPM, fixedParent Primary signing key with the command "tpm2_createprimary"

### ISSUE THREAD

**Issue by ltf0925** [tpm2-software/tpm2-tools#3203]
Hi there,

I am working on the implementation of IAK/IDEVID in the  TCG publication "TPM 2.0 Keys for Device Identity and Attestation,  Version 1.00 Revision 12 October 8, 2021". Based on the document, IDevID and IAK keys created by an OEM SHOULD be Primary keys. ( section 3.7), and an AK MUST have the following characteristics: Restricted, Signing, Not-decrypting and FixedTPM. (section 4.1) and should be under Endorsement Hierarchy(section 6.1.2).

I wanted to create an IAK with the following command(the version of tpm2-tools is 4.1.3.) and failed. here is the logs:

# tpm2_createprimary -C e  -G rsa2048 -g sha256 -c prim.ctx -a 'restricted|fixedtpm|fixedparent|sensitivedataorigin|userwithauth|sign'
WARNING:esys:../tpm2-tss-2.3.2/src/tss2-esys/api/Esys_CreatePrimary.c:389:Esys_CreatePrimary_Finish() Received TPM Error
ERROR:esys:../tpm2-tss-2.3.2/src/tss2-esys/api/Esys_CreatePrimary.c:135:Esys_CreatePrimary() Esys Finish ErrorCode (0x000002d2)
ERROR: Esys_CreatePrimary(0x2D2) - tpm:parameter(2):unsupported or incompatible scheme

what is wrong with the attributes in the command? or if there is no issue at all with the command above, TCG publication is not correct?

Thanks

Tim

**Comment by JuergenReppSIT** [comment]
If you use a restricted signing key you must also assign the scheme and the symmetric type e.g.: `-G rsa2048:rsapss:null`
If you remove the restricted flag it also would work.

**Comment by JuergenReppSIT** [comment]
It has no meaning for the signing algorithm. But the default for the symmetric encryption in the tpm tools is AES. The TPM checks if this parameter for a restricted signing key is equal TPM_ALG_NULL and would return the error TPM_RCS_SYMMETRIC if not. So you have to set the parameter to null (Could actually be set by the tpm tools ;-))

**Comment by ltf0925** [comment]
Great!  it is clear!

Thank you very much!

Tim
