### ISSUE TITLE
After execute TPM command, how to collect the error print infomation? 

### ISSUE THREAD

**Issue by wjzu2023** [tpm2-software/tpm2-tools#3205]
like below:
root@ORU3668_MAIN:~# tpm2_nvdefine -Q 1024 -C o -s 788 -a "ownerread|policywrite|ownerwrite" > tmp.txt
WARNING:esys:../tpm2-tss-3.0.3/src/tss2-esys/api/Esys_NV_DefineSpace.c:337:Esys_NV_DefineSpace_Finish() Received TPM Error
ERROR:esys:../tpm2-tss-3.0.3/src/tss2-esys/api/Esys_NV_DefineSpace.c:122:Esys_NV_DefineSpace() Esys Finish ErrorCode (0x000009a2)
ERROR: Failed to define NV area at index 0x1000400
ERROR: Esys_NV_DefineSpace(0x9A2) - tpm:session(1):authorization failure without DA implications
ERROR: Failed to create NV index 0x1000400.
ERROR: Unable to run tpm2_nvdefine

**Comment by JuergenReppSIT** [comment]
you can collect the error prints with:
` tpm2_nvdefine -Q 1024 -C o -s 788 -a "ownerread|policywrite|ownerwrite"` 2>error.log`

**Comment by wjzu2023** [comment]
> you can collect the error prints with: ` tpm2_nvdefine -Q 1024 -C o -s 788 -a "ownerread|policywrite|ownerwrite"` 2>error.log`
