### ISSUE TITLE
When use command "openssl pkeyutl -engine libtpm2tss -keyform engine -inkey mykey -decrypt -in mycipher -out mydata.bak", how to enter parent passwd of TPM?

### ISSUE THREAD

**Issue by wjzu2023** [tpm2-software/tpm2-tools#3206]

**Comment by JuergenReppSIT** [comment]
The man page states:
```-W <password>, --parentpw <password>: Password for the parent key (default: none) Openssl Config control command: SET_PARENTAUTH```
Example:
```
cat > engine.conf <<EOF
    openssl_conf = openssl_init

    [openssl_init]
    engines = engine_section

    [engine_section]
    tpm2tss = tpm2tss_section

    [tpm2tss_section]
    SET_PARENTAUTH = abc
EOF

export OPENSSL_CONF=engine.conf
```

**Comment by JuergenReppSIT** [comment]
There was already an issue related to this topic: #105
Unfortunately it seems to be necessary to add the owner password to the config file for the openssl commands:
SET_OWNERAUTH = Welcome
The following example did work with owner auth set to Welcome.
```
tpm2tss-genkey -a rsa -s 2048 mykey
echo 123 > mydata
openssl rsa -engine tpm2tss -inform engine -in mykey -pubout -outform pem -out mykey.pub
openssl pkeyutl -pubin -inkey mykey.pub -in mydata -encrypt -out mycipher
openssl pkeyutl -engine tpm2tss -keyform engine -inkey mykey -decrypt -in mycipher -out mydata2
```

**Comment by wjzu2023** [comment]
> There was already an issue related to this topic: [tpm2-software/tpm2-tss-engine#105](https://github.com/tpm2-software/tpm2-tss-engine/issues/105) Unfortunately it seems to be necessary to add the owner password to the config file for the openssl commands: SET_OWNERAUTH = Welcome The following example did work with owner auth set to Welcome.
> 
> ```
> tpm2tss-genkey -a rsa -s 2048 mykey
> echo 123 > mydata
> openssl rsa -engine tpm2tss -inform engine -in mykey -pubout -outform pem -out mykey.pub
> openssl pkeyutl -pubin -inkey mykey.pub -in mydata -encrypt -out mycipher
> openssl pkeyutl -engine tpm2tss -keyform engine -inkey mykey -decrypt -in mycipher -out mydata2
> ```

Thanks for your reply, I will close the issue
