### ISSUE TITLE
How to manually get into DA lockout mode in tpm2

### ISSUE THREAD

**Issue by Naranthiran** [tpm2-software/tpm2-tools#3211]
Hi All,

I am trying to manually get into DA lockout mode in tpm2 and tpm2 the lockout mode through BISO(tpm_clear).

can anyone share the command to set the tpm2 to DA lockout mode manually? or is there any other way to get into DA lockout mode?

I am using a Linux machine.

Regards
Naranthiran Duraisamy

**Comment by JuergenReppSIT** [comment]
You can set the number of max tries, use a password for a primary key, and then create a key without using the password for the parent key:
```
tpm2_dictionarylockout --setup-parameters --max-tries=1
tpm2_createprimary -C o -c prim.ctx -p 123
tpm2_create -C prim.ctx -r priv -u pub
```

**Comment by Naranthiran** [comment]
Hi Jürgen,

Thanks for your reply. The below command fails. What would be the reason?

Note: The TPM is already binded with luks.

[root@localhost /]# tpm2_create -C prim.ctx -r priv -u pub
WARNING:esys:src/tss2-esys/api/Esys_Create.c:375:Esys_Create_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Create.c:120:Esys_Create() Esys Finish ErrorCode (0x0000098e)
ERROR: Esys_Create(0x98E) - tpm:session(1):the authorization HMAC check failed and DA counter incremented
ERROR: Unable to run tpm2_create

Regards
Naranthiran Duraisamy

**Comment by JuergenReppSIT** [comment]
@Naranthiran If the TPM is already binded with luks you should be careful with bringing the TPM into the lockout mode.
The result is what's should be expected because you did not use the primary auth value and now the TPM should be in lockout mode. I thought that's wat you wanted to do?

**Comment by Naranthiran** [comment]
Hi Jürgen,

Okay, If I understood correctly if I execute the command( tpm2_create -C prim.ctx -r priv -u pub) one than one time should get the TPM into DA lockout mode.

But I still have the value  "inLockout: 0", which should have changed to 1(which denotes the TPM entered into DA lockout mode).

I have the luks password in hand so that I can recover the system even if TPM fails.

Thanks again for your response.
Regards
Naranthiran Duraisamy

**Comment by JuergenReppSIT** [comment]
Hi @Naranthiran and what is the complete output of:
`tpm2_getcap properties-variable`

**Comment by Naranthiran** [comment]
Hi Jürgen,

Please find the output of the command.

[root@localhost /]# tpm2_getcap properties-variable
TPM2_PT_PERSISTENT:
  ownerAuthSet:              0
  endorsementAuthSet:        0
  lockoutAuthSet:            0
  reserved1:                 0
  disableClear:              0
  inLockout:                 0
  tpmGeneratedEPS:           0
  reserved2:                 0
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  1
  shEnable:                  1
  ehEnable:                  1
  phEnableNV:                1
  reserved1:                 0
  orderly:                   1
TPM2_PT_HR_NV_INDEX: 0x2
TPM2_PT_HR_LOADED: 0x0
TPM2_PT_HR_LOADED_AVAIL: 0x3
TPM2_PT_HR_ACTIVE: 0x0
TPM2_PT_HR_ACTIVE_AVAIL: 0x40
TPM2_PT_HR_TRANSIENT_AVAIL: 0x3
TPM2_PT_HR_PERSISTENT: 0x0
TPM2_PT_HR_PERSISTENT_AVAIL: 0x12
TPM2_PT_NV_COUNTERS: 0x0
TPM2_PT_NV_COUNTERS_AVAIL: 0xD
TPM2_PT_ALGORITHM_SET: 0x0
TPM2_PT_LOADED_CURVES: 0x2
TPM2_PT_LOCKOUT_COUNTER: 0x0
TPM2_PT_MAX_AUTH_FAIL: 0x1
TPM2_PT_LOCKOUT_INTERVAL: 0x0
TPM2_PT_LOCKOUT_RECOVERY: 0x0
TPM2_PT_AUDIT_COUNTER_0: 0x0
TPM2_PT_AUDIT_COUNTER_1: 0x0
[root@localhost /]#

Regards
Naranthiran Duraisamy

**Comment by JuergenReppSIT** [comment]
@Naranthiran  TPM2_PT_LOCKOUT_INTERVAL defines the number of seconds before the value reported by
TPM_PT_LOCKOUT_COUNTER is decremented. Because this value is 0  the counter seems to be directly decremented after the failure.
You cant try to set this value e.g. to 10sec with:
`tpm2_dictionarylockout --setup-parameters  --recovery-time=10`

**Comment by Naranthiran** [comment]
Hi Jürgen,

Thank you so much for your support.

I am able to get into DA lockout mode.

 Regards
Naranthiran Duraisamy
