### ISSUE TITLE
How can I set owner password by related API of TPM tools?

### ISSUE THREAD

**Issue by wjzu2023** [tpm2-software/tpm2-tools#3212]

**Comment by JuergenReppSIT** [comment]
You can set it with:
`tpm2_changeauth -c o newpwd`
or
`tpm2_changeauth -c o -p oldpwd newpwd`

**Comment by wjzu2023** [comment]
> You can set it with: `tpm2_changeauth -c o newpwd` or `tpm2_changeauth -c o -p oldpwd newpwd`

When do that , the password is exposed that we can get the password by command "ps -ef | grep changeauth". I want to call source code API of TPM tools to set the password.

**Comment by JuergenReppSIT** [comment]
With `tpm2_changeauth -c o file:-` the password will not be exposed. If FAPI ist installed you can use: 
`tss2_changeauth -p /HS`.  Also here he password will not be exposed.
The ESAPI function for this purpose is  `Esys_HierarchyChangeAuth.` You should use a session with a tpmkey to ensure that the password is encrypted. If you use the FAPI function `Fapi_ChangeAuth` the password will be encrypted automatically.
You can find examples how to do this in the tss integration tests.

**Comment by wjzu2023** [comment]
> With `tpm2_changeauth -c o file:-` the password will not be exposed. If FAPI ist installed and provisioned you can use: `tss2_changeauth -p /HS`. Also here he password will not be exposed. The ESAPI function for this purpose is `Esys_HierarchyChangeAuth.` You should use a session with a tpmkey to ensure that the password is encrypted. If you use the FAPI function `Fapi_ChangeAuth` the password will be encrypted automatically. You can find examples how to do this in the tss integration tests.

Like example :
```
int
test_invoke_esys(ESYS_CONTEXT * esys_context) {
    return test_esys_hierarchychangeauth(esys_context);
}
```
How can I set  corresponding values to the parameters of esys_context ? Could you give me more details ? Thanks.

**Comment by JuergenReppSIT** [comment]
you can find examples in:
https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-fapi/api/Fapi_ChangeAuth.c

**Comment by wjzu2023** [comment]
> you can find examples in: https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-fapi/api/Fapi_ChangeAuth.c

Can I how to call the source code API of  the command "tpm2_nvread -C o -s 2048 1024 -o test.file -P passwd " ?
