### ISSUE TITLE
How Can I Get an EKCert of a TPM Emulator Made by IBM

### ISSUE THREAD

**Issue by velopt** [tpm2-software/tpm2-tools#3217]
Here is what I want to do:
I'm working on TPM's Remote Attestation. To sign an AIKCert, I need to offer an EKCert first.
I just find out at [#1698](https://github.com/tpm2-software/tpm2-tools/issues/1698) that tpm2_getekcertificate can do it, and it can auto-discover TPM manufacturer's server URL. For Some specific TPM like Infineon, I can read EKCert from NV.

So My first question is : Does it mean I don't have to provide manufacturer's server URL At the end of the command line, for REAL TPM?

But before I put all these on a real TPM, I need to test on a TPM Emulator, which I chose IBM's Software TPM.
There is No EKCert in NV, and I don't know where to fatch an EKCert so that I could sign a AIKCert at least.

My second question is : How to find an EKCert for a TPM emulator? Or Is there a suitable way to leave the EKCert so that I can get the AIK certificate first and say, then add EKCert to the process for completing.

This question might seem stupid, sry for that. I'm just a starter. 
よろしくお願いします！

**Comment by wxleong** [comment]
Q1:
The EKCert for Infineon TPM can be found in TPM NV indices, so no URL is needed. The URL option is only for INTC TPM.

Q2:
AFAIK, IBM's software TPM does not support EK cert (correct me if I'm wrong). Maybe you can explore [stefanberger/swtpm](https://github.com/stefanberger/swtpm). You can find instructions to set up the swtpm's EK in the project [ek-based-onboarding-optiga-tpm](https://github.com/Infineon/ek-based-onboarding-optiga-tpm). You can use `tpm2_nvread` or `tpm2_getekcertificate` to read the EK certs and manually verify it against the swtpm locally generated CA certs (there will be an intermediate CA and a root CA, and the EK cert will be signed by the intermediate) that you obtain during the setup stage.

**Comment by velopt** [comment]
> 

Thanks a lot!
This would be very helpful!
I'll work on it.
