### ISSUE TITLE
How to check if TPM is active  or inactive

### ISSUE THREAD

**Issue by shekharpaty** [tpm2-software/tpm2-tools#3220]
Hi Team,

Can any one please point out to me  commond to check, if TPM is in active state or in active state.

Thanks,

**Comment by JuergenReppSIT** [comment]
You can e.g. try to execute 
`tpm2_getcap properties-fixed`
If the TPM returns ErrorCode (0x00000100):
` tpm:error(2.0): TPM not initialized by TPM2_Startup or already initialized`
you can try to execute:
`tpm2_startup -c`
