### ISSUE TITLE
tss2_unseal with multi-pcr policy gives "free(): invalid next size (fast)"

### ISSUE THREAD

**Issue by PiQuer** [tpm2-software/tpm2-tools#3223]
I'm trying to seal / unseal an object associated with a policy involving two PCR values. I can reproduce the issue with tpm2-tools 5.3 and with the latest commit on master (90534beb). I have done my test with IBM's Software TPM 2.0. The FAPI profile is [P_ECCP256SHA256](https://github.com/tpm2-software/tpm2-tss/blob/3d3c9a81db1354fe75dd27f5a87551c101034b0d/dist/fapi-profiles/P_ECCP256SHA256.json).

First a test with a single PCR value policy, which works fine.

```
$ cat policy-pcr.json
{
  "name": "PCR",
  "description": "A policy requiring certain PCR values",
  "policy": [
    {
      "type": "pcr",
      "currentPCRs": [ 16 ]
    }
  ]
}
$ tss2_import --path=/policy/testpolicy -i policy_pcr.json
$ echo "Hello, World" | tss2_createseal --data=- --authValue= --path=HS/SRK/testKey --policyPath=/policy/testpolicy
$ tss2_unseal --path=HS/SRK/testKey --data=-
Hello, World
```

Now with two PCR values (after deleting the previously created objects):
```
$ cat policy-pcr.json
{
  "name": "PCR",
  "description": "A policy requiring certain PCR values",
  "policy": [
    {
      "type": "pcr",
      "currentPCRs": [ 15, 16 ]
    }
  ]
}
$ tss2_import --path=/policy/testpolicy -i policy_pcr.json
$ echo "Hello, World" | tss2_createseal --data=- --authValue= --path=HS/SRK/testKey --policyPath=/policy/testpolicy
$ tss2_unseal --path=HS/SRK/testKey --data=-
free(): invalid next size (fast)
[1]    471215 IOT instruction (core dumped)  tss2_unseal --path=HS/SRK/testKey --data=-
```
I see the same behavior when I use the PCR values directly in the policy instead of "currentPCRs" (works with one, does not work with two values).

Have I misunderstood how policies involving multiple PCRs are supposed to work?

**Comment by dsburns** [comment]
Can confirm the same issue on my setup with tpm2-tss 3.2.2 and tpm2-tools 5.5.

**Comment by JuergenReppSIT** [comment]
@PiQuer Sorry I have overlooked the issue. It's an error in the tss library and now is fixed by:
https://github.com/tpm2-software/tpm2-tss/pull/2616 and also backported to version 3.2.x.

**Comment by PiQuer** [comment]
Sorry for the late reply. Works great now, thanks!
