### ISSUE TITLE
tpm2_create with parameter -Q in tpm2_policypcr.1.md

### ISSUE THREAD

**Issue by TheBigFish** [tpm2-software/tpm2-tools#3247]
In file man/tpm2_policypcr.1.md, the example using `tpm2_create -Q`

But can not get the parameter `-Q` in command `tpm2_create`，so what is this `-Q` using for?

```markdown
Step 2: create an object using that policy

tpm2_create -Q -u key.pub -r key.priv -C primary.ctx -L policy.dat \
-i- <<< "12345678"

tpm2_load -C primary.ctx -u key.pub -r key.priv -n unseal.key.name \
-c unseal.key.ctx
```

thanks!

**Comment by JuergenReppSIT** [comment]
The meaning is --quiet: Silence normal tool output to stdout.
See: https://github.com/tpm2-software/tpm2-tools/blob/master/man/common/options.md

**Comment by TheBigFish** [comment]
Thanks for the answer.
And there is an other question.
In the example above,
`tpm2_create` with `-i` to seal input data, but not using `-c` parameter.
and then using `tpm2_load`  with `-n unseal.key.name` ,
Does `tpm2_load` load the object `tpm2_create` with seal data "12345678"?
How does it work, and what is the mechanism between these sequence as `tpm2_load` after `tpm2_create` in this example?

**Comment by JuergenReppSIT** [comment]
> Does tpm2_load load the object tpm2_create with seal data "12345678"?

yes, `tpm2_load`  creates the context file which can be used for `tpm2_unseal`.
You could also use the `-c` parameter for `tpm2_create`. But after a reboot it would be necessary to recreate the context file with tpm_load from the public and private key files.

**Comment by TheBigFish** [comment]
Thanks!
