### ISSUE TITLE
tpm2_duplicate -G not used consistently

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#3259]
Variable "ctx.key_type" is used to set both the symmetric algorithm:

https://github.com/tpm2-software/tpm2-tools/blob/6e484f59bc65b01ec5b1f81b5bf0897c53a1ff4b/tools/tpm2_duplicate.c#L377

and the key type 

https://github.com/tpm2-software/tpm2-tools/blob/6e484f59bc65b01ec5b1f81b5bf0897c53a1ff4b/tools/tpm2_duplicate.c#L217-L218

The encryption key and the key type specifier should have different options. This is likely a backwards compat breaking change :-(

**Comment by idesai** [comment]
@williamcroberts isn't the later applicable only if we are using openssl when specifying a public key directly. The man page can definitely use some more description.

**Comment by williamcroberts** [comment]
> @williamcroberts isn't the later applicable only if we are using openssl when specifying a public key directly. The man page can definitely use some more description.

Yeah I realized that later that this could be addressed solely by documentation, and I would also urge the use of another long option that maps to '-G'. Perhaps `--key-algorithm` to match `tpm2_create`.
