### ISSUE TITLE
tpm2 commands working without a tpm chip

### ISSUE THREAD

**Issue by matIRL** [tpm2-software/tpm2-tools#3294]
Guys, 

I can execute various tpm2 commands and receive results **without** a tpm chip installed... what is going on here?

![Screenshot from 2023-10-11 11-58-59](https://github.com/tpm2-software/tpm2-tools/assets/39923435/37f121bc-9d34-4125-9bb9-f2accbe2b7d5)

Another example:

tpm2_getrandom 8 -> outputs characters...

![Screenshot from 2023-10-11 11-57-23](https://github.com/tpm2-software/tpm2-tools/assets/39923435/b374797d-990e-4799-8fa9-327adada359a)

**Comment by matIRL** [comment]
![Screenshot from 2023-10-11 12-00-03](https://github.com/tpm2-software/tpm2-tools/assets/39923435/43222402-386a-4976-9814-1e98beb329fc)

tpm2-tools installed from apt

**Comment by akorb** [comment]
Why do you think you don't have a TPM installed? The properties show the TPM vendor is Intel, which indicates a firmware TPM (no hardware). Therefore, the TPM is provided by the Intel Platform Trust Technology (Intel PTT).

**Comment by matIRL** [comment]
Andreas, thank you for the reply... I am embarrassed to report that I did not know there were such a thing as a fTPM.... I had a physical chip that I was testing with and I could not figure out why the TPM was still working when I pulled the chip off the motherboard.... doh!

-Mat
