### ISSUE TITLE
How to create Restricted Signing Key with tpm2_create ?

### ISSUE THREAD

**Issue by Krishap-s** [tpm2-software/tpm2-tools#3296]
Hi All,
I'm able to create restricted decrypt keys with `tpm2_create`

![image](https://github.com/tpm2-software/tpm2-tools/assets/49953521/c48e7fe9-64c7-4200-8308-120c2ef929fe)

But when creating a restricted signing keys with `tpm2_create`, I'm unable to do so

![image](https://github.com/tpm2-software/tpm2-tools/assets/49953521/0c872e80-1492-46ca-a99f-fd0c1c0c56dd)

Are we not supposed to create the keys through `tpm2_create` or am I missing some parameters when creating the keys ?

(Note: primary.ctx was made in the endorsement hierarchy) 

Thank You

**Comment by JuergenReppSIT** [comment]
For a restricted signing key you must specify the used scheme and also null for the symmetric algorithm. Example:
```
tpm2_create -C primary.ctx -Grsa2048:rsapss:null  \
    -a "fixedtpm|fixedparen|sensitivedataorigin|userwithauth|restricted|sign" -r priv -u pub
```

**Comment by Krishap-s** [comment]
Oh, that works. 
Thank You.
