### ISSUE TITLE
tpm2_quote --qualification hex string errors out

### ISSUE THREAD

**Issue by tklengyel** [tpm2-software/tpm2-tools#3300]
According to the documentation tpm2_quote's `--qualification` input is `HEX_STRING_OR_PATH`. When trying to specify a hex string as "hex:12345" tpm2_quote errors out with error code 1 and no output is displayed. This is observed with tpm2-tools from the Ubuntu 22.04 repository (5.2-1build1). Piping the hex value into a file and using that filename as the input works as a work-around but requires temporary files to be created, which may be undesired in some settings.

**Comment by JuergenReppSIT** [comment]
You can use a filename or a hexstring without the prefix "hex:". The length must be a multiple of two.
`12345` would produce an error `123456` (0x12 0x34 0x56) should work.
.

**Comment by tklengyel** [comment]
Thanks, indeed that was the issue. An update to the documentation to describe this would be helpful considering for other commands the hex is supposed to be given with 'hex:0x' prefix.
