### ISSUE TITLE
use libyaml

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#3312]
We need to stop creating YAML by hand, it's gotten too complicated to handle, it's time to just have the individual tools opt in to output. on_option handler a tool could add flag stating that it is requiring output, the on_run handler could pass an allocated libyaml document to it for the tool to populate, on success of on run the framework would dump it to stdout. the framework would always clear this out.

**Comment by shootingatshadow** [comment]
#3313 supersedes his

**Comment by williamcroberts** [comment]
#3313 supersedes his
