### ISSUE TITLE
Unable to create more than 16 NV indexes

### ISSUE THREAD

**Issue by akumarray008** [tpm2-software/tpm2-tools#3382]
Using tpm2-tools, I am exploring NV indexes creation using the available commands:
My tpm is already having 13 indexes defined and I can see it through
sudo tpm2_getcap handles-nv-index
<list of 13 NV handles>

After that I try to create 4 NV indexes
sudo tpm2_nvdefine -C o -s 32 
sudo tpm2_nvdefine -C o -s 32
sudo tpm2_nvdefine -C o -s 32
sudo tpm2_nvdefine -C o -s 32

The first three gets successfully created but the 4th tpm2_nvdefine fails. Even if I try to create 4 NV indexes of 1 byte each, still 4th one fails. In short, after 16(13 existing + 3 new) indexes, when I try to define space for 17th index, it gives me error of insufficient space for NV as below:
ERROR: Esys_NV_DefineSpace(0x14B) - tpm:error(2.0): insufficient space for NV allocation

Is there any property or variable defined for **how many NV indexes** we can create ? I went through spec as well but could not find anything related to this.

**Comment by AndreasFuchsTPM** [comment]
The amount of NV indices depends on the specific TPM you have.
Then it depends on the sizes of the NV idices.
The PC Client TPM profile specifies the minimum numbers somewhere: https://trustedcomputinggroup.org/wp-content/uploads/PC-Client-Specific-Platform-TPM-Profile-for-TPM-2p0-v1p05p_r14_pub.pdf
