### ISSUE TITLE
total :0 in use discrete tpm

### ISSUE THREAD

**Issue by lostzam** [tpm2-software/tpm2-tools#3387]
hi. I want to test TPM2 tools test units on a TPM device. I have downloaded TPM2 tools 5.7 via git on Fedora 39. How can I modify this command to achieve that?
./configure --enable-unit PATH=$PATH:/path/to/tpm2-abrmd:/path/to/tpm/sim/ibmtpm974/src
like this?
./configure --enable-unit PATH=$PATH:/path/to/tpm2-abrmd:/dev/tpm0

**Comment by AndreasFuchsTPM** [comment]
It is recommended to not use the test-suit against "real" TPMs.
The reason is that some of the tests are destructive or use commands not offered by physical TPMs.
So better do not use it...

**Comment by lostzam** [comment]
I am fully aware of and understand this issue. For research purposes, I definitely want to do this task. Please guide me on how to test these tests on real TPM.

**Comment by lostzam** [comment]
> It is recommended to not use the test-suit against "real" TPMs. The reason is that some of the tests are destructive or use commands not offered by physical TPMs. So better do not use it...

I am fully aware of and understand this issue. For research purposes, I definitely want to do this task. Please guide me on how to test these tests on real TPM.
