### ISSUE TITLE
Questions about tpm2_policyauthorizenv

### ISSUE THREAD

**Issue by sw1128** [tpm2-software/tpm2-tools#3390]
Hi!
I am conducting an experiment to calculate the value of PolicyB according to the TCG specification. I know that we should first calculate PolicyA, then use PolicyA to calculate nvIndexName, then use nvIndexName to calculate PolicyC, and finally use PolicyA and PolicyC to calculate PolicyB. But I'm facing some trouble now.
After confirming that PolicyA and nvIndexName are correct, when I calculate PolicyC using "tpm2_policyauthorizenv", I receive an error, after trying multiple methods but failing, I can only come to seek your help.
Here are my commands, execution sequence, and some images:
```
tpm2_startauthsession --policy-session -g sm3_256 -S session.ctx
tpm2_policysecret -S session.ctx -c 0x4000000b
tpm2_getpolicydigest -S session.ctx -o sm2policya.digest
tpm2_nvdefine 0x1c07f04 -C o -a 0x20f1008 -s 34 -g sm3_256 -L sm2policya.digest
dd if=/dev/zero bs=1 count=34 status=none | tpm2_nvwrite 0x1c07f04 -C 0x1c07f04 -P session:session.ctx -i-
```
I execute "hd sm2policya.digest", its hexadecimal value is the same as the TCG specification:
![image](https://github.com/tpm2-software/tpm2-tools/assets/65203923/4e9f1d99-0165-4b25-a8fd-3758a7d2e552)
![image](https://github.com/tpm2-software/tpm2-tools/assets/65203923/1a90661a-e7f3-4fe6-8fbb-571a3190fb68)
Then I execute "tpm2_nvreadpublic", the nvIndexName is the same as in the TCG specification:
![image](https://github.com/tpm2-software/tpm2-tools/assets/65203923/f3e9f294-bfcb-485a-a367-8d9bdd15fb90)
![image](https://github.com/tpm2-software/tpm2-tools/assets/65203923/8a0f382e-fa9e-4d31-968d-f84a4f2b110f)
Then I execute "tpm2_policyauthorizenv -S session.ctx -C 0x1c07f04 -L sm2policyc.digest 0x1c07f04", I received an error message(Some printed characters were manually added to the log by me): 
![image](https://github.com/tpm2-software/tpm2-tools/assets/65203923/8319b5b8-3189-4ae5-91dd-192142b30b65)
I don't know how to solve it, maybe some of my previous commands were incorrect. Can you help me, thank you very much!
If you have any further information that I need to provide, please reply.

**Comment by JuergenReppSIT** [comment]
If you replace:
`tpm2_policyauthorizenv -S session.ctx -C 0x1c07f04 -L sm2policyc.digest 0x1c07f04`
with:
`tpm2_startauthsession -g sha256 -S session2.ctx`
`tpm2_policyauthorizenv -S session2.ctx -C 0x1c07f04 -L sm2policyc.digest 0x1c07f04`
it should work.

**Comment by sw1128** [comment]
> If you replace: `tpm2_policyauthorizenv -S session.ctx -C 0x1c07f04 -L sm2policyc.digest 0x1c07f04` with: `tpm2_startauthsession -g sm3_256 -S session2.ctx` `tpm2_policyauthorizenv -S session2.ctx -C 0x1c07f04 -L sm2policyc.digest 0x1c07f04` it should work.

Thank you, you are right. When I remove "-- policy-session", it can work and correctly calculate policyC and policyB. But I encountered a new problem again, I tried to execute tpm2_activatecredential:
```
tpm2_activatecredential -c sm2_ak.ctx -C sm2_ek.ctx  -i cred.out  -o actcred.out -P "session:session.ctx"
```
I got an error message: A trial session cannot be used to authenticate, Please use an hmac or policy session.
It seems that the "--policy-session" needs to be added during "tpm2_startauthsession" to execute, but after adding it, it becomes the initial issue again. Is there a contradiction between them, and how should I solve this problem.
The following are all the commands I have executed. Please correct any errors.
```
tpm2_createek -c sm2_ek.ctx -G ecc_sm2 -u sm2_ek.pub
tpm2_createak -C sm2_ek.ctx -c sm2_ak.ctx -G ecc_sm2 -g sm3_256 -s sm2 -u sm2_ak.pub -r sm2_ak.priv -n sm2_ak.name
tpm2_flushcontext -lst
file_size=`stat --printf="%s" sm2_ak.name`
loaded_key_name=`cat sm2_ak.name | xxd -p -c $file_size`
echo "this is my secret" > file_input.data
tpm2_makecredential -u sm2_ek.pub -s file_input.data -n $loaded_key_name -o cred.out
tpm2_flushcontext -lst
tpm2_startauthsession -g sm3_256 -S session.ctx
tpm2_startauthsession -g sm3_256 -S session.ctx --policy-session
tpm2_policysecret -S session.ctx -c 0x4000000b
tpm2_getpolicydigest -o sm2policya.digest -S session.ctx
tpm2_policyauthorizenv -S session.ctx -C o -L sm2policyc.digest 0x1c07f04
tpm2_policyor -S session.ctx -L sm2policyb.digest sm3_256:sm2policya.digest,sm2policyc.digest
tpm2_activatecredential -c sm2_ak.ctx -C sm2_ek.ctx  -i cred.out  -o actcred.out -P "session:session.ctx"
```

**Comment by JuergenReppSIT** [comment]
Please check https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_startauthsession.1.md.
The description of `--policy-session` explains when a policy session and when a trial session is created.
Your first error did occur because you created a policy session an the content of the NV index was checked whether the hash alg and the policy digest was stored.

**Comment by sw1128** [comment]
> Please check https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_startauthsession.1.md. The description of `--policy-session` explains when a policy session and when a trial session is created. Your first error did occur because you created a policy session an the content of the NV index was checked whether the hash alg and the policy digest was stored.

I know that I need to splice "0012" and "sm2policya.digest" first, and then use the "tpm2_nvwrite" command. Now I have completed all the steps. Thank you for your help!
