### ISSUE TITLE
Preventing chained duplication using tpm2_policyduplicationselect

### ISSUE THREAD

**Issue by salrashid123** [tpm2-software/tpm2-tools#3391]
The default end-to-end example in [tpm2_duplicate](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_duplicate.1.md#example-2-as-an-end-to-end-example-the-following-will-transfer-an-rsa-key-generated-on-tpm-a-to-tpm-b) describes a way to Transfer from `A->B`

however, you can also repeat that process to further propagate the key from `a->b->c`.   

here's an example:
 
- [Chained duplication from A -> B -> C tpm2_policycommandcode](https://gist.github.com/salrashid123/13166ff8d579d55436a128087d5b43c7)

but what i really want is for the key to get used ONLY on B and prevent this chain and it seem [tpm2_policyduplicationselect](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_policyduplicationselect.1.md) is whats needed somewhere.

the procedure i came up with *seems* to work but it'd be great if someone can confirm it  ( if confirmed and there's interest in adding to to docs is warranted, i'll file the doc PR).

the thing i tried is replace [tpm2_policycommandcode](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_policycommandcode.1.md) with [tpm2_policyduplicationselect](https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_policyduplicationselect.1.md) (i'm not sure if that is legit to do or not and the failed duplication could well be for some other reason and not the one i'm after..)

here's the procedure:

- [Prevent Chained duplication from A -> B -> C using tpm2_policyduplicationselect](https://gist.github.com/salrashid123/8cf62917392c3a05b4a750ce3cfe4c6a)

**Comment by AndreasFuchsTPM** [comment]
That is exactly correct and it would be great to have this be added to documentation.
Maybe you can shrink it a bit (e.g. leaving out the counter example case for C) to still fit into the man page.
I'm looking forward to your PR.

**Comment by salrashid123** [comment]
a small side comment about having an example of policies on duplication:

you can use these restrictions to also clarify the controls around using TPMs for authentication to cloud provider from on-prem hardware or remote systems.

for example if you can control duplication of rsa or hmac keys, you enable some usecases for auth  i looked at earler:

* Google cloud uses  RSA service account keys for auth (see [gcp-adc-tpm](https://github.com/salrashid123/gcp-adc-tpm))
* Azure applications also uses RSA keys  (see [azsigner](https://github.com/salrashid123/azsigner))
* AWS uses HMAC (see [aws_hmac](https://github.com/salrashid123/aws_hmac) and [aws-tpm-process-credential](https://github.com/salrashid123/aws-tpm-process-credential))
