### ISSUE TITLE
total :0 in use discrete tpm

### ISSUE THREAD

**Issue by lostzam** [tpm2-software/tpm2-tools#3393]
hi. I want to test TPM2 tools test units on a TPM device. I have downloaded TPM2 tools 5.7 via git on Fedora 39. How can I modify this command to achieve that?
./configure --enable-unit PATH=$PATH:/path/to/tpm2-abrmd:/path/to/tpm/sim/ibmtpm974/src
like this?
./configure --enable-unit PATH=$PATH:/path/to/tpm2-abrmd:/dev/tpm0

I am aware that this task can be problematic for TPM. However, I need this test for research and development purposes.
please guide me.

**Comment by AndreasFuchsTPM** [comment]
I must advise against this. The tests do not work on a discrete TPM e.g. due to missing command support, etc.
