### ISSUE TITLE
I ran into a problem when compiling the latest version: pandoc: command not found

### ISSUE THREAD

**Issue by PunyHunter** [tpm2-software/tpm2-tools#3396]
My system can't install pandoc, is there any other way to fix this? configure has checked that my system does not have pandoc, why do it still use pandoc when compiling.I have no problem installing the old version of 3.X, is it only possible to use the old version?

 GEN      man/man1/tpm2_hmac.1
  GEN      man/man1/tpm2_incrementalselftest.1
  GEN      man/man1/tpm2_import.1
  GEN      man/man1/tpm2_makecredential.1
  GEN      man/man1/tpm2_nvdefine.1
  GEN      man/man1/tpm2_load.1
/bin/sh: line 44: pandoc: command not found
  GEN      man/man1/tpm2_loadexternal.1
/bin/sh: line 44: pandoc: command not found
  GEN      man/man1/tpm2_nvextend.1
  GEN      man/man1/tpm2_nvundefine.1
  GEN      man/man1/tpm2_nvreadpublic.1
  GEN      man/man1/tpm2_nvincrement.1
/bin/sh: line 44: pandoc: command not found
  GEN      man/man1/tpm2_nvwritelock.1
  GEN      man/man1/tpm2_nvwrite.1
  GEN      man/man1/tpm2_nvsetbits.1
  GEN      man/man1/tpm2_nvreadlock.1
  GEN      man/man1/tpm2_pcrallocate.1
  GEN      man/man1/tpm2_nvread.1
  GEN      man/man1/tpm2_pcrevent.1

**Comment by AndreasFuchsTPM** [comment]
Could you post your `config.log` file and the complete output of the `make -j1 V=1` call ?

Thanks !

**Comment by PunyHunter** [comment]
I work out it.I reinstall tss and tools and finish it.

**Comment by PunyHunter** [comment]
I work out it.I reinstall tss and tools and finish it.
