### ISSUE TITLE
tpm2_getcap -c 'handles-persistent' gives no output

### ISSUE THREAD

**Issue by brmcdot** [tpm2-software/tpm2-tools#3409]
Dear all,

tpm2_getcap -c 'handles-persistent'  gives no output.

The below commands also doesnt give any output:
# tpm2_getcap -c 'handles-loaded-session'
# tpm2_getcap -c 'handles-saved-session'
# tpm2_getcap -c 'handles-transient'

Pleas find details:
TPM 2.0 device used - OPTIGA™ T PM SLB 9670 
Processor -  Qualcomm 8074 Arm64 
Linux Kernel version - 5.4
tpm-tools  version -  3.4.1 
tpm-tss version - 2.0.1
tpm-aprmd version - 2.0.3
-------------------------------------------------------------------------------------------------------------------------------------
The "tpm2_getcap -c 'properies-fixed'" gives the following output:
**WARN: More data to be queried: capability: 0x6, property: 0x100**
TPM_PT_FAMILY_INDICATOR:
  as UINT32:                0x08322e3000
  as string:                "2.0"
TPM_PT_LEVEL:               0
TPM_PT_REVISION:            1.38
TPM_PT_DAY_OF_YEAR:         0x00000008
TPM_PT_YEAR:                0x000007e2
TPM_PT_MANUFACTURER:        0x49465800
TPM_PT_VENDOR_STRING_1:
  as UINT32:                0x534c4239
  as string:                "SLB9"
TPM_PT_VENDOR_STRING_2:
  as UINT32:                0x36373000
  as string:                "670"
TPM_PT_VENDOR_STRING_3:
  as UINT32:                0x00000000
  as string:                ""
TPM_PT_VENDOR_STRING_4:
  as UINT32:                0x00000000
  as string:                ""
TPM_PT_VENDOR_TPM_TYPE:     0x00000000
TPM_PT_FIRMWARE_VERSION_1:  0x00070055
TPM_PT_FIRMWARE_VERSION_2:  0x0011cb00
TPM_PT_INPUT_BUFFER:        0x00000400
TPM_PT_TPM2_HR_TRANSIENT_MIN:    0x00000004
TPM_PT_TPM2_HR_PERSISTENT_MIN:   0x00000007
TPM_PT_HR_LOADED_MIN:       0x00000003
TPM_PT_ACTIVE_SESSIONS_MAX: 0x00000040
TPM_PT_PCR_COUNT:           0x00000018
TPM_PT_PCR_SELECT_MIN:      0x00000003
TPM_PT_CONTEXT_GAP_MAX:     0x0000ffff
TPM_PT_NV_COUNTERS_MAX:     0x00000008
TPM_PT_NV_INDEX_MAX:        0x00000800
TPM_PT_MEMORY:              0x00000006
TPM_PT_CLOCK_UPDATE:        0x00004000
TPM_PT_CONTEXT_HASH:        0x0000000b
TPM_PT_CONTEXT_SYM:         0x00000006
TPM_PT_CONTEXT_SYM_SIZE:    0x00000080
TPM_PT_ORDERLY_COUNT:       0x000000ff
TPM_PT_MAX_COMMAND_SIZE:    0x0000058c
TPM_PT_MAX_RESPONSE_SIZE:   0x0000058c
TPM_PT_MAX_DIGEST:          0x00000020
TPM_PT_MAX_OBJECT_CONTEXT:  0x0000038f
TPM_PT_MAX_SESSION_CONTEXT: 0x000001ee
TPM_PT_PS_FAMILY_INDICATOR: 0x00000001
TPM_PT_PS_LEVEL:            0x00000000
TPM_PT_PS_REVISION:         0x00000103
TPM_PT_PS_DAY_OF_YEAR:      0x00000000
TPM_PT_PS_YEAR:             0x00000000
TPM_PT_SPLIT_MAX:           0x00000080
TPM_PT_TOTAL_COMMANDS:      0x00000061
TPM_PT_LIBRARY_COMMANDS:    0x00000060
TPM_PT_VENDOR_COMMANDS:     0x00000001
TPM_PT_NV_BUFFER_MAX:       0x00000300
TPM_PT_MODES: 0x00000001
  TPMA_MODES_FIPS_140_2

please do the needful at the earliest

regards,
Manjula

**Comment by AndreasFuchsTPM** [comment]
If
```
tpm2_getcap -c 'handles-loaded-session'
tpm2_getcap -c 'handles-saved-session'
tpm2_getcap -c 'handles-transient'
```
then there are currently no loaded / saved / transient objects inside the TPM.

**Comment by brmcdot** [comment]
Thanks for the support
