### ISSUE TITLE
Question: tpm2_createek can't replace persistent object

### ISSUE THREAD

**Issue by ChuanDou2021** [tpm2-software/tpm2-tools#3424]
When I execute the following command, it succeeds for the first time:
`
tpm2_createek -c 0x81010001 -u ek.pub
`

But the second attempt failed:

```
tpm2_createek -c 0x81010001 -u ek.pub
WARNING:esys:src/tss2-esys/api/Esys_EvictControl.c:330:Esys_EvictControl_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_EvictControl.c:114:Esys_EvictControl() Esys Finish ErrorCode (0x0000014c)
ERROR: Esys_EvictControl(0x14C) - tpm:error(2.0): NV Index or persistent object already defined
ERROR: Unable to run tpm2_createek
```

Excuse me, is this as expected? If I want to replace the object with **0x81010001** , I need to execute the following instruction sequence:

```
tpm2_createek -c ek.ctx -G rsa -u ek1.pub -f PEM
tpm2_evictcontrol -c 0x81000001
tpm2_evictcontrol -c ek.ctx 0x81000001
tpm2_readpublic -c 0x81000001 -o ek2.pub -f pem -Q
```

Excuse me, is this method of persisting EK certificates correct?

**Comment by JuergenReppSIT** [comment]
yes it's correct. You can't overwrite a existing persistent object with the tpm2_create... commands.

**Comment by ChuanDou2021** [comment]
I see, thanks!
