### ISSUE TITLE
Sealing a secret with PCR+PIN? (AND'ing policies)

### ISSUE THREAD

**Issue by jsommr** [tpm2-software/tpm2-tools#3437]
I have searched high and low for a way to seal a password with PCR + PIN. Every issue in here, all tpm2-tools bash scripts on GitHub and all articles I've been able to find only use PCR (or a password, but never both).

I've followed the [Disk Encryption guide](https://tpm2-software.github.io/2020/04/13/Disk-Encryption.html) for signed PCR values. What I have is attached below, and it only requires the PIN because tpm2_policypcr and tpm2_policyauthorize is discarded, since I can't include it in tpm2_policyauthvalue.

What am I doing wrong? How can I seal something with multiple policies? Ideally I can add a third policy that uses the static PCR 7 value.

```bash
tpm2_createprimary --hierarchy o --key-algorithm rsa --key-context prim.ctx --pcr-list sha1:0,7

tpm2_loadexternal -G rsa -C o -u /etc/systemd/tpm2-pcr-public-key-initrd.pem -c signing_key.ctx -n signing_key.name

tpm2_startauthsession -S session.ctx
tpm2_policypcr --session session.ctx --pcr-list sha1:11 --policy pcr.policy
tpm2_policyauthorize -S session.ctx -n signing_key.name -i pcr.policy --policy authorized_.policy
tpm2_policyauthvalue --session session.ctx --policy authorized.policy
tpm2_flushcontext session.ctx

tpm2_create -u auth_pcr_seal_key.pub -r auth_pcr_seal_key.priv -i- -C prim.ctx -L authorized.policy -p 1234 <<< "password"

# Only needed for multiple runs
tpm2_evictcontrol -C o -c 0x81010001

tpm2_load -C prim.ctx -u auth_pcr_seal_key.pub -r auth_pcr_seal_key.priv -n auth_pcr_seal_key.name -c auth_pcr_seal_key.ctx
tpm2_evictcontrol -c auth_pcr_seal_key.ctx 0x81010001 -C o

openssl dgst -sha256 -sign /etc/systemd/tpm2-pcr-private-key-initrd.pem -out pcr.signature pcr.policy

tpm2_loadexternal -G rsa -C o -u /etc/systemd/tpm2-pcr-public-key-initrd.pem -c signing_key.ctx -n signing_key.name
tpm2_verifysignature -c signing_key.ctx -g sha256 -m pcr.policy -s pcr.signature -t verification.tkt -f rsassa

tpm2_startauthsession --policy-session -S session.ctx
tpm2_policypcr -l sha1:11 --session session.ctx
tpm2_policyauthorize -S session.ctx -i pcr.policy -n signing_key.name -t verification.tkt
tpm2_policyauthvalue --session session.ctx
#tpm2_unseal -p session:session.ctx+1234 -c 0x81010001
tpm2_unseal -p 1234 -c 0x81010001
```

**Comment by JuergenReppSIT** [comment]
Your object `auth_pcr_seal_key.ctx` is created with the default attributes `"fixedtpm|fixedparent|userwithauth"`. `ùserwithauth` is set because the option `-p` is used (see man page `tpm2_create`). If you do not add `userwithauth` and use `-a "fixedtpm|fixedparent"` for `tpm2_create` only
`tpm2_unseal -p session:session.ctx+1234 -c 0x81010001` 
will work. For 
`tpm2_unseal -p 1234 -c 0x81010001`
 you should get an error.

**Comment by jsommr** [comment]
You just saved me days if not weeks of research. Thank you so much!
