### ISSUE TITLE
SRK interoperability issues between tpm2-tools and go-tpm-tools?

### ISSUE THREAD

**Issue by loicsikidi** [tpm2-software/tpm2-tools#3446]
Hi,

I'm facing what is seems to be an interoperability issue between `tpm2-tool` and `go-tpm`.

I'm expecting that in the same context, both tools should create the exact same **SRK key** but I observe a difference...

> [!NOTE]
> *I compare the SRK public key produced by each tool to check the uniqueness.*

You can find a summary of my experiments in this repository (if you wish to reproduce my behavior) :arrow_right: [srk-interoperability-issue](https://github.com/loicsikidi/srk-interoperability-issue/tree/main).

After a thorough investigation, it seems that the mismatch is due to a difference between templates used in `tpm2-tools` and in `go-tpm-tools`.

According to *TCG Credential Profile EK 2.0* `go-tpm-tools` filled `public.unique.buffer` with ***zeros*** which seems not being the case in `tpm2-tools` (at least the way I'm using it).

| Key type | TCG Spec | *go-tpm-tools* implementation |
| -------- | -------- | ------------------------------|
| RSA 2048 | [here](https://trustedcomputinggroup.org/wp-content/uploads/TCG-EK-Credential-Profile-V-2.5-R2_published.pdf#page=38) | [code](https://github.com/google/go-tpm-tools/blob/main/client/template.go#L46) |
| ECC P256 | [here](https://trustedcomputinggroup.org/wp-content/uploads/TCG-EK-Credential-Profile-V-2.5-R2_published.pdf#page=39) | [code](https://github.com/google/go-tpm-tools/blob/main/client/template.go#L54-L57) 

Is it possible to use the same kind of templates in `tpm2-tools`?

---

**tpm2-tool version**
```
tpm2 --version
tool="/nix/store/27v7gy3df98s586dx4gqxrp3lfz6p1wl-tpm2-tools-5.7/bin/tpm2" version="5.7" tctis="libtss2-tctildr" tcti- default=tcti-abrmd
``` 
---

Thank you in advance for your support :pray: .

KR,

PS: It's possible that I'm not using `tpm2-tool` the proper way :sweat_smile:.

**Comment by JuergenReppSIT** [comment]
The EK credential profile defines the initialization of public.unique.buffer for the EK. You can use the command `tpm2_createek`to create an EK. This command uses the template defined in the EK credential profile.
If you want to initialize the unique field of a primary key you can use the `--unique-data (-u)` parameter (see man page of tpm2_createprimary). Examples:
```
echo -n -e $(printf '\\x00%.0s' {1..256}) | tpm2_createprimary -Grsa -C o -c prim.ctx -u-
echo -n -e $(printf '\\x00%.0s' {1..64}) | tpm2_createprimary -Gecc -C o -c prim.ctx -u-
```

**Comment by loicsikidi** [comment]
I confirm that your answer works perfectly!

Now, I understand more precisely what is the goal of this flag :muscle:.  

I'm closing this *false positive* issue.

Thanks again @JuergenReppSIT !
