### ISSUE TITLE
tpm2_getmanufec: fix memory leak reported via asan

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#390]
Building with ASAN enabled results in:

```
$ tpm2_getmanufec -g rsa -O -N -U -E ECcert.bin -f test_ek.pub -S https://ekop.intel.com/ekcertservice/
WARN: TLS communication with the said TPM manufacturer server setup with SSL_NO_VERIFY!


=================================================================
==12207==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4b9408 in __interceptor_malloc (/home/wcrobert/workspace/tpm2.0-tools/tools/tpm2_getmanufec+0x4b9408)
    #1 0x7f23ab155e77 in CRYPTO_malloc (/lib/x86_64-linux-gnu/libcrypto.so.1.0.0+0x62e77)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x4b9408 in __interceptor_malloc (/home/wcrobert/workspace/tpm2.0-tools/tools/tpm2_getmanufec+0x4b9408)
    #1 0x7f23ab155e77 in CRYPTO_malloc (/lib/x86_64-linux-gnu/libcrypto.so.1.0.0+0x62e77)
```

**Comment by williamcroberts** [comment]
```
==29488==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4b96b8 in __interceptor_malloc (/home/wcrobert/workspace/tpm2-tools/tools/tpm2_getmanufec+0x4b96b8)
    #1 0x7f49c7990e77 in CRYPTO_malloc (/lib/x86_64-linux-gnu/libcrypto.so.1.0.0+0x62e77)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x4b96b8 in __interceptor_malloc (/home/wcrobert/workspace/tpm2-tools/tools/tpm2_getmanufec+0x4b96b8)
    #1 0x7f49c7990e77 in CRYPTO_malloc (/lib/x86_64-linux-gnu/libcrypto.so.1.0.0+0x62e77)

SUMMARY: AddressSanitizer: 80 byte(s) leaked in 2 allocation(s).
```
I think this is an issue in OpenSSL not my code. Maybe I can post to the mailing list and see if anyone of those guys know.

**Comment by williamcroberts** [comment]
I have looked into this for hours, since I can't find a solution, ill leave this open but take it off of 4.0

**Comment by joshuagl** [comment]
I'm seeing similar leaks in a lot of the tools in the ESAPI branch #1239. I think this is an issue that's resolved in newer OpenSSL, at least I can't reproduce on Fedora 29 (OpenSSL 1.1.1) and I've found some OpenSSL issues which seem relevant i.e. openssl/openssl#3128 & openssl/openssl#3033

Where does our Dockerfile live? I'd like to try updating the base OS to a version with newer OpenSSL and see if this issue persists.

**Comment by williamcroberts** [comment]
> -----Original Message-----
> From: Joshua Lock [mailto:notifications@github.com]
> Sent: Wednesday, December 19, 2018 8:06 AM
> To: tpm2-software/tpm2-tools <tpm2-tools@noreply.github.com>
> Cc: Roberts, William C <william.c.roberts@intel.com>; Author
> <author@noreply.github.com>
> Subject: Re: [tpm2-software/tpm2-tools] tpm2_getmanufec: fix memory leak
> reported via asan (#390)
> 
> I'm seeing similar leaks in a lot of the tools in the ESAPI branch #1239
> <https://github.com/tpm2-software/tpm2-tools/pull/1239> . I think this is an
> issue that's resolved in newer OpenSSL, at least I can't reproduce on Fedora 29
> (OpenSSL 1.1.1) and I've found some OpenSSL issues which seem relevant i.e.
> openssl/openssl#3128 <https://github.com/openssl/openssl/issues/3128>  &
> openssl/openssl#3033 <https://github.com/openssl/openssl/issues/3033>
> 
> Where does our Dockerfile live? I'd like to try updating the base OS to a version
> with newer OpenSSL and see if this issue persists.

I never created a docker file, I just modified an image and pushed it to Dockerhub directly.
That was probably a poor choice on my part.
