### ISSUE TITLE
Non-persistent AKs

### ISSUE THREAD

**Issue by srihanfb** [tpm2-software/tpm2-tools#421]
There doesn't seem to be an easy way to create a non-persistent AK under the EK. tpm2_create/load don't have an option to use PolicySecret for authorization. One way would be add that functionality to tpm2_create/load. An alternative approach might be to add an option to tpm2_getpubak to write the public and private portions to a file, and skip making the key persistent.

**Comment by williamcroberts** [comment]
I'm planning the next release, I am not 100% sure what you want here, any way you could submit prototype patches?

**Comment by williamcroberts** [comment]
@srihanfb 
Oh now that I am more familiar with these tools, yes I see what you mean. However, I don't see CreatePrimary returning the private portion of the AK.

I think what you would want is a -C option to save the context of the handle.

**Comment by srihanfb** [comment]
@williamcroberts : Tss2_Sys_Create returns both the public and private parts of the key. For the AK we're creating a key under the endorsement hierarchy so we need Create and not CreatePrimary. I you look at tpm_getpubak you'll see that it uses Tss2_Sys_Create.

**Comment by williamcroberts** [comment]
@srihanfb Yes I see that, so you also need the private key exported as well. Will add that in.

**Comment by srihanfb** [comment]
@williamcroberts : yeah, I think we need an option to export the private key. One possibility is to have an option that just generates the AK, but doesn't actually load it, and exports both the private and public key. That's how I've been using it internally.

We also need a corresponding tool to load a key into the TPM. The existing tpm_load.c isn't sufficient because it doesn't create a session. I can file a separate issue for that if you like.

**Comment by williamcroberts** [comment]
tpm2_load takes a session option via the `-S` option (currently, it will change).

Sessions are tricky, if your using an RM that isn't the latest ABRMD they won;t wonk with the tools. Abrmd currently has a bug preventing it from working with it too: https://github.com/tpm2-software/tpm2-abrmd/issues/317
