### ISSUE TITLE
Persistent objects can't be persistent by using a loaded transient object handle

### ISSUE THREAD

**Issue by martinezjavier** [tpm2-software/tpm2-tools#489]
This does work:

```
$ tpm2_createprimary -A o -g sha256 -G ecc -C primary.context

CreatePrimary Succeed ! Handle: 0x80ffffff

$ tpm2_evictcontrol -A o -c primary.context -S 0x81010000
persistentHandle: 0x81010000
```

But this doesn't:

```
$ tpm2_createprimary -A o -g sha256 -G ecc -C primary.context

CreatePrimary Succeed ! Handle: 0x80ffffff

$ tpm2_evictcontrol -A o -H 0x80ffffff -S 0x81010000
persistentHandle: 0x81010000
ERROR: EvictControl failed, error code: 0xa000a

$ tpm2_rc_decode 0xa000a
error layer
  hex: 0xa0000
  identifier: TSS2_TCTI_ERROR_LEVEL
  description: Error from the TCTI
base error code
  identifier: TSS2_BASE_RC_IO_ERROR
  description: IO failure
```

The reason why the former works is that [files_load_tpm_context_from_file()](https://github.com/01org/tpm2-tools/blob/master/lib/files.c#L236) has a side effect, since it also does a call to Tss2_Sys_ContextLoad().

IIUC this is just another case of the context load/save/flush issue that @williamcroberts and @idesai have been [discussing](https://github.com/01org/tpm2-tools/issues/484#issuecomment-328962870) in issue #484. But I still wanted it to have documented since is currently not working.

**Comment by electrickite** [comment]
@martinezjavier Were these commands run against a resource manager? Or against the TPM device directly?

**Comment by martinezjavier** [comment]
@electrickite the reported issue was when using the in-kernel resource manager (although the same error occurs with the tpm2-abrmd). Sending commands directly to the TPM will of course work because the session is alive in the TPM and never flushed.

The problem as I mentioned is that the session is flushed when the SAPI context is released. The corrct thing to do is to allow the tools to save and load sessions now that the tpm2-abrmd has support for it. With the in-kernel resource manager this may never work since is a design decision to flush all the sessions after the file descriptor is closed. 

* With tpm2-abrmd:
```
$ tpm2_createprimary -H o -g sha256 -G ecc -C primary.context
ObjectAttribute: 0x00030072

CreatePrimary Succeed ! Handle: 0x800000ff

$ tpm2_evictcontrol -A o -H 0x800000ff -S 0x81010000
persistentHandle: 0x81010000
ERROR: EvictControl failed, error code: 0x284

$ tpm2_rc_decode 0x284
error layer
  hex: 0x0
  identifier: TSS2_TPM_ERROR_LEVEL
  description: Error produced by the TPM
format 1 error code
  hex: 0x04
  identifier: TPM2_RC_VALUE
  description: value is out of range or is not correct for the context
handle
  hex:0x200
  identifier:  TPM2_RC_2
  description:  (null)

$ journalctl -xe | grep tpm2-abrmd
Nov 30 11:26:27 [machine name edited] tpm2-abrmd[18735]: No HandleMapEntry for vhandle: 0x800000ff
```

* With the in-kernel resource manager (/dev/tpmrm0):

```
$ tpm2_createprimary -H o -g sha256 -G ecc -C primary.context
ObjectAttribute: 0x00030072

CreatePrimary Succeed ! Handle: 0x80ffffff

$ tpm2_evictcontrol -A o -H 0x80ffffff -S 0x81010000
persistentHandle: 0x81010000
ERROR: EvictControl failed, error code: 0xa000a

$ tpm2_rc_decode 0xa000a
error layer
  hex: 0xa0000
  identifier: TSS2_TCTI_ERROR_LEVEL
  description: Error from the TCTI
base error code
  identifier: TSS2_BASE_RC_IO_ERROR
  description: IO failure
```
* Accessing the TPM directly:

```
$ tpm2_createprimary -H o -g sha256 -G ecc -C primary.context
ObjectAttribute: 0x00030072

CreatePrimary Succeed ! Handle: 0x80000000

$ tpm2_evictcontrol -A o -H 0x80000000 -S 0x81010000
persistentHandle: 0x81010000
```

**Comment by williamcroberts** [comment]
@martinezjavier I don't see anything to fix here, this seems by design, correct?

**Comment by martinezjavier** [comment]
@williamcroberts yes, this was an old issue I filled before we had even discussed the session context save/load support on tpm2-abrmd. I'm closing it now.
