### ISSUE TITLE
Change tpm2_nv{define,read,write,release,readlock} tools -a option to not require hex values

### ISSUE THREAD

**Issue by martinezjavier** [tpm2-software/tpm2-tools#512]
The tpm2 NV tools require the user to pass the hexadecimal values for the hierarchy authorization used, but we converted most tools to allow a pretty name instead (i.e: tpm2_evictcontrol).

**Comment by williamcroberts** [comment]
This kind of collides with #514. Some tools take `-A o` and `-A p` as options.
