### ISSUE TITLE
simple policy, add to required tools

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#532]
Find and modify tools to support simple policy sessions like tpm2_unseal. See #510 for a long discussion on this topic.

**Comment by idesai** [comment]
@williamcroberts @martinezjavier i would have liked the capability (with lua or natively built as runtime option in to RM) to carry over sessions between tools but i appreciate the discussion in #510. 
If this is the approach we are going with then the create policy tool should exist both as a tool and a library.
(1) A tool to create policies without creating objects should exist to define objects property.
(2) All tools that create objects should only need tpm2_createpolicy as a tool  
(3) All tools that satisfy the policy to use the object should use tpm2_createpolicy as a library
(4) Tools that both create and satisfy policy it should follow tpm2_createpolicy-->tpm2_<tool> 
      --> Eg. tpm2_create needs to satisfy policy for parent and tpm2_create also creates the object with a policy from tpm2_createpolicy tool

**Comment by williamcroberts** [comment]
@idesai you're saying you want full tpm2_createpolicy support not just simple policy support? ie anytihng that tpm2_createpolicy takes, others should take.. that makes sense, do I understand you correctly?

**Comment by idesai** [comment]
@williamcroberts correct.
While in-kernel-RM is choosing to implement it other wise, I am glad that @flihp user space tpm2-abrmd will support continuing sessions. I actually prefer to have this choice and flexibility than be restricted by the kernel/module IMHO.

**Comment by williamcroberts** [comment]
@idesai you can just put a service between the RM and the tools to hold the connection open, I actually have started a prototype for this... any interest?

**Comment by williamcroberts** [comment]
@idesai it's local, I can work on it today and get it working (i literary wrote it and hit compile, thats it).

Essentially, you start this service, and it creates a socket file wherever you tell it... Then you can use the device TCTI on the sock_file. It then sends commands over the actual TCTI until you kill it.

```
# Start sessiond in the background and create a socket file at /path/to/socket/tpm
# and talk to the in-kernel resource manager
tpm2_sessiond --tcti=device:/dev/tpmrm0 /path/to/socket/tpm &

# Now send tool requests via that socket file
tpm2_createpolicy --tcti=device:/path/to/socket/tpm <options for tool>

# keep using tools via that socket file (session is alive)
tpm2_<tool> --tcti=device:/path/to/socket/tpm <options for tool>

# kill tpm2_sessiond (causes RM flush)
kill %1
```

**Comment by idesai** [comment]
@williamcroberts cool. IIUC this is a possible solution to this ticket as a probable solution path for in kernel RM.
I actually prefer this to duplicating code in our tools which we don't have to with @flihp tpm2-abrmd.

**Comment by martinezjavier** [comment]
> keep using tools via that socket file (session is alive)
> tpm2_\<tool\> --tcti=device:/path/to/socket/tpm <options for tool>

@williamcroberts @idesai  I'm not sure I like this. Passing a socket path instead of a chardev looks to me like an abuse of the device TCTI (which in my opinion should be used to have direct access to the device, without any abstraction).

I would instead do it differently, I would leverage on the fact that we already have a socket TCTI, and have your tpm2_sessiond (maybe rename it to tpm2_spaced since that's the terminology used in the kernel: TPM spaces) expose a socket but with the same interface that's implemented by the TPM simulator, that AFAICT is just basically sending a marshaled command over a socket.

Then people not wanting to use the tpm2-abrmd but the kernel RM instead, and still want to have a "persistent" connection could just start an instance of your daemon choosing a port and use that with the socket TCTI. The daemon will just be a proxy to the character device.

So it would be something like this:

```
$ tpm2_sessiond --tcti-device:/dev/tpmrm0 --tcti-socket-address=127.0.0.1 --tcti-socket-port=9999

$ tpm2_createpolicy --tcti=socket:127.0.0.1:9999 <options for tool>

$ tpm2_<tool> --tcti=socket:127.0.0.1:9999 <options for tool>

$ kill tpm2_sessiond (causes RM flush)
```
I think that we still want to have createpolicy as a helper function (or a subset of it) so tools accessing directly to the device can have simple policies like tpm2_unseal and tpm2_nv{read,write}.

**Comment by martinezjavier** [comment]
If you really want to use a AF_UNIX instead of AF_INET socket, then the socket TCTI could be extended to support it.

**Comment by idesai** [comment]
@martinezjavier, also tools accessing device "directly" (/dev/tpm?) would simply call createpolicy to start the session and subsequent tools use it. I think we found that this worked in #510 discussion. Why then would you need the helper function?

**Comment by martinezjavier** [comment]
@idesai by directly I didn't meant /dev/tpm0 instead of /dev/tpmrm0 but directly opening,reading,writing the character device (if the kernel provides an abstraction or not is a different conversation but the device TCTI shouldn't care).

The session is not flushed with /dev/tpm0 and the context is not invalidated in that case because the TPM zones logic is not used there.

**Comment by martinezjavier** [comment]
So with the design I mentioned you will have 4 options:

1. Use device TCTI with /dev/tpm0 (tools can be chained, but most people won't use this option due the max transient objects limit)

2. Use device TCTI with /dev/tpmrm0 (tools can't be chained, but tools can create policies with a library/helper)

3. Use socket TCTI with tpm2_sessions -> /dev/tpmrm0 (tools can be chained thanks to the daemon keeping the fd opened)

4. Use abrmd TCTI (tools can be chained once the tpm2_abrmd is changed to not flush sessions on connection close)

**Comment by idesai** [comment]
@martinezjavier I like third option here.

PS: Third and Fourth can co-exist, in latter case just don't have to run tpm_sessionid

**Comment by williamcroberts** [comment]
@martinezjavier I like the concept of allowing the socket TCTI to support file path sockets.. I  think the sock_file will be easier than having to configure a socket interface every time...

**Comment by martinezjavier** [comment]
@idesai yes, the options are not mutually exclusive. All can be supported and users choose what fits their use case better.

@williamcroberts indeed, unix sock support can even be added to the simulator if someone is interested in that.

**Comment by williamcroberts** [comment]
@martinezjavier FYI looks like open fails on a sock file path ENXIO. So we will have to add unix socket support to socket tcti

**Comment by williamcroberts** [comment]
@martinezjavier  looks like the socket tcti is it's own protocol.. so I ended up hacking on device tcti to support domain sockets...

The tpm2_spaced can be found at:
https://github.com/williamcroberts/tpm2.0-tools/tree/spaced

The TSS changes can be found:
https://github.com/williamcroberts/TPM2.0-TSS/tree/unix-socket-support

It still needs a lot of cleanup, but it appears working... @idesai do you want to try some session work with it?

The test_tpm2_createprimary.sh test gives a weird, non-decoding error:
```
$ ./test/system/test_tpm2_createprimary.sh 
ERROR: 
CreatePrimary Failed ! ErrorCode: 0xc0902

tpm2_createprimary -Q -A $Atype -g $gAlg -G $GAlg -C context.out on line 58 failed: 1
$ tpm2_rc_decode 0xc0902
error layer
  hex: 0xc0000
failed to decode TPM_RC layer: 0xc0000
```

**Comment by martinezjavier** [comment]
@williamcroberts I still fail to understand why the daemon could not implement whatever protocol the socket TCTI is already using to communicate with the simulator. But I haven't looked at the socket TCTI implementation in detail so I trust your judgment.

**Comment by williamcroberts** [comment]
@martinezjavier it's not that it can't, it's just annoying. First off the socket protocol uses two sockets, one for tpm commands and one for platform commands. I solved that by disabling the platform command socket. It then seems to be sending some additional header, as what I received on the other side was weird. Rather than figure out what that weirdness was, I just used the device TCTI which doesn't do anything like that, it just sends things.

**Comment by martinezjavier** [comment]
@williamcroberts I see. Wonder if then we shouldn't rename the socket TCTI to simulator TCTI (since is really an ad-hoc TCTI for the simulator) and have a socket TCTI that's just a proxy to the device. But probably not worth the effort?

**Comment by williamcroberts** [comment]
@martinezjavier Yeah, the TCTIs are a mess. Maybe one day if we go through them we could do something like that...

**Comment by flihp** [comment]
This is definitely on my TODO list. The name "socket" TCTI is a lie and one that confused me when I inherited the project. This should be on the task list for "2.0" which I'm now starting. Thanks for the reminder.

**Comment by martinezjavier** [comment]
@williamcroberts I believe this issue can be closed now that you added PCR policy auth support for tpm2_nv{read,write}. Or can you think of other tool that needs the "simple" policy?

**Comment by martinezjavier** [comment]
Another ping to close this. I think there no tools remaining that need the simple policy logic.

**Comment by martinezjavier** [comment]
@williamcroberts usual ping to close this issue. Or do you think there's a reason to keep it open?

**Comment by williamcroberts** [comment]
Any tool that takes an auth session would need simple policy support. I need to audit all the tools and make sure that logic is present in them, correct?

**Comment by martinezjavier** [comment]
@williamcroberts Ok, I misunderstood and thought that the simple policy would only be an exception for some tools that were used for common uses cases (specifically tpm2_unseal and tpm2_nv{read,write}).

And that the rest of the tools should either support the `-S` option (when the tools could be chained on an execution environment that doesn't close the SAPI context) or support the new tpm2-abrmd option that allows to save and load session contexts.

But if you think that more tools should support the simple policy support, then is correct to keep this issue option. Sorry for the noise.

**Comment by williamcroberts** [comment]
@martinezjavier I just read through this to refresh my memory.

I am not 100% on a direction here, so discussion would be nice so we can all agree.

I am leaning towards:
1. We're done adding policy support to tools directly, and we keep it in nvread/write/unseal/createpolicy
2. As we add policy tools, ensure that createpolicy has that support so the usecases in 1 continue to work
3. We add tpm2_spaced as a tool that implements it's own TCTI (full dynamic TCTIs now, so that will be easy)
4. We document this, and actually start a wiki page on sessions, as they can be tricky.

Thoughts?

**Comment by martinezjavier** [comment]
@williamcroberts I absolutely agree with all your points.

I just wonder how we should call to such TCTI...

**Comment by williamcroberts** [comment]
@martinezjavier I am working with @flihp and @tstruk to see if it's possible to rename the existing tctis in the tss project since it's getting a major version bump. I am proposing socket goes to simulator and device goes to file. Then we can just create a true socket tcti that spaced can consume.

**Comment by martinezjavier** [comment]
Sounds good to me. I believe there's even an issue filled at tpm2-tss for the rename.

**Comment by williamcroberts** [comment]
Rather then implementing spaced, we're just going to have a proxy mode for tpm2_abrmd. So this will be behind that. So I am taking this off of the 4.0 release.

**Comment by williamcroberts** [comment]
Im taking this off the list of things to do. We won't remove simple policy support in existing tools, but our long term and more flexible goal will be using sessions and session tools to craft a session to be passed to other tools for usage, rather than doing all of this inside of a single tool.
