### ISSUE TITLE
Add bash-completion support for tpm2-tools

### ISSUE THREAD

**Issue by liuqun** [tpm2-software/tpm2-tools#589]
With the bash-completion support, developers can use "Tab" key to list available options "tpm2_xxx --options", which will made tpm2 sub-commands more friendly to newbies.

Example on Ubuntu/Debian:
```
sudo apt-get install bash-completion

tail ~/.bashrc
if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# Check 3rd-party tools that have already been supported by bash-completion
dpkg-query --listfiles bash-completion | sort
```

Homepage of Bash-Completion: http://bash-completion.alioth.debian.org
will give us more info on howto work with bash

**Comment by williamcroberts** [comment]
closed in #1100
