### ISSUE TITLE
stdout as yaml

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#634]
Make sure that ALL tools are doing tpm2_tooloutput in a yaml format and update all tests to not use grep/awk/sed to find values. Use here-doc python scripts that use PyYaml to validate/parse the yaml output for values.

**Comment by williamcroberts** [comment]
@martinezjavier you'll be glad to know that an output of just a number is valid YAML. It's a scalar type output. So those tools really don't need any changes, but the docs likely need to be updated to include the output formatting.

**Comment by martinezjavier** [comment]
@williamcroberts ah cool, I didn't know that.

**Comment by williamcroberts** [comment]
@martinezjavier I am looking at libyaml and thinking maybe the tools should just hand back a list of libyaml events that can be emitted, and let tpm2_tool.c handle output.

Right now, if a tool fails, it could fail with partial, incorrect output.... just a thought.

**Comment by martinezjavier** [comment]
@williamcroberts yeah, it's an interesting idea. I just don't know if it's going to make the output logic more complex...

**Comment by williamcroberts** [comment]
@martinezjavier not sure, and not in this release. We can do that later with no major version bump.
