### ISSUE TITLE
Fix abrmd version check for 3.0.1

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#687]

**Comment by williamcroberts** [comment]
I wonder how this has been working:
```
checking for SAPI... yes
checking for TCTI_DEV... yes
checking for TCTI_SOCK... yes
checking for TCTI_TABRMD... no
checking for CRYPTO... yes
checking for CURL... yes
```

**Comment by williamcroberts** [comment]
If I move it to the top level it works... something with that conditional check is wrong.

**Comment by williamcroberts** [comment]
Weird, this works just fine:
```
$ pkg-config --modversion tcti-tabrmd
1.2.0
```

**Comment by williamcroberts** [comment]
Oooh I had the version check in tabrmd, which if it's not the right version, just disables tabrmd. We need to think through what should happen if we detect tabrmd but it's not the right version...

**Comment by williamcroberts** [comment]
@tstruk @flihp @martinezjavier thoughts on this?

**Comment by flihp** [comment]
since it's the default it may be best to complain loudly unless it's explicitly disabled

**Comment by williamcroberts** [comment]
@flihp I don't really have a tethered version in the tools for tabrmd, it's really the coupling of abrmd and tss  that would bind it's version. In theory, one could have built an abrmd 1.0 on the tss for that time and have that running, and be using a different tss version with the tools.

With that said, not really sure if I should be checking version until I have an explicit need for an abrmd feature. I see the session work being one of these things.

**Comment by flihp** [comment]
Was just looking at the configure.ac and noticed there was no version check. Thanks for the clarification.

**Comment by flihp** [comment]
Your plan sounds like the right thing to do to me. All releases of the tabrmd up to now should be compatible with TSS versions < 2.0. I may have broken backward compatibility with the older 1.x releases due to some macros being fixed in the TSS. Probably a good time for me to tighten those up too I guess.

**Comment by martinezjavier** [comment]
@flihp @williamcroberts sounds good to me as well.

**Comment by williamcroberts** [comment]
Seems fixed on 3.X
