### ISSUE TITLE
friendly error messages

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#709]
Use the rc_decode logic to implement a tpm2_rc_to_err() routine similar to strerror()

**Comment by flihp** [comment]
how would you feel about turning this into a stable API / library? It's been on my "short list of things I never have time to implement" for ~6 months. The rc_decode tool was supposed to be the first step in this direction but so far it was the first and last.

I figure the minimum bar will be a function to get the layer that produced the RC and a string representation as well as the RC itself & string rep. Thoughts?

**Comment by williamcroberts** [comment]
By "stable API / library" do you mean in the tss project?

**Comment by flihp** [comment]
yes

**Comment by williamcroberts** [comment]
This has been issued as a PR to the tss project: https://github.com/tpm2-software/tpm2-tss/pull/737
