### ISSUE TITLE
test encryptdecrypt.sh

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#731]
passes under all conditions, fix.

**Comment by martinezjavier** [comment]
@williamcroberts can you please elaborate a little bit about this?

**Comment by martinezjavier** [comment]
@williamcroberts another ping on this one, it would be nice to have more details about what you think it's needed.

**Comment by williamcroberts** [comment]
The test script itself will pass even if it fails.
For instance, run it without abrmd and the simulator running, and it passes.
Likely the rc coming back is not getting propagated correctly.

**Comment by williamcroberts** [comment]
Fixed in #920
