### ISSUE TITLE
takeownership improvements

### ISSUE THREAD

**Issue by jeannegreulich** [tpm2-software/tpm2-tools#755]
The takeownership command only has the possibility of using the command line for setting up ownership.  This leaves the password in the history and viewable using ps.  Is it possible to add an option to use a file or an Environment variable?  We are trying to configure and manage alot of workstations and servers through an automated process.  Using an Environment variable that can be created for the process that runs the command would prevent it from being visable in ps and remove the environment variable  once the process is complete. (I am using v 2.1.1 currently)

**Comment by martinezjavier** [comment]
@jeannegreulich another option is to make the tool to read the password from the standard input, so you could do something like:

```
$ export $PASS=ownerpass
$ tpm2_takeownership -o- <<< $PASS
```

It won't leave any trace in neither the shell history (will show $PASS) nor ps output (will show tpm2_takeownership -o-).

That way you don't have to store anything on disk (which could be another attack vector if someone gets read access to the file where you stored the pass).

That approach may not work though if you want to set not only the owner auth but also the endorse and lockout passwords so maybe env vars as you suggest is more suitable.

**Comment by emmanuel-deloget** [comment]
If some env vars are used, should they be shared by all tools that might need them?

Moreover, tpm2_takeownership/tpm2_changeauth can be used to reset old passwords. Should these be stored in env vars as well (so 6 are needed)?

**Comment by williamcroberts** [comment]
History avoidance:
Most shells have HISTCONTROL set up to ignoreboth or ignoreshell. You could set that and then start your commands you want hidden with a space. Those commands then don't pop up in bash history.

The second issue you have is "password" in proctitle component of command output (ie shows up in ps aux). I'm not sure of any way to get bash not to call setproctitle() with the full command parameters expanded. You could, and we would take this on master as well (tpm2_takeownership was split into tpm2_clear and tpm2_changeauth on master). Starting on 3.0 in commit 5646feda0cb7125852d3768c98f119fd12390dcd The password has a new syntax like str:1234, or hex:aaBBcc. We could extend that to have `env:<variable-name>`, so you can instruct the tool to go looking into a particular env variable.

Then we don't have to deal with what env names are being used.

**Comment by williamcroberts** [comment]
If you provide patches to 2.X and master, I can cut you a new 2.X release if you would like.
