### ISSUE TITLE
Check that handle values passed to the tools are between a supported range

### ISSUE THREAD

**Issue by martinezjavier** [tpm2-software/tpm2-tools#880]
The TPM2 Handle space is split for the different TPM2 resources. For example, NV Index Areas start at 0x01000000, Transient Objects at 0x80000000 and Persistent Objects at 0x81000000. This means that each set of commands are only supposed to be used within the Handle range of the resources that they manage.

So for example TPM2_Unseal should only be used with handles from the Transient Objects range and TPM2_NV_Write for handles from the Persistent Objects range.

Right now any hex value can be used as a handle and even commands that will fails are sent to the TPM. This can be easily checked in the tools to avoid that.

**Comment by williamcroberts** [comment]
ESAPI port handles:
- transient objects
- persistent objects

However NV space is left, and also NV space would be nice if you could just do 1,2,3,4 and it just adds the 0x01000000 to it.

**Comment by idesai** [comment]
@williamcroberts, esapi doesn't check the range for NV; but does check for transient and persistent? Sounds like this should be checked in esapi.
However, there is more to parsing the handle value than it's relevance to a specific tool. What about reserved key handles and NV Indices. There is a TCG registry of these and the handle ranges **vary depending on which TCG TPM workgroup** we are talking about. I am not sure the tpm simulator restricts you on writing these ranges today -- I do know that Intel(r) PTT or Intel's integrated TPM does prevent you from writing NV Indices reserved for EK resulting in TPM error. This being one example. The full registry is here https://trustedcomputinggroup.org/wp-content/uploads/RegistryOfReservedTPM2HandlesAndLocalities_v1p1_pub.pdf

**Comment by williamcroberts** [comment]
Your over thinking this, its more like the top byte of the handle should be 0x1:
```C
#define TPM2_HT_NV_INDEX       ((TPM2_HT) 0x01) /* NV Index  assigned by the caller */
#define TPM2_HR_SHIFT             ((TPM2_HC) 24)
#define TPM2_HR_NV_INDEX          ((TPM2_HC) (TPM2_HT_NV_INDEX << TPM2_HR_SHIFT))
```

However, this begs the question, handles like 0, 1, 2 ... N (within range) should work too. I don't think when people want to write to index 0 that they have to write 0x01000000 (or something like that). So we probably want to say, if the top byte is set in the handle it must be 0x01, else if the top byte is all 0 set it to 1. This way things like 0 as input (pcr index 0), just internally turn into the right handle.
