### ISSUE TITLE
Wrong Markdown syntax for link markup

### ISSUE THREAD

**Issue by paulmenzel** [tpm2-software/tpm2-tools#883]
The syntax for the link on the [Wiki page](https://github.com/tpm2-software/tpm2-tools/wiki/Getting-Started#hello-world) is incorrect. Unfortunately I couldn’t find how to edit the page.

```
[https://github.com/tpm2-software/tpm2-tools/wiki/Dependency-Matrix](dependency matrix)
```

The URL is put last in Markdown.

**Comment by williamcroberts** [comment]
Fixed, thank you for noticing.
