### ISSUE TITLE
set heirarchy to owner by default for all tools, make -H optional.

### ISSUE THREAD

**Issue by kaccardi** [tpm2-software/tpm2-tools#892]
We could reduce complexity for the user by making some of these options that are required today optional, with a sane default. For heirarchy, could we set this by default to Owner, then remove the requirement that -H be specified on the command line.

**Comment by williamcroberts** [comment]
Yes I think this makes sense. We should however set all tools to default to the owner hierarchy. Currently the tools that have hierarchy defaults are set to platform, which was a poor choice on my part.

if/when we do this:
1. update all the tools to use a default platform of owner
2. update -H to generate on if not selected.

**Comment by kaccardi** [comment]
ok, I'll edit the title of this issue to encompass all the tools.

**Comment by joshuagl** [comment]
I've started working on this, I'd appreciate if someone could assign to me.

**Comment by williamcroberts** [comment]
@joshuagl I need to add you into one of the groups.
