### ISSUE TITLE
Tool to dump EK to file

### ISSUE THREAD

**Issue by srihanfb** [tpm2-software/tpm2-tools#910]
The existing tpm2_nvread.c only reads a particular NVRAM location. Since the size of the EK cert is greater than MAX_NV_BUFFER_SIZE, this ends up taking multiple reads. In addition the output from the command needs to be parsed to construct the certificate. 

It would be nice to have a standalone command that does the following:
- get the NVRAM area size using Tss2_Sys_NV_ReadPublic
- optionally use Tss2_Sys_GetCapability to get the max NV buffer reported by the TPM as TPM_PT_NV_BUFFER_MAX
- read the entire cert using calls to Tss2_Sys_NV_Read
- dump the EK cert to a file

**Comment by williamcroberts** [comment]
I'm pretty sure it already does:

1. Reads public to get size
    https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_nvread.c#L79

2. Gets the max buffer size via a getcap call:
    https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_nvread.c#L110

3. Calls read in a loop:
    https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_nvread.c#L127

4. Writes to a file or stdout:
    https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_nvread.c#L150

Maybe you're using an outdated version?

**Comment by srihanfb** [comment]
Sounds like we are indeed using an out-of-date version. Thanks for pointing that out!
