### ISSUE TITLE
Update Getting-Started document

### ISSUE THREAD

**Issue by martinezjavier** [tpm2-software/tpm2-tools#915]
[This document ](https://github.com/tpm2-software/tpm2-tools/wiki/Getting-Started) is kind of outdated, for example it claims that the tpm2-abrmd default TCTI is socket (to use with the simulator) but the default is to use the device TCTI.

**Comment by williamcroberts** [comment]
@martinezjavier can't you edit the wiki? If you can, just make the edit how you see fit.

**Comment by martinezjavier** [comment]
@williamcroberts no, I don't seem to have permissions to edit the wiki. In that page the footer say `Found a bug? File it in the bug tracker`, so that's what I did :smiley: 

Related, should these documents mention the commands that apply to the latest stable release or master? or both?

**Comment by williamcroberts** [comment]
@martinezjavier it's a bug that you don't have wiki-edit permissions IIU @flihp correctly.

I think we should just target master for now, eventually the commands and options should solidify... in due time.

**Comment by martinezjavier** [comment]
@williamcroberts Ok, thanks. I'll keep this open anyways until I've access to fix the doc.

**Comment by williamcroberts** [comment]
Seems fixed as I read the doc
