### ISSUE TITLE
Session handling

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#917]
As discussed on #904 

Session handling is a tad bit broken. Some tools need multiple auths for different things, and thus the current single input of `-S` is not sufficient. However, the password mechanism is already in place and should be re-used.

Since passwords have a mini-language, use that: `session:<file>`. This is going to be a big change, but reduces the number of arguments.

While at it, look at updating the option arguments to something like `--auth` versus `--password` where possible, perhaps re-arranging the short options as well.

**Comment by williamcroberts** [comment]
- [x] session:<file> is done in 53a6e1a6465a5ff

- [x] Long options are covered by option trackers for 4.0.

- [ ] need to go through and make sure the password handler can update the full auth session array.

**Comment by williamcroberts** [comment]
@idesai question, do we actually ever need to fully populate the auths array for most commands? What commands would actually need more than auth data? If we can get this list, it would be helpful to understand what impact this change would have overall.

**Comment by idesai** [comment]
I think these: ActivateCredential, Duplicate, Certify, FieldUpgradeStart, NVUndefineSpace, ObjectChangeAuth, NVChangeAuth
