### ISSUE TITLE
Create TLS client cert, where the secret never left the TPM

### ISSUE THREAD

**Issue by svenschwermer** [tpm2-software/tpm2-tools#928]
Hi!

My goal is to generate a secure TLS client certificate using a TPM. My idea is to generate the secret inside the TPM and make it never leave it. Using that secret, a signing request for the certificate is generated. The signing request should then be signed by a CA and the resulting certificate should be loaded back into the TPM.

I am using irtimmer/tpm2-pk11 to provide a PKCS#11 backend. However, it is not clear to me what sort of keys I need to generate (with tpm2-tools) that suit my requirements. I have read somewhere that the TPM will not allow signing external data with internal keys. Is that true? What choices do I have?

**Comment by svenschwermer** [comment]
Nevermind, now I have found out, that the secret key returned by `tpm2_create` is actually wrapped (i.e. encrypted) using the primary key (that never leaves the TPM).

**Comment by nsun1** [comment]
Hi Sven,

I am interested in creating the keys like you did, can you share the commands used to generate keys?

Thanks,
-Ning

**Comment by svenschwermer** [comment]
Hi Ning,

I took them from here: https://github.com/irtimmer/tpm2-pk11/wiki/Create-TPM-key

Sven

**Comment by nsun1** [comment]
Thanks Sven.

I have another scenario, if the pub and priv keys and certificate are generated by key server, but need to import the priv key to TPM and use the key to do signing in future, can tpm2 tools support that?

-Ning

**Comment by svenschwermer** [comment]
This is kind of unrelated, but if I understand the docs correctly, that's what `tpm2_loadexternal` is for.
