### ISSUE TITLE
make fails with error: tss2/tpm2.0.h: No such file or directory

### ISSUE THREAD

**Issue by dantpm** [tpm2-software/tpm2-tools#946]
make fails with error: tss2/tpm2.0.h: No such file or directory, as the result of using a file from tpm2-tss that no longer exists:

+ make
  CC       lib/files.o
lib/files.c:36:24: fatal error: tss2/tpm20.h: No such file or directory
compilation terminated.
Makefile:1945: recipe for target 'lib/files.o' failed
make: *** [lib/files.o] Error 1

**Comment by dantpm** [comment]
The usage of tpm20.h seems very widespread, so everything is basically broken:

lib/files.c:#include <tss2/tpm20.h>
lib/files.h:#include <tss2/tpm20.h>
lib/log.h:#include <tss2/tpm20.h>
lib/pcr.c:#include <tss2/tpm20.h>
lib/pcr.h:#include <tss2/tpm20.h>
lib/tpm2_alg_util.c:#include <tss2/tpm20.h>
lib/tpm2_alg_util.h:#include <tss2/tpm20.h>
lib/tpm2_attr_util.c:#include <tss2/tpm20.h>
lib/tpm2_attr_util.h:#include <tss2/tpm20.h>
lib/tpm2_convert.h:#include <tss2/tpm20.h>
lib/tpm2_ctx_mgmt.c:#include <tss2/tpm20.h>
lib/tpm2_errata.h:#include <tss2/tpm20.h>
lib/tpm2_error.c:#include <tss2/tpm20.h>
lib/tpm2_error.h:#include <tss2/tpm20.h>
lib/tpm2_hash.c:#include <tss2/tpm20.h>
lib/tpm2_hash.h:#include <tss2/tpm20.h>
lib/tpm2_header.h:#include <tss2/tpm20.h>
lib/tpm2_hierarchy.c:#include <tss2/tpm20.h>
lib/tpm2_hierarchy.h:#include <tss2/tpm20.h>
lib/tpm2_nv_util.h:#include <tss2/tpm20.h>
lib/tpm2_openssl.c:#include <tss2/tpm20.h>
lib/tpm2_openssl.h:#include <tss2/tpm20.h>
lib/tpm2_options.h:#include <tss2/tpm20.h>
lib/tpm2_password_util.c:#include <tss2/tpm20.h>
lib/tpm2_password_util.h:#include <tss2/tpm20.h>
lib/tpm2_policy.h:#include <tss2/tpm20.h>
lib/tpm2_session.c:#include <tss2/tpm20.h>
lib/tpm2_session.h:#include <tss2/tpm20.h>
lib/tpm2_tcti_ldr.c:#include <tss2/tpm20.h>
lib/tpm2_tcti_ldr.h:#include <tss2/tpm20.h>
lib/tpm2_util.h:#include <tss2/tpm20.h>
lib/tpm_kdfa.c:#include <tss2/tpm20.h>
lib/tpm_kdfa.h:#include <tss2/tpm20.h>
tools/tpm2_activatecredential.c:#include <tss2/tpm20.h>
tools/tpm2_certify.c:#include <tss2/tpm20.h>
tools/tpm2_changeauth.c:#include <tss2/tpm20.h>
tools/tpm2_createak.c:#include <tss2/tpm20.h>
tools/tpm2_create.c:#include <tss2/tpm20.h>
tools/tpm2_createek.c:#include <tss2/tpm20.h>
tools/tpm2_createpolicy.c:#include <tss2/tpm20.h>
tools/tpm2_createprimary.c:#include <tss2/tpm20.h>
tools/tpm2_dictionarylockout.c:#include <tss2/tpm20.h>
tools/tpm2_encryptdecrypt.c:#include <tss2/tpm20.h>
tools/tpm2_evictcontrol.c:#include <tss2/tpm20.h>
tools/tpm2_flushcontext.c:#include <tss2/tpm20.h>
tools/tpm2_getcap.c:#include <tss2/tpm20.h>
tools/tpm2_getmanufec.c:#include <tss2/tpm20.h>
tools/tpm2_getrandom.c:#include <tss2/tpm20.h>
tools/tpm2_hash.c:#include <tss2/tpm20.h>
tools/tpm2_hmac.c:#include <tss2/tpm20.h>
tools/tpm2_import.c:#include <tss2/tpm20.h>
tools/tpm2_listpersistent.c:#include <tss2/tpm20.h>
tools/tpm2_load.c:#include <tss2/tpm20.h>
tools/tpm2_loadexternal.c:#include <tss2/tpm20.h>
tools/tpm2_makecredential.c:#include <tss2/tpm20.h>
tools/tpm2_nvdefine.c:#include <tss2/tpm20.h>
tools/tpm2_nvlist.c:#include <tss2/tpm20.h>
tools/tpm2_nvread.c:#include <tss2/tpm20.h>
tools/tpm2_nvreadlock.c:#include <tss2/tpm20.h>
tools/tpm2_nvrelease.c:#include <tss2/tpm20.h>
tools/tpm2_nvwrite.c:#include <tss2/tpm20.h>
tools/tpm2_pcrevent.c:#include <tss2/tpm20.h>
tools/tpm2_pcrextend.c:#include <tss2/tpm20.h>
tools/tpm2_pcrlist.c:#include <tss2/tpm20.h>
tools/tpm2_policypcr.c:#include <tss2/tpm20.h>
tools/tpm2_policyrestart.c:#include <tss2/tpm20.h>
tools/tpm2_quote.c:#include <tss2/tpm20.h>
tools/tpm2_readpublic.c:#include <tss2/tpm20.h>
tools/tpm2_rsadecrypt.c:#include <tss2/tpm20.h>
tools/tpm2_rsaencrypt.c:#include <tss2/tpm20.h>
tools/tpm2_sign.c:#include <tss2/tpm20.h>
tools/tpm2_startauthsession.c:#include <tss2/tpm20.h>
tools/tpm2_tool.h:#include <tss2/tpm20.h>
tools/tpm2_unseal.c:#include <tss2/tpm20.h>
tools/tpm2_verifysignature.c:#include <tss2/tpm20.h>

**Comment by joshuagl** [comment]
We have three open pull requests that resolve build failures. All three are required for a successful build: #942, #944, #945

**Comment by dantpm** [comment]
Builds are working now, again, for the moment anyway.

**Comment by rguru379** [comment]
make  check-am
make[1]: Entering directory '~/tpm2-abrmd'
  CC       src/tabrmd.o
src/tabrmd.c:11:10: fatal error: tss2/tss2_tpm2_types.h: No such file or directory
   11 | #include <tss2/tss2_tpm2_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:2451: src/tabrmd.o] Error 1
make[1]: Leaving directory '~/tpm2-abrmd'
make: *** [Makefile:3964: check] Error 2


still getting above error.

**Comment by williamcroberts** [comment]
@rguru379 you're getting a different error (different file). What does `pkg-config --modversion tss2-sys` return?

It appears when tpm2-abrmd is building it's not finding the header files.

**Comment by rguru379** [comment]
Thanks, tpm2-tss was not installed properly and caused this issue.
