### ISSUE TITLE
Dictionary Attack Lockout not working as expected

### ISSUE THREAD

**Issue by munessparan** [tpm2-software/tpm2-tools#951]
I'm trying negative test by entering wrong password to reach max attempt and make sure it enter lockout state. Below are my steps:-
1 "./tpm_takeownership -o 1234 -e 1234 -l 1234"(initial takeownership password)
2. "./tpm_takeownership -o 1111 -e 1111 -l 1111 -O 9999 -E 9999 -L 9999" (I tried wrong pass for 50 times instead of 1234 to set lockout state)
3. "./tpm_takeownership o 1111 -e 1111 -l 1111 -O 1234 -E 1234 -1234" ( I tried this command by giving right password to check whether it already go into lockout state. But this command successfully set new password. As per my understanding this command should be failed because of max attempt reach to enter lockout)

I would like to know the command to check Lockout status and also to check max number of attempt allowed for Dictionary Attack Lockout.

**Comment by williamcroberts** [comment]
I think you can find it via:
```
tpm2_getcap  -c properties-variable
```

Via the properties:
```
TPM2_PT_LOCKOUT_COUNTER
TPM2_PT_MAX_AUTH_FAIL
```

Which can be looked up here:
https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-2-Structures-01.38.pdf

**Comment by williamcroberts** [comment]
Next time please ask generic questions on the mailing list.
