### ISSUE TITLE
tpm2-abrmdTss2_Sys_Startup returned unexpected RC: 0x144

### ISSUE THREAD

**Issue by mmelamud01** [tpm2-software/tpm2-tools#955]
Hi,

I am trying to start tpm2-abrmd and i am getting:

** (tpm2-abrmd:2485): WARNING **: Tss2_Sys_Startup returned unexpected RC: 0x144

** (tpm2-abrmd:2485): WARNING **: access_broker_sent_tpm_startup failed: 0x144

Any Ideas?

Thanks

**Comment by martinezjavier** [comment]
@mmelamud01 this is a known issue, please take a look to https://github.com/tpm2-software/tpm2-tss/issues/879. I'm closing this since is a duplicated issue and the problem seems to be in the SAPI layer.
