### ISSUE TITLE
HMAC Auth Support

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#956]
Support HMAC Authorizations.

The tools should be using HMAC for passwords implicitly when they are not tpm2_create like commands. In those instances, the password has to be send cleartext. One would probably want to couple a create with an encrypted session via tpm2_startauthsession

**Comment by JuergenReppSIT** [comment]
@celesteking  I have created a PR where the man page of tpm2_startauthsession is extended with examples how to fix this problem.
