### ISSUE TITLE
Make option short forms consistent

### ISSUE THREAD

**Issue by joshuagl** [tpm2-software/tpm2-tools#957]
Overhaul the options the tools take so that the short form of options are consistent and carry the same meaning across tools.

- [x] document current option flows on the wiki
  - https://github.com/tpm2-software/tpm2-tools/wiki/3.0.x-options-matrix
- [x] wiki page recording unified options and their short forms as an easy reference point for future tools to follow the patterns
- [ ] fix short options to unified and consistent options across tools
  - [ ] Fix tools
  - [ ] Update man pages

**Comment by williamcroberts** [comment]
Cool you got check boxes!

**Comment by joshuagl** [comment]
I found them in the markdown help when editing the wiki -- `[ ]`.

**Comment by williamcroberts** [comment]
I think `-A` is only for specifying attributes and all the `--pwdk`` type things are now `--auth-` so we want to get this matrix updated with those changes.

**Comment by williamcroberts** [comment]
So I see some patterns emerging:
1. Most tools specify auth values for 1 or more objects, my patch corrects those
2. Most tools specify hierarchy, my patch makes this clean, not sure if **-a** is best.
3. Most tools specify a parent and current object in either:
  * Handle
  * Context blob
4. Others I haven't looked at.

Maybe we can reign in item 3 by combining these concepts. What if we do
**-C** is always the parent object and **-c** is always the child object.
And then figure out if they specified a handle or a file blob. We can figure this out
and allow a way for coercion.
```
0x1234 - Treated as handle
foo.dat - Treated as context file
file:0x1234 - Treated as file
```
This would collapse 4 options from tools into 2.

We also may want to consider getting the options consistent not for ALL the tools, but for the groups as laid out by:
https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf

You'll see them organized by "Session Commands", "Object Commands", etc. I think we should be consistent in groups.

Thoughts?

**Comment by joshuagl** [comment]
Thanks for taking a look. I like all of your suggestions a lot. Keeping options consistent for groups of tools, as laid out in the commands spec, seems like a much more attainable goal and should certainly be the default position - nothing wrong with aiming higher than we can reach though.

I saw your patch land and have a WIP change to the wiki page to update the options following that change, will get it completed ASAP and start working on a proposal based on your suggestions above.

**Comment by joshuagl** [comment]
I've updated the wiki page documenting the current option use at "[3.0.x-options-matrix](https://github.com/tpm2-software/tpm2-tools/wiki/3.0.x-options-matrix)" and started a second page to document the proposals at "[Option unification](https://github.com/tpm2-software/tpm2-tools/wiki/Option-unification)", I imagine this becoming a living document of proposals that become patterns to follow as they are implemented. That page may make more sense simply being edited to document the agreed conventions/patterns.

I think this bug is probably going to end up spawning some child bugs to handle specific work items. The first work item I'd like to tackle is unifying the context object handling, as proposed by @williamcroberts, under -C for parent and -c for current/child with some logic to determine whether the object is a handle or file based on the format of the option argument.

**Comment by williamcroberts** [comment]
@joshuagl That sounds like a great start. I think the best way to do it is to keep identifying changes until the matrix stabilizes around something decent looking.

I'd like to stop thrashing downstream, so hopefully after this work, we can stop :-P

**Comment by joshuagl** [comment]
Agreed, it would be great to get the interfaces stable. I've filed #966 for the -C/-c handling.

**Comment by williamcroberts** [comment]
I updated the Matrix page to include the current conflict status:
https://github.com/tpm2-software/tpm2-tools/wiki/3.0.x-options-matrix

**Comment by joshuagl** [comment]
The original task list for this issue suggest that **-f** should always be **--format**. Any thoughts on that @williamcroberts? Several tools use it, though not in a manner that causes conflicts within a group, usually for a file of some sort, i.e. **--attest-file**, **--sig-file**, **--in-file**, etc.

If we're going to change this we should change it now, but is format significant enough to warrant a tools-wide short-option like **-c**/**-C**?

**Comment by williamcroberts** [comment]
Issue #1060 PR has -g to -G changes for tpm2_getmanufec/tpm2_createek/tpm2_createak
-g - should be name alg
-G - should be object type/alg

**Comment by joshuagl** [comment]
Spoke with @wcrobert and we agreed it wasn't a requirement to standardise **-f**/**--format** across all tools, instead we strive to ensure that options are consistent across groups.

**Comment by joshuagl** [comment]
We have a wiki page which records the state of the option unification effort: https://github.com/tpm2-software/tpm2-tools/wiki/Option-unification

However there's still some work to do on confliciting options within groups according to the tool `scrips/utils/analyze.py` -- I shall resolve those before closing this issue.
