### ISSUE TITLE
READ_STCLEAR and tpm2_nvread - how  to stop the following readings after the first read

### ISSUE THREAD

**Issue by strongerwill** [tpm2-software/tpm2-tools#960]
I have a question about how tpm2-tools to stop the following readings after the first read.

In tpm1.2, we can achieve this by using tpm_define and tpm_nvread. Specifically, 
1) in tpm_nvdefine, add READ_STCLEAR in permissions
2) tpm_nvread -i index -s 0

However, I did not find any similar mechanisms in tpm2-tools.
In particular, we can specify READ_STCLEAR in attribute 
tpm2_nvdefine -x <index> -a <auth> -s <size> -t **0x800A000A** -L policy.digest -P <pw>

Unfortunately, the tpm2_nvread with "-s 0" cannot stop the following reading. 

If I missed something, please let me know. Thx

**Comment by williamcroberts** [comment]
I don't understand what you mean, and the bug tracker is not for general support. Please send a message to our mailing list.

**Comment by strongerwill** [comment]
OK. I see.

BTW: I have fixed this issue using tpm2_nvreadlock.
