### ISSUE TITLE
Unify options to specify parent and current/child object

### ISSUE THREAD

**Issue by joshuagl** [tpm2-software/tpm2-tools#966]
When tools take a parent and/or current object we can simplify the options by having **-C** always be the parent object and **-c** the child object.
Rather than having a separate parameter for different object types (file vs. handle) we can reduce the number of related options from 4 to 2  by defining semantics for specifying handle vs. file and have a library function to determine the object type and load it appropriately.

For example:
```
0x1234 - specifies a handle
foo.dat - specifies a context file
file:0x1234 - specifies a file
```

**Comment by joshuagl** [comment]
I'm most of the way there on a series to implement this:
https://github.com/joshuagl/tpm2-tools/commits/issue966

A few actions remain:

- [ ] fix examples using modified commands in all manual pages
- [ ] ensure common fragment is correctly included in manual pages of modified commands
- [ ] figure out what to do where -c/-C are used in other tools, ensure -c/-C usage is at least consistent for tools of the same family
- [ ] fix the cases where tests are using awk rather than `yaml_get_kv`
  - [ ] createak.sh
  - [ ] createek.sh
  - [ ] getmanufec.sh
- [ ] ensure commit logs reflect the patches (type and function were renamed)

Whilst the patch is in review, or even after merge, I need to:
- [ ] update the options matrix wiki page

**Comment by williamcroberts** [comment]
@joshuagl I have a python script here that finds conflicting issues:
https://github.com/tpm2-software/tpm2-tools/pull/1007

**Comment by joshuagl** [comment]
Wiki page will be updated as part of #957, closing this ticket.
