### ISSUE TITLE
long option "--version" should print version, not verbose mode

### ISSUE THREAD

**Issue by liuqun** [tpm2-software/tpm2-tools#967]
Our document said that use "-v" for --version and "-V" for --verbose.

But the codes since 3.0 branch have a bug that treats "--version" as "-V" and print verbose messages instead of version str:
https://github.com/tpm2-software/tpm2-tools/blob/ae1f70ec7c1789293022e1e8d37d3dcf759d793b/lib/tpm2_options.c#L308-L362

The right code should be:
```
 struct option long_options [] = { 
     { "tcti",          required_argument, NULL, 'T' }, 
     { "help",          no_argument,       NULL, 'h' }, 
     { "verbose",       no_argument,       NULL, 'V' }, 
     { "quiet",         no_argument,       NULL, 'Q' }, 
     { "version",       no_argument,       NULL, 'v' }, 
     { "enable-errata", no_argument,       NULL, 'Z' }, 
 }; 

/* ... */

        case 'V':
            flags->verbose = 1;
            break;
        case 'v':
            show_version(argv[0]);
            rc = tpm2_option_code_stop;
            goto out;
            break;
```

**Comment by williamcroberts** [comment]
Considering that master and 3.X have the same issue:
https://github.com/tpm2-software/tpm2-tools/blob/master/lib/tpm2_options.c#L311
https://github.com/tpm2-software/tpm2-tools/blob/3.X/lib/tpm2_options.c#L300

The fix is likely fixing the documentation for each.

**Comment by williamcroberts** [comment]
Nevermind, I see the problem you describe now. It's the long options, not the short.
