### ISSUE TITLE
Test infrastructure changes to exercise tests on TPM directly (or without RM)

### ISSUE THREAD

**Issue by idesai** [tpm2-software/tpm2-tools#971]
1. Identify tools and tests that can run on the TPM directly 
2. Test infrastructure changes to be able to create tests to run directly on the TPM.

**Comment by flihp** [comment]
@liuqun provided a few patches to the tabrmd that used some of the the autotools parallel test harness features to accomplish this: https://www.gnu.org/software/automake/manual/html_node/Parallel-Test-Harness.html#Parallel-Test-Harness. It required some coordination across the autoconf and automake bits but it's pretty clean. Might be a good reference for this work.

**Comment by martinezjavier** [comment]
@flihp I think you meant @jiazhang0? I just want to see if I'm looking at the right commit, are you referring to this one https://github.com/tpm2-software/tpm2-abrmd/commit/64fc43a7b2353c6789ab746370ca89cd8cd9d615 ?

**Comment by flihp** [comment]
doh! Should have checked the history of https://github.com/tpm2-software/tpm2-abrmd/blob/master/scripts/int-hardware-setup.sh before posting. Thanks for the correction @martinezjavier, you got the commit right and everything.

**Comment by williamcroberts** [comment]
Not doing this
