### ISSUE TITLE
tpm2_loadexternal fails

### ISSUE THREAD

**Issue by fidget324** [tpm2-software/tpm2-tools#985]
I'm using tpm2-tools with tpm2-tss in QEMU to talk to the [swtpm](https://github.com/stefanberger/swtpm/tree/tpm2-preview.v2) emulator through a QEMU passthrough. Every tpm2-tools command I have tried so far has worked, except for `tpm2_loadexternal`, which gives me the following error:
```
$ echo "This is public" > public
$ sudo tpm2_loadexternal  --tcti device -a o -u public
WARNING:marshal:src/tss2-mu/tpm2b-types.c:355:
Tss2_MU_TPM2B_PUBLIC_Unmarshal() buffer_size: 20 with offset: 2 are insufficient for object of size 21608
ERROR: Error serializing public structure: 0x90006
```

**Comment by williamcroberts** [comment]
This was fixed in the tss, as you already found out:
**https://github.com/tpm2-software/tpm2-tss/issues/931**

**Comment by fidget324** [comment]
Hi @williamcroberts. That issue I reported in tpm2-tss was a separate issue. I reported this new issue after https://github.com/tpm2-software/tpm2-tss/issues/931 was fixed, and I tried to run `tpm2_loadexternal` with the patch. I think that the issue here is that `tpm2_loadexternal` expects a TPM2B_PUBLIC structure, but I was just providing a string. Nonetheless, it seems that tpm2_loadexternal doesn't perform any validation on the input to determine that the structure is valid. It just tries to unmarshal the input, and if the format of that input is not correct, it throws an error which is not very useful.

**Comment by williamcroberts** [comment]
via `-u` it is passed a file to what is supposed to be a TPM2B_PUBLIC structure. It just loads those bytes up as is and then passes it to Tss2_MU_TPM2B_PUBLIC_Unmarshal(). The Unmarshal itself should catch any issues, so perhaps unmarshal should be checking something better? Do you have the input file you were loading up that caused this?

The expanded MACRO code is:
```C
_Bool files_load_public(const char *path, TPM2B_PUBLIC *public) { \
    \
        UINT8 buffer[sizeof(*public)]; \
        UINT16 size = sizeof(buffer); \
        _Bool res = files_load_bytes_from_path(path, buffer, &size); \
        if (!res) { \
            return 0; \
        } \
        \
        size_t offset = 0; \
        TSS2_RC rc = Tss2_MU_TPM2B_PUBLIC_Unmarshal(buffer, size, &offset, public); \
        if (rc != ((TSS2_RC) 0)) { \
            _log(log_level_error, "/home/wcrobert/workspace/tpm2-tools/lib/files.c", 625, "Error serializing ""public"" structure: 0x%x", rc); \
            return 0; \
        } \
        \
        return rc == (0x000); \
    }
```

**Comment by fidget324** [comment]
I get the error by running:
```
$ echo "This is public" > public
$ sudo tpm2_loadexternal --tcti device -a o -u public
```
I'm on commit f783, which is recent as of less than 2 weeks ago.

I now understand that the format of the input argument is supposed to be a TPM2B_PUBLIC structure, which it clearly is not in my example. I think that the tool should emit a more useful error message for an invalid argument, e.g. something like "Argument needs to be a TPM2B_PUBLIC structure."

**Comment by williamcroberts** [comment]
@fidget324 hopefully PR https://github.com/tpm2-software/tpm2-tools/pull/1010 will help with understanding whats going on.
